### ISSUE TITLE
This is would be great to have on notebooks.azure.com

### ISSUE THREAD

**Issue by smortaz** [fastai/fastai#1]
hi - thanks for creating this awesome notebook - pls consider upload to https://notebooks.azure.com.

that way anyone can actually run it w/o installing anything.

thanks!

**Comment by rahulunair** [comment]
Well, if you just want to view the notebook, you could try:

http://nbviewer.jupyter.org/github/fastai/fastai/blob/master/tutorials/linalg_pytorch.ipynb

**Comment by jph00** [comment]
We may well do that once we release the course officially!
