### ISSUE TITLE
will you please tell me how to install fastai for win10?

### ISSUE THREAD

**Issue by chengerr** [fastai/fastai#1004]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by stas00** [comment]
For fastai 0.7.x installation see [here](http://forums.fast.ai/t/fastai-v0-install-issues-thread/24652) 

For fastai 1.0.x - in general fastai 1.x can't be used on windows until pytorch-1. is released on windows, but if you build your own then you can. Read posts here: https://forums.fast.ai/t/fastai-v1-install-issues-thread/24111/84

Good luck, @chengerr.
