### ISSUE TITLE
Test Failing for tests/test_vision_train.py

### ISSUE THREAD

**Issue by letsdodatascience** [fastai/fastai#1007]
**Describe the bug**

as of commit 6c70f9c4fa62277273ca2fc0ec69f14089b84b2d if one runs the testing suite, the tests fail. specifically ``` def test_image_data``` in ```tests/test_vision_train.py``` is failing.

<img width="1033" alt="screenshot 2018-10-29 at 20 50 02" src="https://user-images.githubusercontent.com/40219100/47667592-6474fd00-dbcc-11e8-864c-1e4513ec6008.png">

**To Reproduce**

run ```make coverage``` as of this (6c70f9c4fa62277273ca2fc0ec69f14089b84b2d) commit.
**Expected behavior**

All the tests should pass. the ```mean-0.2``` of the first image in the dataset is 0.1181. 

if we compare to 0.12 then all the tests pass. screenshot below. 
![image](https://user-images.githubusercontent.com/40219100/47667780-d77e7380-dbcc-11e8-9407-c132f0a3348f.png)

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
I don't have that issue when running the test locally. I think it's a random issue and you were out of luck, but the thresholds probably need to be a bit more loose. Will update.
