### ISSUE TITLE
Leading zeros are stripped from filename when using ImageClassifierData.from_csv 

### ISSUE THREAD

**Issue by asengsta** [fastai/fastai#1008]
**Describe the bug**
When using the ImageClassifierData.from_csv function the output training dataset file names - data.trn_ds.fnames are not correct if the file names in the CSV are zero padded numbers.  The function removes the zero padding when calling csv_source and parse_csv.  

I believe the issue comes from the parse_csv function when the fnames are generated (fnames = df.index.values)

**To Reproduce**
create a label.csv file where the filenames are all zero padded integers, create a dataset using ImageClassifierData.from_csv and inspect the returned data - data.trn_ds.fnames

**Expected behavior**

**Comment by sgugger** [comment]
Should be fixed in the latest version of master. Please reopen if it's not the case.
