### ISSUE TITLE
pil2tensor only work for 8bit images

### ISSUE THREAD

**Issue by kasparlund** [fastai/fastai#1018]
**Describe the bug**
pil2tensor only work for image with 8 bit channels and fails on images with one or more 16 bit channels

**To Reproduce**
The bug is reproduced in this notebook using af 16bit grayscale image
https://github.com/albertnaur/fastaiNotebooks/blob/master/pil2tensor/pil2TensorTests.ipynb

**Expected behavior**
pil2tensor should work for all PIL images

**Solution**
The following works for rgb and 16 bit grayscale and most likely all PIL.images:

def Pil2tensor(image)->TensorImage:
    “handles all numpy format”
    arr = torch.from_numpy(np.asarray(image))
    arr = arr.view(image.size[1], image.size[0], -1)
    return arr.permute(2,0,1)

The implementation is also negligibly faster in case the conversion to float in "open_image" is included in the measurements. It probably uses less memory because np.asarray creates a view on the internal PIL.image storage thus avoiding the image.tobytes() operation

**Comment by marii-moe** [comment]
torchvision.transforms.ToTensor handles Pil Images and might be worth a look here.

**Comment by albertnaur** [comment]
excellent idea. I will se if i can optimize the code further

**Comment by albertnaur** [comment]
ok torchvisions implementation is about 8 times slower - very strange

**Comment by albertnaur** [comment]
have done some more optimisation. The following delivers the same function but is 20% faster because the actual conversion is postpone until all dimension are in place:

#The proposed method - fastest
def allPil2tensor2(image:NPImage)->TensorImage:
    arr = np.asarray(image)
    if arr.ndim==2 : arr = np.expand_dims(arr,2) 
    #transpose width, height to height,width
    arr = np.transpose(arr, (1,0,2))
    #move channels to the first position
    arr = np.transpose(arr, (2, 1, 0))
    return torch.from_numpy(arr)

**Comment by jph00** [comment]
Thanks for the analysis of this! Any chance you could provide a PR, including a couple of tests of a variety of formats (you can either add some small images to the data/ folder, or create them in the test)?

**Comment by albertnaur** [comment]
sure will have a look at how you build the test. which image formats are relevant rgb, 16bit grayscale ?  ?

**Comment by kasparlund** [comment]
Will make the test so that it tries to convert any image you put in the test folder. the it easier to test conversion of any image for the users
