### ISSUE TITLE
Is 'model_path' deprecated?

### ISSUE THREAD

**Issue by whatrocks** [fastai/fastai#1025]
https://github.com/fastai/fastai/blob/b535463ac22d92db1f83b8bfe2330664ded76272/fastai/datasets.py#L39

Is the model_path in config.yml deprecated?

`'model_path': '~/.fastai/models'`

It seems that the models from learners are being stored within the image folders of the various datasets, rather than this path.

**Comment by sgugger** [comment]
It's for the pretrained models of fastai, not to save your own models.

**Comment by whatrocks** [comment]
Okay, thanks. I've seen the pre-trained models being downloaded to, for example, `/root/.torch/models/resnet34-333f7ec4.pt` rather than this `/.fastai/models` though?

**Comment by sgugger** [comment]
That's because it's a pytorch pretrained model, not a a fastai pretrained model ;)
