### ISSUE TITLE
Running Learner(data, model)  returns an error

### ISSUE THREAD

**Issue by enod** [fastai/fastai#1027]
**Describe the bug**

I'm trying to reproduce ULMFIT with fastai-1.0.x version. I have successfully prepared language model data using TextLMDataBunch and the model with get_language_model. 

When I run `Learner(data, model) ` it returns:
`RecursionError: maximum recursion depth exceeded.`

I have followed [this](https://mattjegan.com/Chasing-Pythons-Recursion-Limit/) to set it maximum but no luck so far. I'm wondering what causes this error and if there is any way to fix this? 

**To Reproduce**

```
from fastai.text import *
from fastai.torch_core import *
from fastai.text.data import *
from fastai.basic_train import Learner

trn_dataset = TextDataset('data/wiki/lang', create_mtd=TextMtd.IDS, name='trn')
val_dataset = TextDataset('data/wiki/lang', create_mtd=TextMtd.IDS, name='val')
data = TextLMDataBunch(train_dl=trn_dataset, valid_dl=val_dataset)

bs=64
bptt=70
sampled=True

itos = pickle.load(open('data/wiki/lang/' + 'tmp/itos.pkl', 'rb'))
vs = len(itos)
lm = get_language_model(vs, emb_sz, n_hid, n_layers, pad_token=0)
learn = Learner(data, lm)
```
**Expected behavior**

[Expected](https://docs.fast.ai/training.html#Basic-training-with-Learner) result should initialize Learner class.
**Screenshots**

**Additional context**

Vocabulary size is 30002. 
len(trn_dataset), len(val_dataset)  -> (997651, 110850).

**Comment by sgugger** [comment]
That is strange. Have you tested your datasets and your data object? Do trn_dataset[0]/val_dataset[0] return what is expected? Same for x,y = next(iter(data.train_dl))?
Lastly, what is you version of fastai?

**Comment by enod** [comment]
_Do trn_dataset[0]/val_dataset[0] return what is expected?_
Returns list of tuples containing token ids with a label=0.

_Same for x,y = next(iter(data.train_dl))?_
Returns `AttributeError: 'int' object has no attribute 'to'`  on
torch_core.py line 86:
`return b.to(device)`

_Lastly, what is you version of fastai?_
I've followed the installation guide of this repository. I believe it's the latest version.
```
conda install -c pytorch pytorch-nightly cuda80
conda install -c fastai torchvision-nightly
conda install -c fastai fastai
```

**Comment by sgugger** [comment]
Ah, I see now. All the `DataBunch` take dataloaders, you have to use the `.create` method if you want to pass datasets.
