### ISSUE TITLE
training cnn after get_transforms() throws RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. ...

### ISSUE THREAD

**Issue by discdiver** [fastai/fastai#1028]
**Describe the bug**

training cnn after ``` data = ImageDataBunch.from_folder(path, tfms=get_transforms()) ```

throws RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. ...

```
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/fastai/torch_core.py", line 91, in data_collate
    return torch.utils.data.dataloader.default_collate(to_data(batch))
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 232, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 232, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 209, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 341 and 311 in dimension 2 at /pytorch/aten/src/TH/generic/THTensorMoreMath.cpp:1317
```

**To Reproduce**

```

from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'
!pip install torch_nightly -f https://download.pytorch.org/whl/nightly/{accelerator}/torch_nightly.html
!pip install fastai

import torch
import fastai
from fastai import *
from fastai.vision import *

path = untar_data(URLs.DOGS)
path

data = ImageDataBunch.from_folder(path, tfms=get_transforms())

img,label = data.valid_ds[-1]
img.show(title=data.classes[label])

learner = create_cnn(data, models.resnet34, metrics=[accuracy])
learner.fit_one_cycle(1)
```

**Expected behavior**
Not throw an error.

**Additional context**
Attempted resolutions:

Based on this similar pytorch issue answer: https://github.com/marvis/pytorch-yolo2/issues/89#issuecomment-395284147 

I tried to crop the images in get_transforms with xtra_tfms

   data = ImageDataBunch.from_folder(path, tfms=get_transforms(xtra_tfms[crop(224)]))

That led to:
```
NameError                                 Traceback (most recent call last)
<ipython-input-16-4d8241a12972> in <module>()
----> 1 data = ImageDataBunch.from_folder(path, tfms=get_transforms(xtra_tfms[crop(224)]))
      2 img,label = data.valid_ds[-1]
      3 img.show(title=data.classes[label])

NameError: name 'xtra_tfms' is not defined
```

Source code makes it appear 'xtra_tfms' expects an integer.

Tried to fix by applying a crop to all images, but didn't see how to implement that function. Tried a few things:

```
crop(data, 224)
```
throws an error. As does

```
tfms = [crop(224)]
data = data.tfms
````

FastAI v1.0.18 
Pytorch 1.0.0.dev20181029
on Google Colab with GPU

**Comment by sgugger** [comment]
You have to specify a size in your method creating data.

**Comment by discdiver** [comment]
Thanks for the quick response @sgugger . I accidentally deleted size =2224 when I deleted   tfms=imagenet_norm because that was throwing an error.

**Comment by TomTurbo2016** [comment]
Hi, 

I get the very same error at "lern.fit(1)" when I run the code from "https://docs.fast.ai/vision.html".
I then changed "data = ImageDataBunch.from_folder(path)" to "data = ImageDataBunch.from_folder(path, size=224)" but the error stays.

Where do I have to put the "size"?

**Comment by agarnitin86** [comment]
Can someone clearly post the solution.. i am also facing same issue

**Comment by mrkieumy** [comment]
Hi, I don't know exactly what is your environment and your case. But in my case, after some days facing. I set the self.seen instead for index in the dataset.py as this: https://github.com/andy-yun/pytorch-0.4-yolov3/issues/55
Hope it helps you.
