### ISSUE TITLE
in nlp.py, get_rnn_classifer() is being called with an extra parameter, max_sl  In lm_rnn.py:

### ISSUE THREAD

**Issue by gsgbills** [fastai/fastai#103]
in nlp.py, get_rnn_classifer() is being called with an extra parameter, max_sl

In lm_rnn.py:
def get_rnn_classifer(bptt, max_seq, n_class, n_tok, emb_sz, n_hid, n_layers, pad_token, layers, drops, bidir=False,

In nlp.py:
        m = get_rnn_classifer(max_sl, bptt, self.bs, self.c, self.nt,

**Comment by jph00** [comment]
Should be fixed now. Please re-open if you still see a problem

**Comment by shirishr** [comment]
I don't think it is fixed. Let's review
In nlp.py **max_sl** still exists:
m = get_rnn_classifer(**max_sl**, bptt, self.bs, se

In lesson4-imdb.ipynb we are passing a value of 1500 in the 6th cell in section Sentiment which seems to be for max_sl.
What is max_sl??
