### ISSUE TITLE
Return type of create_cnn should be ClassificationLearner

### ISSUE THREAD

**Issue by twosatnams** [fastai/fastai#1032]
https://github.com/fastai/fastai/blob/b2c214c1ca568ef72da2e0027598e2034a0ee05c/fastai/vision/learner.py#L55

Currently, it says None

**Comment by jph00** [comment]
That's true! Would you like to do a PR to fix that?

**Comment by sgugger** [comment]
Closing this now, as it's fixed. Thanks for flagging!
