### ISSUE TITLE
language model training failing due to ram exhaustion

### ISSUE THREAD

**Issue by akanshajainn** [fastai/fastai#1051]
I am training a french language model on latest french wikipedia. Having chunk size = 30000, with hardware config as 30 GB RAM, 4 cpu cores, 16 GB V100 GPU. The code fails with the following error
```0
1
2
3
4
5
6
7
A process in the process pool was terminated abruptly while the future was running or pending.```
so it failed on 7th batch of chunk. 
I was following the imdb.ipynb script only, error comes on the tokenisation part which is 
```     tok_trn, trn_labels = get_all(df_trn, 0) ```
I would like to know what are the resources requiremnts to train a language model from scratch on wikipedia. What are the other ways to run it? Any changes in the code which can help ? Anybody tried or successfully trained a language model from scratch for any other language using fastai? 

PS. When is model Zoo releasing ?

**Comment by sgugger** [comment]
For a huge amount of data, you probably need to modify the existing code to save the processed tokens as they go instead of accumulating them in RAM. Closing this here as it should be discussed on the [forum](https://forums.fast.ai/).
