### ISSUE TITLE
ImageDataBunch.from_df does not accept Paths

### ISSUE THREAD

**Issue by EdwardJRoss** [fastai/fastai#1060]
**Describe the bug**

Version 1.0.18 of fastai having `Path` objects in the `fn_col` of `ImageDataBunch.from_df` causes an error.

**To Reproduce**

```
from fastai import *
from fastai.vision import *
ImageDataBunch.from_df('.', pd.DataFrame([[Path('path'), 1]]))
```
This causes
```TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U40') dtype('<U40') dtype('<U40')```

This is caused by line 34 of `data_block.py` in `_df_to_fns_labels`:

        fnames = df.iloc[:,fn_col].str.lstrip()

This returns a column of NaNs because they're not strings.

**Expected behavior**

I would expect this to return an ImageDataBunch equivalent to:
```
ImageDataBunch.from_df('.', pd.DataFrame([['path', 1]]))
```

One potential fix would be to change the offending line to:

    fnames = df.iloc[:,fn_col].apply(str).str.lstrip()

**Comment by noklam** [comment]
I think a simpler solution is to read the df outside of the argument,  make it a str first or whatever processing you need to do.

Can you just do this transformation outside and just pass the processed df?

**Comment by EdwardJRoss** [comment]
Sorry, I don't follow where you're suggesting to make the change.

The root problem is that `Path` is ubiquitous in fastai, and it's really hard for end users to work out what they did wrong from this error.

Some possible fixes:
1. Allow `Path` by changing the code in `_df_to_fns_labels`
2. Allow `Path` by changing the code in `ImageDataBunch.from_df` (and potentially any other callers of `_df_to_fns_labels`)
3. Disallow `Path` with an assertion in `ImageDataBunch.from_df`, giving clear feedback that you need to pass strings (or something that `pandas.Series.str` can handle)
4. Dissalow `Path` with an assertion in `_df_to_fns_labels`, giving clear feedback that you need to pass strings (or something that `pandas.Series.str` can handle)

I'm not sure what sort of fix best fits here, but something like this would be really helpful.

**Comment by sgugger** [comment]
Should be fixed now. Note that using path objects in your dataframe is incompatible with suffix not None (path objects have the extension in any case).
