### ISSUE TITLE
Fix dead link in CONTRIBUTE.md

### ISSUE THREAD

**Issue by noklam** [fastai/fastai#1066]
**Describe the bug**

Page not found

**To Reproduce**

https://github.com/fastai/fastai/blob/master/docs/style.md
**Expected behavior**

Those link should point to the right location? I can't find the code style guide. I think it probably should point to https://docs.fast.ai/dev_style.html instead?

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
Should be fixed now.
