### ISSUE TITLE
ModuleNotFoundError: No module named 'fastai.widgets'

### ISSUE THREAD

**Issue by ravilkashyap** [fastai/fastai#1076]
When trying to use FileDeleter from the course v3, when importing fastai.widgets, it throws up error -
 `ModuleNotFoundError: No module named 'fastai.widgets'`

**Comment by sgugger** [comment]
You need to update your version of the library. Please look at the [forum](https://forums.fast.ai/) for more help.

**Comment by yuxx1006** [comment]
anyone resolves this?
