### ISSUE TITLE
List of tensors as target not supported anymore?

### ISSUE THREAD

**Issue by davidpapazian** [fastai/fastai#1083]
Hello,
Callbacks during training assume target is a tensor when calling last_target.size(0) in callback.py
In previous versions, we didn't have this problem.
Does it mean that tensor list as target will not be supported anymore?
Thanks

**Comment by sgugger** [comment]
Hi there, it's only for computation of metrics such as accuracy that this is assumed (to get the batch size). This would bug anyway if you have a target that is a list as you'd need to implement your custom metric. List of targets as tensors is fully supported otherwise.

**Comment by sgugger** [comment]
Apologies, I didn't realize you had a custom metric function. Can you try [this commit](https://github.com/fastai/fastai/commit/2ae9b4dc5a0fbf7d628e7866470ee53b0b882225) and see if it fixes your problem?

**Comment by davidpapazian** [comment]
No problem. I wasn't very clear.
It works perfectly with all my metrics.
Thank you very much!
