### ISSUE TITLE
Is ClassificationLearner.predict too slow for production?

### ISSUE THREAD

**Issue by devforfu** [fastai/fastai#1086]
**Describe the bug**

The `ClassificationLearner.predict` prediction method is a bit too slow.

_I am sorry if the question is too long, just wanted to provide an exact context of my issue. I can run profiling in the Notebook if you would like._

> Update: [here is a link](http://142.93.123.151) to droplet with the deployed app so you can test yourself.

**To Reproduce**

I am building [a simple app](https://github.com/devforfu/quick_draw_api) that exposes ResNet50 model trained on Quick Draw Doodles dataset via web UI. And, this methods takes a few seconds to complete:
```python
def predict_image(data):
    base64str, slow = data['imgBase64'], data['slow']
    if slow:
        print('Slow execution')
        return predict_image_from_base64_slow(base64str)
    return predict_image_from_base64_fast(base64str)

def predict_image_from_base64_slow(base64str):
    _, content = base64str.split(',')
    decoded = base64.b64decode(content)
    image = open_image(BytesIO(decoded))
    _, _, losses = learn.predict(image)
    return create_predictions(losses)

def predict_image_from_base64_fast(base64str):
    _, content = base64str.split(',')
    decoded = base64.b64decode(content)
    image = open_image(BytesIO(decoded))
    classes, losses = predictor.predict_top(image.data, k=10)
    return list(zip(classes.tolist(), losses.tolist()))
```
I think that probably something goes wrong in `ClassificationLearner.predict` method, where it calls `pred_batch` method. The reason why I think so, is that my own class prediction class works a bit faster. You can reprouce my experiment using the repo I've shared and running the command:
```bash
$ python app.py serve
```
Also, I am making an inference on CPU, setting env variable `CUDA_VISIBLE_DEVICES` to empty value.

**Expected behavior**

I think that it should be computed faster because this thing seems to work faster:
```python
@dataclass
class Predictor:
    learn: Learner
    mean: FloatTensor
    std: FloatTensor

    def __post_init__(self):
        device = self.learn.data.device
        self.learn.model.eval()
        self.classes = np.array(self.learn.data.classes)
        self.mean, self.std = [torch.tensor(x).to(device) for x in (self.mean, self.std)]

    def predict(self, x):
        out = self.predict_logits(x)
        best_index = out.argmax()
        return self.learn.data.classes[best_index]

    def predict_top(self, x, k=1):
        out = self.predict_logits(x)
        np_out = out.flatten().detach().numpy()
        top_idx = np_out.argsort()[-k:]
        top_losses = np_out[top_idx]
        top_classes = self.classes[top_idx]
        return top_classes[::-1], top_losses[::-1]

    def predict_logits(self, x):
        x = self._to_tensor(x)
        out = self.learn.model(x[None])
        return out

    def _to_tensor(self, x):
        if isinstance(x, str):
            data = open_image(x).data
        elif isinstance(x, PILImage.Image):
            data = to_tensor(x)
        else:
            data = torch.tensor(x)
        x = data.to(self.learn.data.device)
        x = normalize(x, self.mean, self.std)
        return x
```
However, probably I am just doing something in a wrong way. Would be glad to hear your advice how to organize this thing better.

**Additional context**
The packages required to run UI locally:
```text
Pillow
uvicorn
starlette
aiohttp
aiofiles
jinja2
fastai==1.0.19
```

**Comment by sgugger** [comment]
Is this still happening with our latest refactors?

**Comment by sgugger** [comment]
Closing this since it's been a while with no news, please reopen if needed.

**Comment by devforfu** [comment]
@sgugger Yes, this thing was tested against the quite old version of the library so I believe that now everything should be fine.
