### ISSUE TITLE
Bug on fbeta

### ISSUE THREAD

**Issue by ymittal23** [fastai/fastai#1092]
**Describe the bug**

Using fbeta matric in image classification give a runtime error. The error comes when the first epoch gets completed. Other people also got the same bug. See [https://forums.fast.ai/t/bug-on-fbeta/29416](url) 
[https://forums.fast.ai/t/lesson-1-chat/27332/1203?u=ymittal23](url)
If other matrices like accuracy are used code works fine.

**To Reproduce**

**Expected behavior**

It should complete all epochs while showing f score on each epoch.
**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
This isn't a bug: `fbeta` is intended for multiclassification problems where the target are one-hot encoded, which isn't the case in the example you give. If you really want to use it there, you'll have to modify the current implementation to add that one-hot encoding step.
