### ISSUE TITLE
Confusion matrix started using float after fast.ai library update from 1.0.11 to 1.0.19

### ISSUE THREAD

**Issue by odysseus0** [fastai/fastai#1094]
**Describe the bug**
Confusion matrix started using float instead of int after updating the library from 1.0.11 to 1.0.19. This makes the matrix rather unreadable. Here is a screenshot:

<img width="742" alt="image" src="https://user-images.githubusercontent.com/8635094/48064880-1bdcc580-e204-11e8-8e89-a0d8e89fc725.png">

**To Reproduce**

Update the fast.ai library to 1.0.19.

Update the course-v3 to the latest using `git pull` and then run through the notebook to reach the confusion matrix part.

**Comment by sgugger** [comment]
You can pass an `norm_dec` argument to show less digits.

**Comment by odysseus0** [comment]
Thank you for the tip. But would you agree that displaying the number in int format by default would be a much more preferable option?

**Comment by sgugger** [comment]
Oh, see what you mean! It should only use that argument when using `normalize=True`, will push a fix, otherwise show ints.

**Comment by MicPie** [comment]
Sorry, this was my fault.

I will check it and propose a fix (if still needed).

**Comment by sgugger** [comment]
No need, I've done it [here](https://github.com/fastai/fastai/commit/c00d576cba1e3970959f1f71cc3ca707473aa276) ;)
Thanks for offering though!

**Comment by MicPie** [comment]
This should fix it:

“““
for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
             plt.text(j, i, cm[i, j], horizontalalignment="center", color="white" if cm[i, j] > thresh else "black")
             if normalize: plt.text(j, i, f'{cm[i, j]:.{norm_dec}f}', horizontalalignment="center", color="white" if cm[i, j] > thresh else "black")
“““

I will test and get back to you.

Sorry for the inconvenience!
