### ISSUE TITLE
can't set batch size with datablock API

### ISSUE THREAD

**Issue by 10zinten** [fastai/fastai#1099]
https://github.com/fastai/fastai/blob/bfd34a61fb7fa75a7a721078af471dcf8d71f708/fastai/vision/data.py#L60

Here is my usage of datablock API and I wanted to set bs=32. But with following method its still using the default bs=64 in in ImageDataBunch.create()
```
data = (ProteinImageList.from_folder(DATA, train_fns, TRAIN)
      .label_from_csv('train.csv', sep=' ', folder='train-comb')
      .random_split_by_pct(0.2)
      .add_test(ItemList(get_files(test_fns, TEST)))
      .datasets(ProtienImageMultiDataset)
      .transform(get_transforms(max_warp=None, flip_vert=True), size=sz)
      .databunch(bs=bs))
```

Is there a way to set bs with datablock API, please let me know, thanks ;)

**Comment by sgugger** [comment]
Mmmm, what version of the library are you using? I just tested some similar code and the batch size seemed to be set properly with `.databunch(bs=32)`.

**Comment by 10zinten** [comment]
I am using 1.0.20, the developer version

**Comment by sgugger** [comment]
To check the batch size, type `data.train_dl.batch_size`. Let me know by reopening this issue if it doesn't give you the expected result.
