### ISSUE TITLE
InputList.label_from_df casting label to numpy array

### ISSUE THREAD

**Issue by sevenfx** [fastai/fastai#1110]
**Describe the bug**
`data_block.InputList.label_from_df` seems to be casting the labels as numpy arrays, causing issues when turning a `SplitData` into a `ImageClassificationDataset`

```
LabelList (1 items)
[[PosixPath('test_file.png') array('test', dtype=object)]]
Path: .
```
when it is supposed to look like 
```
LabelList (1 items)
[[PosixPath('test_file.png') 'test']]
Path: .
```

**To Reproduce**
[gist with reproduction steps
](https://gist.github.com/sevenfx/73635a99e7d93a77efca134cb7c08545)
(I ran into this issue with real data, I simplified the steps for the repro steps)

* Create an `ImageFileList` (I got the same problem when using a vanilla `InputList`)
* Call `label_from_df` on that object with a valid dataframe
* Notice that the label in the resulting `LabelList` is a numpy array instead of a raw number or string
* This causes a `TypeError` when calling `datasets()` later down the chain

**Expected behavior**
The labels in each of the `LabelList` items should be raw strings or numbers as they are when `label_from_re` creates the labels correctly.  

**Screenshots**

**Additional context**
It appears that `label_from_csv` has the same issue, although I didn't test it quite as much.  Apologies if I'm missing something with the usage of that function.  I don't have time to write a test right now, but I may be able to dig in this weekend.

**Comment by sgugger** [comment]
Normally this is fixed now. Your gist still has an error, but it comes from the empty validation data, so it should work okay on a real case.
Thanks for flagging!
