### ISSUE TITLE
planet notebook

### ISSUE THREAD

**Issue by kasparlund** [fastai/fastai#1114]
To make the kaggle download (as per the notebook) work you have to :
-go to the kaggle competition and click “Late submission” and confirm by an sms code
-go to the datapage and accept the rule (the dialog box)

**Comment by sgugger** [comment]
Can you open this issue on the [course repo](https://github.com/fastai/course-v3)? This isn't linked to the library.
Thanks!

**Comment by kasparlund** [comment]
oh correct -thanks
