### ISSUE TITLE
download_data("url") fails on conda, ubuntu.

### ISSUE THREAD

**Issue by SamujjwalSam** [fastai/fastai#1120]
**Describe the bug**

When calling download_data("https://s3.amazonaws.com/fast-ai-nlp/ag_news_csv.tgz") with a fastai dataset url, it is throwing *KeyError: 'content-length'*.

**To Reproduce**

from fastai import *
download_data("https://s3.amazonaws.com/fast-ai-nlp/ag_news_csv.tgz")

**Expected behavior**

Download the dataset given in the url.

**Screenshots**

![fastai error 2](https://user-images.githubusercontent.com/3850813/48264692-681c4580-e450-11e8-987b-455016edaa58.JPG)

**Additional context**

Python 3.6.5 | Anaconda custom (64-bit) | Linux dgx 4.4.0-45-generic #66~14.04.1-Ubuntu

**Comment by sgugger** [comment]
Note that `download_data` adds the '.tgz' at the end, so you should use `download_data("https://s3.amazonaws.com/fast-ai-nlp/ag_news_csv")`.
