### ISSUE TITLE
Is data_block API ready to use?

### ISSUE THREAD

**Issue by shirishr** [fastai/fastai#1126]
I am working with a established dataset kaggle whale-categorization-playground
train and test folders contain jpg images (no sub-folders by class etc.)
train.csv contains ImageId/ClassName belonging to the train folder as:

ImageId | LabelName
-- | --
00022e1a.jpg | w_e15442c
000466c4.jpg | w_1287fbc
00087b01.jpg | w_da2efe0
001296d5.jpg | w_19e5482

The data can be downloaded from kaggle as:

! kaggle competitions download -c whale-categorization-playground -p {path}

**What is the appropriate way of creating a databunch when all train images are in one folder, their classes are specified in a csv file?**
databunch creation as shown below seemed reasonable:

data = (ImageFileList.from_folder(path)           
        .label_from_csv(path/'train.csv', folder='train') 
        .random_split_by_pct(0.2)
        .datasets()  
        .transform(tfms, size=128)             
        .databunch()
        .normalize(imagenet_stats))

However it ends in a key error for the first ClassName in the csv file.

Full trace as shown:

KeyError                                  Traceback (most recent call last)
<ipython-input-8-4017be140322> in <module>()
      2 data = (ImageFileList.from_folder(path)           
      3         .label_from_csv(path/'train.csv', folder='train')
----> 4         .random_split_by_pct(0.2)
      5         .datasets()
      6         .transform(tfms, size=128)

~/Documents/fastai/courses/v3/nbs/dl1/fastai/data_block.py in datasets(self, dataset_cls, **kwargs)
    234         train = dataset_cls(*self.train.items.T, **kwargs)
    235         dss = [train]
--> 236         dss += [train.new(*o.items.T, **kwargs) for o in self.lists[1:]]
    237         cls = getattr(train, '__splits_class__', self._pipe)
    238         return cls(self.path, *dss)

~/Documents/fastai/courses/v3/nbs/dl1/fastai/data_block.py in <listcomp>(.0)
    234         train = dataset_cls(*self.train.items.T, **kwargs)
    235         dss = [train]
--> 236         dss += [train.new(*o.items.T, **kwargs) for o in self.lists[1:]]
    237         cls = getattr(train, '__splits_class__', self._pipe)
    238         return cls(self.path, *dss)

~/Documents/fastai/courses/v3/nbs/dl1/fastai/vision/data.py in new(self, classes, *args, **kwargs)
     80     def new(self, *args, classes:Optional[Collection[Any]]=None, **kwargs):
     81         if classes is None: classes = self.classes
---> 82         return self.__class__(*args, classes=classes, **kwargs)
     83 
     84 class ImageClassificationDataset(ImageClassificationBase):

~/Documents/fastai/courses/v3/nbs/dl1/fastai/vision/data.py in __init__(self, x, y, classes, **kwargs)
     75 class ImageClassificationBase(ImageDatasetBase):
     76     def __init__(self, x:Collection, y:Collection, classes:Collection=None, **kwargs):
---> 77         super().__init__(x=x, y=y, classes=classes, **kwargs)
     78         self.learner_type = ClassificationLearner
     79 

~/Documents/fastai/courses/v3/nbs/dl1/fastai/vision/data.py in __init__(self, **kwargs)
     67 class ImageDatasetBase(DatasetBase):
     68     def __init__(self, **kwargs):
---> 69         super().__init__(**kwargs)
     70         self.image_opener = open_image
     71         self.learner_type = ImageLearner

~/Documents/fastai/courses/v3/nbs/dl1/fastai/basic_data.py in __init__(self, x, y, classes, c, task_type, class2idx, as_array, do_encode_y)
     23                 else: self.c = len(self.classes)
     24             if class2idx is None: self.class2idx = {v:k for k,v in enumerate(self.classes)}
---> 25             if y is not None and do_encode_y: self.encode_y()
     26         if self.task_type==TaskType.Regression: self.loss_func = MSELossFlat()
     27         elif self.task_type==TaskType.Single:   self.loss_func = F.cross_entropy

~/Documents/fastai/courses/v3/nbs/dl1/fastai/basic_data.py in encode_y(self)
     30     def encode_y(self):
     31         if self.task_type==TaskType.Single:
---> 32             self.y = np.array([self.class2idx[o] for o in self.y], dtype=np.int64)
     33         elif self.task_type==TaskType.Multi:
     34             self.y = [np.array([self.class2idx[o] for o in l], dtype=np.int64) for l in self.y]

~/Documents/fastai/courses/v3/nbs/dl1/fastai/basic_data.py in <listcomp>(.0)
     30     def encode_y(self):
     31         if self.task_type==TaskType.Single:
---> 32             self.y = np.array([self.class2idx[o] for o in self.y], dtype=np.int64)
     33         elif self.task_type==TaskType.Multi:
     34             self.y = [np.array([self.class2idx[o] for o in l], dtype=np.int64) for l in self.y]

KeyError: 'w_e15442c'

**It gets worse**

Another suggestion was to create the databunch as follows:

data = ImageDataBunch.from_csv(path, folder='train', sep=None, csv_labels='train.csv', valid_pct=0.2, ds_tfms=get_transforms(), size=128)

This also results in the same error (full trace below)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-f5e1f948a709> in <module>()
      1 np.random.seed(42)
----> 2 data = ImageDataBunch.from_csv(path, folder='train', sep=None, csv_labels='train.csv', valid_pct=0.2, ds_tfms=get_transforms(), size=128)

~/Documents/fastai/courses/v3/nbs/dl1/fastai/vision/data.py in from_csv(cls, path, folder, sep, csv_labels, valid_pct, fn_col, label_col, test, suffix, header, **kwargs)
    343         df = pd.read_csv(path/csv_labels, header=header)
    344         return cls.from_df(path, df, folder=folder, sep=sep, valid_pct=valid_pct, test=test,
--> 345                 fn_col=fn_col, label_col=label_col, suffix=suffix, header=header, **kwargs)
    346 
    347     @classmethod

~/Documents/fastai/courses/v3/nbs/dl1/fastai/vision/data.py in from_df(cls, path, df, folder, sep, valid_pct, fn_col, label_col, test, suffix, **kwargs)
    333                 .random_split_by_pct(valid_pct))
    334         if test is not None: src.add_test_folder(test)
--> 335         return cls.create_from_split_ds(src.datasets(), **kwargs)
    336 
    337     @classmethod

~/Documents/fastai/courses/v3/nbs/dl1/fastai/data_block.py in datasets(self, dataset_cls, **kwargs)
    234         train = dataset_cls(*self.train.items.T, **kwargs)
    235         dss = [train]
--> 236         dss += [train.new(*o.items.T, **kwargs) for o in self.lists[1:]]
    237         cls = getattr(train, '__splits_class__', self._pipe)
    238         return cls(self.path, *dss)

~/Documents/fastai/courses/v3/nbs/dl1/fastai/data_block.py in <listcomp>(.0)
    234         train = dataset_cls(*self.train.items.T, **kwargs)
    235         dss = [train]
--> 236         dss += [train.new(*o.items.T, **kwargs) for o in self.lists[1:]]
    237         cls = getattr(train, '__splits_class__', self._pipe)
    238         return cls(self.path, *dss)

~/Documents/fastai/courses/v3/nbs/dl1/fastai/vision/data.py in new(self, classes, *args, **kwargs)
     80     def new(self, *args, classes:Optional[Collection[Any]]=None, **kwargs):
     81         if classes is None: classes = self.classes
---> 82         return self.__class__(*args, classes=classes, **kwargs)
     83 
     84 class ImageClassificationDataset(ImageClassificationBase):

~/Documents/fastai/courses/v3/nbs/dl1/fastai/vision/data.py in __init__(self, x, y, classes, **kwargs)
     75 class ImageClassificationBase(ImageDatasetBase):
     76     def __init__(self, x:Collection, y:Collection, classes:Collection=None, **kwargs):
---> 77         super().__init__(x=x, y=y, classes=classes, **kwargs)
     78         self.learner_type = ClassificationLearner
     79 

~/Documents/fastai/courses/v3/nbs/dl1/fastai/vision/data.py in __init__(self, **kwargs)
     67 class ImageDatasetBase(DatasetBase):
     68     def __init__(self, **kwargs):
---> 69         super().__init__(**kwargs)
     70         self.image_opener = open_image
     71         self.learner_type = ImageLearner

~/Documents/fastai/courses/v3/nbs/dl1/fastai/basic_data.py in __init__(self, x, y, classes, c, task_type, class2idx, as_array, do_encode_y)
     23                 else: self.c = len(self.classes)
     24             if class2idx is None: self.class2idx = {v:k for k,v in enumerate(self.classes)}
---> 25             if y is not None and do_encode_y: self.encode_y()
     26         if self.task_type==TaskType.Regression: self.loss_func = MSELossFlat()
     27         elif self.task_type==TaskType.Single:   self.loss_func = F.cross_entropy

~/Documents/fastai/courses/v3/nbs/dl1/fastai/basic_data.py in encode_y(self)
     30     def encode_y(self):
     31         if self.task_type==TaskType.Single:
---> 32             self.y = np.array([self.class2idx[o] for o in self.y], dtype=np.int64)
     33         elif self.task_type==TaskType.Multi:
     34             self.y = [np.array([self.class2idx[o] for o in l], dtype=np.int64) for l in self.y]

~/Documents/fastai/courses/v3/nbs/dl1/fastai/basic_data.py in <listcomp>(.0)
     30     def encode_y(self):
     31         if self.task_type==TaskType.Single:
---> 32             self.y = np.array([self.class2idx[o] for o in self.y], dtype=np.int64)
     33         elif self.task_type==TaskType.Multi:
     34             self.y = [np.array([self.class2idx[o] for o in l], dtype=np.int64) for l in self.y]

KeyError: 'w_e15442c'

**Comment by devforfu** [comment]
It should be because the most recent version of the package shows [a deprecation warning](https://github.com/fastai/fastai/blob/8b9eb88f9581b5e897b7f04d466e0a2debe6e14b/fastai/vision/data.py#L87) if you use old methods to create data bunch. The warning says old factory methods will be removed in the next release.

**Comment by shirishr** [comment]
@devforfu,
I don't think so. Using pdb.set_trace() I see that somewhere len(self.classes) < unique class names in train.csv. I thought there is a problem with the train.csv file from kaggle (whitespace etc.). But the file opens very well in pandas dataframe. So I am at a loss. Can you try downloading the dataset from kaggle:

! kaggle competitions download -c whale-categorization-playground -p {path}

and try 

data = (ImageFileList.from_folder(path)           
        .label_from_csv(path/'train.csv', folder='train') 
        .random_split_by_pct(0.2)
        .datasets()  
        .transform(get_transforms(), size=128)             
        .databunch()
        .normalize(imagenet_stats))


It is likely that we may have found a bug ???

**Please keep it on the back-burner but keep it alive.**

**Comment by shirishr** [comment]
Thank you for your patience !

Finally my databunch is ready and a learner based on resnet34 is finding the lr.

Here is what I had to do.

1. move 1970 random images (out of 9850 i.e. apprx 20%) from train directory to valid directory

1. built a labels.csv with two columns containing path+image_name & class name

1. create a codes file containing unique class names from the labels.csv

1. Build databunch using:

codes = np.loadtxt(path/'codes.txt', dtype=str)
df_fn_labels=pd.read_csv(path/'labels.csv', index_col=None)
fnames=list(df_fn_labels['Image'])
labels=list(df_fn_labels['Id'])
`data = (ImageFileList.from_folder(path)
        .label_from_df(df_fn_labels, fn_col=0, label_col=1)
        .split_by_folder()
        .datasets(ImageClassificationDataset, fns=fnames, labels=labels, classes=codes)
        .transform(get_transforms(), size=128)
        .databunch()
        .normalize(imagenet_stats))`

There maybe opportunity to get the fastai library itself to do some of this stuff

**Comment by shirishr** [comment]
Closing now since I have discovered that codes.csv should only contain classes that are common to train and valid directories.

**Comment by shirishr** [comment]
With fastai 1.0.22, can not create a databunch anymore:

codes = np.loadtxt(path/'codes.txt', dtype=str)
df_fn_labels=pd.read_csv(path/'labels.csv', index_col=None)
fnames=list(df_fn_labels['Image'])
labels=list(df_fn_labels['Id'])
data = (ImageFileList.from_folder(path) .label_from_df(df_fn_labels, fn_col=0, label_col=1) .split_by_folder() .datasets(ImageClassificationDataset, fns=fnames, labels=labels, classes=codes) .transform(get_transforms(), size=128) .databunch() .normalize(imagenet_stats))

Error says:
NameError: name 'ImageFileList' is not defined

If I use ImageItemList  and follow it up with .label_from_df(df_fn_labels, fn_col=0, label_col=1)  it leads to error:

AttributeError: 'NoneType' object has no attribute 'iloc'

**Comment by sgugger** [comment]
The data block API is new and changing fast. Closing this issue as it's not relevant anymore.
