### ISSUE TITLE
MNIST loading error in fastaiv1

### ISSUE THREAD

**Issue by bewagner** [fastai/fastai#1129]
**Description**
I encountered an error when I tried to load the full version of MNIST with fastaiv1. 
The problem seems to be that the training directory in the version of MNIST that gets downloaded is called 'training' and not 'train'. 

For MNIST_SAMPLE everything works fine. It would be nice, if this would work for the full dataset as well. Maybe just renaming the folder on the fastai AWS server would be enough?

**To Reproduce (in fastai v1)**
`from fastai.vision import * `
`from fastai import *`
`path = untar_data(URLs.MNIST)`
`data = ImageDataBunch.from_folder(path)`

**Expected behavior**
ImageDataBunch loads train, val and test set of MNIST.

**Error message**

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-2c35a02c3c7b> in <module>()
      3 path = untar_data(URLs.MNIST)
      4 
----> 5 data = ImageDataBunch.from_folder(path)

~/anaconda3/envs/pytorch/lib/python3.6/site-packages/fastai/vision/data.py in from_folder(cls, path, train, valid, test, valid_pct, **kwargs)
    306         path=Path(path)
    307         if valid_pct is None:
--> 308             train_ds = ImageClassificationDataset.from_folder(path/train)
    309             datasets = [train_ds, ImageClassificationDataset.from_folder(path/valid, classes=train_ds.classes)]
    310         else: datasets = ImageClassificationDataset.from_folder(path/train, valid_pct=valid_pct)

~/anaconda3/envs/pytorch/lib/python3.6/site-packages/fastai/vision/data.py in from_folder(cls, folder, classes, valid_pct, extensions)
    104             extensions:Collection[str]=image_extensions)->Union['ImageClassificationDataset', List['ImageClassificationDataset']]:
    105         "Dataset of `classes` labeled images in `folder`. Optional `valid_pct` split validation set."
--> 106         if classes is None: classes = [cls.name for cls in find_classes(folder)]
    107 
    108         fns,labels,keep = [],[],{}

~/anaconda3/envs/pytorch/lib/python3.6/site-packages/fastai/core.py in find_classes(folder)
     67 def find_classes(folder:Path)->FilePathList:
     68     "List of label subdirectories in imagenet-style `folder`."
---> 69     classes = [d for d in folder.iterdir()
     70                if d.is_dir() and not d.name.startswith('.')]
     71     assert(len(classes)>0)

~/anaconda3/envs/pytorch/lib/python3.6/site-packages/fastai/core.py in <listcomp>(.0)
     67 def find_classes(folder:Path)->FilePathList:
     68     "List of label subdirectories in imagenet-style `folder`."
---> 69     classes = [d for d in folder.iterdir()
     70                if d.is_dir() and not d.name.startswith('.')]
     71     assert(len(classes)>0)

~/anaconda3/envs/pytorch/lib/python3.6/pathlib.py in iterdir(self)
   1077         if self._closed:
   1078             self._raise_closed()
-> 1079         for name in self._accessor.listdir(self):
   1080             if name in {'.', '..'}:
   1081                 # Yielding a path object for these makes little sense

~/anaconda3/envs/pytorch/lib/python3.6/pathlib.py in wrapped(pathobj, *args)
    385         @functools.wraps(strfunc)
    386         def wrapped(pathobj, *args):
--> 387             return strfunc(str(pathobj), *args)
    388         return staticmethod(wrapped)
    389 

FileNotFoundError: [Errno 2] No such file or directory: '/home/benjamin/.fastai/data/mnist_png/train'

**Comment by sgugger** [comment]
You can specify the name of the train folder with an argument called (very unoriginal) train.

**Comment by bewagner** [comment]
Alright, thanks for the reply!

**Comment by fredguth** [comment]
I tried the same thing today without knowledge of this issue.  
I got an error: index 0 is out of bounds for axis 0 with size 0

I guess the problem is that MNIST folders are named wrongly, they should be `train` and `valid`, not `training` and `testing`, right?

Where can this be changed?

**Comment by bewagner** [comment]
You're right. That is the problem. 

As I see it, you have two options:

1. Rename the folders themselves. 
On Linux you find them in your home directory under
 `~/.fastai/data/mnist_png`. 

2. Use the functions arguments as Sylvain mentioned above. 
Your call would look similar to
 `data = ImageDataBunch.from_folder(path, train='training', valid='testing')`
(I did not test this. But I hope you get the gist of it)

**Comment by fredguth** [comment]
I got it.  I already knew how to solve it, but the problem is not that.  We have to change MNIST dataset, so that others do not get this error.

**Comment by bewagner** [comment]
Yes. It looks like the fastest way would be if someone from fastai could change the names of the folders on their servers.

**Comment by sgugger** [comment]
Why would we change an academic dataset? There are methods in the library to open it properly, and it's useful to learn them since your data will not always be in folders named train and valid.

**Comment by bewagner** [comment]
In my view, then naming inconsistency between MNIST_SAMPLE and MNIST_TINY compared to the full dataset is an incentive for a change. 
As Fred mentioned, people will look up the documentation and see 


```
path = untar_data(URLs.MNIST_SAMPLE) 
data = ImageDataBunch.from_folder(path)
```

working out of the box. After doing some experiments, they might want to switch to the full dataset, only to  run into an error because the folder names are different. 

I see how it's useful to learn the methods parameters, but inconsistent behavior should not be the way we teach new users.

**Comment by fredguth** [comment]
Another option is to be more specific in the docs using data = ImageDataBunch.from_folder(path, train='...
so that people learn this.
