### ISSUE TITLE
Reset GPU memory when CUDA runs out of memory in training

### ISSUE THREAD

**Issue by odysseus0** [fastai/fastai#1133]
**Describe the bug**
It is fairly common to run out of GPU memory due to underestimation. However, right now, the fast.ai library will not free the GPU memory after such error is raised. The consequence is that people usually have to manually free it, and for novice users, the option is almost always shut down the kernel and then restart, which is quite inconvenient.

**To Reproduce**
Simply run through the lesson-3 planet notebook as of 11:10 PM Sunday, November 11, 2018 (PST) on a P4 instance, which is the default one created following the [official GCP setup guide](https://course-v3.fast.ai/start_gcp.html). The GPU will run out of memory in one of the training steps.

**Expected behavior**
It would be much more convenient if the fast.ai library automatically frees the GPU memory after GPU runs out of memory and aborts the training, just like what it does after the training successfully completes.

**Comment by brtknr** [comment]
Even better would be to determine an optimal batchsize before the training starts....

**Comment by odysseus0** [comment]
It would be nice to write a function that automatically determine the appropriate batch size based on the stats of the dataset, the specs of the GPU as obtainable from `nvidia-smi`, and other related information.

**Comment by brtknr** [comment]
What do you mean by stats of the dataset?
