### ISSUE TITLE
DL1 Lesson1 : error in most_by_correct()

### ISSUE THREAD

**Issue by jonathanmist** [fastai/fastai#114]
In lesson 1, the logic in ```most_by_mask()``` is not evaluated as I think it was intended because the operator precedence of bitwise AND is greater than logical equals. This can give erroneous results if there are strong false predictions. I only noticed it when training with a very small data and validation set of doors vs windows.

From fastai/courses/dl1/lesson1.ipynb:

```
def most_by_correct(y, is_correct): 
    mult = -1 if (y==1)==is_correct else 1
    return most_by_mask((preds == data.val_y)==is_correct & (data.val_y == y), mult)
```

I am pretty sure it should be:

```
def most_by_correct(y, is_correct): 
    mult = -1 if (y==1)==is_correct else 1
    return most_by_mask(((preds == data.val_y)==is_correct) & (data.val_y == y), mult)
```

**Comment by jph00** [comment]
Thanks - fixed now.

**Comment by jph00** [comment]
(BTW a pull request for this kind of thing is really helpful. If you haven't done a PR before, check the forum for tips and links to help get started).
