### ISSUE TITLE
padding_mode error 

### ISSUE THREAD

**Issue by firetix** [fastai/fastai#1146]
**Describe the bug**
I believe this is just a documentation Issue. but it you run 
`data = vision.data.ImageDataBunch.from_folder(PATH, ds_tfms=vision.get_transforms(), bs=bs, size=sz, padding_mode='border')` without the padding_mode it will trigger an error. 

**To Reproduce**
`data = vision.data.ImageDataBunch.from_folder(PATH, ds_tfms=vision.get_transforms(), bs=bs, size=sz) `If you ommit the padding_mode you will get an error  padding_mode needs to be 'zeros' or 'border', but got reflection
 

**Screenshots**

![image](https://user-images.githubusercontent.com/818836/48380120-6db19f80-e68b-11e8-9839-83b5479ff038.png)

**Comment by sgugger** [comment]
Your version of pytorch is v1.0 if you have this error. fastai doesn't support pytorch 0.4, see the [forum](https://forums.fast.ai/) for more details.

**Comment by firetix** [comment]
makes more sense now hahaha, Thanks!
