### ISSUE TITLE
Dead code in tabular/data.py

### ISSUE THREAD

**Issue by marii-moe** [fastai/fastai#1147]
fastai-1.0.x: http://forums.fast.ai/t/fastai-v1-install-issues-thread/24111

**Describe the bug**
./fastai/tabular/data.py: def _parse_kwargs
This code seems completely unused throughout the entire repository

**To Reproduce**
```
(fastai_new) molly@molly-dl:~/fastai$ grep '_parse_kwargs' -r .
./fastai/tabular/data.py:def _parse_kwargs(kwargs):
Binary file ./fastai/tabular/__pycache__/data.cpython-37.pyc matches
./htmlcov/fastai_tabular_data_py.html:<p id="t65" class="stm run hide_run"><span class="key">def</span> <span class="nam">_parse_kwargs</span><span class="op">(</span><span class="nam">kwargs</span><span class="op">)</span><span class="op">:</span><span class="strut">&nbsp;</span></p>
```

**Expected behavior**
The code to be used somewhere in the repository

**Additional context**
I am currently verifying that the code is not used anywhere throughout the notebooks, as I am not sure a grep would find the `_parge_kwargs` in the jupyter notebooks. What do we do when we find dead-code? This seems to be a private function that is not used anywhere throughout the file that it is declared in.

**Comment by sgugger** [comment]
This is an area of heavy refactor for now. Closing this issue as we're aware of it and it should be fixed tomorrow.
