### ISSUE TITLE
Imagebbox Doesn't have a flip attribute

### ISSUE THREAD

**Issue by firetix** [fastai/fastai#1148]
**Describe the bug**
Imagebbox Doesn't have a flip attribute. It doesn't support flip as a transform. 

**To Reproduce**
`tfms = ([flip_lr(p=0.5), crop_pad(size=size)], [crop_pad(size=size)])
train_tds = DatasetTfm(train_ds, tfms[0], tfm_y=True, size=size, padding_mode='zeros', do_crop=False)`
![image](https://user-images.githubusercontent.com/818836/48385512-a198bf00-e6a3-11e8-93f9-b7bbc28ba1b7.png)

**Comment by sgugger** [comment]
That's not a bug, you should use `flip_affine` for bounding boxes and points [see here in the docs](https://docs.fast.ai/vision.transform.html#flip_affine).
