### ISSUE TITLE
error from metrics=[accuracy] in lesson-4.imdb

### ISSUE THREAD

**Issue by kevindewalt** [fastai/fastai#115]
From https://github.com/fastai/fastai/blob/master/courses/dl1/lesson4-imdb.ipynb
`
m3.fit(lrs/2, 1, metrics=[accuracy])
`

metrics throws an up the pytorch stack.

`
m3.fit(lrs/2, 1)
`

results no error

### error
TypeError: eq received an invalid combination of arguments - got (Variable), but expected one of:
 * (int value)
      didn't match because some of the arguments have invalid types: (Variable)
 * (torch.cuda.LongTensor other)
      didn't match because some of the arguments have invalid types: (Variable)

**Comment by apiltamang** [comment]
@kevindewalt 
Might be a cause of a recent change (minor) I made to the 'fit' method. I will look onto it over the weekend. :)

**Comment by interogativ** [comment]
This is because you are comparing an autograd variable to a tensor.  Here's how I got around this:
```
def accuracy1(preds, targs):
    preds = torch.max(preds, dim=1)[1]
    #print ('preds: {}, {}'.format(preds.shape,type(preds)))
    #print ('targs: {}, {}'.format(targs.shape,type(targs)))
    return (preds==targs.data).float().mean()

```

**Comment by jph00** [comment]
I recently changed metrics to use pytorch tensors rather than numpy arrays. So it looks like this is an example of a regression. I'll take a look shortly.

**Comment by MattKleinsmith** [comment]
Regression occurs in the lesson1 notebook accuracy calls, too. On a deadline atm.

https://github.com/fastai/fastai/blob/master/courses/dl1/lesson1.ipynb

**Comment by jph00** [comment]
@MattKleinsmith it works for me in in the lesson 1 notebook. Are you sure you have `git pull` up to date, and are using the latest version of the notebooks?

**Comment by MattKleinsmith** [comment]
@jph00 My mistake. Pulling and testing now.

**Comment by MattKleinsmith** [comment]
@jph00 I'm getting:

```
torch.max received an invalid combination of arguments - 
got (numpy.ndarray, dim=int), but expected one of:
 * (torch.FloatTensor source)
[...]
```

If you go to [lesson1.ipynb](https://github.com/fastai/fastai/blob/master/courses/dl1/lesson1.ipynb) and CTRL+F "accuracy(" you'll see that `probs`, an argument to accuracy, comes from `np.mean`, making it a numpy array.

**Comment by jph00** [comment]
OK I've pushed an `accuracy_np` function to fix this.
