### ISSUE TITLE
LanguageModelData not defined

### ISSUE THREAD

**Issue by alibaltschun** [fastai/fastai#1151]
hello, i was following the tutorial. and in this code give me an error

```
trn_dl = LanguageModelLoader(pd.DataFrame(trn_lm,columns=['x']), bs, bptt)
val_dl = LanguageModelLoader(pd.DataFrame(trn_lm,columns=['x']), bs, bptt)
md = LanguageModelData(PATH_MODELS, 1, vs, trn_dl, val_dl, bs=bs, bptt=bptt)

NameError: name 'LanguageModelData' is not defined
```

i was check on this [file ](https://github.com/fastai/fastai/blob/master/fastai/text/data.py) and there are no class 'LanguageModelData' .  and on this [doc](https://docs.fast.ai/text.data.html#TextLMDataBunch) at 'Language Model Data' at the bottom say 'This is all done internally when we use TextLMDataBunch, by creating DataLoader using the following class:'

its that mean the class LanguageModelData was refactored to TextLMDataBunch ? 

thanks

**Comment by sgugger** [comment]
The course uses the old version of fastai, you're using the new one, which is why you have a problem.

**Comment by alibaltschun** [comment]
so how to fix that problem with the new version?

**Comment by sgugger** [comment]
I'm not sure I understand the question. You are following the old course, that is meant to work with the old (aka 0.7) library. It's not fixable with the new library.

**Comment by CarlosRCDev** [comment]
Change:
LanguageModelLoader
for:
LanguageModelPreLoader

You can read it here:
page: https://github.com/fastai/fastai/blob/master/CHANGES.md
Part: 1.0.40 (2019-01-17) 
Info: LanguageModelLoader becomes LanguageModelPreLoader and is a dataset to wrap in a pytorch DataLoader

**Comment by CarlosRCDev** [comment]
Change:
LanguageModelLoader
For:
LanguageModelPreLoader

Page: https://github.com/fastai/fastai/blob/master/CHANGES.md
Part: 1.0.40 (2019-01-17)
Info: LanguageModelLoader becomes LanguageModelPreLoader and is a dataset to wrap in a pytorch DataLoader

**Comment by abhigenie92** [comment]
What about LanguageModelData what does that become?
