### ISSUE TITLE
fastai v1.0.x typo in fastai.text.data.py #L326

### ISSUE THREAD

**Issue by Ari-Ramkilowan** [fastai/fastai#1153]
**Describe the bug**

There is a minor typo in the  `from_tokens` function in the `TextDataBunch` class

**Error Received :** NameError: name `'src'` is not defined

`srx = create_sdata(TextSplitData, path, trn_tok, trn_lbls, val_tok, val_lbls, tst_tok)` should be 
`src = create_sdata(TextSplitData, path, trn_tok, trn_lbls, val_tok, val_lbls, tst_tok)`  

Full Stack trace :

> NameError                                 Traceback (most recent call last)
> <ipython-input-77-7df6be0c639e> in <module>
>       4                                        trn_lbls=wiki_trn_lbls,
>       5                                        val_tok=wiki_val_tok,
> ----> 6                                        val_lbls=wiki_val_lbls)
> 
> /opt/anaconda3/lib/python3.6/site-packages/fastai/text/data.py in from_tokens(cls, path, trn_tok, trn_lbls, val_tok, val_lbls, vocab, tst_tok, classes, **kwargs)
>     331         num_kwargs, kwargs = extract_kwargs(['max_vocab', 'min_freq'], kwargs)
>     332         srx = create_sdata(TextSplitData, path, trn_tok, trn_lbls, val_tok, val_lbls, tst_tok)
> --> 333         return (src.datasets(TokenizedDataset, classes=classes)
>     334                    .numericalize(vocab, **num_kwargs)
>     335                    .databunch(cls, **kwargs))
> 
> NameError: name 'src' is not defined
>

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
This will be changed in the refactor we are currently doing, I saw that typo too yesterday. Thanks for flagging!
