### ISSUE TITLE
language models aren't saved with models

### ISSUE THREAD

**Issue by stas00** [fastai/fastai#1157]
`
learn = language_model_learner(data_lm, drop_mult=0.3, pretrained_model=URLs.WT103)
`
downloads the model files into `~/.fastai/data` instead of `~/.torch/models`

lesson3-imdb suggests it should go into `./fastai/models/`, which is yet another location, it probably should go into `~/.torch/models` and lesson3-imdb's suggestion fixed accordingly.

**Comment by stas00** [comment]
exploring some more, we also have `~/.torch/models/`. So is the intention to have both `~/.torch/models/`and `~/.fastai/models/? In which case the language model should not be saved under ` ~/.fastai/data`, but `~/.fastai/models`.

Except we don't have `~/.fastai/models`, even though the future reading lesson3-imdb says so.

Currently I only see ~/.fastai/data in datasets.py and only `data_path` is configurable via `~/.fastai/config.yml`, documented [here](https://docs.fast.ai/datasets.html).  

So I suppose we need to add a configurable `models_path`, with default to `~/.fastai/models`, and make the model downloads go there instead.

**Comment by sgugger** [comment]
The intention is to have the models save in `~/.fastai/models`. I've fixed the code accordingly.

**Comment by stas00** [comment]
Thanks, @sgugger.
And please note somewhere that we are missing a user-configurable `models_path` (see my previous comment).

**Comment by sgugger** [comment]
You can configure models_pah in your config file too: as seen on [this line](https://github.com/fastai/fastai/blob/075b6582042588d026ebf32c1c457413d0cec0db/fastai/datasets.py#L41). Unless there is something I'm missing?

**Comment by stas00** [comment]
Ah, I see it in the code - thank you for the link. It's not documented though in the section of `~/.fastai/config.yml`of https://docs.fast.ai/datasets.html, probably under `modelpath4file`, which is not there either?

Or perhaps we add a new section for `~/.fastai/config.yml` and put all those user-configurable variables in one place?
