### ISSUE TITLE
metrics.py invokes torch.max with "an invalid combination of arguments "

### ISSUE THREAD

**Issue by gsgbills** [fastai/fastai#116]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-53-a1eb5389ef99> in <module>()
----> 1 accuracy(*learn.TTA())

~/fastai/courses/dl1/fastai/metrics.py in accuracy(preds, targs)
      3 
      4 def accuracy(preds, targs):
----> 5     preds = torch.max(preds, dim=1)[1]
      6     return (preds==targs).float().mean()
      7 

TypeError: torch.max received an invalid combination of arguments - got (numpy.ndarray, dim=int), but expected one of:
 * (torch.FloatTensor source)
 * (torch.FloatTensor source, torch.FloatTensor other)
      didn't match because some of the keywords were incorrect: dim
 * (torch.FloatTensor source, int dim)
 * (torch.FloatTensor source, int dim, bool keepdim)

**Comment by gsgbills** [comment]
This maybe the same issue as #115 .

**Comment by gsgbills** [comment]
arguments should be cast, e.g., torchLongTensor(targs)

**Comment by jph00** [comment]
Let's move the discussion to #115 . We'll need more info about where you're calling the function from to fix this properly, BTW.
