### ISSUE TITLE
ImageDataBunch from_csv pandas issue

### ISSUE THREAD

**Issue by Data-drone** [fastai/fastai#1169]
**Describe the bug**
when trying to create an `ImageDataBunch` using `from_csv` it has issues with `pandas.read_csv`  
this if for fastai version 1.0.22
with pandas 0.23.4

**To Reproduce**
csv is structured like:

filenames | cats
-- | --
n03706229/n03706229_8315.JPEG | 352
n03706229/n03706229_473.JPEG | 352
n03706229/n03706229_2254.JPEG | 352

folder structure is:

data
+-- imagenet
|     +-- train.csv
|     +-- train
|          +-- n03706229
|          +-- n01440764

`data = ImageDataBunch.from_csv(path=PosixPath('../data/imagenet'),folder='train', sep = ',',
                                   csv_labels='train.csv')`

returns 

`
ErrorTraceback (most recent call last)
<ipython-input-74-c78a68ffb734> in <module>()
      2     return ImageClassificationDataset.from_folder(folder='train')
      3 data = ImageDataBunch.from_csv(path=PATH,folder='train', sep = ',',
----> 4                                    csv_labels='train.csv')

/usr/local/lib/python3.6/site-packages/fastai/vision/data.py in from_csv(cls, path, folder, sep, csv_labels, valid_pct, fn_col, label_col, test, suffix, header, **kwargs)
    343         df = pd.read_csv(path/csv_labels, header=header)
    344         return cls.from_df(path, df, folder=folder, sep=sep, valid_pct=valid_pct, test=test,
--> 345                 fn_col=fn_col, label_col=label_col, suffix=suffix, header=header, **kwargs)
    346 
    347     @classmethod

/usr/local/lib/python3.6/site-packages/fastai/vision/data.py in from_df(cls, path, df, folder, sep, valid_pct, fn_col, label_col, test, suffix, **kwargs)
    330         path = Path(path)
    331         src = (ImageFileList.from_folder(path/folder)
--> 332                 .label_from_df(df, suffix=suffix, sep=sep, fn_col=fn_col, label_col=label_col)
    333                 .random_split_by_pct(valid_pct))
    334         if test is not None: src.add_test_folder(test)

/usr/local/lib/python3.6/site-packages/fastai/data_block.py in label_from_df(self, df, fn_col, label_col, sep, folder, suffix)
     94                       suffix:str=None)->'LabelList':
     95         "Look in `df` for the filenames in `fn_col` to get the corresponding label in `label_col`."
---> 96         fnames, labels = _extract_input_labels(df, fn_col, label_col, label_delim=sep, suffix=suffix, is_fnames=True)
     97         fnames = join_paths(fnames, self.path/Path(folder))
     98         df1 = pd.DataFrame({'fnames':fnames, 'labels':labels}, columns=['fnames', 'labels'])

/usr/local/lib/python3.6/site-packages/fastai/data_block.py in _extract_input_labels(df, input_cols, label_cols, is_fnames, label_delim, suffix)
     38     assert label_delim is None or not isinstance(label_cols, Iterable) or len(label_cols) == 1
     39     labels = df.iloc[:,df_names_to_idx(label_cols, df)]
---> 40     if label_delim: labels = np.array(list(csv.reader(labels.iloc[:,0], delimiter=label_delim)))
     41     else:
     42         if isinstance(label_cols, Iterable) and len(label_cols) > 1: labels = _decode(labels)

Error: iterator should return strings, not int (did you open the file in text mode?)`

**Expected behavior**
data bunch should be successfully created 

**Additional context**
I am trying to update @sgugger 's https://github.com/sgugger/Deep-Learning/blob/master/Resnet%2050%20and%20Darknet%2053.ipynb

**Comment by sgugger** [comment]
The separator is not the csv separator, but a separator for your labels in the label columns (if you had things lie 'cat,dog' to multi-label one image.
That's probably why you get the issue, here you want to let sep be None.
