### ISSUE TITLE
Possible error in EmbeddingDotBias class

### ISSUE THREAD

**Issue by wontheone1** [fastai/fastai#1180]
**Describe the bug**

When creating an object of [`EmbeddingDotBias` class](https://github.com/fastai/fastai/blob/724736bcff29056761f870399d6c8a2e57611130/fastai/collab.py#L56), if only `min_score` argument is given, it can throw when forward is called.

**To Reproduce**
Create an object of `EmbeddingDotBias` class with `min_score` argument but not the `max_score` argument. Since `self.min_score` is non-None value, it will pass through [this line](https://github.com/fastai/fastai/blob/724736bcff29056761f870399d6c8a2e57611130/fastai/collab.py#L68) but now `self.max_score` is None, subtracting from it will throw.

**Expected behavior**
One option: Constructor should throw when only `min_score` is given. Error message can be something like "When min_score is given, max_score should be given also" (Helpful to coder why this throws and what to fix than throwing by subtracting from `None`.
Another option: Forward should make sure to return above min_score but no upper limit. Code can be e.g.
```python3
    def forward(self, users:LongTensor, items:LongTensor) -> Tensor:
        dot = self.u_weight(users)* self.i_weight(items)
        res = dot.sum(1) + self.u_bias(users).squeeze() + self.i_bias(items).squeeze()
        if self.min_score is None:
             return res
        elif self.max_score is None:
            return res + self.min_score
        return torch.sigmoid(res) * (self.max_score-self.min_score) + self.min_score
```

**Screenshots**
N/A

**Additional context**
I caught this by thought experiment, so if this is not a real problem, I am very sorry. I can make PR to fix this myself but I don't know which of two options I suggest you will accept so I am only going so far as making an issue. If you let me know how to solve this I can make PR myself.

**Comment by wontheone1** [comment]
@sgugger good point! it can be also like RELU but `max(self.min_score, res)` but also throwing from the constructor and give explanation that both argument should be given or None should be given would be helpful don't you think ?

**Comment by sgugger** [comment]
I think an assertion may be better yes. Ideally then, I should remove those two arguments and have something called `y_range` instead that is a tuple, so it would be clearer this way, but since it changes the API for the lesson notebooks, I'll check with Jeremy.

**Comment by sgugger** [comment]
It's been pushed and released now, so closing this issue.
