### ISSUE TITLE
how to read images from sub directories for training.

### ISSUE THREAD

**Issue by VinACE** [fastai/fastai#1187]
**Describe the bug**
loading data from sub directories 

PATH = "/root/sharedfolder/fai/data/"

OSError: Is a directory: /root/sharedfolder/fai/data/train/runing_class/runing_file_01012018/
so I have captured the data inside the subdirectories/

so under train i have got
├── runing_class_01
│   ├── runing_file_01012018/
│   │   ├── 0001.jpg
│   │   ├── 0002.jpg
│   │   ├── 0003.jpg

arch=resnet34
data = ImageClassifierData.from_paths(PATH, tfms=tfms_from_model(arch, sz))
learn = ConvLearner.pretrained(arch, data, precompute=True)
learn.fit(0.01, 2)

Here iam getting the following errors as the files are inside the class/subdirectory
OSError: Is a directory: /root/sharedfolder/fai/data/train/runing_class_01/runing_file_01012018/

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
You have to use the data block API for this, which has the option `recurse` (default True) to look into subdirectorires.

**Comment by VinACE** [comment]
could you please point to a document, or piece of code, so that I can follow, I am unsure where to search this.

**Comment by VinACE** [comment]
https://docs.fast.ai/data_block.html -- I am currently looking at this page.

**Comment by VinACE** [comment]
I tried  the following,
data = (ImageItemList.from_folder(PATH) #Where to find the data? -> in path and its subfolders
        .split_by_folder()              #How to split in train/valid? -> use the folders
        .label_from_folder()            #How to label? -> depending on the folder of the filenames
        .add_test_folder(f'{PATH}/test')              #Optionally add a test set (here default name is test)
        .transform(tfms, size=64)       #Data augmentation? -> use tfms with a size of 64
        .databunch()) 
from fastai.vision import *
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-160-05c4443cffd4> in <module>
      2 import fastai
      3 from fastai.imports import *
----> 4 from fastai.vision import *

ModuleNotFoundError: No module named 'fastai.vision'

**Comment by VinACE** [comment]
I tried in Ipython notebook from the terminal, that is working for import the library, rest of methods are still failing
In [12]: data = (ImageItemList.from_folder(PATH) #Where to find the data? -> in path and its subfolders 
    ...:         .split_by_folder()              #How to split in train/valid? -> use the folders 
    ...:         .label_from_folder()            #How to label? -> depending on the folder of the filenames 
    ...:         .add_test_folder(f'{PATH}/test')              #Optionally add a test set (here default name is tes
    ...: t) 
    ...:         .transform(tfms, size=64)       #Data augmentation? -> use tfms with a size of 64 
    ...:         .databunch())                                                                                     
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-12-2a3731f53300> in <module>
----> 1 data = (ImageItemList.from_folder(PATH) #Where to find the data? -> in path and its subfolders
      2         .split_by_folder()              #How to split in train/valid? -> use the folders
      3         .label_from_folder()            #How to label? -> depending on the folder of the filenames
      4         .add_test_folder(f'{PATH}/test')              #Optionally add a test set (here default name is test)
      5         .transform(tfms, size=64)       #Data augmentation? -> use tfms with a size of 64

NameError: name 'ImageItemList' is not defined

In [13]: from fastai.vision import ImageItemList                                                                   
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-13-35003d83c618> in <module>
----> 1 from fastai.vision import ImageItemList

ImportError: cannot import name 'ImageItemList'

In [14]: from fastai.vision import ItemList                                                                        
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-14-1d8f73f0eb33> in <module>
----> 1 from fastai.vision import ItemList

ImportError: cannot import name 'ItemList'

In [15]:                                                                                                           

In [15]: import fastai.vision                                                                                      

In [16]:

**Comment by sgugger** [comment]
Please use the [forum](https://forums.fast.ai/) for questions around the library.
