### ISSUE TITLE
passed custom function to read 4 channels image is not working

### ISSUE THREAD

**Issue by 10zinten** [fastai/fastai#1188]
https://github.com/fastai/fastai/blob/672c8c5344f319e64ac096e7ce9fd9c0c75a440b/fastai/vision/data.py#L287

I am trying to read the Image with 4 channels but biult-in `open_image()` uses Pillow, which only return 3 channels image. With setting custom function to read 4 channels still uses the default `open_image()'.

Here is my custom function.
```
def open_rgby(fn):
    flags = cv2.IMREAD_UNCHANGED
    img = cv2.imread(str(fn), flags).astype(np.float32)/255
    return Image(torch.tensor(img).permute(2,0,1))
```
Setting custom function like this: `create_func=open_rgby`
```
src = (ImageItemList.from_csv(DATA, 'train.csv', create_func=open_rgby, folder='train-comb', suffix='.png')
       .random_split_by_pct(0.2)
       .label_from_df(sep=' '))
```
Please let me know the correct approach. Right now I have overwritten the default `open_image()`, which fixed the problem.

**Comment by sgugger** [comment]
This should work, but there was a problem with `create_func` not being properly passed in the latest release. This is fixed in master normally, are you running this code on it?

**Comment by 10zinten** [comment]
Oh okay, I am running this on `'1.0.25.dev0'`

**Comment by 10zinten** [comment]
I have figured out, we have to set `create_func` for ItemsList. 
example:
```
src.train.x.create_func=open_rgby
src.valid.x.create_func=open_rgby
src.test.x.create_func=open_rgby
```
But looks little bit redundant.
