### ISSUE TITLE
Memory Error with the Tokenizer

### ISSUE THREAD

**Issue by matiu2** [fastai/fastai#1195]
# Description

I'm hitting a memory error in the text tokenizer. I've tried this with a 30 GB google cloud machine; it's only 387 MB of data.

I'm on Python3.7. I've seen it happen on both my laptop and my cloud machine.

I was working with the git master, in particular this commit: https://github.com/fastai/fastai/commit/0a45ccac40eefb5ccaf5e8259d867bdf4bee367d

# To reproduce

    from fastai import *
    from fastai import text

    data_path = Path('data/aclImdb')
    data_path.mkdir(exist_ok=True)

    #! curl -O http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
    #! tar -xzfv aclImdb_v1.tar.gz -C data/

    !tree -d {data_path}

    train_path = data_path/'train'
    test_path = data_path/'test'

    !ls {train_path}

    text_list = text.data.TextList.from_folder(train_path)
    text_list = text_list.random_split_by_pct(0.1)
    text_list = text_list.label_from_folder()

## Traceback

    ---------------------------------------------------------------------------
    MemoryError                               Traceback (most recent call last)
    <ipython-input-29-505969c25047> in <module>
    ----> 1 text_list = text_list.label_from_folder()

    ~/fastai/fastai/data_block.py in _inner(*args, **kwargs)
        291             self.valid = fv(*args, **kwargs)
        292             self.__class__ = LabelLists
    --> 293             self.process()
        294             return self
        295         return _inner

    ~/fastai/fastai/data_block.py in process(self)
        326     def process(self):
        327         xp,yp = self.get_processors()
    --> 328         for ds in self.lists: ds.process(xp, yp)
        329         return self
        330 

    ~/fastai/fastai/data_block.py in process(self, xp, yp)
        388     def process(self, xp=None, yp=None):
        389         "Launch the preprocessing on `xp` and `yp`."
    --> 390         self.x.process(xp)
        391         self.y.process(yp)
        392         return self

    ~/fastai/fastai/data_block.py in process(self, processor)
         45         if processor is not None: self.processor = processor
         46         if not is_listy(self.processor): self.processor = [self.processor]
    ---> 47         for p in self.processor: p.process(self)
         48         ret
    ![selection_060](https://user-images.githubusercontent.com/790456/48644263-cb4c4000-ea2d-11e8-8850-bf381ccb24fa.png)
    urn self
         49 

    ~/fastai/fastai/text/data.py in process(self, ds)
        305     def process_one(self, item):  return self.tokenizer._process_all_1([item])[0]
        306     def process(self, ds):
    --> 307         ds.items = _join_texts(ds.items, self.mark_fields)
        308         tokens = []
        309         for i in progress_bar(range(0,len(ds),self.chunksize), leave=False):

    ~/fastai/fastai/text/data.py in _join_texts(texts, mark_fields)
        291 
        292 def _join_texts(texts:Collection[str], mark_fields:bool=True):
    --> 293     if not isinstance(texts, np.ndarray): texts = np.array(texts)
        294     if is1d(texts): texts = texts[:,None]
        295     df = pd.DataFrame({i:texts[:,i] for i in range(texts.shape[1])})

    MemoryError:

**Comment by sgugger** [comment]
Not sure where the problem lies. I've loaded and processed the imdb dataset without any issue. Could you share more about your steup on the [forum](https://forums.fast.ai/)?

**Comment by jamesr2323** [comment]
I have also come across this error, with 1.0.43. The only solution I found so far was to revert to a known good version. 1.0.9. The following code works as expected in 1.0.9 but fails with a MemoryError in 1.0.43:

```
from fastai.text import *
from pathlib import Path
import spacy
! python -m spacy download en
spacy.load('en')

DATA_PATH=Path('text_class/data/')
DATA_PATH.mkdir(exist_ok=True)

! curl -O http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
! tar xzfv aclImdb_v1.tar.gz -C {DATA_PATH}

# Language model data
data_lm = TextLMDataBunch.from_folder(DATA_PATH/'aclImdb')
```
