### ISSUE TITLE
ImageDataBunch.labels_to_csv fails because internal function _get_fns takes two arguments

### ISSUE THREAD

**Issue by erdmann** [fastai/fastai#1199]
**version**

fastai v1.0.26

**Describe the bug**
`ImageDataBunch.labels_to_csv(filename)` fails with bad arguments to `fastai.data.vision._get_fns`

A stacktrace follows:

```python
TypeError                                 Traceback (most recent call last)
<ipython-input-351-3f0ab52ab7fa> in <module>()
----> 1 data.labels_to_csv('labels.csv')

/opt/anaconda/envs/py36/lib/python3.6/site-packages/fastai/vision/data.py in labels_to_csv(self, dest)
    170     def labels_to_csv(self, dest:str)->None:
    171         "Save file names and labels in `data` as CSV to file name `dest`."
--> 172         fns = _get_fns(self.train_ds)
    173         y = list(self.train_ds.y)
    174         fns += _get_fns(self.valid_ds)

TypeError: _get_fns() missing 1 required positional argument: 'path'

```
The definition of `_get_fns()` is

```python
def _get_fns(ds, path):
    "List of all file names relative to `path`."
    return [str(fn.relative_to(path)) for fn in ds.x]
```

Note that `_get_fns(ds, path)` is used incorrectly three times in `ImageDataBunch.labels_to_csv`:

```python
    def labels_to_csv(self, dest:str)->None:
        "Save file names and labels in `data` as CSV to file name `dest`."
        fns = _get_fns(self.train_ds)
        y = list(self.train_ds.y)
        fns += _get_fns(self.valid_ds)
        y += list(self.valid_ds.y)
        if hasattr(self,'test_dl') and data.test_dl:
            fns += _get_fns(self.test_ds)
            y += list(self.test_ds.y)
        df = pd.DataFrame({'name': fns, 'label': y})
        df.to_csv(dest, index=False)
```

Poking around, `_get_fns()` seems to be left over from a previous version, since `ds.x` in the definition of `_get_fns` is an iterator over images, not filenames.  

Additionally, it's not clear how one gets a list of filenames from a dataset.  Is there an obvious way to do this?

Thanks in advance.

**Comment by sgugger** [comment]
I'll fix this, you're right it should have been adapted since our recent breaking changes.
For your second questions, the filenames are the raw items (before opening) and you can always access those with the `items` attribute: `data.train_ds.x.items` for instance will give you the filenames in the training set.

**Comment by sgugger** [comment]
It's been replaced by data.train_ds (or valid_ds) .to_csv() now, and this method should work.
