### ISSUE TITLE
class MultiCategoryList doesn't work properly

### ISSUE THREAD

**Issue by Xmiler** [fastai/fastai#1202]
**Describe the bug**

Issue 1. `ItemList.label_from_df(...)` causes error when optional parameter `classes` is not passed. See https://github.com/fastai/fastai/blob/62e749f65ad4bff56776fe7042c657e092b93095/fastai/data_block.py#L220
Issue 2. `MultiCategoryList` crashes while applying the one-hot encoding on strings. I added after https://github.com/fastai/fastai/blob/62e749f65ad4bff56776fe7042c657e092b93095/fastai/data_block.py#L253 casting to int `items = [[int(item_2_level) for item_2_level in item_1_level] for item_1_level in items]` and it works.

**To Reproduce**

I'm playing with https://www.kaggle.com/c/human-protein-atlas-image-classification . So one should to download input data and place it to the current working directory. Then
```
from pathlib import Path
import numpy as np
import cv2
from fastai.vision import ImageItemList

PATH = Path('./')
TRAIN = Path('input/train/')
LABELS = Path('input/train.csv')

def open_rgby(path): #a function that reads RGBY image    
    colors = ['red','green','blue','yellow']    
    img = [cv2.imread(path + '_'+color+'.png', cv2.IMREAD_GRAYSCALE).astype(np.float32)/255
           for color in colors]
    return np.stack(img, axis=-1)

# Issue 1.
data = (ImageItemList.from_csv(PATH, LABELS, folder=TRAIN, create_func=open_rgby)
                     .label_from_df(sep=' '))

# Issue 2.
data = (ImageItemList.from_csv(PATH, LABELS, folder=TRAIN, create_func=open_rgby)
                     .label_from_df(sep=' ', classes=np.arange(28)))
```

**Expected behavior**

Issue 1.
Default parameter must work. Otherwise it must be an required one.

Issue 2.
Just fix a bug.

**Screenshots**

Issue 1.
![image](https://user-images.githubusercontent.com/25466384/48664950-9ab0e880-eab7-11e8-8642-99ba3552b0a5.png)

Issue 2.
![image](https://user-images.githubusercontent.com/25466384/48664962-d64bb280-eab7-11e8-9505-99a7109738e3.png)

**Additional context**

**Comment by sgugger** [comment]
This should be fixed by [this commit](https://github.com/fastai/fastai/commit/ac45d71d4fab9430f0c195aeb7f2ad7c823d43a1).
