### ISSUE TITLE
imdb scripts/finetune_lm.py failing

### ISSUE THREAD

**Issue by orenmel** [fastai/fastai#1209]
**Describe the bug**

When running finetune_lm.py, I get the following error:
ModuleNotFoundError: No module named ‘fastai.lm_rnn’

**To Reproduce**

python finetune_lm.py
https://github.com/fastai/fastai/blob/master/courses/dl2/imdb_scripts/finetune_lm.py

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
This script is meant to be used with fastai v0.7, not v1.
