### ISSUE TITLE
Exception in mulithreaded worker

### ISSUE THREAD

**Issue by gurvindersingh** [fastai/fastai#1213]
**Describe the bug**

When running Fastai version 1.0.20 or above (likely before as well) in multi threaded worker under load it throughs exception and requests fails.

**To Reproduce**

Run gunicorn with multi threads worker e.g. `gunicorn app:app --workers 2 -k gthread --threads 3` Now send 20+ requests per second to do inference. Randomly some request will start to fail due to exception in the server.

**Expected behavior**

All requests should succeed and they do if I run with multiple single threaded workers.

**Screenshots**

[Stack Trace](https://pastebin.com/2QCZW6M0)

**Additional context**

**Comment by stas00** [comment]
@gurvindersingh, a lot has changed in 3 months - is this still a problem with the latest fastai and pytorch versions?

**Comment by gurvindersingh** [comment]
I have not tested the newer version but i think using multiple workers with single threads works fine. So we can close this issue.
