### ISSUE TITLE
sgen_notebooks seems to have disappeared

### ISSUE THREAD

**Issue by marii-moe** [fastai/fastai#1217]
fastai-1.0
**Describe the bug**
A way to create notebooks seems to have changed, and is now missing

**To Reproduce**
sgen_notebooks not located in tools as noted here: https://docs.fast.ai/gen_doc.gen_notebooks.html#create_module_page

**Expected behavior**
I expect there is a new way to generate notebooks that has not yet been documented. This is to raise that issue. 

**Additional context**
Was attempting to add some unit tests specifically for testing the code for generation and updating of notebooks, and not individual notebooks. This area seems to be uncovered currently. I was going to review sgen_notebook in order to better understand how these modules work.

**Comment by sgugger** [comment]
Your link is pointing toward the function needed to generate a new notebook. We'll remove the mentions of the old script, thanks for flagging!
