### ISSUE TITLE
wikiExtractor.py missing in courses/dl2/imdb_scripts/wikiextractor

### ISSUE THREAD

**Issue by nathanvl** [fastai/fastai#1221]
The file is missing in the wikiextractor folder in:
https://github.com/fastai/fastai/tree/master/courses/dl2/imdb_scripts

and is being called when running the prepare_wiki.sh script. => error
This is discussed nowhere in the documentation, so quite confusing.

I found a file with the same name in https://github.com/attardi/wikiextractor/blob/master/WikiExtractor.py
if there are ownership/copyright issues, maybe refer to that page in the documentation?

Edit: I see now that when the wikiextractor folder is not present, a git clone is attempted, so maybe the folder should be removed instead of the file added :)

**Comment by PiotrCzapla** [comment]
@nathanvl  this is old code and it is going to be replaced by something that works with fastai v1. If you need some scripts to fetch and transform wikipedia you can fetch them from here: https://github.com/n-waves/ulmfit-multilingual

**Comment by sgugger** [comment]
Closing this then.
