### ISSUE TITLE
ULMFiT Language Model increasing memory consumption during pretraining in v1

### ISSUE THREAD

**Issue by pvcastro** [fastai/fastai#1224]
**Describe the bug**

While training a language model using the code from v1, it has been verified by me, @PiotrCzapla and @tchambon that after each training epoch, the memory consumption is increasing, eventually running into an out of memory error, even if the starting batch size fits the GPU memory.

@PiotrCzapla believes it may be related to this issue from previous versions:

[Modified sortsampler and sortishsampler to start with the largest batch sizes first. This should hopefully help with a few memory issues that were occuring when random sequences of batch width led to the creation of multiple buffers.](https://github.com/fastai/fastai/commit/fba4a118b16a62658bfa76bf90b91b801be63250)

I'm using a GeForce GTX 1070 with 8GB, which is the same I used in 0.7.

In the previous 0.7 version I was able to pre-train the model using a batch size of 64. In the 1.0 version I got an out of memory error before starting the training:

> epoch  train_loss  valid_loss  accuracy
Traceback (most recent call last):------------------------------| 0.00% [0/62991 00:00<00:00]

With a batch size of 32, I got an out of memory error in this point:

> epoch  train_loss  valid_loss  accuracy
Traceback (most recent call last):------------------------------| 1.67% [2099/125983 07:45<7:38:01 3.4529]

![memory_consumption_epoch1_bs32](https://user-images.githubusercontent.com/12713359/48891113-bb63a000-ee21-11e8-8a30-31726f38cd60.png)

Then I ran with a batch size of 16, and these were the checkpoints I measured the memory consumption (the _python_ process is the one getting tracked):

First checkpoint, at start:
![memory_consumption_epoch1_bs16](https://user-images.githubusercontent.com/12713359/48891167-d6361480-ee21-11e8-88ff-619bc540f1a9.png)

Epoch 1, 0.67%:
![memory_consumption_epoch1_bs16_0 67](https://user-images.githubusercontent.com/12713359/48891168-d6ceab00-ee21-11e8-8006-f4a33fb0a863.png)

Epoch 1, 1.28%:
![memory_consumption_epoch1_bs16_1 28](https://user-images.githubusercontent.com/12713359/48891169-d6ceab00-ee21-11e8-88cb-15235b4ead6d.png)

Epoch 1, 2.37%:
![memory_consumption_epoch1_bs16_2 37](https://user-images.githubusercontent.com/12713359/48891171-d6ceab00-ee21-11e8-9725-5b8109488f52.png)

Epoch 1, 19.21%:
![memory_consumption_epoch1_bs16_19 21](https://user-images.githubusercontent.com/12713359/48891173-d6ceab00-ee21-11e8-90cb-00b4adad5e89.png)

Epoch 1, 27.33%:
![memory_consumption_epoch1_bs16_27 33](https://user-images.githubusercontent.com/12713359/48891174-d7674180-ee21-11e8-9446-ac6ecd5aa4e8.png)

Epoch 1, 32.00%:
![memory_consumption_epoch1_bs16_32 00](https://user-images.githubusercontent.com/12713359/48891176-d7674180-ee21-11e8-8bb6-84010b20e40c.png)

Epoch 2, 46.78%:
![memory_consumption_epoch2_bs16_46 78](https://user-images.githubusercontent.com/12713359/48891178-d7674180-ee21-11e8-8f60-16b1ff4bcaea.png)

Epoch 7, 18.56%:
![memory_consumption_epoch7_bs16_18 56](https://user-images.githubusercontent.com/12713359/48891179-d7ffd800-ee21-11e8-9097-102ef2208eed.png)

Epoch 7, 69.33%:
![memory_consumption_epoch7_bs16_69 33](https://user-images.githubusercontent.com/12713359/48891180-d7ffd800-ee21-11e8-922a-ed5e7a19e249.png)

Epoch 8, 81.59%:
![memory_consumption_epoch8_bs16_81 59](https://user-images.githubusercontent.com/12713359/48891181-d7ffd800-ee21-11e8-89c9-08e6d00d5da7.png)

Epoch 9, 34.43%:
![memory_consumption_epoch9_bs16_34 43](https://user-images.githubusercontent.com/12713359/48891182-d8986e80-ee21-11e8-9236-158e4db67ca6.png)

Epoch 10, 42.30%:
![memory_consumption_epoch10_bs16_42 30](https://user-images.githubusercontent.com/12713359/48891183-d8986e80-ee21-11e8-93c9-3488f3bf48dd.png)

**To Reproduce**

This the code I'm using for training, using the v1 codebase:

```
def pretrain(path, language_model_id, epochs, batch_size, use_ids=True):
    if use_ids:
        data_lm = TextLMDataBunch.from_id_files(path=path, train='train', valid='valid', test='test', max_vocab=60000,
                                        min_freq=2, n_labels=0, chunksize=24000, bs=batch_size)
    else:
        data_lm = TextLMDataBunch.from_csv(path=path, tokenizer=Tokenizer(lang='pt'), train='train', valid='valid',
                                   test='test', max_vocab=60000, min_freq=2, n_labels=0, chunksize=24000)

    learn = RNNLearner.language_model(data_lm, drop_mult=0.5)

    lr = float(1e-3)

    learn.fit(epochs=epochs, lr=slice(lr / 2.6, lr), wd=1e-7)
    learn.save(language_model_id)
```

I used 16 for the batch size.

**Expected behavior**

For v0.7 I was able to use a bs 64 for the pre-training, but for v1, I had to lower to 16, using the same hardware. And even with 16, sometimes I get to the edge of memory consumption. 

**Additional context**

For this last execution using a bs of 16 the pre-training finished ok, but the last time I tried this, I eventually got an error around epoch 10. Besides,

**Comment by matiu2** [comment]
I've seen a similar thing, but during the tokenization `process` phase. I got around it by tokenizing it myself, and not using numpy arrays; just using plain old python lists actually halved the memory usage.

After tokenizing, you can call 'TextDataBunch.from_tokens'.

Without that work around, the process grew up to 24 GB within about an hour of going through the full aclImdb.

I don't know how related this is.

@pvcastro you might try using a [python memory profiler](https://stackoverflow.com/questions/110259/which-python-memory-profiler-is-recommended) to find the source of the bad behaviour:

**Comment by pvcastro** [comment]
Hi there @matiu2 ! 

Your suggestion applies only to RAM consumption, right? My scenario is regarding the GPU, I'm running out of CUDA memory. I had no problems with RAM.
Yesterday I tried running the ULMFiT pre-training with the same dataset, using a batch size of 80 on a Tesla P100 with 16Gb of memory, but I got the CUDA error: out of memory right in the second epoch:

```
1      1.659578    2.702391    0.505284                                                                      
Traceback (most recent call last):███---------------------------| 47.90% [24138/50393 1:48:07<1:57:37 1.6910]
  File "legal_docs_preprocessing.py", line 37, in <module>
    if __name__ == '__main__': fire.Fire(pretrain)
  File "/home/ubuntu/anaconda3/envs/fastai/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/ubuntu/anaconda3/envs/fastai/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/ubuntu/anaconda3/envs/fastai/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "legal_docs_preprocessing.py", line 26, in pretrain
    learn.fit(epochs=epochs, lr=lr, wd=1e-7)
  File "/home/ubuntu/repositorios/fastai/fastai/basic_train.py", line 137, in fit
    callbacks=self.callbacks+callbacks)
  File "/home/ubuntu/repositorios/fastai/fastai/basic_train.py", line 89, in fit
    raise e
  File "/home/ubuntu/repositorios/fastai/fastai/basic_train.py", line 79, in fit
    loss = loss_batch(model, xb, yb, loss_func, opt, cb_handler)[0]
  File "/home/ubuntu/repositorios/fastai/fastai/basic_train.py", line 26, in loss_batch
    loss.backward()
  File "/home/ubuntu/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ubuntu/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: out of memory
```

**Comment by matiu2** [comment]
@pvcastro yes, in my situation, it's before it even gets to the CUDA; purely in the tokenization stage

**Comment by sgugger** [comment]
Closing this since it's been a while with no news, please reopen if needed.
