### ISSUE TITLE
language_model_learner fails when using nn.parallel (multi-GPU).

### ISSUE THREAD

**Issue by gsgbills** [fastai/fastai#1231]
**Describe the bug**

**language_model_learner** reports ```AttributeError: 'DataParallel' object has no attribute 'reset' ``` in learners (callbacks?) after using `nn.parallel` in `language_model_learner`.

----> 3 learn.fit(1)

~/anaconda3/lib/python3.7/site-packages/fastai/basic_train.py in fit(self, epochs, lr, wd, callbacks)
    160         callbacks = [cb(self) for cb in self.callback_fns] + listify(callbacks)
    161         fit(epochs, self.model, self.loss_func, opt=self.opt, data=self.data, metrics=self.metrics,
--> 162             callbacks=self.callbacks+callbacks)
    163 
    164     def create_opt(self, lr:Floats, wd:Floats=0.)->None:

~/anaconda3/lib/python3.7/site-packages/fastai/basic_train.py in fit(epochs, model, loss_func, opt, data, callbacks, metrics)
     92     except Exception as e:
     93         exception = e
---> 94         raise e
     95     finally: cb_handler.on_train_end(exception)
     96 

~/anaconda3/lib/python3.7/site-packages/fastai/basic_train.py in fit(epochs, model, loss_func, opt, data, callbacks, metrics)
     78         for epoch in pbar:
     79             model.train()
---> 80             cb_handler.on_epoch_begin()
     81 
     82             for xb,yb in progress_bar(data.train_dl, parent=pbar):

~/anaconda3/lib/python3.7/site-packages/fastai/callback.py in on_epoch_begin(self)
    197         "Handle new epoch."
    198         self.state_dict['num_batch'] = 0
--> 199         self('epoch_begin')
    200 
    201     def on_batch_begin(self, xb:Tensor, yb:Tensor, train:bool=True)->None:

~/anaconda3/lib/python3.7/site-packages/fastai/callback.py in __call__(self, cb_name, call_mets, **kwargs)
    185         "Call through to all of the `CallbakHandler` functions."
    186         if call_mets: [getattr(met, f'on_{cb_name}')(**self.state_dict, **kwargs) for met in self.metrics]
--> 187         return [getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs) for cb in self.callbacks]
    188 
    189     def on_train_begin(self, epochs:int, pbar:PBar, metrics:MetricFuncList)->None:

~/anaconda3/lib/python3.7/site-packages/fastai/callback.py in <listcomp>(.0)
    185         "Call through to all of the `CallbakHandler` functions."
    186         if call_mets: [getattr(met, f'on_{cb_name}')(**self.state_dict, **kwargs) for met in self.metrics]
--> 187         return [getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs) for cb in self.callbacks]
    188 
    189     def on_train_begin(self, epochs:int, pbar:PBar, metrics:MetricFuncList)->None:

~/anaconda3/lib/python3.7/site-packages/fastai/callbacks/rnn.py in on_epoch_begin(self, **kwargs)
     16 
     17     def on_epoch_begin(self, **kwargs):
---> 18         self.learn.model.reset()
     19 
     20     def on_loss_begin(self, last_output:Tuple[Tensor,Tensor,Tensor], **kwargs):

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __getattr__(self, name)
    523                 return modules[name]
    524         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 525             type(self).__name__, name))
    526 
    527     def __setattr__(self, name, value):

AttributeError: 'DataParallel' object has no attribute 'reset'

**To Reproduce**

```python
from fastai.text import *
path = untar_data(URLs.IMDB_SAMPLE)
data = TextLMDataBunch.from_csv(path, 'texts.csv')
learn = language_model_learner(data)
learn.model = torch.nn.DataParallel(learn.model, device_ids=[0,1])
learn.fit(1)
```
**Expected behavior**

I expected that the learner will be able to work fine, ie use both GPUs, as it does for create_cnn and tabular_learner.
**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
Should be fixed by [this commit](https://github.com/fastai/fastai/commit/f7d97d19487119c18f4ec788883890a8ca321602).
