### ISSUE TITLE
TextClasDataBunch Input Type Different from Target Type

### ISSUE THREAD

**Issue by syb0rg** [fastai/fastai#1233]
**Describe the bug**
The dtype of the input tensor is different from the target tensor, both created by the fastai library.

```
return (input==targs).float().mean()
RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'other'
```

Changing that line to the following allows the code to work as expected:
```
return (input.float()==targs.float()).float().mean()
```
But this is just a temporary hack, a better more official fix should be made.

**To Reproduce**
Attempting to build a seq2seq network with the VCTK dataset:

```
from fastai import *
from fastai.text import *
from pathlib import Path
from scipy.io import wavfile
import IPython
import collections
from torchtext import vocab, data
import numpy as np
import pickle
import pandas as pd
import librosa
import random

PATH = Path('data/VCTK-Corpus')
TEXT = Path('txt')
AUDIO = Path('wav48')
SPEAKER = Path('p278')
TMP_PATH = PATH/'tmp'
TMP_PATH.mkdir(exist_ok=True)

spk_txt = [open(f).read().strip() for f in sorted((PATH/TEXT/SPEAKER).iterdir())]

Audio = collections.namedtuple('Audio', 'sample_rate, data')
spk_audio = [Audio(*wavfile.read(f)) for f in sorted((PATH/AUDIO/SPEAKER).iterdir())]

df = pd.DataFrame({
        'label':[a.data for a in spk_audio],
        'text':spk_txt
    })

data_lm = TextLMDataBunch.from_df(PATH, df, df, bs=8)
data_clas = TextClasDataBunch.from_df(PATH, df, df, vocab=data_lm.train_ds.vocab, bs=8)

learn = language_model_learner(data_lm, pretrained_model=URLs.WT103, bptt=25, callback_fns=ShowGraph)
moms = (0.8,0.7)
learn.fit_one_cycle(1, slice(1e-2), moms=moms)
learn.unfreeze()
learn.fit_one_cycle(1, slice(1e-3,1e-2), moms=moms)
learn.save_encoder('enc')
learn = text_classifier_learner(data_clas)
learn.load_encoder('enc')
learn.freeze()
learn.fit_one_cycle(1, moms=moms)
```

**Expected behavior**
The generated input and target tensors should be of the same type.  I'm probably abusing how these classes are meant to be used too, maybe an official seq2seq example would be helpful as well?

**Additional context**
```
> x, y = next(iter(data_clas.train_dl))
> x.dtype, y.dtype
(torch.int64, torch.float32)
```

**Comment by sgugger** [comment]
There's no seq2seq implemented in fastai yet, that's in development. If your inputs and/or targets aren't loaded as you wish it's probably because you didn't load your data properly. It's very likey that TextLMDataBunch or TextClasDataBunch won't work for seq2seq, you should use the data block API.
In any case, this will be better discussed on the [forum](https://forums.fast.ai).

**Comment by syb0rg** [comment]
@sgugger Data was loaded correctly into the data-frame as far as I saw, visualization steps were taken out of the given example for brevity.  Visualizing x and y looked fine too, other than the data types being inconsistent.  While seq2seq may not be supported, I do think this is a legitimate bug that will pop up again in the future.
