### ISSUE TITLE
ModuleNotFoundError: No module named 'fastai.callbacks.loss_metrics'

### ISSUE THREAD

**Issue by gerardogarciag1** [fastai/fastai#1235]
**Describe the bug**

 https://forums.fast.ai/t/fastai-v1-install-issues-thread/24111/191

C:\Users\gerar\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Pool size changed, may indicate binary incompatibility. Expected 48 from C header, got 64 from PyObject
  return f(*args, **kwds)
C:\Users\gerar\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Address size changed, may indicate binary incompatibility. Expected 24 from C header, got 40 from PyObject
  return f(*args, **kwds)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gerar\fastai\fastai\__init__.py", line 10, in <module>
    from .train import *
  File "C:\Users\gerar\fastai\fastai\train.py", line 3, in <module>
    from .callbacks import *
  File "C:\Users\gerar\fastai\fastai\callbacks\__init__.py", line 11, in <module>
    from .loss_metrics import *
ModuleNotFoundError: No module named 'fastai.callbacks.loss_metrics'
>>>
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
Solved now.
