### ISSUE TITLE
TextClasDataBunch.from_ids sometimes create unusable databunches.

### ISSUE THREAD

**Issue by PiotrCzapla** [fastai/fastai#1238]
**Describe the bug**
In some situations, the `learn.fit` that runs on a databunch created by `TextClasDataBunch.from_ids` will throw the following error:
```
File "/home/pczapla/workspace/_oss/fastai/fastai/fastai/text/data.py", line 90, in pad_collate
    if pad_first: res[-len(s[0]):,i] = LongTensor(s[0])
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: double, float, float16, int64, int32, and uint8.
```

**To Reproduce**
This code throws an error
```
def test_from_ids_works_for_equally_length_sentences():
    ids = [np.array([0])]*10
    lbl = [0]*10
    data = TextClasDataBunch.from_ids('/tmp', vocab=Vocab({0: BOS, 1:PAD}),
                                      train_ids=ids, train_lbls=lbl,
                                      valid_ids=ids, valid_lbls=lbl, classes={0:0})
    text_classifier_learner(data).fit(1)
```
The following will work fine
```
def test_from_ids_works_for_variable_length_sentences():
    ids = [np.array([0]),np.array([0,1])]*5 # notice diffrent number of elements in arrays
    lbl = [0]*10
    data = TextClasDataBunch.from_ids('/tmp', vocab=Vocab({0: BOS, 1:PAD}),
                                      train_ids=ids, train_lbls=lbl,
                                      valid_ids=ids, valid_lbls=lbl, classes={0:0})
    text_classifier_learner(data).fit(1)
```

**Additional context**
The issue is caused by a subtle "feature" of numpy, that can cast an object array of int arrays to one ndarray of objects. It is best shown by example:
```
>>> a = array([array([0]), array([0,1])], dtype=object); a
array([array([0]), array([0, 1])], dtype=object) # is an object array of int arrays
>>> b = array([array([0]), array([0])], dtype=object); b
array([[0],
       [0]], dtype=object) # becomes 2d ndarray of objects
>>> a[0].dtype
dtype('int64')
>>> b[0].dtype
dtype('O')
````
The array is converted to ndarray in the `ItemList` constructor.  Here:
https://github.com/fastai/fastai/blob/master/fastai/data_block.py#L45

The issue seems to be very exotic but it can be easily triggered when one write tests.
It took me quite some time to understand what is going on, as I haven't notice at first that the `array` becomes `ndarray`. 

I can propose a fix by adding a postprocessor to TextClasDataBunch.from_ids that converst the ndarray to object array of arrays of ints. Or we can simply add assert to warn ppl when this behaviour occurs. What do you prefer?

**Comment by sgugger** [comment]
Maybe do the conversion to object in from_ids, no need for a preprocessor I think. Can you add your unit test in the same PR?

**Comment by PiotrCzapla** [comment]
@sgugger would you mind if I put it to the same PR  #1239, we have it already merged to our version of fastai as our tests are using the fixes, so having two separate branches will just make things more complex to maintain and merge in the future.
