### ISSUE TITLE
TextClasDataBunch classes error

### ISSUE THREAD

**Issue by alibaltschun** [fastai/fastai#1245]
hello, i have a problem with TextClasDataBunch.
i tried open my csv file that contains 5 classes [0,1,2,3,5].
but imageClassDataBunch real only 4 classes.

i was tried using header and non-header in csv file but still have the same problem

this my csv file
```
df = pd.DataFrame.from_csv(PATH_DATASET/'datatrain-en.csv',header=-1,index_col=False)
df.columns=['label','text']
df.label.value_counts()
3    18442
2    18346
5    10294
1     1479
0      923
Name: label, dtype: int64

df.head()

label | text
-- | --
1 | belfile upload tuga revisi fg
1 | file upload tuga pre fg
1 | file upload sisfo tuga
1 | secur alert link googl account
1 | secur alert link googl account

```

and this the problem

```
data_clas = TextClasDataBunch.from_csv(PATH_DATASET, 'datatrain-en.csv')
data_clas.train_ds.y.classes
[2, 3, 5, 0]
data_clas.valid_ds.y.classes
[2, 3, 5, 0]

```

thanks for helping

**Comment by sgugger** [comment]
This might happen because the class 1 doesn't appear in your validation set: by default there is a random split and maybe you were unlucky and it wasn't picked. You can pass classes=bla if you want to fix the classes to use.
