### ISSUE TITLE
Documentation syntax issue

### ISSUE THREAD

**Issue by markgoodhead** [fastai/fastai#1246]
Apologies if this isn't the right place to put this (if it's not please direct me to the correct place!), but I think I've found some possibly obsoleted syntax in the documentation. On https://docs.fast.ai/vision.html there's a line:

`data = ImageDataBunch.from_folder(path, ds_tfms=(tfms, []))`

And the text references passing in the tuple of (train_tfms, valid_tfms). However, when I tried this example in a notebook using the tuple threw an obscure error whereas this code works fine (or appears to!):

`data = ImageDataBunch.from_folder(path, ds_tfms=tfms)`

Is the documentation incorrect or am I missing something?

**Comment by sgugger** [comment]
Docs run without any problem here. Are you sure you have the latest version of fastai?
