### ISSUE TITLE
mistake in the docs for tabular learner: range instead of slice for valid_idx

### ISSUE THREAD

**Issue by pchronz** [fastai/fastai#1249]
**Describe the bug**

The docs for fastai_v1 state that one should use `valid_idx = range(...)`, which results in an error. Instead one should use `valid_idx = slice(...)`. 

**To Reproduce**

Read the docs and type in the code ;)
[https://docs.fast.ai/tabular.html](https://docs.fast.ai/tabular.html)

> To split our data into training and validation sets, we use valid indexes
> 
> `valid_idx = range(len(df)-2000, len(df))`
> 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
Doc notebooks run without any issue here. Are you sure it's not an install issue?
