### ISSUE TITLE
Use of import *  in the fastai library 

### ISSUE THREAD

**Issue by yashu-seth** [fastai/fastai#125]
Hello everyone.

I was going through the fastai GitHub repository to understand the internal working. I noticed that almost everywhere import * has been used. I believe that it makes understanding the codebase difficult. [(Why is import * bad)](https://stackoverflow.com/questions/2386714/why-is-import-bad)

If you also feel that the wildcard imports should be done away with, let me know I would be happy to submit a PR to try and fix this.

Thanks.

**Comment by macsermkiat** [comment]
Jeremy had pointed that out somewhere in the VDO. Import *might be bad generally. But for datascience work, it helps in better workflow.

**Comment by kongscn** [comment]
I would expect a more normal kind of python at least in the `fastai` package. Being easy to read and understand is more import than making it some lines shorter, the mental model decides how *long* or *difficult* a script is. But it looks like a new language at first glance 😢. 

With `import *` I don't know something comes from which file, or from another package like torch. It's really more difficult to get a quick picture of a file even with IDE. and feels fragile.

**Comment by iskode** [comment]
Jeremy plans to make the lib more documented, but he showed some tip to know where a class or function comes from:
``?unknown_function + Enter

**Comment by jeremyjordan** [comment]
@macsermkiat i'm sorry, but you can elaborate on why `import *` can improve the data science workflow? it severely hinders readability.

**Comment by jph00** [comment]
Configure your editor or IDE to display this info and/or jump to the token. That's a computer's job, not a human's :)

If you're just browsing the code online thru github, install the sourcetree chrome extension to get the same functionality (in-project only).

**Comment by dbook-kkbrandt** [comment]
Wow, thank you for pointing us to this chrome extension - this is seriously the most useful Chrome extension I've ever seen, and it works wonderfully!
https://chrome.google.com/webstore/detail/sourcegraph-for-github/dgjhfomjieaadpoljlnidmbgkdffpack
