### ISSUE TITLE
from_folder needs to assert on an empty folder

### ISSUE THREAD

**Issue by stas00** [fastai/fastai#1252]
We need to have a more defensive functionality in data classes. from_folder() on an empty folder (and non-existing?) returns a DataBunch object with no data in it, which when fed to pytorch later in the code generates various error messages like `IndexError: index 0 is out of bounds for axis 0 with size 0` that can be avoided at an earlier stage, by indicating to the user that the folder they are trying to get data from is empty.

I see there are multiple versions of `from_folder` for different data classes. So perhaps this should be done once for all of them, and perhaps the same for other `from_` methods? Basically assert if the number of items is 0?

Do you think someone will want for this situation to not throw an exception? Then perhaps by default it should complain, but have an option to override?

**Comment by sgugger** [comment]
You want to be able to create empty ItemList (for inference for instance) so it can't be checked in the __init__ method. Let me think about this.

**Comment by stas00** [comment]
And it surely should assert on non-existing folders. This shouldn't succeed, but it does:

`il = ImageItemList.from_folder('galkjasdljkasdfasd')`

**Comment by stas00** [comment]
Here is another related problem along the same issue (not checking folder exists/has items):

```
data = (ImageItemList.from_folder(mnist)
        .split_by_folder()          
        .label_from_folder()
        .transform(tfms, size=32)
        .databunch()
        .normalize(imagenet_stats)) 
```
if 'valid' folder doesn't exist, the user gets:

"IndexError: index 0 is out of bounds for axis 0 with size 0"

instead of "valid folder is missing from {path}" or something like that.

to reproduce, delete `fastai/data/mnist_tiny/valid`.
