### ISSUE TITLE
RuntimeError: you can only change requires_grad flags of leaf variables.

### ISSUE THREAD

**Issue by sdezoete** [fastai/fastai#1259]
**Describe the bug**
learn = language_model_learner(data_lm, pretrained_model=URLs.WT103_1) throws the following error:

RuntimeError: you can only change requires_grad flags of leaf variables. If you want to use a computed variable in a subgraph that doesn't require differentiation use var_no_grad = var.detach().

**To Reproduce**
The code is the provided example: "text.ipynb"

**Expected behavior**
No RuntimeError

**Screenshots**
N/A

**Additional context**
N/A

**Comment by sgugger** [comment]
Are you sure you have the right version of fastai? I just ran the notebook without any issue. Please use the [forum](https://forums.fast.ai/) for installation troubleshooting.
