### ISSUE TITLE
Bad quality of texts obtained from predict method for LanguageLearner

### ISSUE THREAD

**Issue by festeh** [fastai/fastai#1264]
**Describe the bug**
Hi!
The `predict`method for LanguageLearner class seems not to be correct. 

Firstly, the diversity of generated texts decreases while raising the temperature - that doesn't correspond to common sense. I'd suggest to call `res.pow_(1 / (temperature + eps))` instead of `res.pow_(temperature)`

The other minor issue is that master_bar cannot be silenced - sometimes there's no need to see "Total time:" message.

But, most importantly, this method does not seem to produce texts with good quality - i tried to vary temperature with no success. Then I wrote own implementation. It relies on `Multinomial` class and low-level call to `learn.model` and seem to produce better texts overall and with `temperature=1` in particular.

**To Reproduce**

```
from fastai import *
from fastai.text import *
import torch


path = untar_data(URLs.IMDB_SAMPLE)
data_lm = TextLMDataBunch.from_csv(path, 'texts.csv')

learn = language_model_learner(data_lm, pretrained_model=URLs.WT103, drop_mult=0.5)
learn.fit_one_cycle(5, 1e-2)

TEXT = "the movie was"
N_WORDS = 10
N_SENTENCES = 5

print("LanguageLearner predict from 1.0.29:")
print("\n".join(learn.predict(TEXT, N_WORDS) for _ in range(N_SENTENCES)))

print("LanguageLearner predict from 1.0.29 with less diverse texts:")
print("\n".join(learn.predict(TEXT, N_WORDS, temperature=2) for _ in range(N_SENTENCES)))


def custom_predict_language_learner(model, text,  n_words, temperature=1):
    ds = learn.data.single_dl.dataset
    learn.model.eval()
    for _ in range(n_words):
        ds.set_item(text)
        x, _ = next(iter(ds))
        x = torch.tensor(x, device="cuda").view(-1, 1)
        res = learn.model(x)[0][-1]
        ds.clear_item()
        res /= temperature
        idx = torch.distributions.Multinomial(logits=res, total_count=1).sample((1, )).argmax().item()
        text += f' {learn.data.vocab.itos[idx]}'
    return text

print("Custom implementation of predict:")
print("\n".join(custom_predict_language_learner(learn.model, TEXT, N_WORDS) 
                for _ in range(N_SENTENCES)))

print("Custom implementation of predict with lower temperature:")
print("\n".join(custom_predict_language_learner(learn.model, TEXT, N_WORDS, temperature=0.7) 
                for _ in range(N_SENTENCES)))
```

**Results**

**LanguageLearner predict from 1.0.29:**
the movie was pushed the independent demonstrated this activity in their home run
the movie was a few years before remembering how the of this effort
the movie was so many years , when they morse part of the
the movie was another small fails to the army fight 's " xxup
the movie was described by precise bands lacking in a concept and more
**LanguageLearner predict from 1.0.29 with less diverse texts:**
the movie was the " xxup ii of the " a " the
the movie was a few years later , and the " a series
the movie was a few years later in " xxup wwii . "
the movie was a single - a few years later in order of
the movie was also included a new , in the previous to the
**Custom implementation of predict:**
the movie was positive to the critics . in addition to marrying each
the movie was her masterpiece . i love the stars and turn them
the movie was xxunk to me upon the film . i 've '
the movie was highly recommended and i had stuck with people until edges
the movie was released . xxmaj the original claim to the movie .
**Custom implementation of predict with lower temperature:**
the movie was released in 1949 and became the first feature film to
the movie was released in 1948 and was also available with xxup vhs
the movie was released in 1948 . it stars xxunk xxmaj xxunk and
the movie was based on the novel . xxmaj xxunk , a talented
the movie was also based on a novel by xxmaj pulp xxmaj xxmaj

So is there such problem with `predict` method?
Thanks!

**Comment by jph00** [comment]
Many thanks for noticing this - the issue is the missing `.view(-1, 1)` in our code. We'll fix it. And you temperature suggestion seems reasonable too.

**Comment by sgugger** [comment]
Thanks for all of this! I also added a reset of the hidden state.
