### ISSUE TITLE
Fbeta_binary and other classifiers don't work

### ISSUE THREAD

**Issue by pchronz** [fastai/fastai#1271]
**Describe the bug**

```
learn = text_classifier_learner(data_cls, drop_mult=0.2, metrics=[accuracy, Fbeta_binary(beta2=1)])
```
leads to two errors. 

1. there's a missing `self.` for `clas` in the implementation of Fbeta_binary itself. 
Fix with:
```
 64     def on_batch_end(self, last_output, last_target, **kwargs):
 65         y_pred = last_output.argmax(dim=1)
 66         y_true = last_target.float()
 67
 68         self.TP += ((y_pred==self.clas) * (y_true==self.clas)).float().sum()
 69         self.total_y_pred += (y_pred==self.clas).float().sum()
 70         self.total_y_true += (y_true==self.clas).float().sum()
```
2. afterwards there's a problem in `CallbackHandler` when checking whether the metric is an instance of `Callback`. This doesn't work because the `Callback` class is loaded dynamically. 
One fix would be: 
```
187         import fastai.callbacks
188         self.metrics = [(met if isinstance(met, fastai.callbacks.Callback) else AverageMetric(met))
189                         for met in self.metrics]
```
That'll work. Otherwise one would have to reimplement `isinstance` based on the class names.

**Comment by wy-q** [comment]
hey, you're my first customer :) I actually didn't expect anyone to use this metric, which originated as a callback.

1. You're right. It's missing a `self.clas`

2. I suspect it being a callback, you would likely have to do it this way to use it immediately:

```
learn = text_classifier_learner(data_clas, drop_mult=0.5)
learn.load_encoder('fine_tuned_enc')
learn.metrics=[accuracy, Fbeta_binary(beta2=1,clas = 1)]
``` 
Or if you want F1 for label 0

```
learn = text_classifier_learner(data_clas, drop_mult=0.5)
learn.load_encoder('fine_tuned_enc')
learn.metrics=[accuracy, Fbeta_binary(beta2=1,clas = 0)]
```

**Comment by sgugger** [comment]
Fixed the clas thing, not really sure what the problem is in the second point. The `Callback` class is loaded at this point.

**Comment by pchronz** [comment]
Thanks for the fix.
The second issue was a false alarm. While debugging I've changed the callback module without restarting the kernel, which then led to the issue of the two CallBack classes not being the same.
