### ISSUE TITLE
LabelList.from_lists passes path to the y argument of LabelList.__init__

### ISSUE THREAD

**Issue by yasrynn** [fastai/fastai#1275]
**Describe the bug**

The constructor call in `LabelList.from_lists` is incompatible with the constructor's signature.

**To Reproduce**

`from fastai.data_block import *`
`LabelList.from_lists(".",[0],[0])` produces an `AttributeError` trying to access the `x` attribute of ".".

**Expected behavior**

The call to the constructor should probably look something like:
`return cls(inputs,labels,path=path)` to avoid mismatched positional arguments, but this still isn't quite right because `LabelList.__init__` never processes a `path` argument.

**Comment by sgugger** [comment]
Oh this is legacy code that we forgot to remove. Just did, thanks for flagging!
