### ISSUE TITLE
LabelList splits result in ItemLists with discarded labels.

### ISSUE THREAD

**Issue by yasrynn** [fastai/fastai#1276]
**Describe the bug**

Various split methods accessible in `LabelList` behave in unexpected ways.  

Calling `random_split_by_pct` from a `LabelList` produces an `ItemLists` with no labels associated with the training or validation sets.  `split_by_idx` and `split_by_idxs` suffer from similar issues.

**To Reproduce**

`_ll = LabelList(ItemList([1,2,3,4]),ItemList([5,6,7,8]))`
`_lls = _ll.random_split_by_pct(valid_pct=.5)`
`type(_lls)`
`_lls.train`
`_lls.valid`

**Expected behavior**

Calling `random_split_by_pct` from a `LabelList` should produce a `LabelLists` with labels correctly associated within the `train` and `valid` sets.

**Additional context**

Presumably the default purpose of splitting an `ItemList` into training and validation sets is when it is a `LabelList`, otherwise splitting must be done in the same way repeatedly on the `ItemList` for the data and the `ItemList` for the labels, and if this is done with `random_split_by_pct`, the data and labels will be mismatched.  

The primary problem appeared to be that the splitting is delegated to the class `_split` attribute which is set in `ItemList.__init__` and not overridden in the subclass.  However, manually setting `myLabelList._split = LabelLists` does not fix the problem.  On the other hand, manually unrolling `random_split_by_pct`, `split_by_idx`, and `split_by_idxs` *does* seem to fix the problem, and I can't for the life of me tell why.

**Comment by sgugger** [comment]
We have decided to stick with the order split then label (note that you can do no_split) and there is now an assertion error when you don't respect it. Closing this issue.
