### ISSUE TITLE
learn.get_preds(ds_type = DatasetType.Train) sorted differently than learn.data.train_ds.to_df()

### ISSUE THREAD

**Issue by ahue** [fastai/fastai#1277]
**Describe the bug**

I'd like to track predictions back to their observations. Seems like the target values (learn.data.train_ds.y) are not sorted the same way the predictions are (learn.get_preds(ds_type = DatasetType.Train)). This also applies for the learn.data.train_ds.to_df() which gives access to the file names, which i wanted to use for grouping observations (based on certain attributes) in the file name.

Seems to be related to: https://github.com/fastai/fastai/issues/975 ; which was marked as closed for the RNN learner.

**To Reproduce**

```
df_train = pd.DataFrame({
   "proba": preds_train[0].numpy()[:,0:1].flatten(),
   "pred_act": preds_train[1].numpy(),
   "actual": [l.data for l in learn.data.train_ds.y]
})

df_train_fix = pd.DataFrame({
   "proba": preds_train[0].numpy()[:,0:1].flatten(),
   "pred_act": preds_train[1].numpy(),
   "actual": [l.data for l in learn.data.train_ds.y[train_sampler]]
})

df_valid = pd.DataFrame({
   "proba": preds_valid[0].numpy()[:,0:1].flatten(),
   "pred": [0 if v>0.5 else 1 for v in preds_valid[0].numpy()[:,0:1].flatten()],
   "pred_act": preds_valid[1].numpy(),
   "actual": [l.data for l in learn.data.valid_ds.y]
})

print(interp_train.confusion_matrix())
print(np.diag(interp_train.confusion_matrix()).sum())
print((df_train["pred_act"]==df_train["actual"]).sum()) # should equal the diagonal of confusion matrix - DOES NOT
print((df_train_fix["actual"]==df_train_fix["pred_act"]).sum()) # should equal the diagonal of confusion matrix - DOES NOT


print(interp_valid.confusion_matrix())
print(np.diag(interp_valid.confusion_matrix()).sum())
print((df_valid["pred"] == df_valid["actual"]).sum()) # equals the diagonal of confusion matrix...
print((df_valid["pred_act"] == df_valid["actual"]).sum()) # should equal the diagonal of confusion matrix - DOES NOT
```

**Expected behavior**
learn.get_preds(ds_type = DatasetType.Train) should be sorted like learn.data.train_ds.y

**Additional context**
Using:
* torch-nightly-1.0.0.dev20181202
* fastai-1.0.31

**Comment by sgugger** [comment]
You have to pass `ordered=True` to get your predictions ordered like the items.

**Comment by ahue** [comment]
Getting `TypeError: get_preds() got an unexpected keyword argument 'ordered' ;`

```
path = untar_data(URLs.MNIST_SAMPLE)
data = ImageDataBunch.from_folder(path)
learn = create_cnn(data, models.resnet18, metrics=accuracy)
learn.fit(1)

preds_train = learn.get_preds(ds_type = DatasetType.Train, ordered=True)
```
seems only implemented in _fastai/text/learner.py_ yet but not in  _fastai/vision/learner.py_ and _fastai/basic_train.py_ ; 

* torch-nightly-1.0.0.dev20181202
* fastai-1.0.31

**Comment by jahody** [comment]
not in fastai.tabular either

**Comment by sgugger** [comment]
In both those situations, the predictions are ordered like the labels. It's only in text that the predictions are in a different order because we sort them by lengths before batching them.

**Comment by jahody** [comment]
I see, thank you

**Comment by sanjabh11** [comment]
Hi.. I'm working on multi-level image classification problem and need prediction level for all the images specified in a train dataset..I'm using the followings to create Data bunch…

**data = ImageDataBunch.from_folder(path, train=".", valid_pct=0.1,  ds_tfms=get_transforms(), size=224, num_workers=4).normalize(imagenet_stats)**
Getting the nice predictions, however prediction file is not having the image name but series of integers starting 0 , 1 ,2 ,3 etc..which is not matching with the training set name and order both. Pls note that image names are in text not numbers...Pls suggest what can be done.?

**Comment by sgugger** [comment]
Please use the [forum](https://forums.fast.ai) for debugging, GitHub issues are for bugs in the library only.

**Comment by sanjabh11** [comment]
Sure...just posted on the forum as suggested..
