### ISSUE TITLE
Wrong when train examples/cifar.ipyth

### ISSUE THREAD

**Issue by mengjiexu** [fastai/fastai#1282]
first I run the cifar.ipython and It shows the Error:
RuntimeError: DataLoader worker (pid 5924) exited unexpectedly with exit code 127. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

Then, I change the num workers to 0, It dead with no response.

**Comment by sgugger** [comment]
Sounds like an installation issue (also you might have to remove the .fp16() call). You should check the [forum]() and ask your question with more details in the [troubleshooting page](https://forums.fast.ai/).
