### ISSUE TITLE
Predict in LanguageLearner for low temperatuers does not reduce to argmax

### ISSUE THREAD

**Issue by festeh** [fastai/fastai#1283]
**Describe the bug**
Hi! Thanks for quick fix for  #1264! I also have a small question:  was it intended that even for lowest temperatures, samples obtained from `predict` in `LanguageLearner` are not the same sentence obtained from greedy agrmax sampling? If not, changing `res.div_(temperature)` to `res.pow_(1 / temperature)` helped in my experiments - with temperature=0.1 same sentence was produced.

**To Reproduce**
```
from fastai import *
from fastai.text import *


path = untar_data(URLs.IMDB_SAMPLE)
data_lm = TextLMDataBunch.from_csv(path, 'texts.csv')

learn = language_model_learner(data_lm, pretrained_model=URLs.WT103, drop_mult=0.5)
learn.fit_one_cycle(1, 1e-2)

TEXT = "the movie was"
N_WORDS = 10
N_SENTENCES = 5
# lower temperatures would result in numerical error
print("\n".join(learn.predict(TEXT, N_WORDS, temperature=1e-25) for _ in range(N_SENTENCES)))
```

**Results**
the movie was one of the biggest . a fan of the film
the movie was viewed by viewers as the reasons why the show was
the movie was filmed by the brothers north foot in the late 20th
the movie was then available to normal . stars of other films were
the movie was equally wild and taking place in georgia and georgia .

**Comment by sgugger** [comment]
No objection to try.
