### ISSUE TITLE
NameError: name 'ObjectDetectDataset' is not defined from v1.0.24

### ISSUE THREAD

**Issue by geopan** [fastai/fastai#1285]
fastai-1.0.24 -> 1.0.32

**Describe the bug**
ObjectDetectDataset isn't available anymore from version 1.0.24 (potentially 1.0.23) up to 1.0.32. This might be on purpose but since I haven't seen anything related in the CHANGE.md, I am opening this issue.

Please close if discussed elsewhere.

Regards

Guillaume

**Comment by sgugger** [comment]
All datasets have been removed and replaced by the data block API. You can find an example of use with object detection in the [ docs](https://docs.fast.ai/data_block.html#Examples-of-use) (you'll have to scroll down a bit, there's no direct link to this specific example).

**Comment by geopan** [comment]
Thank you for having pointed the example to me, exactly what I was looking for! Thx.
