### ISSUE TITLE
Pytorch and Torchvision Versions Incompatible? 

### ISSUE THREAD

**Issue by DivonC** [fastai/fastai#1290]
**Describe the bug**
The Pytorch version in the current environment.yml fastai file is set to pytorch<0.4, while the torchvision version is set to torchvision>=0.1.9. This seems to result in an incompatibility, because torchvision 0.2.1  models\resnet.py has a call to ‘kaiming_normal_’, which doesn't appear in pytorch 0.3.1. This causes the error described here: https://forums.fast.ai/t/attributeerror-module-torch-nn-init-has-no-attribute-kaiming-normal/29278. Should the environment.yml file be updated to use torchvision ==0.1.9?

**Comment by sgugger** [comment]
Seems like it would fix this. Would you mind making a PR for this?

**Comment by sgugger** [comment]
The PR was merged so closing this.
