### ISSUE TITLE
Windows compatible paths

### ISSUE THREAD

**Issue by Elli1993** [fastai/fastai#1291]
**Problems reading in own ItemLists due to the differences in path coding in Windows**

 I ran accross this in "https://github.com/fastai/fastai/blob/master/fastai/vision/data.py" line 281.

               res.items = np.char.add(np.char.add(f'{folder}/', res.items.astype(str)), suffix)

I want to read in my own dataset on my Windows PC but since paths are created using "f'{res.path}/'" it does not work right away. It could simply be changed to os.path.join or something comparable instead. I bet this shows up a lot more often in other places too.

**To Reproduce**
Run something like:

`data = (ImageItemList.from_csv(PATH, 'labels.csv', folder='folder', suffix='.png', cols='filename')`

on Windows. I used windows 10 with fastai 1.0.33.

**Comment by sgugger** [comment]
Not sure this should be an issue, usually python handles Windows \ pretty well when with string filenames. We'll keep this issue for when we delve in Windows support for fastai, probably in a couple of weeks.
