### ISSUE TITLE
Loading pretrained ULMFiT fails on version 1.0.32

### ISSUE THREAD

**Issue by cjmay** [fastai/fastai#1294]
Hi,

I was following the ULMFiT description [here](http://nlp.fast.ai/category/classification.html) and related notebooks [here](https://github.com/fastai/fastai/blob/master/courses/dl1/lesson4-imdb.ipynb) and [here](https://github.com/fastai/fastai/blob/master/courses/dl2/imdb.ipynb) to use the pretrained model and found that when I upgraded from fastai version 0.7.0 to 1.0.32 loading the pretrained model failed.  I'm running the following code in Python 3 after downloading the model files from [here](http://files.fast.ai/models/wt103/).  It ran fine in fastai 0.7.0 but when I upgraded to fastai 1.0.32 it threw an error:

```python
import pickle
import torch
from fastai.text import get_language_model
wgts = torch.load('fwd_wt103.h5', map_location=lambda storage, loc: storage)
itos = pickle.load(open('itos_wt103.pkl', 'rb'))
pad_token = itos.index('_pad_')
m = get_language_model(len(itos), 400, 1150, 3, pad_token)
m.load_state_dict(wgts)
```

(Please forgive me if I'm doing something dumb; based on the linked documentation and the code this seemed like a reasonable way to get the underlying pytorch module, but I could definitely be wrong.)

The error appears to be that the structure of the model changed:

```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    m.load_state_dict(wgts)
  File "/home/cmay14/anaconda3/envs/foo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SequentialRNN:
        Missing key(s) in state_dict: "0.encoder_dp.emb.weight", "0.rnns.0.weight_hh_l0_raw", "0.rnns.0.module.weight_hh_l0", "0.rnns.1.weight_hh_l0_raw", "0.rnns.1.module.weight_hh_l0", "0.rnns.2.weight_hh_l0_raw", "0.rnns.2.module.weight_hh_l0", "1.decoder.bias".
        Unexpected key(s) in state_dict: "0.encoder_with_dropout.embed.weight", "0.rnns.0.module.weight_hh_l0_raw", "0.rnns.1.module.weight_hh_l0_raw", "0.rnns.2.module.weight_hh_l0_raw".

```

This is disappointing, especially given that 0.7.0 depends on pytorch 0.3.  Has support for ULMFiT already ended?

Thanks,
Chandler

**Comment by sgugger** [comment]
If you're using fastai v1, you should check the [v1 docs](https://docs.fast.ai/). There is full support for ULMfit and a complete [overview here](https://docs.fast.ai/text.html).

**Comment by cjmay** [comment]
That looks great, thanks!  I'll take a look.
