### ISSUE TITLE
Unable to install with `python setup.py install`, possible `regex` version conflict

### ISSUE THREAD

**Issue by tallamjr** [fastai/fastai#1311]
Unable to install via `python setup.py install`

**Describe the bug**

error: regex 2018.11.22 is installed but regex==2018.01.10 is required
by {'fastai', 'spacy'}

**To Reproduce**

`pip install torch torchvision`
`pip install fastai`
`python setup.py install`

**Expected behavior**

This should run to completion without error

**Screenshots**

**Additional context**

**Comment by stas00** [comment]
Applied your fix, https://github.com/fastai/fastai/pull/1312, thank you.
