### ISSUE TITLE
Can I use to generate text?

### ISSUE THREAD

**Issue by abubakar-ucr** [fastai/fastai#1321]
Hi, 
In DL 2, there is a classification task, which uses a pre-trained language model, fine tune it and then for classification.

Can I use it for the following scenario, if yes how (in pytorch or fastai)?: [Based on my search, I could not find any methods for it]
1. Fine-tune the pre-trained language model on my own text corpus and then generate(sample) text.
2. Fine-tune the pre-trained language model on my own text corpus and then score any given text/sentence.
Thanks.

**Comment by sgugger** [comment]
Hi, please use the [forum](https://forums.fast.ai) for those questions. We want to keep the issues are limited to bugs in the library, thanks!

**Comment by abubakar-ucr** [comment]
Hi @sgugger, Thanks for pointing me to the proper forum. I posted it here: https://forums.fast.ai/t/can-i-use-fine-tuned-lms-to-generate-text/32548

However, if any of my scenarios is not implemented in fastai, it can be considered as a feature to include.
