### ISSUE TITLE
'WindowsPath' object is not iterable

### ISSUE THREAD

**Issue by find-happiness** [fastai/fastai#1327]
system : window 10
fastai : 1.0.36.post1

my code:
interper =  ClassificationInterpretation.from_learner(learner)
top_loss,idx =  interper.top_losses()
interper.plot_top_losses(4,figsize=(15,12))

TypeError                                 Traceback (most recent call last)
<ipython-input-39-0fc7e4f07038> in <module>
----> 1 interper.plot_top_losses(4,figsize=(15,12))

f:\workspace\python\fastai\fastai\vision\learner.py in plot_top_losses(self, k, largest, figsize)
    103         fig.suptitle('prediction/actual/loss/probability', weight='bold', size=14)
    104         for i,idx in enumerate(tl_idx):
--> 105             im,cl = self.data.valid_ds[idx]
    106             cl = int(cl)
    107             im.show(ax=axes.flat[i], title=

f:\workspace\python\fastai\fastai\data_block.py in __getitem__(self, idxs)
    512         # note: labels will be ignored if available in the test dataset
    513         items = self.x.__class__.from_folder(self.path / test_folder)
--> 514         return self.add_test(items.items, label=label)
    515 
    516     @classmethod

f:\workspace\python\fastai\fastai\data_block.py in __getitem__(self, idxs)
     93         self.processor = listify(self.processor)
     94         for p in self.processor: item = p.process_one(item)
---> 95         return item
     96 
     97     def analyze_pred(self, pred: Tensor):

f:\workspace\python\fastai\fastai\data_block.py in new(self, items, processor, **kwargs)
     88         return self
     89 
---> 90     def process_one(self, item, processor=None):
     91         "Apply `processor` or `self.processor` to `item`."
     92         if processor is not None: self.processor = processor

f:\workspace\python\fastai\fastai\vision\data.py in __init__(self, convert_mode, *args, **kwargs)
    253 
    254         img = PIL.Image.open(file)
--> 255         if max_size is not None and (img.height > max_size or img.width > max_size):
    256             assert isinstance(dest, Path), "You should provide `dest` Path to save resized image"
    257             dest_fname = dest / file.name

f:\workspace\python\fastai\fastai\data_block.py in __init__(self, items, path, label_cls, xtra, processor, x, **kwargs)
     47     def process_one(self, item: Any):         return item
     48 
---> 49     def process(self, ds: Collection):        ds.items = array([self.process_one(item) for item in ds.items])
     50 
     51 

f:\workspace\python\fastai\fastai\core.py in array(a, dtype, **kwargs)
    244 
    245 def save_texts(fname: PathOrStr, texts: Collection[str]):
--> 246     "Save in `fname` the content of `texts`."
    247     with open(fname, 'w') as f:
    248         for t in texts: f.write(f'{t}\n')

TypeError: 'WindowsPath' object is not iterable

**Comment by sgugger** [comment]
There was a bug with this function due to some changes in the library, but it has been fixed in 1.0.37.
