### ISSUE TITLE
Split by list is not working

### ISSUE THREAD

**Issue by jaideep11061982** [fastai/fastai#1328]
**Describe the bug**

https://forums.fast.ai/t/error-in-split-by-list/32349/5
when i use split by list i get error  list object has no attribute label from df
**To Reproduce**

Try running this code below it will throw the error
(ImageItemList.from_csv(path, 'train.csv', folder='train', suffix='.png')
       .split_by_list( list(trn),list(val))
       .label_from_df(sep=' ',  classes=[str(i) for i in range(28)]))

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
I'm suspecting you're passing lists for `trn` and `val`, when it should be `ItemList` object. This is more of an internal method, you should be using `split_by_files` if you want to pass a list of filenames for the validation set.
