### ISSUE TITLE
ImageMultiDataset has no attribute 'from_folder_validx'

### ISSUE THREAD

**Issue by Bonsen** [fastai/fastai#1329]
**Additional context**

1、ImageMultiDataset has no attribute 'from_folder_validx' (version 1.0.6)
2、
from fastai.vision import ImageMultiDataset 
ImportError: cannot import name 'ImageMultiDataset'(version 1.0.38)

**Comment by sgugger** [comment]
Datasets have all been removed from the library, yes. Use the docs on the [data block API](https://docs.fast.ai/data_block.html) to see how to get your data in the more recent versions.

**Comment by Iron4dam** [comment]
Hi, have you fixed this? Should we use ImageList in the latest version instead?
