### ISSUE TITLE
Resolve package not found

### ISSUE THREAD

**Issue by sl2902** [fastai/fastai#133]
I was running the conda env update command and I received the following error on a Windows 10 machine

```
Solving environment: failed

ResolvePackageNotFound:
  - pytorch[version='>=0.2.0']
  - ptyprocess
  - libgcc
  - glib
  - fontconfig
  - readline
  - libgfortran
  - jbig
  - libffi
  - torchvision[version='>=0.1.9']
```

**Comment by nsantini** [comment]
Similar issues for me on MacOS

ResolvePackageNotFound: 
  - cuda90

**Comment by vnessified** [comment]
Same for me on MacOS...

ResolvePackageNotFound: 
  - cuda90

**Comment by navneetkrc** [comment]
https://github.com/fastai/fastai/issues/88
This issue is similar to this one.

**Comment by jph00** [comment]
I can't help with MacOS sorry. If anyone knows how to get it working on MacOS, a PR would be welcomed.

**Comment by danielrvoigt** [comment]
Ran into a similar issue for MacOS. Looks like cuda90 is not supported on Mac, only on Windows and Linux. You can verify package compatibility by searching [https://anaconda.org/](url)

**Comment by stas00** [comment]
This is a year old thread, and this information is no longer correct. 

MacOS is partially supported, i.e. not 100% mainly due to issues in pytorch for which fastai has no control over. e.g, this one: https://github.com/pytorch/pytorch/issues/14359

**Comment by danielrvoigt** [comment]
@stas00 Good to hear. Any idea how to get around cuda90 not being available on MacOS?

**Comment by stas00** [comment]
Here https://pytorch.org/get-started/locally/ it says:
```
conda install pytorch torchvision -c pytorch
# MacOS Binaries dont support CUDA, install from source if CUDA is needed
```
Looking at https://www.google.com/search?q=pytorch+macos+cuda the install from source works. and that pytorch has [no intention currently to support binaries](https://github.com/pytorch/pytorch/issues/7960).

But what I meant in my original reply is that fastai-v1 has no direct dependency on cuda.

fastai-v1 supports whatever pytorch supports (with windows support catching up that is). FWIW, we run a 100% success build on CI for MacOS/conda for cpu. MacOS/pip has incompatibility issues between pytorch and numpy. https://github.com/pytorch/pytorch/issues/14359. We have no CI w/ GPU capacity to test with.

If, however, you're referring to fastai-0.7x, then I don't know.
