### ISSUE TITLE
TabularDataBunch for regression

### ISSUE THREAD

**Issue by franperezlopez** [fastai/fastai#1334]
**Describe the bug**
1) When using TabularDataBunch.from_df , the input parameter cat_names is modified by the function, so becomes an "output" parameter without the user noticing. IMO, output parameters should be explicitly supported in the return of the function, not as "collide" behavior
2) when using a continuous variable, and not using any normalization process, the target variable is still transformed (normalized? floating point conversion issues?)

**To Reproduce**
```python
df_bug = pd.DataFrame({'A': ['a','a','b','b','c','c','a','b','c','a'],
                       'B': np.random.normal(size=10).round(2),
                       'C': [0.0, np.nan, 2.0, np.nan, 4.0, 5.0,4.0,np.nan,3.0,2.0], 
                       'Y': np.random.normal(0,0.1,10).round(2)}).reset_index()

df_bug

columns_categorical = ['A']
tfms = [FillMissing, Categorify]
tabular_data = TabularDataBunch.from_df('output', 
                                        df_bug, 
                                        dep_var='Y', 
                                        valid_idx=[7,8], 
                                        procs=tfms, 
                                        cat_names=columns_categorical, 
                                        bs=4)

columns_categorical

tabular_data.show_batch(rows=4)
``` 
**Expected behavior**
variable `columns_categorical` should be the same before / after execution of the method
target databunch column should not be transformed (otherwise, I missed some info in the docs)

**Screenshots**
execution in google colab:
![image](https://user-images.githubusercontent.com/1222398/49951467-4b18dd80-fefa-11e8-9f06-199b2813e65c.png)

**Additional context**
![image](https://user-images.githubusercontent.com/1222398/49951928-633d2c80-fefb-11e8-9e49-8151c2f95182.png)

**Comment by sgugger** [comment]
The target being modified is just a floating conversion, I believe. Will fix the list of cat_names being modified.
