### ISSUE TITLE
TabularDataBunch with multivariate output automatically assumes classification

### ISSUE THREAD

**Issue by FedericoV** [fastai/fastai#1338]
**Describe the bug**

When initializing a TabularDataBunch with a multivariate output (for example, in the case of multivariate regression) the constructor will assume you are dealing with a multi-target classification problem.

**To Reproduce**

Passing dep_var as a list to TabularDataBunch constructor (even when the columns in dep_var are floating points).

This is because the logic in get_label_cls (from data_block.py) currently does the wrong thing and assigns MultiCategoryList to the datablock type.

**Expected behavior**

get_label_cls should correctly identify the input type as a multidimensional FloatList

**Screenshots**

**Additional context**

I did a very hacky work around as such: 

I changed the label_from_list function like so:
```
    def label_from_list(self, labels:Iterator, **kwargs)->'LabelList':
        "Label `self.items` with `labels`."
        #labels = array(labels, dtype=object)
        labels = array(labels)
        label_cls = self.get_label_cls(labels, **kwargs)
        y = label_cls(labels, path=self.path, **kwargs)
        res = self._label_list(x=self, y=y)
        return res
```

and the get_label_cls function like so:
```
    def get_label_cls(self, labels, label_cls:Callable=None, sep:str=None, **kwargs):
        "Return `label_cls` or guess one from the first element of `labels`."
        if label_cls is not None:               return label_cls
        if self.label_cls is not None:          return self.label_cls
        it = index_row(labels,0)
        if sep is not None:                     return MultiCategoryList
        try:
            if it.dtype == np.float32:
                return FloatList
        except AttributeError:
            pass
        if isinstance(it, (float, np.float32)): return FloatList
        if isinstance(try_int(it), (str,int)):  return CategoryList
        if isinstance(it, Collection):          return MultiCategoryList
        return self.__class__
```

Those are not optimal fixes.  It's my first time using the fastai library so I'm not familiar with the code base so I don't know the correct way to fix it yet.

**Comment by sgugger** [comment]
That isn't a bug, and this is the intended behavior as labels in a multiclassification problem may be one-hot encoded as floats.
Factory methods are for beginners and can only deal with simple data, you should use the [data block API](https://docs.fast.ai/data_block.html) for such a problem, where you can pass the `label_cls` of your choice.
