### ISSUE TITLE
what is the meaning of fix_dl in databunch?

### ISSUE THREAD

**Issue by mengjiexu** [fastai/fastai#1339]
just update the fastai and the old code can‘t run. Can someone tell me the meaning of fix_dl?

**Comment by mengjiexu** [comment]
@sgugger Could you please tell us the meaning of fix_dl. We are very confunsed for that is not used but is required param. Thank you very much.

**Comment by phillynch7** [comment]
The changes says "DataBunch now has fix_dl attr, which is same data as train_dl but without shuffle or train tfms", but this doesn't seem to match with the implementation.

**Comment by mengjiexu** [comment]
ok，Thank you very much.

**Comment by mengjiexu** [comment]
ok，Thank you very much.
