### ISSUE TITLE
DataSet requires an `items` attribute now?

### ISSUE THREAD

**Issue by phillynch7** [fastai/fastai#1341]
https://github.com/fastai/fastai/blob/53080d4b488b874da5d37cf0116e2d5e3ee40970/fastai/basic_data.py#L198

For creating a custom Pytorch DataSet, we are typically only required to override `__len__` and `__getitem__`. The new sanity check on DataBunch now throws an error if you use a DataSet without this.

Here is an example DataSet class that I was using that worked prior to this change:
```
class CustomDataset(Dataset):
    def __init__(self, data_list): self.data = copy(data_list)
    def __len__(self): return len(self.data)
    def __getitem__(self, idx):
        x1, x2, x3 = self.data[idx]
        return x1, np.array(x2), np.array(x3)
```

Throwing this into a DataLoader and DataBunch now gives an error:
```
AttributeError: 'CustomDataset' object has no attribute 'items'
```

**Comment by sgugger** [comment]
Just pushed a fix. Don't expect anything apart training to work though, if you don't use fastai datasets.

**Comment by phillynch7** [comment]
Is there a standard way used to implement the items? This seems like a new concept that doesn't show up anywhere else in the library (that I can find). Seems like `len(self.train_ds.items)` is trying to accomplish the same thing as what a `DataSet`'s `__len__` does? Is that wrong?
