### ISSUE TITLE
An better approach to documentation

### ISSUE THREAD

**Issue by odysseus0** [fastai/fastai#1348]
I am opening this issue only to bring the previously closed #596 issue back to our attention. What the issue creator proposed seems quite wonderful and constructive to me. What is its status right now? Is it being considered? Or maybe it is already forgotten?

@sgugger @jph00

**Comment by sgugger** [comment]
We have used a different approach to build the [docs](https://docs.fast.ai/).

**Comment by odysseus0** [comment]
Sorry I do not mean to confront your authority, but the approach recommended in #596 does seem to have many advantages. The reasons What is the reason why we are taking the current approach?

I did find your [post](https://forums.fast.ai/t/documentation-for-fastai-v1/20735).

You mentioned that no documentation generator library incorporates Jupyter notebook directly, but [nbsphinx](https://nbsphinx.readthedocs.io/en/0.3.4/installation.html) does exactly that.

**Comment by KaiLicht** [comment]
I started the documentation for the old version and wanted to propose it again when the new one is ready for documentation which I did in the forums. Since there was no comment I never looked into it again, just forgot to delete it.

**Comment by odysseus0** [comment]
@KaiLicht I am looking into it! There have been several vocal proposals on the forum, but the proposers somehow all missed each other. If you are still interested, we can start building one for fast.ai v1.
