### ISSUE TITLE
Update README.md to indicate to only use `activate fastai` for Windows

### ISSUE THREAD

**Issue by theangellmethod** [fastai/fastai#136]
`source activate fastai`

For Windows, it is only `activate fastai`.  

To be clear for Windows users, it would be good to indicate this so they can install without needing to search for why `source activate` isn't working.

**Comment by jph00** [comment]
I believe we are all now meant to use 'conda activate fastai'. Do you want to make that change?

**Comment by theangellmethod** [comment]
I checked the documentation [https://conda.io/docs/user-guide/getting-started.html#managing-environments](url) and it looks like it is split with `activate fastai` (Windows) and `source activate fastai` (Linux and macOS).  I will do a PR based on this for practice.
