### ISSUE TITLE
data.(tab) list doesn't include `.label_from_df`

### ISSUE THREAD

**Issue by Deena-B** [fastai/fastai#1362]
**Describe the bug**
Normally, pressing tab brings up a list of all the arguments that can be used, but sometimes not all the arguments are listed. This is one case that I noticed.

**To Reproduce**
```
iil = ImageItemList.from_df(path=path, df=df, cols='cols')
data = iil.random_split_by_pct(valid_pct=0.2, seed=10)
data.(tab)
```

The following are listed: 

data.label_from_lists
data.lists              
data.path             
data.test
data.train             
data.transform          
data.transform_y       
data.valid             

**Expected behavior**
I expected `data.label_from_df` to also be listed

**Screenshots**
<img width="280" alt="screen shot 2018-12-18 at 19 21 04" src="https://user-images.githubusercontent.com/17785851/50196962-1e016c00-02fa-11e9-978b-2237cec78eb1.png">

**Additional context**
 Other fastai users have confirmed they've noticed this sometimes too.

**Comment by sgugger** [comment]
Should be fixed by [this commit](https://github.com/fastai/fastai/commit/cc959272920391f16881498004cec0fb2742b639).
