### ISSUE TITLE
lesson1 learn.fit(0.01, 2) error!

### ISSUE THREAD

**Issue by jsupeng** [fastai/fastai#137]
learn.fit(0.01, 2)
learn.fit(0.01, 2)
Epoch
0% 0/2 [00:00<?, ?it/s]
  0%|                                                                                          | 0/360 [00:00<?, ?it/s]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-18-ae8b5bdd6b82> in <module>()
----> 1 learn.fit(0.01, 2)

d:\Anaconda3\envs\fastai\lib\site-packages\fastai\learner.py in fit(self, lrs, n_cycle, wds, **kwargs)
     97         self.sched = None
     98         layer_opt = self.get_layer_opt(lrs, wds)
---> 99         self.fit_gen(self.model, self.data, layer_opt, n_cycle, **kwargs)
    100 
    101     def lr_find(self, start_lr=1e-5, end_lr=10, wds=None):

d:\Anaconda3\envs\fastai\lib\site-packages\fastai\learner.py in fit_gen(self, model, data, layer_opt, n_cycle, cycle_len, cycle_mult, cycle_save_name, metrics, callbacks, **kwargs)
     87         n_epoch = sum_geom(cycle_len if cycle_len else 1, cycle_mult, n_cycle)
     88         fit(model, data, n_epoch, layer_opt.opt, self.crit,
---> 89             metrics=metrics, callbacks=callbacks, reg_fn=self.reg_fn, clip=self.clip, **kwargs)
     90 
     91     def get_layer_groups(self): return self.models.get_layer_groups()

d:\Anaconda3\envs\fastai\lib\site-packages\fastai\model.py in fit(model, data, epochs, opt, crit, metrics, callbacks, **kwargs)
     82         for (*x,y) in t:
     83             batch_num += 1
---> 84             loss = stepper.step(V(x),V(y))
     85             avg_loss = avg_loss * avg_mom + loss * (1-avg_mom)
     86             debias_loss = avg_loss / (1 - avg_mom**batch_num)

d:\Anaconda3\envs\fastai\lib\site-packages\fastai\model.py in step(self, xs, y)
     41         if isinstance(output,(tuple,list)): output,*xtra = output
     42         self.opt.zero_grad()
---> 43         loss = raw_loss = self.crit(output, y)
     44         if self.reg_fn: loss = self.reg_fn(output, xtra, raw_loss)
     45         loss.backward()

d:\Anaconda3\envs\fastai\lib\site-packages\torch\nn\functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce)
   1047         weight = Variable(weight)
   1048     if dim == 2:
-> 1049         return torch._C._nn.nll_loss(input, target, weight, size_average, ignore_index, reduce)
   1050     elif dim == 4:
   1051         return torch._C._nn.nll_loss2d(input, target, weight, size_average, ignore_index, reduce)

RuntimeError: Expected object of type Variable[torch.cuda.LongTensor] but found type Variable[torch.cuda.IntTensor] for argument #1 'target'

**Comment by iskode** [comment]
Have you update your local fastai with: `git pull`.
Because I ran the same command and it works perfectly.
BTW don't forget to close the issue and it's better to discuss issues in the forum than here.
