### ISSUE TITLE
error in language_model_learner ?

### ISSUE THREAD

**Issue by kuilef** [fastai/fastai#1370]
**Describe the bug**

Trying to use pretrained_fnames get the error:
```
    131     dps = default_dropout['language'] * drop_mult
--> 132     vocab_size = len(data.vocab.itos)
    133     model = get_language_model(vocab_size, emb_sz, nh, nl, pad_token, input_p=dps[0], output_p=dps[1],
    134                 weight_p=dps[2], embed_p=dps[3], hidden_p=dps[4], tie_weights=tie_weights, bias=bias, qrnn=qrnn)

AttributeError: module 'torch.utils.data' has no attribute 'vocab'
```

I think that correct 132 string should be
`vocab_size = len(data.train_ds.vocab.itos)`

**Comment by sgugger** [comment]
No, data forwad any unknown attriute to its train_ds. You get this bug because your data isn't properly defined (it's looking for the module data of torch.utils instead of an actual DataBunch here).
