### ISSUE TITLE
"fix_ds" in basic_data.py => def _init_ds - why do we need it

### ISSUE THREAD

**Issue by kasparlund** [fastai/fastai#1379]
"fix_ds" in basic_data.py => def _init_ds creates an extra dataset that will lead to an extra instance of LanguageModelLoader. This requires more memory which is bad.

I not understand "fix_ds". It looks like a hack to compensate for a design choice concerning dataset/transform. I think the root cause should be fixed and fix_ds removed

**Comment by jph00** [comment]
You admit yourself that you don't know what you're talking about, and then you go on to make a totally inappropriate recommendation and an offensive and wrong assertion. How can you possibly think that is in any way helpful? I honestly can't begin to imagine what you were thinking when you decided to post this here.
