### ISSUE TITLE
Issue with show_batch() when using CollabDataBunch

### ISSUE THREAD

**Issue by danieldiamond** [fastai/fastai#1381]
show_batch() fails when using CollabDataBunch. This issue appears to result from `x.cats` having no property `size()` in the show_xys and show_xysz functions. 

Replicating the issue:
```
data = CollabDataBunch.from_df(pd.read_csv(untar_data(URLs.ML_SAMPLE)/'ratings.csv'))
data.show_batch()
```

x.cats appears in the TabularLine and CollabLine classes. However, 
TabularLine returns tensors `self.data = [tensor(cats), tensor(conts)]` 
whereas CollabLine returns the data (in the form of a list) `self.data = [self.data[0][0],self.data[0][1]]`.

I would recommend either amending CollabLine to return tensor objects (similar to TabularLine) otherwise amending the if statements within show_xys and show_xysz functions to `len(x.cats)` instead of `len(x.cats.size())`

References:
show_xys function:
`https://github.com/fastai/fastai/blob/master/fastai/tabular/data.py#L137`

TabularLine returning tensors:
`https://github.com/fastai/fastai/blob/master/fastai/tabular/data.py#L28`

CollabLine returning data (in the form of a list):
`https://github.com/fastai/fastai/blob/master/fastai/collab.py#L12`

**Comment by sgugger** [comment]
Good catch! There is something else to make it work right though: the reconstruct method (which transforms a tensor to the initial object) needs to be different for Collab (which it was, but there was a bug there). Will commit the fix in a few secs.
