### ISSUE TITLE
requires_grad errors in language_model_learner.fit_one_cycle

### ISSUE THREAD

**Issue by mnye** [fastai/fastai#1383]
Hi there.  I'm trying to run some of the code from the fastai ML course, converting it to V1, and have come across this error which has stumped me:

> (full stack trace at bottom)
> RuntimeError: you can only change requires_grad flags of leaf variables. If you want to use a computed variable in a subgraph that doesn't require differentiation use var_no_grad = var.detach().

I have normally been able to work out most the issues with moving to V1, but this one looks a bit more tricky and maybe an actual bug.

I put the notebook in a gist, which hopefully will reproduce the issue for you: https://gist.github.com/mnye/b72811a191ada312654d1464ab21fcfb

Thanks in advance for looking at this.

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-15-812bca348026> in <module>
> ----> 1 learn = language_model_learner(data_lm, pretrained_model=URLs.WT103_1, drop_mult=0.5)
>       2 learn.fit_one_cycle(1, 1e-2)
> 
> ~/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/text/learner.py in language_model_learner(data, bptt, emb_sz, nh, nl, pad_token, drop_mult, tie_weights, bias, qrnn, pretrained_model, pretrained_fnames, **kwargs)
>     138         fnames = [list(model_path.glob(f'*.{ext}'))[0] for ext in ['pth', 'pkl']]
>     139         learn.load_pretrained(*fnames)
> --> 140         learn.freeze()
>     141     if pretrained_fnames is not None:
>     142         fnames = [learn.path/learn.model_dir/f'{fn}.{ext}' for fn,ext in zip(pretrained_fnames, ['pth', 'pkl'])]
> 
> ~/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/basic_train.py in freeze(self)
>     186         "Freeze up to last layer."
>     187         assert(len(self.layer_groups)>1)
> --> 188         self.freeze_to(-1)
>     189         self.create_opt(defaults.lr)
>     190 
> 
> ~/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/basic_train.py in freeze_to(self, n)
>     179         for g in self.layer_groups[:n]:
>     180             for l in g:
> --> 181                 if not self.train_bn or not isinstance(l, bn_types): requires_grad(l, False)
>     182         for g in self.layer_groups[n:]: requires_grad(g, True)
>     183         self.create_opt(defaults.lr)
> 
> ~/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/torch_core.py in requires_grad(m, b)
>     104     if not ps: return None
>     105     if b is None: return ps[0].requires_grad
> --> 106     for p in ps: p.requires_grad=b
>     107 
>     108 def trainable_params(m:nn.Module)->ParamList:
> 
> RuntimeError: you can only change requires_grad flags of leaf variables. If you want to use a computed variable in a subgraph that doesn't require differentiation use var_no_grad = var.detach().
>

**Comment by sgugger** [comment]
I can't reproduce your bug on master. Can you check your installation with:
```
from fastai.utils.show_install import show_install
show_install(1)
```
in a jupyter cell?

**Comment by mnye** [comment]
Sorry for the slow reply.  This is the output:

````text
=== Software === 
python version : 3.6.7
fastai version : 1.0.36.post1
torch version  : 0.4.1
torch cuda ver : 9.2.148
torch cuda is  : **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform       : Linux-4.4.0-17134-Microsoft-x86_64-with-debian-buster-sid
distro         : #471-Microsoft Fri Dec 07 20:04:00 PST 2018
conda env      : fastai
python         : /home/michael/anaconda3/envs/fastai/bin/python
sys.path       : 
/home/michael/anaconda3/envs/fastai/lib/python36.zip
/home/michael/anaconda3/envs/fastai/lib/python3.6
/home/michael/anaconda3/envs/fastai/lib/python3.6/lib-dynload
/home/michael/anaconda3/envs/fastai/lib/python3.6/site-packages
/home/michael/anaconda3/envs/fastai/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg
/home/michael/anaconda3/envs/fastai/lib/python3.6/site-packages/IPython/extensions
/home/michael/.ipython
no supported gpus found on this system
```

Please make sure to include opening/closing ``` when you paste into forums/github to make the reports appear formatted as code sections.

Optional package(s) to enhance the diagnostics can be installed with:
pip install distro
Once installed, re-run this utility to get the additional information`

**Comment by sgugger** [comment]
Your pytorch version isn't 1.0, that's why it's not working. See the installation instructions and the [installation thread](https://forums.fast.ai/t/fastai-v1-install-issues-thread/24111) on the forum.

**Comment by K0T3R** [comment]
I got a similar error when running lesson3.

```
learn.load('fit_head');

learn.unfreeze()
```

https://nbviewer.jupyter.org/github/fastai/course-v3/blob/master/nbs/dl1/lesson3-imdb.ipynb

In this notebook results in a runtime error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-36-e9ed8beef70a> in <module>
----> 1 learn.unfreeze()

~/SageMaker/envs/fastai/lib/python3.7/site-packages/fastai/basic_train.py in unfreeze(self)
    203     def unfreeze(self):
    204         "Unfreeze entire model."
--> 205         self.freeze_to(0)
    206         self.create_opt(defaults.lr)
    207 

~/SageMaker/envs/fastai/lib/python3.7/site-packages/fastai/basic_train.py in freeze_to(self, n)
    192             for l in g:
    193                 if not self.train_bn or not isinstance(l, bn_types): requires_grad(l, False)
--> 194         for g in self.layer_groups[n:]: requires_grad(g, True)
    195         self.create_opt(defaults.lr)
    196 

~/SageMaker/envs/fastai/lib/python3.7/site-packages/fastai/torch_core.py in requires_grad(m, b)
    115     if not ps: return None
    116     if b is None: return ps[0].requires_grad
--> 117     for p in ps: p.requires_grad=b
    118 
    119 def trainable_params(m:nn.Module)->ParamList:

RuntimeError: you can only change requires_grad flags of leaf variables.

```

My installation details are as follows:
```text
=== Software === 
python        : 3.7.2
fastai        : 1.0.42
fastprogress  : 0.1.18
torch         : 1.0.0
nvidia driver : 396.44
torch cuda    : 9.0.176 / is available
torch cudnn   : 7401 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11441MB | Tesla K80

=== Environment === 
platform      : Linux-4.14.77-70.82.amzn1.x86_64-x86_64-with-glibc2.10
distro        : #1 SMP Mon Dec 3 20:01:27 UTC 2018
conda env     : fastai
python        : /home/ec2-user/SageMaker/envs/fastai/bin/python
sys.path      : /home/ec2-user/SageMaker/course-v3/nbs/dl1
/home/ec2-user/src/cntk/bindings/python
/home/ec2-user/SageMaker/envs/fastai/lib/python37.zip
/home/ec2-user/SageMaker/envs/fastai/lib/python3.7
/home/ec2-user/SageMaker/envs/fastai/lib/python3.7/lib-dynload

/home/ec2-user/SageMaker/envs/fastai/lib/python3.7/site-packages
/home/ec2-user/SageMaker/envs/fastai/lib/python3.7/site-packages/IPython/extensions
/home/ec2-user/.ipython

Thu Jan 31 01:39:31 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:1E.0 Off |                    0 |
| N/A   80C    P0   139W / 149W |   6942MiB / 11441MiB |     98%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      8721      C   ...2-user/SageMaker/envs/fastai/bin/python   317MiB |
|    0      9011      C   ...2-user/SageMaker/envs/fastai/bin/python  6295MiB |
|    0     14514      C   ...2-user/SageMaker/envs/fastai/bin/python   317MiB |
+-----------------------------------------------------------------------------+

```

**Comment by 13204942** [comment]
Any ideas about @K0T3R  error? I got the same error when running learn.unfreeze()
