### ISSUE TITLE
Comparing a list with a torch.Size object is always False

### ISSUE THREAD

**Issue by CaveSven** [fastai/fastai#1389]
https://github.com/fastai/fastai/blob/f7d97d19487119c18f4ec788883890a8ca321602/fastai/vision/transform.py#L148

This line compares a List object (the result of listify) with torch.Size (a subclass of Tuple according to https://pytorch.org/docs/stable/tensors.html#torch.Tensor.size) which is always False.

**Comment by sgugger** [comment]
Good catch!
