### ISSUE TITLE
Error in the TextClasDataBunch.load_empty()

### ISSUE THREAD

**Issue by RupeshGoud** [fastai/fastai#1397]
**Describe the bug**
As mentioned in the tutorial, for inference when we do 
```python 
empty_data = TextClasDataBunch.load_empty(datadump)
learn = text_classifier_learner(empty_data)
learn.load('classifier_learn_cl', with_opt=False);
```
getting an error, **TypeError: object of type ‘NoneType’ has no len()** when calling text_classifier_learner

This is because attribute **c** is not getting assigned inside load_empty() method and text_classifier_learner is trying to access **c** attribute(For num of classes)

**To Reproduce**

Create a **TextClasDataBunch** like following,
```python
data_clas = TextClasDataBunch.from_df(datadump, df_train, df_val,label_cols = all_classes ,text_cols = 'snippet_text',vocab=data_lm.train_ds.vocab)
```
`df_train` and `df_val` and dataframes with multiple categories are one hot encoded and ontains one text column `snippet_text` and `all_classes` is a list of category column names 
```python
['competitive-challenge','customer-dissatisfaction', 'executive-publication','headcount-growth']
```
**Expected behavior**
`TextClasDataBunch.load_empty(datadump)` should return `empty_data` with `c` attribute which resembels number of classes. So, that  `text_classifier_learner` can be called safely as mentioned in the [tutorial](https://docs.fast.ai/tutorial.inference.html#Classification)

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
Should be fixed now, thanks for flagging!

**Comment by stas00** [comment]
Not until a new release is made. Until then follow [this](https://github.com/fastai/fastai/blob/master/README.md#developer-install). Or you can install directly from github i.e. 
```
pip install git+https://github.com/fastai/fastai.git
```
