### ISSUE TITLE
sanity_check improvements

### ISSUE THREAD

**Issue by stas00** [fastai/fastai#1399]
In basic_data.py, sanity_check.

```
        try: samples = [self.train_ds[i] for i in idx]
        except:
            warn(f"There seems to be something wrong with your dataset, 
                     can't access self.train_ds[i] for all i in {idx}")
```

First, why does it say **all i** if the exception will happen only on one of them, i.e. we don't really know whether there is a problem with all of them, or just that i it failed on? Probably need to try/except each one separately, and then report the failing ones? Unless, this usually happens when something is wrong with the whole dataset and not just individual entries, in which case still, there is no point indicating entry ids, if you know that it's all wrong. Giving unique entry ids makes the user think that something is wrong with some data entries, which is misleading and time-wasteful.

Second, any chance to help the user with the "something wrong"? For example, I encountered this problem when using transforms, but no problem with `tfms=[]`. So, really, something went wrong with the transforms, fastai didn't indicate that, but instead fails much later in `normalize()`. If I do print the exception I get:

```
TypeError: unsupported operand type(s) for /: 'str' and 'int' # from image.py: return (int(x/mult+0.5)*mult)
```

so clearly, something isn't setup properly in the earlier stages of the data block.

**Comment by sgugger** [comment]
Changed for the first point. For the second, I'd need more details and a reproducible bug, thanks!

**Comment by stas00** [comment]
See my follow up in your commit: https://github.com/fastai/fastai/commit/c2f3b410dac22c41493357c0b0cf11557e8c7b8a

**Comment by stas00** [comment]
I will try to come up with a reproducible example to help debug the actual problem.

**Comment by SalChem** [comment]
Hi Guys,
what if I simply want to remove the idx elements, produced by the warning, from training dataset. Would you happen to know the command?

**Comment by stas00** [comment]
That won't work, since you're getting a warning only for one batch. Chances are that you have this problem all over the dataset. 

The only reason specific indices are returned is so that you could check what the problem is.

If you want to extract all the indices you can modify sanity_check to loop through all of the data and record bad ones.

But you really should pre-process your input data and throw out anything that's not right before you feed it to the dataloader.

**Comment by SalChem** [comment]
Thanks for prompt response. You are def on point, thanks for the clarification. Forgot that the warning is only for one batch, and there are elements on other batches that are also corrupted.

Instead of manually removing the images, there must be a command in Python that can scan the folders prior to feeding them to ImageDataBunch, removing all corrupt images by idx. Is it sanity_check? or you have other suggestions?

**Comment by stas00** [comment]
Perhaps you're after: https://docs.fast.ai/vision.data.html#verify_images

**Comment by stas00** [comment]
and the error msg has now been changed to indicate that it's just in the first batch to avoid confusion.

**Comment by SalChem** [comment]
You are the man. Yes, it worked. Thanks.

One last question, a bit off from this discussion but would like to hear your insight please:

Why is it that running 'ImageDataBunch.from_folder' without valid_pct throws an error. I thought valid_pct is set by default to 0.2? I have to run ImageDataBunch.from_folder(PATH, valid_pct=0.2) instead of ImageDataBunch.from_folder(PATH). Just curious why? on the other hand 'ImageDataBunch.from_name_re' works without it.

**Comment by stas00** [comment]
It's because it's expecting an imagenet type of dataset by default which already has a valid folder, see:
https://docs.fast.ai/vision.data.html#ImageDataBunch.from_folder
please continue asking questions at forums.fast.ai where others can benefit from the answers and also provide answers.
Thanks.

**Comment by SalChem** [comment]
Okay. Got it. Yes, and I will post future questions to the forum. 

One last thing if you don't mind,

Both 'ImageItemList.from_folder(path)' and 'ImageDataBunch.from_folder(PATH)' work well for creating data objects, train_ds, etc... How do you go between picking which one is more appropriate for the task? I checked their source code and even their options are about the same. 

I am new to this, your insights have been valuable. Thanks again.
