### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by swiss-knight** [fastai/fastai#1401]
Hello,

I cloned the github repository in order to try to follow some courses but many Python libraries seem missing. 
Messages like: 
`ModuleNotFoundError: No module named <package_name> `
are displayed while running the first ml "lesson1-rf.ipynb" notebook.

Here are some libs which could be integrated (I actually wonder why it is not the case) to the **requirements.txt** or **setup.py** file:

- bcolz
- seaborn
- graphviz
- isoweek
- sklearn_pandas
- pdpbox
- pandas_summary (this one is not recognized even after having installed it (fig.1)).
- torchtext
- plotnine 
- feather-format 
- jupyter_contrib_nbextensions
- docrepr
- awscli
- kaggle-cli
- (... and probably others)

I'm on Ubuntu 18.04 (4.15.0-43-generic x86_64 GNU/Linux) using Python 3.6.7, pip 18.1 and virtualenv 16.1.0.
Thanks.

![untitled](https://user-images.githubusercontent.com/19967599/50507246-fa1df300-0a7c-11e9-8807-efc79c14eae9.png)
_**Fig.1**. "pandas_summary" is still missing even after having explicitly installed it._

**Comment by sgugger** [comment]
They are all in the requirements.txt file of old fastai, so I'm not sure what is the issue here. Are you sure you followed the steps [here](https://forums.fast.ai/t/fastai-v0-7-install-issues-thread/24652)?

**Comment by swiss-knight** [comment]
I actually cloned the master git repo as I didn't find any "courses" branch or "0.7".

That's probably why.

But now I wonder; why do the dev team rely on "old packages" for courses, ( e.g. torch 0.3.1 instead of 1.0.0 ) and keep saying that the framework is based on the latest advances in ML or so?
I absolutely don't want to be offending, it's a simple open question as on the link you shared it's written "outdated" on the pip installation section:

![untitled](https://user-images.githubusercontent.com/19967599/50508593-d362bb00-0a82-11e9-88e9-973e1185808d.png)
**Fig.2.** _Documentation from https://forums.fast.ai/t/fastai-v0-7-install-issues-thread/24652 for installing with pip._

Do you also know is they planned to open a dedicated git branch for courses?    
When I begin to read suffixes like "_old" or "v3" it's not a sign of a homogeneous development to me, branches should do the job instead (but I'm not a dev at all).

But still, installing ~fastai==0.7.0~ leads to:
`ModuleNotFoundError: No module named 'pandas_summary'`

**Comment by sgugger** [comment]
The current setup is temporary before the new MOOC is released in January. The new version of the library is using pytorch 1.0, but there are a lot of breaking changes with the old one, which is why you should use 0.7 for the current public version MOOC.
Once the new MOOC is released, this will all go in a separate repo, and since it's temporary we didn't bother making it super clean. `pandas_summary` is in the old requirements, you should use the conda from git source install. 
Optionally, just wait for two weeks to use fastai v1 with the new version of the MOOC.
