### ISSUE TITLE
Type len() 0 0-d tensor

### ISSUE THREAD

**Issue by jaideep11061982** [fastai/fastai#1404]
**Describe the bug**

preds,y,losses = learn1.get_preds(with_loss=True,n_batch=64)
interp = ClassificationInterpretation(data, preds, y, losses)
interep.top_losses(9)

I get the error in subject when i run the last statement. When i check losses length it is a single length. I dint pass reduction ,which i presume should be defaulted to None ?
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
We can't help you without more code or the data you're using, otherwise we can't reproduce the bug (and even less fix it).

**Comment by sgugger** [comment]
Closing this since it has been a while with no news. Feel free to reopen with a gist reproducing the bug!
