### ISSUE TITLE
Running torch.backends.cudnn.enabled on Intel CPU Getting True as OP. 

### ISSUE THREAD

**Issue by nullbyte91** [fastai/fastai#1405]
**Describe the bug**
Running `torch.backends.cudnn.enabled ` on Intel CPU and GPU showing True. 

**To Reproduce**
After fastai import 

Running below code on JN,
torch.cuda.is_available() - False
torch.backends.cudnn.enabled - True

**Expected behavior**
False should be an output

**Additional context**
Ubuntu 16.04 LTS
CPU Intel® Core™ i5-6300U CPU @ 2.40GHz × 4
GPU Intel® HD Graphics 520 (Skylake GT2) 
Conda installs - Fastai V0.7

I believe its not an issue with fastai setup neither Notebook. But, Trying to understand this?
![fast_torch_backend_issue](https://user-images.githubusercontent.com/24765915/50519977-98dd3a80-0ae3-11e9-80ca-ccacb1034b44.png)

**Comment by sgugger** [comment]
That's a question for the pytorch forum, no link to fastai (and no idea why it shows this).

**Comment by stas00** [comment]
See: https://docs.fast.ai/troubleshoot.html#correctly-configured-nvidia-drivers

**Comment by stas00** [comment]
And this is always true, no matter whether you're on CPU or GPU. It's not cuda, it's cudnn.
torch.backends.cudnn.enabled - True

**Comment by nullbyte91** [comment]
Yes. I have few more questions now. But, Let me read about this and the torch backend implementation and come back. Thank you.

**Comment by stas00** [comment]
But please let's continue at the forums, so that others can benefit from the answers. 
Perhaps [here](http://forums.fast.ai/t/fastai-v1-install-issues-thread/24111).

**Comment by nullbyte91** [comment]
Yes. Great. I do that.
