### ISSUE TITLE
Error with pretrained-models.pytorch

### ISSUE THREAD

**Issue by Bonsen** [fastai/fastai#1406]
Please see https://forums.fast.ai/t/error-with-pretrained-models-pytorch/33139. I have received many emails that they meet the same problem if using create_cnn.....

The resnet/senet is OK but inception network and pnas network and etc. give errors because of the forward().
But they are all right if I don't use fastai or I just use learner.

**Comment by sgugger** [comment]
This model isn't supported with `create_cnn`. Supported models are resnet only until someone else develops that feature. In the meantime, you can always pass your pytorch model to a `Learner` with your data.
