### ISSUE TITLE
Unresolved references in TabularList.get()

### ISSUE THREAD

**Issue by brennon** [fastai/fastai#1409]
**Describe the bug**
There are unresolved references in `TabularList.get()`.  As of cf45d5ea53f092f563e7229df629e7a248a823b1, this method refers to `self.codes` (I'm guessing this should be `self.cat_names`?), `self.conts` (I'm guessing this should be `self.cont_names`?), `self.classes`, and `self.col_names` (I'm not sure what these last two should be.) I don't see where these have ever been valid attributes either in `TabularList` or in `ItemList`. Any calls to `get` explode (including via `__repr__`).

**To Reproduce**
```
df = pd.DataFrame({'foo': [1.0, 1.5, 2.0], 'bar': ['positive', 'negative', 'negative']})
data = TabularList.from_df(df=train_df,
                           cat_names=['bar'], 
                           cont_names=['foo'])
print(data[0])
```

**Expected behavior**
I expect to get an item from the `TabularList`...

**Additional context**
I'd love to submit a PR to fix this, but this is where your philosophy of not-terribly-descriptive variable names coupled with little inline documentation/comments can bite you. If someone can tell me what these four things should be, I'd be happy to put together the PR. Are my first two assumptions about `self.codes` and `self.conts` correct? Is `self.classes` a list of all possible classes, the column name(s) holding the class(es), or something else altogether? Is `self.col_names` just a list of all available columns?

**Comment by brennon** [comment]
I see the stupidity of my previous questions...seems to me now that `self.codes` should actually be the values of the categorical columns for the given row, and similar for `self.conts` and `self.classes`(?). I'm still not sure what `self.col_names` should be, though.

**Comment by sgugger** [comment]
The problem is that currently, the get method assumes the data has already been preprocessed (which is when it gains all those attributes). I've added a test to return the line of the dataframe if it hasn't been preprocessed.
