### ISSUE TITLE
Default embedding sizes for ColumnarModelData

### ISSUE THREAD

**Issue by mcintyre94** [fastai/fastai#141]
In lesson 4 of dl1 we learned what embedding matrixes are about and a heuristic for generating them: cardinality/2, but not bigger than 50 - implemented in the notebook as:

```
cat_sz = [(c, len(joined_samp[c].cat.categories)+1) for c in cat_vars]
emb_szs = [(c, min(50, (c+1)//2)) for _,c in cat_sz]
```

We then pass that as the first parameter to the `fit` method:
`m = md.get_learner(emb_szs, ...)`

I'm wondering if it would make sense to make that parameter optional, and to use the heuristic discussed as the default value - we already passed in the data frame and the categorical fields:
`md = ColumnarModelData.from_data_frame(PATH, val_idx, df, yl.astype(np.float32), cat_flds=cat_vars, bs=128, test_df=df_test)`

Any thoughts? If this wouldn't be sensible and I've mis-understood the content I've asked a similar question in the fast.ai forums here: http://forums.fast.ai/t/lesson-4-is-there-a-non-teaching-reason-not-to-have-default-embedding-sizes/11391

**Comment by kevindewalt** [comment]
Sounds like a good idea. Keeps in general spirit of the fastai approach.

**Comment by jph00** [comment]
Seems reasonable to me. Would be happy with a PR :)
