### ISSUE TITLE
Unable to set TextLMDataBunch batch_size property

### ISSUE THREAD

**Issue by bfarzin** [fastai/fastai#1420]
**Describe the bug**

Unable to set batch_size after buliding Language Model Data Bunch

** why it matters **
Sometimes building a language model data bunch can take a long time (i.e. tokenize a large corpus)
I would like to try different batch sizes after the data is loaded.  It appears that functionality is intended to be there, but it does not seem to work right now.

**To Reproduce**
```
from fastai.text import *
path = untar_data(URLs.IMDB_SAMPLE)
data_lm = TextLMDataBunch.from_csv(path,'texts.csv') #I can set it here
data_lm.batch_size = 16
```

It appears the issue is with `intercept_args()` in `fastai/basic_data.py`  in that it is getting additional arguments that is cannot handle in the `**new_kwargs` (Line 42)

I tried to modify that code to accept `**kwargs` but that causes other issues down the road (trying to group un-equal sized tensors...)  

**Expected behavior**

I expect to be able to set the attribute after generating the data_lm

**Screenshots**
![image](https://user-images.githubusercontent.com/16351572/50564706-eb3d7780-0cec-11e9-843c-ec2c196e5462.png)

**Additional context**
This is  a dev install from the latest github pull.  I did not see this as a current outstanding issue.

**Comment by sgugger** [comment]
It was due to LMDataLoader being a bit different from a classic dataloader, thanks for spotting this!

**Comment by bfarzin** [comment]
Thanks for the quick response!  your change addressed it and all runs fine now.
