### ISSUE TITLE
TabularDataBunch.from_df is 1-indexed when dealing with pandas categoricals

### ISSUE THREAD

**Issue by andaag** [fastai/fastai#1423]
**Describe the bug**
Trying to do a collaborative filter in fastai 1.0 I got the very helpful error "RuntimeError: reduce failed to synchronize: device-side assert triggered".

Looking at all my data all the sizes of the tensors align up as I would expect. After debugging (by pulling all the relevant data out and running it on a cpu) I found that it was due to the embedding matrix.

In my dataset dataframe["one_categorical"].nunique() = 451.

When using TabularDataBunch.from_df to read these and calling the fit method, any batch containing the max value in the dataframe will try to lookup index 451 in the embedded matrix. But the embedded matrix is 0-indexed, and goes from 0-450. So that lookup will fail.

It looks like when TabularDataBunch reads the dataframe's categoricals it does so 1-indexed, or deals with NaN values in some way? (nb : There are no nan values in the dataset. )

**To Reproduce**
My dataset in this case is rather unhelpfully large.. If it doesn't make immediate sense let me know and I'll come up with some test data that reproduces this.

**Workaround**
Set embedded sizes to +1 more than the number of unique categoricals. 

---

It'd make a lot more sense to me if these tensors had the same size, and we could deal with categoricals in a 0-indexed way. If there are reasons not to, capturing the error and warning the user about it would be lovely too.

**Comment by andaag** [comment]
https://gist.github.com/andaag/ebb37e4fde782a07e8894311c417bf3a

Debug info

**Comment by sgugger** [comment]
In fastai, all categorical variables go from 0 (nan), 1 (first value) to n (last value), even if you don't have nans (because in most cases, users have nans). You need to set +1 in your embedding sizes in your model (this is automatically done in the fastai models) to account for that.
