### ISSUE TITLE
Issue with type of accuracy metric - classifcation with more than 2 classes

### ISSUE THREAD

**Issue by bjoernholzhauer** [fastai/fastai#1428]
**Describe the bug**

When doing classification of images into more than 2 categories (e.g. dogs, cats, snakes instead of just dogs/cats), the accuracy metric appears to cause an error at the end of epochs. This is [already described](https://forums.fast.ai/t/error-pytorch-expected-object-of-scalar-type-long-but-got-scalar-type-float-for-argument-2-other/33778) in the fastai forums with a potential solution given. I am not sure whether this is a very specific solution to this one setting and breaks something elsewhere (and some different more general solution is needed, or not), hence I post as an issue.

**To Reproduce**
```
from fastai.vision import *
tfms = get_transforms()

data = ImageDataBunch.from_csv(path='mypath',
                        folder='jpg_folder',
                        csv_labels='tagged_images.csv',
                        label_col=1,
                        sep=' ',
                        ds_tfms=tfms,
                        size=128,
                        valid_pct=0.2)

# Produces RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'other'
learn = create_cnn(data,
                   models.resnet34, 
                   metrics = accuracy)
learn.fit_one_cycle(1)

# works fine
def myaccuracy(input:Tensor, targs:Tensor)->Rank0Tensor:
    "Compute accuracy with `targs` when `input` is bs * n_classes."
    n = targs.shape[0]
    input = input.argmax(dim=-1).view(n,-1)
    targs = targs.view(n,-1).long()
    return (input==targs).float().mean()
learn = create_cnn(data,
                   models.resnet34, 
                   metrics = myaccuracy)
learn.fit_one_cycle(1)
```
**Expected behavior**
Should produce accuracy in the way that the user define myaccuracy metric does above.

**Additional context**
Versions used:
fastai                    1.0.39
pytorch                   1.0.0           py3.7_cuda10.0.130_cudnn7.4.1_1  [cuda100]

**Comment by sgugger** [comment]
Why are you using `sep=' '` if it's a single classification problem? `accuracy` won't work in this case since the library will return float targets one-hot encoded (which is what the loss function for multilabel problems expect). Just removing that `sep=' '` should fix your problem.

**Comment by RomRoc** [comment]
Hello, I get the same error even with a simple multilabel classification problem. 
Exactly the same problem described in the fast.ai forum [link ](https://forums.fast.ai/t/error-pytorch-expected-object-of-scalar-type-long-but-got-scalar-type-float-for-argument-2-other/33778) above.

`learn = create_cnn(data=data, arch=models.resnet34, metrics=error_rate)`

If I omit `, metrics=error_rate` I don't get the error, but this couldn't be the solution.

**Comment by sgugger** [comment]
`error_rate` can't work for multi-classification problems, that's the whole source of the error.
