### ISSUE TITLE
Calling `python` within fastai/fasti directory causes a core dump

### ISSUE THREAD

**Issue by prairie-guy** [fastai/fastai#143]
In exploring the `fastai` library, I tried calling `python` to test some code. While in the `fastai/fastai` directory, this caused a core dump:
```
(fastai) prairie@gold:~/fastai/fastai$ python
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/home/prairie/fastai/fastai/io.py", line 1, in <module>
ImportError: attempted relative import with no known parent package
Aborted (core dumped)
```
This doesn't happen with`python2.7`

This is a minor edge case which is easy to avoid, but I pass it on any way. (Not even sure if this is anaconda related.)

Thanks for a terrific `fastai` library and an equally impressive MOOC! Much appreciated.

**Comment by jph00** [comment]
Please use the forums for this one.
