### ISSUE TITLE
unet_learner fails when using nn.DataParallel (multi-GPU)

### ISSUE THREAD

**Issue by gsgbills** [fastai/fastai#1435]
**Describe the bug**

unet_learner fails if model is assigned DataParallel
```
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_batch_norm)
```
**To Reproduce**

```
from fastai import *
from fastai.vision import *
camvid = untar_data(URLs.CAMVID_TINY)
path_lbl = camvid/'labels'
path_img = camvid/'images'
codes = np.loadtxt(camvid/'codes.txt', dtype=str)
get_y_fn = lambda x: path_lbl/f'{x.stem}_P{x.suffix}'
data = (SegmentationItemList.from_folder(path_img)
        .random_split_by_pct()
        .label_from_func(get_y_fn, classes=codes)
        .transform(get_transforms(), tfm_y=True, size=128)
        .databunch(bs=16, path=camvid)
        .normalize(imagenet_stats))
learn = unet_learner(data, models.resnet18)
learn.model = torch.nn.DataParallel(learn.model, device_ids=[0,1])
learn.fit(1)
**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->
Same behavior of learn.fit with or without the learn.model DataParallel
**Screenshots**
<!-- If applicable, add screenshots to help explain your problem. -->

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by eugenegoncharov** [comment]
Got the same issue

**Comment by loveisp** [comment]
Got the same issue

**Comment by bauerm97** [comment]
Just wanted to confirm that this happens to me as well. If someone could help point me in the right direction to fix that, I'd be more than happy to take a stab at it

**Comment by sgugger** [comment]
We know this is an issue. The problem comes from the hooks that save the intermediate features in the pretrained body. They only remember the features on one GPU instead of aggregating.
I'd suggest using distributed training (there is a fastai function to help) which works.

**Comment by sgugger** [comment]
I asked on the PyTorch slack for any workaround and didn't get an answer, so I'm afraid this will stay like this. As I said before, using distributed training is a workaround that works (sadly not in a notebook but only in script).
Closing this issue, the known bug is documented in `unet_learner`.

**Comment by rwightman** [comment]
@sgugger I mentioned this to jeremy recently but probably best to leave a note here... I was working on some hooks for feature collection recently and ran into this problem, this was the first issue I came across on github. 

My usage is a bit different than the DynamicUnet, but I think the approach would work. If you stash the tensors in the hooks in a dict by tensor.device it prevents the mixup with DataParallel usage.

My WIP, messy example:
https://github.com/rwightman/pytorch-image-models/blob/condconvs_and_features/timm/models/gen_efficientnet.py#L1076

**Comment by LucaSoato** [comment]
That's cool @rwightman, do you think it's possible to apply your solution to simpler unets, for example the one in camvid segmentation? 
I'm trying to build a solution or a workaround for this.
Thanks for the help

**Comment by bosmart** [comment]
I realise the thread is quite old but was anyone able to find a workaround? @rwightman, your link doesn't work anymore...

**Comment by sktalha68** [comment]
@rwightman I am also facing the same issue (DataParallel not working and showing a GPU missmatch) and unfortunately the link you provided is not working. Can you please guide us?

**Comment by hectorferronato** [comment]
Any changes to this? facing same issue, unet_learner won't work in DataParallel. Doesnt work with DDP either.
