### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'label'

### ISSUE THREAD

**Issue by CaesarLuvAI** [fastai/fastai#1436]
I am following the "Quick Start: Training an IMDb sentiment model with ULMFiT"  .it report an error like 
lbls = df[self.label_cols].values.astype(lbl_type) if (len(self.label_cols) > 0) else []
ValueError: invalid literal for int() with base 10: 'label'
I read the source code and it seems the label column has not been encoded into numbers, and i don't know how to completely fix this problem.
my code is as follows
##
from fastai.text import *
from fastai import *
pd.set_option('display.width',None)
path=untar_data(URLs.IMDB)
print(path)
df=pd.read_csv(path/'texts.csv')
df.label=preprocessing.LabelEncoder().fit_transform(df.label)
data_lm=TextLMDataBunch.from_csv(path=path,train='texts')
data_clas=TextClasDataBunch.from_csv(path,train='texts',vocab=data_lm.train_ds.vocab,bs=32)

**Comment by sgugger** [comment]
What is this "Quick Start: Training an IMDb sentiment model with ULMFiT", could you link to the file?
The line you're quoting doesn't exist in the fastai library (v1), are you sure you aren't trying to use the old version of the library? Could you show us the result of
```
from fastai.utils.show_install import *
show_install()
```

**Comment by CaesarLuvAI** [comment]
> What is this "Quick Start: Training an IMDb sentiment model with ULMFiT", could you link to the file?
> The line you're quoting doesn't exist in the fastai library (v1), are you sure you aren't trying to use the old version of the library? Could you show us the result of
> 
> ```
> from fastai.utils.show_install import *
> show_install()
> ```

thank u sir for your reply, i tried your code 'from fastai.utils.show_install import *
show_install()', but sadly it reported no module named fastai.utils.show_ and its version is 1.0.6 . And here is the link where i follow the tutorial : https://docs.fast.ai/text.html, i am truly looking forward to your help

**Comment by stas00** [comment]
Your fastai version is several months old, @CaesarLuvAI 

Please follow the instructions at https://github.com/fastai/fastai#installation and make sure you're running the latest version: 1.0.39 as of this writing.

If after installing the latest version you have a problem still please refer to [this](http://forums.fast.ai/t/fastai-v1-install-issues-thread/24111)

**Comment by CaesarLuvAI** [comment]
> Your fastai version is several months old, @CaesarLuvAI
> 
> Please follow the instructions at https://github.com/fastai/fastai#installation and make sure you're running the latest version: 1.0.39 as of this writing.
> 
> If after installing the latest version you have a problem still please refer to [this](http://forums.fast.ai/t/fastai-v1-install-issues-thread/24111)

thank u for your attention  i tried but failed to update my fastai perhaps because i am on windows,it remains 1.0.6

**Comment by stas00** [comment]
Please see:
https://docs.fast.ai/troubleshoot.html#cant-install-the-latest-fastai-conda-package
