### ISSUE TITLE
Indexerror: list index out of range in language model learner

### ISSUE THREAD

**Issue by agarnitin86** [fastai/fastai#1439]
I am trying to run the code given here https://docs.fast.ai/text.html
But i am getting following error 

Traceback (most recent call last):
  File "code/ulmfit.py", line 56, in <module>
    learn = language_model_learner(data_lm, pretrained_model=URLs.WT103, drop_mult=0.7)
  File "/opt/anaconda/envs/fastaiv3/lib/python3.7/site-packages/fastai/text/learner.py", line 136, in language_model_learner
    fnames = [list(model_path.glob(f'*.{ext}'))[0] for ext in ['pth', 'pkl']]
  File "/opt/anaconda/envs/fastaiv3/lib/python3.7/site-packages/fastai/text/learner.py", line 136, in <listcomp>
    fnames = [list(model_path.glob(f'*.{ext}'))[0] for ext in ['pth', 'pkl']]
IndexError: list index out of range

I am using fastai version : 1.0.38

I can see that the folder named "models" is getting created in my directory but it is empty.
What exactly is the problem and how to resolve it?

**Installation details**

```
from fastai.utils.show_install import *
show_install()
```
```text
=== Software === 
python       : 3.7.0
fastai       : 1.0.38
fastprogress : 0.1.18
torch        : 1.0.0
torch cuda   : 9.0 / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Windows-7-6.1.7601-SP1
conda env    : Unknown
python       : C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\pythonw.exe
sys.path     : 
C:\Users\nitin.agarwal
C:\Users\nitin.agarwal\Documents\PythonWorkspace\ULMFIT_TextClassification
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\python37.zip
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\DLLs
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages\win32
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages\win32\lib
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages\Pythonwin
C:\Users\nitin.agarwal\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\extensions
C:\Users\nitin.agarwal\.ipython
no supported gpus found on this system
```

**Comment by sgugger** [comment]
It seems the model didn't download properly, it should be in your home directory/.fastai/models/wt103 (or something like that). Remove the files wt103.tgz and the wt103 directory to trigger a new download.
