### ISSUE TITLE
unable to pass remove_out

### ISSUE THREAD

**Issue by radekosmulski** [fastai/fastai#1443]
I tried passing remove out via trial and error to either of the methods below, but it either was not accepted or it didn't make a difference.

```
data = (PointsItemList.from_folder(path)
        .split_by_valid_func(lambda o: o.parent.name=='13')
        .label_from_func(lambda x: torch.tensor([10.,20.]))
        .transform(get_transforms(), tfm_y=True, size=(120,160))
        .databunch().normalize(imagenet_stats)
       )
```

Once I commented out some code in `vision/data.py` I was able to get the behavior.

**Comment by sgugger** [comment]
I just dug into the code, and it looks like my past self had already foreseen we'd need to pass this. There is no need to subclass `PointsItemList`, it's inside your transform call: normally
```
.transform(get_transforms(), tfm_y=True, size=(120,160), remove_out=False)
```
should work. Please let me know if it does!

**Comment by radekosmulski** [comment]
Thank you! :slightly_smiling_face:
