### ISSUE TITLE
BrokenProcessPool

### ISSUE THREAD

**Issue by tuhinjubcse** [fastai/fastai#1447]
![image](https://user-images.githubusercontent.com/3104771/50920597-caeb8680-146b-11e9-83fb-028fd9577b90.png)

def get_texts(df, n_lbls=1):
    labels = df.iloc[:,range(n_lbls)].values.astype(np.int64)
    texts = f'\n{BOS} {FLD} 1 ' + df[n_lbls].astype(str)
    for i in range(n_lbls+1, len(df.columns)): texts += f' {FLD} {i-n_lbls} ' + df[i].astype(str)
    texts = list(texts.apply(fixup).values)

    tok = Tokenizer().proc_all_mp(partition_by_cores(texts))
    return tok, list(labels)

**Comment by sgugger** [comment]
Please try to follow the guidelines to file an issue, there is nothing we can do without knowing which version of fastai you're using, or with a minimal reproducible example. This error is generic in multiprocessing, you should try without the multiprocessing to get an error message more understandable.
