### ISSUE TITLE
TabularDataBunch.from_df produces cryptic error when target is int64

### ISSUE THREAD

**Issue by andaag** [fastai/fastai#1451]
**Describe the bug**
Playing around with a dataset I get the following error when loading:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-9f3e9fdc7995> in <module>
      1 procs = [Normalize, Categorify]
----> 2 databunch = TabularDataBunch.from_df("tmp", joined[cat_vars + contin_vars + ["Sales"]], dep_var="Sales", valid_idx=joined.sample(frac=0.2).index, procs=procs, cat_names=cat_vars, cont_names=contin_vars, test_df=None)

...

/opt/conda/lib/python3.7/site-packages/fastai/data_block.py in process(self, xp, yp, name)
    618                     if len(getattr(p, 'warns', [])) > 0:
    619                         warnings = list(set(p.warns))
--> 620                         self.warn += ', '.join(warnings[:5])
    621                         if len(warnings) > 5: self.warn += "..."
    622                     p.warns = []

TypeError: sequence item 0: expected str instance, int found
```
Link to full backtrace : https://gist.github.com/andaag/d048c5947dccae75787509c1ae500408

Trying to load the same dataset in the latest fastai version installed from conda I get the following error : "Exception: Your validation data contains a label that isn't present in the training set, please fix your data."
 - However, my dataset is regression, not classification.

Casting my input from int64 to float makes the dataset load just fine - in git head, but produces the exception "TypeError: __init__() got an unexpected keyword argument 'classes'" in latest released in conda.

**Provide your installation details**
```text
=== Software === 
python        : 3.7.1
fastai        : 1.0.40.dev0
fastprogress  : 0.1.18
torch         : 1.0.0
nvidia driver : 415.25
torch cuda    : 9.0.176 / is available
torch cudnn   : 7401 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 8119MB | GeForce GTX 1070

=== Environment === 
platform      : Linux-4.18.0-13-generic-x86_64-with-debian-stretch-sid
distro        : #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018
conda env     : Unknown
python        : /opt/conda/bin/python
sys.path      : /home/jovyan/work/deeplearning/datasets/rossman
/opt/conda/lib/python37.zip
/opt/conda/lib/python3.7
/opt/conda/lib/python3.7/lib-dynload

/opt/conda/lib/python3.7/site-packages
/opt/conda/lib/python3.7/site-packages/IPython/extensions
/home/jovyan/.ipython
```

**To Reproduce**
The dataset for this is rather large and hard to reproduce. Does my error make sense? If this requires effort on your side in order to track down and understand, let me know and I'll upload my dataset somewhere.

I can also try to reproduce this from a branch with some print statements or something like that if that'd help.

**Expected behavior**
Expected behavior 1 : Dataset should load just fine as int64
Expected behavior 2 : Error should be captured and rendered correctly.

**Comment by andaag** [comment]
Having problems reproducing this, will do another round from disk just to ensure my report isn't incorrect...

**Comment by sgugger** [comment]
I'm not sure what the issue is. The factory methods are very basic way to quickly get started for beginner in classification problems, so don't expect them to work all the time. For the highest flexibility, you should use the data block API where you can force the library to acknowledge this is a regression problem by passing `label_cls=FloatList`.

With the factory method, the library tries its best to guess what the problem is, which is why you have no problem when casting your target to float (on master, there were bugs recently corrected). If the target is an int, the default is classification and it won't change.

**Comment by andaag** [comment]
Maybe an option here is to print out to the user what the library automatically infers? At least in case of exceptions?

If it did it'd be pretty easy to spot that it's picking a classification problem with a few million classes.

**Comment by sgugger** [comment]
I'll see what's possible to do.

**Comment by andaag** [comment]
If you have any concrete ideas I can try making a PR. My time is a bit.. unstable, but I want to help, and it might be good to get my hands dirty with something simple.

**Comment by sgugger** [comment]
On further investigation, the error came while building a warning for the user, I just added the labeling class to it.
