### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '.data/cifar10/train'

### ISSUE THREAD

**Issue by usake** [fastai/fastai#1454]
**Describe the bug**

**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by usake** [comment]
where could I find this dataset?

**Comment by sgugger** [comment]
Googling its name might help to begin with: https://www.cs.toronto.edu/~kriz/cifar.html. Also there is a helper function in fastai that will download it for you:
`untar_data(URLs.CIFAR)`
