### ISSUE TITLE
Text classification with float target value: pad_collate cannot create target tensor

### ISSUE THREAD

**Issue by tchambon** [fastai/fastai#1455]
When creating a text classifier with float target values, pad_collate calls tensor() to create the target values array with  an array of array. This gives the error:  len() of unsized object

This is a gist of how to reproduce the bug and how to fix the bug for my use case : https://gist.github.com/tchambon/cd9ff7f8851efab1acbadd9207bcb38a

I would like to provide a PR for this but I am afraid this fix could have side effect for other type of target values (ex: for multiclass target values)

**Comment by sgugger** [comment]
Thanks for flagging! I also added a test so that we see if regression suddenly fails in the future.
