### ISSUE TITLE
name accuracy is not defined

### ISSUE THREAD

**Issue by saqibmobin** [fastai/fastai#1463]
I have imported fastai.vision
when i write the following code I get error that "name 'accuracy' is not defined"

learn = create_cnn(data, models.resnet34, metrics=accuracy)
learn.fit_one_cycle(1)

NameError                                 Traceback (most recent call last)
<ipython-input-50-6ec085df1eed> in <module>
----> 1 learn = create_cnn(data, models.resnet34, metrics=accuracy)
      2 learn.fit_one_cycle(1)

NameError: name 'accuracy' is not defined

**Comment by sgugger** [comment]
It's impossible to help you if you don't post your full code. It's looking like an installation issue, so it would be best to go on the [forum](https://forums.fast.ai/t/fastai-v1-install-issues-thread/24111).
