### ISSUE TITLE
[Tabular] "AttributeError: databunch" when split_by_idx not used

### ISSUE THREAD

**Issue by nalepae** [fastai/fastai#1466]
**Observed:**

```
data = (TabularList.from_df(df, cont_names=cont_vars, procs=procs)
      #  .split_by_idx(range(500000, 605750))
        .label_from_df(cols=dep_var, label_cls=FloatList)
        .databunch())
```
throws the following error:
> AttributeError: databunch

Uncommenting the line **#  .split_by_idx(range(500000))** solves the issue.

**Expected:**
I know not splitting data set in not recommended, but, in my opinion, this code should either work or throw a different error, more understandable for the user (like "TabularList should be splitted before getting a databunch on it.")

**Comment by sgugger** [comment]
Done. Note that if you don't want to split your data, you should use `no_split`.

**Comment by nalepae** [comment]
Thanks!

Le lun. 14 janv. 2019 à 15:34, Sylvain Gugger <notifications@github.com> a
écrit :
