### ISSUE TITLE
learn.summary() - unreadable output

### ISSUE THREAD

**Issue by ecatkins** [fastai/fastai#1479]
Does anyone know what might cause the behaviour below, where the `learn.summary()` method is rendered unreadable?

![image](https://user-images.githubusercontent.com/8319226/51332608-0a0c6f80-1a4a-11e9-9520-8c53907c67cf.png)

Also, a secondary question. It appears that the `learn.summary()` method is not implemented for text learners. Is there any intention to do this?

**Comment by sgugger** [comment]
You should print it to have it readable (we prefer fastai functions not to print anything when possible), so the use is `print(learn.summary())`.
As for text learners, you will have to ask the author of `model_summary` on the [forum](https://forums.fast.ai/t/model-summary-implementation/31193).

**Comment by ecatkins** [comment]
@sgugger Thanks! You might want to update [this](https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson3-camvid-tiramisu.ipynb) course notebook to include the `print` statement - it's where I pulled that line of code from

**Comment by sgugger** [comment]
Oh, it must be from before we changed the function. Thanks for flagging and feel free to suggest a PR to amend that!
