### ISSUE TITLE
ImageDataBunch.from_lists shuffles labels

### ISSUE THREAD

**Issue by Andras7** [fastai/fastai#1481]
ImageDataBunch.from_lists function doesn't work correctly, it causes label inconsistency.

When I convert my dataset into csv format then everything works fine with ImageDataBunch.from_csv function.

````text
=== Software === 
python        : 3.6.8
fastai        : 1.0.40
fastprogress  : 0.1.18
torch         : 1.0.0
nvidia driver : 410.78
torch cuda    : 10.0.130 / is available
torch cudnn   : 7401 / is enabled
=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11178MB | GeForce GTX 1080 Ti
=== Environment === 
platform      : Linux-4.15.0-43-generic-x86_64-with-debian-buster-sid
distro        : #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018
conda env     : base
python        : /home/andras/anaconda3/bin/python
sys.path      : /home/andras/Desktop/deep_image_rank
/home/andras/pycharm-community-2018.2.4/helpers/pydev
/home/andras/Desktop/deep_image_rank
/home/andras/pycharm-community-2018.2.4/helpers/third_party/thriftpy
/home/andras/pycharm-community-2018.2.4/helpers/pydev
/home/andras/anaconda3/lib/python36.zip
/home/andras/anaconda3/lib/python3.6
/home/andras/anaconda3/lib/python3.6/lib-dynload
/home/andras/.local/lib/python3.6/site-packages
/home/andras/anaconda3/lib/python3.6/site-packages
/home/andras/anaconda3/lib/python3.6/site-packages/warpctc_pytorch-0.1-py3.6-linux-x86_64.egg
/home/andras/anaconda3/lib/python3.6/site-packages/IPython/extensions
/home/andras/Desktop/deep_image_rank
```
Please make sure to include opening/closing ``` when you paste into forums/github to make the reports appear formatted as code sections.
Optional package(s) to enhance the diagnostics can be installed with:
pip install distro
Once installed, re-run this utility to get the additional information`

**Comment by sgugger** [comment]
`ImageDataBunch.from_lists` is more intended to be used behind the scenes than in front end, so I'm not sure you used it properly. In any case there is nothing we can do without at least seeing the code you tried...

**Comment by Andras7** [comment]
I will show you the code, but it really easy to test. it would be really useful to have a function like this in the front end.

**Comment by Andras7** [comment]
**here is my sampe test code**

common part:
`images = dataset[:, url_idx] # array(['/home/....68708.jpg', '/home/..91083.jpg', ........
labels = dataset[:, category_idx] # array(['graceland', 'puma', 'nike', 'converse' ........`

this code doesent work:
`path = Path("/home/andras/datasets/")
data = ImageDataBunch.from_lists(path, images, labels, ds_tfms=get_transforms(), size=224).normalize(imagenet_stats)
data.show_batch(rows=4, figsize=(14, 12)) # this shows the first wrong figure`
![figure_1](https://user-images.githubusercontent.com/28984142/51417148-f7468780-1b7c-11e9-9ba4-50e96b6be207.png)



Here is my fix:
`with open('a.csv', 'w') as f:
    for i in range(len(images)):
        f.write(f'{images[i]},{labels[i]}\n')

data = ImageDataBunch.from_csv('/', csv_labels='/home/andras/Desktop/deep_image_rank/a.csv',
                              ds_tfms=get_transforms(), size=224).normalize(imagenet_stats)
data.show_batch(rows=4, figsize=(14, 12))
`
![figure_2](https://user-images.githubusercontent.com/28984142/51417178-1ba26400-1b7d-11e9-9d47-8a94fa2dc95c.png)

**Comment by Andras7** [comment]
**here is my sampe test code**

common part:
`images = dataset[:, url_idx] # array(['/home/....68708.jpg', '/home/..91083.jpg', ........
labels = dataset[:, category_idx] # array(['graceland', 'puma', 'nike', 'converse' ........`

this code doesent work:
`path = Path("/home/andras/datasets/")
data = ImageDataBunch.from_lists(path, images, labels, ds_tfms=get_transforms(), size=224).normalize(imagenet_stats)
data.show_batch(rows=4, figsize=(14, 12)) # this shows the first wrong figure`
![figure_1](https://user-images.githubusercontent.com/28984142/51417148-f7468780-1b7c-11e9-9ba4-50e96b6be207.png)



Here is my fix:
`with open('a.csv', 'w') as f:
    for i in range(len(images)):
        f.write(f'{images[i]},{labels[i]}\n')

data = ImageDataBunch.from_csv('/', csv_labels='/home/andras/Desktop/deep_image_rank/a.csv',
                              ds_tfms=get_transforms(), size=224).normalize(imagenet_stats)
data.show_batch(rows=4, figsize=(14, 12))
`
![figure_2](https://user-images.githubusercontent.com/28984142/51417178-1ba26400-1b7d-11e9-9d47-8a94fa2dc95c.png)

**Comment by sgugger** [comment]
Sorry I mixed the method with another one. This is indeed a front-end function that needs fixing. Will do in a bit.
