### ISSUE TITLE
Cannot import structures module

### ISSUE THREAD

**Issue by muggle14** [fastai/fastai#1483]
**Describe the bug**

**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by muggle14** [comment]
Cannot import structures module on windows

**Comment by sgugger** [comment]
What is you version of fastai? There is no structured module in v1.

**Comment by muggle14** [comment]
In the machine learning course, we import
from fastai.imports import *
from fastai.structured import *
In the module, I don't find the structured file

**Comment by sgugger** [comment]
Yes, and as is indicated on each notebook, you need to install v0.7 for this course.
