### ISSUE TITLE
simple resize w/o transforms

### ISSUE THREAD

**Issue by stas00** [fastai/fastai#1494]
This is about implementing a simple equivalent of pytorch's [transforms.Resize(size)](https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.Resize).

Currently, in order to do that some special magic is required. The user must either not pass the `ds_tfms` argument, or pass it as `ds_tfms=[[],[]]`. And if `ds_tfms=[]` and `size` args are passed, fastai silently does nothing. e.g. the following silently ignores the `size` argument:

```
data = ImageDataBunch.from_name_re(path_img, fnames, pat, ds_tfms=[], size=224, bs=bs).normalize(imagenet_stats)
```

Can we please improve this interface to make it less error-prone and more user-friendly? In particular:

1. If `ds_tfms=[]` and `size` are passed fastai should assert
2. can we not need to demand an awkward `ds_tfms=[[],[]]` and match it with  `ds_tfms=[]`. The problem is that while the user experiments with `ds_tfms`, it's usually convenient to keep the ds_tfms argument at some point making it `[]`. If a user is required to do `[[],[]]` surely the library can do better than that.
3. on the other hand resize is a transform in pytorch, why not create an actual transform function called resize? so that it's not a magical side-effect but an explicit function. in which case there is no need to fix (2)

And thinking more about resize in general:

Documentation-wise it probably should recommend not to do a bare resize transform, since it's a wasteful operation repeated on every re-run and it should ideally be done once and the results saved on the filesystem. With the details on how to do that.

Thanks.

**Comment by stas00** [comment]
fixed by @sgugger https://github.com/fastai/fastai/commit/25a4a8667e5d46b0b6b11f46789c2b5f0f9176f6

**Comment by stas00** [comment]
More related issues:

If I pass:

size=(224,224)

```data = ImageDataBunch.from_name_re(path_img, fnames, pat, ds_tfms=None, size=(224,224), bs=bs).normalize(imagenet_stats)```

I get this:
```
fastai/basic_data.py:234: UserWarning: It's not possible to collate samples of your dataset together in a batch.
Shapes of the inputs/targets:
[[torch.Size([3, 356, 500]), torch.Size([3, 375, 500]),
```

this doesn't happen w size=224.

**Comment by xnutsive** [comment]
I fixed a related issue with passing 2dim sizes instead of 3dim, I can take on that and fix it tomorrow. 

Do you think databunch should support both `size=(h,w)` and `size=(channels, h, w)` and not raise a warning on `(h,w)`? 

It's cool to provide a very flexible API, my question is more about would it still be consistent across other parts of fastai and other DL libraries, is it a good practice to accept different shapes of arguments and fix them on the fly without providing feedback to the user?

**Comment by stas00** [comment]
I'd say at the very least it should match [transforms.Resize(size)](https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.Resize), support (h,w) that is.

For channels I'd say a different transform would be the best. And surely, it does need attention. For example, currently if you have a 1 channel image, it gets silently upgraded to 3 if you apply normalize(imagenet).

I see pytorch doesn't have such a transform, other than the other way around [to_grayscale](https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.functional.to_grayscale).

But I will let captain @sgugger follow up.

**Comment by stas00** [comment]
I no longer can find that code where I was having this issue, and perhaps @xnutsive solution fixed it since my report predates his post, so I will close it for now and if others encounter the same issue please reopen it ideally with a full example to reproduce, which I failed to provide in first place.

**Comment by cluePrints** [comment]
I have this sort of problem in 1.0.41 / cpu / google colab ([notebook|https://colab.research.google.com/drive/1A9H-6QyS-NlTfZaNjCM2TbifODmvxOTG#scrollTo=_kuCPJS1r_rJ].

@stas00 do you mind if I'll reopen this issue & look into getting it fixed?

It also leads to occasional hanging when multiple workers are used (~1/5 cases on 2 cpus).

Code and traceback are below just in case

```
transforms = None
batch_size = 2
num_workers = 1

import os
import requests
import contextlib
import tempfile
import shutil
import pdb

@contextlib.contextmanager
def tempdir():
    dirpath = tempfile.mkdtemp()
    try:
      yield dirpath
    finally:
      shutil.rmtree(dirpath)

def create_image(tmp_image, w, h):
  if not os.path.isfile(tmp_image):
    response = requests.get(f'https://picsum.photos/{w}/{h}')
    img = response.raw.read()
    with open(tmp_image, 'wb') as f:
        for chunk in response.iter_content(1024):
            f.write(chunk)
            
with tempdir() as tmp:
  if not os.path.exists(tmp):
    os.makedirs(tmp)
  for i in range(10):
    create_image(f'{tmp}/{i}.jpg', 300-i, 200+i)
  item_list = ImageItemList.from_folder(tmp)
  split_list = item_list.random_split_by_pct(0.5)
  labeled_list = split_list.label_from_folder()
  labeled_list = labeled_list.transform(tfms=None, size=10)
  
  # this spits warns
  data = labeled_list.databunch(bs=batch_size, num_workers=num_workers).normalize(imagenet_stats)

  # this breaks / hangs
  next(iter(data.train_dl))
```

```
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/fastai/torch_core.py", line 110, in data_collate
    return torch.utils.data.dataloader.default_collate(to_data(batch))
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 232, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 232, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 209, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 205 and 208 in dimension 2 at /pytorch/aten/src/TH/generic/THTensorMoreMath.cpp:1333
```

**Comment by stas00** [comment]
you never need to ask if you can re-open a closed issue, if you feel that you have the same issue you can always re-open it - or opening a new one - it is your call.
