### ISSUE TITLE
Inconsistent repr for data and its items

### ISSUE THREAD

**Issue by stas00** [fastai/fastai#1496]
`data`'s repr and its items' repr are inconsistent when tfms are registered (like resize):

```
data = ImageDataBunch.from_name_re(path_img, fnames, pat, ds_tfms=None, size=224, bs=bs).normalize(imagenet_stats)
data.train_ds[0]
data
```
gives:
```
(Image (3, 224, 224), Category wheaten_terrier)
ImageDataBunch;
[...]
[Image (3, 330, 500),
```
The item shows the size after resize, the whole shows the original size.

**Comment by nvs-abhilash** [comment]
Hi @stas00 big fan :). I though I would dig into this. 

I was experimenting with the MNIST sample dataset.

It seems when one tries to get `repr` for  `data.train_ds[0]`, the `__getitem__` method from `fastai/data_block.py/LabelList` is called: [data_block.py#L565](https://github.com/fastai/fastai/blob/master/fastai/data_block.py#L565)

And as you can note that the x and y are transformed on-demand and then returned.

But when we call `repr` on the `data` itself, it calls the `repr` methods of individual datasets, and finally the `repr` method is called for x directly without transforming it. [data_block.py#L539](https://github.com/fastai/fastai/blob/master/fastai/data_block.py#L539).

Hence the inconsistency in the output.

But, I am not sure how to correct this, I thought of multiple approaches like 
* transforming `self.x` and `self.y` somehow. But I guess this would make things slow.

Maybe we can take some inspiration from how `data.show_batch()` works. I guess it's a visual version of what we need. But I am not sure how to proceed, any suggestions?

**Comment by sgugger** [comment]
So a `LabelList` will now use its internal `__getitem__` to sample items for its representation, which means transforms will be applied. In your example, `data` will give the right sizes.
If one goes inside to grab the individual `ItemList`, `data.train_ds.x` for instance, the transforms won't be applied and we will see the original sizes.
