### ISSUE TITLE
Index out of bounds in learn.show_results() for WGAN

### ISSUE THREAD

**Issue by deichastronaut** [fastai/fastai#1501]
**Describe the bug**

Hi,

I try to train a WGAN. After the training, I try to get a sample of generated images, but i get an index out of bounds error (see below). 

Regards, Christian

This is what I run in the notebook:

learn.gan_trainer.switch(gen_mode=True)
learn.show_results(ds_type=DatasetType.Train, rows=16, figsize=(8,8))

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-12-9be5862cf1ee> in <module>
      1 learn.gan_trainer.switch(gen_mode=True)
----> 2 learn.show_results(ds_type=DatasetType.Train, rows=16, figsize=(8,8))

~/anaconda3/envs/fai10/lib/python3.7/site-packages/fastai/basic_train.py in show_results(self, ds_type, rows, **kwargs)
    313                 preds = self.data.denorm(preds, do_x=True)
    314         analyze_kwargs,kwargs = split_kwargs_by_func(kwargs, ds.y.analyze_pred)
--> 315         preds = [ds.y.analyze_pred(grab_idx(preds, i), **analyze_kwargs) for i in range(rows)]
    316         xs = [ds.x.reconstruct(grab_idx(x, i)) for i in range(rows)]
    317         if has_arg(ds.y.reconstruct, 'x'):

~/anaconda3/envs/fai10/lib/python3.7/site-packages/fastai/basic_train.py in <listcomp>(.0)
    313                 preds = self.data.denorm(preds, do_x=True)
    314         analyze_kwargs,kwargs = split_kwargs_by_func(kwargs, ds.y.analyze_pred)
--> 315         preds = [ds.y.analyze_pred(grab_idx(preds, i), **analyze_kwargs) for i in range(rows)]
    316         xs = [ds.x.reconstruct(grab_idx(x, i)) for i in range(rows)]
    317         if has_arg(ds.y.reconstruct, 'x'):

~/anaconda3/envs/fai10/lib/python3.7/site-packages/fastai/torch_core.py in grab_idx(x, i, batch_first)
    285 def grab_idx(x,i,batch_first:bool=True):
    286     "Grab the `i`-th batch in `x`, `batch_first` stating the batch dimension."
--> 287     if batch_first: return ([o[i].cpu() for o in x]   if is_listy(x) else x[i].cpu())
    288     else:           return ([o[:,i].cpu() for o in x] if is_listy(x) else x[:,i].cpu())
    289 

IndexError: index 128 is out of bounds for dimension 0 with size 128

**Provide your installation details**
```text
=== Software === 
python        : 3.7.2
fastai        : 1.0.41
fastprogress  : 0.1.18
torch         : 1.0.0
nvidia driver : 410.78
torch cuda    : 9.0.176 / is available
torch cudnn   : 7401 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11178MB | GeForce GTX 1080 Ti

=== Environment === 
platform      : Linux-4.15.0-43-generic-x86_64-with-debian-buster-sid
distro        : #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018
conda env     : fai10
python        : /home/christian/anaconda3/envs/fai10/bin/python
sys.path      : /ml/fastai10/course-v3/nbs/dl1
/home/christian/anaconda3/envs/fai10/lib/python37.zip
/home/christian/anaconda3/envs/fai10/lib/python3.7
/home/christian/anaconda3/envs/fai10/lib/python3.7/lib-dynload

/home/christian/anaconda3/envs/fai10/lib/python3.7/site-packages
/home/christian/anaconda3/envs/fai10/lib/python3.7/site-packages/IPython/extensions
/home/christian/.ipython
```

Please make sure to include opening/closing ``` when you paste into forums/github to make the reports appear formatted as code sections.

Optional package(s) to enhance the diagnostics can be installed with:
pip install distro
Once installed, re-run this utility to get the additional information

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
`rows=16` will try to make 16 by 16 images which is probably greater than your batch size? I'll put an assert there as this error comes often.

**Comment by deichastronaut** [comment]
Oh, yes. Thanks, with a lower number of rows it's working.

**Comment by sgugger** [comment]
Now it silently falls back to maximum batch size elements.
