### ISSUE TITLE
lesson1-vgg.ipynb issue will be submit this bug

### ISSUE THREAD

**Issue by cableyang** [fastai/fastai#1503]
https://github.com/fastai/fastai/blob/master/courses/dl1/lesson1-vgg.ipynb
==============================================
issue : line 21   couldn`t run locally 
log_preds,y = learn.TTA()
probs = np.mean(np.exp(log_preds),0)accuracy_np(probs,y)

==============================================
should write next line like this :

log_preds,y = learn.TTA()
probs = np.mean(np.exp(log_preds),0)
accuracy_np(probs,y)

**Comment by sgugger** [comment]
Yes, there should be a new line. Would you mind submitting a PR to add it?

**Comment by stas00** [comment]
master branch please. thank you.

**Comment by githubssd** [comment]
Forgot to put a semicolon. 
probs = np.mean(np.exp(log_preds),0); accuracy_np(probs,y)
