### ISSUE TITLE
Use fastai with vision task errors if spacy not installed

### ISSUE THREAD

**Issue by PsidomPC** [fastai/fastai#1522]
**Describe the bug**

Fastai errors if spacy is not installed;

**Provide your installation details**

Can't run this, gives error:

`ModuleNotFoundError: No module named 'spacy'`

**To Reproduce**

Install fastai with `--no-deps` and then run:

`from fastai.vision import *`

**Expected behavior**

For vision task, `spacy` should not be required;

**Screenshots**

**Additional context**

**Comment by stas00** [comment]
Thank you, fixed by https://github.com/fastai/fastai/commit/bcce0be0150f97f096b30da6ccfbe0198de9bf59
