### ISSUE TITLE
Error/unexpected behavior with untar_data function

### ISSUE THREAD

**Issue by jiata** [fastai/fastai#1528]
**Describe the bug**
I want use the `untar_data` function and specify where the data lives (i dont want to use the default `~/.fastai/data` location).

When i pass in params for the `fname` and `dest`, the results are not as expected. When I run the following:
```
untar_data(URLs.PETS, "/mnt/data/fastai/pets-tar.tgz", "/mnt/data/fastai/pets")
```
I would expect the tarred file to be in saved to `/mnt/data/fastai/pets-tar.tgz`, and the untarred data to be in this location: `/mnt/data/fastai/pets`.  

Instead, i end up with:
```bash
/mnt/data/fastai $ ls
oxford-iiit-pet  pets-tar.tgz
```
and the following error:
![image](https://user-images.githubusercontent.com/16616215/51813229-33679f80-2283-11e9-9a35-70e15966faf1.png)

It looks to me that the function creates the PosixPath based on the `dest` variable i passed it, but actually untarred the result to a different folder name (`oxford-oiiit-pet` in this case), and so the PosixPath reference is broken.

**Provide your installation details**
```text
=== Software ===
python        : 3.7.1
fastai        : 1.0.42
fastprogress  : 0.1.18
torch         : 1.0.0
nvidia driver : 410.73
torch cuda    : 9.0.176 / is available
torch cudnn   : 7401 / is enabled

=== Hardware ===
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 16130MB | Tesla V100-PCIE-16GB

=== Environment ===
platform      : Linux-4.15.0-1036-azure-x86_64-with-debian-buster-sid
distro        : #38-Ubuntu SMP Fri Dec 7 02:47:47 UTC 2018
conda env     : cvbp
python        : /home/jiata/anaconda3/envs/cvbp/bin/python
sys.path      : /home/jiata/learn/fastai/course-v3/nbs/dl1
/home/jiata/anaconda3/envs/cvbp/lib/python37.zip
/home/jiata/anaconda3/envs/cvbp/lib/python3.7
/home/jiata/anaconda3/envs/cvbp/lib/python3.7/lib-dynload
/home/jiata/.local/lib/python3.7/site-packages
/home/jiata/anaconda3/envs/cvbp/lib/python3.7/site-packages
```

**To Reproduce**
1. Create dir `/mnt/data/fastai`
1. Created a new cell and run the following:
`path = untar_data(URLs.PETS, "/mnt/data/fastai/pets-tar.tgz", "/mnt/data/fastai/pets"); path`

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kdorichev** [comment]
As of now, on `fastai v.1.0.43.dev0`, the file is downloaded with correct, specified name -- `pets-tar.tgz` in this case, but is untarred into data.**parent** directory -- `/mnt/data/fastai/`.  
```
tarfile.open(fname, 'r:gz').extractall(dest.parent)
```
`untar_data` returns unexisting path.

With a simple fix 
```
tarfile.open(fname, 'r:gz').extractall(dest)
```
I was able to acheve expected behavior -- the tar was untarred into `/mnt/data/fastai/pets` directory.

I will now submit a pull request.

**Comment by kdorichev** [comment]
@jiata Note, that the untarred file will have the structure of the tar file, including `oxford-iiit-pet`, namely:
```
└── pets
    └── oxford-iiit-pet
        ├── annotations
        │   ├── trimaps
        │   └── xmls
        └── images
```

**Comment by sgugger** [comment]
There was a problem with the fix proposed by @kdorichev  so I changed it. Note that as he pointed out, you will still get the structure
```
└── pets
    └── oxford-iiit-pet
        ├── annotations
        │   ├── trimaps
        │   └── xmls
        └── images
```
What the function returns in this case is `Path("pets/oxford-iii-pet")`.
