### ISSUE TITLE
Learner.export and load_learner malfunction when custom classes are used in creating the databunch

### ISSUE THREAD

**Issue by odysseus0** [fastai/fastai#1540]
**Describe the bug**
`Learner.export` and `load_learner` aim to provide a convenient way of exporting and loading trained model with one command, without the need to go through the data block API and new learner creation, which is what `Leaner.load` requires.

However, when we used a customized class in the data block API, for example in the following code

```python
class SegLabelListCustom(SegmentationLabelList):
    def open(self, fn): return open_mask(fn, div=True)
    
class SegItemListCustom(ImageItemList):
    _label_cls = SegLabelListCustom

src = (SegItemListCustom.from_folder(path_img)
        .random_split_by_pct()
        .label_from_func(get_y_fn, classes=codes))
tfms = get_transforms(flip_vert=True, max_warp=0, max_zoom=1.2, max_lighting=0.3)
data = (src.transform(tfms, size=size, tfm_y=True)
        .databunch(bs=bs)
        .normalize(imagenet_stats))
```
`learn.export()` and `load_learner` would throw an error.

Such a setup was necessary to deal with a common kind of image segmentation datasets which uses 0 and 255 to encode the mask, supposedly for the ease of mask visualization when opened as a normal image file, as 0 and 255 will be white and black:

![image](https://user-images.githubusercontent.com/8635094/51953903-27453300-2479-11e9-8d31-221ae31b7bf3.png)

The above code snippet was recommended by a student based on a suggestion of our wonderful maintainer Sylvian Gruger in the forum, when Sylvian is trying to help students dealing with such segmentation dataset: https://forums.fast.ai/t/unet-binary-segmentation/29833/42. So far, it seems the best way to deal with such dataset.

However, when we trained a model using such a customized data block and ran `learn.export()`, `load_learner` would not work straight out of the box. There will be an Error:

```python
AttributeError: Can't get attribute 'SegItemListCustom' on <module '__main__'>
```

The problem can be easily solved by running the code containing the customized class and loading it into the memory before running `load_learner`. However, it in some sense breaks the nice and convenient design of `load_learner`, which is supposed to work out of the box with just the `export.pkl` file. Is there any way to make `learn.export` serialize the customized class and package it into the `export.pkl` file as well?

**Provide your installation details**
```text
=== Software === 
python        : 3.6.8
fastai        : 1.0.42
fastprogress  : 0.1.18
torch         : 1.0.0.dev20190121
nvidia driver : 396.44
torch cuda    : 9.0.176 / is available
torch cudnn   : 7401 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 16160MB | Tesla V100-SXM2-16GB

=== Environment === 
platform      : Linux-4.9.0-8-amd64-x86_64-with-debian-9.6
distro        : #1 SMP Debian 4.9.130-2 (2018-10-27)
conda env     : Unknown
python        : /opt/anaconda3/bin/python
sys.path      : /opt/anaconda3/lib/python36.zip
/opt/anaconda3/lib/python3.6
/opt/anaconda3/lib/python3.6/lib-dynload

/opt/anaconda3/lib/python3.6/site-packages
/opt/anaconda3/lib/python3.6/site-packages/IPython/extensions
/home/jupyter/.ipython

Wed Jan 30 02:11:52 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    34W / 300W |     10MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

**To Reproduce**
Run `learn.export()` at the end of [this notebook](https://github.com/daveluo/zanzibar-aerial-mapping/blob/master/znz-segment-buildingfootprint-20190108-alldata.ipynb). Then, restart the kernel, execute the necessary imports and path variable definition, and run `load_learner(path_img)`.

**Expected behavior**
A fully trained learner should be loaded correctly from the `export.pkl` by `load_learner`. However, her e there will be an Attribute Error instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/8635094/51954404-10074500-247b-11e9-8ef3-ec9569a1b124.png)

**Comment by sgugger** [comment]
I'm afraid there is nothing we can do for this. The serialization uses pytorch, which uses pickle behind the scenes, which doesn't compile the source code of the functions used, just serialize their names. 
It's the same if you have custom layers in your model for instance, you'll need to redefine them at inference time.

**Comment by zzz123xyz** [comment]
If so, Could you guys give an example or template about how to correctly use export() and load_learner functions in the customization case?

**Comment by garrettmsft7** [comment]
+1. Would be interested to know what the best practices are too.

**Comment by ashutoshraj** [comment]
> If so, Could you guys give an example or template about how to correctly use export() and load_learner functions in the customization case?

Did you get any best template to recover the same learner?

**Comment by zzz123xyz** [comment]
> > If so, Could you guys give an example or template about how to correctly use export() and load_learner functions in the customization case?
> 
> Did you get any best template to recover the same learner?

Hi @ashutoshraj , not yet, I still use learner.save. do you have any updates recently?
