### ISSUE TITLE
Vocab minimum frequency is one more than desired

### ISSUE THREAD

**Issue by andrewbest** [fastai/fastai#1544]
I have attempted to create a vocab that ignores no tokens. I find that I have to set min_freq=0. It seems to me that it should be min_freq=1. I am guessing it is an off by one error in this comparison.

transform.py:
itos = [o for o,c in freq.most_common(max_vocab) if c > min_freq]

Relevant code to reproduce this issue:
data_lm = TextLMDataBunch.from_df(folder, df_trn, df_val, bs=32, min_freq=1)

**Comment by sgugger** [comment]
Good point! Changed the default from 2 to 3 as a consequence.
