### ISSUE TITLE
Transform pathlib.WindowsPath to posix before calling str

### ISSUE THREAD

**Issue by ahartikainen** [fastai/fastai#1547]
**Describe the bug**

Currently pathlib.WindowsPath are transformed to windows pathlike, which means that regular expression assuming posix format will fail.

**To Reproduce**

    import pathlib
    a = pathlib.WindowsPath("./hello/world.py")
    str(a) # ".\\hello\\world.py"

This can be fixed by testing if given path is a pathlib object and then calling `.as_posix()` which returns a string

    a_posix = a.as_posix() 
    a_posix  # "./hello/world.py"
    str(a_posix) # "./hello/world.py"

**Expected behavior**

Regular expression using path separator should work on all OS.

**Additional context**

If the current behaviour is wanted, then nothing should be done.

**Comment by ahartikainen** [comment]
For example `fastai/vision/data.py` # line 300

from

    def _get_label(fn): return pat.search(str(fn)).group(1)

to

    from pathlib import WindowsPath as _WindowsPath # line 2

    def _get_label(fn): # line 301
        if isinstance(fn, _WindowsPath):
            fn = fn.as_posix()
        return pat.search(str(fn)).group(1)

**Comment by sgugger** [comment]
Changed the places I could think of, let me know if you see other ones missing.

**Comment by ahartikainen** [comment]
Thanks for that.

I'm not sure if `as_posix` work if input is `str` and not `pathlib.Path`. Do those functions accept `str`?

**Comment by sgugger** [comment]
Ah yes. In the data block API they'll be Path objects but not necessarily in the factory method in data.vision. Will add a check.
