### ISSUE TITLE
label_by_df causing AttributeError

### ISSUE THREAD

**Issue by rsk2327** [fastai/fastai#1549]
**Describe the bug**
Using label_by_df raises an AttributeError : 'numpy.int64' object has no attribute 'isna'. This seems to be occurring because _maybe_squeeze converts labels into a numpy array but the very next line uses .isna(), which is a method of a Pandas Series object. 

**Provide your installation details**
=== Software === 
python        : 3.6.8
fastai        : 1.0.39
fastprogress  : 0.1.18
torch         : 1.0.0
nvidia driver : 410.79
torch cuda    : 9.0.176 / is available
torch cudnn   : 7401 / is enabled

**To Reproduce**
`d = ImageItemList.from_csv(path='/home/data/',csv_name='/home/dataFile.csv', cols='files')
                              .split_from_df(col='train').label_from_df(cols='label').databunch()
`

**Screenshots**
[https://ibb.co/Nx6Kdrj](url)

**Solution**
Run the assert statement before the _maybe_squeeze() method

**Comment by enricodata** [comment]
I have a similar issue, can you explain better how you solved it?

**Comment by rsk2327** [comment]
I believe @sgugger had already made the required changes and hence the issue was closed. Fastai version has changed since then. Probably the newest version wouldnt have the same issue

**Comment by enricodata** [comment]
I was using the version 1.0.59.dev0 which should be the newest
