### ISSUE TITLE
Add skip_start argument to all loss plots.

### ISSUE THREAD

**Issue by gcp** [fastai/fastai#1553]
Currently, only the learning rate finder has a skip_start option, to ignore the first (few) epochs.

I think this would be useful for all loss plots. 

Currently plot_loss() has a "last" argument, which is vaguely similar, but probably less useful (how does it interact with early stopping?) and in any case a somewhat inconsistent API.

**Comment by sgugger** [comment]
Sounds right. Would you be willing to suggest a PR to address this?

**Comment by TheAnig** [comment]
I can work on it. I'm assuming this is the function [plot_loss()](https://github.com/fastai/fastai/blob/master/old/fastai/sgdr.py#L100)
