### ISSUE TITLE
ClassificationInterpretation plot_multi_top_losses exception

### ISSUE THREAD

**Issue by EtienneT** [fastai/fastai#1565]
**Describe the bug**
Using ClassificationInterpretation plot_multi_top_losses method throws an exception for multi label image classification.

After fitting my model on a multi-label classification task, I ran the following code:

```
interp = ClassificationInterpretation.from_learner(learn)
interp.plot_multi_top_losses()
```

Then got the following exception:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-20-e309d37e2ae1> in <module>
----> 1 interp.plot_multi_top_losses()

~\Anaconda3\lib\site-packages\fastai\vision\learner.py in plot_multi_top_losses(self, samples, figsz, save_misclassified)
    130                 mismatches_idxs.append(i)
    131                 losses_mismatches.append((losses[i][pred],i))
--> 132             infotup=(i, pred, where_truth, losses[i][pred], np.round(self.probs[i], decimals=3)[pred], mismatch)
    133             infolist.append(infotup)
    134         mismatches = self.data.valid_ds[mismatches_idxs]

IndexError: too many indices for tensor of dimension 0
```

**Provide your installation details**
```text
=== Software === 
python        : 3.7.1
fastai        : 1.0.42
fastprogress  : 0.1.18
torch         : 1.0.0
torch cuda    : 10.0 / is available
torch cudnn   : 7401 / is enabled

=== Hardware === 
torch devices : 1
  - gpu0      : GeForce GTX 1070

=== Environment === 
platform      : Windows-10-10.0.17134-SP0
conda env     : base
python        : C:\Users\PC\Anaconda3\python.exe
sys.path      : C:\Users\PC\Dropbox\Bayesian
C:\Users\PC\Anaconda3\python37.zip
C:\Users\PC\Anaconda3\DLLs
C:\Users\PC\Anaconda3\lib
C:\Users\PC\Anaconda3

C:\Users\PC\Anaconda3\lib\site-packages
C:\Users\PC\Anaconda3\lib\site-packages\win32
C:\Users\PC\Anaconda3\lib\site-packages\win32\lib
C:\Users\PC\Anaconda3\lib\site-packages\Pythonwin
C:\Users\PC\Anaconda3\lib\site-packages\IPython\extensions
C:\Users\PC\.ipython
no nvidia-smi is found
```
**To Reproduce**
- Fit a multi-label image classification
- Create a ClassificationInterpretation: interp = ClassificationInterpretation.from_learner(learn)
- Call interp.plot_multi_top_losses()

Here is the code where I create my learner and databunch:

```
bs = 64
np.random.seed(42)
acc_02 = partial(accuracy_thresh, thresh=0.2)
f_score = partial(fbeta, thresh=0.2)
data = ImageDataBunch.from_df(path=path, df=pictures, fn_col='PicturePath', label_col='Labels', label_delim=',', ds_tfms=get_transforms(), size=224, bs=bs).normalize(imagenet_stats)
learn = create_cnn(data, models.resnet34, metrics=[acc_02, f_score])
```

**Expected behavior**
Expected it to work just like the example from the course v3 lesson1 example using ClassificationInterpretation for single label classification.

**Comment by sgugger** [comment]
I can't reproduce your bug. Can you try if you have it on master? It may have already been solved.

**Comment by EtienneT** [comment]
I was testing with the most recent version from conda.  Updated fastai with conda this morning and the problem was still there.

But then setuped fastai from master with the dev instructions and it worked.  So I guess the problem will be resolved in the next release.

Where can we follow changelogs of fastai and when changes are released to conda?

Thanks,

**Comment by sgugger** [comment]
The changelog is [here](https://github.com/fastai/fastai/blob/master/CHANGES.md). The next version will be released sometime next week.
