### ISSUE TITLE
TabularDataBunch.classes only returns categorical columns

### ISSUE THREAD

**Issue by saschahofmann** [fastai/fastai#1579]
The docs are rather sparse on what the `classes` attributes is. I only found:
`classes` attribute: it's used by `ClassificationInterpretation` and also in `collab_learner` (best to use `CollabDataBunch.from_df` than a `pytorch` Dataset) and represents the unique tags that appear in your data.

I am not sure what the behaviour for tabular data should be, but since `classes` are used to produce the confusion matrix plot, I suggest it only returns the used label(s).

Right now, it returns the categorical columns and their possible values. The confusion matrix then shows the right matrix but with wrong axes.

**To Reproduce**
Simply add:

```
from fastai.vision import *
interp = ClassificationInterpretation.from_learner(learn)
interp.plot_confusion_matrix(figsize=(12,12), dpi=60)
```
to the lesson-4-tabular script.

**Comment by saschahofmann** [comment]
Additionally, the behaviour changes when one does not provide categorical parameters. In this case, `.classes` works as expected.

**Comment by sgugger** [comment]
Ah yes, that's because it defaults to the classes of the input `ItemList` when there is one. Will fix.
