### ISSUE TITLE
Unclear variables

### ISSUE THREAD

**Issue by imbolc** [fastai/fastai#162]
Hi guys, thanks a lot for your job, it's the best ml course I've ever seen.

I just have a issue about variable names in notebooks and especially in fastai library. It's ok to read a notebook right after watching its lesson, but if I want to recall something after a few days, I can't do this just looking at code, e.g. `lrf=learn.lr_find()`, I need at least read markdown, think `model.find_learn_rate()` would be much understandable even without any comments.

Btw this does not prevent you to use shortcuts, you can add them as aliases, e.g. `lr_find()` would be an alias for `find_learn_rate()`.

So what do you think? I will look at the code during the course anyway, so I would provide a few pull requests with improved var names if you agree.

**Comment by bhollan** [comment]
We actually had a discussion about this that was recently closed:
https://github.com/fastai/fastai/issues/86

A fellow student created kind of [a glossary of sorts](https://github.com/reshamas/fastai_deeplearn_part1/blob/master/fastai_dl_terms.md).

I hope this helps.

**Comment by imbolc** [comment]
Thanks, @bhollan, going there :)
