### ISSUE TITLE
Problem loading pre trained model in TransformerXL

### ISSUE THREAD

**Issue by rahul-iyer** [fastai/fastai#1622]
Code Run
```
learn = language_model_learner(data_lm,TransformerXL, drop_mult=0.5,pretrained=False)
learn.load_pretrained('data/data/models/bestmodel.pth','data/data/tmp/itos.pkl')
```
Error:
```
Error(s) in loading state_dict for SequentialRNN:
	Unexpected key(s) in state_dict: "0.encoder_dp.emb.weight".
```

Environment
```text
=== Software === 
python        : 3.6.3
fastai        : 1.0.43.dev0
fastprogress  : 0.1.18
torch         : 1.0.0
nvidia driver : 410.48
torch cuda    : 10.0.130 / is available
torch cudnn   : 7001 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 12198MB | Tesla P100-PCIE-12GB

=== Environment === 
platform      : Linux-3.10.0-862.14.4.el7.x86_64-x86_64-with-centos-7.5.1804-Core
distro        : #1 SMP Wed Sep 26 15:12:11 UTC 2018
conda env     : Unknown
python        : /project/6006845/r3iyer/fastai/bin/python
sys.path      : 
/cvmfs/soft.computecanada.ca/easybuild/python/site-packages
/cvmfs/soft.computecanada.ca/custom/python/site-packages
/project/6006845/r3iyer/fastai/lib/python36.zip
/project/6006845/r3iyer/fastai/lib/python3.6
/project/6006845/r3iyer/fastai/lib/python3.6/lib-dynload
/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6
/project/6006845/r3iyer/fastai/lib/python3.6/site-packages
/project/6006845/r3iyer/fastai/lib/python3.6/site-packages/IPython/extensions
/home/r3iyer/.ipython
```

**Comment by stas00** [comment]
May I suggest that you folks that work with text start helping out with the test suite a bit, by including a new fastai test whenever you report a bug (or expand an existing test if it fits) - we have a pretty good coverage for vision, but could use more tests for text. That will ensure that future improvements in the fastai text domain code will not break other previously working features. Thank you.

**Comment by rahul-iyer** [comment]
Sure @stas00 .
I guess the problem is `covert_weights()` is very specific to AWD LSTM and doesn't handle other architectures.

**Comment by stas00** [comment]
then it can be very specific to this architecture. Any test is a great start, then it can evolve to better itself if possible, and if not it'll just test that very specific arch. Does it make sense?

and just to clarify, I'm in no way getting in the way of requiring it for @sgugger to fix it, but meanwhile creating a test would be a goodness. and I'm sure if there were to be a test it'd save him time.

**Comment by sgugger** [comment]
I hadn't gotten to that point yet, but loading pretrained models for transformer and transformerXL should now work.
