### ISSUE TITLE
untar_data file {fname} does not match checksum expected

### ISSUE THREAD

**Issue by pnlph** [fastai/fastai#1636]
```text
KeyError                                  Traceback (most recent call last)

<ipython-input-28-3be7bbd4e733> in <module>()
----> 1 path = untar_data('https://s3.amazonaws.com/fast-ai-imageclas/CUB_200_2011'); path

/usr/local/lib/python3.6/dist-packages/fastai/datasets.py in untar_data(url, fname, dest, data, force_download)
    162         fname = download_data(url, fname=fname, data=data)
    163         data_dir = Config().data_path()
--> 164         assert _check_file(fname) == _checks[url], f"Downloaded file {fname} does not match checksum expected! Remove that file from {data_dir} and try your code again."
    165         tarfile.open(fname, 'r:gz').extractall(dest.parent)
    166     return dest

KeyError: 'https://s3.amazonaws.com/fast-ai-imageclas/CUB_200_2011'
```

untar_data is not working with most of the fastai dataset URLs, eg:
path = untar_data('https://s3.amazonaws.com/fast-ai-imageclas/CUB_200_2011')
path = untar_data('https://s3.amazonaws.com/fast-ai-imageclas/caltech_101')
path = untar_data('https://s3.amazonaws.com/fast-ai-imageclas/oxford-102-flowers')
path = untar_data('https://s3.amazonaws.com/fast-ai-imageclas/food-101')

```text
=== Software === 
python        : 3.6.7
fastai        : 1.0.43
fastprogress  : 0.1.19
torch         : 1.0.1.post2
nvidia driver : 410.79
torch cuda    : 10.0.130 / is available
torch cudnn   : 7402 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11441MB | Tesla K80

=== Environment === 
platform      : Linux-4.14.79+-x86_64-with-Ubuntu-18.04-bionic
distro        : #1 SMP Wed Dec 19 21:19:13 PST 2018
conda env     : Unknown
python        : /usr/bin/python3
sys.path      : 
/env/python
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/usr/local/lib/python3.6/dist-packages/IPython/extensions
/root/.ipython
```

path = untar_data('https://s3.amazonaws.com/fast-ai-imageclas/oxford-102-flowers')
We tried with Colab and Floydhub.

Expected behavior would be downloading and unpacking the file, like:
path = untar_data('https://s3.amazonaws.com/fast-ai-imageclas/oxford-iiit-pet')

**Screenshots**

**Additional context**

**Comment by stas00** [comment]
You're correct, it's because they aren't in the fastai registry. 

So far we only have these: https://github.com/fastai/fastai/blob/master/fastai/datasets.py#L17

Would you be kind to add the missing ones? You will need to add them in the list at the location I listed above and also once again at https://github.com/fastai/fastai/blob/master/fastai/datasets.py#L45 with checksums, here is how you generate the checksums:

```
$ wget https://s3.amazonaws.com/fast-ai-imageclas/oxford-102-flowers.tgz
$ python -c 'import fastai.datasets; print(fastai.datasets._check_file("oxford-102-flowers.tgz"))'
(345236087, '5666e01c1311b4c67fcf20d2b3850a88')
```

feel free to choose a good short name that fits for these, we may tweak them later.

and a bonus to fix that not so helpful assert by adding an earlier assert to check whether the dataset is registered and to give a user-friendly error if it's not.
```
 assert _check_file(fname) == _checks[url], f"Downloaded file {fname} does not match checksum expected! Remove that file from {data_dir} and try your code again."
```

Thank you!

**Comment by sgugger** [comment]
I'll also push a fix that ignores that test if the url isn't in the dictionary of checks, but that doesn't mean a PR with these missing datasets wouldn't be appreciated!

**Comment by pnlph** [comment]
Thanks for the swift response, we added in our PR the rest of the Image Classification and NLP datasets that can be found here:
https://course.fast.ai/datasets

But anyway, there should be a way to untar external datasets (eg. from URLs or Github repositories) that are not included in the fastai registry, shouldn't it?

**Comment by sgugger** [comment]
Yes, that's why I removed the assert when the url isn't in the internal check dictionary.

**Comment by pnlph** [comment]
It seems i cannot send the PR, i receive this in Github Desktop:
Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository.

**Comment by stas00** [comment]
you need to fork it, do the change on your fork and then submit pr. here is a helper app:
https://docs.fast.ai/dev/git.html#how-to-make-a-pull-request-pr

**Comment by pnlph** [comment]
OK thank you, now the PR is sent.

Please @sgugger take a look to avoid your changes to be overwritten. I think we were editing a previous version.
