### ISSUE TITLE
Potential Statistical Bug: _dihedral(...) and _dihedral_affine(...) in fastai.vision

### ISSUE THREAD

**Issue by kechan** [fastai/fastai#1644]
**Describe the bug**
Potential statistics/probabilistic bug for data augmentation transforms of dihedral(...) and dihedral_affine(...). I said potential because I have yet to dig into how uniform distribution are being sampled in fastai. For all I know, it could be doing it weirdly?

**Provide your installation details**
```text
=== Software === 
python       : 3.7.1
fastai       : 1.0.42
fastprogress : 0.1.18
torch        : 1.0.0
torch cuda   : None / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Darwin-17.7.0-x86_64-i386-64bit
conda env    : Unknown
python       : /Users/kelvinchan/tmp/python3_env/deeplearning/bin/python3
sys.path     : 
/Users/kelvinchan/Documents/LearnFastai
/Users/kelvinchan/tmp/python3_env/deeplearning/lib/python37.zip
/Users/kelvinchan/tmp/python3_env/deeplearning/lib/python3.7
/Users/kelvinchan/tmp/python3_env/deeplearning/lib/python3.7/lib-dynload
/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7
/Users/kelvinchan/tmp/python3_env/deeplearning/lib/python3.7/site-packages
/Users/kelvinchan/tmp/python3_env/deeplearning/lib/python3.7/site-packages/IPython/extensions
/Users/kelvinchan/.ipython
no supported gpus found on this system
```

**To Reproduce**
(1) Put this in your notebook
```
from fastai.vision import *
def get_ex(): return open_image('imgs/cat_example.jpg')
tfms = [dihedral_affine()]
[get_ex().apply_tfms(tfms, size=224, padding_mode='zeros').show(ax=ax) 
 for i, ax in enumerate(plt.subplots(rows, cols, figsize = (width, height))[1].flatten())
];
```

(2) 
In your local install (pip), edit this in fastai/vision/transform.py:

```
def _dihedral_affine(k:partial(uniform_int,0,8)):
    "Randomly flip `x` image based on `k`."
    print("k={}".format(k))          // add this line to report the sampled k
    x = -1 if k&1 else 1
```

(3) I found that k of values from 0 through 8 are eventually being printed (if you run multiple times). 0 and 8 are the same and result in no operation. If k is generated uniformly 0 thru 8 (including), then for prob of 2/9, you have no op, while all other op has 1/9. I assume if there's no "p" specified in the transform, k will be uniformly sampled. 

(4) To be sure this statistics is true, i should run exhaustive test and verify this statistically. Since I don't know when i can come around, I will err on the wrong side and just document this here. 

**Expected behavior**
I thought "8" shouldn't be sampled, it should be from 0....7, resulting in 8 flip/rotate? This will result in all 8 orientations having equal probabilities. Of course, if for some reasons this is known to improve generalization, then this is a feature not a bug. I would like to see a paper on this if it's true.

**Comment by sgugger** [comment]
Arg, with all those different conventions in randint we sometimes get confused. It should be 0 to 7, the 8 wasn't supposed to be included. Since you found it, I'll let you do the honor of fixing it, if you don't mind?

**Comment by kechan** [comment]
Ok. If the "uniform" mean randint(...) as in numpy, then this will indeed be a uniform sampling of 0...8 including 8. Of course, this can be by design if you really want to bias towards no op in a simpler  (albert a bit arbitrary/adhoc) manner.

This bug may have subtle impact since it may affect accuracy/results of all trained vision models. Do we want more input from others before going ahead and "fix" this. I am totally new to fastai, and also new to git PR (if you have short concise tutorial, pls send), so this is an excuse for me to have more time. 

Now, if fastai has a philosophy of curating what work best across most cases (this is a tough one in my opinion) by providing that get_transforms(...), and if a bias towards no-op actually achieves this, then we should have a flexible way to spec the prob distribution for the 8-orientation, and then put in a sensible bias in that get_transform. Bias towards no-op actually make sense for many everyday object that "stands" up. 

So, we just may have stumble upon a good one here (a feature and not a bug). 

If you have easy access to Jeremy, would like to hear what he thinks.

**Comment by sgugger** [comment]
No it's definitely a mistake (I asked Jeremy and he confirmed). We already have some bias toward doing nothing with the probability of the transform (default is 0.75 IIRC, so 25% of the time it does nothing plus all the times we pick 0).

Here is [our tutorial](https://docs.fast.ai/dev/git.html#how-to-make-a-pull-request-pr) to make a PR. It's a good occasion for you to learn how to do this ;)

**Comment by kechan** [comment]
My branch is kechan:bug-uniform-int-dihedral, I have created a PR but it seemed still to be running checks. Please let me know if there's any issues, or anything else I need to do.

**Comment by sgugger** [comment]
It was good, thanks!

**Comment by kechan** [comment]
It would be interesting to see if this change will make results better or worse.

**Comment by stas00** [comment]
what a great opportunity to write a new fastai test to do just that, @kechan! and thank you!

**Comment by kechan** [comment]
Please post some pointers, I may come around and do this later. I will also post this on the fastai lesson forum, since a lot of them are simple recognition type tasks.

**Comment by stas00** [comment]
Well, I don't know what you need to know. We have all kinds of tips here: https://docs.fast.ai/dev/test.html
but, really, look at the existing tests and modify/add to create this new one that measures quality. Most likely it should go here: https://github.com/fastai/fastai/blob/master/tests/test_vision_transform.py
From the git checkout:
```
pytest -sv tests/test_vision_transform.py
```

**Comment by kechan** [comment]
Thanks. Yup, I don't know what I need for now (2nd degree ignorance). But what you post will get me started, hopefully efficiently.

This is the blight of working for a company for too long that used proprietary everything (incl. source control).

**Comment by kechan** [comment]
I am actually investigating, and possibility proposing adding a new transform thats not exactly available. I will take that chance to also write some test for this bug. 

I can see 2 kinds of test (the latter one unique to deep learning). 

1) traditional test that test for programmatic correctness. In this case, it can be as simple as checking if "8" is indeed never sampled. 

2) statistical test. i.e. a test for targeting the statistics ??

Since this is just a dead simple sampling (2) is not probably needed. I just thought it may actually be quite interesting if test accuracy for ML/DL tasks drop across the board after this fix. Then we may consider to do some research if this was indeed a feature fastai stumble upon and it's closer to the optimal value for generic scenarios.

**Comment by stas00** [comment]
I have just written this quick guide: https://docs.fast.ai/dev/test.html#quick-guide
Let me know if you encounter any issues following it.

---------------------

> I can see 2 kinds of test (the latter one unique to deep learning).
> 
>   1. traditional test that test for programmatic correctness. In this case, it can be as simple as checking if "8" is indeed never sampled.
> 
>   2.  statistical test. i.e. a test for targeting the statistics ??

while general unit tests (correctness) are always welcome, you suggested a quality test - which is very important, precisely because it can detect regressions. So yes, to statistical test. Just give it some tolerance that it it's not huge (pointless test), but not too tight either because it'll lead to failures often.

**Comment by kechan** [comment]
I am just re-running lesson 1 as IS, I haven't finished training the whole book yet. But my prelim observation is that after this PR, things look a little bit worse. This is just one run and one task, so it may not mean much. 

But I do have reasons to suspect this PR may actually regress things for default. Cat/Dog breeds photo may not have total rotational invariance. So giving all orientations almost equal prob may not be the optimal. I know that you already added in a probability to apply the tfm or not, such that no-op is still favored. 

It is early, but just want to give a head up we may need a better solution. The original mistake may actually end up to be a pretty good default. I just don't know how sensitive the err rate is dependent on dihedral aug.

**Comment by kechan** [comment]
Just missed one thing. The default actually does not invoke dihedral_affine(...) since flip_vert:bool=False, so my change should have no impact. If this is real perf hit, then it may be due to something else.
