### ISSUE TITLE
numpy upgrade

### ISSUE THREAD

**Issue by Benudek** [fastai/fastai#1652]
**Reproduce: make test**

_______________________ test_should_load_backwards_lm_1 ________________________

def test_should_load_backwards_lm_1():
    "assumes that a backwards batch starts where forward ends. Whether this holds depends on LanguageModelPreLoader"
    path = untar_data(URLs.IMDB_SAMPLE)

    df = text_df(['neg','pos'])
    data = TextLMDataBunch.from_df(path, train_df=df, valid_df=df, label_cols=0, text_cols=["text"],
                                   bs=2, backwards=False)
    batch_forward = data.one_batch(DatasetType.Valid)[0].numpy()

    data = TextLMDataBunch.from_df(path, train_df=df, valid_df=df, label_cols=0, text_cols=["text"],
                                   bs=2, backwards=True)
    batch_backwards = data.one_batch(DatasetType.Valid)[0].numpy()
  np.testing.assert_array_equal(batch_backwards, np.flip(batch_forward))
E TypeError: flip() missing 1 required positional argument: ‘axis’

tests/test_text_data.py:92: TypeError

**python -m fastai.utils.show_install**
```text
=== Software === 
python       : 3.6.6
fastai       : 1.0.46.dev0
fastprogress : 0.1.19
torch        : 1.0.0
torch cuda   : None / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Darwin-17.7.0-x86_64-i386-64bit
conda env    : base
python       : /Users/bherudek/miniconda3/bin/python
sys.path     : 
/Users/bherudek/miniconda3/lib/python36.zip
/Users/bherudek/miniconda3/lib/python3.6
/Users/bherudek/miniconda3/lib/python3.6/lib-dynload
/Users/bherudek/miniconda3/lib/python3.6/site-packages
/Users/bherudek/Desktop/fastaigits/fastai-doctestcheckclsstas
no supported gpus found on this system
```

**Resolution:**
pip install --upgrade numpy
--> unfortunately I could not find logs for the previous version

**Comment by stas00** [comment]
Thank you.

Can you please try to do bisecting and find out at which version it breaks?

You can easily find which versions are available using this trick:
```
$ pip install numpy==999999
  Could not find a version that satisfies the requirement numpy==999999 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0b3, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.11.1rc1, 1.11.1, 1.11.2rc1, 1.11.2, 1.11.3, 1.12.0b1, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.1rc1, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1)
No matching distribution found for numpy==999999
```
then skipping rc releases, and starting probably around 1.12 (no need to go before that).
```
pip install numpy==version_num_to_try
pytest tests/test_text_data.py::test_should_load_backwards_lm_1 
```
so within just a few runs of the above you will find the problematic version.

Thank you.

**Comment by Benudek** [comment]
pip install numpy==1.12.0b1

this already fails ;-)

**Comment by stas00** [comment]
Please re-read the previous comment. We need to know the first version where it doesn't fail. I asked you to find the last failing to make sure you actually find that transition. finding the first failing one does't help us.

Once we know the first good version we can then set in the dependencies file: `numpy>=first_good_version`

And if you skip steps and tell me that `1.16.0` works, that's not good. Because we need to know the lowest version number at which it starts working. If we set to the highest, then users won't be able to install other software that may rely on a lower numpy version. I hope you understand now why the very specific request.

**Comment by Benudek** [comment]
I suggest 1.15.0 - spacy indicated this dependency and I installed and tested - that version works.
And actually, exactly the previous version pip install numpy==1.14.6 does fail.

So there you go and have your min. dependency ;-)


pip install numpy==1.12.0

spacy 2.0.18 has requirement numpy>=1.15.0, but you'll have numpy 1.12.0 which is incompatible.
Installing collected packages: numpy
  Found existing installation: numpy 1.14.5
    Uninstalling numpy-1.14.5:
      Successfully uninstalled numpy-1.14.5
Successfully installed numpy-1.12.0

**Comment by stas00** [comment]
Fixed here: https://github.com/fastai/fastai/commit/31706b8cf48e81dab0b2eb12bc9b9ab29487c8b6
Thank you for this debug session, @Benudek.
