### ISSUE TITLE
Add rot90_affine and rot90 as new transforms

### ISSUE THREAD

**Issue by kechan** [fastai/fastai#1653]
Sorry if this is not appropriate for Issue. I have posted this on fastai forum for a while now but have no answer. I also looked at the docs.

Basically would like a data aug transform thats like np.rot90(...) A discrete rotation only transform resulting in 0, 90, 180, 270. 

I found a hack where you just use rotate(...) with a fixed degree and apply this multiple times for the diff orientation. This is quite bad as 

1) computationally wasteful
2) hard to spec the "p" to have resulting distribution to converge to uniform among 4-orientations. 

Motivation: 
I don't want to use dihedral for some images because the reflected version is not valid. This applies to text in quite a few languages. And even if it is harmless, it may still be wasteful since you are diluting the training set with unrealistic samples. You may have to use TTA to take advantage but that drag down the inference side.

**Comment by kechan** [comment]
If np.rot90(...) can be invoked by calling thats already in fastai, it will be great. But it isn't too hard to create a new one. So if you happen to need it, here's the simple addition you can use as well.

```
def _rot90_affine(k:partial(uniform_int, 0, 3)):
    "Randomly rotate `x` image based on `k` as in np.rot90"
    if k%2 == 0:
        x = -1. if k&2 else 1.
        y = -1. if k&2 else 1.
        
        return [[x, 0, 0.],
                [0, y, 0],
                [0, 0, 1.]]
    else:
        x = 1. if k&2 else -1.
        y = -1. if k&2 else 1.
        
        return [[0, x, 0.],
                [y, 0, 0],
                [0, 0, 1.]]

rot90_affine = TfmAffine(_rot90_affine)
tfms = [rot90_affine()]
get_ex().apply_tfms(tfms, size=224)
```

If this is indeed the best way, I will propose this in the fastai dev forum and see if this is common enough to be part of the library.

**Comment by sgugger** [comment]
This is the best way to implement this transform, yes. You can definitely suggest a PR with this, it can probably be useful to other people too.

**Comment by kechan** [comment]
Is this https://forums.fast.ai/c/fastai-users/fastai-dev the right forum to post this suggestion and hear feedback?

**Comment by kechan** [comment]
Posted on dev forum to solicitate feedback.

**Comment by sgugger** [comment]
I think you should go ahead and make a PR out of your transform. It may not be used very often, but the next person that needs it will be glad to see it here.

**Comment by kechan** [comment]
I have written a notebook on 

GitHub: https://github.com/kechan/FastaiPlayground under "Quick Tour of Data Augmentation.ipynb". It is currently reachable if you search "rot90 fastai". I didn't end with just rot90 and attempt to try to highlight how easy it is to add your own. 

So if this isn't high priority, we can close this and come back to it later.

**Comment by stas00** [comment]
Love it, @kechan! I find that you using a geometric image is a easier to appreciate the different transforms than an image of a cat. But that's just me. Thank you for sharing your nb.

**Comment by jph00** [comment]
I'll close this now since it's not something we're committing to doing ourselves - if someone wants to add a PR then we'll certainly look

**Comment by kechan** [comment]
@stas00 Thanks for appreciation. Cats are cute too and would be great for color transform. I would just do both to get a feel what transforms are doing. 

This is the motivation why i suggested adding an embedded image that's available with the library itself, rather than some external URLs. It allows for quick call up for test images. It can even be used for training if you use heavy data aug for classification of "R" and no "R". 

I posted this on dev forum for feedback. A nicely designed "F" will do, if you want a logo for fastai.

**Comment by stas00** [comment]
As I mentioned earlier, it should be easy to add an image file to the library, but not before it's actually needed. So usually we do well with actionable PRs: here is a PR that adds/extends/improves feature 'foo', and it requires/uses/prefers a built-in image 'bar' instead of fetching it from somewhere. And if it's a good idea then chances are it'll be accepted. 

I hope this makes sense. And, yes, let's continue this discussion over at the forums.

**Comment by kechan** [comment]
Sure, it is just a proposal, and not very high priority one. 

I just posted this on dev forum:

https://forums.fast.ai/t/adding-a-template-image-as-part-of-the-library/38927
