### ISSUE TITLE
Not installable on OSX with CUDA

### ISSUE THREAD

**Issue by phenomax** [fastai/fastai#1657]
**Describe the bug**
Because NVML is not supported on Mac OS (by Nvidia), the fastai lib cannot be installed with CUDA support.

**Provide your installation details**
```text
=== Software ===
python        : 3.7.2
fastai        : 1.0.45
fastprogress  : 0.1.19
torch         : 1.1.0a0+fbd690c
torch cuda    : 10.0 / is available
torch cudnn   : 7402 / is enabled

=== Hardware ===
torch devices : 1
  - gpu0      : GeForce GTX 1080 Ti

=== Environment ===
platform      : Darwin-17.0.0-x86_64-i386-64bit
conda env     : base
python        : /Users/phenomax/anaconda3/bin/python3
sys.path      : /Users/phenomax/projects/fastai
/Users/phenomax/anaconda3/lib/python37.zip
/Users/phenomax/anaconda3/lib/python3.7
/Users/phenomax/anaconda3/lib/python3.7/lib-dynload
/Users/phenomax/anaconda3/lib/python3.7/site-packages
/Users/phenomax/anaconda3/lib/python3.7/site-packages/aeosa
no nvidia-smi is found
```

**To Reproduce**

Compile Pytorch 1.1 from source with CUDA and try to execute the following code
```
from fastai.vision import *
from fastai.metrics import error_rate
```

**Output**

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/pynvml.py in _LoadNvmlLibrary()
    643                         # assume linux
--> 644                         nvmlLib = CDLL("libnvidia-ml.so.1")
    645                 except OSError as ose:

~/anaconda3/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    355         if handle is None:
--> 356             self._handle = _dlopen(self._name, mode)
    357         else:

OSError: dlopen(libnvidia-ml.so.1, 6): image not found

During handling of the above exception, another exception occurred:

NVMLError_LibraryNotFound                 Traceback (most recent call last)
<ipython-input-2-283c0d40bede> in <module>
----> 1 from fastai.vision import *
      2 from fastai.metrics import error_rate

~/anaconda3/lib/python3.7/site-packages/fastai/vision/__init__.py in <module>
----> 1 from .. import basics
      2 from ..basics import *
      3 from .learner import *
      4 from .data import *
      5 from .image import *

~/anaconda3/lib/python3.7/site-packages/fastai/basics.py in <module>
----> 1 from .basic_train import *
      2 from .callback import *
      3 from .core import *
      4 from .basic_data import *
      5 from .data_block import *

~/anaconda3/lib/python3.7/site-packages/fastai/basic_train.py in <module>
      4 from .callback import *
      5 from .data_block import *
----> 6 from .utils.mem import gpu_mem_restore
      7 
      8 __all__ = ['Learner', 'LearnerCallback', 'Recorder', 'RecordOnCPU', 'fit', 'loss_batch', 'train_epoch', 'validate',

~/anaconda3/lib/python3.7/site-packages/fastai/utils/mem.py in <module>
     14 have_cuda = 0
     15 if torch.cuda.is_available():
---> 16     pynvml.nvmlInit()
     17     have_cuda = 1
     18 

~/anaconda3/lib/python3.7/site-packages/pynvml.py in nvmlInit()
    606 ## C function wrappers ##
    607 def nvmlInit():
--> 608     _LoadNvmlLibrary()
    609 
    610     #

~/anaconda3/lib/python3.7/site-packages/pynvml.py in _LoadNvmlLibrary()
    644                         nvmlLib = CDLL("libnvidia-ml.so.1")
    645                 except OSError as ose:
--> 646                     _nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)
    647                 if (nvmlLib == None):
    648                     _nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)

~/anaconda3/lib/python3.7/site-packages/pynvml.py in _nvmlCheckReturn(ret)
    308 def _nvmlCheckReturn(ret):
    309     if (ret != NVML_SUCCESS):
--> 310         raise NVMLError(ret)
    311     return ret
    312 

NVMLError_LibraryNotFound: NVML Shared Library Not Found
```

**Expected behavior**
FastAI should not rely on Nvidia-smi. It should either be made optional, or it's feature implemented platform-agnostic.

**Comment by sgugger** [comment]
Hi there. First things first, MacOs isn't officially supported (I think it is clearly stated on the installation page) and it's not a priority to change that. With this being said, a PR that would try/except this import nicely would definitely be accepted.

**Comment by phenomax** [comment]
Thanks for your reply. When I was doing the Deep Learning 2018 course installing fastai with cuda from source was still possible.
<img width="699" alt="image" src="https://user-images.githubusercontent.com/12475496/52942037-6674ee80-336a-11e9-9026-7adcfb8aaba8.png">

Although official mac support is none of your priority, breaking it with newly added features shouldn't be the way to go. When I find time, I'll work on a friendly workaround/fix for mac os.

**Comment by stas00** [comment]
> **Expected behavior**
> FastAI should not rely on Nvidia-smi. It should either be made optional, or it's feature implemented platform-agnostic.

it's not relying on nvidia-smi.

Here is what's happening: fastai requires pytorch which requires nvidia library and therefore needs to be able to query the gpu. Since pytorch doesn't provide this functionality we have to use another approach. Currently, [python-nvml](https://pythonhosted.org/nvidia-ml-py) seems to be the best option. But as you're saying OSX is not supported.

I'm not an OSX user, so it's hard for me to tell where things are wrt nvidia on that platform. But a quick search resulted in: https://github.com/1132719438/pynvx, whose API seems to be very similar to nvml, so it should be easy to use that one on OSX - if you'd like to help to make the use of it on mac it'd be helpful. There are just a few API calls to pynvml in https://github.com/fastai/fastai/blob/master/fastai/utils/mem.py. So we would need some kind of a wrapper to use one library or the other.

So once that is supported we can just try/except that `pynvml.nvmlInit()` call and if on OSX ask the user to: `pip install pynvx` - we could tweak fastai pip dependencies to install it automatically, but since there is no conda package the dynamic check will still be needed.

I'd be happy to support you in this porting if you'd like to help make a proper nvidia querying work.

**Comment by stas00** [comment]
OK, please try the latest git and let me know whether it's a happy resolution. I added a little hack to have `pynvx` work as if it were `pynvml`.

```
is_osx = platform.system() == "Darwin"

# transparently monkey patch pynvx as pynvml API on OSX (for the few funcs we use)
if use_gpu and is_osx:
    try:
        import pynvx
    except:
        print("please install pynvx on OSX: pip install pynvx")
        sys.exit(1)

    # missing function
    def cudaDeviceGetHandleByIndex(id): return pynvx.cudaDeviceGetHandles()[id]
    setattr(pynvx, 'cudaDeviceGetHandleByIndex', cudaDeviceGetHandleByIndex)

    # different named and return value needs be a named tuple
    def cudaDeviceGetMemoryInfo(handle):
        info = pynvx.cudaGetMemInfo(handle)
        return GPUMemory(*info)
    setattr(pynvx, 'cudaDeviceGetMemoryInfo', cudaDeviceGetMemoryInfo)

    # remap the other functions
    for m in ['Init', 'DeviceGetCount', 'DeviceGetHandleByIndex', 'DeviceGetMemoryInfo']:
        setattr(pynvx, f'nvml{m}', getattr(pynvx, f'cuda{m}'))
    pynvml = pynvx

```

**Comment by phenomax** [comment]
Thanks for the quick resolution. Your monkey patch is working fine!
For convenience you may want to add `pynvx;platform_system=="Darwin"` to the `setup.py` core dependencies.

> it's not relying on nvidia-smi.

> Here is what's happening: fastai requires pytorch which requires nvidia library and therefore needs to be able to query the gpu. Since pytorch doesn't provide this functionality we have to use another approach.

Thanks for your explanation. I was missing the active usage of the `gpu_mem_restore` function, which led to cuda out of memory exceptions on my primal fix

**Comment by stas00** [comment]
> Thanks for the quick resolution. Your monkey patch is working fine!
> For convenience you may want to add `pynvx;platform_system=="Darwin"` to the `setup.py` core dependencies.

Done. Thank you for that and testing it.

If could please validate the auto-install is working after removing fastai/pynvx from your install and then installing just fastai and checking that pynvx gets in just right, that would be helpful.

Unfortunately, conda users will have to do it manually. or we could add it to the instructions if need be. And could also try to build a conda package, but it'll still need to be installed manually, since conda doesn't support run-time dependencies, only build time, and we would like to stick to `noarch` single release.

> Thanks for your explanation. I was missing the active usage of the `gpu_mem_restore` function, which led to cuda out of memory exceptions on my primal fix

Actually, `gpu_mem_restore` doesn't use/need gpu access. the nvml query functionality is used primarily for testing, memory profiling and already in fastai lessons where we try to help calibrate batch size and other hyperparameters based on available GPU RAM.

**Comment by phenomax** [comment]
> If could please validate the auto-install is working after removing fastai/pynvx from your install and then installing just fastai and checking that pynvx gets in just right, that would be helpful.

I did it and everything is working like a charm. I think we can call that done :)

> Actually, `gpu_mem_restore` doesn't use/need gpu access. the nvml query functionality is used primarily for testing, memory profiling and already in fastai lessons where we try to help calibrate batch size and other hyperparameters based on available GPU RAM.

Yeah, I was a bit hasty about the so called fix. The function had nothing to do with it at all. Nonetheless I am running into graphics memory leakage: without any processes active it fills up to 80%, but resets after I disconnect my monitors. Do you have any advice regarding that?

**Comment by stas00** [comment]
Thank you for testing, @phenomax.

>Nonetheless I am running into graphics memory leakage: without any processes active it fills up to 80%, but resets after I disconnect my monitors.

You mean physically disconnect a monitor? Some kinds of a bug in your OS?

In general have a look at this new work-in-progress tutorial for all things memory-reclaiming:
https://docs.fast.ai/tutorial.resources.html
and [ipyexperiments](https://github.com/stas00/ipyexperiments/) is very helpful at making it easy to watch real memory consumption.

Probably start a new thread at the forums, sharing as much as possible about your env, setup and sample code and someone will know what to recommend? I don't know anything about Mac.

**Comment by phenomax** [comment]
Thanks a lot, I'll try that!
