### ISSUE TITLE
Adding Gaussian Blur for data augmentation

### ISSUE THREAD

**Issue by kechan** [fastai/fastai#1661]
Gaussian blur doesn't seem popular. I also don't find this in Keras image processing out of the box. I have to set up my own and use PIL ImageFilter, and i found success in a project that I started out with Keras.

**Prototype** (this works but not sure its speed):

```
import PIL
from PIL import ImageFilter

def _gaussian_blur(x, radius:uniform):
    y = (x.numpy()*255.).astype(np.uint8).transpose((1, 2, 0))
    img = PIL.Image.fromarray(y)
    img = img.filter(ImageFilter.GaussianBlur(radius=radius))
    x = np.array(img).transpose((2, 0, 1))
    
    return torch.tensor(x/255., dtype=torch.float32)

gaussian_blur = TfmPixel(_gaussian_blur)
```
![screen shot 2019-02-18 at 2 16 00 am](https://user-images.githubusercontent.com/122762/52934048-5259ce80-3323-11e9-9bcb-b992bb790b94.png)

I assume the data aug will be performed with CPU (even in a GPU available env). Since PIL ImageFilter seemed to only work with numpy array and not torch tensor, I am not sure if this is the best way. Writing one from scratch of course has pros and cons. I want to reuse existing great image libraries as much as I can. Any idea if there are other options?

**Motivation**:
I read somewhere people said Gaussian blur is not a big deal, and thus its absence in Keras as well. But I found it a useful data augmentation esp. if your dataset comes from out of focus end user photos. This is even more frequent if you are making inferences continuously from a video stream. I find Gaussian Blur + Shear (is this in fastai??) is also a good approximation for motion blur. If you look at benchmark or Kaggle dataset, the photos are often in focus, so this is not going to be representative to the kind of distortion.

**Comment by sgugger** [comment]
We didn't implement gaussian blur but that doesn't mean we wouldn't like to have it in the fastai library. I understand it's a convolution with a random kernel so we have the tool in pytorch to do this directly on a tensor. Implementing new transforms isn't high priority on our side, but if you want to dig in and suggest a PR, it would be very welcome.

Shear mapping in general isn't implemented but we have all kinds of perspective warping available. The pipeline is already there to treat transforms that operates on coordinates, so I don't think it would be too hard to implement more versions of shear.

**Comment by kechan** [comment]
Understood. This is an area where ability to customize is more important since many of them are task dependent. There are posts where people have already written gaussian blur operating directly on torch tensor. It is matter of testing them and integrating into fastai. 

But before jumping in, i want to see how bad the above code is and decide if i can procrastinate on this. I would like to move on other things as well.

**Comment by jph00** [comment]
Transforms should be implemented with pytorch tensors, not numpy - see the fastai code for examples. Please use the forums to discuss. Thanks!

**Comment by kechan** [comment]
Understood well this has to be torch tensor. This is quick and dirty. But it brings up, all the goodies image transform done prior in numpy, May have to be re written....
