### ISSUE TITLE
I installed fastai 1.0.45 from pip and then when I try to use ConvLearner it throws an error that ConvLearner is not defined. Need some help please

### ISSUE THREAD

**Issue by shaunakjoshi12** [fastai/fastai#1662]
**Describe the bug**

**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tcapelle** [comment]
Conv learner is not defined in V1. To use convLearner use the 0.7 version of the library.

**Comment by sgugger** [comment]
Like he said ;)

**Comment by shaunakjoshi12** [comment]
ConvLearner is still in latest Lesson 1 then why isn't v1 updated for that!  Thank you very much by the way

**Comment by sgugger** [comment]
I'm guessing you aren't using the latest [lesson 1](https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson1-pets.ipynb).

**Comment by shaunakjoshi12** [comment]
Thank you! I think I am not even watching the latest lesson!
