### ISSUE TITLE
Imdb_scripts are out dated for version 1.0. Is there a plan to update them?

### ISSUE THREAD

**Issue by woshipzs** [fastai/fastai#1676]
Hi,

I am trying to mimic what fastai has achieved in imdb tutorial. However, those scripts are apparently out of date. I am wondering if there is an easy way to update them so that it's working under the new version of fastai.

Thanks,
Zeshan

**Comment by sgugger** [comment]
The updated version would be [here](https://github.com/n-waves/ulmfit-multilingual) I believe.
