### ISSUE TITLE
test_basic_train: test_export_load_learner & test_destroy fail

### ISSUE THREAD

**Issue by Benudek** [fastai/fastai#1683]
**python -m fastai.utils.show_install**

```text
=== Software === 
python       : 3.6.6
fastai       : 1.0.46.dev0
fastprogress : 0.1.19
torch        : 1.0.0
torch cuda   : None / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Darwin-17.7.0-x86_64-i386-64bit
conda env    : base
python       : /Users/bherudek/miniconda3/bin/python
sys.path     : 
/Users/bherudek/miniconda3/lib/python36.zip
/Users/bherudek/miniconda3/lib/python3.6
/Users/bherudek/miniconda3/lib/python3.6/lib-dynload
/Users/bherudek/miniconda3/lib/python3.6/site-packages
/Users/bherudek/Desktop/fastaigits/fastai-improvedoctest
no supported gpus found on this system
```

Please make sure to include opening/closing ``` when you paste into forums/github to make the reports appear formatted as code sections.

**To Reproduce**
make test

Result:

=================================== FAILURES ===================================
_________________________________ test_destroy _________________________________

    def test_destroy():
        msg = "this object has been destroyed"
        learn = fake_learner()
        with CaptureStdout() as cs: learn.destroy()
        assert "this Learner object self-destroyed" in cs.out
    
        # should be able to re-run learn.destroy multiple times for nb convenience
        with CaptureStdout() as cs: learn.destroy()
>       assert msg in cs.out
E       AssertionError: assert 'this object has been destroyed' in 'this Learner object self-destroyed - it still exists, but no longer usable\n'
E        +  where 'this Learner object self-destroyed - it still exists, but no longer usable\n' = stdout: this Learner object self-destroyed - it still exists, but no longer usable\n\n.out

tests/test_basic_train.py:139: AssertionError
___________________________ test_export_load_learner ___________________________

    def test_export_load_learner():
        export_file = 'export.pkl'
        for should_destroy in [False, True]:
            learn = fake_learner()
            path = learn.path
>           with CaptureStdout() as cs: learn.export(destroy=should_destroy)
E           TypeError: export() got an unexpected keyword argument 'destroy'

tests/test_basic_train.py:193: TypeError

**Comment by stas00** [comment]
this functionality was just added to git - are you using the dev install? Try again after 
`pip install -e "."dev]"`?

**Comment by Benudek** [comment]
aah sorry, think was my fault and indeed pip install -e ".[dev]" solved it. Next time I know, usually I run this scripts after downloading a new branch indeed -forgot this time
