### ISSUE TITLE
how to get rid of annoying lines on plot_confusion_matrix

### ISSUE THREAD

**Issue by CoderOverflow** [fastai/fastai#1693]
**Describe the bug**

There are many grid lines on the plot, When use plot_confusion_matrix to render the confusion_matrix.
how to get rid of the mesh on plot_confusion_matrix?
![](https://user-images.githubusercontent.com/29338660/53143919-1188e080-35d5-11e9-97ab-5844907d9309.png) 

We can see that some annoying lines on the plot.

![](https://user-images.githubusercontent.com/29338660/53144060-a095f880-35d5-11e9-800b-ff02e3606d84.png)
As a temporary method, I have to add plt.grid(False) to remove these lines. 

Is there any other way?

Anyone helps?

**Provide your installation details**

I install fastai1.0 on colab

```
!curl https://course.fast.ai/setup/colab | bash
```
```
from fastai import *
from fastai.vision import *
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
Confirmed it now works in colab as expected. Note that it's only on master for now, so you will need to run
```
!pip install git+https://github.com/fastai/fastai
```
if you want to see the fix. Thanks for flagging!
