### ISSUE TITLE
Running out of memory while creating databunch for a language model with wikipedia data

### ISSUE THREAD

**Issue by rubenaranamorera** [fastai/fastai#1703]
**Describe the bug**

When training a language model from scratch, I'm running out of memory while creating the databunch from extracted wikipedia files. I think it is a problem related with tokenization, as @matiu2 pointed out in https://github.com/fastai/fastai/issues/1224#issuecomment-441116061:

> I've seen a similar thing, but during the tokenization `process` phase. I got around it by tokenizing it myself, and not using numpy arrays; just using plain old python lists actually halved the memory usage.
> 
> After tokenizing, you can call 'TextDataBunch.from_tokens'.
> 
> Without that work around, the process grew up to 24 GB within about an hour of going through the full aclImdb.
> 
> I don't know how related this is.
> 
> @pvcastro you might try using a [python memory profiler](https://stackoverflow.com/questions/110259/which-python-memory-profiler-is-recommended) to find the source of the bad behaviour:

**Provide your installation details**
Using fastai 1.0.45 installed with conda on a p2.xlarge instance in AWS with "Deep Learning AMI (Amazon Linux) Version 21.2"

**To Reproduce**

You should download wikipedia data and extract it to "EXTRACTED_PATH"

````
databunch = (TextList.from_folder(EXTRACTED_PATH, recurse=True)
                 .random_split_by_pct(0.1)
                 .label_for_lm()
                 .databunch())
````
**Expected behavior**
A databunch is created

**Comment by sgugger** [comment]
Try to lower your number of CPUs. It's likely you get OOM because python copies the same things accross processes.

**Comment by sgugger** [comment]
Also, one thing I had to do for a wikipedia setting is to make sure I had deleted all the heavy objects used in pre-processing before making the call to the datablock API to avoid this.

**Comment by rubenaranamorera** [comment]
Finally I got it to work with less data. Instead of using files, I have created the databunch from a preprocessed csv with about 80% of the wiki texts in spanish.
