### ISSUE TITLE
how to specify path when we use the create_cnn method

### ISSUE THREAD

**Issue by CoderOverflow** [fastai/fastai#1711]
**Describe the bug**

Due to the dataset folder /input is read-only in **Kaggle notebook**,
how to specify a path when we use the create_cnn method to save temporary files without more linux's 
operations？

**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
Please refer to the [doc on Learner](https://docs.fast.ai/basic_train.html#Learner). What you are looking for is `model_dir`. Pass a Path object pointing to the directory you want.
