### ISSUE TITLE
How to use model_summary

### ISSUE THREAD

**Issue by gkourogiorgas** [fastai/fastai#1714]
Hi. I am trying to figure out how to use model_summary
```
dep_var = 'closefwd'
valid_idx = range(len(X_train)-2000, len(X_train))
procs = [Normalize]
data = TabularDataBunch.from_df(path, X_train, dep_var, valid_idx=valid_idx,procs=procs, bs=1000)
learn = tabular_learner(data, layers=[200,100,75,50,25], metrics=mean_absolute_error )
learn.fit(50, 3.31E-02)
```
I am running this code successfully but then I try to run:
`learn.model_summary`
but doesn't work. It says:
`'Learner' object has no attribute 'model_summary'`

**Comment by sgugger** [comment]
Where did you find a `model_summary` method for `Learner`? You can use `model_summary(learn)` or `learn.summary()`, see the docs.
PS: you will want to do `print(learn.summary())` to have a clean output :)

**Comment by gkourogiorgas** [comment]
I added these lines:
from fastai.callbacks import hooks
hooks.model_summary(learn)
and I also ran this separately
learn.summary()
and I got this error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-38-93c8a11c9ccf> in <module>
      1 from fastai.callbacks import hooks
      2 #hooks.model_summary(learn)
----> 3 learn.summary()

~/anaconda3/lib/python3.6/site-packages/fastai/callbacks/hooks.py in model_summary(m, n)
    165 def model_summary(m:Learner, n:int=70):
    166     "Print a summary of `m` using a output text width of `n` chars"
--> 167     info = layers_info(m)
    168     header = ["Layer (type)", "Output Shape", "Param #", "Trainable"]
    169     res = "=" * n + "\n"

~/anaconda3/lib/python3.6/site-packages/fastai/callbacks/hooks.py in layers_info(m)
    156     func = lambda m:list(map(get_layer_name, flatten_model(m)))
    157     layers_names = func(m.model) if isinstance(m, Learner) else func(m)
--> 158     layers_sizes, layers_params, layers_trainable, hooks = params_size(m)
    159     for h1,h2 in hooks:
    160         h1.remove()

~/anaconda3/lib/python3.6/site-packages/fastai/callbacks/hooks.py in params_size(m, size)
    145     hooks = zip(hooks_outputs, hooks_params)
    146     x = m.eval()(*x) if is_listy(x) else m.eval()(x)
--> 147     output_size = [(o.stored.shape) for o in hooks_outputs]
    148     params = [o.stored for o in hooks_params]
    149     params, trainables = map(list,zip(*params))

~/anaconda3/lib/python3.6/site-packages/fastai/callbacks/hooks.py in <listcomp>(.0)
    145     hooks = zip(hooks_outputs, hooks_params)
    146     x = m.eval()(*x) if is_listy(x) else m.eval()(x)
--> 147     output_size = [(o.stored.shape) for o in hooks_outputs]
    148     params = [o.stored for o in hooks_params]
    149     params, trainables = map(list,zip(*params))

AttributeError: 'NoneType' object has no attribute 'shape'
