### ISSUE TITLE
Error using SqueezeNet model in unet_learner

### ISSUE THREAD

**Issue by dejanmilivojevic** [fastai/fastai#1724]
I'm trying to use squeezenet as my unet model like this

learn = unet_learner(data, models.SqueezeNet, metrics=metrics, wd=wd, bottle=True)

and I get this error:

/usr/local/lib/python3.6/dist-packages/torchvision/models/squeezenet.py:94: UserWarning: nn.init.kaiming_uniform is now deprecated in favor of nn.init.kaiming_uniform_.
  init.kaiming_uniform(m.weight.data)
/usr/local/lib/python3.6/dist-packages/torchvision/models/squeezenet.py:92: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, mean=0.0, std=0.01)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-15-8c792c9288ff> in <module>()
----> 1 learn = unet_learner(data, models.SqueezeNet, metrics=metrics, wd=wd, bottle=True)

/usr/local/lib/python3.6/dist-packages/fastai/vision/learner.py in unet_learner(data, arch, pretrained, blur_final, norm_type, split_on, blur, self_attention, y_range, last_cross, bottle, cut, **learn_kwargs)
     90     model = to_device(models.unet.DynamicUnet(body, n_classes=data.c, blur=blur, blur_final=blur_final,
     91           self_attention=self_attention, y_range=y_range, norm_type=norm_type, last_cross=last_cross,
---> 92           bottle=bottle), data.device)
     93     learn = Learner(data, model, **learn_kwargs)
     94     learn.split(ifnone(split_on, meta['split']))

/usr/local/lib/python3.6/dist-packages/fastai/vision/models/unet.py in __init__(self, encoder, n_classes, blur, blur_final, self_attention, y_range, last_cross, bottle, **kwargs)
     43         imsize = (256,256)
     44         sfs_szs = model_sizes(encoder, size=imsize)
---> 45         sfs_idxs = list(reversed(_get_sfs_idxs(sfs_szs)))
     46         self.sfs = hook_outputs([encoder[i] for i in sfs_idxs])
     47         x = dummy_eval(encoder, imsize).detach()

/usr/local/lib/python3.6/dist-packages/fastai/vision/models/unet.py in _get_sfs_idxs(sizes)
      9     feature_szs = [size[-1] for size in sizes]
     10     sfs_idxs = list(np.where(np.array(feature_szs[:-1]) != np.array(feature_szs[1:]))[0])
---> 11     if feature_szs[0] != feature_szs[1]: sfs_idxs = [0] + sfs_idxs
     12     return sfs_idxs
     13 

IndexError: list index out of range

**Comment by sgugger** [comment]
Yes, `unet_learner` is completely untested on something else than resnet bases, as it has been designed for that. You will need to tweak the code yourself for new models to work with it. Closing this issue, I suggest you create a new thread on the [forum](https://forums.fast.ai/) if you need help making those changes.
