### ISSUE TITLE
About learn.export()

### ISSUE THREAD

**Issue by CoderOverflow** [fastai/fastai#1727]
When I run learn.export() 
error happens, due to the input folder is read-only in kaggle notebook
Following the [lesson3](https://www.kaggle.com/hortonhearsafoo/fast-ai-v3-lesson-3-planet), I've set the model path by using model_dir in create_cnn().
Is there anything else need to be add?

![8 uga_uz2ddv j n h5 0](https://user-images.githubusercontent.com/29338660/53544402-dbada400-3b60-11e9-93f3-375fa8e893bf.png)

**Describe the bug**

**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by CoderOverflow** [comment]
can use fname parameter to set the filename with full path

**Comment by stas00** [comment]
Perhaps, propose a PR that adjusts `export` to check whether the folder is writable, and if it's not to suggest to a user to use the `fname` argument instead? Thanks.
