### ISSUE TITLE
AWD_LSTM not defined

### ISSUE THREAD

**Issue by akanshajainn** [fastai/fastai#1731]
In fastai/examples/text.ipynb:

It is mentioned that we can download the english language model for fine tuning but no link is provided for the same. Also, it is directly mentioned to use AWD_LSTM, what is it exactly? Path to model? name of the model? What is it?

**Comment by sgugger** [comment]
Hi there! Please use the [forum](https://forums.fast.ai/) for question around the library as we prefer to keep issues for bugs only.
The model is going to be downloaded automatically when you execute the instruction, like torchvision does. As for AWD_LSTM, it's an architecture so a class of nn.Module.

**Comment by akanshajainn** [comment]
Okay so I figured out, there is typo in that notebook,
"AWD_LSTM" must be given in quotes otherwise we'll get keyerror: AWD_LSTM is not defined.

**Comment by sgugger** [comment]
I'm not sure you have the latest version of fastai if AWD_LSTM doesn't work. It's not supposed to work with quotes.
