### ISSUE TITLE
learn.purge in 1.0.45

### ISSUE THREAD

**Issue by CoderOverflow** [fastai/fastai#1734]
Following [lesson3](https://www.kaggle.com/hortonhearsafoo/fast-ai-v3-lesson-3-planet)
**Describe the bug**

The error happens after run the learn.export and calling other learn object
[my notebook](https://www.kaggle.com/liuyd2018/planet-multi-label-image-classification)
<img width="863" alt="2019-03-02 6 18 26" src="https://user-images.githubusercontent.com/29338660/53680505-ae572680-3d17-11e9-8b18-aaefa0b02877.png">

> 
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-35-b24efc6644a6> in <module>()
>       1 learn = load_learner('/kaggle/working/', test=test)
> ----> 2 preds, _ = learn.get_preds(ds_type=DatasetType.Test)
> 
> /opt/conda/lib/python3.6/site-packages/fastai/basic_train.py in get_preds(self, ds_type, with_loss, n_batch, pbar)
>     276         lf = self.loss_func if with_loss else None
>     277         return get_preds(self.model, self.dl(ds_type), cb_handler=CallbackHandler(self.callbacks),
> --> 278                          activ=_loss_func2activ(self.loss_func), loss_func=lf, n_batch=n_batch, pbar=pbar)
>     279 
>     280     def pred_batch(self, ds_type:DatasetType=DatasetType.Valid, batch:Tuple=None, reconstruct:bool=False) -> List[Tensor]:
> 
> /opt/conda/lib/python3.6/site-packages/fastai/basic_train.py in get_preds(model, dl, pbar, cb_handler, activ, loss_func, n_batch)
>      38     "Tuple of predictions and targets, and optional losses (if `loss_func`) using `dl`, max batches `n_batch`."
>      39     res = [torch.cat(o).cpu() for o in
> ---> 40            zip(*validate(model, dl, cb_handler=cb_handler, pbar=pbar, average=False, n_batch=n_batch))]
>      41     if loss_func is not None: res.append(calc_loss(res[0], res[1], loss_func))
>      42     if activ is not None: res[0] = activ(res[0])
> 
> /opt/conda/lib/python3.6/site-packages/fastai/basic_train.py in validate(model, dl, loss_func, cb_handler, pbar, average, n_batch)
>      50         val_losses,nums = [],[]
>      51         if cb_handler: cb_handler.set_dl(dl)
> ---> 52         for xb,yb in progress_bar(dl, parent=pbar, leave=(pbar is not None)):
>      53             if cb_handler: xb, yb = cb_handler.on_batch_begin(xb, yb, train=False)
>      54             val_losses.append(loss_batch(model, xb, yb, loss_func, cb_handler=cb_handler))
> 
> /opt/conda/lib/python3.6/site-packages/fastprogress/fastprogress.py in __iter__(self)
>      64         self.update(0)
>      65         try:
> ---> 66             for i,o in enumerate(self._gen):
>      67                 yield o
>      68                 if self.auto_update: self.update(i+1)
> 
> /opt/conda/lib/python3.6/site-packages/fastai/basic_data.py in __iter__(self)
>      73     def __iter__(self):
>      74         "Process and returns items from `DataLoader`."
> ---> 75         for b in self.dl: yield self.proc_batch(b)
>      76 
>      77     @classmethod
> 
> /opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
>     629         while True:
>     630             assert (not self.shutdown and self.batches_outstanding > 0)
> --> 631             idx, batch = self._get_batch()
>     632             self.batches_outstanding -= 1
>     633             if idx != self.rcvd_idx:
> 
> /opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _get_batch(self)
>     608             # need to call `.task_done()` because we don't use `.join()`.
>     609         else:
> --> 610             return self.data_queue.get()
>     611 
>     612     def __next__(self):
> 
> /opt/conda/lib/python3.6/multiprocessing/queues.py in get(self, block, timeout)
>      92         if block and timeout is None:
>      93             with self._rlock:
> ---> 94                 res = self._recv_bytes()
>      95             self._sem.release()
>      96         else:
> 
> /opt/conda/lib/python3.6/multiprocessing/connection.py in recv_bytes(self, maxlength)
>     214         if maxlength is not None and maxlength < 0:
>     215             raise ValueError("negative maxlength")
> --> 216         buf = self._recv_bytes(maxlength)
>     217         if buf is None:
>     218             self._bad_message_length()
> 
> /opt/conda/lib/python3.6/multiprocessing/connection.py in _recv_bytes(self, maxsize)
>     405 
>     406     def _recv_bytes(self, maxsize=None):
> --> 407         buf = self._recv(4)
>     408         size, = struct.unpack("!i", buf.getvalue())
>     409         if maxsize is not None and size > maxsize:
> 
> /opt/conda/lib/python3.6/multiprocessing/connection.py in _recv(self, size, read)
>     377         remaining = size
>     378         while remaining > 0:
> --> 379             chunk = read(handle, remaining)
>     380             n = len(chunk)
>     381             if n == 0:
> 
> /opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py in handler(signum, frame)
>     272         # This following call uses `waitid` with WNOHANG from C side. Therefore,
>     273         # Python can still get and update the process status successfully.
> --> 274         _error_if_any_worker_fails()
>     275         if previous_handler is not None:
>     276             previous_handler(signum, frame)
> 
> RuntimeError: DataLoader worker (pid 63) is killed by signal: Bus error. 
> 
> 

## So I try to add the learn.purge in 1.0.45

Error happens
<img width="763" alt="2019-03-02 5 58 27" src="https://user-images.githubusercontent.com/29338660/53680366-72bb5d00-3d15-11e9-8a6a-da4b89c15fc7.png">

🔴 Error:  Read-only file system
How to del the learn object in kaggle notebook in the  fastai version 1.0.45

I alse tried 
del learn
gc.collect()
It still cannot run correctly.
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-35-b24efc6644a6> in <module>()
      1 learn = load_learner('/kaggle/working/', test=test)
----> 2 preds, _ = learn.get_preds(ds_type=DatasetType.Test)

/opt/conda/lib/python3.6/site-packages/fastai/basic_train.py in get_preds(self, ds_type, with_loss, n_batch, pbar)
    276         lf = self.loss_func if with_loss else None
    277         return get_preds(self.model, self.dl(ds_type), cb_handler=CallbackHandler(self.callbacks),
--> 278                          activ=_loss_func2activ(self.loss_func), loss_func=lf, n_batch=n_batch, pbar=pbar)
    279 
    280     def pred_batch(self, ds_type:DatasetType=DatasetType.Valid, batch:Tuple=None, reconstruct:bool=False) -> List[Tensor]:

/opt/conda/lib/python3.6/site-packages/fastai/basic_train.py in get_preds(model, dl, pbar, cb_handler, activ, loss_func, n_batch)
     38     "Tuple of predictions and targets, and optional losses (if `loss_func`) using `dl`, max batches `n_batch`."
     39     res = [torch.cat(o).cpu() for o in
---> 40            zip(*validate(model, dl, cb_handler=cb_handler, pbar=pbar, average=False, n_batch=n_batch))]
     41     if loss_func is not None: res.append(calc_loss(res[0], res[1], loss_func))
     42     if activ is not None: res[0] = activ(res[0])

/opt/conda/lib/python3.6/site-packages/fastai/basic_train.py in validate(model, dl, loss_func, cb_handler, pbar, average, n_batch)
     50         val_losses,nums = [],[]
     51         if cb_handler: cb_handler.set_dl(dl)
---> 52         for xb,yb in progress_bar(dl, parent=pbar, leave=(pbar is not None)):
     53             if cb_handler: xb, yb = cb_handler.on_batch_begin(xb, yb, train=False)
     54             val_losses.append(loss_batch(model, xb, yb, loss_func, cb_handler=cb_handler))

/opt/conda/lib/python3.6/site-packages/fastprogress/fastprogress.py in __iter__(self)
     64         self.update(0)
     65         try:
---> 66             for i,o in enumerate(self._gen):
     67                 yield o
     68                 if self.auto_update: self.update(i+1)

/opt/conda/lib/python3.6/site-packages/fastai/basic_data.py in __iter__(self)
     73     def __iter__(self):
     74         "Process and returns items from `DataLoader`."
---> 75         for b in self.dl: yield self.proc_batch(b)
     76 
     77     @classmethod

/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    629         while True:
    630             assert (not self.shutdown and self.batches_outstanding > 0)
--> 631             idx, batch = self._get_batch()
    632             self.batches_outstanding -= 1
    633             if idx != self.rcvd_idx:

/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _get_batch(self)
    608             # need to call `.task_done()` because we don't use `.join()`.
    609         else:
--> 610             return self.data_queue.get()
    611 
    612     def __next__(self):

/opt/conda/lib/python3.6/multiprocessing/queues.py in get(self, block, timeout)
     92         if block and timeout is None:
     93             with self._rlock:
---> 94                 res = self._recv_bytes()
     95             self._sem.release()
     96         else:

/opt/conda/lib/python3.6/multiprocessing/connection.py in recv_bytes(self, maxlength)
    214         if maxlength is not None and maxlength < 0:
    215             raise ValueError("negative maxlength")
--> 216         buf = self._recv_bytes(maxlength)
    217         if buf is None:
    218             self._bad_message_length()

/opt/conda/lib/python3.6/multiprocessing/connection.py in _recv_bytes(self, maxsize)
    405 
    406     def _recv_bytes(self, maxsize=None):
--> 407         buf = self._recv(4)
    408         size, = struct.unpack("!i", buf.getvalue())
    409         if maxsize is not None and size > maxsize:

/opt/conda/lib/python3.6/multiprocessing/connection.py in _recv(self, size, read)
    377         remaining = size
    378         while remaining > 0:
--> 379             chunk = read(handle, remaining)
    380             n = len(chunk)
    381             if n == 0:

/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py in handler(signum, frame)
    272         # This following call uses `waitid` with WNOHANG from C side. Therefore,
    273         # Python can still get and update the process status successfully.
--> 274         _error_if_any_worker_fails()
    275         if previous_handler is not None:
    276             previous_handler(signum, frame)

RuntimeError: DataLoader worker (pid 63) is killed by signal: Bus error.
```

🔴 error:DataLoader worker (pid 63) is killed by signal: Bus error.

**Provide your installation details**

kaggle notebook
learn.purge in 1.0.45
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by stas00** [comment]
This has now been fixed in master, by adding a new purge arg: `tmppath`, please see the updated doc
https://docs.fast.ai/basic_train.html#Learner.purge

**Comment by stas00** [comment]
Apologies, there was a better solution to this issue - therefore, `tmppath` had a very short life and is now gone.

Instead set the model_dir attribute in Learner to a full libpath path that is writable (by setting learn.model_dir or passing model_dir argument in the Learner constructor).

As described in the now updated document: https://docs.fast.ai/basic_train.html#Learner.purge

Please use: `pip install git+https://github.com/fastai/fastai` to get the latest git and verify that the solution works for you, @CoderOverflow.

**Comment by CoderOverflow** [comment]
I have set the model_dir in learn.create_cnn but it seems doesn't work.
Shows as [my notebook ver5](https://www.kaggle.com/liuyd2018/planet-multi-label-image-classification?scriptVersionId=11066484)

Lastest Kaggle notebook runs with version 1.0.45

@stas00

**Comment by stas00** [comment]
> **Please use: pip install git+https://github.com/fastai/fastai to get the latest git and verify that the solution works for you, @CoderOverflow.**

**Comment by CoderOverflow** [comment]
I get the latest version of 1.0.47 dev
I use learn.export(fname='/kaggle/working/export.pkl',destroy=True) to instead of learn.purge, but still returns an error:
DataLoader worker (pid 94) is killed by signal: Bus error.

[my notebook ver11](https://www.kaggle.com/liuyd2018/planet-multi-label-image-classification?scriptVersionId=11100303)
@stas00 

I decided to use learn2 as a new learn object and see what happens.

**Comment by stas00** [comment]
I'm having a difficult time with this (mis-)communication. You opened a ticket with a problem in `purge`. I added a fix and requested that you validate it, and now 2 replies in a row, you're not validating the fix, but talking about other things. I'm not sure how to proceed.

Let's focus in this thread on `purge` and if there are sill problems with it, please re-open the ticket and we will continue solving it.

For other issues please open new tickets and we will sort them out.

Thank you.

**Comment by CoderOverflow** [comment]
Thanks.
I will open a new issue since I can use the latest version 1.0.47 in my kaggle notebook.
