### ISSUE TITLE
fastai v1: Suggestion: Follow semantic versioning

### ISSUE THREAD

**Issue by parthopdas** [fastai/fastai#1739]
**Describe the bug**
At times fasta1 v1 library undergoes significant refactoring. E.g. Image*List related refactoring.

This is a great thing as we tend towards a more intuitive API based on experience and user feedback. 
On the flip side, given that we recommend users to pull down the latest versions, such refactorings cause existing code to break unceremoniously.

Recommendation here is to follow a mid-path - where the version number indicates to the user the effort required, should they choose to upgrade.

[Semantic versioning](https://semver.org/) enables this.

In short:
1. Major version is updated in case of breaking changes
2. Minor version is updated when new features are added in a back-compat manner
3. Patch version is updated when bug fixes are made in a back-compat manner.

Note that I am not recommending that we be purists w.r.t. semantic versioning - adhering to it most of time times IMHO is enough. i.e. there may be times where the occasional breaking change slip through the same major version.

**Provide your installation details**

None

**To Reproduce**

**Expected behavior**

None

**Screenshots**

None

**Additional context**

None

**Comment by sgugger** [comment]
This can be discussed more on the forum, but basically we don't follow semantic versioning for now. The API is only stabilizing and we may change when we release a stable v1.1, but we're not there yet ;)

**Comment by parthopdas** [comment]
@sgugger should we at least keep this issue open.

Few reasons:
- We walk through prod deployment scenarios in the lessons, meaning we can 'go live' with v1
- It's certainly a pain to upgrade the library and find things broken, rather badly.
- My understanding is that we start this semver with v1 release in general 

Also do you recommend I initiate a forum thread asking for opinions?

**Comment by sgugger** [comment]
We keep the GitHub issues for standing bugs only, but the discussion can completely continue on the forum. Feel completely free to open a thread on this!

**Comment by stas00** [comment]
@parthopdas, it looks like someone started a similar thread in the forums already:
https://forums.fast.ai/t/v1-api-changes-too-drastic/31903/4
So perhaps proceed there - I will share my thoughts as well.
