### ISSUE TITLE
about DataLoader worker 

### ISSUE THREAD

**Issue by CoderOverflow** [fastai/fastai#1741]
**Describe the bug**

```
learn.export(fname='/kaggle/working/export.pkl',destroy=True)
test = ImageList.from_folder(path/'test-jpg-v2')
learn_test = load_learner('/kaggle/working/', test=test)
preds, _ = learn_test.get_preds(ds_type=DatasetType.Test)

```

RuntimeError: DataLoader worker (pid 94) is killed by signal: Bus error. 

I guess this is about multi-processing.
Is the num_workers value not in the export.pkl file?
How to set num_worker in this case?

or Is there any global  variable to switch off the multi-processing to use in the special environment like kaggle?

[my notebook v12](https://www.kaggle.com/liuyd2018/planet-multi-label-image-classification?scriptVersionId=11112362)
[tutorial.inference](https://docs.fast.ai/tutorial.inference.html)
[tutorial.inference notebook](https://github.com/fastai/fastai/blob/0765c828a94603340e0ad269eed0ecd4e46f7ea5/docs_src/tutorial.inference.ipynb)
**Provide your installation details**

kaggle notebook
```
!pip install git+https://github.com/fastai/fastai 
```
1.0.47 dev

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
I don't think there is an option to remove multiprocessing in `load_learner` yet. Will look today.

**Comment by maykulkarni** [comment]
I had a similar error in `ImageDataBunch` which I fixed by passing `num_workers=0`

**Comment by CoderOverflow** [comment]
@maykulkarni 
In the training phase, I also set num_workers=0. It's ok.
But, In the deploy phase, I don't know how to set this value when the error happens again.

**Comment by sgugger** [comment]
Ok, you can know pass `db_kwargs` in that method that will be passed to the call to `databunch` internally. This way you can set `num_workers` to 0, or specify a `bs` for your test set.

**Comment by CoderOverflow** [comment]
It's great. Thanks. @sgugger  It works in my [kernel ver13]
(https://www.kaggle.com/liuyd2018/planet-multi-label-image-classification?scriptVersionId=11164873)
I set bs=1 for prediction and got 0.93 score ranking top 11% ^^
