### ISSUE TITLE
retrain with more classes

### ISSUE THREAD

**Issue by bsback** [fastai/fastai#1742]
Hi! I am following lesson 1 and managed to train a model with 23 classes, later i added 3 more classes, 
when i try to load model with `learn.load('stage-1');`
i get this error
`Error(s) in loading state_dict for Sequential:
	size mismatch for 1.8.weight: copying a param with shape torch.Size([23, 512]) from checkpoint, the shape in current model is torch.Size([26, 512]).
	size mismatch for 1.8.bias: copying a param with shape torch.Size([23]) from checkpoint, the shape in current model is torch.Size([26]).
`
how can i fix this?

**Comment by sgugger** [comment]
You can't without creating a new model and digging into the weight dictionary to copy what you can. You should retrain your model with the new classes, with transfer learning it's pretty fast in any case.

**Comment by bsback** [comment]
thanks, to copy the weight dictionary, which fastai api should i use?  i'm using resnet34 model.

**Comment by sgugger** [comment]
There is no fastai API for that, you have to do it in plain PyTorch.
