### ISSUE TITLE
Custom create func for test set not working for 1.39<v

### ISSUE THREAD

**Issue by jaideep11061982** [fastai/fastai#1745]
**Describe the bug**

below peace of code works for 1.39 but for version above dsnt works. It still tries to open using default get->open function and hence fails because open channel func appends color name to file name to access the file in directory.
```
src1.test.x.create_func = open_4_channel2
src1.test.x.open = open_4_channel2

src1.add_test(test_fnames, label='0');

trn_tfms,_ = get_transforms(do_flip=True, flip_vert=True, max_rotate=30., max_zoom=1.08,
                      max_lighting=0.15, max_warp=0. )

data1 = (src1.transform((trn_tfms,trn_tfms), size=224,resize_method=ResizeMethod.SQUISH)
        .databunch(bs=64).normalize(protein_stats))
```
**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
Yes, you should subclass `ImageList` with your custom open function from now on.
