### ISSUE TITLE
Problems with TextClassificationInterpretation

### ISSUE THREAD

**Issue by aftertouch** [fastai/fastai#1757]
**Describe the bug**
TextClassificationInterpretation definitely does not work with models converted to half-precision. Additionally, it does not seem to work either when the learner is loaded and kept in full precision.

Half precision throws the error: "RuntimeError: expected scalar type Half but found Float"

Full precision throws the error: "RuntimeError: cudnn RNN backward can only be called in training mode"

**Provide your installation details**
```text
=== Software === 
python        : 3.7.2
fastai        : 1.0.46
fastprogress  : 0.1.19
torch         : 1.0.0
nvidia driver : 410.78
torch cuda    : 10.0.130 / is available
torch cudnn   : 7401 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 7951MB | GeForce RTX 2070

=== Environment === 
platform      : Linux-4.15.0-45-generic-x86_64-with-debian-buster-sid
distro        : #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019
conda env     : fastai-usr
python        : /home/jmill/anaconda3/envs/fastai-usr/bin/python
sys.path      : /home/jmill/projects/project/nb
/home/jmill/anaconda3/envs/fastai-usr/lib/python37.zip
/home/jmill/anaconda3/envs/fastai-usr/lib/python3.7
/home/jmill/anaconda3/envs/fastai-usr/lib/python3.7/lib-dynload

/home/jmill/anaconda3/envs/fastai-usr/lib/python3.7/site-packages
/home/jmill/anaconda3/envs/fastai-usr/lib/python3.7/site-packages/IPython/extensions
/home/jmill/.ipython
../
```

**To Reproduce**
Train a create a text classifier learner with AWD_LSTM, call to_fp16(). Train and save. Load learner, create a TextClassificationInterpretation object using from_learner(), call to_fp16(), then attempt to call show_intrinsic_attention().

To reproduce other error, load same learner but do not call to_fp16()

**Comment by sgugger** [comment]
I'm not sure it will work in FP16, the bug in FP32 is known and hopefully a fix will arrive soon.
