### ISSUE TITLE
about batch size in deploy phase of Image classification task 

### ISSUE THREAD

**Issue by CoderOverflow** [fastai/fastai#1758]
about batchsize with test dataset in deploy phase

there are some methods to predict in deploy phase
such as 
learn.predict
learn.get_preds
learn.TTA(test=True)

I am wondering if i use the data object which have the test parameter and is initialized in the training phase, will test_dataset set its bs into 1 by default in deploy phase when I call the predict methods or I have to create a new data object for prediction only and set the bs=1?
```
data = ImageDataBunch.from_csv(
                      path_input,
                      folder='train',
                      valid_pct=0.2,
                      ds_tfms=get_transforms(flip_vert=True,max_rotate=20., max_zoom=1.1),
                      size=224,
                 ->   test='/kaggle/input/test/test',
                      suffix='.jpg',
                      bs=64,
                      num_workers=0).normalize(imagenet_stats)
```

As [dogbreeds my kenerl ver9](https://www.kaggle.com/liuyd2018/120-dogbreeds-fast-ai-v1-0-x?scriptVersionId=10882715) using 
```
test_result = learner.get_preds(ds_type=DatasetType.Test)
```
 only get  score: 0.48214, I am looking for the reason.

**Describe the bug**

**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
The batch size isn't 1 by default, it's the same as the training set. You have to create a new `DataBunch` object for tests to change it.

**Comment by CoderOverflow** [comment]
Thank you

**Comment by santialferez** [comment]
Can it also be changed like this?
`learner.data.batch_size = 4`

Without creating a new `DataBunch`

**Comment by sgugger** [comment]
Probably yes.
