### ISSUE TITLE
CategoryList is not debuggable or printable in ipdb?

### ISSUE THREAD

**Issue by kechan** [fastai/fastai#1760]
CategoryList is not "debuggable" during a set_trace() and ipdb

**Provide your installation details**
```text
=== Software === 
python       : 3.7.1
fastai       : 1.0.45
fastprogress : 0.1.19
torch        : 1.0.1.post2
torch cuda   : None / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Darwin-17.7.0-x86_64-i386-64bit
conda env    : Unknown
python       : /Users/kelvinchan/tmp/python3_env/deeplearning/bin/python3
sys.path     : 
/Users/kelvinchan/Documents/LearnFastai/FastaiPlayground
/Users/kelvinchan/tmp/python3_env/deeplearning/lib/python37.zip
/Users/kelvinchan/tmp/python3_env/deeplearning/lib/python3.7
/Users/kelvinchan/tmp/python3_env/deeplearning/lib/python3.7/lib-dynload
/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7
/Users/kelvinchan/tmp/python3_env/deeplearning/lib/python3.7/site-packages
/Users/kelvinchan/tmp/python3_env/deeplearning/lib/python3.7/site-packages/IPython/extensions
/Users/kelvinchan/.ipython
no supported gpus found on this system
```

**To Reproduce**
1) Put set_trace() at fastai/data_block.py 
```
class ItemList():
     ...
      def label_from_list(self, labels:Iterator, label_cls:Callable=None, **kwargs)->'LabelList':
        "Label `self.items` with `labels`."
        labels = array(labels, dtype=object)
        label_cls = self.get_label_cls(labels, label_cls=label_cls, **kwargs)
        y = label_cls(labels, path=self.path, **kwargs)
        set_trace()
        res = self._label_list(x=self, y=y)
        return res
```

2) when it breaks at "res = self._label_list(x=self, y=y)", 

> (Pdb) y
> *** TypeError: 'NoneType' object is not subscriptable
> (Pdb) y is None
> False
> (Pdb) type(y)
> <class 'fastai.data_block.CategoryList'>

3) we should be able to debug CategoryList better by printing out its content here. 
Not exactly sure why this doesn't work in ipdb. 

**Expected behavior**
Should print out whats in CategoryList, same behavior as when you 

aLabelLists.train.y would if you do this on a cell not using ipdb.

> CategoryList (709 items)
> 7,7,7,7,7
> Path: /Users/kelvinchan/.fastai/data/mnist_tiny

Note: I don't know enough for sure if this is an indication of a hidden problem.

**Comment by sgugger** [comment]
Should be fixed by [this commit](https://github.com/fastai/fastai/commit/cb08d8f16a369b82837e1ef1d5d6f7c96112aefc).
