### ISSUE TITLE
Weighted CrossEntropyFlat for Segmentation

### ISSUE THREAD

**Issue by JosephPB** [fastai/fastai#1768]
**Describe the bug**

When creating a custom weighted loss function for segmentation I wish to use the flattened cross entropy loss, however, this appears to have no parameter for weights, unlike in classification examples such.

**Provide your installation details**
```
=== Software === 
python        : 3.6.8
fastai        : 1.0.46.dev0
fastprogress  : 0.1.20
torch         : 1.1.0a0+929cd23
nvidia driver : 384.130
torch cuda    : 8.0.61 / is available
torch cudnn   : 7104 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11439MB | Tesla K80

=== Environment === 
platform      : Linux-4.4.0-1075-aws-x86_64-with-debian-stretch-sid
distro        : Ubuntu 16.04 xenial
conda env     : fastai_test
python        : /home/ubuntu/anaconda3/envs/fastai_test/bin/python
sys.path      : /home/ubuntu/src/cntk/bindings/python
/home/ubuntu/pytorch/build
/efs/data/jpb/Detectron/Detectron
/home/ubuntu/anaconda3/envs/fastai_test/lib/python36.zip
/home/ubuntu/anaconda3/envs/fastai_test/lib/python3.6
/home/ubuntu/anaconda3/envs/fastai_test/lib/python3.6/lib-dynload

/home/ubuntu/.local/lib/python3.6/site-packages
/home/ubuntu/anaconda3/envs/fastai_test/lib/python3.6/site-packages
/home/ubuntu/anaconda3/envs/fastai_test/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg
/home/ubuntu/anaconda3/envs/fastai_test/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg
/home/ubuntu/anaconda3/envs/fastai_test/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg
/efs/data/jpb/fastai/fastai
/home/ubuntu/anaconda3/envs/fastai_test/lib/python3.6/site-packages/IPython/extensions
/home/ubuntu/.ipython
```

**To Reproduce**

```
learn = unet_learner(data, models.resnet18, metrics=metrics, wd=wd)
w = torch.Tensor([1.0, 5.0, 10]).float().cuda()
learn.loss_func = CrossEntropyFlat(weight=w)
```
```
TypeError: forward() got an unexpected keyword argument 'weight'
```
**Expected behavior**

To update the loss function to the weighted cross entropy loss

**Comment by sgugger** [comment]
`CrossEntropyFlat` is just a shortcut around `nn.CrossEntropy()`. I think you should type `FlattenedLoss(nn.CrossEntropy(weights=...))`.

**Comment by JosephPB** [comment]
I tried that but I get the following error after doing ```learn.loss_func = FlattenedLoss(nn.CrossEntropyLoss(weight=w))```:

```
TypeError: forward() missing 2 required positional arguments: 'input' and 'target'
```

**Comment by sgugger** [comment]
Ah, you're right. 
But I can't reproduce your initial bug: just tried
``` 
learn.lossfunc = CrossEntropyFlat(weight = Tensor([1.] * data.c).cuda())
```
on a classification and a segmentation task and I didn't get any errors.

**Comment by JosephPB** [comment]
Thank you, that seems to have fixed it. I think I was getting some CUDA/CPU errors before when I was using the 
```
learn.lossfunc = CrossEntropyFlat(weight = w).cuda())
```
and then when I changed it to try to specify the Flattened version I got the errors I flagged in this issue. It seems to be working now after some changes to the Tensor type. 

Not entirely sure why I was getting the original error.

**Comment by willemcossey** [comment]
To change the loss function used by a learner, do you change the attribute `learn.loss_func` or `learn.lossfunc` like in the example above ? Or can you use it interchangeably ?

**Comment by sgugger** [comment]
`learn.loss_func`

**Comment by rpdunne** [comment]
@sgugger I am trying to use a loss function different to the default FlattenedLoss (learn.lr_find() trains fine) but when I pass it as above ( `learn.loss_func = nn.BCEWithLogitsLoss()` ) I get the error:

`ValueError                                Traceback (most recent call last)
<ipython-input-29-d81c6bd29d71> in <module>
----> 1 learn.lr_find()

~\.conda\envs\ml\lib\site-packages\fastai\train.py in lr_find(learn, start_lr, end_lr, num_it, stop_div, wd)
     30     cb = LRFinder(learn, start_lr, end_lr, num_it, stop_div)
     31     epochs = int(np.ceil(num_it/len(learn.data.train_dl)))
---> 32     learn.fit(epochs, start_lr, callbacks=[cb], wd=wd)
     33 
     34 def to_fp16(learn:Learner, loss_scale:float=None, max_noskip:int=1000, dynamic:bool=True, clip:float=None,

~\.conda\envs\ml\lib\site-packages\fastai\basic_train.py in fit(self, epochs, lr, wd, callbacks)
    200         callbacks = [cb(self) for cb in self.callback_fns + listify(defaults.extra_callback_fns)] + listify(callbacks)
    201         self.cb_fns_registered = True
--> 202         fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
    203 
    204     def create_opt(self, lr:Floats, wd:Floats=0.)->None:

~\.conda\envs\ml\lib\site-packages\fastai\basic_train.py in fit(epochs, learn, callbacks, metrics)
     99             for xb,yb in progress_bar(learn.data.train_dl, parent=pbar):
    100                 xb, yb = cb_handler.on_batch_begin(xb, yb)
--> 101                 loss = loss_batch(learn.model, xb, yb, learn.loss_func, learn.opt, cb_handler)
    102                 if cb_handler.on_batch_end(loss): break
    103 

~\.conda\envs\ml\lib\site-packages\fastai\basic_train.py in loss_batch(model, xb, yb, loss_func, opt, cb_handler)
     28 
     29     if not loss_func: return to_detach(out), yb[0].detach()
---> 30     loss = loss_func(out, *yb)
     31 
     32     if opt is not None:

~\.conda\envs\ml\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~\.conda\envs\ml\lib\site-packages\torch\nn\modules\loss.py in forward(self, input, target)
    599                                                   self.weight,
    600                                                   pos_weight=self.pos_weight,
--> 601                                                   reduction=self.reduction)
    602 
    603 

~\.conda\envs\ml\lib\site-packages\torch\nn\functional.py in binary_cross_entropy_with_logits(input, target, weight, size_average, reduce, reduction, pos_weight)
   2122 
   2123     if not (target.size() == input.size()):
-> 2124         raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
   2125 
   2126     return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)

ValueError: Target size (torch.Size([2, 1, 64, 128])) must be the same as input size (torch.Size([2, 2, 64, 128]))`


Any ideas why I can't use these different Loss Functions?

Thanks

**Comment by enemni** [comment]
`learn.loss_func= CrossEntropyFlat(weight = w).cuda()) ` because if you use `learn.lossfunc=...` and then you check typing `learn.loss_func`, you will find that nothing has been changed and the loss function is still 

> FlattenedLoss of CrossEntropyLoss()

**Comment by enemni** [comment]
> @sgugger To change the loss function used by a learner, do you change the attribute `learn.loss_func` or `learn.lossfunc` like in the example above ? Or can you use it interchangeably ?
> 
> Using fastai v 1.0.52 , pytorch v 1.1.0

`learn.loss_func= CrossEntropyFlat(weight = w).cuda()) ` because if you use `learn.lossfunc=...` and then you check typing `learn.loss_func`, you will find that nothing has been changed and the loss function is still 

> FlattenedLoss of CrossEntropyLoss()
