### ISSUE TITLE
Is there any way to take a small part of the dataset for temporary usage of debugging

### ISSUE THREAD

**Issue by CoderOverflow** [fastai/fastai#1770]
**Describe the bug**

Is there any way to take a small part of the dataset for temporary usage of debugging
```
data = (src[:1000].transform(tfms, size=128)
        .databunch(num_workers=0).normalize(imagenet_stats))
```
or
```
learn = cnn_learner(data[:1000], arch, metrics=[acc_02, f_score], model_dir='/kaggle/working/')
```

If the data-bunch can be sliced I think that will be convenient and save time when we debug the whole script.
Or, there already has some functionality can get a part of dataset that I don't know.

**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by marii-moe** [comment]
Depending on where you are getting it from you can usually do this by simply creating a folder/csv/etc folder with a small subset of your dataset. 

Also these question on how to use the library belongs on the forum, so that others are available to answer, and see the answers that you get as well.

**Comment by CoderOverflow** [comment]
I found 
train = ImageList.from_csv(path, 'train.csv')#.use_partial_data(0.001)
That seems what i want
