### ISSUE TITLE
parallel in fastai.core -> function is required to take BOTH value and index

### ISSUE THREAD

**Issue by ecatkins** [fastai/fastai#1781]
I'd posted on the[ fastai forums previously](https://forums.fast.ai/t/use-of-parallel-function-in-fastai-core/35704), that the parallel function was failing for me under all circumstances (progress bar would go to 100% but with no work done).

I dug into the code today, and it seems that the Executor is passing both the value (o) from the array BUT ALSO the index (i) to the parallelized function:

```
with ProcessPoolExecutor(max_workers=max_workers) as ex:
            futures = [ex.submit(func,o,i) for i,o in enumerate(arr)]
```

My code was failing, because my parallelized function was only expecting one value (i.e. the value from the array). The fix was to add an extra parameter to my function e.g. `def my_func(value) `becomes `def my_func(value, index)`. 

Is there a good reason for this design? If so, a note in the documentation would probably suffice. If not, the underlying code could be relatively easily amended. Either way, I'm happy to attempt a pull request.

**Comment by sgugger** [comment]
It's useful to have the index of the array when you want to save multiple files for instance (check `verify_images` in vision.data for instance) but you are right, this absolutely should be documented!
If you can make a PR to the cod notebook core.ipynb and give an example, that would be much appreciated!

**Comment by sgugger** [comment]
Can close now this is merged.
