### ISSUE TITLE
Customize an ITEMLIST to output two target values.

### ISSUE THREAD

**Issue by illcat** [fastai/fastai#1784]
Most machine reading comprehension tasks are in the form of answer extraction, outputting an answer starting position and answer ending position. But I didn't find a way to implement such an itemlist, most of the examples are in the field of machine vision. Can you give an example?

**Comment by sgugger** [comment]
Questions like this should be asked on the [forum](https://forums.fast.ai) as we keep the issues for known bugs only.
There are plenty of examples of ItemList in text and tabular. TabulatList returns two inputs for instance.
