### ISSUE TITLE
provision to have bias=True or False in Last Linear Layer

### ISSUE THREAD

**Issue by jaideep11061982** [fastai/fastai#1785]
**Describe the bug**

I think it would be quite handy feature to allow create_head take one more param to whether have last FC layer bias or not.In some competitions of kaggle Top rankers have explicitly set bias=False in nn.Linear() layer at last.Please consider including this param so left to use to decide on this.
```
def create_cnn_model(base_arch:Callable, nc:int, cut:Union[int,Callable]=None, pretrained:bool=True,
        lin_ftrs:Optional[Collection[int]]=None, ps:Floats=0.5, custom_head:Optional[nn.Module]=None,
        split_on:Optional[SplitFuncOrIdxList]=None, bn_final:bool=False):
    "Create custom convnet architecture"
    body = create_body(base_arch, pretrained, cut)
    if custom_head is None:
        nf = num_features_model(nn.Sequential(*body.children())) * 2
        head = create_head(nf, nc, lin_ftrs, ps=ps, bn_final=bn_final)
    else: head = custom_head
    return nn.Sequential(body, head)
```
**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
Hi there! New features should be suggested on the appropriate thread on the [forum](https://forums.fast.ai/). We keep issues for standing bugs only.

In the meantime, you can do it manually by creating your own head (just mimic the source code of `create_head`) and then pass your custom head to `create_cnn` with `custom_head=...`.
