### ISSUE TITLE
name 'create_cnn' is not defined

### ISSUE THREAD

**Issue by raphtoubi** [fastai/fastai#1794]
**Describe the bug**
I have imported fastai.vision
when i write the following code I get error that "name 'create_cnn' is not defined "

learn = create_cnn(data, models.resnet34, metrics=error_rate)

NameError Traceback (most recent call last)
in
----> 1 learn = create_cnn(data, models.resnet34, metrics=error_rate)

NameError: name 'create_cnn' is not defined

**Provide your installation details**

[Uploading Capture d’écran 2019-03-08 à 19.07.56.png…]()

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by raphtoubi** [comment]
I have imported fastai.vision
when i write the following code I get error that "name 'create_cnn' is not defined "

learn = create_cnn(data, models.resnet34, metrics=error_rate)

NameError                                 Traceback (most recent call last)
<ipython-input-9-24f407e425f3> in <module>
----> 1 learn = create_cnn(data, models.resnet34, metrics=error_rate)

NameError: name 'create_cnn' is not defined

**Comment by raphtoubi** [comment]
I have imported fastai.vision
when i write the following code I get error that "name 'create_cnn' is not defined "

learn = create_cnn(data, models.resnet34, metrics=error_rate)

NameError Traceback (most recent call last)
in 
----> 1 learn = create_cnn(data, models.resnet34, metrics=error_rate)

NameError: name 'create_cnn' is not defined

**Comment by RikTikTav** [comment]
Hi,
I believe create_cnn has been deprecated. Did you try cnn_learner? This problem was brought up on forum... https://forums.fast.ai/t/nameerror-name-create-cnn-is-not-defined/40321/7

**Comment by sgugger** [comment]
Yes create_cnn has been deprecated, you should see a proper error message if you are on the latest fastai, double-check you're not on 0.7
