### ISSUE TITLE
AttributeError: 'Learner' object has no attribute 'min_grad_lr'

### ISSUE THREAD

**Issue by austinmw** [fastai/fastai#1796]
**Describe the bug**

**Intermittently**, I am getting the error `AttributeError: 'Learner' object has no attribute 'min_grad_lr'` When attempting to do:

```
learn.lr_find()
fig = learn.recorder.plot(suggestion=True, return_fig=True);
lr = learn.recorder.min_grad_lr 
```
**Provide your installation details**

```text
=== Software === 
python        : 3.6.5
fastai        : 1.0.46
fastprogress  : 0.1.20
torch         : 1.0.0
nvidia driver : 410.79
torch cuda    : 10.0.130 / is available
torch cudnn   : 7401 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11441MB | Tesla K80

=== Environment === 
platform      : Linux-4.14.97-74.72.amzn1.x86_64-x86_64-with-glibc2.9
distro        : #1 SMP Tue Feb 5 20:59:30 UTC 2019
conda env     : pytorch_p36
python        : /home/ec2-user/anaconda3/envs/pytorch_p36/bin/python
sys.path      : 
/home/ec2-user/src/cntk/bindings/python
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python36.zip
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/lib-dynload
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/IPython/extensions
/home/ec2-user/.ipython
```

**To Reproduce**
This error is happening while training inside a docker container (local-notebook SageMaker training). It seems that I can't reproduce this error directly inside a notebook environment. I've also tried `lr_find(learn)`, but I assume that's the same thing.

**Comment by sgugger** [comment]
You need to pass `suggestion=True` to make the LR finder try to find a suggestion for you and have that argument.

**Comment by austinmw** [comment]
@sgugger I am doing that, `learn.recorder.plot(suggestion=True, return_fig=True)`

**Comment by sgugger** [comment]
Ah sorry, I missed that. Weird! Do you see the red dot and everything?

**Comment by austinmw** [comment]
My training logs are being written to console from docker so I can't actually see the plots. It seemed that the problem was Intermittent, although now it looks like `lr_find(learn)` is erroring every time and `learn.lr_find()` is not. Aren't they the same thing though? Apologies if my error feedback is not that useful, please let me know of any other info to add.

**Comment by sgugger** [comment]
They are the same thing, this is really weird. You won't see the plots but it prints the suggestion, do you have that line? Also, can you check the result of 
```
from fastai.utils.show_install import show_install
show_install()
```
and copy-paste it here?

**Comment by austinmw** [comment]
Yup I have the suggestion print out. The `show_install()` output I posted is from my training code inside the container. Let me triple check that everything I've said is accurate, will post back shortly with more test details.

**Comment by sgugger** [comment]
Thanks, and yes I can see the show_install. Sorry I'm really distracted today ;)

**Comment by austinmw** [comment]
Np :) so It does happen with both `lr_find()` and `.lr_find()`, and when it happens the number is not printed to logs.

**Comment by sgugger** [comment]
Ok, in that case, do you get this error message printed? "Failed to compute the gradients, there might not be enough points."

**Comment by austinmw** [comment]
Ah, yeah I do! My console is printing a lot of control characters from the progress bars so it was hard to see.

**Comment by sgugger** [comment]
Oh so that's not a bug then ;)

**Comment by austinmw** [comment]
Thanks, added a try block.

**Comment by austeane** [comment]
I was having this issue too, with plenty of data, and it seems the min_grad_lr is not calculated until I call recorder.plot().

**Comment by sgugger** [comment]
Yes, it's only computed in that function.

**Comment by Tato14** [comment]
Hi! Following a little bit the issue, is there a way to output the table with loss and lr rather than the graph?

**Comment by sgugger** [comment]
Losses and learning rates are in `learn.recorder.losses` and `learner.recorder.lrs` so you can easily build the table you want.

**Comment by sid-sundrani** [comment]
when a model is saved using learn.save('model'), then later loaded using learn.load('model'), the loaded learner object does not have a recorder attribute and hence I can't access training stats like plot_losses. Is there a way I can save the learner object such that it would save these attributes along with it?

**Comment by Flock1** [comment]
Hi,

I am getting this error:
```
AttributeError: 'Learner' object has no attribute 'lr_find'
```
Please let me know why am I getting this? I see everyone using this but no one gets this error. I am using `'2.0.10'` version of fastai. I imported `Learner` like this:
`from fastai.vision.learner import Learner`

**Comment by rnyak** [comment]
I am getting the same `AttributeError: 'Learner' object has no attribute 'lr_find'`  error with version `2.1.5`.

**Comment by MoshiurFaisal** [comment]
getting an error of  'TransformerTextClassLearner' object has no attribute 'recorder' on tensor flow 2.2.1
