### ISSUE TITLE
Error: `libsixel` is needed

### ISSUE THREAD

**Issue by odysseus0** [fastai/fastai#1798]
```text
=== Software === 
python       : 3.7.2
fastai       : 1.0.48.dev0
fastprogress : 0.1.19
torch        : 1.0.1.post2
torch cuda   : None / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Darwin-18.2.0-x86_64-i386-64bit
conda env    : fastai-dev
python       : /Users/georgezhang/anaconda3/envs/fastai-dev/bin/python
sys.path     : /Users/georgezhang/fastai/course-v3/nbs/dl1
/Users/georgezhang/anaconda3/envs/fastai-dev/lib/python37.zip
/Users/georgezhang/anaconda3/envs/fastai-dev/lib/python3.7
/Users/georgezhang/anaconda3/envs/fastai-dev/lib/python3.7/lib-dynload

/Users/georgezhang/anaconda3/envs/fastai-dev/lib/python3.7/site-packages
/Users/georgezhang/fastai/fastai-fork
/Users/georgezhang/anaconda3/envs/fastai-dev/lib/python3.7/site-packages/IPython/extensions
/Users/georgezhang/.ipython
no supported gpus found on this system
```

After running

```python
from fastai.vision import *
```

I got an error:

```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-2-283c0d40bede> in <module>
----> 1 from fastai.vision import *
      2 from fastai.metrics import error_rate

~/fastai/fastai-fork/fastai/vision/__init__.py in <module>
----> 1 from .. import basics
      2 from ..basics import *
      3 from .learner import *
      4 from .image import *
      5 from .data import *

~/fastai/fastai-fork/fastai/basics.py in <module>
----> 1 from .basic_train import *
      2 from .callback import *
      3 from .core import *
      4 from .basic_data import *
      5 from .data_block import *

~/fastai/fastai-fork/fastai/basic_train.py in <module>
      8 from fastprogress.fastprogress import format_time, IN_NOTEBOOK
      9 from time import time
---> 10 from fastai.sixel import plot_sixel
     11 
     12 __all__ = ['Learner', 'LearnerCallback', 'Recorder', 'RecordOnCPU', 'fit', 'loss_batch', 'train_epoch', 'validate',

~/fastai/fastai-fork/fastai/sixel.py in <module>
      3 libsixel = try_import('libsixel')
      4 if not libsixel:
----> 5     raise Exception('Error: `libsixel` is needed. See https://github.com/saitoha/libsixel')
      6 
      7 def _sixel_encode(data, width, height):

Exception: Error: `libsixel` is needed. See https://github.com/saitoha/libsixel
```

**Comment by odysseus0** [comment]
I have checked that `1.0.47.post1` does not have this issue. So the problem is introduced in `release-1.0.48`.

**Comment by Benudek** [comment]
did you find a way to install it locally ? Searching around ...

**Comment by Benudek** [comment]
tried some things like: pip install libsixel-python no luck ...

**Comment by odysseus0** [comment]
I didn't find an easy way to install for Mac OS X. So for now we need to download the source code and compile it ourselves.

**Comment by jph00** [comment]
> I have checked that 1.0.47.post1 does not have this issue. So the problem is introduced in release-1.0.48.

There is no release 1.0.48. The issue is on master. Please do let us know when you're reporting an issue using master. We certainly like to hear about them (including this one - thanks!) but note that we don't in general expect master to work for everyone all the time; it's where we do all our day to day development. So you should only use it if you're OK finding and fixing bugs.

I've moved the libsixel check inside the function where it's used. So you should find everything works fine now for you without libsixel installed, except of course for fastai.sixel. If you want to test that, you'll need to install the lib from source unfortunately, since there are no packages for it yet.

**Comment by odysseus0** [comment]
Ah, sorry for my inaccurate wording. I should have said it as "1.0.48-dev".

I was trying to fix another bug I found so that I thought working on master would be best.

Thank you so much!

**Comment by xavierfontaine** [comment]
Using a 1.0.52 freshly installed with pip, I happen to have a similar issue when running my scripts at the command line (see below).  

I have installed `libsixel-python`, but it did not change the outcome.

The error I face:
`---> 83 learner.recorder.plot(skip_start=0)

~\AppData\Local\Continuum\anaconda3\envs\bdclcl\lib\site-packages\fastai\basic_train.py in plot(self, skip_start, skip_end, suggestion, return_fig, **kwargs)
    542             self.min_grad_lr = lrs[mg]
    543         if ifnone(return_fig, defaults.return_fig): return fig
--> 544         if not IN_NOTEBOOK: plot_sixel(fig)
    545
    546     def plot_losses(self, skip_start:int=0, skip_end:int=0, return_fig:bool=None)->Optional[plt.Figure]:

~\AppData\Local\Continuum\anaconda3\envs\bdclcl\lib\site-packages\fastai\sixel.py in plot_sixel(fig)
     14 def plot_sixel(fig=None):
     15     if not libsixel:
---> 16         raise Exception('Error: `libsixel` is needed. See https://github.com/saitoha/libsixel')
     17     if fig is None: fig = plt.gcf()
     18     fig.canvas.draw()

Exception: Error: `libsixel` is needed. See https://github.com/saitoha/libsixel`

**Comment by xavierfontaine** [comment]
My bad, this issue has already been answered [somewhere else](https://github.com/fastai/fastai/commit/74ff274773ef20d7611cffd08c57b1143a07058d). Instead of raising an Exception, the next version of the package will simply warn the user.

**Comment by aviogit** [comment]
I did `sudo apt install libsixel-bin libsixel-dev libsixel1` and now I don't get the exception error anymore, but still no graph. Now the error is:

> LR Finder is complete, type {learner_name}.recorder.plot() to see the graph.

Of course I have `learn.recorder.plot()` in my code.

**Comment by OwlWisdom** [comment]
> I did `sudo apt install libsixel-bin libsixel-dev libsixel1` and now I don't get the exception error anymore, but still no graph. Now the error is:
> 
> > LR Finder is complete, type {learner_name}.recorder.plot() to see the graph.
> 
> Of course I have `learn.recorder.plot()` in my code.

It's useful !  Thank you!
