### ISSUE TITLE
Wrong dropout default values in awd_lstm_lm_config

### ISSUE THREAD

**Issue by jpizarrom** [fastai/fastai#1809]
**Describe the bug**

Values used to be (https://github.com/fastai/fastai/blob/release-1.0.42/fastai/text/learner.py#L16)
- [0.25, 0.1, 0.2, 0.02, 0.15]
  - [input_p=dps[0], output_p=dps[1],weight_p=dps[2], embed_p=dps[3], hidden_p=dps[4]]

But now are (https://github.com/fastai/fastai/blob/release-1.0.43/fastai/text/models/awd_lstm.py#L194)
- output_p=0.25, hidden_p=0.1, input_p=0.2, embed_p=0.02, weight_p=0.15

**Expected behavior**

Values should be 
- input_p=0.25, output_p=0.1, weight_p=0.2, embed_p=0.02, hidden_p=0.15

**Comment by sgugger** [comment]
Oh, thanks for flagging!
Should be fixed in [this commit](https://github.com/fastai/fastai/commit/4a979c72d2a09337cb89b6f584f207dc6d7db1e8).
