### ISSUE TITLE
Make fastai release 0.7.2 available on pip

### ISSUE THREAD

**Issue by vishalvijay30** [fastai/fastai#1821]
Hello, would it be possible to make [fastai release 0.7.2](https://github.com/fastai/fastai/releases/tag/v0.7.2) available on pypi so that it can be installed using pip. Currently, we only have fastai 0.7.0 published but there were some changes made to the old fastai library which are only available on fastai 0.7.2. Thanks!

**Comment by sgugger** [comment]
You have to install from the repo as explained [here](https://github.com/fastai/fastai/tree/master/old#install-as-pip-package). We won't make any new releases with versions < 1.
