### ISSUE TITLE
No URL for pre-trained xresnet weights.

### ISSUE THREAD

**Issue by BavarianToolbox** [fastai/fastai#1822]
**Describe the bug**

Importing pre-trained ```xresnet``` weights fails because the dictionary that's supposed to contain the URL pointing at the weight file doesn't exist in the ```xresnet.py``` module.

**Provide your installation details**

```text
=== Software === 
python        : 3.7.2
fastai        : 1.0.48
fastprogress  : 0.1.19
torch         : 1.0.1.post2
nvidia driver : 410.72
torch cuda    : 10.0.130 / is available
torch cudnn   : 7402 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 7611MB | Tesla P4

=== Environment === 
platform      : Linux-4.9.0-8-amd64-x86_64-with-debian-9.6
distro        : #1 SMP Debian 4.9.130-2 (2018-10-27)
conda env     : base
python        : /home/constantin.baumgartner/.conda/envs/fellowship_env/bin/python
sys.path      : /home/constantin.baumgartner/grossman
```

**To Reproduce**

With any single-label image dataset, try creating a ```cnn_learner``` with any of the pretrained xresnet architetures.

```learn = cnn_learner(data, models.xresnet34, metrics = accuracy, pretrained=True)```

```---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-11-a99c8c9e8e1d> in <module>
----> 1 learn = cnn_learner(data, models.xresnet34, metrics = accuracy)

~/.conda/envs/fellowship_env/lib/python3.7/site-packages/fastai/vision/learner.py in cnn_learner(data, base_arch, cut, pretrained, lin_ftrs, ps, custom_head, split_on, bn_final, init, concat_pool, **kwargs)
     95     meta = cnn_config(base_arch)
     96     model = create_cnn_model(base_arch, data.c, cut, pretrained, lin_ftrs, ps=ps, custom_head=custom_head,
---> 97         split_on=split_on, bn_final=bn_final, concat_pool=concat_pool)
     98     learn = Learner(data, model, **kwargs)
     99     learn.split(split_on or meta['split'])

~/.conda/envs/fellowship_env/lib/python3.7/site-packages/fastai/vision/learner.py in create_cnn_model(base_arch, nc, cut, pretrained, lin_ftrs, ps, custom_head, split_on, bn_final, concat_pool)
     81         split_on:Optional[SplitFuncOrIdxList]=None, bn_final:bool=False, concat_pool:bool=True):
     82     "Create custom convnet architecture"
---> 83     body = create_body(base_arch, pretrained, cut)
     84     if custom_head is None:
     85         nf = num_features_model(nn.Sequential(*body.children())) * 2

~/.conda/envs/fellowship_env/lib/python3.7/site-packages/fastai/vision/learner.py in create_body(arch, pretrained, cut)
     53 def create_body(arch:Callable, pretrained:bool=True, cut:Optional[Union[int, Callable]]=None):
     54     "Cut off the body of a typically pretrained `model` at `cut` (int) or cut the model as specified by `cut(model)` (function)."
---> 55     model = arch(pretrained)
     56     cut = ifnone(cut, cnn_config(arch)['cut'])
     57     if cut is None:

~/.conda/envs/fellowship_env/lib/python3.7/site-packages/fastai/vision/models/xresnet.py in xresnet34(pretrained, **kwargs)
    164     """
    165     model = XResNet(BasicBlock, [3, 4, 6, 3], **kwargs)
--> 166     if pretrained: model.load_state_dict(model_zoo.load_url(model_urls['xresnet34']))
    167     return model
    168 

NameError: name 'model_urls' is not defined
```

It looks like ```model_urls``` is supposed to be a dictionary that takes an architecture name as the key and returns a URL pointing to the corresponding weight file, but the ```model_urls``` dictionary isn't defined or imported anywhere in the ```xresnet.py``` module.

**Expected behavior**

The cnn_learner should be created and initialized with the pre-trained weights. 

**Screenshots**

<img width="875" alt="Screen Shot 2019-03-14 at 5 55 46 PM" src="https://user-images.githubusercontent.com/30835467/54394164-7f7b7180-4682-11e9-834c-ae83424f1b15.png">

**Additional context**

It works without the pre-trained weights, i.e. with ```pretrained=False```.

<img width="879" alt="Screen Shot 2019-03-14 at 5 58 48 PM" src="https://user-images.githubusercontent.com/30835467/54394295-dbde9100-4682-11e9-9d7f-da1d6943650c.png">

**Comment by sgugger** [comment]
No xresnet doesn't have a pretrained model. It's for our training imagenet from scratch experiments.

**Comment by BavarianToolbox** [comment]
Gotcha, sorry for the confusion.

**Comment by mariopi27** [comment]
It seems like there is a problem with the xresnet model in the current version.

fastai                            1.0.52    

`from fastai.vision import *

path = untar_data(URLs.MNIST_SAMPLE)

data = ImageDataBunch.from_folder(path)

learn = cnn_learner(data, models.xresnet34, metrics = accuracy, pretrained=False)

learn.fit(1)`

results in 

TypeError: xresnet() got multiple values for argument 'expansion'

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-9613abaa75d2> in <module>
      5 data = ImageDataBunch.from_folder(path)
      6 
----> 7 learn = cnn_learner(data, models.xresnet34, metrics = accuracy, pretrained=False)
      8 
      9 learn.fit(1)

~/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/vision/learner.py in cnn_learner(data, base_arch, cut, pretrained, lin_ftrs, ps, custom_head, split_on, bn_final, init, concat_pool, **kwargs)
     95     meta = cnn_config(base_arch)
     96     model = create_cnn_model(base_arch, data.c, cut, pretrained, lin_ftrs, ps=ps, custom_head=custom_head,
---> 97         split_on=split_on, bn_final=bn_final, concat_pool=concat_pool)
     98     learn = Learner(data, model, **kwargs)
     99     learn.split(split_on or meta['split'])

~/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/vision/learner.py in create_cnn_model(base_arch, nc, cut, pretrained, lin_ftrs, ps, custom_head, split_on, bn_final, concat_pool)
     81         split_on:Optional[SplitFuncOrIdxList]=None, bn_final:bool=False, concat_pool:bool=True):
     82     "Create custom convnet architecture"
---> 83     body = create_body(base_arch, pretrained, cut)
     84     if custom_head is None:
     85         nf = num_features_model(nn.Sequential(*body.children())) * (2 if concat_pool else 1)

~/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/vision/learner.py in create_body(arch, pretrained, cut)
     53 def create_body(arch:Callable, pretrained:bool=True, cut:Optional[Union[int, Callable]]=None):
     54     "Cut off the body of a typically pretrained `model` at `cut` (int) or cut the model as specified by `cut(model)` (function)."
---> 55     model = arch(pretrained)
     56     cut = ifnone(cut, cnn_config(arch)['cut'])
     57     if cut is None:`

**Comment by JoshVarty** [comment]
>As said up there, there is no pretrained model for xresnet, it's then not suitable for use with `cnn_learner` which requires a pretrained architecture.

But not all `cnn_learner`'s require pretrained architectures, correct? @mariopi27 created his with `pretrained=False`. I upgraded from fastai `1.0.50` to `1.0.52` and started seeing this error as well.

Is this related to: https://github.com/fastai/fastai/commit/67e866623aa52b51f7e139dc2fc10a78c30b6b06

**Comment by sgugger** [comment]
That is what's needed yes, plus some metada to explain the library where to cut and split. 
We just finished developing that model. Making it usable with `cnn_learner` and providing a pretrained model is in our plans and will be in v1.1 (the ultimate plan being for it to be integrated in torchvision directly), just be a little bit more patient ;)

**Comment by gloriamacia** [comment]
Dear @sgugger, just went trough the thread. When will v1.1 of fastai be realeased aproximately?

**Comment by sgugger** [comment]
It's going to be v2 in the end, not v1.1, and it's under active development. You can track the progress on the [forum](https://forums.fast.ai/c/fastai-users/fastai-v2).
