### ISSUE TITLE
Vision TTA breaks when with_loss = True

### ISSUE THREAD

**Issue by BavarianToolbox** [fastai/fastai#1823]
**Describe the bug**

In ```fastai/vision/tta.py```, ```_TTA``` fails when ```with_loss=True```.  This happens in two scenarios:

1)
When ```TTA``` is called indirectly from ```ClassificationInterpretation``` with ```tta=True```:

 ```
interp = ClassificationInterpretation.from_learner(learn, tta = True)

Total time: 00:37
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-35-43028903da6d> in <module>
----> 1 interp = ClassificationInterpretation.from_learner(learn, tta = True)

~/.conda/envs/fellowship_env/lib/python3.7/site-packages/fastai/vision/learner.py in _cl_int_from_learner(cls, learn, ds_type, tta)
    125 def _cl_int_from_learner(cls, learn:Learner, ds_type:DatasetType=DatasetType.Valid, tta=False):
    126     "Create an instance of `ClassificationInterpretation`. `tta` indicates if we want to use Test Time Augmentation."
--> 127     preds = learn.TTA(ds_type=ds_type, with_loss=True) if tta else learn.get_preds(ds_type=ds_type, with_loss=True)
    128     return cls(learn, *preds, ds_type=ds_type)
    129 

~/.conda/envs/fellowship_env/lib/python3.7/site-packages/fastai/vision/tta.py in _TTA(learn, beta, scale, ds_type, with_loss)
     39         final_preds = preds*beta + avg_preds*(1-beta)
     40         if with_loss:
---> 41             return final_preds, y, calc_loss(final_preds, y, learn.loss_func)
     42         return final_preds, y
     43 

NameError: name 'calc_loss' is not defined
``` 

2)
When ```TTA``` is called directly from the learner with ```with_loss=True```

```
 learn.TTA(with_loss = True)

Total time: 00:29
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-42-f10a597bda46> in <module>
----> 1 accuracy(*learn.TTA(with_loss = True))

~/.conda/envs/fellowship_env/lib/python3.7/site-packages/fastai/vision/tta.py in _TTA(learn, beta, scale, ds_type, with_loss)
     39         final_preds = preds*beta + avg_preds*(1-beta)
     40         if with_loss:
---> 41             return final_preds, y, calc_loss(final_preds, y, learn.loss_func)
     42         return final_preds, y
     43 

NameError: name 'calc_loss' is not defined
```

Both errors are a result of a problem on line 41 in``` fastai/vision/tta.py```, namely, ```calc_loss``` is note defined.

I think ```calc_loss``` used to be part of ```torch_core```(I'm not 100% sure about this).

**Provide your installation details**

```
=== Software === 
python        : 3.7.2
fastai        : 1.0.48
fastprogress  : 0.1.19
torch         : 1.0.1.post2
nvidia driver : 410.72
torch cuda    : 10.0.130 / is available
torch cudnn   : 7402 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 7611MB | Tesla P4

=== Environment === 
platform      : Linux-4.9.0-8-amd64-x86_64-with-debian-9.6
distro        : #1 SMP Debian 4.9.130-2 (2018-10-27)
conda env     : base
python        : /home/constantin.baumgartner/.conda/envs/fellowship_env/bin/python
sys.path      : /home/constantin.baumgartner/grossman
```

**To Reproduce**

Call TTA on a vision learner, either directly using ```.TTA(with_loss=True)``` or indirectly using ```ClassificationInterpretation.from_learner(learn, tta=True)```.

**Expected behavior**

When the ```with_loss``` flag is set to ```True```, ```_TTA``` should return the final predictions: ```final_preds```, the ground truth labels: ```y```, AND the loss: ```calc_loss(final_preds, y, learn.loss_func)```

**Screenshots**

A direct call to ```TTA``` with ```with_loss=True```

<img width="868" alt="Screen Shot 2019-03-14 at 7 23 46 PM" src="https://user-images.githubusercontent.com/30835467/54397965-bb1c3880-468e-11e9-957c-bcb80f8025d0.png">

An indirect call to ```TTA``` using ```ClassificationInterpretation.from_learner``` with ```tta=True``` 

<img width="870" alt="Screen Shot 2019-03-14 at 7 23 35 PM" src="https://user-images.githubusercontent.com/30835467/54397960-b6578480-468e-11e9-86b2-54bac86b3472.png">

**Additional context**

TTA works when ```with_loss=False``` (which is the default), and the ClassificationInterpretation works when ```tta=False``` (which is also the default).

**Comment by sgugger** [comment]
Oh, the function called (`calc_loss`) was removed. Will fix tomorrow morning.
