### ISSUE TITLE
Image size attribute does not reflect resize changes

### ISSUE THREAD

**Issue by austinmw** [fastai/fastai#1825]
**Describe the bug**

`fastai.vision.image.Image` object `size` attribute does not reflect `resize` changes.

**Provide your installation details**

```text
=== Software === 
python        : 3.6.5
fastai        : 1.0.48
fastprogress  : 0.1.20
torch         : 1.0.0
nvidia driver : 410.79
torch cuda    : 10.0.130 / is available
torch cudnn   : 7401 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11441MB | Tesla K80

=== Environment === 
platform      : Linux-4.14.97-74.72.amzn1.x86_64-x86_64-with-glibc2.9
distro        : Amazon Linux AMI 2018.03 
conda env     : pytorch_p36
python        : /home/ec2-user/anaconda3/envs/pytorch_p36/bin/python
sys.path      : 
/home/ec2-user/src/cntk/bindings/python
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python36.zip
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/lib-dynload
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/IPython/extensions
/home/ec2-user/.ipython
```

**To Reproduce**
```python
im = open_image(img_path)
print(im.size, im.data.shape)
im.resize(240)
print(im.size, im.data.shape)
```
Output:

> torch.Size([800, 432]) torch.Size([1, 800, 432])
> torch.Size([800, 432]) torch.Size([1, 240, 240])

**Expected behavior**

I think if this resizing is done in place that the size attribute should be updated as well so that the output should look like:

> torch.Size([800, 432]) torch.Size([1, 800, 432])
> torch.Size([1, 240, 240]) torch.Size([1, 240, 240])

**Screenshots**
![Screenshot 2019-03-15 15 39 29](https://user-images.githubusercontent.com/12224358/54457988-33d7cf00-4739-11e9-9787-128edf64be16.png)

p.s. sorry for the +1 issue count :)

**Comment by sgugger** [comment]
No problem ;)
It's not a bug, this is the intended behavior: the resize is done lazily so if you don't specifically ask for img.data to be computed, it doesn't do anything (that's how we manage to execute all the transforms + resize in one call and one interpolation only).

So to see the change just do:
```
_ = img.data
```
then you will see the size has changed.

Another way is to type `img.refresh()`, which should trigger that computation too (without returning anything).

**Comment by austinmw** [comment]
Ah, that clears up my confusion, thanks again!

**Comment by sgugger** [comment]
Np, and if you feel like contributing, you can add this little bit to the doc notebook `vision.transform` so that other people aren't confused :)

**Comment by stas00** [comment]
Specifically, https://docs.fast.ai/vision.transform.html#resize - thank you!
