### ISSUE TITLE
Cannot load language model dumped with lm.save

### ISSUE THREAD

**Issue by timpal0l** [fastai/fastai#1826]
In [13]: learn = load_learner('', fname='fit_head.pth')                                                                                                            
---------------------------------------------------------------------------
```
KeyError                                  Traceback (most recent call last)
<ipython-input-13-ea915999eaa7> in <module>
----> 1 learn = load_learner('', fname='fit_head_big.pth')

~/anaconda3/lib/python3.7/site-packages/fastai/basic_train.py in load_learner(path, fname, test, **db_kwargs)
    584     state = torch.load(Path(path)/fname, map_location='cpu') if defaults.device == torch.device('cpu') else torch.load(Path(path)/fname)
    585     model = state.pop('model')
--> 586     src = LabelLists.load_state(path, state.pop('data'))
    587     if test is not None: src.add_test(test)
    588     data = src.databunch(**db_kwargs)

KeyError: 'data'
```
So I built a lm, fitted it a few cycles, then saved it with lm.save('fit_head').

I tried to load it again later, without any success..
 
latest pytorch & fastai, using a macbook pro 2018 with latest sierra. Everything installed with anaconda..

btw, when should I use export instead of save?

**Comment by sgugger** [comment]
You should use `export` :)
`Learner.save` goes with `Learner.load` and `Learner.export` goes with `load_learner`.
