### ISSUE TITLE
learn.lr_find() fail for language modelleing

### ISSUE THREAD

**Issue by kasparlund** [fastai/fastai#1837]
i use lr_find for language modelling in version 1.0.50.dev0
when i run this: 
learn.lr_find()
learn.recorder.plot()
gc.collect()

is get this:
LR Finder is complete, type {learner_name}.recorder.plot() to see the graph.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-37-612f4cdb545e> in <module>
----> 1 learn.lr_find()
      2 learn.recorder.plot()
      3 gc.collect()

d:\code\fastai\fastai\train.py in lr_find(learn, start_lr, end_lr, num_it, stop_div, wd)
     30     cb = LRFinder(learn, start_lr, end_lr, num_it, stop_div)
     31     epochs = int(np.ceil(num_it/len(learn.data.train_dl)))
---> 32     learn.fit(epochs, start_lr, callbacks=[cb], wd=wd)
     33 
     34 def to_fp16(learn:Learner, loss_scale:float=None, max_noskip:int=1000, dynamic:bool=False, clip:float=None,

d:\code\fastai\fastai\basic_train.py in fit(self, epochs, lr, wd, callbacks)
    194         callbacks = [cb(self) for cb in self.callback_fns] + listify(callbacks)
    195         if defaults.extra_callbacks is not None: callbacks += defaults.extra_callbacks
--> 196         fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
    197 
    198     def create_opt(self, lr:Floats, wd:Floats=0.)->None:

d:\code\fastai\fastai\basic_train.py in fit(epochs, learn, callbacks, metrics)
    105                                        cb_handler=cb_handler, pbar=pbar)
    106             else: val_loss=None
--> 107             if cb_handler.on_epoch_end(val_loss): break
    108     except Exception as e:
    109         exception = e

d:\code\fastai\fastai\callback.py in on_epoch_end(self, val_loss)
    314         "Epoch is done, process `val_loss`."
    315         self.state_dict['last_metrics'] = [val_loss] if val_loss is not None else [None]
--> 316         self('epoch_end', call_mets = val_loss is not None)
    317         self.state_dict['epoch'] += 1
    318         return self.state_dict['stop_training']

d:\code\fastai\fastai\callback.py in __call__(self, cb_name, call_mets, **kwargs)
    248         if call_mets:
    249             for met in self.metrics: self._call_and_update(met, cb_name, **kwargs)
--> 250         for cb in self.callbacks: self._call_and_update(cb, cb_name, **kwargs)
    251 
    252     def set_dl(self, dl:DataLoader):

d:\code\fastai\fastai\callback.py in _call_and_update(self, cb, cb_name, **kwargs)
    238     def _call_and_update(self, cb, cb_name, **kwargs)->None:
    239         "Call `cb_name` on `cb` and update the inner state."
--> 240         new = ifnone(getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs), dict())
    241         for k,v in new.items():
    242             if k not in self.state_dict:

d:\code\fastai\fastai\train.py in on_epoch_end(self, n_epochs, last_metrics, **kwargs)
     71             val_iter = np.array(rec.nb_batches).cumsum()
     72             x_bounds = (0, (n_epochs - len(rec.nb_batches)) * rec.nb_batches[-1] + len(rec.losses))
---> 73             y_bounds = (0, max((max(Tensor(rec.losses)), max(Tensor(rec.val_losses)))))
     74             rec.pbar.update_graph([(iters, rec.losses), (val_iter, rec.val_losses)], x_bounds, y_bounds)
     75         return {}

TypeError: must be real number, not NoneType

**Comment by sgugger** [comment]
Fixed now, but please always give a full reproducible example as errors may come from other reasons than the last line you typed. In this case, it's because you used `ShowGraph` as a `Callback` and it takes time to guess this, time that I'd rather spend developing new features ;)
