### ISSUE TITLE
fastai.text:  learn.load(filename) failes first time and succed next time

### ISSUE THREAD

**Issue by kasparlund** [fastai/fastai#1849]
versiob : '1.0.51.dev0'

**Preceeding the failiur**
TEXT = "Andrew Yan-Tak Ng is a Chinese English computer scientist, executive, investor, "
N_WORDS = 40
N_SENTENCES = 5

print(("\n".join(learn.predict(TEXT, N_WORDS, temperature=0.75, sep="") for _ in range(N_SENTENCES))).replace("▁",""))
print(("\n".join(learn.predict(TEXT, N_WORDS, temperature=0.25, sep="") for _ in range(N_SENTENCES))).replace("▁",""))

pd_train_loss = pd.DataFrame(data=np.hstack([learn.recorder.losses]),  columns=["train_loss"])
pd_train_loss.to_csv(pathTrainValid/f"models/{model.name}/{experiment_name}_train_loss.csv", header="losses")

pd_valid_loss = pd.DataFrame(data=np.column_stack((learn.recorder.val_losses, learn.recorder.metrics)),  columns=["val_loss", "accuracy"])
pd_valid_loss.to_csv(pathTrainValid/f"models/{model.name}/{experiment_name}_valid_loss.csv", header="losses")
pd_train_loss = pd_valid_loss=None
gc.collect()

**Failes in this line**
**learn = learn.load(f'{model.name}/{experiment_name}')**

**THE error message:**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-99-6a62bf5b0534> in <module>
----> 1 learn = learn.load(f'{model.name}/{experiment_name}')

d:\code\fastai\fastai\basic_train.py in load(self, name, device, strict, with_opt, purge, remove_module)
    259             remove_module:bool=False):
    260         "Load model and optimizer state (if `with_opt`) `name` from `self.model_dir` using `device`."
--> 261         if purge: self.purge(clear_opt=ifnone(with_opt, False))
    262         if device is None: device = self.data.device
    263         elif isinstance(device, int): device = torch.device('cuda', device)

d:\code\fastai\fastai\basic_train.py in purge(self, clear_opt)
    320         self.callbacks = [load_callback(c,s, self) for c,s in cb_state.items()]
    321         if not clear_opt and 'opt' in state:
--> 322             self.opt = OptimWrapper.load_with_state_and_layer_group(state['opt'], self.layer_groups)
    323         del state
    324         gc.collect()

d:\code\fastai\fastai\callback.py in load_with_state_and_layer_group(cls, state, layer_groups)
    153                      bn_wd=state['bn_wd'])
    154         res._mom,res._beta = state['mom'],state['beta']
--> 155         res.load_state_dict(state['opt_state'])
    156         return res
    157 

c:\users\kl\appdata\local\conda\conda\envs\fastai\lib\site-packages\torch\optim\optimizer.py in load_state_dict(self, state_dict)
    112         saved_lens = (len(g['params']) for g in saved_groups)
    113         if any(p_len != s_len for p_len, s_len in zip(param_lens, saved_lens)):
--> 114             raise ValueError("loaded state dict contains a parameter group "
    115                              "that doesn't match the size of optimizer's group")
    116 

ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

**Comment by sgugger** [comment]
Tentative fix. Please make sure to post the issue with a full reproducible example if you want us to help. Here it's however you trained that learner before that is relevant since it doesn't manage to load the optimizer state. Tried to reproduce on my side but didn't come across a similar bug.

**Comment by kasparlund** [comment]
works fine now thx
