### ISSUE TITLE
`BrokenProcessPool` error when running Jupyter 5.6.0 notebook with Python 3.6.5

### ISSUE THREAD

**Issue by shettyprithvi** [fastai/fastai#1850]
Hi,

**Bug with description**:

I am facing an issue while executing the TextLMDataBunch function on my Jupyter notebook using Python 3.6.5

Code before error: 

import fastai
from fastai import *
from fastai.text import * 
import pandas as pd
import numpy as np
from functools import partial
import io
import os

from sklearn.datasets import fetch_20newsgroups
dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=('headers', 'footers', 'quotes'))
documents = dataset.data

df = pd.DataFrame({'label':dataset.target,
                   'text':dataset.data})
df_trn, df_val = train_test_split(df, stratify = df['label'], test_size = 0.3, random_state = 12)
df = df[df['label'].isin([1,10])]
df = df.reset_index(drop = True)

Error screenshot : ![image](https://user-images.githubusercontent.com/36528857/54726982-a7f7e580-4b32-11e9-855c-2fb0d9f74eef.png)

![image](https://user-images.githubusercontent.com/36528857/54727725-931d5100-4b36-11e9-9ee4-f3f7dfedbbb5.png)

Full error message : In the comment

**Configuration and installation** :

My Python version : 3.6.5
GPU : None
Fastai version : 1.0.50.post1
Installation steps : 
!pip install fastai

Collecting fastai
  Using cached https://files.pythonhosted.org/packages/37/25/9a07ca0e7710d97e595dd5b437324fdaeaa6812affeb8d609607e7e022e4/fastai-1.0.50.post1-py3-none-any.whl
Requirement already satisfied: pandas in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (0.23.0)
Requirement already satisfied: torch>=1.0.0 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (1.0.1)
Collecting spacy>=2.0.18 (from fastai)
  Using cached https://files.pythonhosted.org/packages/a1/26/a319ea69cd42795559927c03f1ae90e369af4b106838be5b5115d4cd83ec/spacy-2.1.1-cp36-cp36m-win_amd64.whl
Requirement already satisfied: torchvision in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (0.2.1)
Requirement already satisfied: matplotlib in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (2.2.2)
Requirement already satisfied: nvidia-ml-py3 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (7.352.0)
Requirement already satisfied: bottleneck in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (1.2.1)
Requirement already satisfied: numexpr in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (2.6.5)
Requirement already satisfied: requests in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (2.18.4)
Requirement already satisfied: beautifulsoup4 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (4.6.0)
Requirement already satisfied: fastprogress>=0.1.19 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (0.1.20)
Requirement already satisfied: scipy in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (1.1.0)
Requirement already satisfied: pyyaml in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (3.12)
Requirement already satisfied: numpy>=1.15 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (1.16.2)
Requirement already satisfied: typing in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (3.6.4)
Requirement already satisfied: Pillow in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (5.1.0)
Requirement already satisfied: packaging in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (17.1)
Requirement already satisfied: dataclasses; python_version < "3.7" in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from fastai) (0.6)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from pandas->fastai) (2.7.3)
Requirement already satisfied: pytz>=2011k in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from pandas->fastai) (2018.4)
Requirement already satisfied: plac<1.0.0,>=0.9.6 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from spacy>=2.0.18->fastai) (0.9.6)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from spacy>=2.0.18->fastai) (2.0.2)
Requirement already satisfied: jsonschema<3.0.0,>=2.6.0 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from spacy>=2.0.18->fastai) (2.6.0)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from spacy>=2.0.18->fastai) (0.28.0)
Requirement already satisfied: wasabi<1.1.0,>=0.0.12 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from spacy>=2.0.18->fastai) (0.1.4)
Requirement already satisfied: preshed<2.1.0,>=2.0.1 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from spacy>=2.0.18->fastai) (2.0.1)
Requirement already satisfied: blis<0.3.0,>=0.2.2 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from spacy>=2.0.18->fastai) (0.2.4)
Requirement already satisfied: srsly<1.1.0,>=0.0.5 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from spacy>=2.0.18->fastai) (0.0.5)
Collecting thinc<7.1.0,>=7.0.2 (from spacy>=2.0.18->fastai)
  Using cached https://files.pythonhosted.org/packages/12/b0/2c6c0f0edd87a3a4ac039bec792a61603233901a6df53e976d746eb86d04/thinc-7.0.4-cp36-cp36m-win_amd64.whl
Requirement already satisfied: six in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from torchvision->fastai) (1.11.0)
Requirement already satisfied: cycler>=0.10 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib->fastai) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib->fastai) (2.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib->fastai) (1.0.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from requests->fastai) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from requests->fastai) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from requests->fastai) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from requests->fastai) (2018.4.16)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from thinc<7.1.0,>=7.0.2->spacy>=2.0.18->fastai) (4.23.4)
Requirement already satisfied: setuptools in c:\users\i870648\appdata\local\continuum\anaconda3\lib\site-packages (from kiwisolver>=1.0.1->matplotlib->fastai) (39.1.0)
Installing collected packages: thinc, spacy, fastai
  Found existing installation: thinc 6.10.2
    Uninstalling thinc-6.10.2:
      Successfully uninstalled thinc-6.10.2
  Found existing installation: spacy 2.0.11
    Uninstalling spacy-2.0.11:
      Successfully uninstalled spacy-2.0.11
Successfully installed fastai-1.0.50.post1 spacy-2.1.1 thinc-7.0.4

![image](https://user-images.githubusercontent.com/36528857/54727075-1dfc4c80-4b33-11e9-9107-3a51bf0f7f5a.png)

Windows version : 10

I tried to look at the documentation and also this link but the solution didn't work : https://stackoverflow.com/questions/43836876/processpoolexecutor-works-on-ubuntu-but-fails-with-brokenprocesspool-when-r

**Expected behavior:** 

I'm assuming there seems to be some issue with multiprocessing. But, this should be working with Windows, at least it used to.

It would be great if you can help me out with this issue :)

Thanks!

**Comment by shettyprithvi** [comment]
The full error message: 

BrokenProcessPool Traceback (most recent call last)
in ()
1 # Language model data
----> 2 data_lm = TextLMDataBunch.from_df(train_df = df_trn, valid_df = df_val, path = "")
3
4 # Classifier model data
5 data_clas = TextClasDataBunch.from_df(path = "", train_df = df_trn, valid_df = df_val, vocab=data_lm.train_ds.vocab, bs=32)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\text\data.py in from_df(cls, path, train_df, valid_df, test_df, tokenizer, vocab, classes, text_cols, label_cols, label_delim, chunksize, max_vocab, min_freq, mark_fields, include_bos, include_eos, **kwargs)
200 src = ItemLists(path, TextList.from_df(train_df, path, cols=text_cols, processor=processor),
201 TextList.from_df(valid_df, path, cols=text_cols, processor=processor))
--> 202 if cls==TextLMDataBunch: src = src.label_for_lm()
203 else: src = src.label_from_df(cols=label_cols, classes=classes, label_delim=label_delim)
204 if test_df is not None: src.add_test(TextList.from_df(test_df, path, cols=text_cols))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\data_block.py in _inner(*args, **kwargs)
463 self.valid = fv(*args, from_item_lists=True, **kwargs)
464 self.class = LabelLists
--> 465 self.process()
466 return self
467 return _inner

~\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\data_block.py in process(self)
517 "Process the inner datasets."
518 xp,yp = self.get_processors()
--> 519 for ds,n in zip(self.lists, ['train','valid','test']): ds.process(xp, yp, name=n)
520 #progress_bar clear the outputs so in some case warnings issued during processing disappear.
521 for ds in self.lists:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\data_block.py in process(self, xp, yp, name)
694 p.warns = []
695 self.x,self.y = self.x[~filt],self.y[~filt]
--> 696 self.x.process(xp)
697 return self
698

~\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\data_block.py in process(self, processor)
73 if processor is not None: self.processor = processor
74 self.processor = listify(self.processor)
---> 75 for p in self.processor: p.process(self)
76 return self
77

~\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\text\data.py in process(self, ds)
292 tokens = []
293 for i in progress_bar(range(0,len(ds),self.chunksize), leave=False):
--> 294 tokens += self.tokenizer.process_all(ds.items[i:i+self.chunksize])
295 ds.items = tokens
296

~\AppData\Local\Continuum\anaconda3\lib\site-packages\fastai\text\transform.py in process_all(self, texts)
118 if self.n_cpus <= 1: return self._process_all_1(texts)
119 with ProcessPoolExecutor(self.n_cpus) as e:
--> 120 return sum(e.map(self._process_all_1, partition_by_cores(texts, self.n_cpus)), [])
121
122 class Vocab():

~\AppData\Local\Continuum\anaconda3\lib\concurrent\futures\process.py in _chain_from_iterable_of_lists(iterable)
364 careful not to keep references to yielded objects.
365 """
--> 366 for element in iterable:
367 element.reverse()
368 while element:

~\AppData\Local\Continuum\anaconda3\lib\concurrent\futures_base.py in result_iterator()
584 # Careful not to keep a reference to the popped future
585 if timeout is None:
--> 586 yield fs.pop().result()
587 else:
588 yield fs.pop().result(end_time - time.time())

~\AppData\Local\Continuum\anaconda3\lib\concurrent\futures_base.py in result(self, timeout)
430 raise CancelledError()
431 elif self._state == FINISHED:
--> 432 return self.__get_result()
433 else:
434 raise TimeoutError()

~\AppData\Local\Continuum\anaconda3\lib\concurrent\futures_base.py in __get_result(self)
382 def __get_result(self):
383 if self._exception:
--> 384 raise self._exception
385 else:
386 return self._result

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by sgugger** [comment]
That's the part where Windows support is flunky. You should try to do the same thing with `defaults.cpus=1` to remove the multiprocessing. If you have an error in your data, you will get a clearer error message then you can do it again with multiproc.
If you don't have an error, it'll just be slower than the multiproc version.

**Comment by sgugger** [comment]
Also, you could try again if it ends up your data has no problem after a run on a single process as it may have been linked to #1846

**Comment by shettyprithvi** [comment]
@sgugger Can you please guide me on exactly where and which file do you set defaults.cpus=1?
Thanks :)

**Comment by sgugger** [comment]
Just type it in the cell before your `DataBunch` creation.

**Comment by shettyprithvi** [comment]
Thanks a lot @sgugger !

**Comment by maynayak** [comment]
Thank you @sgugger it solved my problem as well

from fastai.text import *
import numpy as np
from sklearn.model_selection import train_test_split
import pickle
import sentencepiece as spm
import re
import pdb
defaults.cpus=1
