### ISSUE TITLE
too many values to unpack (expected 2) on learn.show_results

### ISSUE THREAD

**Issue by relax94** [fastai/fastai#1859]
I am working on object detection functionality and I have some problems.

```text
=== Software === 
python        : 3.6.7
fastai        : 1.0.49
fastprogress  : 0.1.20
torch         : 1.0.1.post2
nvidia driver : 410.79
torch cuda    : 10.0.130 / is available
torch cudnn   : 7402 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11441MB | Tesla K80

=== Environment === 
platform      : Linux-4.14.79+-x86_64-with-Ubuntu-18.04-bionic
distro        : #1 SMP Wed Dec 19 21:19:13 PST 2018
conda env     : Unknown
python        : /usr/bin/python3
sys.path      : 
/env/python
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/usr/local/lib/python3.6/dist-packages/IPython/extensions
/root/.ipython
```
So I prepare my data for ObjectDetection Task
``fn2bbox = {jj['fileName']: [[anno2bbox(jj)], [jj['label']]] for jj in j}``
``path2fn = lambda path: str(path).split('/')[-1]``
``get_y_func = lambda o: fn2bbox[path2fn(o)]``

Create simple databunch

``data = (ObjectItemList.from_folder('/content/2ODataset/train')``
        `` .split_by_rand_pct()``
         ``.label_from_func(get_y_func)``
         ``.databunch(bs=16, collate_fn=bb_pad_collate)``
         ``.normalize(imagenet_stats))``

And after the training process, I am pushing ``learn.show_results(rows=3, fig_size=(5,5))`` command and see error

Trace 

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-135-f85a727d2a0e> in <module>()
----> 1 learn.show_results(rows=3, fig_size=(5,5))

/usr/local/lib/python3.6/dist-packages/fastai/basic_train.py in show_results(self, ds_type, rows, **kwargs)
    401         if has_arg(ds.y.reconstruct, 'x'):
    402             ys = [ds.y.reconstruct(grab_idx(y, i), x=x) for i,x in enumerate(xs)]
--> 403             zs = [ds.y.reconstruct(z, x=x) for z,x in zip(preds,xs)]
    404         else :
    405             ys = [ds.y.reconstruct(grab_idx(y, i)) for i in range(n_items)]

/usr/local/lib/python3.6/dist-packages/fastai/basic_train.py in <listcomp>(.0)
    401         if has_arg(ds.y.reconstruct, 'x'):
    402             ys = [ds.y.reconstruct(grab_idx(y, i), x=x) for i,x in enumerate(xs)]
--> 403             zs = [ds.y.reconstruct(z, x=x) for z,x in zip(preds,xs)]
    404         else :
    405             ys = [ds.y.reconstruct(grab_idx(y, i)) for i in range(n_items)]

/usr/local/lib/python3.6/dist-packages/fastai/vision/data.py in reconstruct(self, t, x)
    358 
    359     def reconstruct(self, t, x):
--> 360         (bboxes, labels) = t
    361         if len((labels - self.pad_idx).nonzero()) == 0: return
    362         i = (labels - self.pad_idx).nonzero().min()

ValueError: too many values to unpack (expected 2)
```

I understand that this error produced because we cannot have ``label_cls`` param in ``label_from_func(get_y_func, label_cls=?)``. How can I fix this and could you please provide some example or help for ``label_cls`` param definition? 

Thanks.

**Comment by sgugger** [comment]
No, this isn't linked to a `label_cls` parameter. If you want `Learner.show_results` to work, your model has to give an output that is exactly of the same format as the targets are, so a tensor of (potentially padded) `bboxes` and `labels`. (Note that `data.show_batch()` uses the same functions and should work properly.)

Otherwise you should use the model by yourself to draw the results as you want.
