### ISSUE TITLE
Error installing fastai from anaconda channel fastai

### ISSUE THREAD

**Issue by FrankCreen** [fastai/fastai#1871]
Hello,

I am having some issue with conda version 4.5.12.

Please see the error below.

Any ideas?

Best regards,
Chen

frank@frank-UNIX:~$ conda install -c pytorch -c fastai fastai
Solving environment: done

## Package Plan ##

  environment location: /home/frank/anaconda3

  added / updated specs: 
    - fastai

The following NEW packages will be INSTALLED:

    cudatoolkit:   10.0.130-0                                   
    cymem:         2.0.2-py37hfd86e86_0                         
    dataclasses:   0.6-py_0                              fastai 
    dill:          0.2.9-py37_0                                 
    fastai:        1.0.50.post1-1                        fastai 
    fastprogress:  0.1.20-py_0                           fastai 
    msgpack-numpy: 0.4.3.2-py37_0                               
    murmurhash:    1.0.2-py37he6710b0_0                         
    ninja:         1.9.0-py37hfd86e86_0                         
    nvidia-ml-py3: 7.352.0-py_0                          fastai 
    plac:          0.9.6-py37_0                                 
    preshed:       2.0.1-py37he6710b0_0                         
    pytorch:       1.0.1-py3.7_cuda10.0.130_cudnn7.4.2_2 pytorch
    regex:         2018.01.10-py37h14c3975_1000          fastai 
    spacy:         2.0.18-py37hf484d3e_1000              fastai 
    thinc:         6.12.1-py37h637b7d7_1000              fastai 
    torchvision:   0.2.2-py_3                            pytorch
    typing:        3.6.4-py37_0                                 
    ujson:         1.35-py37h14c3975_0                          

The following packages will be UPDATED:

    conda:         4.5.12-py37_0                                 --> 4.6.8-py37_0

Proceed ([y]/n)? y

Preparing transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/frank/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/home/frank/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/home/frank/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/frank/anaconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "/home/frank/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 253, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/home/frank/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 282, in handle_txn
        unlink_link_transaction.execute()
      File "/home/frank/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 223, in execute
        self.verify()
      File "/home/frank/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 46, in decorated
        return f(*args, **kwds)
      File "/home/frank/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 200, in verify
        self.prepare()
      File "/home/frank/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 192, in prepare
        stp.remove_specs, stp.update_specs)
      File "/home/frank/anaconda3/lib/python3.7/site-packages/conda/core/link.py", line 282, in _prepare
        mkdir_p(transaction_context['temp_dir'])
      File "/home/frank/anaconda3/lib/python3.7/site-packages/conda/gateways/disk/__init__.py", line 60, in mkdir_p
        makedirs(path)
      File "/home/frank/anaconda3/lib/python3.7/os.py", line 221, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: '/home/frank/anaconda3/.condatmp'

`$ /home/frank/anaconda3/bin/conda install -c pytorch -c fastai fastai`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/frank/anaconda3/bin/conda
             CONDA_PREFIX=/home/frank/anaconda3
    CONDA_PROMPT_MODIFIER=
         CONDA_PYTHON_EXE=/home/frank/anaconda3/bin/python
               CONDA_ROOT=/home/frank/anaconda3
              CONDA_SHLVL=1
            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
                     PATH=/home/frank/anaconda3/bin:/home/frank/bin:/home/frank/.local/bin:/usr/
                          local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/us
                          r/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
               http_proxy=<set>
              https_proxy=<set>

     active environment : base
    active env location : /home/frank/anaconda3
            shell level : 1
       user config file : /home/frank/.condarc
 populated config files : 
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : /home/frank/anaconda3  (read only)
           channel URLs : https://conda.anaconda.org/pytorch/linux-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/fastai/linux-64
                          https://conda.anaconda.org/fastai/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/frank/anaconda3/pkgs
                          /home/frank/.conda/pkgs
       envs directories : /home/frank/.conda/envs
                          /home/frank/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/4.15.0-46-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

**Comment by stas00** [comment]
This is not a fastai issue, but something is wrong with your conda setup

> PermissionError: [Errno 13] Permission denied: '/home/frank/anaconda3/.condatmp'

What's your:

`ls -l /home/frank | grep anaconda3`

Make sure it's writable/executable. Try `chmod u+xrw /home/frank/anaconda3`

Also check if perhaps you already have `/home/frank/anaconda3/.condatmp` and it's not writable, do the same as above to fix it if it's.

**Comment by stas00** [comment]
If it's still an issue, let's continue troubleshooting it at this dedicated forum thread:
http://forums.fast.ai/t/fastai-v1-install-issues-thread/24111

**Comment by FrankCreen** [comment]
@stas00 OK,thank you.
