### ISSUE TITLE
learn.lr_find() uses the wrong GPU

### ISSUE THREAD

**Issue by marcdumon** [fastai/fastai#1878]
When I select my 2nd gpu with `torch.cuda.set_device(1)`  and run `learn.lr_find()` it starts with using the correct 2nd gpu but at the end of the process it suddenly start using the 1st gpu.  
A workaround is to select the gpu with: 
```
torch.cuda.set_device(1)   
torch_core.defaults.device = torch.device('cuda',1)
```
When I use that then lr_find stay's on the correct gpu. 
I'm using fastai v. 1.0.48 and pytorch 1.0.0

**Comment by sgugger** [comment]
This has been fixed since then, please try again with the most recent version (1.0.50) and reopen if the problem persists.

Normally now, after doing `torch.cuda.set_device(1) `, your `defaults.device` should point to that device.
