### ISSUE TITLE
Error in the documentation for _cl_int_plot_top_losses

### ISSUE THREAD

**Issue by tal-yifat** [fastai/fastai#1892]
I believe there is a documentation error in _cl_int_plot_top_losses, and the comment:
`"Show images in 'top_losses' along with their prediction, actual, loss, and probability of **predicted** class." `
should be changed to:
`"Show images in 'top_losses' along with their prediction, actual, loss, and probability of **actual** class."
`

**Comment by sgugger** [comment]
Thanks! Next time you can suggest a PR directly to fix the mistake ;)
