### ISSUE TITLE
Weird syntax for symmetric_warp

### ISSUE THREAD

**Issue by RohitMidha23** [fastai/fastai#1894]
I'm not sure if this is how it's supposed to be but this sure does seem weird for syntax.
This screenshot has been taken from the fast.ai website from Chrome browser. 
![Screenshot 2019-03-29 at 1 14 10 AM](https://user-images.githubusercontent.com/38888530/55188353-33bbe280-51c1-11e9-86c0-a14b3f0d1ae8.png)
I would be happy to fix it if someone could point out where the doc for this is generated.

**Comment by stas00** [comment]
looks like a bug in the doc converter, 
affects at least:
* https://docs.fast.ai/vision.transform.html#_symmetric_warp
* https://docs.fast.ai/vision.transform.html#_perspective_warp
@bearpelican, can you please have a look? The source looks correct, but once it's converted it gets messed up.

**Comment by RohitMidha23** [comment]
Can I work on this issue? First time trying it out but I would love to try!

**Comment by stas00** [comment]
Yes, of course, @RohitMidha23.

First you need to set things up: https://docs.fast.ai/gen_doc_main.html#building-the-documentation-website

Then learn how to build the docs:
https://docs.fast.ai/gen_doc_main.html#process-for-contributing-to-the-docs

Then you can look at the code under `fastai/gen_doc/` to identify where things go wrong in the doc generator.

@bearpelican developed most of it, so you may have to ask him questions if you get stuck and he is up for helping you and not just fixing it himself.

**Comment by RohitMidha23** [comment]
That's amazing! 
Thanks for linking me to the resources. I'll get started ASAP.

**Comment by RohitMidha23** [comment]
@stas00 from what I was able to gather the syntax in the metadata of the notebook should look like : 
```
> <code>symmetric_warp</code>(**`c`**, **`magnitude`**:<code>partial(</code>[`uniform`](/torch_core.html#uniform), `k=`4<code>)</code>=**`0`**, **`invert`**=**`False`**) → [`Image`](/vision.image.html#Image) :: [`TfmCoord`](/vision.image.html#TfmCoord)\n 
```
to generate : 
> <code>symmetric_warp</code>(**`c`**, **`magnitude`**:<code>partial(</code>[`uniform`](/torch_core.html#uniform), `k=`4<code>)</code>=**`0`**, **`invert`**=**`False`**) → [`Image`](/vision.image.html#Image) :: [`TfmCoord`](/vision.image.html#TfmCoord)\n

But the notebook metadata currently is : 
```     
> <code>symmetric_warp</code>(**`c`**, **`magnitude`**:<code>partial(</code>[`uniform`](/torch_core.html#uniform), `k=`4``<code>)</code>=***`0`***, **`invert`**=***`False`***) → [`Image`](/vision.image.html#Image) :: [`TfmCoord`](/vision.image.html#TfmCoord)\n
```
 which generates the issue. 

Working on finding the function that does this now. @bearpelican if you can point me to that it'll be massively helpful!

**Comment by stas00** [comment]
Yes, an extraneous \'\' and 2 \*\*\*
```
***`0`***
***`False`***
```

I have no idea how it came to be. @bearpelican is the magician in charge! ;)

**Comment by RohitMidha23** [comment]
@stas00 I'm able to get rid of the ***. Minor change in `format_param`, yes. 
If we remove `code_esc()` from [here](https://github.com/fastai/fastai/blob/35b640d45963967e8b0202e7223c054d56f3b1e4/fastai/gen_doc/nbdoc.py#L34) to make it just `if include_bt: arg_name` it works. However I'm not too sure what `include_bt` stands for so I hope @bearpelican can clarify that and then I'll make a PR.

**Comment by stas00** [comment]
I think that `***` is there by design, but I don't know why. Is it `**` + `*` bold+italic? 
It was added in this PR: https://github.com/fastai/fastai/pull/1515 fixing the backticks which weren't getting rendered.

Also we should probably stick to a clean markdown so also replacing `<code>` with \` everywhere:  e.g now we have a mix of both: ` <code>symmetric_warp</code>(**`c`**, **`magnitude`**:<code>partial(</code>[`

**Comment by RohitMidha23** [comment]
> I think that `***` is there by design, but I don't know why. Is it `**` + `*` bold+italic?
> It was added in this PR: #1515 fixing the backticks which weren't getting rendered.

@stas00 you're right, I hadn't thought of that. I've fixed it in that case also. The only other problem now would be the extra `` . 

> Also we should probably stick to a clean markdown so also replacing `<code>` with ` everywhere: e.g now we have a mix of both: ` <code>symmetric_warp</code>(**`c`**, **`magnitude`**:<code>partial(</code>[`

I'll look into that as well, shouldn't be too much of a problem.

**Comment by RohitMidha23** [comment]
@stas00 I figured it out to an extent. 
In this line [here](https://github.com/fastai/fastai/blob/62834a277a266c48ebb5e5828e0cca0c36fe86d6/fastai/gen_doc/nbdoc.py#L62) we call `link_type(v)`. For perspective_warp, `size = 8` is the second argument. So when we call `link_type(v)` it gives 8 back as `8`. And now in that line, k = `8`. The problem arises when we call `link_type(v)` again in the next [line](https://github.com/fastai/fastai/blob/62834a277a266c48ebb5e5828e0cca0c36fe86d6/fastai/gen_doc/nbdoc.py#L63). This returns it with an extra \`.
Therein lies our problem. 
Further what has been missed out is that k is actually `size` and hence we should be calling link_type for `k` too. Thereby making this [line](https://github.com/fastai/fastai/blob/62834a277a266c48ebb5e5828e0cca0c36fe86d6/fastai/gen_doc/nbdoc.py#L62) : 
```python 
args = (t.func,) + t.args + tuple([f'{link_type(k)}={link_type(v)}' for k,v in t.keywords.items()])
```
However by following the logic above we get a pair of extra \` which surround the `=`. 
Hence our output looks like : 
![Screenshot 2019-03-30 at 3 05 31 AM](https://user-images.githubusercontent.com/38888530/55263946-bebbdc00-5298-11e9-920d-1cdf79555c4b.png)

With the current code, the simplest solution would be to change this [line](https://github.com/fastai/fastai/blob/62834a277a266c48ebb5e5828e0cca0c36fe86d6/fastai/gen_doc/nbdoc.py#L62) to : 
```python
args = (t.func,) + t.args + tuple([f'{k}={v}' for k,v in t.keywords.items()])
```
Hence our output would look like : 
![Screenshot 2019-03-30 at 3 08 27 AM](https://user-images.githubusercontent.com/38888530/55264357-0c851400-529a-11e9-807a-16f8578b68b8.png)

**Comment by stas00** [comment]
Without looking at the outcome of this proposed change, if you are removing some function call, most likely it's going to affect every other situation where there are no nested default values - which is 99% of cases. Perhaps the code could detect that it's a nested definition and encode it as an independent string?

**Comment by RohitMidha23** [comment]
@stas00 again, you're right. I was just looking into that.

**Comment by RohitMidha23** [comment]
@stas00 correct me if I'm wrong and I know this is slightly naive but the function `partial_repr` is called only when the object has instance `partial` as can be seen by this [line](https://github.com/fastai/fastai/blob/255ebe536659a70d7b09dc0d5831fd6331bf6253/fastai/gen_doc/nbdoc.py#L51). 

The thing to note is that nearly 5 functions seem to have `partial` as part of them. When I changed the `nbdoc` code to the above proposed code, the nbdiff shows that the notebook had changed only in our two oddities. 

The reason for this is the fact that none of the second/third arguments used in partial in the 5 functions have a link anywhere (as they are numbers). 

The nbdiff for the changes made can be seen here : 
![Screenshot 2019-03-30 at 4 28 40 AM](https://user-images.githubusercontent.com/38888530/55266693-5246da00-52a4-11e9-977f-4db7141fa30a.png)

**Comment by RohitMidha23** [comment]
@stas00 correct me if I'm wrong and I know this is slightly naive but the function `partial_repr` is called only when the object is of instance `partial` as can be seen from this [line](https://github.com/fastai/fastai/blob/255ebe536659a70d7b09dc0d5831fd6331bf6253/fastai/gen_doc/nbdoc.py#L51). 

The thing to note is that only 5 functions use `partial` in their methods. All of these functions have integer arguments as their second and third arguments and hence the function `link_type` is of no use for this particular function, from my understanding. 

When I changed the code in `nbdoc` as I proposed above and built the docs, the `nbdiff` showed only two changes, for `perspective_warp` and `symmetric_warp`. 

The output of nbdiff I got was : 
![Screenshot 2019-03-30 at 4 28 40 AM](https://user-images.githubusercontent.com/38888530/55267326-8c65ab00-52a7-11e9-9c2b-f9142ac96ead.png)

**Comment by stas00** [comment]
Yes, you found a bug - it should have been `{k}` and not 'k'! Good one, @RohitMidha23 

So what you're proposing is this:
```
diff --git a/fastai/gen_doc/nbdoc.py b/fastai/gen_doc/nbdoc.py
index 1876e4ba..5daf55bb 100644
--- a/fastai/gen_doc/nbdoc.py
+++ b/fastai/gen_doc/nbdoc.py
@@ -59,7 +59,7 @@ def type_repr(t):
     else: return link_type(t)

 def partial_repr(t):
-    args = (t.func,) + t.args + tuple([f'k={link_type(v)}' for k,v in t.keywords.items()])
+    args = (t.func,) + t.args + tuple([f'{k}={v}' for k,v in t.keywords.items()])
     reprs = ', '.join([link_type(o) for o in args])
     return f'<code>partial(</code>{reprs}<code>)</code>'
```
I rebuilt all nbs and indeed only these 2 entries got modified and they look correct now.

Excellent job, @RohitMidha23. 

So next please submit a PR https://docs.fast.ai/dev/git.html#how-to-make-a-pull-request-pr and we will merge it and fix the broken docs.
