### ISSUE TITLE
xception.py TypeError  

### ISSUE THREAD

**Issue by itLek** [fastai/fastai#1896]
fastai/fastai/vision/models/xception.py

run
`learn = cnn_learner(data, xception, pretrained=True, metrics=accuracy, model_dir='.',)`

> 
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-22-6372ff58f874> in <module>()
> ----> 1 learn = cnn_learner(data, xception, pretrained=True, metrics=accuracy, model_dir='.',)
> 
> /opt/conda/lib/python3.6/site-packages/fastai/vision/learner.py in cnn_learner(data, base_arch, cut, pretrained, lin_ftrs, ps, custom_head, split_on, bn_final, init, concat_pool, **kwargs)
>      95     meta = cnn_config(base_arch)
>      96     model = create_cnn_model(base_arch, data.c, cut, pretrained, lin_ftrs, ps=ps, custom_head=custom_head,
> ---> 97         split_on=split_on, bn_final=bn_final, concat_pool=concat_pool)
>      98     learn = Learner(data, model, **kwargs)
>      99     learn.split(split_on or meta['split'])
> 
> /opt/conda/lib/python3.6/site-packages/fastai/vision/learner.py in create_cnn_model(base_arch, nc, cut, pretrained, lin_ftrs, ps, custom_head, split_on, bn_final, concat_pool)
>      81         split_on:Optional[SplitFuncOrIdxList]=None, bn_final:bool=False, concat_pool:bool=True):
>      82     "Create custom convnet architecture"
> ---> 83     body = create_body(base_arch, pretrained, cut)
>      84     if custom_head is None:
>      85         nf = num_features_model(nn.Sequential(*body.children())) * 2
> 
> /opt/conda/lib/python3.6/site-packages/fastai/vision/learner.py in create_body(arch, pretrained, cut)
>      53 def create_body(arch:Callable, pretrained:bool=True, cut:Optional[Union[int, Callable]]=None):
>      54     "Cut off the body of a typically pretrained `model` at `cut` (int) or cut the model as specified by `cut(model)` (function)."
> ---> 55     model = arch(pretrained)
>      56     cut = ifnone(cut, cnn_config(arch)['cut'])
>      57     if cut is None:
> 
> /opt/conda/lib/python3.6/site-packages/fastai/vision/models/xception.py in xception(c, k, n_middle)
>      56         nn.AdaptiveAvgPool2d(1),
>      57         Flatten(),
> ---> 58         nn.Linear(k*256,c)
>      59     ]
>      60     return nn.Sequential(*layers)
> 
> /opt/conda/lib/python3.6/site-packages/torch/nn/modules/linear.py in __init__(self, in_features, out_features, bias)
>      49         self.in_features = in_features
>      50         self.out_features = out_features
> ---> 51         self.weight = Parameter(torch.Tensor(out_features, in_features))
>      52         if bias:
>      53             self.bias = Parameter(torch.Tensor(out_features))
> 
> TypeError: new() received an invalid combination of arguments - got (bool, int), but expected one of:
>  * (torch.device device)
>  * (torch.Storage storage)
>  * (Tensor other)
>  * (tuple of ints size, torch.device device)
>       didn't match because some of the arguments have invalid types: (!bool!, !int!)
>  * (object data, torch.device device)
>       didn't match because some of the arguments have invalid types: (!bool!, !int!)

run in kaggle kernels

resnet50 work fine

**Comment by sgugger** [comment]
As mentioned in the [docstring](https://github.com/fastai/fastai/blob/7d0ca5152c0af43dd195988cdc7efa0c772bd1db/fastai/vision/models/xception.py#L42), there is no pretrained model for this, it's experimental. So you can't use it with `conv_learner`.
