### ISSUE TITLE
[Feature Request] Datasets config

### ISSUE THREAD

**Issue by tydlwav** [fastai/fastai#1898]
**Feature Request**

Separate configs in config.yml for downloaded data and untar destination. 

**Justification**

I am running on my own desktop machine and I have an SSD for fast file storage, but I use a harddrive for archiving purposes and files that I don't need all the time. To not use too much space on my SSD, I usually save my data on the HDD as a compressed file and then decompress them onto my SSD when I need them. This way, I can easily delete the whole data directory when I need to free up space. 

To achieve this purpose, I need to set the config.yml data directory to my HDD and then specifically declare dest="SOMEWHERE/ON/MY/SSD" when running notebooks. This is not so convenient and the trivial issue should be solved with less than 10 lines of code to get a quality of life improvement. 

**I'm willing to help**

Hopefully you guys can consider this. I'm willing to fork, change the code and docs and submit a pull request if you guys approve of this.

**Comment by stas00** [comment]
Looks like a useful feature to me. I think your situation would be quite common for large datasets.

Needless to say, but the default should remain as it is now (shared folder).

But let's wait for @sgugger to double check before you proceed. Thank you, @tydlwav

**Comment by sgugger** [comment]
Hi there. This could be a useful feature for some users, yes. It's not going to be on our priority list for now but if you're willing to tackle it, we'll gladly look at a PR. I'm closing this here as issues are for standing bugs only, but I've created a topic on the forum to continue the discussion if needed.

**Comment by tydlwav** [comment]
Sure. I'll look into writing an implementation and adding it to the docs. I'll shoot up a PR when I'm done.
