### ISSUE TITLE
Minor typo / error in `fit()` method assertion error

### ISSUE THREAD

**Issue by HamsterHuey** [fastai/fastai#1900]
In this line:
https://github.com/fastai/fastai/blob/255ebe536659a70d7b09dc0d5831fd6331bf6253/fastai/basic_train.py#L87

The values in the f-string should be `learn.data.train_dl...`. In both instances, the `learn.` prefix is missing and this assertion error would instead result in a different error when raised.

Nothing major, but figured I'd draw attention to this as it is a super-quick fix.

**Comment by stas00** [comment]
Thank you, @HamsterHuey. 

Fixed @ https://github.com/fastai/fastai/commit/e5693f6d34d0564c24c5f9db48cbd1c36c29d9ef

In the future also please don't hesitate to submit a PR https://docs.fast.ai/dev/git.html#how-to-make-a-pull-request-pr
