### ISSUE TITLE
How can I use multi-item loss

### ISSUE THREAD

**Issue by f-sky** [fastai/fastai#1902]
My loss consists of many losses,such as loss=l1+l2, now I want to inspect not only loss during training but also l1 and l2. How can I do that?

**Comment by sgugger** [comment]
There is a `LossMetrics` callback. You just have to use it when the loss function of your `Learner` has an attribute `metric_names` (for the names of l1 and l2) and updates in `forward` an attribute `metrics` (to contain the values of l1 and l2).

There is an example with `FeatureLoss` in [this notebook](https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson7-superres.ipynb).
