### ISSUE TITLE
Data Block API split_none and label_empty combination

### ISSUE THREAD

**Issue by pYtoner** [fastai/fastai#1908]
**Describe the bug**
In the Data Block API;
Using both `.split_none()` and `.label_empty()` throws an exception that tells you to use `.split_none()`.

**Provide your installation details**
```text
=== Software === 
python        : 3.6.8
fastai        : 1.0.50.post1
fastprogress  : 0.1.20
torch         : 1.0.1.post2
nvidia driver : 418.56
torch cuda    : 10.0.130 / is available
torch cudnn   : 7402 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11177MB | GeForce GTX 1080 Ti

=== Environment === 
platform      : Linux-4.15.0-47-generic-x86_64-with-debian-buster-sid
distro        : #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019
conda env     : fastai
python        : /home/no1/anaconda3/envs/fastai/bin/python
sys.path      : 
/home/no1/anaconda3/envs/fastai/lib/python36.zip
/home/no1/anaconda3/envs/fastai/lib/python3.6
/home/no1/anaconda3/envs/fastai/lib/python3.6/lib-dynload
/home/no1/.local/lib/python3.6/site-packages
/home/no1/anaconda3/envs/fastai/lib/python3.6/site-packages
```

**To Reproduce**
https://gist.github.com/pYtoner/cefa15b5a3a275237978569260fd8521

**Expected behavior**
No exception.

**Additional Details**
https://github.com/fastai/fastai/issues/1852#issuecomment-475397096
was not a fix for this issue

**Comment by sgugger** [comment]
Yup, this has been fixed in master and will be in the next release (double checked with your gist). Note that you can't see it until v1.0.51 is out unless you do a developer install with
```
pip install -e .[dev]
```
inside the fastai repo (it would show v1.0.51dev in `show_install`).
