### ISSUE TITLE
trying to replicate code

### ISSUE THREAD

**Issue by ggdhines** [fastai/fastai#1909]
Hi,

I just spent a good amount of time trying to sign up to the fast.ai forums and post a question but the process for how to do a new post is completely unclear. So apologies if this post should be on the forum.

I'm using version 1.0.34 and trying to follow along with the code at this tutorial https://github.com/prrao87/tweet-stance-prediction/blob/master/ulmfit.ipynb (this is definitely not an official tutorial). The line 
```
 learn = language_model_learner(data_lm, pretrained_model=URLs.WT103_1)
```

gives me the error

```
 RuntimeError: you can only change requires_grad flags of leaf variables. If you want to use a computed variable in a subgraph that doesn't require differentiation use var_no_grad = var.detach().
```

Any suggestions?

**Comment by sgugger** [comment]
It's hard to say without saying the whole code but I have seen this error pop up with older version of PyTorch. Make sure you're using pytorch v1 or v1.0.1 and fastai v1.0.50 or later, then reopen with more details if the bug persists.

For the forum, you have to read for at least 10 minutes before being allowed to post I believe.
