### ISSUE TITLE
callback stopping issues

### ISSUE THREAD

**Issue by stas00** [fastai/fastai#1913]
there are 2 issues with callback stopping

1. a minor one, it runs one extra batch after being told to stop:

In `fastai/callbacks/misc.py` add a debug print so it look like:

```
    def on_batch_end(self, iteration, **kwargs):
        print(f"IT {iteration}", self.n_batches)
        if iteration == self.n_batches:
            print(f"Stopping at iteration {iteration}")
            return {'stop_epoch': True, 'stop_training': True}
```

now enable the printout of `cs.out` in `tests/test_callbacks_misc.py` (uncomment `# print(cs.out)` and run it:
`pytest -sv tests/test_callbacks_misc.py`

you will see 
```
collecting ...
epoch     train_loss  valid_loss  time
IT 0 1
IT 1 1
Stopping at iteration 1
IT 2 1
0         -0.823743   -0.129145   00:00

epoch     train_loss  valid_loss  time
IT 0 1
IT 1 1
Stopping at iteration 1
IT 2 1
0         -0.275073   0.380975    00:00
```

So `on_batch_end` runs one too many times.

Testing `len(learn.recorder.losses)` doesn't catch that.

2. If I add to `lesson7-superres.ipynb`

```
from fastai.callbacks.misc import StopAfterNBatches
defaults.extra_callbacks = [StopAfterNBatches(n_batches=2)]
```
when fit is run we get:

```
IT 0 1
IT 1 1
Stopping at iteration 1
IT 2 1
IT 2 1
...
IT 2 1
IT 2 1
```
so that's not quite `StopAfterNBatches(n_batches=2)`

So it works almost correctly with a single model, but doesn't quite handle it with 2 concurrent models.

It was working fine before the last callback return API change. i.e. it indeed stopped after running 2 main batches. I guess we need to write a superres-like test to catch future breakages.

Thanks.

(p.s. this is a detailed note for Sylvain, so I didn't follow the usual protocol of env inclusion, please don't use this is a model for your Issue submissions.)

**Comment by sgugger** [comment]
Should be fixed by [this commit](https://github.com/fastai/fastai/commit/e5d0aeb69d195f135608318094745e497e2d713f).
