### ISSUE TITLE
Doc example code doesn't work

### ISSUE THREAD

**Issue by danielwpz** [fastai/fastai#1918]
**Describe the bug**

I'm playing with `collab.ipynb`, added one single line which I COPIED from the official documents and it throws an error :(

**Provide your installation details**
```text
=== Software === 
python       : 3.7.3
fastai       : 1.0.51
fastprogress : 0.1.20
torch        : 1.0.1.post2
torch cuda   : None / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Darwin-18.2.0-x86_64-i386-64bit
conda env    : fastai
python       : /anaconda3/envs/fastai/bin/python
sys.path     : /Users/daniel/Programs/fastai/examples
/anaconda3/envs/fastai/lib/python37.zip
/anaconda3/envs/fastai/lib/python3.7
/anaconda3/envs/fastai/lib/python3.7/lib-dynload

/anaconda3/envs/fastai/lib/python3.7/site-packages
/anaconda3/envs/fastai/lib/python3.7/site-packages/IPython/extensions
/Users/daniel/.ipython
no supported gpus found on this system
```
**To Reproduce**
Open `collab.ipynb` in a notebook, add this line at the bottom and run:
```
learn.predict(learn.data.train_ds[0][0])
```

it will throw:
```
KeyError                                  Traceback (most recent call last)
/anaconda3/envs/fastai/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2656             try:
-> 2657                 return self._engine.get_loc(key)
   2658             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index_class_helper.pxi in pandas._libs.index.Int64Engine._check_type()

KeyError: 'userId'
```

However, I copied this line from your doc!
https://docs.fast.ai/basic_train.html#Learner.predict
```
data = learn.data.train_ds[0][0]

pred = learn.predict(data)
```

**Expected behavior**
Show me the prediction not the error.

**Additional Message**
Correct me if I'm wrong but there is no example code in https://github.com/fastai/fastai/tree/master/examples shows you how to make prediction with a trained learner. They just shows how to train the model but **NOT** how to use it.

Why I need to train a model? Because I need to make predictions on new data! **PLEASE add how to make predictions to your example notebooks!**

Thanks

**Comment by adumont** [comment]
Hi @danielwpz , did you check in courses/ml1 subfolder? You'll find several Jupyter notebooks, and they show you with great details how to use Fast.AI.

**Comment by sgugger** [comment]
This is an open-source project, not an outlet to vent your frustration. Please be mindful of that, there is no need to capitalize words or bold-emphasis while using a patronizing tone.

That being said, I added an example on how to make a prediction in the `collab` notebook. There is also a whole [tutorial on inference](https://docs.fast.ai/tutorial.inference.html) in the docs.

**Comment by danielwpz** [comment]
hey guys thanks for replying so quick. Maybe I'm not expressing myself clearly. 

What the issue is:

The document, which is designed to be read and referred by all users, provides a line of code that is supposed to work with `Learner` base class, however in fact it doesn't work with a derived class `CollabLearner `, can we at least have some docs addressing this difference.

**Comment by adumont** [comment]
@danielwpz I've just opened https://colab.research.google.com/, opened the collab.ipynb straight from Github, and run it without any issue at all.

Seems to indicate it works fine as is. Maybe it's a problem with your python environment? 

I'd suggest you try for yourself with Google's Collaboratory. Using this link should open it directly. THen re-run every cell: https://colab.research.google.com/github/fastai/fastai/blob/master/examples/collab.ipynb .

Hopefully that should help you find the issue by comparing your environment with the setup at Collaboratory.
