### ISSUE TITLE
COCO data loading fails

### ISSUE THREAD

**Issue by attibalazs** [fastai/fastai#1919]
hi All,

I'm getting a checksum error when running the COCO examples from the docs.
I tried upgrading to the latest version but it didn't resolve the issue 
Successfully installed fastai-1.0.52.dev0

Noticed someone attempted to fix it previously in a Jan 15 commit but might have regressed since then again.

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-3-8fa59e65823c> in <module>()
----> 1 coco = untar_data(URLs.COCO_TINY)
      2 # images, lbl_bbox = get_annotations(coco/'train.json')
      3 # img2bbox = dict(zip(images, lbl_bbox))
      4 # get_y_func = lambda o:img2bbox[o.name]

/anaconda/envs/py36/lib/python3.6/site-packages/fastai/datasets.py in untar_data(url, fname, dest, data, force_download)
    231         data_archive_dir = Config().data_archive_path()
    232         if url in _checks:
--> 233             assert _check_file(fname) == _checks[url], f"Downloaded file {fname} does not match checksum expected! Remove that file from {data_archive_dir} and try your code again."
    234         tarfile.open(fname, 'r:gz').extractall(dest.parent)
    235     return dest

AssertionError: Downloaded file /home/lab-admin/.fastai/data/coco_tiny.tgz does not match checksum expected! Remove that file from /home/lab-admin/.fastai/data and try your code again.

```

Thanks

**Comment by sgugger** [comment]
This error means you don't have the latest version of the dataset. As instructed, just remove the file `coco_tiny.tgz` to trigger a new download. Just tried on master and it downloads without any issue.

**Comment by attibalazs** [comment]
i did remove the coco_tiny.tgz file, i still got the error, actually tried a few times.

**Comment by sgugger** [comment]
That is weird. Just to double-check, can you see the progress bar for the download when you remove it? Then if you do
```
from fastai.datasets import _check_file
_check_file(Config().data_path()/'coco_tiny.tgz')
```
what is the result you see?

**Comment by attibalazs** [comment]
thanks for the quick response, i was just about check the checksum on the file

this is what i get:
(7957, '5b4a3a114cbe89f2165bc1fd3d2b7244')

**Comment by sgugger** [comment]
Ok, so this is definitely wrong. The first part is the size, so it looks like it didn't download the whole thing. Can you try a manual download? Address is `http://files.fast.ai/data/examples/coco_tiny.tgz`

**Comment by attibalazs** [comment]
just tried again on my windows machine and it downloaded correctly, size and checksums match with the code, it looks like there is an issue with my linux machine i will try and get to the bottom of it. Thanks for your quick responses, hopefully this will also help others in future.

**Comment by sgugger** [comment]
Yup, please do let us know if you find the reason it didn't work!
