### ISSUE TITLE
How to specify class weights in MixedModelInput model

### ISSUE THREAD

**Issue by kickbox** [fastai/fastai#192]
I followed the notebook [here ](https://github.com/KeremTurgutlu/deeplearning/blob/master/avazu/FAST.AI%20Classification%20-%20Kaggle%20Avazu%20CTR.ipynb) to create a Classifier using MixedModelInput model.

How can I specify class weights to overcome class imbalance problems?

In the case of a binary classification problem, I tried the following after reviewing the documentation with no success. 

```
----> 5 learn.crit = F.cross_entropy(weight=[.1,.99])
      6 learn.crit
```
`
TypeError: cross_entropy() missing 2 required positional arguments: 'input' and 'target'`

Can you point me towards the right place to set the weights to overcome class imbalance issues?

**Comment by jph00** [comment]
Please use the forums.
