### ISSUE TITLE
TypeError: wrn_22() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by ravilkashyap** [fastai/fastai#1923]
**Describe the bug**
Unable to import and use wide resnet architecture in fastai v1

**Provide your installation details**
python        : 3.7.1
fastai        : 1.0.46
fastprogress  : 0.1.20
torch         : 1.0.1.post2
nvidia driver : 410.72
torch cuda    : 10.0.130 / is available
torch cudnn   : 7402 / is enabled

**To Reproduce**
`learn = create_cnn(data, models.wrn_22, metrics=accuracy)`

Error- TypeError: wrn_22() takes 0 positional arguments but 1 was given

**Additional context**
The model architecture expects `pretrained=Bool` argument I presume which is not defined in  fastai/vision/models/wrn.py

**Comment by sgugger** [comment]
Yes wrn is meant to be used as a standalone, and will only work on CIFAR10. It's not intended to be used in `cnn_learner`.
