### ISSUE TITLE
untar_data ignores configured value for data_path

### ISSUE THREAD

**Issue by mcsieber** [fastai/fastai#1928]
#### Description
untar_data does not use the "data_path" value in the configuration file.

**To Reproduce ... Example ... Excerpted Jupyter cells**
```
In  [5] : path = untar_data(URLs.IMDB_SAMPLE) ; path.ls()
Out [5] : [PosixPath('/Users/mcsieber/.fastai/data/imdb_sample/texts.csv')]

In  [6] : Config.data_path()
Out [6] : PosixPath('/Users/mcsieber/storage/data')

```
**Installation and Environment**
```
sys.platform =  darwin
sys.prefix   =  /Users/mcsieber/anaconda3/envs/fastai
sys.version  =  3.7.2 (default, Dec 29 2018, 00:00:04) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
fastai.version =  1.0.52.dev0
torch.version  =  1.0.1.post2
cuda_available =  False
sys.path = 
[   '/Users/mcsieber/storage/notebooks/l3_imdb',
    '/Users/mcsieber/anaconda3/envs/fastai/lib/python37.zip',
    '/Users/mcsieber/anaconda3/envs/fastai/lib/python3.7',
    '/Users/mcsieber/anaconda3/envs/fastai/lib/python3.7/lib-dynload',
    '',
    '/Users/mcsieber/anaconda3/envs/fastai/lib/python3.7/site-packages',
    '/Users/mcsieber/github/fastai',
    '/Users/mcsieber/anaconda3/envs/fastai/lib/python3.7/site-packages/IPython/extensions',
    '/Users/mcsieber/.ipython',
    '/Users/mcsieber/storage/lib']
```
Configuration file "~/.fastai/config.yml"
```
data_path: ~/storage/data
model_path: ~/storage/models
# Previous:
# data_path: ~/.fastai/data
# model_path: ~/.fastai/models
```

**Expected behavior**

I would expect the configured value to be used ... is this correct?

**Discussion**

I hope the info above, and below, helps.

I examined the source, and scanned thru the recent discussions about the "configuration" model and api.

I think the proximate cause might be that "datapath4file" checks for the existence of the
default path and, if it exists, returns that value immediately without checking for a configured value. ... ( But I could be wrong, too ... just coming up to speed on this ...)
```
def datapath4file(filename, ext:str='.tgz', archive=True):
    "Return data path to `filename`, checking locally first then in the config file."
    local_path = URLs.LOCAL_PATH/'data'/filename
    if local_path.exists() or local_path.with_suffix(ext).exists(): return local_path
    elif archive: return Config.data_archive_path() / filename
    else: return Config.data_path() / filename
```
*Also*,   the "config" discussion suggested that there is a general re-think about
the design of this piece, so any potential fault with datapath4file could be moot.

**Comment by sgugger** [comment]
The problem is that you are missing a line in your config file. Wince a recent PR, it needs to add a 
'data_archive_path' line that should point to where you want to store the archives (the behavior is still wrong since it should have been untared in your data path and not your archive path, will investigate)

**Comment by sgugger** [comment]
Fully solved this now, the archives are download the 'data_archive_path' in your config file and untarred in 'data_path'.
