### ISSUE TITLE
Output on distributed training prints "Total time:" n_gpus times

### ISSUE THREAD

**Issue by yeldarby** [fastai/fastai#1932]
Super low-priority bug. But I tried to pin it down to submit a PR and couldn't find out where this code was getting triggered.

**Describe the bug**
At the end of distributed training, "Total time: xx:xx" is printed to the console for each GPU rather than just once. The rest of the stats are silenced on GPUs other than #0 by `self.learn.recorder.silent = (self.rank != 0)` in the `distributed.py` `on_train_begin` callback.

**Provide your installation details**
```text
=== Software === 
python        : 3.7.1
fastai        : 1.0.51
fastprogress  : 0.1.20
torch         : 1.0.0
nvidia driver : 410.66
torch cuda    : 10.0.130 / is available
torch cudnn   : 7401 / is enabled

=== Hardware === 
nvidia gpus   : 8
torch devices : 8
  - gpu0      : 8119MB | GeForce GTX 1070
  - gpu1      : 8119MB | GeForce GTX 1070
  - gpu2      : 8119MB | GeForce GTX 1070
  - gpu3      : 8119MB | GeForce GTX 1070
  - gpu4      : 8119MB | GeForce GTX 1070
  - gpu5      : 8119MB | GeForce GTX 1070
  - gpu6      : 8119MB | GeForce GTX 1070
  - gpu7      : 8119MB | GeForce GTX 1070

=== Environment === 
platform      : Linux-4.15.0-46-generic-x86_64-with-debian-stretch-sid
distro        : #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019
conda env     : Unknown
python        : /opt/conda/bin/python
sys.path      : /workspace/course-v3/nbs/dl1
/opt/conda/lib/python37.zip
/opt/conda/lib/python3.7
/opt/conda/lib/python3.7/lib-dynload

/opt/conda/lib/python3.7/site-packages
/opt/conda/lib/python3.7/site-packages/IPython/extensions
/root/.ipython
```

**To Reproduce**
Run the example code from `distributed.py`

**Expected behavior**
`Total time: xx:xx` prints once at the end rather than `n_gpus` times.

**Screenshots**
![image](https://user-images.githubusercontent.com/870796/55660886-8d7e6700-57d6-11e9-868d-12220fe8d127.png)

**Additional context**
Again, super low priority. It's not hurting anything. I tried to fix it but not sure where that is being printed from (a search of the entire repo for "Total time" only finds where it's been saved in outputs rather than where it's triggered in the code).

**Comment by sgugger** [comment]
It's fixed in fastprogress master, we should do a release of that to make it more easily available :)
