### ISSUE TITLE
Doc Strings for Various Library Elements

### ISSUE THREAD

**Issue by Holisticnature** [fastai/fastai#194]
I realize this is a mundane topic, but I figured I would bring it up. The class put a large emphasis on using various notebook commands to understand the code we are running, but I noticed some of the fastai abstraction methods/classes lack doc strings. For example some of the first code we run is from [conv_learn.py](https://github.com/fastai/fastai/blob/master/fastai/conv_learner.py). I noticed both on the repo some of the parameters are not very spelled out. Some of the methods/classes do have strings with information about the class or function but not all of them. Is there a logic here or just something on the to do list?
As the one raising the issue, if pointed to the relevant materials I am willing to try to issue a pull request to put in some of these doc strings.

**Comment by jph00** [comment]
We'd love PRs! :) Thanks for the offer. What do you need from us to help you get started?

**Comment by Holisticnature** [comment]
Hi Jeremy, I have really enjoyed the class so far. The notebooks are great examples, and having the data right there for testing has been phenomenal. 

I was curious if it would be desirable to spell out docstrings of the sub-classes parameters even if its bears some repetition (**kwargs for example in ConvLearner)? 
Would you want each method also to have a doc string? 
Is there any documentation you can point me to regarding the parameters these classes are using? I was just going to check the imported libraries for this one file as a starting point if not.

**Comment by jph00** [comment]
> I was curious if it would be desirable to spell out docstrings of the sub-classes parameters even if its bears some repetition (**kwargs for example in ConvLearner)?

Yes I think so.

> Would you want each method also to have a doc string?

Yup.

> Is there any documentation you can point me to regarding the parameters these classes are using?

No, but feel free to ask on the forum if there's anything unclear.
