### ISSUE TITLE
Model_dir path changing

### ISSUE THREAD

**Issue by Hamdikap** [fastai/fastai#1943]
I am trying to change model_dir of cnn_learner . Because ıf I use default path ,its warning about read-only file system at kaggle and I want to export it to tmp/models/ . How can ı change the path or am I doing wrong ?

**Comment by charusat09** [comment]
@Hamdikap I will suggest you to use this forum for your question: https://forums.fast.ai/t/productionizing-models-thread/28353/98.

**Comment by Hamdikap** [comment]
Thanks I will try.

**Comment by sgugger** [comment]
Unless there is a reproducible bug with code, the forum is the best place to solve this, so closing this issue.
