### ISSUE TITLE
Learner.export should support MixedItemList

### ISSUE THREAD

**Issue by EtienneT** [fastai/fastai#1944]
**Describe the bug**
When fitting a model using a MixedItemList, if you export the learner using the export method, when you try to use load_learner later, it won't work if you try to have a test set.  See [discussion in forum here](https://forums.fast.ai/t/custom-itemlist-getting-forkingpickler-broken-pipe/39086/42).

**To Reproduce**
Fit a model using a MixedItemList.  Then try to export the learner using export.  Then try to load back the learner using load_learner method with the test parameter.  The method will crash while trying to reconstruct the MixedItemList because we don't pass-in the underlying ItemLists used in the MixedItemList.

Code crashing:

```
imgList = ImageList.from_df(petsTest, path=path, cols='PicturePath')
tabList = TabularList.from_df(petsTest, cat_names=cat_names, cont_names=cont_names, procs=procs, path=path)
textList = TextList.from_df(petsTest, cols='Description', path=path, vocab=vocab)

norm, denorm = normalize_custom_funcs(*imagenet_stats)

mixedTest = (MixedItemList([imgList, tabList, textList], path, inner_df=tabList.inner_df))

learn = load_learner(path, 'mixed.pkl', test=mixedTest)
```

**Expected behavior**
Learner.export should work for any type of ItemList.

**Comment by sgugger** [comment]
`MixedItemList` is a development feature that isn't officially supported yet. It was just added for you to play with, but there are some rough edges you will have to work around ;)

**Comment by EtienneT** [comment]
:'(.  Even though I could not make export work, I was able to run my code on a test set by tricking fastai in thinking it was a validation set (setting all labels of the test set to 0...) and then simply running:

`preds,y = learn.get_preds(ds_type=DatasetType.Valid)`

Thanks for your help in the forum thread!
