### ISSUE TITLE
fastai

### ISSUE THREAD

**Issue by dhekrasaeed** [fastai/fastai#1945]
I'm having  bug 
RuntimeError: cuda runtime error (30) : unknown error at C:\Anaconda2\conda-bld\pytorch_1519496000060\work\torch\lib\THC\THCGeneral.c:120
•	os: Windows 10 64 bit
•	gpu: Geforce GTX1060
•	driver versoin: 419.35
•	diver type: DCH
•	NvideaCuda: 10.1.120 driver
•	CuDNN: 7.5.0

**Comment by sgugger** [comment]
Please follow the issue template. We aren't magicians and can't help without any information.
