### ISSUE TITLE
name 'ImageDataBunch' is not defined.

### ISSUE THREAD

**Issue by ravikanth076** [fastai/fastai#1947]
im doing a fastai image classification project. i came with the above errror.
 my code went lke this in jupyter notebook.
data = ImageDataBunch.from_folder("D:\ravikanth\hands")

for that above statement , i got an error  shown below.

NameError                                 Traceback (most recent call last)
<ipython-input-6-f716f3df2d77> in <module>
----> 1 data = ImageDataBunch.from_folder("D:\ravikanth\hands")

NameError: name 'ImageDataBunch' is not defined

**Comment by alibaltschun** [comment]
please give information about the package version that you used, such as version of python, fastai, etc

**Comment by ravikanth076** [comment]
Fastai version 1.0.5.1
Python 3.7.1
Pytorch 1.0.1

**Comment by ravikanth076** [comment]
Anaconda 2018.12
Jupyter notebook 5.7.4

**Comment by alibaltschun** [comment]
did you call  `from fastai.vision import *` ?

**Comment by ravikanth076** [comment]
Yes

**Comment by sgugger** [comment]
Please follow the issue template. There is a specific command that is there and will give us all your installation information (which doesn't match what you said earlier otherwise you would have an `ImageDataBunch`).

**Comment by flydragon2018** [comment]
version upgraded. the  API names and formats are changed!!!  
compatibility is not  user-friendly.

**Comment by shyamgupta196** [comment]
something is really off!!! the old boilerplate codes doesnt seem to be working .... :(
