### ISSUE TITLE
How to check my fastai version

### ISSUE THREAD

**Issue by ravikanth076** [fastai/fastai#1948]
.....

**Comment by sgugger** [comment]
Please read and follow the issue template. the command you ask is inside it.
Also there is a thread on the [forum](https://forums.fast.ai) for installation problems.

**Comment by ChrisPalmerNZ** [comment]
As the issue template states:
```
from fastai.utils.show_install import *
show_install()
```
You can also
```
import fastai
fastai.__version__
```
