### ISSUE TITLE
Destroying a hooks callback early on causes it to fail

### ISSUE THREAD

**Issue by karthiksubraveti** [fastai/fastai#1950]
simple bug - 
Exception ignored in: <bound method HookCallback.__del__ of ActivationStats
learn: None
modules: None
do_remove: True>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/fastai/callbacks/hooks.py", line 80, in __del__
    def __del__(self): self.remove()
  File "/opt/conda/lib/python3.6/site-packages/fastai/callbacks/hooks.py", line 79, in remove
    def remove(self): self.hooks.remove()
  File "/opt/conda/lib/python3.6/site-packages/fastai/basic_train.py", line 423, in __getattr__
    def __getattr__(self,k): return getattr(self.learn, k)
AttributeError: 'NoneType' object has no attribute 'hooks'

This fixes the issue. 
```diff --git a/fastai/callbacks/hooks.py b/fastai/callbacks/hooks.py
index cc4ddaff..0c9e63db 100644
--- a/fastai/callbacks/hooks.py
+++ b/fastai/callbacks/hooks.py
@@ -63,6 +63,7 @@ class HookCallback(LearnerCallback):
     "Callback that can be used to register hooks on `modules`. Implement the corresponding function in `self.hook`."
     def __init__(self, learn:Learner, modules:Sequence[nn.Module]=None, do_remove:bool=True):
         super().__init__(learn)
+        self.hooks = None
         self.modules,self.do_remove = modules,do_remove

     def on_train_begin(self, **kwargs):
@@ -76,7 +77,10 @@ class HookCallback(LearnerCallback):
         "Remove the `Hooks`."
         if self.do_remove: self.remove()

-    def remove(self): self.hooks.remove()
+    def remove(self):
+               if self.hooks:
+                       self.hooks.remove()
+```
Making a pull request for fixing this issue.

**Comment by sgugger** [comment]
How do you get hooks destroyed inside a context manager where they are defined?

**Comment by karthiksubraveti** [comment]
This is without using context manager, i plainly instantiate the callback as follows
`actStats = ActivationStats(learn)`
and use it by passing in 
`learn.fit_one_cycle(3, 0.5, callbacks=actStats)`

prior to doing fit, if i attempt to destroy the actStats and reinstantiate it, i think i will hit this issue.

**Comment by sgugger** [comment]
Was looking at the wrong line, makes sense and should be fixed now.
