### ISSUE TITLE
What loss function is used?

### ISSUE THREAD

**Issue by jsrimr** [fastai/fastai#1958]
Hi,

I was being curious to know what loss function is appropriate when DL model deals with a dataset with both Categorical and Continuous variable.

https://github.com/fastai/fastai/blob/master/courses/dl1/lesson3-rossman.ipynb

However, I cannot get this info( what loss function are you using?!) in the jupyter notebook?

May I know it?

**Comment by sgugger** [comment]
Those questions are best asked (and maybe already answered!) on the [forum](https://forums.fast.ai/). In this case, you're mixing inputs and outputs: the output of the model is a float so the loss function is simply the mean squared error.
