### ISSUE TITLE
Input type error

### ISSUE THREAD

**Issue by Hamdikap** [fastai/fastai#1965]
My error there is :
RuntimeError: grid_sampler(): expected input and grid to have same dtype, but input has uint8_t and grid has float
````
learn = load_learner('E:\İndirmeler', 'trained_model.pkl')

p = cv2.imread("One_8.jpg") # p is numpy array with shape (height,width,channels)

t = pil2tensor(p, dtype=np.uint8) # converts to numpy tensor

t = t.permute(2,0,1) # Move num_channels as first dimension

im = Image(t) # Convert to fastAi Image - this class has "apply_tfms"

learn.predict(im)
````

**Comment by sgugger** [comment]
You should load images with `open_image` to make your life easier, but if you want to do the process manually, remember to convert to float and divide by 255. before passing your tensor to `Image`.

**Comment by Hamdikap** [comment]
I am loading my test image like that because ı have to capturing frame on real time system with opencv. So ı have to convert it  . I think.

**Comment by sgugger** [comment]
Oh ok, then like I said: add `.float()/255.` after the permute and you should be fine.

**Comment by Hamdikap** [comment]
```
p = cv2.imread("One_8.jpg") # p is numpy array with shape (height,width,channels)

t = pil2tensor(p, dtype=np.float32 ) # converts to numpy tensor

im = Image(t) # Convert to fastAi Image - this class has "apply_tfms"

```

Where should ı change ?

**Comment by sgugger** [comment]
This is not the same code as before. Here is the code you should use modified from the original one.
```
learn = load_learner('E:\İndirmeler', 'trained_model.pkl')

p = cv2.imread("One_8.jpg") # p is numpy array with shape (height,width,channels)

t = pil2tensor(p, dtype=np.uint8) # converts to numpy tensor

t = t.permute(2,0,1) # Move num_channels as first dimension

t = t.float()/255. #Convert to float

im = Image(t) # Convert to fastAi Image - this class has "apply_tfms"

learn.predict(im)
```

**Comment by Hamdikap** [comment]
`RuntimeError: cuda runtime error (30)`

**Comment by raghavendrajain** [comment]
@sgugger Hi. I tried this now. 

```
p = cv2.imread('rooster.jpg') # p is numpy array with shape (height,width,channels)
t = pil2tensor(p, dtype=np.uint8) # converts to numpy tensor
t = t.permute(2,0,1) # Move num_channels as first dimension
t = t.float()/255. #Convert to float
im = Image(t) # Convert to fastAi Image - this class has "apply_tfms"
learn1.predict(im)
```

But it gives me the following error:

```
<ipython-input-160-770b213cea6a> in <module>
      3 t = t.permute(2,0,1) # Move num_channels as first dimension
      4 t = t.float()/255. #Convert to float
----> 5 im = Image(t) # Convert to fastAi Image - this class has "apply_tfms"
      6 learn1.predict(im)

TypeError: 'module' object is not callable

```

**Comment by Hamdikap** [comment]
> @sgugger Hi. I tried this now.
> 
> ```
> p = cv2.imread('rooster.jpg') # p is numpy array with shape (height,width,channels)
> t = pil2tensor(p, dtype=np.uint8) # converts to numpy tensor
> t = t.permute(2,0,1) # Move num_channels as first dimension
> t = t.float()/255. #Convert to float
> im = Image(t) # Convert to fastAi Image - this class has "apply_tfms"
> learn1.predict(im)
> ```
> 
> But it gives me the following error:
> 
> ```
> <ipython-input-160-770b213cea6a> in <module>
>       3 t = t.permute(2,0,1) # Move num_channels as first dimension
>       4 t = t.float()/255. #Convert to float
> ----> 5 im = Image(t) # Convert to fastAi Image - this class has "apply_tfms"
>       6 learn1.predict(im)
> 
> TypeError: 'module' object is not callable
> ```

you are probably calling module but you have to call object of module
