### ISSUE TITLE
load_learner doesn't work with 'cpu' as default device

### ISSUE THREAD

**Issue by francolq** [fastai/fastai#1984]
According to [documentation](https://docs.fast.ai/torch_core.html#Global-constants), to run on CPU we must do `defaults.device = 'cpu'`.

However, in code, comparison is w.r.t. the device object, not the string, giving always False: `defaults.device == torch.device('cpu')`.

https://github.com/fastai/fastai/blob/bb573cc7f58a10afeb29fc6e767743c2d749b999/fastai/basic_train.py#L598

**Comment by sgugger** [comment]
Docs are wrong. Fixing it, thanks for flagging!

**Comment by francolq** [comment]
Good! Thank you.
