### ISSUE TITLE
XResNet cannot handle some image sizes

### ISSUE THREAD

**Issue by edwardeasling** [fastai/fastai#1993]
When using the XResNet models, I get an error with certain input image sizes. 

For example, when I give an XResNet 34 an input image of 375x400, it gives me the following error -  "RuntimeError: The size of tensor a (24) must match the size of tensor b (23) at non-singleton dimension 2". 

This does not happen with the standard ResNet34. I suspect it is something to do with how the stride 2 layers are handled.

Here are my installation details:

```text
=== Software === 
python        : 3.6.5
fastai        : 1.0.51
fastprogress  : 0.1.20
torch         : 1.0.0.dev20190409
nvidia driver : 410.104
torch cuda    : 10.0.130 / is available
torch cudnn   : 7402 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11441MB | Tesla K80

=== Environment === 
platform      : Linux-4.4.0-1079-aws-x86_64-with-debian-stretch-sid
distro        : #89-Ubuntu SMP Tue Mar 26 15:25:52 UTC 2019
conda env     : Unknown
python        : /home/ubuntu/anaconda3/bin/python
sys.path      : 
/home/ubuntu/src/cntk/bindings/python
/home/ubuntu/anaconda3/lib/python36.zip
/home/ubuntu/anaconda3/lib/python3.6
/home/ubuntu/anaconda3/lib/python3.6/lib-dynload
/home/ubuntu/.local/lib/python3.6/site-packages
/home/ubuntu/anaconda3/lib/python3.6/site-packages
/home/ubuntu/anaconda3/lib/python3.6/site-packages/IPython/extensions
/home/ubuntu/.ipython
```

**Comment by sgugger** [comment]
This is probably due to some inconsistency in padding between the conv layer and the average pooling. I'd suggest to stick with dimensions that are a multiple of 32 on both sizes (don't have to be the same) in the meantime.

**Comment by sgugger** [comment]
Should be fixed now.
