### ISSUE TITLE
How to pass custom sampler into dataloader

### ISSUE THREAD

**Issue by L1aoXingyu** [fastai/fastai#1995]
**Describe the bug**

In `torch.utils.data.DataLoader`, there is a args `sampler`. I want to pass my custom `sampler` into train dataloader but train dataloader default `shuffle=True` will have a conflict with `sampler` and I don't know how to solve this problem.

**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
Just type `data.train_dl = data.train_dl.new(shuffle=False, sample=your_sampler)`.

**Comment by msrdinesh** [comment]
Hey, I tried the same but got the following error..
data_class.train_dl = data_class.train_dl.new(shuffle=False, sampler=WeightedRandomSampler)
ValueError: sampler should be an instance of torch.utils.data.Sampler, but got sampler=<class 'torch.utils.data.sampler.WeightedRandomSampler'>
I thins there is a typo in the fastai's source code. 
It should accept "torch.utils.data.sampler" not "torch.utils.data.Sampler"
