### ISSUE TITLE
Is there a way to save databunch more efficiently

### ISSUE THREAD

**Issue by rubick1896** [fastai/fastai#1996]
I was trying to save a large language model databunch to disk and surprisingly found that the save method consumes a lot of RAM. I traced the source code and found it is using torch.save which is using pickle. According to stackoverflow 
https://stackoverflow.com/questions/13871152/why-pickle-eat-memory
pickle is not a good method for dumping large data into disk. I am not an expert, just wondering if there could be a more efficient way of saving large databunch.

**Comment by sgugger** [comment]
You can always save the pieces you need independently if you don't want to use pickle. Your ids are in `data.train_ds.x.items` (or valid), the vocab in `data.train_ds.vocab`, the label indices in `data.train_ds.y.items` and the classes in `data.train_ds.classes`.
