### ISSUE TITLE
What's the explanation for line 167-168

### ISSUE THREAD

**Issue by Steffy-zxf** [fastai/fastai#2001]
fastai/fastai/text.py
<img width="661" alt="84d2015a4d6ca4a29591eff8565bf151" src="https://user-images.githubusercontent.com/48793257/56662166-f4a48280-66d5-11e9-8a0a-e43666c83d4a.png">

what is the meaning for 0.95?

**Comment by sgugger** [comment]
Questions are better asked on the [forum](https://forums.fast.ai), issues on GitHub are for bugs only. Note that this is not the current code in the library.
This corresponds to the idea of randomized bptt introduced in [this article](https://arxiv.org/pdf/1708.02182.pdf).
