### ISSUE TITLE
Create a smaller production pip install?

### ISSUE THREAD

**Issue by crearo** [fastai/fastai#2007]
I want to run an inference on `heroku` where I've already hosted [my website](www.rish.space). 
Everything worked great on my laptop, but as soon as I push to Heroku, it complains about its maximum size limit being 500MB. 

Here's all I've done:
1. `pip install fastai`
2. `pip freeze > requirements.txt # fastai internally installs so many more pypis`
3. `git push heroku master`

Aaaand, heroku fails. Specifically, it redirects me to the [slug-size page](https://devcenter.heroku.com/articles/slug-compiler#slug-size).

Can we have a separate install for inferencing only? I know PyTorch comes with a CPU only build that's 45MB and is meant for production.

**Comment by stas00** [comment]
Here are the instructions that let you choose and pick what fastai dependencies you want to install:
https://docs.fast.ai/install.html#custom-dependencies

But dependencies of dependencies is beyond of fastai control.

**Comment by crearo** [comment]
Alright! The trick was to just type:

`fastai`
`https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl`

in `requirements.txt`. 

I was doing a `pip freeze > requirements.txt` which does not work. I'm still 
This still is problematic for me because every time I pip install something I have to be extra careful to put it in the requirements.txt file manually.
