### ISSUE TITLE
Wrong links generated by doc

### ISSUE THREAD

**Issue by vshalts** [fastai/fastai#2021]
Hey!

Probably not that a big issue, but still. Seems `doc` not always works as expected. Particularly
```
from fastai.vision import *
doc(ClassificationInterpretation.plot_confusion_matrix)
```

generate [Show in docs](https://docs.fast.ai/train.html#ClassificationInterpretation.plot_confusion_matrix) which is wrong.

Correct link [Show in docs](https://docs.fast.ai/vision.learner.html#ClassificationInterpretation.plot_confusion_matrix) (should be `vision.learner.html` instead of `train.htm`)

Expected behavior - `Show in docs` points to correct link which describes function.

**Comment by sgugger** [comment]
Oh that's because the function was moved, so its documentation should be moved too. If you want to have a go at it and suggest a PR, go ahead!
