### ISSUE TITLE
databunch creation and usage issues

### ISSUE THREAD

**Issue by Hagenov** [fastai/fastai#2022]
**Describe the bug**
When creating a databunch using ItemList, split works, label is a bit off (I'll worry about this later) but I cannot wrap the databunch using any pre-processing techniques.

When I pass the data into anything that tries show the data I get the error:
TypeError: 'DataBunch' object is not subscriptable

When I tried to pass the data into the Learner() function, i received the error:
TypeError: batch must contain tensors, numbers, dicts or lists; found <class 'pathlib.PosixPath'>)

When I tried to pass the data into a cnn_learnre, i received the function: 
TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not bool
```

tfms = []    # first element applies to training set, second element applies to valid set
padding_mode='reflection'  
  
db_txt_data = (ItemList.from_folder(path=path)                               # Should ds_tfms=tfms ?
               .split_by_folder(train='training_set', valid='valid_set')                            
               .label_from_folder()                                          # (cols='Label')
               .transform(tfms)
               #.normalize()
               .databunch(bs=8, num_workers=4)                                              # bs=16, collate_fn=bb_pad_collate
              )
```

I'm pulling straight from my Google Drive, which has all the csv files split into training and valid folders. Each file indicating a specific label are bunched together. The files themselves consist of two fields, time elapsed and an interval timing.

**Expected behaviour**
Firstly, I am aware the databunch needs to be wrapped,, yet through dozens of attempts I cannot get this to work.

I am expecting a databunch that can be fed into a convolutional network I am currently constructing. There seems to be a lot of confusion in this area online with widely varying solutions that don't fix the problem

**Comment by sgugger** [comment]
I think your problem comes from the fact you're using `ItemList` and not one of its subclass. `ItemList` is the base abstract class, it's not suitable to be used directly unless your data is basic arrays. 
Since you mention a CNN, I'm guessing you have images? You should use `ImageList` then.

**Comment by Hagenov** [comment]
Hi Sylvain,

Thanks for getting back to me so quickly!

I’ll have a look into ItemList subclasses, I have a lot of problems getting other classes to work for my application, but I’ve cleaned the data various different ways since then.

The .csv files I am using have 2 columns. The first is a continuous time interval of an event (foot hitting the ground) and the second is the interval since last step

I have done a lot of research into the use of deep convolutional networks for physiological classification

If there’s anything else you feel I’m missing the point to, would you let me know?

All the best,
Dean

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by sgugger** [comment]
Oh, if this is a custom kind of data then you will need to write your own `ItemList`. I suggest you have a look at [this tutorial](https://docs.fast.ai/tutorial.itemlist.html) that explains how to do so.

**Comment by sgugger** [comment]
Closing as this isn't a bug in the library. We can continue the discussion on the [forum](https://forums.fast.ai/) if you need more help!
