### ISSUE TITLE
After recent updates.. TypeError: 'TextDataLoader' object does not support indexing

### ISSUE THREAD

**Issue by digitalspecialists** [fastai/fastai#203]
Receiving this error in an NLP task (eg Lesson4 IMDB, and own projects too) after a git pull today. 
At the start of model fitting this is the error "TypeError: 'TextDataLoader' object does not support indexing".

No error on my last pull of 762f0b6 back on Feb 27. I've reverted to that version and all OK.

**Comment by digitalspecialists** [comment]
The issue has been reported by other users on the forum.

**Comment by jph00** [comment]
Thanks for letting me know. Would you mind submitting a PR that undoes this change, or fixes it? Also could you provide a link to the forum discussion?

**Comment by digitalspecialists** [comment]
3 others reported the problem at http://forums.fast.ai/t/sentiment-classification-part-in-lesson-4-results-in-typeerror-textdataloader-object-does-not-support-indexing/13016
I encountered the problem during the kaggle donorschoose comp. I'll see what I can do about narrowing down the issue/resolution.

**Comment by jph00** [comment]
Should be fixed now.
