### ISSUE TITLE
val_loss , valid_loss  in SaveModelCallback and EarlyStoppingCallback

### ISSUE THREAD

**Issue by camelia-c** [fastai/fastai#2043]
Setup on Colab

```text
=== Software === 
python        : 3.6.7
fastai        : 1.0.52
fastprogress  : 0.1.21
torch         : 1.1.0
nvidia driver : 410.79
torch cuda    : 10.0.130 / is available
torch cudnn   : 7501 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11441MB | Tesla K80

=== Environment === 
platform      : Linux-4.14.79+-x86_64-with-Ubuntu-18.04-bionic
distro        : #1 SMP Wed Dec 19 21:19:13 PST 2018
conda env     : Unknown
python        : /usr/bin/python3
sys.path      : 
/env/python
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/usr/local/lib/python3.6/dist-packages/IPython/extensions
/root/.ipython

Mon May  6 11:15:29 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8    30W / 149W |     11MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

While experimenting with callbacks, I came across the following naming issues with SaveModelCallback and EarlyStoppingCallback:

* If I write explicitly the monitor to be "valid_loss":

resnet152_learner.fit_one_cycle(100, callbacks=[SaveModelCallback(resnet152_learner, monitor="valid_loss", every='improvement', name='bestmodel')])  

I get the following contradictory warning which includes "valid_loss" among available metrics, yet specifying "metric valid_loss which is not available"  :

/usr/local/lib/python3.6/dist-packages/fastai/callbacks/tracker.py:50: UserWarning: conditioned on metric valid_loss which is not available. Available metrics are: train_loss, valid_loss, accuracy, error_rate, time warn(f'{self.class} conditioned on metric {self.monitor} which is not available. Available metrics are: {", ".join(map(str, self.learn.recorder.names[1:]))}')

* Instead, it works very well when using the default monitor:

resnet152_learner.fit_one_cycle(100, callbacks=[SaveModelCallback(resnet152_learner, every='improvement', name='bestmodel')])  

The naming issue is due to the fact that it expects "val_loss" for valid_loss, thing which may be confusing: 
```
help(fastai.callbacks.tracker.SaveModelCallback.__init__)


Help on function __init__ in module fastai.callbacks.tracker:

__init__(self, learn:fastai.basic_train.Learner, monitor:str='val_loss', mode:str='auto', every:str='improvement', name:str='bestmodel')
    Initialize self.  See help(type(self)) for accurate signature.
```

Thanks in advance for clarifying the naming for this.

Best regards,
Camelia

**Comment by sgugger** [comment]
Thanks for pointing it out and your detailed analysis! This has been fixed recently and will be in the next release of fastai, in the meantime you can install master with
```
!pip install git+https://github.com/fastai/fastai
```
