### ISSUE TITLE
nbconvert >= 5.5 markdown2html filter call contract changed

### ISSUE THREAD

**Issue by MSeal** [fastai/fastai#2045]
**Describe the bug**

https://github.com/jupyter/nbconvert/issues/1007 was opened in nbconvert after the 5.5 release (I'm a maintainer of that porject). Fast.ai is calling methods that are not intended to be called in this particular manner and broke `nbdoc.doc` calls for the users who reported the issue.

**Provide your installation details**

With a fresh installed fastai vitrual environment via:

```
git clone git@github.com:fastai/fastai.git
cd fastai
pip install .
```

```text
=== Software === 
python       : 3.6.7
fastai       : 1.0.53.dev0
fastprogress : 0.1.21
torch        : 1.1.0
torch cuda   : 9.0.176 / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Linux-4.18.0-18-generic-x86_64-with-Ubuntu-18.04-bionic
distro       : #19~18.04.1-Ubuntu SMP Fri Apr 5 10:22:13 UTC 2019
conda env    : Unknown
python       : /home/mseal/.py3local/bin/python
sys.path     : 
/home/mseal/.py3local/lib/python36.zip
/home/mseal/.py3local/lib/python3.6
/home/mseal/.py3local/lib/python3.6/lib-dynload
/usr/lib/python3.6
/home/mseal/.py3local/lib/python3.6/site-packages
/home/mseal/Workspace/nbconvert
no supported gpus found on this system
```

**To Reproduce**

Running the `doc` function call in ` fastai.gen_doc.nbdoc` has a `TypeError` on calling the internal jinja filter method `markdown2html`

```
$ python -c 'from fastai.gen_doc.nbdoc import doc; doc(lambda: "")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mseal/Workspace/fastai/fastai/gen_doc/nbdoc.py", line 131, in doc
    md = show_doc(elt, markdown=False)
  File "/home/mseal/Workspace/fastai/fastai/gen_doc/nbdoc.py", line 116, in show_doc
    test_link, test_modal = get_pytest_html(elt, anchor_id=anchor_id) if show_tests else ('', '')
  File "/home/mseal/Workspace/fastai/fastai/gen_doc/nbtest.py", line 57, in get_pytest_html
    html = HTMLExporter().markdown2html(md).replace('\n','') # nbconverter fails to parse markdown if it has both html and '\n'
TypeError: markdown2html() missing 1 required positional argument: 'source'
```

**Expected behavior**

No `TypeError` should be raised.

**Screenshots**

**Additional context**

To fix, either pass in an empty defaultdict `defaultdict(lambda: defaultdict(dict))` or pass a real nbformat notebook as the context argument, or avoid using jinja template functions in non-jinja code-paths. We don't guarantee contracts on filters will be fixed as is in future releases in nbconvert.

**Comment by sgugger** [comment]
Thanks for the warning! It's not ideal to have to test for the version of nbconvert and apply the correct version of the function but it should work for what we need.
