### ISSUE TITLE
Tensor size errors on TransformerXL

### ISSUE THREAD

**Issue by rubenaranamorera** [fastai/fastai#2053]
I'm using new TransformerXL model to classify. I have completed the training without any problems, but when deploying it on production I have this error about 5-10% of the time, always with different sizes.

I'm loading the model trainied with load_learner and then calling predict with some text.

I'm using fastai 1.0.51.

Any idea? Could be related with having mutliple requests at the same time? I can not reproduce this on my local machine.

````

File /usr/local/lib/python3.6/site-packages/fastai/basic_train.py, line 362, in predict
    res = self.pred_batch(batch=batch)
  File /usr/local/lib/python3.6/site-packages/fastai/basic_train.py, line 342, in pred_batch
    preds = loss_batch(self.model.eval(), xb, yb, cb_handler=cb_handler)
  File /usr/local/lib/python3.6/site-packages/fastai/basic_train.py, line 25, in loss_batch
    out = model(*xb)
  File /usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py, line 489, in __call__
    result = self.forward(*input, **kwargs)
  File /usr/local/lib/python3.6/site-packages/torch/nn/modules/container.py, line 92, in forward
    input = module(input)
  File /usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py, line 489, in __call__
    result = self.forward(*input, **kwargs)
  File /usr/local/lib/python3.6/site-packages/fastai/text/learner.py, line 260, in forward
    r, o = self.module(input[:,i: min(i+self.bptt, sl)])
  File /usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py, line 489, in __call__
    result = self.forward(*input, **kwargs)
  File /usr/local/lib/python3.6/site-packages/fastai/text/models/transformer.py, line 229, in forward
    inp = layer(inp, r=pos_enc, u=self.u, v=self.v, mask=mask, mem=mem)
  File /usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py, line 489, in __call__
    result = self.forward(*input, **kwargs)
  File /usr/local/lib/python3.6/site-packages/fastai/text/models/transformer.py, line 152, in forward
    def forward(self, x:Tensor, mask:Tensor=, **kwargs): return self.ff(self.mhra(x, mask=mask, **kwargs))
  File /usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py, line 489, in __call__
    result = self.forward(*input, **kwargs)
  File /usr/local/lib/python3.6/site-packages/fastai/text/models/transformer.py, line 49, in forward
    return self.ln(x + self.drop_res(self.out(self._apply_attention(x, mask=mask, **kwargs))))
  File /usr/local/lib/python3.6/site-packages/fastai/text/models/transformer.py, line 116, in _apply_attention
    if self.scale: attn_score = (AC + BD).mul_(1/(self.d_head ** 0.5))
RuntimeError: The size of tensor a (35) must match the size of tensor b (14) at non-singleton dimension 3

````

````
RuntimeError: The size of tensor a (40) must match the size of tensor b (20) at non-singleton dimension 3
````

````
RuntimeError: The size of tensor a (46) must match the size of tensor b (21) at non-singleton dimension 3
````

**Comment by sgugger** [comment]
I think this is linked to a bug recently fixed in master but can't be 100% sure. The bug was introduced in 1.0.52 and wasn't in 1.0.51 I believe, so double-check your model in production uses 1.0.51? Or try master and see if it persists?

**Comment by rubenaranamorera** [comment]
Seems it was a problem related with multithreading. Making it single thread solved all issues and improved the performance

**Comment by zhangjiekui** [comment]
@rubenaranamorera I'm also trying to train a TransformerXL to classify and sequence generate, would you share you  "TransformerXL classification model"? Thanks

**Comment by zhangjiekui** [comment]
when I'm trying to use TransformerXL model, such as:
`    path = untar_data(URLs.IMDB_SAMPLE)
    data = TextLMDataBunch.from_csv(path, 'texts.csv')
    vocab_size = len(data.vocab.itos)
    transformer_model = get_language_model(TransformerXL,vocab_size)
    learn = LanguageLearner(data, transformer_model)
    learn.fit(1)`

I received the error:
 `path for imdb dataset: /home/zjk/.fastai/data/imdb_sample
epoch     train_loss  valid_loss  accuracy  time    
Traceback (most recent call last):
  File "/home/zjk/fastai_transformerXl/LM_test.py", line 40, in <module>
    test1()
  File "/home/zjk/fastai_transformerXl/LM_test.py", line 36, in test1
    learn.fit(1)
  File "/home/zjk/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/basic_train.py", line 199, in fit
    fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
  File "/home/zjk/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/basic_train.py", line 101, in fit
    loss = loss_batch(learn.model, xb, yb, learn.loss_func, learn.opt, cb_handler)
  File "/home/zjk/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/basic_train.py", line 26, in loss_batch
    out = model(*xb)
  File "/home/zjk/anaconda3/envs/fastai/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zjk/anaconda3/envs/fastai/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/zjk/anaconda3/envs/fastai/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zjk/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/text/models/transformer.py", line 229, in forward
    inp = layer(inp, r=pos_enc, u=self.u, v=self.v, mask=mask, mem=mem)
  File "/home/zjk/anaconda3/envs/fastai/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zjk/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/text/models/transformer.py", line 152, in forward
    def forward(self, x:Tensor, mask:Tensor=None, **kwargs): return self.ff(self.mhra(x, mask=mask, **kwargs))
  File "/home/zjk/anaconda3/envs/fastai/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zjk/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/text/models/transformer.py", line 49, in forward
    return self.ln(x + self.drop_res(self.out(self._apply_attention(x, mask=mask, **kwargs))))
  File "/home/zjk/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/text/models/transformer.py", line 108, in _apply_attention
    wq,wk,wv = map(lambda x:x.view(bs, x_len, self.n_heads, self.d_head), (wq,wk,wv))
  File "/home/zjk/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/text/models/transformer.py", line 108, in <lambda>
    wq,wk,wv = map(lambda x:x.view(bs, x_len, self.n_heads, self.d_head), (wq,wk,wv))
RuntimeError: shape '[64, 70, 10, 41]' is invalid for input of size 3673600`

some additional info:
fastai:1.0.52
pytorch:1.10
ubuntu 16.04

**Comment by zhangjiekui** [comment]
but if I replaced :
`transformer_model = get_language_model(TransformerXL,vocab_size)`
with
`transformer_model = get_language_model(Transformer,vocab_size)`

It worked. what's wrong?
