### ISSUE TITLE
Memory leak when creating a custom open function in Vision application.

### ISSUE THREAD

**Issue by StatisticDean** [fastai/fastai#2068]
The bug is the following :
If you create a custom open function that returns a tensor in the vision side of fastai like for example : 
```
class TensorImageList(ImageList):
    def open(self, fn):
        return torch.load(fn, map_location='cpu').type(torch.float)
```
Everything will work fine, the databunch will be created and the learner can be trained, but the memory usage will go up until it eats all of your available RAM during training. 
I talked about this issue on fastais and pytorch forum : 
-https://forums.fast.ai/t/learn-fit-one-cycle-makes-me-run-out-of-memory-on-cpu-while-i-train-on-gpu/45428/3
-https://discuss.pytorch.org/t/dataloader-memory-leak/44860/8

The 'fix' I have found is to apply the Image after loading the tensor like this :  
```
class TensorImageList(ImageList):
    def open(self, fn):
        return Image(torch.load(fn, map_location='cpu').type(torch.float))
```

but this still doesn't explain why in the first case, all the memory is used.

Here's a notebook to reproduce the bug :
- https://github.com/StatisticDean/fastai_memory_cpu 

In fact you don't even need to train to get the bug, just iterating through the dataloader eats up all your RAM.

**Comment by sgugger** [comment]
This isn't a bug in the sense that when using the fastai library, you should have your datasers return `ItemBase` [docs](https://docs.fast.ai/core.html#ItemBase). As the docs say: "All items used in fastai should subclass this."
In it you should implement the `.data` attribute that will be your tensors as instructed in [this tutorial](https://docs.fast.ai/tutorial.itemlist.html#Creating-a-custom-ItemBase-subclass). 

The whole of this will very likely change in 1.1 in any case, which is why I'm closing this issue.

**Comment by StatisticDean** [comment]
You're right that this isn't a bug but a consequence of a misuse of the library. What's annoying here is that it "almost" works, aside from the memory leak, everything is training just fine. Maybe a warning could be useful. Do you think it could be a good idea to add a check at the creation of a `Databunch` (or at the creation of an `ItemList`) that verifies that what is returned is a subclass of `ItemBase` and print a warning if it doesn't? I'm assuming that a lot of things will change in fastai's 1.1 so it might not be worth doing a PR right now, but I would be happy to contribute.

**Comment by sgugger** [comment]
From the direction we're heading right now, there won't be this data attribute anymore in 1.1, which is why I closed the issue ;)
