### ISSUE TITLE
Cannot get started with conda and CPU-only build of PyTorch

### ISSUE THREAD

**Issue by nihil-admirari** [fastai/fastai#2078]
Since I don't have a CUDA 3.5-capable GPU, I tried to install a CPU-only build of PyTorch:
```sh
conda install -c pytorch pytorch-cpu torchvision-cpu
conda install -c fastai fastai
```
([Installation instructions](https://docs.fast.ai/install.html) mention `torchvision` instead of `torchvision-cpu`, but it results in both `pytorch-cpu` and `pytorch` being installed.)

Unfortunately, in this case, `conda` allows to install only a very old version of fastai (1.0.34):
```text
=== Software ===
python version : 3.7.3
fastai version : 1.0.34
torch version  : 1.1.0
torch cuda ver
torch cuda is  : **Not available**

=== Hardware ===
No GPUs available

=== Environment ===
platform       : Windows-10-10.0.17763-SP0
conda env      : base
python         : C:\Users\user\Miniconda3\python.exe
sys.path       :
C:\Users\user\Miniconda3\python37.zip
C:\Users\user\Miniconda3\DLLs
C:\Users\user\Miniconda3\lib
C:\Users\user\Miniconda3
C:\Users\user\Miniconda3\lib\site-packages
C:\Users\user\Miniconda3\lib\site-packages\win32
C:\Users\user\Miniconda3\lib\site-packages\win32\lib
C:\Users\user\Miniconda3\lib\site-packages\Pythonwin
C:\Users\user\Miniconda3\lib\site-packages\IPython\extensions
no supported gpus found on this system
```

fastai 1.0.34 does not work on Windows at all:
```py
%matplotlib inline
from fastai import *
from fastai.vision import *

path = untar_data(URLs.MNIST_SAMPLE)
data = ImageDataBunch.from_folder(path)
data.show_batch(rows=3, figsize=(5, 5))
```
results in
```text
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\lib\site-packages\fastai\data_block.py", line 478, in __getattr__
    res = getattr(self.x, k, None)
  File "C:\Users\user\Miniconda3\lib\site-packages\fastai\data_block.py", line 478, in __getattr__
    res = getattr(self.x, k, None)
  File "C:\Users\user\Miniconda3\lib\site-packages\fastai\data_block.py", line 478, in __getattr__
    res = getattr(self.x, k, None)
  [Previous line repeated 997 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```
(On Ubuntu VM, the same old version of fastai is installed when CPU-only PyTorch is requested, but `show_batch` succeeds without throwing an exception)

CUDA-enabled `pytorch` and `torchvision` work, and `conda` installs fastai 1.0.52, but I have to type:
```py
from fastai.torch_core import defaults
defaults.device = torch.device('cpu')
```
before importing any other fastai module, which is inconvenient. Device detection is broken on my machine: `torch.cuda.is_available()` returns `True`, even though nothing works:
```text
Found GPU0 GeForce ... which is of cuda capability 3.0.
PyTorch no longer supports this GPU because it is too old.
The minimum cuda capability that we support is 3.5.
```

Can you please make fastai from conda channel compatible with `pytorch-cpu`?

**Comment by stas00** [comment]
> Since I don't have a CUDA 3.5-capable GPU, I tried to install a CPU-only build of PyTorch:

Are you saying that since you have an old GPU, pytorch tries to use it and fails to work, rather than automatically using its cpu mode? If so this is a bug in pytorch and please consider reporting it to the pytorch team.

Normally, you shouldn't need `pytorch-cpu` as the `pytorch` package works with and without GPU.

> ([Installation instructions](https://docs.fast.ai/install.html) mention `torchvision` instead of `torchvision-cpu`, but it results in both `pytorch-cpu` and `pytorch` being installed.)

You're correct, those are outdated instructions. I have just updated them: https://docs.fast.ai/install.html#cpu-build

**Comment by Hamdikap** [comment]
You have to download and setup only cpu version of pytorch . you can find it at Pytorch Donloads.

**Comment by nihil-admirari** [comment]
```text
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.tensor(1).cuda()
C:\Users\user\Miniconda3\lib\site-packages\torch\cuda\__init__.py:118: UserWarning:
    Found GPU0 GeForce ... which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability that we support is 3.5.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
tensor(1, device='cuda:0')
>>> torch.tensor(1).cuda() + torch.tensor(1).cuda()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: no kernel image is available for execution on the device
```
So PyTorch reports that CUDA is available though warns that GPU is too old, and even allows to put a tensor on a GPU, but every other operation fails.

I looked at the updated instructions. Ok, I'll try to go with custom dependencies if there is no other way.

**Comment by stas00** [comment]
Thank you for sharing the details of the failure. My feeling is that pytorch needs to have a way to fall back to cpu and not fail.

An easy workaround is setting `CUDA_VISIBLE_DEVICES=""`, in which case pytorch will not try to check your gpu at all.

**Comment by nihil-admirari** [comment]
PyTorch changed the way to install CPU-only builds: https://github.com/fastai/fastai/pull/2333. Simple `conda install`s are now possible.
