### ISSUE TITLE
Error: attribute not found when trying to load textdatabunch

### ISSUE THREAD

**Issue by hamelsmu** [fastai/fastai#2089]
**Describe the bug**
I'm getting an error that an attribute `pass_through` is not found when loading a language model data bunch.  

**Provide your installation details**

```text
=== Software === 
python       : 3.7.3
fastai       : 1.0.52
fastprogress : 0.1.21
torch        : 1.1.0
torch cuda   : None / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Linux-3.16.0-4-amd64-x86_64-with-debian-9.9
distro       : #1 SMP Debian 3.16.51-3 (2017-12-13)
conda env    : Unknown
python       : /usr/local/bin/python
sys.path     : /ds/mdtokenizer/notebooks
/usr/local/lib/python37.zip
/usr/local/lib/python3.7
/usr/local/lib/python3.7/lib-dynload

/usr/local/lib/python3.7/site-packages
/usr/local/lib/python3.7/site-packages/IPython/extensions
/root/.ipython
no supported gpus found on this system
```

**To Reproduce**
I created [this gist](https://gist.github.com/hamelsmu/df8c5c2f43e8affa5756ed291f8026ce) to reproduce this error.  Please note that if I just run the gist as one script no error occurs.  However, if I restart the kernel and try to load the data bunch, I get the error below:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-ba8e7fea8797> in <module>
----> 1 data_lm = load_data('lang_model/', num_workers=0)

/usr/local/lib/python3.7/site-packages/fastai/basic_data.py in load_data(path, file, bs, val_bs, num_workers, dl_tfms, device, collate_fn, no_check, **kwargs)
    275     "Load a saved `DataBunch` from `path/file`. `file` can be file-like (file or buffer)"
    276     source = Path(path)/file if is_pathlike(file) else file
--> 277     ll = torch.load(source, map_location='cpu') if defaults.device == torch.device('cpu') else torch.load(source)
    278     return ll.databunch(path=path, bs=bs, val_bs=val_bs, num_workers=num_workers, dl_tfms=dl_tfms, device=device,
    279                         collate_fn=collate_fn, no_check=no_check, **kwargs)

/usr/local/lib/python3.7/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    385         f = f.open('rb')
    386     try:
--> 387         return _load(f, map_location, pickle_module, **pickle_load_args)
    388     finally:
    389         if new_fd:

/usr/local/lib/python3.7/site-packages/torch/serialization.py in _load(f, map_location, pickle_module, **pickle_load_args)
    572     unpickler = pickle_module.Unpickler(f, **pickle_load_args)
    573     unpickler.persistent_load = persistent_load
--> 574     result = unpickler.load()
    575 
    576     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

AttributeError: Can't get attribute 'pass_through' on <module '__main__'>
```

**Expected behavior**
I'm just trying to load a previously created data bunch.

**Comment by hamelsmu** [comment]
I'm working on a reproducible example that you can run yourself will update the issue above when that is done

**Comment by hamelsmu** [comment]
I'm going to close this issue until I'm able to provide a reproduceable example and re-open when its ready.

**Comment by hamelsmu** [comment]
Well that was dumb mistake on my part.  I'm going to write what I did wrong incase someone reaches this thread via Google Search:

The lesson learned is if you have any custom transformation functions that are arguments to the tokenizer, you have to bring that back into the context, because when you load the databunch it is going to look for this.  

In my case, I had a function called `pass_through` that I passed to the Tokenizer as a `pre_rule`, I have to make sure I define this function or import it in the context that I'm loading the databunch.

**Comment by harshikanu** [comment]
@hamelsmu  Hi! I am getting a similar error now when loading the databunch. 

  File "/home/views.py", line 641, in get
    path, r"/home/data_save.pkl")
  File "/usr/local/lib/python3.7/site-packages/fastai/basic_data.py", line 281, in load_data
    ll = torch.load(source, map_location='cpu') if defaults.device == torch.device('cpu') else torch.load(source)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
AttributeError: Can't get attribute 'RobertaTextList' on <module '__main__' from 'manage.py'>


Could you probably help me with this?

**Comment by hamelsmu** [comment]
This issue is so old that I don’t think I can be helpful try the fastai forums
