### ISSUE TITLE
 TransformerXL Errors: shape '[64, 70, 10, 41]' is invalid for input of size 3673600

### ISSUE THREAD

**Issue by zhangjiekui** [fastai/fastai#2093]
when I'm trying to use TransformerXL model, such as:
`path = untar_data(URLs.IMDB_SAMPLE) 
data = TextLMDataBunch.from_csv(path, 'texts.csv') 
vocab_size = len(data.vocab.itos) 
transformer_model = get_language_model(TransformerXL,vocab_size) 
learn = LanguageLearner(data, transformer_model)
 learn.fit(1)`

I received the error:
`  File "/home/zjk/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/text/models/transformer.py", line 108, in <lambda>

    wq,wk,wv = map(lambda x:x.view(bs, x_len, self.n_heads, self.d_head), (wq,wk,wv))

RuntimeError: shape '[64, 70, 10, 41]' is invalid for input of size 3673600`

but if I replaced :
transformer_model = get_language_model(TransformerXL,vocab_size)

with

transformer_model = get_language_model(Transformer,vocab_size)

It worked. what's wrong?

some additional info:
fastai:1.0.52
pytorch:1.10
ubuntu 16.04

**Comment by sgugger** [comment]
This bug has been fixed in master already, it will be in the next release. In the meantime, either make a dev install or revert to v1.0.51, I think this version didn't have it.
