### ISSUE TITLE
offline mnist dataset and sat4-6 datasets usage with fastai & fastai with satellite imagery

### ISSUE THREAD

**Issue by jaigsingla** [fastai/fastai#2094]
Hi,

I am trying to ingest mnist.npz file in to fastai but not able to understand how to go around ?

how to ingest sat4-sat6 dataset .mat files and do operations on these

Can we perform multilabel classification on satellite imagery using this?

thanks
Jai

**Comment by sgugger** [comment]
You should ask those questions on the [forum](https://forums.fast.ai/) as there'll be more people to help you there. We keep the issues in GitHub for bugs only.
