### ISSUE TITLE
Lesson 4 spacy tokenizer is not initialized and throws NameError

### ISSUE THREAD

**Issue by bharadwaj6** [fastai/fastai#213]
`NameError: name 'spacy_tok' is not defined` on line 8 in lesson4-imdb

**Comment by pauloneves** [comment]
The problem was introduced in commit 3e4b5a9, till the commit before (98fad0e) everything was working fine. The code below reproduces the error:

```
%reload_ext autoreload
%autoreload 2
%matplotlib inline

from fastai.learner import *

import torchtext
from torchtext import vocab, data
from torchtext.datasets import language_modeling

from fastai.rnn_reg import *
from fastai.rnn_train import *
from fastai.nlp import *
from fastai.lm_rnn import *

import dill as pickle
print(spacy_tok)
```

it fails since spacy_tok is not defined.

**Comment by xapss** [comment]
Yes, I noticed it has been refactored a bit. It's inside Tokenizer() class.
Try: `Tokenizer().spacy_tok`

**Comment by urmaspitsi** [comment]
Try replacing spacy_tok with string "spacy", when initializing TEXT variable. Instead of module reference it seems to use string variable instead.
