### ISSUE TITLE
Metrics docs markdown equations are not displayed properly

### ISSUE THREAD

**Issue by kori73** [fastai/fastai#2140]
The equations on the metrics page are displayed in raw form. I have written the equations, I might have made a mistake. Here is a screenshot. I am not sure if this should be reported as an issue, I am sorry if it shouldn’t be.

![metrics](https://user-images.githubusercontent.com/36677585/58832026-b1cfb600-8656-11e9-9e0c-238fa8d2327e.png)

**Comment by sgugger** [comment]
Ah yes, properly displaying LaTeX equations on GitHub pages requires MatJax, which is heavy and would make the docs load more slowly. We're investigating how to make it performant and only used on the needed pages.
