### ISSUE TITLE
from fastai.vision import * raise error,no module found 

### ISSUE THREAD

**Issue by thisisreallife** [fastai/fastai#2147]
## Probelm:

I learned fastai deeplearning courseV3. I came across a problem like this:
```
from fastai.vision import *
from fastai.metrics import error_rate
```
Output:
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-30-283c0d40bede> in <module>
----> 1 from fastai.vision import *
      2 from fastai.metrics import error_rate

ModuleNotFoundError: No module named 'fastai.vision'
```

What is the problem? I almost try every version combination of torch,torchvision and fastai, things still goes wrong...I think the instructor of deep learning course did not give us the specific version of each package to install.
 
## My device or software versions:
OS = win10
Python = 3.6
torch = 1.1.0
torchvision = 0.2.2
fastai=1.0.52

I will very appreciate if someone can help me !

**Comment by sgugger** [comment]
Looks like you have some installation problem. There is a [dedicated thread](https://forums.fast.ai/t/fastai-v1-install-issues-thread/24111/356) on the forum for this.

**Comment by thisisreallife** [comment]
Ok,I will check it. I already run fastai code on Colab and  Colab supports fastai very well, thanks!

**Comment by anjanimsp** [comment]
Can we do the installation of the specific library for inference in fastai.  Such as we required for inference only load_learner() module for prediction can we installation only that library.

**Comment by sgugger** [comment]
No the library is not split in separate packages. You'll need to make you own fork for that.

**Comment by anjanimsp** [comment]
Thanks a lot for your reply. I'll do the same.

**Comment by anjanimsp** [comment]
My PyTorch version is these.
PyTorch Version:  1.4.0
Torchvision Version:  0.5.0
When I use fastai .pth weight file in PyTorch model using pytorch_model.load_state_dict(new_state_dict) it's get error ( Unexpected key(s) in state_dict: "").
What is the fasai torchvision version? What is the reason behind this error?

**Comment by staru09** [comment]
I am having a similar configurations and facing the similar issue

**Comment by jiamin9722** [comment]
same I met this problem too

**Comment by LinoSun** [comment]
> I am having a similar configurations and facing the similar issue, can you plz suggest how you managed to sort out.
> 
> ![Screenshot 2020-09-25 161740](https://user-images.githubusercontent.com/70081536/94260822-72fdf780-ff4e-11ea-8196-c4b0d7971483.jpg)

You can do like this to fix this problem:
python -m ipykernel install --user --name my_pt --display-name my_pt

**Comment by LinoSun** [comment]
![image](https://user-images.githubusercontent.com/44741345/95995045-94724500-0e63-11eb-81ad-d56fe311309c.png)
![image](https://user-images.githubusercontent.com/44741345/95995077-9dfbad00-0e63-11eb-888e-01fc09cd90cf.png)

**Comment by staru09** [comment]
Try to install the dev version of fast AI. It sorted out the problem  in my
case.
