### ISSUE TITLE
Adding torch.no_grad() flag to prediction

### ISSUE THREAD

**Issue by bearpelican** [fastai/fastai#2149]
Should we disable autograd when calling Learn.predict? (with torch.no_grad())
https://github.com/fastai/fastai/blob/master/fastai/text/learner.py#L120
https://github.com/fastai/fastai/blob/master/fastai/basic_train.py#L362

Or perhaps add it to pred_batch
https://github.com/fastai/fastai/blob/master/fastai/basic_train.py#L338

Happy to provide a PR, but wasn't sure the best way to go about it. 
I'm getting about 10% faster predictions with it off.

**Comment by sgugger** [comment]
Makes sense. Just double-checked it wasn't used when we do things like grad cam, but it's not.
