### ISSUE TITLE
ItemList class holding a method not being used

### ISSUE THREAD

**Issue by dejanbatanjac** [fastai/fastai#2152]
`ItemList` class is not `@dataclass` which should be why it may implement the `__post_init__` method inside.

This `__post_init__` method is what will be added to the unexposed `__init__` method of a `@dataclass`.

As currently `ItemList` is not a dataclass, we may remove this method to eliminate the confusion.
I can create a Pull Request to do so if OK with you.

Specifically the line `self.__post_init__()` is also not needed.

In case we change `ItemList` to `@dataclass` we may add this method back in.

**Comment by sgugger** [comment]
This is probably some legacy code, but I'd need to double check it's not used in any subclass of ItemList before removing. Will try to do that tomorrow.

**Comment by sgugger** [comment]
Scanned through the library and it was used once, so I changed it to use the regular init.
