### ISSUE TITLE
Using cut index in vision.learner fails due to hard-coded model splitting indices

### ISSUE THREAD

**Issue by dhudsmith** [fastai/fastai#2156]
**Describe the bug**
The vision learners accept a parameter called `cut` which is supposed to allow you to remove final layers of the encoder architecture (`arch`). When using any resnet model, I believe cut should work for cut index values 1 through 9 based on the number of layer groups in the encoder portion of the resnet model. Currently, the cut index works for values 7,8, and 9. Any other values return the error: `IndexError: index 6 is out of range`. 

**Provide your installation details**
```text
=== Software === 
python        : 3.6.7
fastai        : 1.0.52
fastprogress  : 0.1.21
torch         : 1.1.0
nvidia driver : 410.79
torch cuda    : 10.0.130 / is available
torch cudnn   : 7501 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 15079MB | Tesla T4

=== Environment === 
platform      : Linux-4.14.79+-x86_64-with-Ubuntu-18.04-bionic
distro        : #1 SMP Wed Dec 19 21:19:13 PST 2018
conda env     : Unknown
python        : /usr/bin/python3
sys.path      : 
/env/python
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/usr/local/lib/python3.6/dist-packages/IPython/extensions
/root/.ipython
```
**To Reproduce**
I have trimmed down the lesson 1 pets notebook to show this issue. See the colab gist here: https://gist.github.com/dhudsmith/b4ef5d2e56e03cb22a2cad5a0d648a78

**Expected behavior**
When passing an integer value to the cut parameter, I expect the learner to create a model based on the passed `arch` where the encoder includes all layers up to but not including the value of cut. 

**Additional context**
Others have run into this problem. See here: https://forums.fast.ai/t/cutting-pretrained-models/31156. In answering that post, I identified why the above bug is occurring. The issue is that the cut parameter is not taken into account when splitting the model near the end of the learner functions. From this diagnosis it seems clear that the issue will apply to some degree for all model types. 

I also describe a partial solution in that thread. It involved revising the `cnn_config` function to the following (only works for resnet18 currently):
```
def cnn_config(arch, **kwargs):
    "Get the metadata associated with `arch`."
    torch.backends.cudnn.benchmark = True
    cut = kwargs.get('cut')
    if kwargs.get('cut') is not None and arch == models.resnet18:
        return {'cut': cut,
                'split': partial(_resnet_split, cut=cut)}
    else:
        return model_meta.get(arch, _default_meta)
```

To apply this solution to all model types would require significant refactoring of the vision.learner code. I would like to get other's take on this issue before I try to implement this type of solution more generally. For now, I have a working solution that my students and I can use. Still I would be happy to contribute if others decide this is worthwhile.

**Comment by sgugger** [comment]
I wouldn't characterize this as a bug: you are passing a custom cut that is incompatible with the default split. You should then pass your own custom split too, with `split_on=...` in your call to `cnn_learner`, using a value like the function `_resnet_split` but with a different index (obliviously not 6).

Please reopen if this doesn't work (not tested but it should).

**Comment by dhudsmith** [comment]
This does work; thank you. That being said, I do think the current behavior will be unexpected to most users, making the cut feature less accessible to many. I think it would be more intuitive if the default behavior was to cut to the last _available_ layer in the truncated encoder rather than a hard-coded value.  

For anyone who finds this post looking to cut resnet models, it's as simple as using a  function like this:
```
def split_fn(m, cut):
  return (m[0][cut-1], m[1])
```
Then in the learner pass `cut=5` and `split_on = partial(split_fn, cut=5)` to cut to the first five layers of the encoder and split at the last layer.
