### ISSUE TITLE
'TensorDataset' object has no attribute path

### ISSUE THREAD

**Issue by redknightlois** [fastai/fastai#2157]
Beyond some data preparation, I have a pretty straightforward code... 

```python
    features_dataset = TensorDataset(features, labels)
    features_loader = torch.utils.data.DataLoader(features_dataset, shuffle=True, batch_size=batch_size, pin_memory=True)
    opt_func = partial(optim.Adam, eps=0.1, betas=(0.9, 0.99))
    learn = Learner(features_loader, model, metrics=[accuracy], wd=1e-3, opt_func=opt_func, bn_wd=False, true_wd=True, loss_func=LabelSmoothingCrossEntropy())
```
 The following error is raised.

```
Traceback (most recent call last):
  File "E:/Src/trendstone-git/src/tf-next3/agents/v1/train.py", line 117, in <module>
    learn = Learner(features_loader, model, metrics=[accuracy], wd=1e-3, opt_func=opt_func, bn_wd=False, true_wd=True, loss_func=LabelSmoothingCrossEntropy())
  File "<string>", line 18, in __init__
  File "C:\Anaconda3\lib\site-packages\fastai\basic_train.py", line 164, in __post_init__
    self.path = Path(ifnone(self.path, self.data.path))
  File "C:\Anaconda3\lib\site-packages\fastai\basic_data.py", line 20, in DataLoader___getattr__
    def DataLoader___getattr__(dl, k:str)->Any: return getattr(dl.dataset, k)
AttributeError: 'TensorDataset' object has no attribute 'path'
```

My installation 

```text
=== Software ===
python        : 3.6.8
fastai        : 1.0.52
fastprogress  : 0.1.21
torch         : 1.1.0
torch cuda    : 10.0 / is available
torch cudnn   : 7401 / is enabled

=== Hardware ===
torch devices : 1
  - gpu0      : GeForce GTX 1070

=== Environment ===
platform      : Windows-10-10.0.18362-SP0
conda env     : base
python        : C:\Anaconda3\python.exe
sys.path      :
C:\Anaconda3\python36.zip
C:\Anaconda3\DLLs
C:\Anaconda3\lib
C:\Anaconda3
C:\Users\feder\AppData\Roaming\Python\Python36\site-packages
C:\Anaconda3\lib\site-packages
C:\Anaconda3\lib\site-packages\win32
C:\Anaconda3\lib\site-packages\win32\lib
C:\Anaconda3\lib\site-packages\Pythonwin
no nvidia-smi is found
```

Also tried master branch and it keeps happening. 

Any idea?

**Comment by renato145** [comment]
You are using a `torch.utils.data.DataLoader` object but `Learner` expects a `DataBunch`. Check https://docs.fast.ai/tutorial.data.html

**Comment by redknightlois** [comment]
Thanks, makes a lot of sense. Probably it would be a good idea to check the instance type and the error message to point to the tutorial itself. That would certainly alleviate new fastai users when dealing with this type of errors which are not clear where they are coming from. Closing issue.

**Comment by Flock1** [comment]
@renato145, I am using `DataBunch` object. But still I am getting the error. This is what I am doing:

```
class NumbersDataset():
    def __init__(self, inputs, labels):
        self.X = inputs
        self.y = labels

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        img_train = cv2.imread(self.X[idx])
        img_mask = cv2.imread(self.y[idx])
        img_train = cv2.resize(img_train, (224,224), interpolation = cv2.INTER_LANCZOS4) 
        img_mask = cv2.resize(img_mask, (224,224), interpolation = cv2.INTER_LANCZOS4) 
        return img_train, img_mask

X = list(df['input_img'])  # This contains the location of the input image 
y = list(df['mask_img'])  # This contains the location of the mask image

X_train, X_valid, y_train, y_valid = train_test_split(
     X, y, test_size=0.33, random_state=42)

dataset_train = NumbersDataset(X_train, y_train)
dataloader_train = DataLoader(dataset_train, batch_size=4, shuffle=True, num_workers=2)

dataset_valid = NumbersDataset(X_valid, y_valid)
dataloader_valid = DataLoader(dataset_valid, batch_size=4, shuffle=True, num_workers=2)

data = DataBunch(train_dl = dataloader_train, valid_dl = dataloader_valid)

leaner = unet_learner(data = data, arch = models.resnet34)
```

And I get this error:

> AttributeError: 'NumbersDataset' object has no attribute 'c'

What do you suggest?

**Comment by renato145** [comment]
Hi, in fastai 'c'  usually refers to the number of classes, for a segmentation databunch to know the number of classes, you need to specify which classes to use.
`data = DataBunch(train_dl = dataloader_train, valid_dl = dataloader_valid, classes=URCLASSES)`

Let me know if this work, I cant check right now.
[https://forums.fast.ai/t/help-on-segmentationitemlist/35046](url)

**Comment by Flock1** [comment]
@renato145, thank you very much for the reply. I kinda figured out by going to the code. However, I want to know what type does it accept? I gave the number of classes both in `list` as well as `int` format but it didn't accept it.

**Comment by renato145** [comment]
I have checked, and the `classes` parameter works for the the `DataBlock` api. Since you are using a custom dataloader I would recommend that you add `c` in your `NumbersDataset`:
```python
class NumbersDataset():
    def __init__(self, inputs, labels):
        self.X = inputs
        self.y = labels
        self.c = something_that_calculates_the_number_of_classes(labels)
```

**Comment by Flock1** [comment]
@renato145, thanks. So what should be the type of `self.c`? Should it be `int` or `list` or what?

**Comment by Flock1** [comment]
@renato145, I found this while scrolling through the page
`data = DataBunch.create(train_ds, valid_ds, bs=2, num_workers=1)`
Maybe I'll need to `create` a DataBunch for FastAI to properly get it.

**Comment by Flock1** [comment]
@renato145, I have one more question. This was about classification. What if I want to do a regression problem? Let's say, image reconstruction using UNet. I can't have number of classes there

**Comment by renato145** [comment]
Hi, if you want to do regression with the `unet_learner` you probably will want to have 1 class (or 3 if you want RBG images as output). You will also need to make sure that you are using an appropriate loss_function for the case. It will be good for you to check the super-resolution approach on lesson 7.

**Comment by Flock1** [comment]
@renato145, thank you very much. I'll do that

**Comment by Flock1** [comment]
@renato145 

So in the `__init__` method, I have added `self.c = 2` as suggested [here](https://docs.fast.ai/basic_data.html) for binary classification. I have also attached my [code](https://gist.github.com/Flock1/1bbf76b6fac2269b9ab005e463c67feb) in case you want to have a look at it. When I run the code, I get the following error:

> AttributeError: ‘dict’ object has no attribute ‘shape’

And when I try to run `datas.show_batch()`, I get this:

>AttributeError: ‘NumbersDataset’ object has no attribute ‘x’

What should I do? I also tried to return the `torch tensor` as an array instead of a dictionary but I still got the above error. Can you help me?

**Comment by Flock1** [comment]
@renato145, can you help me with the above issue?
