### ISSUE TITLE
 TypeError: forward() got an unexpected keyword argument 'reduction'

### ISSUE THREAD

**Issue by jeremycochoy** [fastai/fastai#2158]
**Describe the bug**

Crash when calling `learn_critic.interpret()` from a gan critic learner.

**Provide your installation details**
```text
=== Software === 
python        : 3.6.3
fastai        : 1.0.52
fastprogress  : 0.1.21
torch         : 1.1.0
nvidia driver : 396.51
torch cuda    : 9.0.176 / is available
torch cudnn   : 7501 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11441MB | Tesla K80

=== Environment === 
platform      : Linux-4.9.0-8-amd64-x86_64-with-debian-9.5
distro        : #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08)
conda env     : Unknown
python        : /jet/bin/python
sys.path      : 
/jet/var/python/lib/python36.zip
/jet/var/python/lib/python3.6
/jet/var/python/lib/python3.6/lib-dynload
/jet/var/python/lib/python3.6/site-packages
/jet/var/python/lib/python3.6/site-packages/setuptools-36.0.1-py3.6.egg
/jet/var/python/lib/python3.6/site-packages/wheel-0.30.0a0-py3.6.egg
/jet/var/python/lib/python3.6/site-packages/IPython/extensions
/jet/.ipython
```

**To Reproduce**
```
loss_critic = AdaptiveLoss(nn.BCEWithLogitsLoss())
def create_critic_learner(data, metrics):
    return Learner(data, gan_critic(), metrics=metrics, loss_func=loss_critic, wd=1e-3)
learn_critic = create_critic_learner(data_crit, accuracy_thresh_expand)
interp = learn_critic.interpret()
```

which comes from the notebook https://nbviewer.jupyter.org/github/fastai/course-v3/blob/master/nbs/dl1/lesson7-superres-gan.ipynb

**Expected behavior**
Build an interpret.

**Comment by sgugger** [comment]
There is no interpretation object built for GAN trainings, and no plans to add one with the command `.interpret()` as it would require a custom method to get the predictions that generate images with the generator at the same time. The whole `Interpretation`  classes are thought for labelled data and by definition, GANs aren't.

You can open a thread on the [forum](https://forums.fast.ai/) and try to build this feature with other folks interested.

**Comment by jeremycochoy** [comment]
The critic a binary classifier on images. In this setting, data is a collection of images with two classes.

IMO the documentation is misleading.

**Comment by sgugger** [comment]
We can definitely add an addendum to the documentation clarifying it doesn't work for GANs, I'll merge any PR fixing this.
