### ISSUE TITLE
Update setup requirement for pytest

### ISSUE THREAD

**Issue by dejanbatanjac** [fastai/fastai#2159]
I had the problem with pytest version on my end was 4.0.2 while it must be >= 4.4.0 because of pytest-xdist. (https://github.com/pytest-dev/pytest-xdist/blob/master/setup.py) which lead to problems.

Can someone update the `setup.py` so it can read:

pytest>=4.4.0

---
This is for the `dev_requirements` only.

**Comment by sgugger** [comment]
Fixed, thanks for flagging!
