### ISSUE TITLE
Load_learner expects file to be called "export.pkl"

### ISSUE THREAD

**Issue by attibalazs** [fastai/fastai#2163]
Hi all it looks like the load learner expects the export file to be called "export.pkl"
```
# exporting learner
learn.export(Path(ROOT_PATH)/'fastai-retinanet.pkl')

# loading learner for inference
learn = load_learner(Path(ROOT_PATH)/'fastai-retinanet.pkl')
```

> NotADirectoryError: [Errno 20] Not a directory: '/home/lab/data/fastai-retinanet.pkl/export.pkl'

**Comment by Joldnine** [comment]
Hi @attibalazs , you may try 
`learn = load_learner(Path(ROOT_PATH)/'fastai-retinanet')`
I believe fastai will attribute postfix `.pkl` for you if it is a file.

**Comment by attibalazs** [comment]
yes that works thank you !

**Comment by livinghumanz** [comment]
i get this error
`NameError: name 'load_model' is not defined`

**Comment by livinghumanz** [comment]
this doesn't work for **`fastai v2`**

**Comment by AbdullahJirjees** [comment]
Hello everyone, 
I am having an issue with the dataloader while exporting the pkl file, any idea? I am using icevision on googl
![Screenshot 2022-11-06 205628](https://user-images.githubusercontent.com/13992604/200224776-2c767683-29b2-4300-8a2e-ea9422105e64.png)
e colab
