### ISSUE TITLE
Using custom sampler

### ISSUE THREAD

**Issue by msrdinesh** [fastai/fastai#2167]
This is continuation of [1995](https://github.com/fastai/fastai/issues/1995).
I have tried 
'data_class.train_dl = data_class.train_dl.new(shuffle=False, sampler=torch.utils.data.sampler.WeightedRandomSampler)'. 
I got the following error 
'ValueError: sampler should be an instance of torch.utils.data.Sampler, but got sampler=<class 'torch.utils.data.sampler.WeightedRandomSampler'>'

**Comment by sgugger** [comment]
You need to instantiate your sampler: `WeightedRandomSampler()` with the parenthesis.
