### ISSUE TITLE
plot_sixel fails from command line

### ISSUE THREAD

**Issue by bulrich** [fastai/fastai#2170]
**Describe the bug**
Running `learn.recorder.plot()` from the command line fails with:

```
Traceback (most recent call last):
  File "train_mnist.py", line 5, in <module>
    @call_parse
  File "/home/bulrich/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/script.py", line 40, in call_parse
    func(**args.__dict__)
  File "train_mnist.py", line 12, in main
    learn.recorder.plot()
  File "/home/bulrich/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/basic_train.py", line 556, in plot
    if not IN_NOTEBOOK: plot_sixel(fig)
  File "/home/bulrich/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/sixel.py", line 21, in plot_sixel
    res = _sixel_encode(fig.canvas.buffer_rgba(), fig.get_figwidth()* dpi, fig.get_figheight() * dpi)
  File "/home/bulrich/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/sixel.py", line 10, in _sixel_encode
    libsixel.sixel_dither_initialize(dither, data, w, h, libsixel.SIXEL_PIXELFORMAT_RGBA8888)
  File "/home/bulrich/anaconda3/envs/fastai/lib/python3.7/site-packages/libsixel/__init__.py", line 506, in sixel_dither_initialize
    quality_mode)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

**Provide your installation details**
```text
=== Software ===
python        : 3.7.3
fastai        : 1.0.53.post2
fastprogress  : 0.1.21
torch         : 1.1.0
nvidia driver : 410.78
torch cuda    : 10.0.130 / is available
torch cudnn   : 7501 / is enabled

=== Hardware ===
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11178MB | GeForce GTX 1080 Ti

=== Environment ===
platform      : Linux-4.15.0-46-generic-x86_64-with-debian-buster-sid
distro        : #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019
conda env     : fastai
python        : /home/bulrich/anaconda3/envs/fastai/bin/python
sys.path      : /home/bulrich/dev/fastai/examples
/home/bulrich/anaconda3/envs/fastai/lib/python37.zip
/home/bulrich/anaconda3/envs/fastai/lib/python3.7
/home/bulrich/anaconda3/envs/fastai/lib/python3.7/lib-dynload
/home/bulrich/anaconda3/envs/fastai/lib/python3.7/site-packages
```

**To Reproduce**
Run this from the command line:
```python
from fastai.script import *
from fastai.vision import *
from fastai.distributed import *

@call_parse
def main():
    path = url2path(URLs.MNIST_SAMPLE)
    tfms = (rand_pad(2, 28), [])
    data = ImageDataBunch.from_folder(path, ds_tfms=tfms, bs=64).normalize(imagenet_stats)
    learn = cnn_learner(data, models.resnet18, metrics=accuracy)
    learn.fit_one_cycle(1, 0.02)
    learn.recorder.plot()
```

**Expected behavior**
I expect the chart to appear in my terminal, which supports sixel.

**Additional context**
I've confirmed that `libsixel` is working from either command line via `img2sixel` and also via `libsixel-python` v0.5.0 as verified by their [Python example script](https://github.com/saitoha/libsixel/blob/master/examples/python/converter.py).

**Comment by sgugger** [comment]
I have no problem with this script on my side (note that `learn.recorder.plot()` is meant to be used in conjunction with `learn.lr_find()`, not the `fit` methods). Which terminal are you using?

**Comment by bulrich** [comment]
I’m using iTerm2 version 3.3.0beta12 on macOS, and haven’t noticed any issues with its sixel support so far. Happy to try whatever terminal you’re using on any OS to verify the behavior.

**Comment by sgugger** [comment]
Ok, don't have a mac, so I checked it worked with WSLtty on windows 10.

**Comment by bulrich** [comment]
Unfortunately, I had the same results running WLStty on Windows 10:
```Traceback (most recent call last):
  File "train_mnist.py", line 5, in <module>
    @call_parse
  File "/home/bulrich/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/script.py", line 40, in call_parse
    func(**args.__dict__)
  File "train_mnist.py", line 12, in main
    learn.recorder.plot()
  File "/home/bulrich/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/basic_train.py", line 556, in plot
    if not IN_NOTEBOOK: plot_sixel(fig)
  File "/home/bulrich/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/sixel.py", line 21, in plot_sixel
    res = _sixel_encode(fig.canvas.buffer_rgba(), fig.get_figwidth()* dpi, fig.get_figheight() * dpi)
  File "/home/bulrich/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/sixel.py", line 10, in _sixel_encode
    libsixel.sixel_dither_initialize(dither, data, w, h, libsixel.SIXEL_PIXELFORMAT_RGBA8888)
  File "/home/bulrich/anaconda3/envs/fastai/lib/python3.7/site-packages/libsixel/__init__.py", line 506, in sixel_dither_initialize
    quality_mode)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

**Comment by sgugger** [comment]
That's weird. Are we on the same libsixel-python version? I have 0.5.0 on my side.

**Comment by bulrich** [comment]
Me too. I've also verified the `libsixel-python` install by successfully running their utility: https://github.com/saitoha/libsixel/blob/master/examples/python/converter.py

**Comment by sgugger** [comment]
I am a bit at a loss then. Can you plot a simple matplotlib figure? For instance can you see something with this?
```
from fastai.script import *
from fastai.vision import *
from fastai.sixel import *

@call_parse
def main():
    
    fig, ax = plt.subplots(1,1)
    x = np.linspace(0,100)
    y = np.exp(x)
    ax.plot(x, y)
    ax.set_ylabel("Loss")
    ax.set_xlabel("Learning Rate")
    ax.set_xscale('log')
    ax.xaxis.set_major_formatter(plt.FormatStrFormatter('%.0e'))
    plot_sixel(fig)
```

**Comment by bulrich** [comment]
Thanks for scratching your head over this in any case.

Your matplotlib example doesn't work either, also failing with a `ctypes.ArgumentError`:

```
  File "plottest.py", line 16, in main
    plot_sixel(fig)
  File "/home/bulrich/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/sixel.py", line 21, in plot_sixel
    res = _sixel_encode(fig.canvas.buffer_rgba(), fig.get_figwidth()* dpi, fig.get_figheight() * dpi)
  File "/home/bulrich/anaconda3/envs/fastai/lib/python3.7/site-packages/fastai/sixel.py", line 10, in _sixel_encode
    libsixel.sixel_dither_initialize(dither, data, w, h, libsixel.SIXEL_PIXELFORMAT_RGBA8888)
  File "/home/bulrich/anaconda3/envs/fastai/lib/python3.7/site-packages/libsixel/__init__.py", line 506, in sixel_dither_initialize
    quality_mode)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

**Comment by sgugger** [comment]
Ok so it's clearly that line that fails for you
```
libsixel.sixel_dither_initialize(dither, data, w, h, libsixel.SIXEL_PIXELFORMAT_RGBA8888)
```
in fastai.sixel. I'm not too familiar with libsixel and din't write that part but maybe there is another flag that makes this work for you?

**Comment by bulrich** [comment]
Yes, it fails with the same error:
```
Traceback (most recent call last):
  File "sixeltest.py", line 30, in <module>
    plot_sixel(fig)
  File "sixeltest.py", line 21, in plot_sixel
    res = _sixel_encode(fig.canvas.buffer_rgba(), fig.get_figwidth()* dpi, fig.get_figheight() * dpi)
  File "sixeltest.py", line 10, in _sixel_encode
    libsixel.sixel_dither_initialize(dither, data, w, h, libsixel.SIXEL_PIXELFORMAT_RGBA8888)
  File "/home/bulrich/anaconda3/envs/fastai/lib/python3.7/site-packages/libsixel/__init__.py", line 506, in sixel_dither_initialize
    quality_mode)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

**Comment by sgugger** [comment]
As far as I can tell, this seems to be a bug in your install or libsixel: this is a simple example unrelated to fastai taht should work. Maybe file an issue with libsixel if re-installing doesn't fix the problem?

**Comment by bulrich** [comment]
I agree. I am unsuccessfully attempting to find an alternate value for some of the default arguments to `sixel_dither_initialize` that works for both of us, and will update this issue if I find one. If not, I'll log an issue with the libsixel folks.

Thanks again for your help with this. I'm closing the issue.

**Comment by Ontheroad123** [comment]
> import numpy as np
> import matplotlib.pyplot as plt
> import libsixel,io
> 
> def _sixel_encode(data, width, height):
>     s = io.BytesIO()
>     output = libsixel.sixel_output_new(lambda data, s: s.write(data), s)
>     dither = libsixel.sixel_dither_new(256)
>     w,h = int(width),int(height)
>     libsixel.sixel_dither_initialize(dither, data, w, h, libsixel.SIXEL_PIXELFORMAT_RGBA8888)
>     libsixel.sixel_encode(data, w, h, 1, dither, output)
>     return s.getvalue().decode('ascii')
> 
> def plot_sixel(fig=None):
>     if not libsixel:
>         warn("You could see this plot with `libsixel`. See https://github.com/saitoha/libsixel")
>         return
>     if fig is None: fig = plt.gcf()
>     fig.canvas.draw()
>     dpi = fig.get_dpi()
>     res = _sixel_encode(fig.canvas.buffer_rgba(), fig.get_figwidth()* dpi, fig.get_figheight() * dpi)
>     print(res)
> 
> fig, ax = plt.subplots(1,1)
> x = np.linspace(0,100)
> y = np.exp(x)
> ax.plot(x, y)
> ax.set_ylabel("Loss")
> ax.set_xlabel("Learning Rate")
> plot_sixel(fig)

I have the same error:
    libsixel.sixel_dither_initialize(dither, data, w, h, libsixel.SIXEL_PIXELFORMAT_RGBA8888)
  File "/data/soft/anaconda3/envs/hq1_workspace/lib/python3.6/site-packages/libsixel/__init__.py", line 506, in sixel_dither_initialize
    quality_mode)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
and i have re-install libsixel twice

**Comment by Ontheroad123** [comment]
when we have the orror: ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type,
i have a temporary idea:
add code in the front: 
from fastprogress.fastprogress import IN_NOTEBOOK
IN_NOTEBOOK=True
and improve the code: learn.recorder.plot() to learn.recorder.plot(suggestion=True),

you can see the origin code:*/fastai/basic_train.py
in class Recorder(), see the function plot() last code:
if not IN_NOTEBOOK: plot_sixel(fig)
because plot first choice is notebook,  second choice plot_sixel(fig),
we can force choice notebook,that will be ok,and will print the best lr in epoch

**Comment by shmilee** [comment]
> Ok so it's clearly that line that fails for you
> 
> ```
> libsixel.sixel_dither_initialize(dither, data, w, h, libsixel.SIXEL_PIXELFORMAT_RGBA8888)
> ```
> 
> in fastai.sixel. I'm not too familiar with libsixel and din't write that part but maybe there is another flag that makes this work for you?
> 
> This is a minimum example at this stage that works for me (and probably not for you)
> 
> ```
> import numpy as np
> import matplotlib.pyplot as plt
> import libsixel,io
> 
> def _sixel_encode(data, width, height):
>     s = io.BytesIO()
>     output = libsixel.sixel_output_new(lambda data, s: s.write(data), s)
>     dither = libsixel.sixel_dither_new(256)
>     w,h = int(width),int(height)
>     libsixel.sixel_dither_initialize(dither, data, w, h, libsixel.SIXEL_PIXELFORMAT_RGBA8888)
>     libsixel.sixel_encode(data, w, h, 1, dither, output)
>     return s.getvalue().decode('ascii')
> 
> def plot_sixel(fig=None):
>     if not libsixel:
>         warn("You could see this plot with `libsixel`. See https://github.com/saitoha/libsixel")
>         return
>     if fig is None: fig = plt.gcf()
>     fig.canvas.draw()
>     dpi = fig.get_dpi()
>     res = _sixel_encode(fig.canvas.buffer_rgba(), fig.get_figwidth()* dpi, fig.get_figheight() * dpi)
>     print(res)
> 
> fig, ax = plt.subplots(1,1)
> x = np.linspace(0,100)
> y = np.exp(x)
> ax.plot(x, y)
> ax.set_ylabel("Loss")
> ax.set_xlabel("Learning Rate")
> plot_sixel(fig)
> ```

Use code above，I get an error like yours:
```usr/lib/python3.8/site-packages/libsixel/__init__.py in sixel_dither_initialize(dither, data, width, height, pixelformat, method_for_largest, method_for_rep, quality_mode)
    516     _sixel.sixel_dither_initialize.argtypes = [c_void_p, c_char_p, c_int, c_int, c_int,
    517                                               c_int, c_int, c_int]
--> 518     status = _sixel.sixel_dither_initialize(dither, data, width, height, pixelformat,
    519                                             method_for_largest,
    520                                             method_for_rep,

ArgumentError: argument 2: <class 'TypeError'>: wrong type
```
After reading saitoha‘s [example code](https://github.com/saitoha/libsixel/blob/5db717dfef6fa327cd4025e7352550f63d20699c/examples/python/converter.py), edit this line
```
res = _sixel_encode(fig.canvas.buffer_rgba(), fig.get_figwidth()* dpi, fig.get_figheight() * dpi)
```
to
```
res = _sixel_encode(fig.canvas.buffer_rgba().tobytes(), fig.get_figwidth()* dpi, fig.get_figheight() * dpi)
```
Then all works fine.
