### ISSUE TITLE
TextClassificationInterpretion.show_top_losses() doesn't use ordered preds

### ISSUE THREAD

**Issue by oegedijk** [fastai/fastai#2182]
**Describe the bug**
The `TextClassificationInterpretion.show_top_losses()` method takes the text and the actual label from 
` self.data.dl(self.ds_type).dataset[idx]` and the predicted class, loss and predicted probability from self.pred_class[idx], self.losses[idx] and self.preds[idx][cl].

However the former is ordered and the latter is not, so the indexes actually do not line up. 

Example

```
classifier = text_classifier_learner(data_clas, AWD_LSTM, config=clas_config, drop_mult=0.3, pretrained=False)
classifier.load_encoder('bericht_enc')
classifier.load('clas_mdl')
interp = TextClassificationInterpretation.from_learner(classifier)
interp.show_top_losses(10)
```
Output (text omitted for GDPR reasons):
```
Text | Prediction | Actual | Loss | Probability
"" | 0 | 1 | 4.54 | 0.01
"" | 0 | 0 | 2.19 | 0.89
"" | 0 | 1 | 2.17 | 0.11
"" | 0 | 0 | 2.12 | 0.88
"" | 0 | 0 | 2.06 | 0.87
"" | 0 | 1 | 2.05 | 0.13
"" | 0 | 0 | 2.03 | 0.87
```

The losses are indeed nicely sorted from high to low, but a lot of the predictions and actuals actually align! (Not something you would associate with a high loss). Also the predicted probability of the actual class is not low and increasing as you would expect. 

However when you pass order=True to classifier.get_preds(), you do get the right output:

```
interp2 = TextClassificationInterpretation(classifier, *classifier.get_preds(with_loss=True, ordered=True))
interp2.show_top_losses(10)
```
output:
```
Text | Prediction | Actual | Loss | Probability
"" | 0 | 1 | 5.62 | 0.00
"" | 0 | 1 | 4.54 | 0.01
"" | 0 | 1 | 4.54 | 0.01
"" | 0 | 1 | 2.48 | 0.08
"" | 0 | 1 | 2.19 | 0.11
"" | 0 | 1 | 2.17 | 0.11
"" | 0 | 1 | 2.12 | 0.12
"" | 0 | 1 | 2.06 | 0.13
"" | 0 | 1 | 2.05 | 0.13
"" | 0 | 1 | 2.03 | 0.13
```

Issue seems to be the Interpretation class' from_learner method. When you change 
`preds_res = learn.get_preds(ds_type=ds_type, with_loss=True)` to
`preds_res = learn.get_preds(ds_type=ds_type, with_loss=True, ordered=True) ` the issue disappears. 

**Provide your installation details**
=== Software === 
python       : 3.7.3
fastai       : 1.0.53.post2
fastprogress : 0.1.21
torch        : 1.1.0
torch cuda   : None / is **Not available** 
-->

**Comment by sgugger** [comment]
Right, do you mind making a PR with that change? Thanks.

**Comment by sgugger** [comment]
Fixed by your PR.
