### ISSUE TITLE
layers_groups in Learner is a list of Len 1

### ISSUE THREAD

**Issue by Etienne-Meunier** [fastai/fastai#2187]
**Describe the bug**

When a Learner is created using a Model ( torch.nn.modules.Module) the learner will extract the layers_groups in the __post_init__ but will store them in a list so when other functions try to get the number of layers they will have one and not the actual number, which causes errors.

**Provide your installation details**

```text
=== Software === 
python        : 3.6.7
fastai        : 1.0.54
fastprogress  : 0.1.21
torch         : 1.0.1.post2
nvidia driver : 418.56
torch cuda    : 9.0.176 / is available
torch cudnn   : 7402 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 4042MB | GeForce MX150

=== Environment === 
platform      : Linux-4.15.0-52-generic-x86_64-with-Ubuntu-18.04-bionic
distro        : #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019
conda env     : Unknown
python        : /usr/bin/python3
sys.path      : /usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload

/home/etienne/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/etienne/.local/lib/python3.6/site-packages/IPython/extensions
/home/etienne/.ipython
```

**To Reproduce**

https://gist.github.com/Etienne-Meunier/6dc7cc11f84b72c8c839b09d88a53949

**Additional context**
Looking at the source code of Learner I think it is due to :
````python
if not self.layer_groups: self.layer_groups = [nn.Sequential(*flatten_model(self.model))]
````
on line 168, the [...]  are creating a list over Sequential wich is already treated as a list

**Comment by sgugger** [comment]
This is not a bug, if you don't provide layer groups or build some later with `Learner.split`, all parameters are in the same parameter groups and there is no freezing/unfreezing or differential learning rates.

That's why functions like `cnn_learner` exist, to do this split for you behind the scenes.
