### ISSUE TITLE
Implement "Averaging Weights Leads to Wider Optima and Better Generalization"

### ISSUE THREAD

**Issue by wdhorton** [fastai/fastai#219]
I saw the Twitter thread on this arxiv paper today (Twitter: https://twitter.com/andrewgwils/status/974087637828071429, arxiv: https://arxiv.org/abs/1803.05407), and it was mentioned that it might be useful to include in the fastai lib. So I wanted to ask two questions: 1) @jph00 is this something that you'd be interested in including in the library, and 2) could I take a crack at making a making a PR with an implementation?

**Comment by jph00** [comment]
Absolutely yes! :) Be sure to do plenty of testing to ensure it works as
well as it does in the paper on the same datasets, where possible.
