### ISSUE TITLE
DataBunch constructor behaves badly when the underlying DataLoader has a custom collate_fn

### ISSUE THREAD

**Issue by szhang104** [fastai/fastai#2193]
**Describe the bug**
I am trying to use the fastai training facilities (`basic_learner`) to prevent writing the boilerplates. My code uses `torch_geometric` library, which runs on a subclassed `DataLoader` class, 
 essentially a pytorch `DataLoader` with a custom `collate_fn`. See [here](https://github.com/rusty1s/pytorch_geometric/blob/83f6c30757e8b80c6351228bbc67bb1109be1d85/torch_geometric/data/dataloader.py#L31)

- Issue 1: It seems fastai training needs to run with `DataBunch` which constructs `DeviceDataBunch`, and its constructor ignores the existing `collate_fn` and replaces it with whatever in the constructor argument. (See [this](https://github.com/fastai/fastai/blob/abc5334ff09cd2a195125021b32bd1419af6d957/fastai/basic_data.py#L95) ) This creates unnecessary surprises when obtaining batch data, and I don't understand the purpose of such arrangements.

- Issue 2: Even when I specify the special `collate_fn` explicitly exactly like the `torch_geometric` version in the `DataBunch` class constructor, I again run into trouble. It seems the `DataBunch` constructor needs to build a copy of the `train_dl` to be `fix_dl`, and again with a custom `collate_fn` in `train_dl`, the copying will fail because `collate_fn` has been specified twice in function `intercept_args`.
//---
It is due to [this](https://github.com/fastai/fastai/blob/abc5334ff09cd2a195125021b32bd1419af6d957/fastai/basic_data.py#L64), where the `new_kwargs` contains a `collate_fn` while the `torch_geometric` version of `DataLoader` constructor does not expect the user to provide it.

**Provide your installation details**
```
=== Software === 
python        : 3.7.3
fastai        : 1.0.54
fastprogress  : 0.1.21
torch         : 1.1.0
nvidia driver : 430.26
torch cuda    : 10.0.130 / is available
torch cudnn   : 7501 / is enabled
=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 8116MB | GeForce GTX 1070
=== Environment === 
platform      : Linux-5.1.15-arch1-1-ARCH-x86_64-with-arch
distro        : #1 SMP PREEMPT Tue Jun 25 04:49:39 UTC 2019
conda env     : base
python        : /opt/anaconda/bin/python
sys.path      : /home/sz/dev/graphnn
/home/sz/.IntelliJIdea2019.1/config/plugins/python/helpers/pycharm_display
/home/sz/.IntelliJIdea2019.1/config/plugins/python/helpers/third_party/thriftpy
/home/sz/.IntelliJIdea2019.1/config/plugins/python/helpers/pydev
/home/sz/.IntelliJIdea2019.1/system/cythonExtensions
/opt/anaconda/lib/python37.zip
/opt/anaconda/lib/python3.7
/opt/anaconda/lib/python3.7/lib-dynload
/opt/anaconda/lib/python3.7/site-packages
/home/sz/.IntelliJIdea2019.1/config/plugins/python/helpers/pycharm_matplotlib_backend
/opt/anaconda/lib/python3.7/site-packages/IPython/extensions
```

**To Reproduce**
```python
from fastai.torch_core import *
from fastai.train import Learner
from fastai.basic_data import DataBunch
from torch_geometric.data import DataLoader
from torch_geometric.data import Batch
from torch_geometric.datasets import ShapeNet


ds = ShapeNet(root='/tmp/ShapeNet', category='Airplane')
loader1 = DataLoader(ds[0:10], batch_size=2)
loader2 = DataLoader(ds[10:20], batch_size=2)
db = DataBunch(
train_dl=loader1,
valid_dl=loader2
)
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
Mmmm, there is little I can do about the second problem: subclassing the DataLoader from PyTorch and removing arguments in the constructor is definitely not compatible with fastai.

A workaround if you just want to train a model is to create your own data class, with an attribute `train_dl`, `valid_dl` and `device`. If you pass that to Learner, you should be fine.

fastai v2 won't require a custom collate function like v1 does, so the broader issue will be solved in it, for the short term, there is nothing else I can do.
