### ISSUE TITLE
Prevent catastrophic backtracking wikitext utils.py

### ISSUE THREAD

**Issue by miktoki** [fastai/fastai#2194]
[utils.py](https://github.com/fastai/fastai/blob/1700eaa771bd3e66fe582aa4add999fdd269d240/courses/dl2/imdb_scripts/utils.py#L17) uses a regex pattern which will lead to catastrophic backtracking
See:
https://stackoverflow.com/questions/56847979/regex-match-number-freeze
https://stackoverflow.com/questions/27237579/simple-alphanumeric-regex-single-spacing-without-catastrophic-backtracking

The proposed solution is to replace the regex pattern:
    ```number_match_re = re.compile(r'^([0-9]+[,.]?)+$')```
to 
    ```number_match_re = re.compile(r'^[0-9]+(?:[,.][0-9]*)*$')```

**Comment by sgugger** [comment]
Sure, would you mind making a PR with it?

**Comment by miktoki** [comment]
Sure.

This seems to be related to the ulmfit_v1 branch and is not on master. Should I add some tests, and if so, where would be the right place to put them?

**Comment by sgugger** [comment]
This is mostly legacy code now, so just the fix is enough. New version of UlmFIT with v1 is [here](https://github.com/fastai/fastai/blob/master/examples/ULMFit.ipynb)

**Comment by sgugger** [comment]
Just checking if you're still interested in doing a PR for the fix. I can do it otherwise.

**Comment by ijbo** [comment]
hi Sylvain  : Please let me know how I can contribute to do the PR ?

Thanks,
Jyoti Bose

**Comment by miktoki** [comment]
Sorry, was a bit delayed, but the PR is done now.

**Comment by sgugger** [comment]
Thanks, closing this since it's merged.
