### ISSUE TITLE
Min-max zoom instead of max zoom 

### ISSUE THREAD

**Issue by feribg** [fastai/fastai#220]
I have a PR if that would be of interest that accepts max_zoom as being a tuple and if so treats it as min,max zoom level instead of a single max zoom. This is useful for images where we want to focus on the center area, which is quite often the case in practice. Here is the typical use case:

```
tfms = tfms_from_model(f_model, sz, aug_tfms=transforms, max_zoom=(2,2.5), crop_type=CropType.CENTER)
```
Is that something worth adding ?

**Comment by jph00** [comment]
Sounds reasonable to me.
