### ISSUE TITLE
Error on get method of TextList with empty vocab

### ISSUE THREAD

**Issue by StatisticDean** [fastai/fastai#2208]
My installation
=== Software === 
python       : 3.6.8
fastai       : 1.0.55.dev0
fastprogress : 0.1.21
torch        : 1.0.0
torch cuda   : 10.0.130

When creating a `TextList` with an empty `Vocab` there is an error in the `get` call, 

```
def get(self, i):
    o = super().get(i)
    return Text(o, self.vocab.textify(o, self.sep))
```
`AttributeError: 'NoneType' object has no attribute 'textify'`

This happens when trying to get an item or just in the `__repr__` call. This is because the vocab is created when the processors are called which happens after the labels have been created : 
Code from `ItemLists` class  in `data_block.py` : 

```
    def label_from_lists(self, train_labels:Iterator, valid_labels:Iterator, label_cls:Callable=None, **kwargs)->'LabelList':
        "Use the labels in `train_labels` and `valid_labels` to label the data. `label_cls` will overwrite the default."
        label_cls = self.train.get_label_cls(train_labels, label_cls)
        self.train = self.train._label_list(x=self.train, y=label_cls(train_labels, **kwargs))
        self.valid = self.valid._label_list(x=self.valid, y=self.train.y.new(valid_labels, **kwargs))
        self.__class__ = LabelLists
        self.process()
        return self
```

The following can be done to reproduce this issue : 

```
from fastai import *
from fastai.text import *

data = TextList(['a' for i in range(10)])
data_split = data.split_by_rand_pct()
data_labeled = data_split.label_empty()
```

`data` and `data_split` will raise this error when their `__repr__` method is called but everything will work as expected in data_labeled.

I'm not sure of the right way to fix this, maybe the `get` method could be changed to have another behavior if the vocab is `None`.

**Comment by sgugger** [comment]
Thanks for flagging, I was supposed to tackle that a long time ago but forgot. Just returning o when there is no vocab is fine and give a consistent representation.

**Comment by StatisticDean** [comment]
That's great. Thanks for Fixing this :)
