### ISSUE TITLE
Learn.validate gives metrics error unless learn.fit is called

### ISSUE THREAD

**Issue by henrique** [fastai/fastai#2213]
I've noticed that you can't call Learner.validate() before training the model at least once.
As I'm loading a non-fastai pre-trained model, I'd like to check if everything is fine, so I'd think it's a valid use case.
Same report in an unanswered post in the forum:
https://forums.fast.ai/t/learn-validate-gives-metrics-error-unless-learn-fit-is-called/45453
> [quote="xnet, post:1, topic:45453, full:true"]
> When deploying or just running my model on inference mode, I use learn.validate(trn_data.train_dl, metrics=[error_rate, m_pre, m_rec, m_f1]), where m_x are custom metrics using the fastai configurable metrics.
> 
> I get an error like: AttributeError: ‘Precision’ object has no attribute ‘n_classes’
> 
> The only way around this is to train the model using learn.fit before calling learn.validate. Is there a better workaround for this?
> [/quote]

**Comment by sgugger** [comment]
Thanks for flagging! Should be fixed now.
