### ISSUE TITLE
How to handle multi-output problem such as QA? 

### ISSUE THREAD

**Issue by sakuranew** [fastai/fastai#2218]
How to handle multi-output problem such as QA? 
The target should have both start position label and end position label,but i find DataBunch doesn't work...
For the final multi-loss i can write a callback,but how to handle the input?
thank you

**Comment by sgugger** [comment]
Hi there, those questions should be asked on the [forum](https://forums.fast.ai/) where you'll find plenty of help. Issues on GitHub are for standing bugs only.
