### ISSUE TITLE
Adding se_resnext101_32x4d

### ISSUE THREAD

**Issue by swagato-c** [fastai/fastai#2221]
Now that the pull request [128](https://github.com/Cadene/pretrained-models.pytorch/pull/128) been merged, pls add  `resnext101_32x4d` and `resnext101_64x4d` in `fastai/vision/models/cadene_models.py` in the `master` branch.

I guess the code should be:
```python
def se_resnext101_32x4d(pretrained:bool=False): return get_model('se_resnext101_32x4d', pretrained)
def se_resnext101_64x4d(pretrained:bool=False): return get_model('se_resnext101_64x4d', pretrained)
model_meta[se_resnext101_32x4d] = _se_resnet_meta
model_meta[se_resnext101_64x4d] = _se_resnet_meta
```

**Comment by sgugger** [comment]
Sure, why don't you suggest a PR for it?
In general we keep issues for known bugs only and suggest new features on the [forum](https://forums.fast.ai/) or directly in PRs.

**Comment by tmabraham** [comment]
@swagato-c I am confused. You are talking about resnext101 but then your code has se_resnext101. Also, I don't think se_resnext101_64x4d exists. You will need separate metadata for the resnext models.

**Comment by swagato-c** [comment]
@tmabraham  Sorry I actually meant se_resnext and not resnext  and yes we don't have se_resnext101_64x4d. I'm changing the title

**Comment by sgugger** [comment]
Closing this since #2223 was merged.
