### ISSUE TITLE
OverSamplingCallback not working for MultiLabel Image Classification

### ISSUE THREAD

**Issue by swagato-c** [fastai/fastai#2226]
**Describe the bug**
Trying to oversample using `OverSamplingCallback` on multi-label dataset like `planet` gives the error `IndexError: arrays used as indices must be of integer (or boolean) type` on line:
```python
16         self.weights = (weights if weights is not None else
---> 17                         torch.DoubleTensor((1/counts)[self.labels]))
```

**Provide your installation details**
```text
=== Software === 
python       : 3.6.8
fastai       : 1.0.56.dev0
fastprogress : 0.1.21
torch        : 1.1.0
torch cuda   : 10.0.130 / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Linux-4.14.79+-x86_64-with-Ubuntu-18.04-bionic
distro       : #1 SMP Wed Dec 19 21:19:13 PST 2018
conda env    : Unknown
python       : /usr/bin/python3
sys.path     : 
/env/python
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/usr/local/lib/python3.6/dist-packages/IPython/extensions
/root/.ipython
no supported gpus found on this system
```
**To Reproduce**
```python3
from fastai import *
from fastai.vision import *
from fastai.callbacks import *
planet = untar_data(URLs.PLANET_TINY)
planet_tfms = get_transforms(flip_vert=True, max_lighting=0.1, max_zoom=1.05, max_warp=0.)
data = ImageDataBunch.from_csv(planet, folder='train', size=128, suffix='.jpg', label_delim = ' ', ds_tfms=planet_tfms)
learn = cnn_learner(data,models.resnet18,callback_fns=[OverSamplingCallback])
learn.lr_find()
```
**Expected behavior**
A balanced dataset due to oversampling of classes with low frequency in an imbalanced dataset during training.

**Comment by tmabraham** [comment]
I did not design the callback with multi-label classification problems in mind. It may be hard because it is meant to adjust the class distribution based on their frequencies, but different labels have different distributions but they are also multiple labels per image.

**Comment by sgugger** [comment]
Yes that would require a different sampler entirely. @tmabraham can you document properly that the callback only work for single-label problems? Thanks.
Closing the issue, asking for new features should be done on the [forum](https://forums.fast.ai)
