### ISSUE TITLE
"Backwards" error 

### ISSUE THREAD

**Issue by vdyagilev** [fastai/fastai#2241]
I have a picture of my jupyter notebook here with the error https://prnt.sc/oipyfd
Basically, I am getting an AttributeError: backwards when creating a language_model_learner from a DataBunch. I think there is something wrong with the formatting of my input file but I can't seem to find an answer in the documentation.

**Comment by vdyagilev** [comment]
Here is the rest of the code I wrote if it helps
http://prntscr.com/oiq0c4

**Comment by sgugger** [comment]
You created a TextDataBunch and not a TextLMDataBunch, this is why you have this error.
