### ISSUE TITLE
label_for_lm() destroys the dataset.

### ISSUE THREAD

**Issue by StatisticDean** [fastai/fastai#2247]
While using `label_for_lm()` on a splitted `Textlist`, I noticed that all my data was gone and replaced by a list of 0. I reproduced this bug on a smaller example : 

```
from fastai import *
from fastai.text import *
vocab = Vocab(['a', 'b'])
data = TextList([[0, 0], [0,1]], vocab=vocab, sep='').split_by_rand_pct(0.5)
data
```
Output : 

```
ItemLists;

Train: TextList (1 items)
ab
Path: .;

Valid: TextList (1 items)
aa
Path: .;

Test: None
```
Now, I do `data.label_for_lm()`

Output : 

```
LabelLists;

Train: LabelList (1 items)
x: LMTextList
aaa
y: LMLabelList

Path: .;

Valid: LabelList (1 items)
x: LMTextList
aaa
y: LMLabelList

Path: .;

Test: None
```

Expected output : 

```
LabelLists;

Train: LabelList (1 items)
x: LMTextList
ab
y: LMLabelList

Path: .;

Valid: LabelList (1 items)
x: LMTextList
aa
y: LMLabelList

Path: .;

Test: None
```
the issue is that `data.train.items` and `data.valid.items` are now both `array([[0, 0, 0]])`

My install : 
```text
=== Software === 
python       : 3.7.3
fastai       : 1.0.56.dev0
fastprogress : 0.1.21
torch        : 1.1.0
torch cuda   : 9.0.176 / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Linux-4.15.0-55-generic-x86_64-with-debian-buster-sid
distro       : #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019
conda env    : speech_recognition
```

**Comment by sgugger** [comment]
The default of `TextList` is to receive texts that it will tokenize and numericalize. You are passing ids so you should deactivate this by adding `processsor = []` in your arguments.

**Comment by StatisticDean** [comment]
You're right ! I forgot that Processors were called at labelization, hence why the error happens at this moment. Thank you.
