### ISSUE TITLE
error importinng from fastai.metrics import error_rate

### ISSUE THREAD

**Issue by girmax** [fastai/fastai#2250]
`
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-13-cdd5b74a192e> in <module>
      1 #from fastai.vision import *
----> 2 from fastai.metrics import error_rate

~\.conda\envs\fastai\lib\site-packages\fastai\metrics.py in <module>
      1 "Implements various metrics to measure training accuracy"
----> 2 from .torch_core import *
      3 from .callback import *
      4 from .layers import *
      5 from .basic_train import LearnerCallback

~\.conda\envs\fastai\lib\site-packages\fastai\torch_core.py in <module>
      1 "Utility functions to help deal with tensors"
----> 2 from .imports.torch import *
      3 from .core import *
      4 from collections import OrderedDict
      5 from torch.nn.parallel import DistributedDataParallel

~\.conda\envs\fastai\lib\site-packages\fastai\imports\__init__.py in <module>
----> 1 from .core import *
      2 from .torch import *

~\.conda\envs\fastai\lib\site-packages\fastai\imports\core.py in <module>
      1 import csv, gc, gzip, os, pickle, shutil, sys, warnings, yaml, io, subprocess
----> 2 import math, matplotlib.pyplot as plt, numpy as np, pandas as pd, random
      3 import scipy.stats, scipy.special
      4 import abc, collections, hashlib, itertools, json, operator, pathlib
      5 import mimetypes, inspect, typing, functools, importlib, weakref

~\.conda\envs\fastai\lib\site-packages\pandas\__init__.py in <module>
     40 import pandas.core.config_init
     41 
---> 42 from pandas.core.api import *
     43 from pandas.core.sparse.api import *
     44 from pandas.tseries.api import *

~\.conda\envs\fastai\lib\site-packages\pandas\core\api.py in <module>
     24 )
     25 from pandas.core.arrays import Categorical, array
---> 26 from pandas.core.groupby import Grouper
     27 from pandas.io.formats.format import set_eng_float_format
     28 from pandas.core.index import (Index, CategoricalIndex, Int64Index,

~\.conda\envs\fastai\lib\site-packages\pandas\core\groupby\__init__.py in <module>
      1 from pandas.core.groupby.groupby import GroupBy  # noqa: F401
----> 2 from pandas.core.groupby.generic import (  # noqa: F401
      3     SeriesGroupBy, DataFrameGroupBy, PanelGroupBy)
      4 from pandas.core.groupby.grouper import Grouper  # noqa: F401

~\.conda\envs\fastai\lib\site-packages\pandas\core\groupby\generic.py in <module>
     40 import pandas.core.indexes.base as ibase
     41 from pandas.core.internals import BlockManager, make_block
---> 42 from pandas.core.panel import Panel
     43 from pandas.core.series import Series
     44 

~\.conda\envs\fastai\lib\site-packages\pandas\core\panel.py in <module>
   1584                   docs={})
   1585 
-> 1586 ops.add_special_arithmetic_methods(Panel)
   1587 ops.add_flex_arithmetic_methods(Panel)
   1588 Panel._add_numeric_operations()

~\.conda\envs\fastai\lib\site-packages\pandas\core\ops\__init__.py in add_special_arithmetic_methods(cls)
    810         special methods will be defined and pinned to this class
    811     """
--> 812     _, _, arith_method, comp_method, bool_method = _get_method_wrappers(cls)
    813     new_methods = _create_methods(
    814         cls, arith_method, comp_method, bool_method, special=True

~\.conda\envs\fastai\lib\site-packages\pandas\core\ops\__init__.py in _get_method_wrappers(cls)
    717         comp_special = _comp_method_FRAME
    718         bool_special = _arith_method_FRAME
--> 719     return arith_flex, comp_flex, arith_special, comp_special, bool_special
    720 
    721 

UnboundLocalError: local variable 'arith_flex' referenced before assignment
`

**Comment by sgugger** [comment]
This is an installation problem, not a bug in the library. Please check the [dedicated thread on the forum](https://forums.fast.ai/t/fastai-v1-install-issues-thread/24111/364).
