### ISSUE TITLE
_thnn_conv2d_forward not supported on CPUType for Half

### ISSUE THREAD

**Issue by felixgao** [fastai/fastai#2253]
**Describe the bug**

I am trying out the cifar.ipynb from examples. Inside the Learner method throws an exception. 
https://gist.github.com/felixgao/00333a5837f37125291b51629b0aa8bd

**Provide your installation details**

```text
=== Software ===
python       : 3.7.3
fastai       : 1.0.55
fastprogress : 0.1.21
torch        : 1.1.0
torch cuda   : None / is **Not available**

=== Hardware ===
No GPUs available

=== Environment ===
platform     : Darwin-18.6.0-x86_64-i386-64bit
conda env    : fastai
python       : /Users/ggao/miniconda3/envs/fastai/bin/python
sys.path     : /Users/ggao/github/Learning
/Users/ggao/miniconda3/envs/fastai/lib/python37.zip
/Users/ggao/miniconda3/envs/fastai/lib/python3.7
/Users/ggao/miniconda3/envs/fastai/lib/python3.7/lib-dynload
/Users/ggao/miniconda3/envs/fastai/lib/python3.7/site-packages
no supported gpus found on this system
```

**To Reproduce**

Execute the notebook

**Expected behavior**

The example should run

**Screenshots**

![image](https://user-images.githubusercontent.com/1153820/62164985-4d397c00-b2d2-11e9-988f-a0903a64f85b.png)
![image](https://user-images.githubusercontent.com/1153820/62165006-59253e00-b2d2-11e9-9521-0eb3b337ef44.png)

**Additional context**

**Comment by sgugger** [comment]
You can't train in mixed precision on the CPU, so you either need to run this on a machine with a GPU o remove the `learn.to_fp16()` command.
