### ISSUE TITLE
GANItemList applies transforms once instead of per item

### ISSUE THREAD

**Issue by yissachar** [fastai/fastai#2255]
**Describe the bug**
The GANItemList appears to apply the provided transforms once to the entire dataset, instead of to each item as it is retrieved.

**Provide your installation details**

```text
=== Software === 
python        : 3.6.6
fastai        : 1.0.55
fastprogress  : 0.1.21
torch         : 1.1.0
nvidia driver : 418.67
torch cuda    : 10.0.130 / is available
torch cudnn   : 7501 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 16280MB | Tesla P100-PCIE-16GB

=== Environment === 
platform      : Linux-4.9.0-8-amd64-x86_64-with-debian-9.9
distro        : #1 SMP Debian 4.9.144-3.1 (2019-02-19)
conda env     : Unknown
python        : /opt/conda/bin/python
sys.path      : /kaggle/lib/kagglegym
/kaggle/lib
/opt/conda/lib/python36.zip
/opt/conda/lib/python3.6
/opt/conda/lib/python3.6/lib-dynload

/root/.local/lib/python3.6/site-packages
/opt/conda/lib/python3.6/site-packages
/opt/conda/lib/python3.6/site-packages/nolearn-0.6.1.dev0-py3.6.egg
/opt/conda/lib/python3.6/site-packages/tabulate-0.8.3-py3.6.egg
/opt/conda/lib/python3.6/site-packages/gdbn-0.1-py3.6.egg
/opt/conda/lib/python3.6/site-packages/gnumpy-0.2-py3.6.egg
/opt/conda/lib/python3.6/site-packages/PyBrain-0.3.3-py3.6.egg
/opt/conda/lib/python3.6/site-packages/python_Levenshtein-0.12.0-py3.6-linux-x86_64.egg
/opt/conda/lib/python3.6/site-packages/pyeconometrics-1.0.2-py3.6.egg
/src/bq-helper
/opt/conda/lib/python3.6/site-packages/IPython/extensions
/tmp/.ipython
```

**To Reproduce**
```
from fastai.vision import *
from fastai.vision.gan import *

path = untar_data(URLs.PETS);

def get_data(bs, size):
    return (GANItemList.from_folder(path, noise_sz=100)
               .split_none()
               .label_from_func(noop)
               .transform(tfms=get_transforms(do_flip=True, flip_vert=True), size=size, tfm_y=True)
               .databunch(bs=bs)
               .normalize(stats = [torch.tensor([0.5,0.5,0.5]), torch.tensor([0.5,0.5,0.5])], do_x=False, do_y=True))

data = get_data(128, 64)

data.show_batch(rows=5)
```
Each item in the batch will have an identical transform applied. Calling `show_batch` again will not change the transforms. The transforms will only change when calling `get_data` at  which point the new randomized transform will again be applied to the entire dataset.

**Expected behavior**
Transforms should be applied as each item is retrieved. Calling `show_batch` should show items with different randomized transforms applied.

**Comment by sgugger** [comment]
Should be fixed now, thanks for flagging!

**Comment by yissachar** [comment]
Great, thanks the quick fix! 

I can see how your change makes it so that tfms are applied to the item now, but I can't figure out why they were being applied to the entire dataset before. Is there a separate step that applies it to the entire dataset if they were not applied to the item? Or are they still being applied to the entire dataset, but then an additional tfm is applied at the item level?

**Comment by sgugger** [comment]
Transforms are always applied at the item level, what was happening before the fix is that their state wasn't randomized at each call on __getitem__, (which is the resolve thing), so they were always applied the same way.

**Comment by yissachar** [comment]
Thanks for the explanation!
