### ISSUE TITLE
BrokenProcessPool when creating DataBunch for Language Model

### ISSUE THREAD

**Issue by shreshth211** [fastai/fastai#2260]
```python
import fastai.text as text
lang_data = text.TextList.from_csv('./','lang_df.csv',cols='text').split_by_rand_pct(valid_pct=0.1).label_for_lm().databunch(bs=16)
```

Upon executing the above line of code in Jupyter Notebook I get the following error:

```python
---------------------------------------------------------------------------
BrokenProcessPool                         Traceback (most recent call last)
<ipython-input-26-576ddc81696e> in <module>()
----> 1 lang_data = text.TextList.from_csv('./','lang_df.csv',cols='text').split_by_rand_pct(valid_pct=0.1).label_for_lm().databunch(bs=16)
      2 lang_data.save('lang_data.pkl')
c:\users\shres\appdata\local\programs\python\python36\lib\site-packages\fastai\data_block.py in _inner(*args, **kwargs)
    475             self.valid = fv(*args, from_item_lists=True, **kwargs)
    476             self.__class__ = LabelLists
--> 477             self.process()
    478             return self
    479         return _inner

c:\users\shres\appdata\local\programs\python\python36\lib\site-packages\fastai\data_block.py in process(self)
    529         "Process the inner datasets."
    530         xp,yp = self.get_processors()
--> 531         for ds,n in zip(self.lists, ['train','valid','test']): ds.process(xp, yp, name=n)
    532         #progress_bar clear the outputs so in some case warnings issued during processing disappear.
    533         for ds in self.lists:

c:\users\shres\appdata\local\programs\python\python36\lib\site-packages\fastai\data_block.py in process(self, xp, yp, name)
    709                     p.warns = []
    710                 self.x,self.y = self.x[~filt],self.y[~filt]
--> 711         self.x.process(xp)
    712         return self
    713 

c:\users\shres\appdata\local\programs\python\python36\lib\site-packages\fastai\data_block.py in process(self, processor)
     81         if processor is not None: self.processor = processor
     82         self.processor = listify(self.processor)
---> 83         for p in self.processor: p.process(self)
     84         return self
     85 

c:\users\shres\appdata\local\programs\python\python36\lib\site-packages\fastai\text\data.py in process(self, ds)
    294         tokens = []
    295         for i in progress_bar(range(0,len(ds),self.chunksize), leave=False):
--> 296             tokens += self.tokenizer.process_all(ds.items[i:i+self.chunksize])
    297         ds.items = tokens
    298 

c:\users\shres\appdata\local\programs\python\python36\lib\site-packages\fastai\text\transform.py in process_all(self, texts)
    118         if self.n_cpus <= 1: return self._process_all_1(texts)
    119         with ProcessPoolExecutor(self.n_cpus) as e:
--> 120             return sum(e.map(self._process_all_1, partition_by_cores(texts, self.n_cpus)), [])
    121 
    122 class Vocab():

c:\users\shres\appdata\local\programs\python\python36\lib\concurrent\futures\process.py in _chain_from_iterable_of_lists(iterable)
    364     careful not to keep references to yielded objects.
    365     """
--> 366     for element in iterable:
    367         element.reverse()
    368         while element:

c:\users\shres\appdata\local\programs\python\python36\lib\concurrent\futures\_base.py in result_iterator()
    584                     # Careful not to keep a reference to the popped future
    585                     if timeout is None:
--> 586                         yield fs.pop().result()
    587                     else:
    588                         yield fs.pop().result(end_time - time.time())

c:\users\shres\appdata\local\programs\python\python36\lib\concurrent\futures\_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

c:\users\shres\appdata\local\programs\python\python36\lib\concurrent\futures\_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

```

lang_df.csv is a csv file with just one column named text and about 10k rows of strings of varying length.

My System Config is as follows:

```text
=== Software === 
python        : 3.6.6
fastai        : 1.0.55
fastprogress  : 0.1.20
torch         : 1.0.1
torch cuda    : 9.0 / is available
torch cudnn   : 7005 / is enabled

=== Hardware === 
torch devices : 1
  - gpu0      : GeForce GTX 1050 Ti

=== Environment === 
platform      : Windows-10-10.0.17134-SP0
conda env     : Unknown
python        : c:\users\shres\appdata\local\programs\python\python36\python.exe
sys.path      : 
c:\users\shres\appdata\local\programs\python\python36\python36.zip
c:\users\shres\appdata\local\programs\python\python36\DLLs
c:\users\shres\appdata\local\programs\python\python36\lib
c:\users\shres\appdata\local\programs\python\python36
C:\Users\shres\AppData\Roaming\Python\Python36\site-packages
c:\users\shres\appdata\local\programs\python\python36\lib\site-packages
c:\users\shres\appdata\local\programs\python\python36\lib\site-packages\IPython\extensions
C:\Users\shres\.ipython
no nvidia-smi is found
```

**Comment by shreshth211** [comment]
I just tried running the same code on Windows Subsystem for Linux and it works fine. So it's a problem with windows probably. Also I found [this](https://stackoverflow.com/questions/15900366/all-example-concurrent-futures-code-is-failing-with-brokenprocesspool). That seems to be pretty much the case with me as well. Although running it as a python script and calling the databunch from within `__name__ == '__main__' `didn't help in my case when using windows.

**Comment by sgugger** [comment]
The problem is linked to multiprocessing in windows with PyTorch. If you pass `num_workers=0` in the `.databunch()` function, you will disable it and get rid of the problem. Since reading the texts is pretty fast, you don't really need it anyway.

**Comment by dipankarsahoo180** [comment]
I am facing same issue in windows




data_lm = TextLMDataBunch.from_df(path=path, train_df=train_df, valid_df=valid_df, text_cols=[0], label_cols=label_cols, tokenizer=tokenizer, vocab=oriya_vocab, bs=16,  num_workers=0)


 0.00% [0/2 00:00<00:00]
---------------------------------------------------------------------------
BrokenProcessPool                         Traceback (most recent call last)
<ipython-input-32-6c959ba4eb7e> in <module>
----> 1 data_lm = TextLMDataBunch.from_df(path=path, train_df=train_df, valid_df=valid_df, text_cols=[0], label_cols=label_cols, tokenizer=tokenizer, vocab=oriya_vocab, bs=16,  num_workers=0)

c:\users\deadpool\desktop\nlp_odia\venv\lib\site-packages\fastai\text\data.py in from_df(cls, path, train_df, valid_df, test_df, tokenizer, vocab, classes, text_cols, label_cols, label_delim, chunksize, max_vocab, min_freq, mark_fields, include_bos, include_eos, **kwargs)
    200         src = ItemLists(path, TextList.from_df(train_df, path, cols=text_cols, processor=processor),
    201                         TextList.from_df(valid_df, path, cols=text_cols, processor=processor))
--> 202         if cls==TextLMDataBunch: src = src.label_for_lm()
    203         else:
    204             if label_delim is not None: src = src.label_from_df(cols=label_cols, classes=classes, label_delim=label_delim)

c:\users\deadpool\desktop\nlp_odia\venv\lib\site-packages\fastai\data_block.py in _inner(*args, **kwargs)
    475             self.valid = fv(*args, from_item_lists=True, **kwargs)
    476             self.__class__ = LabelLists
--> 477             self.process()
    478             return self
    479         return _inner

c:\users\deadpool\desktop\nlp_odia\venv\lib\site-packages\fastai\data_block.py in process(self)
    529         "Process the inner datasets."
    530         xp,yp = self.get_processors()
--> 531         for ds,n in zip(self.lists, ['train','valid','test']): ds.process(xp, yp, name=n)
    532         #progress_bar clear the outputs so in some case warnings issued during processing disappear.
    533         for ds in self.lists:

c:\users\deadpool\desktop\nlp_odia\venv\lib\site-packages\fastai\data_block.py in process(self, xp, yp, name)
    709                     p.warns = []
    710                 self.x,self.y = self.x[~filt],self.y[~filt]
--> 711         self.x.process(xp)
    712         return self
    713 

c:\users\deadpool\desktop\nlp_odia\venv\lib\site-packages\fastai\data_block.py in process(self, processor)
     81         if processor is not None: self.processor = processor
     82         self.processor = listify(self.processor)
---> 83         for p in self.processor: p.process(self)
     84         return self
     85 

c:\users\deadpool\desktop\nlp_odia\venv\lib\site-packages\fastai\text\data.py in process(self, ds)
    295         tokens = []
    296         for i in progress_bar(range(0,len(ds),self.chunksize), leave=False):
--> 297             tokens += self.tokenizer.process_all(ds.items[i:i+self.chunksize])
    298         ds.items = tokens
    299 

c:\users\deadpool\desktop\nlp_odia\venv\lib\site-packages\fastai\text\transform.py in process_all(self, texts)
    118         if self.n_cpus <= 1: return self._process_all_1(texts)
    119         with ProcessPoolExecutor(self.n_cpus) as e:
--> 120             return sum(e.map(self._process_all_1, partition_by_cores(texts, self.n_cpus)), [])
    121 
    122 class Vocab():

c:\users\deadpool\appdata\local\programs\python\python36\lib\concurrent\futures\process.py in _chain_from_iterable_of_lists(iterable)
    364     careful not to keep references to yielded objects.
    365     """
--> 366     for element in iterable:
    367         element.reverse()
    368         while element:

c:\users\deadpool\appdata\local\programs\python\python36\lib\concurrent\futures\_base.py in result_iterator()
    584                     # Careful not to keep a reference to the popped future
    585                     if timeout is None:
--> 586                         yield fs.pop().result()
    587                     else:
    588                         yield fs.pop().result(end_time - time.monotonic())

c:\users\deadpool\appdata\local\programs\python\python36\lib\concurrent\futures\_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

c:\users\deadpool\appdata\local\programs\python\python36\lib\concurrent\futures\_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
