### ISSUE TITLE
ULMFiT example uses custom wd for backwards classifier but not for forward

### ISSUE THREAD

**Issue by tsoernes** [fastai/fastai#2262]
In https://github.com/fastai/fastai/blob/master/examples/ULMFit.ipynb
a custom `wd` (weight decay?) is used for training the backwards classifier:
```
learn_bwd.fit_one_cycle(1, lr, moms=(0.8,0.7), wd=0.1)
```
but not for the forward one:
```
learn.fit_one_cycle(1, lr, moms=(0.8,0.7))
```
I assume this is unintentional

**Comment by sgugger** [comment]
Yes, it should be wd=0.1 everywhere. Would you mind making a PR to fix this?

**Comment by tsoernes** [comment]
I don't have the compute to rerun the example (results would differ). Also,
in the docs (https://docs.fast.ai/text.html) they use `drop_mult=0.5` for
training both the LM standalone and the classifier, instead of using it
just for the latter as in the notebook.

man. 5. aug. 2019 kl. 17:10 skrev Sylvain Gugger <notifications@github.com>:

**Comment by sgugger** [comment]
Fixed, results aren't that different for this part and it was a typo, so there was no need to rerun ;)
