### ISSUE TITLE
batch sampler call back not working

### ISSUE THREAD

**Issue by jaideep11061982** [fastai/fastai#2266]
**Describe the bug**

There seems to be an issue with callback handler events. I have made batch sampler such that at the begin of each batch during an epoch ,sampler will select samples based on equi class criteria logic defined inside a Sampler class object below is the code. 
There are three observation that suggests there is possible issue in Callback event handling.
1) There is print statement which is x . This should get printed when i begin the training but is not. At the begin of next iteration only this gets called when i get a syntactic error.
2) I got to know about  the exception only at the end of 1st epoch  ,but it should have at the beginning itself.
3) I corrected the error but learner object was never taking the updated Sampler object called from inside of call back implementing on batch begin and on train begin. Eventually i had to restart the kernel . 
```
class class_balancer(Sampler):
    def __init__(self, df, bs ,trn_idx,ratio):
        #counts=[20,15,25,10,10][4:3:5:2:2]
        self.ratio=np.array(ratio)
        self.counts=[int(ratio[0]*(bs//self.ratio.sum())),int(ratio[1]*(bs//self.ratio.sum())),
                     int(ratio[2]*(bs//self.ratio.sum())),
               int(ratio[3]*(bs//self.ratio.sum())),int(ratio[4]*(bs//self.ratio.sum()))]
        
        self.df=df.copy()
        self.bs=bs
        self.trn_idx=trn_idx
        #self.train_idx=np.setdiff1d(arange_of(df), val_id)
        #train_idx = np.setdiff1d(arange_of(df_train), val_idx)
        #sample=[random.sample(df_train.loc[(df_train.diagnosis==i)&(df_train.index.isin(train_idx))].index.tolist(),c) for i,c in enumerate(self.counts//80) ]
        
    def __iter__(self):
        print('x')
        sample=[random.sample(self.df.loc[(self.df.diagnosis==i)&(self.df.index.isin(self.trn_idx))]
                              .index.tolist(),c) for i,c in enumerate(self.counts) ]
        sample=np.hstack(sample).tolist()
        if len(sample)<self.bs:
            sample=sample+random.sample(self.trn_idx,self.bs-len(sample))
        return iter(sample)

    def __len__(self):
        return len(self.trn_idx)

class OverSamplingCallback1(LearnerCallback):
    def __init__(self,learn:Learner, df,val_id,weights=None):
        super().__init__(learn)
        labels = self.learn.data.train_dl.dataset.y.items.astype(int)
        _,self.counts = np.unique(labels, return_counts=True)
        
        self.df=df.copy()
        self.train_idx=np.setdiff1d(arange_of(df), val_id)
        self.ratio=weights
       (df_train.index.isin(train_idx))].index.tolist(),c) for i,c in enumerate(self.counts//80) ]
        self.bs=learn.data.train_dl.batch_size
       
    def on_train_begin(self,**kwargs):
        self.sample= class_balancer(df=self.df,bs=self.bs,trn_idx=self.train_idx,ratio=self.ratio)
        
    def on_batch_begin(self, **kwargs):
        #sample=[random.sample(self.df.loc[(self.df.diagnosis==i)&(self.df.index.isin(self.train_idx))].index.tolist(),c) for i,c in enumerate(self.counts//self.bs) ]
       BatchSampler(self.sample,self.learn.data.train_dl.batch_size, False)
```

**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
I'm not sure what the bug is. Callbacks can't change the sampler or the batch sampler of a dataloader without creating a new one and setting it properly in `self.learn.data.train_dl` (or valid). That's why your iter is never called, this sampler hasn't been passed to any of the dataloaders.

In general, debugging code is best done using the [forum](https://forums.fast.ai).

**Comment by jaideep11061982** [comment]
> I'm not sure what the bug is. Callbacks can't change the sampler or the batch sampler of a dataloader without creating a new one and setting it properly in `self.learn.data.train_dl` (or valid). That's why your iter is never called, this sampler hasn't been passed to any of the dataloaders.
> 
> In general, debugging code is best done using the [forum](https://forums.fast.ai).

m sorry i missed out these lines .THere is inconsistency in the way call back is invoked  and hence sampler init.  This is what bug is ,print statement as indicator or whether the call back is called or not is some times getting printed some times not,there was mistake in sampler which i corrected it but then callback was not calling the updated the Sampler object definition,eventually i had to restart the kernel.
```
def on_batch_begin(self, **kwargs):
        self.sample= class_balancer(df=self.df,bs=self.bs,trn_idx=self.train_idx,ratio=self.ratio)
        
        self.learn.data.train_dl.dl.batch_sampler = BatchSampler(self.sample,self.learn.data.train_dl.batch_size, False)
```

**Comment by jaideep11061982** [comment]
this is how i add it .When i start the training some times it gets called i mean sampler and some times not or at the end of first epoch. So for this reason i raised this ,atleast event should get called.
`learn2.callback_fns.append(partial(OverSamplingCallback1, df=df_train.copy(),val_id=val_idx,weights=[1,1,1,1,1]))`
