### ISSUE TITLE
ImageDataBunch.from_folder raise the error: IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by VoldemortGin** [fastai/fastai#2271]
![image](https://user-images.githubusercontent.com/23101775/62835394-9a323080-bc8a-11e9-9c34-7f00bac698e3.png)
I was using fast.ai to train a classification on garbage. And I have put the images according to the requirement (in garbage/train/ and garbage/valid/ they both have 40 sub folders represent the class). But I got the error. I've tried to solve it but none of way in the Internet worked, though their question sees similar with me. 
Anyone can help me? Thank you so much.

**Comment by sgugger** [comment]
Your code is correct so there must be some kind of problem with your data. We use GitHub for known issues only, so I'm closing this here, but you can ask for help on the [forum](https://forums.fast.ai/).
