### ISSUE TITLE
regarding import *, auto autocomplete

### ISSUE THREAD

**Issue by vainaijr** [fastai/fastai#2290]
**Describe the bug**

auto autocomplete cannot detect what all classes / functions / methods are within a file, because of use of import *.
due to this, it is near impossible to see the useful classes / functions / methods within a file, and auto autocomplete suggests bunch of classes / functions / methods that should not be suggested.

for example, 
`from fastai.callbacks import  ` 
suggests abc, abstractmethod, and so on, when it should have only suggested callbacks that would be useful.

**Provide your installation details**

**To Reproduce**

**Expected behavior**

instead of using import *, only modules that are used in a file are imported

**Screenshots**

![Screenshot (387)](https://user-images.githubusercontent.com/43755000/63406706-9ee2ab80-c425-11e9-82e0-1f92e797d8ac.png)
![Screenshot (388)](https://user-images.githubusercontent.com/43755000/63406708-9f7b4200-c425-11e9-90de-4cf10c26e9b8.png)

**Additional context**

**Comment by sgugger** [comment]
Please refer to the [contributing guide](https://github.com/fastai/fastai/blob/master/CONTRIBUTING.md#note-for-new-contributors-from-jeremy) and the multiple discussions on the forum. This is not a design that will change and that is balanced that carefully crafted `__all__` variables. callbacks init is missing an `__all__` and I'll make a PR to fix that later today, but the use of import * won't change.

**Comment by vainaijr** [comment]
But this is happens not only for callbacks, but for other modules also, for example if I do `from fastai.vision import`, then again suggests abc, abstract method and so on, same case for `from fastai.datasets import`
I want to have a look at datasets available in fastai.datasets but instead it suggests me abc, abstractmethod and so on.
