### ISSUE TITLE
RuntimeError: Expected object of scalar type Bool but got scalar type Byte for argument #2 'other'

### ISSUE THREAD

**Issue by gvenkat21** [fastai/fastai#2295]
Hi,

I got the following error while using accuracy_thresh_expand:
`RuntimeError: Expected object of scalar type Bool but got scalar type Byte for argument #2 'other'`

```
def accuracy_thresh_expand(y_pred:Tensor, y_true:Tensor, thresh:float=0.5, sigmoid:bool=True)->Rank0Tensor:
    "Compute accuracy after expanding `y_true` to the size of `y_pred`."
    if sigmoid: y_pred = y_pred.sigmoid()
    return ((y_pred>thresh)==y_true[:,None].expand_as(y_pred).byte()).float().mean()
```

Currently the function is implemented as above. I was able to solve the issue by replacing `.byte` with `.bool()`.

**Comment by sgugger** [comment]
This bug appeared with pytorch 1.2.0 and has been solved in v1.0.57 :)
