### ISSUE TITLE
Possible bug with the data block reconstruction causing the predict method to crash

### ISSUE THREAD

**Issue by fromLittleAcorns** [fastai/fastai#2302]
**Describe the bug**
Hi, I have an issue when using a pytorch model in the fastai framework.  After training the model the predict method fails at line 90 in the data_block.py file, when it tries to apply the attribute reconstruct to a numpy array.  I have included the stack trace below and the code is in a gist at this location:

**Provide your installation details**
```text
=== Software ===
python       : 3.7.3
fastai       : 1.0.58.dev0
fastprogress : 0.1.21
torch        : 1.1.0
torch cuda   : None / is **Not available**

=== Hardware ===
No GPUs available

=== Environment ===
platform     : Darwin-18.7.0-x86_64-i386-64bit
conda env    : base
python       : /Users/jr336731/anaconda3/bin/python
sys.path     : /Users/jr336731/repros/fastai/fastai
/Users/jr336731/anaconda3/lib/python37.zip
/Users/jr336731/anaconda3/lib/python3.7
/Users/jr336731/anaconda3/lib/python3.7/lib-dynload
/Users/jr336731/anaconda3/lib/python3.7/site-packages
/Users/jr336731/anaconda3/lib/python3.7/site-packages/aeosa
/Users/jr336731/repros/fastai/fastai
no supported gpus found on this system
```

**To Reproduce**
Please run this script

[Gist here](https://gist.github.com/fromLittleAcorns/12472c0cd9eedb28362dda028aa0b329)

**Expected behavior**

I expected the predict method to return predictions based upon the input data

**Screenshots**

**Additional context**

I have been using and autoencoder and to make the dataloader work I have defined the output as FloatList.  When I look at the databunch it seems to be working ok and the error occurs when processing the input list and not the "y"s

If you can point me in the right direction I am quite happy to try to create a pull request to solve things
Many thanks
John

**Comment by sgugger** [comment]
You can't use the methods `predict`, `show_batch` and `show_results` if you didn't use the fastai data block API to load your data. You need to create a custom `ItemList` if you want to use them. Otherwise, just do `model.eval()(item)`

**Comment by fromLittleAcorns** [comment]
I thought the way I had done it was using the data block API, all of the operations I carried out are as per the docs?  I will have a look at a custom ItemList but in the past found it quite awkward to do

**Comment by sgugger** [comment]
Ah good point, I skimmed through your file too fast. Let me look into it more.

**Comment by sgugger** [comment]
Sorry to have closed this too quickly. This should be fixed now :)

**Comment by fromLittleAcorns** [comment]
Brilliant - thanks very much :)
