### ISSUE TITLE
MultiLabelFbeta doesn't work on pytorch 1.2.0

### ISSUE THREAD

**Issue by Apollo-XI** [fastai/fastai#2305]
MultiLabelFbeta metrics doesn't work on pytorch 1.2.0 as try to multiply a tensor of dtype bool with a tensor of dtype uint8 (line 339 on metrics.py).

The problematic line is the 338 on metrics.py. With pytorch 1.2.0, the comparison returns a tensor of bool dtype instead of uint8 as previous. However, targets are converted to uint8 with .byte() instead of using the new bool() method. 

This mismatch may occur on other lines of code. I don't check all fastai code.

```
=== Software === 
python        : 3.7.3
fastai        : 1.0.57
fastprogress  : 0.1.21
torch         : 1.2.0
nvidia driver : 410.104
torch cuda    : 10.0.130 / is available
torch cudnn   : 7501 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11441MB | Tesla K80

=== Environment === 
platform      : Linux-4.9.0-9-amd64-x86_64-with-debian-9.9
distro        : #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16)
conda env     : base
python        : /opt/anaconda3/bin/python
sys.path      : /home/jupyter/*****
/opt/anaconda3/lib/python37.zip
/opt/anaconda3/lib/python3.7
/opt/anaconda3/lib/python3.7/lib-dynload

/opt/anaconda3/lib/python3.7/site-packages
/opt/anaconda3/lib/python3.7/site-packages/IPython/extensions
/home/jupyter/.ipython
```

**Comment by sgugger** [comment]
Thanks for flagging! Should be fixed now.
