### ISSUE TITLE
Incorrect version of ClassificationInterpretation.plot_top_losses for vision learner

### ISSUE THREAD

**Issue by avandekleut** [fastai/fastai#2309]
Hello,

I'm working with the google colab version of the fastai course-v3 notebooks working on lesson 2. Like in lesson 1, I wanted to called `interp.plot_top_losses` to see where my model was making mistakes (since I could not use the widgets in colab).

However, it looks like somehow, the `ClassificationInterpretation.from_learner(learn)` that gets generated is the one at `fastai/fastai/tabular/models.py` rather than at `fastai/fastai/vision/learner.py`. Each of these modules defines a `_cl_int_plot_top_losses` which is used to define `ClassificationInterpretation.plot_top_losses`. Somehow, in only calling

```python
from fastai.vision import *
```

we must somehow later on import `fastai.tabular`.

I came to this conclusion after calling `doc(interp.plot_top_losses)`, which for lesson 1, gives
```python
_cl_int_plot_top_losses(k, largest=True, figsize=(12, 12), heatmap:bool=False, heatmap_thresh:int=16, return_fig:bool=None) → Optional[Figure
```

and for lesson 2 gives

```python
_cl_int_plot_top_losses(k, largest:bool=True, return_table:bool=False)->Optional[plt.Figure]:
```

You can reproduce this by running the code for lesson 2 and simply trying to call `interp.plot_top_losses(9, figsize=(15,11))` as in lesson 1.

**Comment by sgugger** [comment]
This is not an issue with the library but with the course, I'm closing this issue here, can you open the same one in the course-v3 repo? Thanks!
