### ISSUE TITLE
Add DatasetType option to the GradCam function

### ISSUE THREAD

**Issue by Hamifthi** [fastai/fastai#2310]
Hello,
I'm working with the GradCam function and I need to see activation on Train and test also. Validation and Test set but the default option is Validation here:
```
im,cl = self.learn.data.dl(DatasetType.Valid).dataset[idx]
```
so it's nice to have a dataset type option in input to see all the images
```
def _cl_int_gradcam(self, dataset_type=DatasetType.Valid, idx,
heatmap_thresh:int=16, image:bool=True):
...
im,cl = self.learn.data.dl(dataset_type).dataset[idx]
...
```

**Comment by sgugger** [comment]
Seems reasonable, functionality added in master.

**Comment by tmabraham** [comment]
@sgugger Correct me if I am wrong, but I think in the plot top losses function, there needs to be an argument for the dataset type also.

**Comment by Hamifthi** [comment]
Thank you for your attention

**Comment by sgugger** [comment]
> @sgugger Correct me if I am wrong, but I think in the plot top losses function, there needs to be an argument for the dataset type also.

No, the method that creates an interpet object from the learner as that argument, so it's not needed in top_losses.

**Comment by tmabraham** [comment]
Ok thanks for the clarification!
