### ISSUE TITLE
MultiLabelFbeta metric is calculated over training and validation datasets instead of only the latter

### ISSUE THREAD

**Issue by Apollo-XI** [fastai/fastai#2318]
**Describe the bug**
MultiLabelFbeta metric is calculated over training and validation datasets instead of only the latter.

The bug comes from the fact that the MultiLabelFbeta is a LearnerCallback and doesn't check if it's in training phase when computes the stats on_batch_end. As it's a LearnerCallback, it can't be pass in the metrics argument when Learner is created like any other metrics. So, you could pass it to callback_fns to make it work (I did) without noticing that then the metric will be wrong.

There is only need to check in "on_batch_end" if we're training or not as show on https://docs.fast.ai/metrics.html#Creating-your-own-metric 

**To reproduce**
```text
=== Software === 
python        : 3.7.3
fastai        : 1.0.57
fastprogress  : 0.1.21
torch         : 1.2.0
nvidia driver : 410.104
torch cuda    : 10.0.130 / is available
torch cudnn   : 7602 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11441MB | Tesla K80

=== Environment === 
platform      : Linux-4.9.0-9-amd64-x86_64-with-debian-9.9
distro        : #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16)
conda env     : base
python        : /opt/anaconda3/bin/python
sys.path      : /home/jupyter/zara-ar-ml/pytorch/classifier - napptilus images
/opt/anaconda3/lib/python37.zip
/opt/anaconda3/lib/python3.7
/opt/anaconda3/lib/python3.7/lib-dynload

/opt/anaconda3/lib/python3.7/site-packages
/opt/anaconda3/lib/python3.7/site-packages/IPython/extensions
/home/jupyter/.ipython
```

**To Reproduce**
Create a databunch with an empty validation dataset and see that the stats isn't nan.

**Expected behavior**
Be like the others metrics.

**Comment by sgugger** [comment]
This is not a bug in fastai but in your code. Don't pass a metric as a callback function, pass it as a metric.
