### ISSUE TITLE
Potencial bug in name on MultiLabelFbeta

### ISSUE THREAD

**Issue by Apollo-XI** [fastai/fastai#2319]
Hi

**Describe the bug**
Soory to bother you but I'm not sure if this is the intended behaviour or not. As MultiLabelFbeta is a LearnerCallback, you need to append to the metrics after the learner object has been created (https://forums.fast.ai/t/potential-bug-with-learnercallback/48313/4). However, this adds an extra column on the metrics table that isn't filled.

I'm using fastai 1.0.57

**To Reproduce**
```
learn = cnn_learner(data, models.resnet18)
learn.metrics.append(MultiLabelFbeta(learn))
```
**Screenshots**
![Screenshot 2019-09-06 at 10 18 03](https://user-images.githubusercontent.com/45995383/64412554-e442e200-d08f-11e9-94d2-a001def4f3af.png)

Looking at the MultiLabelFbeta code, micro_fbeta is the intended name for the column.

**Additional context**
A workaround is to pass to callback_fns so the columns are correctly named. However,  the metric is wrong as it uses also the training examples (#2318)

Finally, if you try to pass MultiLabelFbeta on metrics arguments, it fails when computes the metric.

**Comment by sgugger** [comment]
Aaah, I understand now. Will look into this when I have time.

**Comment by sgugger** [comment]
This [commit](https://github.com/fastai/fastai/commit/54e3b9a656aea1b7a89d4acff4b0d0ce073a8f97) makes `MultiLabelFbeta` a regular metric, you should pass it in metrics now and hopefully all problems will be solved.
