### ISSUE TITLE
scipy misc imresize is deprecated! imresize is deprecated in SciPy 1.0.0, and will be removed in 1.2.0. Use skimage.transform.resize instead.

### ISSUE THREAD

**Issue by fivejjs** [fastai/fastai#2320]
**Describe the bug**

**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

https://docs.scipy.org/doc/scipy-1.0.0/reference/generated/scipy.misc.imresize.html

**Comment by sgugger** [comment]
Fixed by your PR.
