### ISSUE TITLE
Class Confusion Widget Fails on Many Non-Pets Datsets

### ISSUE THREAD

**Issue by dcato98** [fastai/fastai#2325]
A regex used in the ClassConfusion widget expects a specific file name format. This causes the widget to give an error when a dataset doesn't conform to this format.

https://github.com/fastai/fastai/blob/master/fastai/widgets/class_confusion.py#L131

`fn = re.search('([^/*]+)_\d+.*$', str(fn)).group(0)`

A more general way to extract the file name would be use pathlib, replacing this line with:

`fn = Path(fn).name`.

**Comment by sgugger** [comment]
That seems like a better idea. Would you mind suggesting a PR with that?

**Comment by dcato98** [comment]
I have just created a pull request #2326. Please let me know if I should change anything. I think it should be linked to this issue - perhaps I am temporarily blind, but I'm not seeing an obvious way to do this.

**Comment by sgugger** [comment]
Fixed by #2326
