### ISSUE TITLE
AttributeError: 'MyDataset' object has no attribute 'init_kwargs'

### ISSUE THREAD

**Issue by samshipengs** [fastai/fastai#2328]
I recently started using Fastai library, im trying to create a DataBunch from pytorch DataLoaders, simply like this
`data = DataBunch(train_dl=train_dl, valid_dl=val_dl)` 
where variable `train_dl` and `val_dl` is regular pytorch Dataloader object created from my custom pytorch Dataset `MyDataset`.

I got this error:

`AttributeError: 'MyDataset' object has no attribute 'init_kwargs'`

based on the [doc](https://docs.fast.ai/basic_data.html#DataBunch), this way of creating a DataBunch should be okay. I'm not sure if I'm missing something obvious.

fastai version: '1.0.57'
pytorch version: '1.2.0'

The complete trace back:

```---------------------------------------------------------------------
AttributeError                      Traceback (most recent call last)
<ipython-input-25-a5760aecf61f> in <module>
----> 1 data = DataBunch(train_dl=train_dl, valid_dl=val_dl)

~/anaconda3/lib/python3.6/site-packages/fastai/basic_data.py in __init__(self, train_dl, valid_dl, fix_dl, test_dl, device, dl_tfms, path, collate_fn, no_check)
     95             return DeviceDataLoader(dl, self.device, self.dl_tfms, collate_fn, **kwargs)
     96         self.train_dl,self.valid_dl,self.fix_dl,self.test_dl = map(_create_dl, [train_dl,valid_dl,fix_dl,test_dl])
---> 97         if fix_dl is None: self.fix_dl = self.train_dl.new(shuffle=False, drop_last=False)
     98         self.single_dl = _create_dl(DataLoader(valid_dl.dataset, batch_size=1, num_workers=0))
     99         self.path = Path(path)

~/anaconda3/lib/python3.6/site-packages/fastai/basic_data.py in new(self, **kwargs)
     61     def new(self, **kwargs):
     62         "Create a new copy of `self` with `kwargs` replacing current values."
---> 63         new_kwargs = {**self.dl.init_kwargs, **kwargs}
     64         return DeviceDataLoader(self.dl.__class__(self.dl.dataset, **new_kwargs), self.device, self.tfms,
     65                                 self.collate_fn)

~/anaconda3/lib/python3.6/site-packages/fastai/basic_data.py in DataLoader___getattr__(dl, k)
     18 torch.utils.data.DataLoader.__init__ = intercept_args
     19 
---> 20 def DataLoader___getattr__(dl, k:str)->Any: return getattr(dl.dataset, k)
     21 DataLoader.__getattr__ = DataLoader___getattr__
     22 
```

**Comment by sgugger** [comment]
`DataBunch` init needs to get `DeviceDataLoader`, not PyTorch `DataLoader`. If you have datasets, the easiest way to build a `DataBunch` is to use `DataBunch.create(train_ds, valids_ds,...)`, otherwise you need to wrap your dataloaders in `DeviceDataLoader` (that will put things on the GPU if needed) to get rid of this bug.

**Comment by sgugger** [comment]
I guess the library could wrap them up automatically for you, will look if it's easy to add on Monday.

**Comment by samshipengs** [comment]
I see, I thought it was pytorch dataloader because in the definition of the class `DataBunch`, the type of `train_dl` gives direct link to pytorch dataloader page. 

thanks for the reply.

**Comment by sgugger** [comment]
I just tried to reproduce your bug and couldn't do it. I made a mistake in my previous comment: the init does take regular PyTorch dataloaders and converts them to `DeviceDataLoader`.

I suspect you create your dataloaders before importing fastai, which has some monkey-patching on PyTorch to add functionality, and that is why you had the bug. Please let me know if that's not the case and you can give me a minimal reproducer while reopening this issue, and I'll dig into it more.

**Comment by SK124** [comment]
Hi, I have created a Dataset and DataLoader using pure pytorch, after which i imported fastai, however I am getting the following error when i am trying to put them in a DataBunch in fastai. I am new to fast.ai so can you tell me what should I amend, Thanks!

from fastai.vision import *
from fastai import *
data = DataBunch(train_loader, val_loader)

 '''AttributeError                            Traceback (most recent call last)
<ipython-input-47-7a37c0dca017> in <module>()
----> 1 data = DataBunch(train_loader, val_loader)

2 frames
/usr/local/lib/python3.7/dist-packages/fastai/basic_data.py in DataLoader___getattr__(dl, k)
     18 torch.utils.data.DataLoader.__init__ = intercept_args
     19 
---> 20 def DataLoader___getattr__(dl, k:str)->Any: return getattr(dl.dataset, k)
     21 DataLoader.__getattr__ = DataLoader___getattr__
     22 

AttributeError: 'Subset' object has no attribute 'init_kwargs' '''

Machine : Google Colab, GPU Enabled.

**Comment by SK124** [comment]
Hi Again, I found a solution to this issue myself, so I am posting it here incase anyone gets stuck with the issue, you will probably get this issue if you are on GPU, so after you construct your dataset in pytorch make sure to add the data to device in the same class that is within the Dataset class instead of training class like its usually done in Pytorch Training loops. Here is the example code.

```
class JSONnew(Dataset):
  def __init__(self,filename,transform=None):
    self.filename=filename
    self.transform=transform
    with open(self.filename) as f:
            self.data = json.load(f)


  def proc(self,band_1,band_2):
        band_3=band_1 / band_2
        r = (band_1 + abs(band_1.min())) / torch.max((band_1 + abs(band_1.min())))
        g = (band_2 + abs(band_2.min())) / torch.max((band_2 + abs(band_2.min())))
        b = (band_3 + abs(band_3.min())) / torch.max((band_3 + abs(band_3.min())))

        image = torch.stack([r, g, b],dim=0)
        return image

  def __getitem__(self,idx):
    id=self.data[idx]["id"]
    H=75
    band_1=torch.tensor(self.data[idx]["band_1"]).reshape(H,H)
    band_2=(torch.tensor(self.data[idx]["band_2"])).reshape(H,H)
    band_3 = band_1 / band_2
    image=self.proc(band_1,band_2)
    is_iceberg=self.data[idx]["is_iceberg"]
    label=torch.tensor(is_iceberg)
    label=label.type(torch.LongTensor)
    if self.transform:
        image=self.transform(image)
    image=image.to(device) #This is what i meant by putting in the dataset class
    label=label.to(device)
    return image,label
  
  def __len__(self):
    return len(self.data)
```
In case you dont know how to declare device, this is the code for that 
```device = torch.device("cuda" if torch.cuda.is_available() else "cpu")```

Cheers!

**Comment by SK124** [comment]
Its me again, Unfortunately the above method doesn't always work
So is there any way to solve it permanently?
