### ISSUE TITLE
Method "predict" output not accordingly implemented with regards to its documentation

### ISSUE THREAD

**Issue by ManuelMartin11** [fastai/fastai#2332]
https://github.com/fastai/fastai/blob/b73f345aa87b71a11bb50960ac3af7cbdd3654ee/fastai/text/learner.py#L118

The class method is intended, as said by its documentation, to return only the next predicted words by the model, but instead, it is returning the context concatenated with the predicted words.

**Comment by sgugger** [comment]
Thanks. WOuld you mind making a PR adjusting the documentation?

**Comment by ManuelMartin11** [comment]
Wouldn't it be better to adapt the output of the method just to return the predicted/generated words? I think it make more sense for practical use cases.

**Comment by sgugger** [comment]
No, the behavior of the function shouldn't change. It's very easy to remove the context if needed.
