### ISSUE TITLE
Test set images end up in train and validation when valid_pct is used

### ISSUE THREAD

**Issue by nihil-admirari** [fastai/fastai#2336]
Steps to reproduce:
1. Create a standard ImageNet folder structure:
   ```
   data/
       train/
           label_0/
               img0.png
               ...
           label_1/
               img0.png
               ...
       test/
           img0.png
           ...
       labels.csv
   ```
   I used [Digit Recognizer](https://www.kaggle.com/c/digit-recognizer) and [mnist_to_imagenet_folders](https://www.kaggle.com/niladmirari/mnist-to-imagenet-folders).
2. `ImageDataBunch.from_folder('data', valid_pct=0.2, test='test').classes` shows `['0', ... , '9', 'test']`.
3. `ImageDataBunch.from_csv('data', valid_pct=0.2, test='test').classes` on the other hand works correctly and shows `[0, ..., 9]` only.

**Comment by sgugger** [comment]
Thanks for flagging, it should be fixed now.
