### ISSUE TITLE
fastai - validation set is empty altough using split_by_rand_pct

### ISSUE THREAD

**Issue by yonatanbitton** [fastai/fastai#2339]
I want to read a dataset using fastai.

I'm using this cmd:

`src = TextList.from_folder(path).split_by_rand_pct(valid_pct=0.2).label_for_lm(ignore_empty=True)
`
I get this warning:
```
C:\Users\PC-1\.conda\envs\KerasEnv36\lib\site-packages\fastai\data_block.py:454: UserWarning: Your validation set is empty. If this is by design, use `split_none()`
                 or pass `ignore_empty=True` when labelling to remove this warning.
  or pass `ignore_empty=True` when labelling to remove this 
```

And indeed later I see that the validation set is empty and I don't receive any losses on it.

I've tried using different functions but i'm at the same status. What am I missing? Thanks

**Comment by sgugger** [comment]
Are you sure you have more than 5 texts in your folder?

**Comment by yonatanbitton** [comment]
I don't. If it's the source if the problem the issue can be closed, I didn't understand it from the docs. Thanks.

**Comment by sgugger** [comment]
You should put a either valid_pct then, to get at least one text in your validation set.
