### ISSUE TITLE
Preparing data for LM in Colab: BrokenProcessPool

### ISSUE THREAD

**Issue by yonatanbitton** [fastai/fastai#2341]
Hello. I have a data in train & validation folders, which I want to prepare for LM in Colab:

`path = '/content/drive/My Drive/Colab Notebooks/data/wiki_train_dev'
`
I try to run this CMD (which work well in Windows):
`src = TextList.from_folder(path).split_by_folder(train='train', valid='valid').label_for_lm(ignore_empty=True)`

But I receive the following error: 
`BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.`

How can I solve it ? Thanks

**Comment by sgugger** [comment]
This is a generic error that tells something went wrong during multiprocessing. There is nothing we can do to help without seeing the code you run. Please use the [forum](https://forums.fast.ai/) to debug your code, we keep the issues for standing bugs only.
