### ISSUE TITLE
Use encoding here

### ISSUE THREAD

**Issue by lvaleriu** [fastai/fastai#2345]
We should be able to specify an encoding when opening this file.

https://github.com/fastai/fastai/blob/ad77d13a195a02bf36e46c8bb6c392165ca6ad43/fastai/text/data.py#L427

**Comment by lvaleriu** [comment]
Same here: https://github.com/fastai/fastai/blob/ad77d13a195a02bf36e46c8bb6c392165ca6ad43/fastai/text/data.py#L467

**Comment by sgugger** [comment]
Should be fixed now.
