### ISSUE TITLE
example data adult_sample not found

### ISSUE THREAD

**Issue by geoHeil** [fastai/fastai#2364]
Hi,

I am trying to work through lesson 4 tabular notebook.
The first step is to download the dataset.

Unfortunately, http://files.fast.ai/data/examples/adult_sample returns only a 404 and the data appears to have moved.

But I could also no longer find it on fastAI's website.
Please, can you explain where the dataset resides now or adapt the URI associated with the ADULT_SAMPLE constant.

**Comment by sgugger** [comment]
You forgot the extension: .tgz. Note that `untar_data` downloads it for you automatically.
