### ISSUE TITLE
Definition of AdamW

### ISSUE THREAD

**Issue by bkj** [fastai/fastai#2368]
**Describe the bug**

In [torch_core line 67](https://github.com/fastai/fastai/blob/master/fastai/torch_core.py#L67) `AdamW` is defined as 
```
AdamW = functools.partial(torch.optim.adam.Adam, betas=(0.9,0.99))
```

I would've expected it to be an extenstion of `torch.optim.adam.AdamW` -- is the current code correct or a typo?  And if correct, is there documentation somewhere that could help me understand how this is intended to work?

Thanks!
~ Ben

**Comment by sgugger** [comment]
PyTorch only added AdamW recently and we have our own implementation in fastai that is way older, so this is not a mistake. The key is not here but in the argument `true_wd` of `Learner` that defaults to `True`. See the [documentation](https://docs.fast.ai/basic_train.html#Learner) of `Learner` for more details.
