### ISSUE TITLE
Explicitely set align_corners argument to prevent UserWarning from pytorch

### ISSUE THREAD

**Issue by mazzma12** [fastai/fastai#2370]
**Describe the bug**
Every iteration over a dataloader with defaults transform for segmentation task raises a torch warning 
```python
/home/user1/.pyenv/versions/torch12/lib/python3.6/site-packages/torch/nn/functional.py:2693: UserWarning: Default grid_sample and affine_grid behavior will be changed to align_corners=False from 1.4.0. See the documentation of grid_sample for details.
```
I report this as an issue as it floods stdout. Also I could not find where it is triggered in the code, and how to change this parameter value. This should be explicitly to prevent from unexpected behavior. ([pytorch source](https://github.com/pytorch/pytorch/blob/f3cc9b221829945fa614c25c1abdd8328f7e3125/torch/nn/functional.py#L2426))
**Provide your installation details**
```text
=== Software === 
python        : 3.6.8
fastai        : 1.0.58
fastprogress  : 0.1.21
torch         : 1.3.0
nvidia driver : 410.79
torch cuda    : 10.1.243 / is **Not available** 

=== Hardware === 
nvidia gpus   : 1
Have 1 GPU(s), but torch can't use them (check nvidia driver) 

=== Environment === 
platform      : Linux-4.15.0-1044-gcp-x86_64-with-debian-buster-sid
distro        : Ubuntu 18.04 bionic
conda env     : Unknown
python        : /home/user1/.pyenv/versions/torch12/bin/python
sys.path      : /home/user1/.pyenv/versions/3.6.8/lib/python36.zip
/home/user1/.pyenv/versions/3.6.8/lib/python3.6
/home/user1/.pyenv/versions/3.6.8/lib/python3.6/lib-dynload

/home/user1/.pyenv/versions/torch12/lib/python3.6/site-packages
/home/user1/.pyenv/versions/torch12/lib/python3.6/site-packages/IPython/extensions
/home/user1/.ipython
```
I also checked the master branch
-->

**To Reproduce**
Run tuto segmentation notebook : https://github.com/TannerGilbert/Tutorials/blob/master/FastAI/Image%20segmentation%20on%20CamVid%20dataset.ipynb

**Expected behavior**
No warning.

EDIT: You can easily catch de warnings with python, but I couln't find an evidence that this information was reported so I opened this ticket. Thank you ! 

```python
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="torch.nn.functional")
```

**Comment by sgugger** [comment]
Thanks for flagging the issue! It should be fixed now (we just ignore the warning for no and will expose the argument when we bump the minimal version of PyTorch supported, but since the arg isn't there in 1.2 or earlier, we can't really use it).

**Comment by luisfgit** [comment]
The commit that added the change to PyTorch mentions [(PyTorch Commit)](https://github.com/pytorch/pytorch/commit/74b65c32be68b15dc7c9e8bb62459efbfbde33d8):
> The old functionality can still be achieved by setting `align_corners=True`

So why not set that as the default value in [c3c3241](https://github.com/fastai/fastai/commit/c3c3241d769245252e87baa7e147fefa2313e524)?

**Comment by sgugger** [comment]
That kwarg doesn’t exist in pytorch 1.2.0 or earlier, so if we do this, fastai will stop working with people having those versions.

**Comment by LF-git** [comment]
Ok, thanks for explaining.

**Comment by akarazniewicz** [comment]
Please reopen it. Hiding warning actually worsened situation, because people are left unaware. With latest release of pytorch 1.4.0, behavior did change and this is basically dealbreaker. Most of existing models and things using vision module are, for obvious reasons, working differently.

**Comment by ArulMoveRepo** [comment]
Is there a fix for this issue? The models which were using the vision modules of fastai are now working differently.
