### ISSUE TITLE
SaveModelCallback saves model on each gpu when distributed training.

### ISSUE THREAD

**Issue by f-sky** [fastai/fastai#2371]
I notice that when distributed training, each gpu has a SaveModelCallback, and saves model according to val loss on that gpu, but not the val loss across all gpus. I think SaveModelCallback should collect val loss on all gpus and saves model in a single process.

**Comment by sgugger** [comment]
That could be a desired feature yes. This is not something we will implement as we're in the development of v2 and this callback is an external contribution.  Closing the issue as this is not a standing bug, you should post on the [forum](https://forums.fast.ai/) to see if someone wants to tackle this (or suggest a PR if you want to tackle it yourself).

**Comment by mraggi** [comment]
By the way, sometimes both threads try to write the same model, resulting in a bad model file. I suggest just adding the SaveModelCallBack when local_rank == 0.

**Comment by sgugger** [comment]
There is a function `rank_distrib` that could be useful to use (and adapt if it doesn't always return the right result). That's what we use in distributed.
