### ISSUE TITLE
name 'LanguageModelData' is not defined

### ISSUE THREAD

**Issue by caochanhduong** [fastai/fastai#2373]
**Describe the bug**

----> 6 md = LanguageModelData(PATH, 1, vs, trn_dl, val_dl)

NameError: name 'LanguageModelData' is not defined

**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/41425919/66710991-6a4bfa00-edad-11e9-9897-b95f1a86b391.png)

**Additional context**
Can i run this code with fastai1.0.x ??????????????????

**Comment by sgugger** [comment]
There is no need to add 17 interrogation marks, it's rather rude to do so. Especially when you don't even mention where your code comes from and don't follow our issue template.
For what it's worth, it looks like fastai 0.7 code, so no, it can't run with v1.0.x.
