### ISSUE TITLE
cat not set attribute in callbacks

### ISSUE THREAD

**Issue by beichuanzhaolun** [fastai/fastai#2376]
### code : 
    import fastai
    from fastai.vision import *
    
    path = untar_data(URLs.MNIST_SAMPLE); path
    tfms = get_transforms(do_flip=False)
    data = ImageDataBunch.from_folder(path, ds_tfms=tfms, size=24)
    
    
    class StepLRCallback(LearnerCallback):
        "A `TrackerCallback` that reduces learning rate when a metric has stopped improving."
        def __init__(self, learn:Learner, step_size = 1, gamma = 0.1, last_epoch = -1):
            super().__init__(learn)
            self.setp_size = 1  # Here I manually set attribute
            self.gamma = 2
            self.last_epoch = 3
            print('__init__')
            print(self.step_size) # Here I try to get the attribute, but failed
            print(self.exclude)
            print(self.get_state)
            
    learn = cnn_learner(data, models.resnet18, metrics=[accuracy])
    cb = StepLRCallback(learn)
    
### Error message from the last line:
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-14-20cdcce0c152> in <module>
          1 learn = cnn_learner(data, models.resnet18, metrics=[accuracy])
    ----> 2 xx = StepLRCallback(learn)
    
    <ipython-input-13-1bb1ba34421d> in __init__(self, learn, step_size, gamma, last_epoch)
         15         self.last_epoch = 3
         16         print('__init__')
    ---> 17         print(self.step_size)
         18         print(self.exclude)
         19         print(self.get_state)
    
    /data2/zhaolun/fastai/fastai/basic_train.py in __getattr__(self, k)
        443         setattr(self.learn, self.cb_name, self)
        444 
    --> 445     def __getattr__(self,k): return getattr(self.learn, k)
        446     def __setstate__(self,data:Any): self.__dict__.update(data)
        447 
    
    AttributeError: 'Learner' object has no attribute 'step_size'
    
 ### My confusion:
   I have already manually set "self.setp_size = 1", but when I try to print it, AttributeError occurs.
   Torally confused, thanks if someone can point out my mistake.

**Comment by sgugger** [comment]
There is a typo in your cod, you typed `self.setp_size = 1` instead of `self.step_size = 1`.

When asked for an attribute it doesn't have, `LearnerCallback` tries to get it inside its `Learner` (which is why you see this error message).

**Comment by beichuanzhaolun** [comment]
Thank you very much! Mr sgugger
I was such a fool !
