### ISSUE TITLE
AttributeError: 'TextList' object has no attribute 'split_by_rand_pct'@fastai/text/data.py 

### ISSUE THREAD

**Issue by hdecamp** [fastai/fastai#2381]
I am trying to follow the steps published here:
https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson3-imdb.ipynb

I am running the code in my local machine with Jupyter notebook v. 6.0.1 & Anaconda.

It failed at this point:
data_lm = (TextList.from_folder(path)
           #Inputs: all the text files in path
            .filter_by_folder(include=['train', 'test', 'unsup']) 
           #We may have other temp folders that contain text files so we only keep what's in train and test
            .split_by_rand_pct(0.1)
           #We randomly split and keep 10% (10,000 reviews) for validation
            .label_for_lm()           
           #We want to do a language model so we label accordingly
            .databunch(bs=bs))

The error message is:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-9d900ae2f247> in <module>
      1 data_lm = (TextList.from_folder(path)
      2            #Inputs: all the text files in path
----> 3             .filter_by_folder(include=['train', 'test', 'unsup'])
      4            #We may have other temp folders that contain text files so we only keep what's in train and test
      5             .split_by_rand_pct(0.1)

AttributeError: 'TextList' object has no attribute 'split_by_rand_pct'

Thank you

**Comment by sgugger** [comment]
It's hard to say without seeing your installation details (please follow the template) but I would say your version of fastai is too old and prior to rename of this function. This runs fine on the latest version, you should update your library.
