### ISSUE TITLE
install windows cpu does not create any files in <fastai root> folder

### ISSUE THREAD

**Issue by kruzel** [fastai/fastai#2388]
(fastai) C:\Dev\fastai>conda install -c pytorch -c fastai fastai
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3\envs\fastai

  added / updated specs:
    - fastai

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    asn1crypto-1.2.0           |           py37_0         162 KB
    attrs-19.3.0               |             py_0          39 KB
    beautifulsoup4-4.8.1       |           py37_0         153 KB
    cffi-1.13.0                |   py37h7a1dbc1_0         226 KB
    chardet-3.0.4              |        py37_1003         192 KB
    cryptography-2.8           |   py37h7a1dbc1_0         570 KB
    importlib_metadata-0.23    |           py37_0          44 KB
    jsonschema-3.1.1           |           py37_0         111 KB
    more-itertools-7.2.0       |           py37_0          99 KB
    numexpr-2.7.0              |   py37hdce8814_0         134 KB
    packaging-19.2             |             py_0          30 KB
    pandas-0.25.2              |   py37ha925a31_0         9.8 MB
    pillow-6.2.0               |   py37hdc69c19_0         703 KB
    pyrsistent-0.15.4          |   py37he774522_0          95 KB
    pysocks-1.7.1              |           py37_0          30 KB
    pyyaml-5.1.2               |   py37he774522_0         163 KB
    requests-2.22.0            |           py37_0          90 KB
    soupsieve-1.9.3            |           py37_0          60 KB
    tqdm-4.36.1                |             py_0          50 KB
    urllib3-1.24.2             |           py37_0         153 KB
    zipp-0.6.0                 |             py_0           9 KB
    ------------------------------------------------------------
                                           Total:        12.9 MB

The following NEW packages will be INSTALLED:

  asn1crypto         pkgs/main/win-64::asn1crypto-1.2.0-py37_0
  attrs              pkgs/main/noarch::attrs-19.3.0-py_0
  beautifulsoup4     pkgs/main/win-64::beautifulsoup4-4.8.1-py37_0
  blas               pkgs/main/win-64::blas-1.0-mkl
  bottleneck         pkgs/main/win-64::bottleneck-1.2.1-py37h452e1ab_1
  cffi               pkgs/main/win-64::cffi-1.13.0-py37h7a1dbc1_0
  chardet            pkgs/main/win-64::chardet-3.0.4-py37_1003
  cryptography       pkgs/main/win-64::cryptography-2.8-py37h7a1dbc1_0
  cudatoolkit        pkgs/main/win-64::cudatoolkit-10.1.168-0
  cycler             pkgs/main/win-64::cycler-0.10.0-py37_0
  cymem              fastai/win-64::cymem-2.0.2-py37h6538335_0
  cython-blis        fastai/win-64::cython-blis-0.2.4-py37hfa6e2cd_1
  dataclasses        fastai/noarch::dataclasses-0.6-py_0
  fastai             fastai/noarch::fastai-1.0.58-1
  fastprogress       fastai/noarch::fastprogress-0.1.21-py_0
  freetype           pkgs/main/win-64::freetype-2.9.1-ha9979f8_1
  icc_rt             pkgs/main/win-64::icc_rt-2019.0.0-h0cc432a_1
  icu                pkgs/main/win-64::icu-58.2-ha66f8fd_1
  idna               pkgs/main/win-64::idna-2.8-py37_0
  importlib_metadata pkgs/main/win-64::importlib_metadata-0.23-py37_0
  intel-openmp       pkgs/main/win-64::intel-openmp-2019.4-245
  jpeg               pkgs/main/win-64::jpeg-9b-hb83a4c4_2
  jsonschema         pkgs/main/win-64::jsonschema-3.1.1-py37_0
  kiwisolver         pkgs/main/win-64::kiwisolver-1.1.0-py37ha925a31_0
  libpng             pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0
  libtiff            pkgs/main/win-64::libtiff-4.0.10-hb898794_2
  matplotlib         pkgs/main/win-64::matplotlib-3.1.1-py37hc8f65d3_0
  mkl                pkgs/main/win-64::mkl-2019.4-245
  mkl-service        pkgs/main/win-64::mkl-service-2.3.0-py37hb782905_0
  mkl_fft            pkgs/main/win-64::mkl_fft-1.0.14-py37h14836fe_0
  mkl_random         pkgs/main/win-64::mkl_random-1.1.0-py37h675688f_0
  more-itertools     pkgs/main/win-64::more-itertools-7.2.0-py37_0
  murmurhash         pkgs/main/win-64::murmurhash-1.0.2-py37h33f27b4_0
  ninja              pkgs/main/win-64::ninja-1.9.0-py37h74a9793_0
  numexpr            pkgs/main/win-64::numexpr-2.7.0-py37hdce8814_0
  numpy              pkgs/main/win-64::numpy-1.16.5-py37h19fb1c0_0
  numpy-base         pkgs/main/win-64::numpy-base-1.16.5-py37hc3f5095_0
  nvidia-ml-py3      fastai/noarch::nvidia-ml-py3-7.352.0-py_0
  olefile            pkgs/main/win-64::olefile-0.46-py37_0
  packaging          pkgs/main/noarch::packaging-19.2-py_0
  pandas             pkgs/main/win-64::pandas-0.25.2-py37ha925a31_0
  pillow             pkgs/main/win-64::pillow-6.2.0-py37hdc69c19_0
  plac               pkgs/main/win-64::plac-0.9.6-py37_0
  preshed            pkgs/main/win-64::preshed-2.0.1-py37h33f27b4_0
  pycparser          pkgs/main/win-64::pycparser-2.19-py37_0
  pyopenssl          pkgs/main/win-64::pyopenssl-19.0.0-py37_0
  pyparsing          pkgs/main/noarch::pyparsing-2.4.2-py_0
  pyqt               pkgs/main/win-64::pyqt-5.9.2-py37h6538335_2
  pyrsistent         pkgs/main/win-64::pyrsistent-0.15.4-py37he774522_0
  pysocks            pkgs/main/win-64::pysocks-1.7.1-py37_0
  python-dateutil    pkgs/main/win-64::python-dateutil-2.8.0-py37_0
  pytorch            pytorch/win-64::pytorch-1.3.0-py3.7_cuda101_cudnn7_0
  pytz               pkgs/main/noarch::pytz-2019.3-py_0
  pyyaml             pkgs/main/win-64::pyyaml-5.1.2-py37he774522_0
  qt                 pkgs/main/win-64::qt-5.9.7-vc14h73c81de_0
  requests           pkgs/main/win-64::requests-2.22.0-py37_0
  scipy              pkgs/main/win-64::scipy-1.3.1-py37h29ff71c_0
  sip                pkgs/main/win-64::sip-4.19.8-py37h6538335_0
  six                pkgs/main/win-64::six-1.12.0-py37_0
  soupsieve          pkgs/main/win-64::soupsieve-1.9.3-py37_0
  spacy              fastai/win-64::spacy-2.1.8-py37he980bc4_0
  srsly              fastai/win-64::srsly-0.1.0-py37h6538335_0
  thinc              fastai/win-64::thinc-7.0.8-py37he980bc4_0
  tk                 pkgs/main/win-64::tk-8.6.8-hfa6e2cd_0
  torchvision        pytorch/win-64::torchvision-0.4.1-py37_cu101
  tornado            pkgs/main/win-64::tornado-6.0.3-py37he774522_0
  tqdm               pkgs/main/noarch::tqdm-4.36.1-py_0
  urllib3            pkgs/main/win-64::urllib3-1.24.2-py37_0
  wasabi             fastai/noarch::wasabi-0.2.2-py_0
  win_inet_pton      pkgs/main/win-64::win_inet_pton-1.1.0-py37_0
  xz                 pkgs/main/win-64::xz-5.2.4-h2fa13f4_4
  yaml               pkgs/main/win-64::yaml-0.1.7-hc54c509_2
  zipp               pkgs/main/noarch::zipp-0.6.0-py_0
  zlib               pkgs/main/win-64::zlib-1.2.11-h62dcd97_3
  zstd               pkgs/main/win-64::zstd-1.3.7-h508b16e_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
cryptography-2.8     | 570 KB    | ################################################################################################################################################################################################################################ | 100%
soupsieve-1.9.3      | 60 KB     | ################################################################################################################################################################################################################################ | 100%
importlib_metadata-0 | 44 KB     | ################################################################################################################################################################################################################################ | 100%
more-itertools-7.2.0 | 99 KB     | ################################################################################################################################################################################################################################ | 100%
beautifulsoup4-4.8.1 | 153 KB    | ################################################################################################################################################################################################################################ | 100%
tqdm-4.36.1          | 50 KB     | ################################################################################################################################################################################################################################ | 100%
pyrsistent-0.15.4    | 95 KB     | ################################################################################################################################################################################################################################ | 100%
numexpr-2.7.0        | 134 KB    | ################################################################################################################################################################################################################################ | 100%
pandas-0.25.2        | 9.8 MB    | ################################################################################################################################################################################################################################ | 100%
chardet-3.0.4        | 192 KB    | ################################################################################################################################################################################################################################ | 100%
requests-2.22.0      | 90 KB     | ################################################################################################################################################################################################################################ | 100%
pillow-6.2.0         | 703 KB    | ################################################################################################################################################################################################################################ | 100%
cffi-1.13.0          | 226 KB    | ################################################################################################################################################################################################################################ | 100%
attrs-19.3.0         | 39 KB     | ################################################################################################################################################################################################################################ | 100%
asn1crypto-1.2.0     | 162 KB    | ################################################################################################################################################################################################################################ | 100%
jsonschema-3.1.1     | 111 KB    | ################################################################################################################################################################################################################################ | 100%
urllib3-1.24.2       | 153 KB    | ################################################################################################################################################################################################################################ | 100%
packaging-19.2       | 30 KB     | ################################################################################################################################################################################################################################ | 100%
zipp-0.6.0           | 9 KB      | ################################################################################################################################################################################################################################ | 100%
pyyaml-5.1.2         | 163 KB    | ################################################################################################################################################################################################################################ | 100%
pysocks-1.7.1        | 30 KB     | ################################################################################################################################################################################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(fastai) C:\Dev\fastai>
(fastai) C:\Dev\fastai>jupiter notebook
'jupiter' is not recognized as an internal or external command,
operable program or batch file.

(fastai) C:\Dev\fastai>dir
 Volume in drive C is SystemDisk
 Volume Serial Number is 4013-AB5C

 Directory of C:\Dev\fastai

10/23/2019  09:15 PM    <DIR>          .
10/23/2019  09:15 PM    <DIR>          ..
10/23/2019  09:20 PM    <DIR>          .idea
               0 File(s)              0 bytes
               3 Dir(s)  196,165,246,976 bytes free

**Comment by sgugger** [comment]
I am unsure what the issue is. Installing fastai with conda is not supposed to put any files in a fastai directory, just installing the library in your conda environment to use it in python/ipython/jupyter.
