### ISSUE TITLE
How to get probability of a word given context in Language model?

### ISSUE THREAD

**Issue by yonatanbitton** [fastai/fastai#2391]
Hello.
I need to add the functionality of getting a probability of a word given a context. 
I've found this post that is exactly what I need: 
https://forums.fast.ai/t/how-to-get-probability-of-a-word-given-context-in-language-model/44787

I want to get P("red"|“The car is”).
It means that I need a function that receives the context: "The car is", and the next word candidate: "red", and returns the probability for this event.

The answer for the post added here wasn't very clear, and I'm having trouble understanding how to implement this function. 

How can I do it? Thanks

**Comment by sgugger** [comment]
The forum is the place to ask this question, we keep issues for bugs in the library only.
