### ISSUE TITLE
Are there plans to include newest transformers based models in fastai?

### ISSUE THREAD

**Issue by enzoampil** [fastai/fastai#2396]
I understand there is now a [fast-bert](https://github.com/kaushaltrivedi/fast-bert/tree/master/fast_bert) library that mixes this repo with [transformers](https://github.com/huggingface/transformers/tree/master/transformers). Does fastai plan to integrate these models or should I continue to refer to **fast-bert** for this?

**Comment by sgugger** [comment]
Not in v1 no. We'll look at integrating closer with the transformes repo in v2. Closing this as we keep issues for bugs only, please use the [forum](https://forums.fast.ai/) for feature requests.
