### ISSUE TITLE
SPProcessor results in OSError when using a folder with whitespace in the path.

### ISSUE THREAD

**Issue by josh-cooper** [fastai/fastai#2403]
**Description**
When using SPProcessor with TextList.from_folder an error will occur if the path passed to from_folder has whitespace in it.
Note that in the traceback the full path should be 
`"/content/drive/My Drive/***left_out**/ulmfit_sentencepiece_wiki/enwiki/docs/tmp/all_text.out"`

Appears to be due to the way SPProcessor passes arguments to the SentencePieceTrainer.train SWIG interface.

**Reproduce**
Call `TextList.from_folder(dest, processor=[OpenFileProcessor(), SPProcessor()])` where `dest` contains whitespace.

**Traceback**
```
---------------------------------------------------------------------------

OSError                                   Traceback (most recent call last)

<ipython-input-38-68fbaa18ae4a> in <module>()
 data = (TextList.from_folder(dest, processor=[OpenFileProcessor(), SPProcessor()])
---->         .split_by_rand_pct(0.1, seed=42)
         .label_for_lm()
         .databunch(bs=bs, num_workers=1))

5 frames

/usr/local/lib/python3.6/dist-packages/fastai/text/data.py in train_sentencepiece(texts, path, pre_rules, post_rules, vocab_sz, max_vocab_sz, model_type, max_sentence_len, lang, char_coverage, tmp_dir, enc)
         f"--unk_id={len(defaults.text_spec_tok)} --pad_id=-1 --bos_id=-1 --eos_id=-1",
         f"--user_defined_symbols={','.join(spec_tokens)}",
-->        f"--model_prefix={cache_dir/'spm'} --vocab_size={vocab_sz} --model_type={model_type}"]))
     raw_text_path.unlink()
     return cache_dir

OSError: Not found: unknown field name "Drive/***left_out**/ulmfit_sentencepiece_wiki/enwiki/docs/tmp/all_text.out" in TrainerSpec.
```

**Installation details**
(Google Colab)
```text
=== Software === 
python        : 3.6.8
fastai        : 1.0.59
fastprogress  : 0.1.21
torch         : 1.3.0+cu100
nvidia driver : 418.67
torch cuda    : 10.0.130 / is available
torch cudnn   : 7603 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11441MB | Tesla K80

=== Environment === 
platform      : Linux-4.14.137+-x86_64-with-Ubuntu-18.04-bionic
distro        : #1 SMP Thu Aug 8 02:47:02 PDT 2019
conda env     : Unknown
python        : /usr/bin/python3
sys.path      : 
/env/python
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/usr/local/lib/python3.6/dist-packages/IPython/extensions
/root/.ipython
```

**Comment by sgugger** [comment]
Added quotes, which should normally solve this issue. Thanks for flagging!

**Comment by yijinlee** [comment]
I can see that it's passing something like `"--input=/path/to/with space/tmp/all_text.out --max_sentence_length=20480"` into `SentencePieceTrainer.Train`, where the expected args are space-separated and thus it thinks `space/tmp/all_text.out` is the next argument, which is an unknown field for TrainerSpec. This is repeated for `--model_prefix=` later on in the arg list.

Not sure how best to fix this... I guess we could try to pass some quotes / escape chars so that SentencePieceTrainer knows that it is a path with space in it (I could not get that to work), or perhaps detect the path with space first, and change the `--input` and `--model_prefix` (both seem to be temp) to another path without space in it, before calling `SentencePieceTrainer`?

**Comment by yijinlee** [comment]
ah @sgugger already fixed this hah. Redundant comment above, please ignore =P

**Comment by yijinlee** [comment]
One of many open issues in sentencepiece [here](https://github.com/google/sentencepiece/issues/419).

**Comment by sgugger** [comment]
Oh, so then we can't do anything until they fix it on their side...
