### ISSUE TITLE
ImportError: cannot import name 'ClassificationInterpretation'

### ISSUE THREAD

**Issue by Tylersuard** [fastai/fastai#2415]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-4fdf1596d604> in <module>
     11 from fastai import *
     12 from fastai.vision import *
---> 13 from fastai.text import *
     14 
     15 from torchvision.models import *

C:\ProgramData\Anaconda3\envs\capstone\lib\site-packages\fastai\text\__init__.py in <module>
----> 1 from .learner import *
      2 from .data import *
      3 from .transform import *
      4 from .models import *
      5 from .. import text

C:\ProgramData\Anaconda3\envs\capstone\lib\site-packages\fastai\text\learner.py in <module>
      7 from ..metrics import accuracy
      8 from ..train import GradientClipping
----> 9 from .models import get_language_model, get_rnn_classifier
     10 from .transform import *
     11 

C:\ProgramData\Anaconda3\envs\capstone\lib\site-packages\fastai\text\models\__init__.py in <module>
----> 1 from .awd_lstm import *
      2 from .transformer import *
      3 __all__ = [*awd_lstm.__all__, *transformer.__all__]

C:\ProgramData\Anaconda3\envs\capstone\lib\site-packages\fastai\text\models\awd_lstm.py in <module>
      1 from ...torch_core import *
      2 from ...layers import *
----> 3 from ...train import ClassificationInterpretation
      4 from ...basic_train import *
      5 from ...basic_data import *

ImportError: cannot import name 'ClassificationInterpretation'

**Comment by Tylersuard** [comment]
Fastai 1.0.34
Pytorch 1.3.1

**Comment by sgugger** [comment]
This is a very old version of fastai that seems mixed up with a new one. You should try to do a clean install.
