### ISSUE TITLE
LabelLists.add_test_folder() doesn't store `test_folder:str`

### ISSUE THREAD

**Issue by kdorichev** [fastai/fastai#2418]
**Bug description**
When adding a test set by calling `LabelLists.add_test_folder(test_folder)`, LabelLists.Test.path contains the path to `train_folder`, not `test_folder`.

**Installation details**
```text
=== Software === 
python       : 3.7.3
fastai       : 1.0.60.dev0
fastprogress : 0.1.21
torch        : 1.3.0
torch cuda   : 10.1.243 / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Linux-5.3.0-23-generic-x86_64-with-debian-buster-sid
distro       : Ubuntu 19.10 eoan
conda env    : base
python       : /home/condor/anaconda3/bin/python
sys.path     : /home/condor/anaconda3/bin
/home/condor/anaconda3/lib/python37.zip
/home/condor/anaconda3/lib/python3.7
/home/condor/anaconda3/lib/python3.7/lib-dynload

/home/condor/anaconda3/lib/python3.7/site-packages
/home/condor/fastai
/home/condor/anaconda3/lib/python3.7/site-packages/IPython/extensions
/home/condor/.ipython
no supported gpus found on this system
```
**To Reproduce**
```python
data = (ImageList.from_folder(mnist/'training').split_by_rand_pct().label_from_folder())
data.add_test_folder(mnist/'testing')

LabelLists;

Train: LabelList (48000 items)
x: ImageList
Image (3, 28, 28),Image (3, 28, 28),Image (3, 28, 28),Image (3, 28, 28),Image (3, 28, 28)
y: CategoryList
5,5,5,5,5
Path: /home/condor/.fastai/data/mnist_png/training;

Valid: LabelList (12000 items)
x: ImageList
Image (3, 28, 28),Image (3, 28, 28),Image (3, 28, 28),Image (3, 28, 28),Image (3, 28, 28)
y: CategoryList
9,8,5,9,7
Path: /home/condor/.fastai/data/mnist_png/training;

Test: LabelList (10000 items)
x: ImageList
Image (3, 28, 28),Image (3, 28, 28),Image (3, 28, 28),Image (3, 28, 28),Image (3, 28, 28)
y: EmptyLabelList
,,,,
Path: /home/condor/.fastai/data/mnist_png/training
```
**Expected behavior**
```python
Test
...
Path: /home/condor/.fastai/data/mnist_png/testing
```
**Additional context**
Related to [Issue 1218](https://github.com/fastai/fastai/issues/1218)?

**Comment by kdorichev** [comment]
It seems the fix is trivial. I am willing to provide a PR.

**Comment by sgugger** [comment]
The `path` attribute of the `LabelList` is only used to be passed to `DataBunch` then the `Learner`, and only the training one. So while this is a bug, I'm not sure it has any impact on anything. If the fix is easy, please go ahead and make a PR otherwise I wouldn't bother.

**Comment by kdorichev** [comment]
Since there is no real impact, let's ignore and keep the focus on other, more important stuff.
Thanks for your excellent work, Sylvain @sgugger.

**Comment by highskillzz** [comment]
Hello,

This is the code

data = (ImageList.from_folder("/kaggle/input/naruto-hand-sign-dataset/Pure Naruto Hand Sign Data/")
        .split_by_rand_pct()          
        .label_from_folder()
        .add_test_folder() 
        .transform(get_transforms(),size=128)
        .databunch()
        .normalize(imagenet_stats))


but for me, no test data is being generated

![image](https://user-images.githubusercontent.com/20688709/74231588-ed924380-4cec-11ea-8d29-ac203f7770d7.png)

Would be grateful for any help. Thanks!
