### ISSUE TITLE
TfmCrop doesn't work

### ISSUE THREAD

**Issue by juvian** [fastai/fastai#2422]
**Steps to reproduce**:

`open_image(data.train_ds.x.items[0]).apply_tfms(fastai.vision.transform.crop_pad(size=256, padding_mode='zeros')).shape`

**Output**: torch.Size([3, 1170, 1654])

The problem seems to be that arguments aren't passed to the function when using TfmCrop:

![image](https://user-images.githubusercontent.com/5660396/69596951-202c7a00-0fe3-11ea-8bde-310fc0460817.png)

I can see that the issue is in apply_tfms, but I don't fully understand how it is supposed to work so not sure how to fix it. 

Using TfmPixel instead seems to work:
![image](https://user-images.githubusercontent.com/5660396/69597216-f889e180-0fe3-11ea-9660-b79af2bf4621.png)

**A bit of context**:
Took me a long why to figure out why I was always running out of gpu memory when training, and it ended up being that the crop_pad wasn't resizing it as I needed. While .transform(([], []), size=256) works, I need that to be the last transform to be applied so removed it and added it as crop_pad transform.

**Comment by sgugger** [comment]
I'm not sure about your use case but the cropping will be the last transform to be applied (it has an order of 99 and all transforms are sorted by order in apply_tfms).
`crop_pad` is a bit weird in the sense that the size you pass to `crop_pad` only matter if you use it directly:
```
img = crop_pad(size=256)(img)
```
When using `apply_tfms`, the size is replaced by the size you pass along, so you need to give it there too:
```
img = img.apply_tfms(crop_pad, size=256)
```
I tested both on an example and the output has the right shape. It's the same for the `padding_mode`, you need to pass it to `apply_tfms` or it will be replaced by the default of that function.

**Comment by juvian** [comment]
I see, thanks! Always thought the size in transforms was just for the resizing but guess it is used by both. As for my case, I leave the solution in case others come in the future:

Doing 
`transform(([split_image_in_half(), crop_pad()], [crop_pad()]), tfm_y=True, size=512, padding_mode='zeros')`

instead of 

`transform(([split_image_in_half(), crop_pad(size=512, padding_mode='zeros')], [crop_pad(size=512, padding_mode='zeros')]), tfm_y=True)`

or

`.transform(([split_image_in_half(), crop_pad()], [crop_pad()]), tfm_y=True, size=512, padding_mode='zeros', resize_method=ResizeMethod.PAD)`

worked.
