### ISSUE TITLE
Missing type hint for return type and inconsistent use of Learner.load method

### ISSUE THREAD

**Issue by wAuner** [fastai/fastai#2425]
I looked up the exact use of the `Learner.load` method in the docs, when I noticed some inconsistencies between the docs, source code and how the method is used in the notebooks.

https://github.com/fastai/fastai/blob/de53504b1e62eb3f4798ae77013a9067e229ba56/fastai/basic_train.py#L260-L261

The function signature doesn't mention a type hint for the return type, but on line 283 https://github.com/fastai/fastai/blob/de53504b1e62eb3f4798ae77013a9067e229ba56/fastai/basic_train.py#L283

it returns a self reference. To add to the confusion, in the notebooks it is used without using the return value as in

`learn.save('stage-1-50')`
 while the [documentation](https://docs.fast.ai/basic_train.html#Learner.load) wants you to use the return value and reassign the model reference:
`
learn = learn.load("trained_model")`

**Comment by sgugger** [comment]
Note that you don't have to assign the value returned, the return is just there to make it easy to chain statements, such as:
```
learn = learn.load("trained_model").to_fp16()
```
Will add the missing type annotation.
