### ISSUE TITLE
Text classification - error unfreezing the learner, if no validation set present

### ISSUE THREAD

**Issue by tpietruszka** [fastai/fastai#2426]
**Describe the bug**
The shortest possible description:

If there is no validation set in the databunch, an error is raised during gradual unfreezing:
`RuntimeError: you can only change requires_grad flags of leaf variables.`

**Provide your installation details**
```text
=== Software === 
python        : 3.7.0
fastai        : 1.0.59
fastprogress  : 0.1.22
torch         : 1.3.1
nvidia driver : 418.87
torch cuda    : 10.1.243 / is available
torch cudnn   : 7603 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 8116MB | GeForce GTX 1080

=== Environment === 
platform      : Linux-4.15.0-70-generic-x86_64-with-debian-buster-sid
distro        : #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019
conda env     : ulmfit_attention
python        : /home/tomasz/anaconda3/envs/ulmfit_attention/bin/python
```
**To Reproduce**
~Minimal example with a traceback:
https://gist.github.com/tpietruszka/8a7f44077e0c7ad75c74acb323051805

Weird problem, as conditions necessary to replicate seem unrelated to the bug and to each other.

As far as I can tell, the error is raised if:
1. the DataBunch is created without a validation set (using the DataBlocks API, and `.split_none()`
2. the classifier is created, frozen, trained for some time, 
3. then `learn.freeze_to(-3)` or `learn.unfreeze()` raise an error. `freeze_to(-2)` does not.

now, if after creating the learner I `unfreeze()` straight away, everything is okay. 
If `freeze()` or `freeze_to(-2)` is run (and the model is trained), then `freeze_to(-3)` and `unfreeze()` raise.
If `freeze_to(-3)` is called (and then `fit_one_cycle`), -> `unfreeze()` raises.

My current understanding is that to get the error one has to:
1. freeze some layers
2. train for some time
3. unfreeze (to -3 or completely)

Also, everything works if the validation set is present.

It does not seem to be related to the specific pytorch version - I had this problem in some older one (1.2 I think), updated hoping it would somehow go away, but it persisted.

**Expected behavior**
No error, a trained `Learner` object

**Comment by sgugger** [comment]
Thanks a lot for the thorough investigation of this bug. I had seen it from time to time but never got a reliable reproducer.
It turns out a reset is necessary before freezing/unfreezing (something linked to the hack inside WeightDropout) so I just added that.

**Comment by tpietruszka** [comment]
Awesome, thanks for fixing it so quickly!
