### ISSUE TITLE
RuntimeError-cuda-runtime-error-710

### ISSUE THREAD

**Issue by somAzzz** [fastai/fastai#2428]
**Describe the bug**
Hi,
I`m trying to do Multi-label classification as Jeremy do in lesson 3 and I modified my own VOC-dataset over steel-surface images by labelme. When I run:

*****************************************
lr_find(learn)
learn.recorder.plot()
*****************************************
I got the error information:

```text
RuntimeError: cuda runtime error (710) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/THCUNN/generic/ClassNLLCriterion.cu:110
```

**installation details**
```text
=== Software === 
python        : 3.7.3
fastai        : 1.0.59
fastprogress  : 0.1.22
torch         : 1.3.1
nvidia driver : 430.14
torch cuda    : 10.1.243 / is available
torch cudnn   : 7603 / is enabled

=== Hardware === 
nvidia gpus   : 2
torch devices : 2
  - gpu0      : 11019MB | GeForce RTX 2080 Ti
  - gpu1      : 11019MB | GeForce RTX 2080 Ti

=== Environment === 
platform      : Linux-4.15.0-66-generic-x86_64-with-debian-stretch-sid
distro        : Ubuntu 16.04 xenial
conda env     : fastai_env
python        : /home/deextra/anaconda3/envs/fastai_env/bin/python
sys.path      : /home/deextra/anaconda3/fastaicode/steel_surface_detection
/home/deextra/anaconda3/envs/fastai_env/lib/python37.zip
/home/deextra/anaconda3/envs/fastai_env/lib/python3.7
/home/deextra/anaconda3/envs/fastai_env/lib/python3.7/lib-dynload

/home/deextra/anaconda3/envs/fastai_env/lib/python3.7/site-packages
/home/deextra/anaconda3/envs/fastai_env/lib/python3.7/site-packages/IPython/extensions
/home/deextra/.ipython
```

**To Reproduce**
[https://github.com/somAzzz/RuntimeError-cuda-runtime-error-710-using-fastai](https://github.com/somAzzz/RuntimeError-cuda-runtime-error-710-using-fastai)

regards

**Comment by sgugger** [comment]
This is a shape mismatch between the outputs of your model and targets that causes this error in the loss function, not a bug in the library. Please use the [forum](https://forums.fast.ai/) if you need help to debug it. The quick steps to debug are:
```
xb,yb = data.one_batch()
out = learn.model(xb)
loss = learn.loss_func(out, yb)
```
and you can inspect the shapes of xb, yb and out to solve your problem.

**Comment by somAzzz** [comment]
ok, I`ll try it. tks a lot!
