### ISSUE TITLE
Update fastai segfaults with fastai.vision

### ISSUE THREAD

**Issue by dsblank** [fastai/fastai#2435]
Just a heads up that I just did a `pip install fastai --upgrade --upgrade-strategy eager` on a working system, and then when doing an `import fastai.vision` python immediately segfaulted. 

I'm trying to rebuild a working system. I'll let you know if/when I succeed.

* python: 3.6.9
* os: linux
* torch: 1.3.1                
* torchvision: 0.4.2
* fastai: 1.0.59

**Comment by dsblank** [comment]
I'm not sure exactly what the issue was, but removing older versions of torch, torchvision, torchvision_nightly, and installing from fresh, with latest fastai 1.0.59 makes everything work again.

**Comment by dsblank** [comment]
Actually, it seems I have to import torch first:

```python
import torch
import fastai.vision
```
where this causes a segfault:
```python
import fastai.vision
```

**Comment by yamennassif** [comment]
i have the same error with Python 3.7 on ubuntu 16LTS 
but with fastai.text instead of fastai.vision

whenever i import it it will just segfault

**Comment by dsblank** [comment]
@yamennassif Try importing "torch" first. Does that help?

**Comment by yamennassif** [comment]
@dsblank i had to install different (older) versions of everything to get it running now. 
later i will try to get the new versions and then try again.

**Comment by sgugger** [comment]
Do we have a consistent way of getting the segfault? I have been trying fresh installs but didn't get anything wrong. Closing the issue, please reopen with a reproducible example.
