### ISSUE TITLE
load_learner: AttributeError: Can't get attribute 'WeightedLabelSmoothingCrossEntropy' on <module '__main__' from 'Cpet.py'>

### ISSUE THREAD

**Issue by yamennassif** [fastai/fastai#2436]
running the following code i have an error
```
file_name = "verbatim.pkl"
path = os.path.join(os.path.curdir)
load_learner(path, file_name, test=texts)
```
`AttributeError: Can't get attribute 'WeightedLabelSmoothingCrossEntropy' on <module '__main__' from 'Cpet.py'>`

problem is i wasnt the one who made that pkl file and i have no idea how it was extracted!

where can i start digging into this ?

full stack trace:

```Traceback (most recent call last):
  File "Cpet.py", line 24, in <module>
    classifier = load_learner(path, classifier_name, test=texts)
  File "/usr/local/lib/python3.7/site-packages/fastai/basic_train.py", line 616, in load_learner
    state = torch.load(source, map_location='cpu') if defaults.device == torch.device('cpu') else torch.load(source)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 613, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'WeightedLabelSmoothingCrossEntropy' on <module '__main__' from 'Cpet.py'>
```

**Comment by sgugger** [comment]
You need the code for 'WeightedLabelSmoothingCrossEntropy' in the same script as you are trying to load your `Learner`. Note that exporting the learner exports the weights and the name of the functions used to create the model/data but when using custom ones (as is the case here) you need to have the code for them too in your production environment.

**Comment by Baukebrenninkmeijer** [comment]
@sgugger Does it matter if the pytorch model is imported from another module or not? I'm trying to load and run a learner with flask, but wherever I paste the model definition, it doesn't seem to be able to find it.
