### ISSUE TITLE
EarlyStoppingCallback with mode='auto' and monitor='error_rate' doesn't set self.Operator() correctly

### ISSUE THREAD

**Issue by franva** [fastai/fastai#2442]
**Describe the bug**
When using EarlyStoppingCallback and leaving mode='auto', internally the self.Operator() is not set correctly if it was monitoring on error_rate.

**To Reproduce**
More details:
https://stackoverflow.com/questions/59517321/fast-ai-earlystoppingcallback-does-not-work/

**Additional context**
Under **TrackerCallback** class, inside the `__init__()` function, change the following line of code to include 'error'
`  mode_dict['auto'] = np.less if 'loss' or 'error' in self.monitor else np.greater`

**Comment by sgugger** [comment]
Yes, but `auto` is not meant to work in every case. I'll had the test but in general, you should pass along the correct mode when using a metric that needs to be as small as possible.

**Comment by franva** [comment]
if 'auto' doesn't mean to work in every case, then the word: auto is really misleading.
Suggestion to change 'auto' to 'best_guess' so that people will be aware of the situation and when things don't work out, they will not miss this piece: mode='auto'.

As the perception of auto means: it's smart enough to figure things out by itself.

**Comment by sgugger** [comment]
I'm curious how you imagine an auto could work for any user-defined metric or loss. In any case this was a user contribution to copy the API of Keras.

**Comment by franva** [comment]
hi @sgugger  thanks for your update.

Yes, the rename in v2 is much better than 'auto'. Also, I highly appreciate if we could use Full words instead of abbreviation. 

Abbreviations look much easy for people like you and other well AI-Educated people, but it's really hard for me who is just landed in the world of AI + Python + all jargon.

I know many of you guys coming from research organizations, but the IT industry likes to make things parameters crystal clean.

I come from an .NET developer here are some suggestions for naming conventions:

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines

I know some guys don't like Microsoft world, then using some other naming conventions, but please not using Abbreviation especially when documents are not fully covered.

Thanks for you guys to bring Fast.Ai to us.
I have to see it is a brilliant AI framework and probably the best AI framework that I have seen so far.

Great job~!
