### ISSUE TITLE
CSV Logger should not write headers in 'append' mode

### ISSUE THREAD

**Issue by hgasimov** [fastai/fastai#2443]
CSV Logger should not write headers in 'append' mode. Otherwise, we'll have CSV headers in the middle of CSV file. At the moment, it produces a result like this, if I use it in append mode:

	epoch	train_loss	valid_loss	error_rate	time
0	0	0.421814	0.215576	0.081452	00:18
1	1	0.339672	0.184925	0.076546	00:17
2	2	0.106375	0.050347	0.017174	00:17
3	3	0.090092	0.037133	0.009323	00:17
4	epoch	train_loss	valid_loss	error_rate	time
5	0	0.429223	0.249327	0.099607	00:17

Bug is here:

https://github.com/fastai/fastai/blob/775dcd03f49f4f6385f19b503f954468b83afbea/fastai/callbacks/csv_logger.py#L27

Something like this can solve the problem:

```
def on_train_begin(self, **kwargs: Any) -> None:
        "Prepare file with metric names."
        self.path.parent.mkdir(parents=True, exist_ok=True)      
        self.file = self.path.open('a') if self.append else self.path.open('w')
        file_has_content = self.path.exists() and self.path.open('r').readline() != ''
        if not file_has_content:
                self.file.write(','.join(self.learn.recorder.names[:(None if self.add_time else -1)]) + '\n')

```

**Comment by sgugger** [comment]
Should be fixed now.
