### ISSUE TITLE
SaveModelCallback seems to be saving model when performance decreases

### ISSUE THREAD

**Issue by maxmatical** [fastai/fastai#2447]
**Describe the bug**
When running
```
learn.fit_one_cycle(10, 
                    lr, 
                    callbacks=[SaveModelCallback(learn, every='improvement', monitor='accuracy', 
                                                 name='model')])
```
When running `fastai        : 1.0.61.dev0`, 
The model is not saved on improvement in accuracy, but rather saving it when accuracy decreases. This did not seem to be an issue in the `1.0.59` version of fastai

**Provide your installation details**
```
=== Software === 
python        : 3.6.9
fastai        : 1.0.61.dev0
fastprogress  : 0.2.2
torch         : 1.3.1
nvidia driver : 418.67
torch cuda    : 10.1.243 / is available
torch cudnn   : 7603 / is enabled
```

**Screenshots**
<img width="964" alt="image" src="https://user-images.githubusercontent.com/8890262/71843177-4426b500-3091-11ea-8e84-71a4cca20468.png">

**Comment by sgugger** [comment]
Thanks for flagging! It's a regression in a recent PR where the code was a tiny bit wrong, but I didn't catch it. Should be fixed now.
