### ISSUE TITLE
Problems with Random transformation not respecting Y. Especially in context of Y being a Mask

### ISSUE THREAD

**Issue by PiotrCzapla** [fastai/fastai#245]
I had huge issues getting the transformation to work with for current Data bowl competition. First it had the concurrency issues, now once this is fixed I've noticed that there are more issues. I will list them one by one in this thread and follow with a pull request that solves the issues.

✅  `RandomCrop` -  works fine
<img width="814" alt="screen shot 2018-03-24 at 18 52 15" src="https://user-images.githubusercontent.com/340180/37867145-7fbe4b5a-2f94-11e8-851f-0415bd32d4d9.png"> 

❌  `RandomRotate(10)` - does not repect masks see image below
<img width="931" alt="screen shot 2018-03-24 at 18 43 45" src="https://user-images.githubusercontent.com/340180/37867056-6e53e038-2f93-11e8-931d-6fa203e7714d.png">

❌ `RandomLighting(0.05, 0.05)` - changes light of a mask

❌ `RandomDihedral` - does not respect masks
<img width="873" alt="screen shot 2018-03-24 at 18 50 17" src="https://user-images.githubusercontent.com/340180/37867112-3722dd16-2f94-11e8-9b2b-ce19a751b5f2.png">

❌  `RandomFlip` -same issue
<img width="903" alt="screen shot 2018-03-24 at 18 51 03" src="https://user-images.githubusercontent.com/340180/37867123-5daa1666-2f94-11e8-90c5-7acb0e166a65.png">

❌  Normalize - tries to normalize binary Masks

**Comment by PiotrCzapla** [comment]
I think I see where the issue is. The `tfm_y` is not being set along when the  `tfms_from_stats` is called with `tfm_y=TfmType.MASK`. (see screenshot), which makes it impossible to use `aug_tfms=transforms_top_down` along with `tfm_y`. 

The issue isn't that easy to correct, as assign tfm_y to all aug_tfms will cause problems later as most of the time aug_tfms are global objects, that are reused between calls. But It could be a good temorary fix
<img width="908" alt="screen shot 2018-03-24 at 18 58 02" src="https://user-images.githubusercontent.com/340180/37867294-4d946fae-2f96-11e8-9af5-8e3ded1771c0.png">

**Comment by jph00** [comment]
I've just pushed some changes showing how to do this. See the transforms etc in this notebook: https://github.com/fastai/fastai/blob/master/courses/dl2/carvana.ipynb

**Comment by jph00** [comment]
BTW note you can't just say 'transforms_top_down'. You have to specify the transforms list in full, as shown in the notebook. Really we should change `transforms_top_down` to a function that takes a TfmType param...
