### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by radharani1306** [fastai/fastai#2451]
I am using python 3.8 on windows10 and unable to install "fastai". Even on python3.7.6 also not working.

I am getting the following error

Collecting fastai
  Using cached https://files.pythonhosted.org/packages/f5/e4/a7025bf28f303dbda0f862c09a7f957476fa92c9271643b4061a81bb595f/fastai-1.0.60-py3-none-any.whl
Collecting bottleneck
  Using cached https://files.pythonhosted.org/packages/62/d0/55bbb49f4fade3497de2399af70ec0a06e432c786b8623c878b11e90d456/Bottleneck-1.3.1.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numexpr
  Using cached https://files.pythonhosted.org/packages/d7/fd/6697b378c24fb0475754169186e9a4c69d807c5234e15dde0a8bd788f031/numexpr-2.7.1-cp37-none-win_amd64.whl
Collecting numpy>=1.15
  Using cached https://files.pythonhosted.org/packages/a9/38/f6d6d8635d496d6b4ed5d8ca4b9f193d0edc59999c3a63779cbc38aa650f/numpy-1.18.1-cp37-cp37m-win_amd64.whl
Requirement already satisfied: pyyaml in c:\python37\lib\site-packages (from fastai) (5.3)
Collecting matplotlib
  Using cached https://files.pythonhosted.org/packages/dd/73/dc25ca27a9960539ef984921b0d42368445b856ae0861c3acba542b9a39c/matplotlib-3.1.2-cp37-cp37m-win_amd64.whl
Collecting spacy>=2.0.18
  Using cached https://files.pythonhosted.org/packages/69/d8/f3103202aeca6fb0d2dbdd3a4ab1a7b86e9ad1d3cf8b23fa46bd466d64ac/spacy-2.2.3-cp37-cp37m-win_amd64.whl
Collecting scipy
  Using cached https://files.pythonhosted.org/packages/61/51/046cbc61c7607e5ecead6ff1a9453fba5e7e47a5ea8d608cc7036586a5ef/scipy-1.4.1-cp37-cp37m-win_amd64.whl
Collecting torchvision
  Using cached https://files.pythonhosted.org/packages/78/3f/7e419d248538ae28a6b29819613f8b1f0eeaccc07774267fc23a68d2b8d1/torchvision-0.4.1-cp37-cp37m-win_amd64.whl
ERROR: Could not find a version that satisfies the requirement torch>=1.0.0 (from fastai) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.0.0 (from fastai)

**Comment by sgugger** [comment]
Please use the [forum](https://forums.fast.ai/) for installation issues, along with all the details (what command did you run for instance), thanks!
