### ISSUE TITLE
confusing error massage for file not found in ImageDataBunch.from_folder kind of funcs

### ISSUE THREAD

**Issue by rushabh-v** [fastai/fastai#2459]
**Describe the bug**

If we run Image.Databunch.from_folder and pass a wrong path of the folder or the file doesn't exist at the mentioned path core.py's `index_row(a, idxs)` will raise,
`IndexError: index 0 is out of bounds for axis 0 with size 0`.
Which is very confusing for new users I think.  

**To Reproduce**

```
from fastai.vision import ImageDataBunch
ImageDataBunch.from_folder("")
```
Or enter any wrong path in the argument.

**Current behavior**
`IndexError: index 0 is out of bounds for axis 0 with size 0`

**Expected behavior**

It should raise a FileNotFoundError.

**I would like to open a PR which will raise a FileNotFoundError in this case.**

**Comment by sgugger** [comment]
Checked the directory is valid and added a clear error message if that's not the case. It's trickier for an empty directory, but I added some clearer message error mentioning the data source is empty. There are also warnings that the training set and the validation set both are empty.
