### ISSUE TITLE
Bug in tutorial.data.html in docs folder

### ISSUE THREAD

**Issue by arp95** [fastai/fastai#2471]
**Describe the bug**
As shown in the screenshot, the accuracy obtained with resnet18 was around 91% but written as 74%.

**Expected behavior**
Update the accuracy number in the html file from 74% to 91%.

**Screenshots**
![fastai](https://user-images.githubusercontent.com/8268392/73143124-4ebae580-4064-11ea-82c1-9b77ac6fcdec.png)

Can I submit a pr concerning this?

**Comment by sgugger** [comment]
Closed by #2473
