### ISSUE TITLE
Adding signature to datapath4file method 

### ISSUE THREAD

**Issue by arp95** [fastai/fastai#2474]
As seen in the screenshot:
![fastai2](https://user-images.githubusercontent.com/8268392/73220469-79707100-412c-11ea-9960-efa13d6b78ba.png)

The signature of filename is "filename:str" which I understood after going through the url2path and url2name functions. Should I change the signature and add "filename:str" in the code also?
The reason is while debugging I had to see the fastai documentation and understand the type of filename before I could debug the entire untar_data function.

**Comment by sgugger** [comment]
Yes, that would be good.

**Comment by sgugger** [comment]
Closed by #2475
