### ISSUE TITLE
Add skin cancer dataset

### ISSUE THREAD

**Issue by arp95** [fastai/fastai#2477]
Please check the dataset here. 
Training data: https://s3-us-west-1.amazonaws.com/udacity-dlnfd/datasets/skin-cancer/train.zip
Validation data: https://s3-us-west-1.amazonaws.com/udacity-dlnfd/datasets/skin-cancer/valid.zip

The data is publicly available and this repo explains how to get the data:
https://github.com/udacity/dermatologist-ai

Should we add the skin cancer dataset in the URLs class of fastai? @sgugger please check.

**Comment by sgugger** [comment]
Seems like  a good idea! I will work on this when I have time (probably next week).

**Comment by arp95** [comment]
Sure @sgugger. If I can be of help in this matter, like updating the URLs class etc., do tell me.

**Comment by krishnakatyal** [comment]
CAN I WORK ON THAT?

**Comment by sgugger** [comment]
Added the dataset on our S3 and in the URLs.
