### ISSUE TITLE
Documentation of ImageList.from_csv is missing

### ISSUE THREAD

**Issue by wAuner** [fastai/fastai#2479]
The [documentation of ImageList](https://docs.fast.ai/vision.data.html#ImageList) does not list the method `from_csv`. It's used in the notebooks and it still is in the sourcecode:

https://github.com/fastai/fastai/blob/ed3635d17a52af7ead2805b802f20b99fa7a7b28/fastai/vision/data.py#L292

Is this an error in the documenation build process?

**Comment by sgugger** [comment]
It's not in the corresponding doc notebook (at least not in the main part, it's in the Undocumented please move section). If you want to make a PR fixing this, it should appear during our next build.

**Comment by wAuner** [comment]
ok, I'll see if I can figure this out in the next days.
