### ISSUE TITLE
Fastai and Pytorch 1.4.0 incompatibility when using `load learner`

### ISSUE THREAD

**Issue by Ari-Ramkilowan** [fastai/fastai#2480]
Hi there. I've read through the relevant portion of the docs and I have searched through the forums but haven't been able to find a solution to the error I'm getting.

**Bug Description**

I get `AttributeError: 'LSTM' object has no attribute '_flat_weights_names'` when loading a pretrained language model/fine tuned classifier using `load_learner`

Installation details provided below

**Installation deets**
```text
=== Software === 
python        : 3.6.9
fastai        : 1.0.60
fastprogress  : 0.2.2
torch         : 1.4.0
nvidia driver : 440.48
torch cuda    : 10.1 / is **Not available** 

=== Hardware === 
nvidia gpus   : 1
Have 1 GPU(s), but torch can't use them (check nvidia driver) 

=== Environment === 
platform      : Linux-5.3.0-26-generic-x86_64-with-debian-buster-sid
distro        : #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019
conda env     : feersum_nlu
python        : /home/ari/anaconda3/envs/feersum_nlu/bin/python
sys.path      : 
/home/ari/anaconda3/envs/feersum_nlu/lib/python36.zip
/home/ari/anaconda3/envs/feersum_nlu/lib/python3.6
/home/ari/anaconda3/envs/feersum_nlu/lib/python3.6/lib-dynload
/home/ari/.local/lib/python3.6/site-packages
/home/ari/anaconda3/envs/feersum_nlu/lib/python3.6/site-packages
/home/ari/.local/lib/python3.6/site-packages/IPython/extensions
```

**To Reproduce**
I believe the error to be an incompatability with fastai and pytorch 1.4.0 so loading a pretrained LM or classifier with these versions will reproduce the error.

**Screenshots**
Relevant portion of stack trace given below

![Screenshot from 2020-01-30 10-34-02](https://user-images.githubusercontent.com/33620500/73432923-64722880-434c-11ea-9e0e-bdc3a7745623.png)

**Comment by sgugger** [comment]
Unfortunately there is nothing we can do on our side to fix this: you need to re-export your model with 1.4.0 then `load_learner` should work again.
From what I understand, they changed the code of LSTM, so when we unpickle a model trained with a previous version that has an LSTM, it crashes.
