### ISSUE TITLE
Minor documentation update (performance.md)

### ISSUE THREAD

**Issue by celynwalters** [fastai/fastai#2481]
This relates to [docs/performance.md](https://github.com/fastai/fastai/blob/ed3635d17a52af7ead2805b802f20b99fa7a7b28/docs/performance.md) (and I hope this affects the [documentation webpage](https://docs.fast.ai/performance.html))

Since (I believe) version 7.0.0, Pillow has a different command.

```bash
python -c "from PIL import Image; print(Image.PILLOW_VERSION)"
3.2.0.post3
```

is now:

```bash
python -c "from PIL import Image; print(Image.__version__)"
7.0.0.post3
```

The rest of the `Pillow-SIMD` instructions seem to be correct.

**Comment by sgugger** [comment]
The thing is since they did not offer backward compatibility, it's actually one of those two commands... I'll write an util function to grab the version when I have a bit of time.
