### ISSUE TITLE
not able to import * from fastai.vision in Google collab

### ISSUE THREAD

**Issue by akashkumar398** [fastai/fastai#2488]
**Describe the bug**

**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by akashkumar398** [comment]
![image](https://user-images.githubusercontent.com/24894328/74217332-291d1580-4ccd-11ea-8984-f6e2a24b8bac.png)

**Comment by akashkumar398** [comment]
it ran fine on TPU but it didn't work on GPU. Do you know the reason?

**Comment by sgugger** [comment]
The problem comes from torchvision.models, not fastai. You should raise an issue on their side.

Here are the imports we do from torchvision if you want to check which one fails to help them:
```
from torchvision.models import ResNet,resnet18,resnet34,resnet50,resnet101,resnet152
from torchvision.models import mobilenet_v2
from torchvision.models import SqueezeNet,squeezenet1_0,squeezenet1_1
from torchvision.models import densenet121,densenet169,densenet201,densenet161
from torchvision.models import vgg11_bn,vgg13_bn,vgg16_bn,vgg19_bn,alexnet
```
