### ISSUE TITLE
Invalid __repr__ on MultiLabelFbeta

### ISSUE THREAD

**Issue by dataframing** [fastai/fastai#2494]
**Describe the bug**
The `MultiLabelFbeta` metric (callback) has an invalid string representation `__repr__`. The `Callback` superclass defines the `__repr__` by inspecting the callback's initialization keywords and removing any attributes specified for removal from the string representation (see https://github.com/fastai/fastai/blob/master/fastai/callback.py#L202-L206):

```python
    def  __repr__(self):
        attrs = func_args(self.__init__)
        to_remove = getattr(self, 'exclude', [])
        list_repr = [self.__class__.__name__] + [f'{k}: {getattr(self, k)}' for k in attrs if k != 'self' and k not in to_remove]
        return '\n'.join(list_repr)
```

This introspection fails on the `MultiLabelFbeta` metric (callback) because although it takes `beta` as an initialization argument, it doesn't save `beta` as an instance attribute — it instead computes and saves the square (under `beta2`; see https://github.com/fastai/fastai/blob/master/fastai/metrics.py#L322-L323):

```python
    def __init__(self, beta=2, eps=1e-15, thresh=0.3, sigmoid=True, average="micro"):
        self.eps,self.thresh,self.sigmoid,self.average,self.beta2 = eps,thresh,sigmoid,average,beta**2
```

The specific traceback is as follows:

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-ec0b0ec30755> in <module>
----> 1 print(MultiLabelFbeta())

~/.local/share/virtualenvs/srs-DkOf0qi1/lib/python3.7/site-packages/fastai/callback.py in __repr__(self)
    203         attrs = func_args(self.__init__)
    204         to_remove = getattr(self, 'exclude', [])
--> 205         list_repr = [self.__class__.__name__] + [f'{k}: {getattr(self, k)}' for k in attrs if k != 'self' and k not in to_remove]
    206         return '\n'.join(list_repr)
    207 

~/.local/share/virtualenvs/srs-DkOf0qi1/lib/python3.7/site-packages/fastai/callback.py in <listcomp>(.0)
    203         attrs = func_args(self.__init__)
    204         to_remove = getattr(self, 'exclude', [])
--> 205         list_repr = [self.__class__.__name__] + [f'{k}: {getattr(self, k)}' for k in attrs if k != 'self' and k not in to_remove]
    206         return '\n'.join(list_repr)
    207 

AttributeError: 'MultiLabelFbeta' object has no attribute 'beta'
```

I think there are a few ways forward:

1. Register `beta` under the `exclude` class attribute on `MultiLabelFbeta` (e.g., `MultiLabelFbeta.exclude = ['beta']`.

    ```python
    class MultiLabelFbeta(Callback):
        ...
        exclude = ['beta']
        ...
    ```

1. Update the superclass `__repr__` by also checking that the instance has the actual attribute:

    ```python
    def  __repr__(self):
        ...
        list_repr = [self.__class__.__name__] + [f'{k}: {getattr(self, k)}' for k in attrs if k != 'self' and k not in to_remove and hasattr(self, k)]
        ...
    ```

1. Save `beta` on the callback, like we do with `beta2`. Though this seems unnecessary and seems like a code smell.

Regardless, I'm happy to open a PR that fixes this; let me know what you all think works best. Thanks!

**Provide your installation details**
```text
=== Software === 
python        : 3.7.6
fastai        : 1.0.60
fastprogress  : 0.2.2
torch         : 1.4.0
nvidia driver : 418.87
torch cuda    : 10.1 / is available
torch cudnn   : 7603 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 16130MB | Tesla V100-SXM2-16GB

=== Environment === 
platform      : Linux-4.4.0-1101-aws-x86_64-with-debian-stretch-sid
distro        : #112-Ubuntu SMP Thu Jan 9 11:27:02 UTC 2020
conda env     : srs
python        : /home/ubuntu/.local/share/virtualenvs/srs-DkOf0qi1/bin/python
sys.path      : /home/ubuntu/srs/notebooks/models
/home/ubuntu/.local/share/virtualenvs/srs-DkOf0qi1/lib/python3.7/site-packages/_pdbpp_path_hack
/home/ubuntu/src/cntk/bindings/python
/home/ubuntu/anaconda3/envs/srs/lib/python37.zip
/home/ubuntu/anaconda3/envs/srs/lib/python3.7
/home/ubuntu/anaconda3/envs/srs/lib/python3.7/lib-dynload

/home/ubuntu/.local/share/virtualenvs/srs-DkOf0qi1/lib/python3.7/site-packages
/home/ubuntu/.local/share/virtualenvs/srs-DkOf0qi1/lib/python3.7/site-packages/IPython/extensions
/home/ubuntu/.ipython
```

**To Reproduce**
In any environment:

```python
import fastai.metrics as fmet
print(fmet.MultiLabelFbeta())
```

I think we could add a test that simply tests each callback's string representation is valid (i.e., does not raise an `AttributeError`).

**Expected behavior**
I expect callbacks to have a standard string representation. This bug was initially raised after fitting a model, which was unfortunate.

**Screenshots**
N/A.

**Additional context**
I've reproduced this bug both on Ubuntu (logs above) and macOS (locally).

**Comment by sgugger** [comment]
Thanks for all the details, it made solving the issue really easy :)
In this case, I think the best is to store the attribute as is (and not the square) so that the representation is as comprehensive as possible.
