### ISSUE TITLE
tabular get_preds outputs zero category for all items in Test dataset (individual predict is ok)

### ISSUE THREAD

**Issue by cluePrints** [fastai/fastai#2495]
**Describe the bug**
`get_preds(Test)` outputs zero category for all the items in the dataset. Individual `predict()` is ok.

Probabilities returned by both do match.

**Provide your installation details**
```text
=== Software === 
python       : 3.6.9
fastai       : 1.0.60
fastprogress : 0.2.2
torch        : 1.4.0
torch cuda   : 10.1 / is **Not available** 

=== Hardware === 
No GPUs available 

=== Environment === 
platform     : Linux-4.14.137+-x86_64-with-Ubuntu-18.04-bionic
distro       : #1 SMP Thu Aug 8 02:47:02 PDT 2019
conda env    : Unknown
python       : /usr/bin/python3
sys.path     : 
/env/python
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/usr/local/lib/python3.6/dist-packages/IPython/extensions
/root/.ipython
no supported gpus found on this system
```

**To Reproduce**
- CPU: [google colab](https://colab.research.google.com/drive/1G3u48O04qGXnvY0s6Uv-u8bnbcqakzQT#scrollTo=f-ve5m3X3bMX)
- GPU: [google colab](https://colab.research.google.com/drive/1jteB3yXlV9PYnAVCsNjBP8H0ysfuF7o1#scrollTo=CzfweWla3fTL)

**Expected behavior**

```
> learn.predict(df_test[feature_names].iloc[1])
(Category 1, tensor(1), tensor([0.2549, 0.7451]))

> preds, y = learn.get_preds(DatasetType.Test)
> y[1], preds[1]
(tensor(0), tensor([0.2549, 0.7451]))                       # tensor(0) should be tensor(1) here
```

**Screenshots**

**Additional context**

**Comment by muellerzr** [comment]
Your y’s will always be zero because they are unlabeled. Labeled test sets are natively supported only in fastai2. There are workarounds in v1, search the forums. To get your tensor(1), take the argmax of your raw probabilities (the other two numbers)

**Comment by sgugger** [comment]
Exactly. the `y` in `get_preds` is the target, which, in the case of a test set, is just a sequence of 0s since there is no labels.

**Comment by swayson** [comment]
> Your y’s will always be zero because they are unlabeled. Labeled test sets are natively supported only in fastai2. There are workarounds in v1, search the forums. To get your tensor(1), take the argmax of your raw probabilities (the other two numbers)

`predicted_classes = preds.argmax(axis=1)`
