### ISSUE TITLE
Error assigning Loss Function to learner

### ISSUE THREAD

**Issue by rpdunne** [fastai/fastai#2497]
```
=== Software === 
python        : 3.7.6
fastai        : 1.0.57
fastprogress  : 0.1.21
torch         : 1.4.0
nvidia driver : 441.22
torch cuda    : 10.1 / is available
torch cudnn   : 7501 / is enabled

=== Hardware === 
nvidia gpus   : 2
torch devices : 2
  - gpu0      : 8129MB | Tesla M60
  - gpu1      : 8129MB | Tesla M60

=== Environment === 
platform      : Windows-10-10.0.14393-SP0
conda env     : ml
python        : C:\Users\-sysop-dur7an-z\.conda\envs\ml\python.exe
```

**Describe the bug**

When I train a learner `learn = unet_learner(data ,models.resnet50, metrics=metrics)`  with the default Loss function (FlattenedLoss), I have no error and the model trains fine. However, when I try to use another loss function, (e.g. `learn.loss_func = nn.BCEWithLogitsLoss()` ), I get the following error:

`ValueError: Target size (torch.Size([2, 1, 64, 128])) must be the same as input size (torch.Size([2, 2, 64, 128]))`

Do you know why this is?

**Provide your installation details**

**To Reproduce**

```
learn = unet_learner(data ,models.resnet50, metrics=metrics)
learn.loss_fn = nn.BCEWithLogitsLoss()
```

`lr_find(learn)`

`ValueError: Target size (torch.Size([2, 1, 64, 128])) must be the same as input size (torch.Size([2, 2, 64, 128]))`

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
Please use the forum for debugging your code, this is also going to benefit more members of the community if we have the discussion there. Here BCEWithLogitsLoss is unvalid because you don't have one-hot encoded targets.
