### ISSUE TITLE
XDG Base Directory Support

### ISSUE THREAD

**Issue by billop** [fastai/fastai#2509]
**Describe the bug**

Fastai does not respect the XDG base directory specifications.

**Expected behavior**
Configuration and data should not be in the same folder. Configuration should be in `$XDG_CONFIG_HOME`, and fall back to `.config/fastai/`. Data should be in `$XDG_DATA_HOME` and fallback to `.local/share/fastai/`.
This is a breaking change so I hope at least fastai2 respects the spec in the future.

**Additional context**

https://wiki.archlinux.org/index.php/XDG_Base_Directory
https://wiki.gnome.org/Initiatives/GnomeGoals/XDGConfigFolders
https://web.archive.org/web/20180827160401/plus.google.com/+RobPikeTheHuman/posts/R58WgWwN9jp

**Comment by sgugger** [comment]
There is no plan to respect that spec in the future, no. None of the software we depend on seems to be following it either. In general we use the [forum](https://forums.fast.ai/) to discuss feature requests, so I encourage you to open a topic there if you want to discuss this further with the community.

**Comment by billop** [comment]
> None of the software we depend on seems to be following it either.

Just curious, I raised this issue partially because [pytorch is pretty good about it](https://github.com/pytorch/pytorch/issues/14693), do you have any dependencies in mind that don't follow the spec? It seems like the only ones I can see are some dev dependencies but that doesn't matter to end users.

**Comment by sgugger** [comment]
I was mostly thinking about jupyter.
