### ISSUE TITLE
Module not found error:

### ISSUE THREAD

**Issue by srp6996** [fastai/fastai#2510]
**Describe the bug**

**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by srp6996** [comment]
from fastai.transforms import tfms_from_model, CropType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fastai.transforms'

Platform: Linux

i have installed fastai using 
conda install -c fastai fastai

**Comment by sgugger** [comment]
It looks like you want to use v0.7 of fastaim for which should not use a conda install but follow the instructions [here](https://github.com/fastai/fastai/tree/master/old).
