### ISSUE TITLE
Lesson 2 sgd gets "can't call numpy" error when drawing plot

### ISSUE THREAD

**Issue by tchaffee** [fastai/fastai#2514]
**Describe the bug**
lesson2-sgd notebook gets an error for the following cell:

```
plt.scatter(x[:,0],y)
plt.scatter(x[:,0],x@a);
```

The last line of the long traceback says:

```
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.
```

The same error happens for the animation cell.

I can submit a PR to fix this, but I cannot find the lesson2-sgd notebook in this repo.

**Provide your installation details**

```text
=== Software ===
python        : 3.6.7
fastai        : 1.0.60
fastprogress  : 0.2.2
torch         : 1.4.0
nvidia driver : 418.67
torch cuda    : 10.1 / is available
torch cudnn   : 7603 / is enabled

=== Hardware ===
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 8126MB | Quadro M4000

=== Environment ===
platform      : Linux-4.15.0-72-generic-x86_64-with-debian-stretch-sid
distro        : #81~16.04.1-Ubuntu SMP Tue Nov 26 16:34:21 UTC 2019
conda env     : fastai
python        : /opt/conda/envs/fastai/bin/python
sys.path      :
/opt/conda/envs/fastai/lib/python36.zip
/opt/conda/envs/fastai/lib/python3.6
/opt/conda/envs/fastai/lib/python3.6/lib-dynload
/opt/conda/envs/fastai/lib/python3.6/site-packages
/opt/conda/envs/fastai/lib/python3.6/site-packages/IPython/extensions
```

**To Reproduce**

Just run that cell.

**Expected behavior**

The plot will be drawn instead of getting an error.

**Screenshots**

**Additional context**

**Comment by tchaffee** [comment]
FYI, this problem and the fix is mentioned in the forums here: https://forums.fast.ai/t/lesson-2-gsd-plot-issue/61622

**Comment by sgugger** [comment]
You are using the old course with version 1.4.0 of PyTorch. It is compatible with version 0.3 as is expressed in the [requirements](https://github.com/fastai/fastai/blob/27ab982e94a75cd81920b5ab6155f6961d69174c/environment.yml#L94) for the old course. If you do not follow the installations instructions for the old course, do not expect it to work. If you want to use more recent versions of PyTorch, please follow the [last version of our course](https://course.fast.ai/).

**Comment by tchaffee** [comment]
@sgugger I believe I am using the new version of the course. I followed the setup instructions. Please help me understand what's wrong.

![Selection_999(304)](https://user-images.githubusercontent.com/148813/77548995-0f571c80-6e8e-11ea-9cff-c374169de93d.png)

**Comment by tchaffee** [comment]
I ran the following commands from the https://course.fast.ai/start_gradient.html instructions:

```
pip install fastai --upgrade
cd course-v3
git pull
```

Still getting this error. Maybe something is wrong with the Gradient container that someone set up?

**Comment by tchaffee** [comment]
@sgugger I finally figured out I was in the wrong repo. This is an actual reported issue with the course v3 and I submitted a PR here. https://github.com/fastai/course-v3/pull/489
