### ISSUE TITLE
Cmap cannot be changed for segmentation masks using show_batch/show_result

### ISSUE THREAD

**Issue by Samcro5C** [fastai/fastai#2518]
**Describe the bug**

When creating a custom colormap which should be applied to the segmentation mask using *data.show_batch()* , or *learn.show_result()*, the default colormap 'tab20' is used instead.
For example, if there are three labels and you want to have each label showing the same color over all samples, independet of the amount of labels in a single sample, you could create a custom Matplotlib colormap and a normalization to ensure the same color for a specific value over all samples.
```
from Matplotlib import colors
custom_cmap = colors.ListedColormap(["red", "green", "blue"])
custom_norm = colors.Normalize(vmin=0, vmax=2)
data.show_batch(2, figsize=(10,10), cmap=custom_map, norm=custom_norm)
```
However, when passing two extra arguments *cmap* and *norm* to *data.show_batch()*, only the latter is passed to the actual matplotlib *imshow()* function. So now the color stays the same for a specific label over all samples, but unfortunately it is not the intended color.
It seems that when *show_xyzy()* and later *x.show()* (with x being an ImageSegment object) is called, the *cmap* argument previously defined and part of *\*\*kwargs* is neglected, as the ImageSegment.show() method has its own *cmap* argument which defaults to 'tab20'.
Maybe it would be better to check if *cmap* is already defined within *\*\*kwargs* and if not set it to 'tab20'?

**Provide your installation details**

=== Software === 
python        : 3.7.6
fastai        : 1.0.60
fastprogress  : 0.2.2
torch         : 1.4.0
nvidia driver : 440.59
torch cuda    : 10.1 / is available
torch cudnn   : 7603 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 7982MB | GeForce RTX 2080 SUPER

=== Environment === 
platform      : Linux-5.3.0-40-generic-x86_64-with-debian-buster-sid
distro        : #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020
conda env     : pytorch_env
python        : /home/cloudator/anaconda3/envs/pytorch_env/bin/python
sys.path      : /home/cloudator/git/sfmt_meteo_nowcasting/CloudCamPrograms/Source/CloudSegmentation/DeepNet/visualization
/home/cloudator/git/sfmt_meteo_nowcasting/CloudCamPrograms/Source/CloudSegmentation/DeepNet/models
/home/cloudator/git/sfmt_meteo_nowcasting/CloudCamPrograms/Source/CloudSegmentation/DeepNet/data
/home/cloudator/git/sfmt_meteo_nowcasting/CloudCamPrograms/Source/CloudSegmentation/DeepNet/notebooks
/home/cloudator/anaconda3/envs/pytorch_env/lib/python37.zip
/home/cloudator/anaconda3/envs/pytorch_env/lib/python3.7
/home/cloudator/anaconda3/envs/pytorch_env/lib/python3.7/lib-dynload

/home/cloudator/anaconda3/envs/pytorch_env/lib/python3.7/site-packages
/home/cloudator/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/IPython/extensions
/home/cloudator/.ipython

**Comment by sgugger** [comment]
In v1, there will be no change to the current implementation. You can subclass `ImageMask` to implement your defaults then define a custom `SegmentationItemList` using it. v2 will be more flexible.
