### ISSUE TITLE
FastaiV1：Lesson1-pets：learn.fit_one_cycle(4)

### ISSUE THREAD

**Issue by xiaosuzhang** [fastai/fastai#2519]
**Describe the bug**

When i run :learn.fit_one_cycle(4)
the erros occus:
BrokenPipeError                           Traceback (most recent call last)
<ipython-input-14-495233eaf2b4> in <module>
----> 1 learn.fit_one_cycle(4)

E:\Anaconda\envs\fastai\lib\site-packages\fastai\train.py in fit_one_cycle(learn, cyc_len, max_lr, moms, div_factor, pct_start, final_div, wd, callbacks, tot_epochs, start_epoch)
     21     callbacks.append(OneCycleScheduler(learn, max_lr, moms=moms, div_factor=div_factor, pct_start=pct_start,
     22                                        final_div=final_div, tot_epochs=tot_epochs, start_epoch=start_epoch))
---> 23     learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
     24 
     25 def fit_fc(learn:Learner, tot_epochs:int=1, lr:float=defaults.lr,  moms:Tuple[float,float]=(0.95,0.85), start_pct:float=0.72,

E:\Anaconda\envs\fastai\lib\site-packages\fastai\basic_train.py in fit(self, epochs, lr, wd, callbacks)
    198         else: self.opt.lr,self.opt.wd = lr,wd
    199         callbacks = [cb(self) for cb in self.callback_fns + listify(defaults.extra_callback_fns)] + listify(callbacks)
--> 200         fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
    201 
    202     def create_opt(self, lr:Floats, wd:Floats=0.)->None:

E:\Anaconda\envs\fastai\lib\site-packages\fastai\basic_train.py in fit(epochs, learn, callbacks, metrics)
     97             cb_handler.set_dl(learn.data.train_dl)
     98             cb_handler.on_epoch_begin()
---> 99             for xb,yb in progress_bar(learn.data.train_dl, parent=pbar):
    100                 xb, yb = cb_handler.on_batch_begin(xb, yb)
    101                 loss = loss_batch(learn.model, xb, yb, learn.loss_func, learn.opt, cb_handler)

E:\Anaconda\envs\fastai\lib\site-packages\fastprogress\fastprogress.py in __iter__(self)
     45         except Exception as e:
     46             self.on_interrupt()
---> 47             raise e
     48 
     49     def update(self, val):

E:\Anaconda\envs\fastai\lib\site-packages\fastprogress\fastprogress.py in __iter__(self)
     39         if self.total != 0: self.update(0)
     40         try:
---> 41             for i,o in enumerate(self.gen):
     42                 if i >= self.total: break
     43                 yield o

E:\Anaconda\envs\fastai\lib\site-packages\fastai\basic_data.py in __iter__(self)
     73     def __iter__(self):
     74         "Process and returns items from `DataLoader`."
---> 75         for b in self.dl: yield self.proc_batch(b)
     76 
     77     @classmethod

E:\Anaconda\envs\fastai\lib\site-packages\torch\utils\data\dataloader.py in __iter__(self)
    277             return _SingleProcessDataLoaderIter(self)
    278         else:
--> 279             return _MultiProcessingDataLoaderIter(self)
    280 
    281     @property

E:\Anaconda\envs\fastai\lib\site-packages\torch\utils\data\dataloader.py in __init__(self, loader)
    717             #     before it starts, and __del__ tries to join but will get:
    718             #     AssertionError: can only join a started process.
--> 719             w.start()
    720             self._index_queues.append(index_queue)
    721             self._workers.append(w)

E:\Anaconda\envs\fastai\lib\multiprocessing\process.py in start(self)
    103                'daemonic processes are not allowed to have children'
    104         _cleanup()
--> 105         self._popen = self._Popen(self)
    106         self._sentinel = self._popen.sentinel
    107         # Avoid a refcycle if the target function holds an indirect

E:\Anaconda\envs\fastai\lib\multiprocessing\context.py in _Popen(process_obj)
    221     @staticmethod
    222     def _Popen(process_obj):
--> 223         return _default_context.get_context().Process._Popen(process_obj)
    224 
    225 class DefaultContext(BaseContext):

E:\Anaconda\envs\fastai\lib\multiprocessing\context.py in _Popen(process_obj)
    320         def _Popen(process_obj):
    321             from .popen_spawn_win32 import Popen
--> 322             return Popen(process_obj)
    323 
    324     class SpawnContext(BaseContext):

E:\Anaconda\envs\fastai\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     63             try:
     64                 reduction.dump(prep_data, to_child)
---> 65                 reduction.dump(process_obj, to_child)
     66             finally:
     67                 set_spawning_popen(None)

E:\Anaconda\envs\fastai\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

BrokenPipeError: [Errno 32] Broken pipe

**Provide your installation details**

=== Software === 
python        : 3.6.10
fastai        : 1.0.60
fastprogress  : 0.2.2
torch         : 1.4.0
torch cuda    : 10.1 / is available
torch cudnn   : 7501 / is enabled

=== Hardware === 
torch devices : 1
  - gpu0      : GeForce GTX 1060 with Max-Q Design

=== Environment === 
platform      : Windows-10-10.0.18362-SP0
conda env     : fastai
python        : E:\Anaconda\envs\fastai\python.exe
sys.path      : E:\Anaconda\envs\fastai\python36.zip
E:\Anaconda\envs\fastai\DLLs
E:\Anaconda\envs\fastai\lib
E:\Anaconda\envs\fastai

E:\Anaconda\envs\fastai\lib\site-packages
E:\Anaconda\envs\fastai\lib\site-packages\win32
E:\Anaconda\envs\fastai\lib\site-packages\win32\lib
E:\Anaconda\envs\fastai\lib\site-packages\Pythonwin
E:\Anaconda\envs\fastai\lib\site-packages\IPython\extensions
C:\Users\jwxxz\.ipython
no nvidia-smi is found

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Gokkulnath** [comment]
Hi @xiaosuzhang ,

Can you check the num_workers passed in the dataloader? It should be set to 0 in Windows based systems as Pytorch's Multiworkers don't work well on windows.

**Comment by xiaosuzhang** [comment]
> Hi @xiaosuzhang ,
> 
> Can you check the num_workers passed in the dataloader? It should be set to 0 in Windows based systems as Pytorch's Multiworkers don't work well on windows.
> If it is a tutorial, you need to pass the argument explicitly else it will default to 4 i guess, which is why it's failing

Thank's for you solution. It has already worked.

**Comment by sgugger** [comment]
Closing the issue then. In general, please use the forum for problems like this :)
