### ISSUE TITLE
Default argument of purge in learn.load

### ISSUE THREAD

**Issue by rdutta1999** [fastai/fastai#2529]
https://github.com/fastai/fastai/blob/3b54ef1575f941721c7d5ec4011ebaf51cd06eeb/fastai/basic_train.py#L261

It is mentioned in the [docs](https://docs.fast.ai/basic_train.html#Learner.load) that `learn.load()` should call `learn.purge` since the default argument for purge is `True`, but the source code says otherwise.

**Comment by sgugger** [comment]
Yes the default was changed because this function breaks things in some cases. Will adapt the docs.

**Comment by sgugger** [comment]
Fixed by [this commit](https://github.com/fastai/fastai/commit/627cb3f35f234ff2e5dc6237ac9089dc650f271a).

**Comment by rdutta1999** [comment]
The same thing is also mentioned in the article [Deep Learning on a Shoestring](https://docs.fast.ai/tutorial.resources.html). If you would kindly update that also.

**Comment by sgugger** [comment]
Thanks, updated this one too.
