### ISSUE TITLE
Please follow the XDG Base Directory Specification

### ISSUE THREAD

**Issue by bjourne** [fastai/fastai#2532]
On Linux, the XDG Base Directory Specification should be followed: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

In practice, that means putting user specific files in `~/.local/share/fastai` and `~/.config/fastai` instead of in `~/.fastai`.

**Comment by sgugger** [comment]
Please post feature requests on the [forum](https://forums.fast.ai/). We keep issues for known bugs only. As it has been asked several times, we will take into consideration, but since it's quite a breaking change, it will be for v2 only.
