### ISSUE TITLE
code redundency

### ISSUE THREAD

**Issue by amigd23** [fastai/fastai#2535]
```a = np.transpose(a, (1, 0, 2))```
```a = np.transpose(a, (2, 1, 0))```

[see here in vision/image.py](https://github.com/fastai/fastai/blob/3b7c453cfa3845c6ffc496dd4043c07f3919270e/fastai/vision/image.py#L18-L19)

Not a bug, but wonder isn't this the same with ```a = np.transpose(a, (2, 0, 1))```?

**Comment by sgugger** [comment]
Yes but it is much faster from our experiments. There was a comment in the code that explained that. Don't know where it went.
