### ISSUE TITLE
Importing from basic_train raises error

### ISSUE THREAD

**Issue by andycraig** [fastai/fastai#2537]
**Describe the bug**

Trying to import from `fastai.basic_train` causes a `KeyError` when using the current `master` version.

**Provide your installation details**

```text
=== Software === 
python        : 3.6.8
fastai        : 1.0.61.dev0
fastprogress  : 0.2.3
torch         : 1.4.0
nvidia driver : 390.116
torch cuda    : 10.1 / is **Not available** 

=== Hardware === 
nvidia gpus   : 1
Have 1 GPU(s), but torch can't use them (check nvidia driver) 

=== Environment === 
platform      : Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic
distro        : #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
conda env     : Unknown
python        : /home/ac/projects/python/fastaibug/env/bin/python
sys.path      : 
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/ac/projects/python/fastaibug/env/lib/python3.6/site-packages
/home/ac/projects/python/fastaibug/env/lib/python3.6/site-packages/IPython/extensions
```

This is using the latest version, installed with `pip install git+https://github.com/fastai/fastai/`.

**To Reproduce**

```
from fastai.basic_train import *
```

Result:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ac/projects/python/fastaibug/env/lib/python3.6/site-packages/fastai/basic_train.py", line 454, in <module>
    class Recorder(LearnerCallback):
  File "/home/ac/projects/python/fastaibug/env/lib/python3.6/site-packages/fastai/basic_train.py", line 541, in Recorder
    **kwargs)->Optional[plt.Figure]:
NameError: name 'kwargs' is not defined
```

**Expected behavior**

Nothing (imports successfully).

**Additional context**

There does seem to be a missing comma at the end of this line, which is probably causing a syntax error: https://github.com/fastai/fastai/blob/ee3d75c35f730f63f13f6cbbf88d61343a43b201/fastai/basic_train.py#L540

Thank you.

**Comment by sgugger** [comment]
Oh thanks for pointing it out! Note that in situations like this where you find the fix, you can directly suggest a PR :)

**Comment by andycraig** [comment]
@sgugger Thank you for the quick fix! Noted, will do so in future :)
