### ISSUE TITLE
TabularProc constructors cause error

### ISSUE THREAD

**Issue by andycraig** [fastai/fastai#2542]
**Describe the bug**

`TabularProc` subclasses cannot be used via their constructors. E.g., `FillMissing` is okay, but `FillMissing(cat_names, cont_names, fill_strategy=FillStrategy.CONSTANT)` will cause an error.

The same applies for `Categorify` and `Normalize`, but they don't have any additional constructor arguments so there's no reason to ever create them via the constructor.

I asked a question about this on the forum: https://forums.fast.ai/t/errors-using-tabularproc-constructors/67975 but looking at the fastai code I'm pretty sure this is a bug. The only other thread I could find on the forum about `TabularProc` constructors was this one: https://forums.fast.ai/t/how-to-change-fillmissing-to-a-constant-in-procs-for-tabular-data/32616 The answer suggests that the `FillMissing`'s `fill_strategy` values etc. be set by subclassing it, rather than using the constructor.

**Provide your installation details**

```text
=== Software === 
python        : 3.6.8
fastai        : 1.0.61.dev0
fastprogress  : 0.2.3
torch         : 1.4.0
nvidia driver : 390.116
torch cuda    : 10.1 / is **Not available** 

=== Hardware === 
nvidia gpus   : 1
Have 1 GPU(s), but torch can't use them (check nvidia driver) 

=== Environment === 
platform      : Linux-4.15.0-96-generic-x86_64-with-Ubuntu-18.04-bionic
distro        : #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020
conda env     : Unknown
python        : /home/ac/projects/python/fastaigit/env/bin/python
sys.path      : 
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/ac/projects/python/fastaigit/env/lib/python3.6/site-packages
```

Using fastai installed with `pip install git+https://github.com/fastai/fastai/` d1551ab3221812bd47e704fc4f5e59e2b6938216

**To Reproduce**

Here is an example using `FillMissing` with and without its constructor:

```
from fastai.tabular import *

path = untar_data(URLs.ADULT_SAMPLE)

cat_names = ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']
cont_names = ['age', 'fnlwgt', 'education-num']

# Modified version of learn() from:
# https://github.com/fastai/fastai/blob/1a914b365720aa216a4a377705fe11707a665fe9/tests/test_tabular_train.py
def preprocess(procs=[FillMissing, Categorify, Normalize]):
    df = pd.read_csv(path/'adult.csv')
    dep_var = 'salary'
    test = TabularList.from_df(df.iloc[800:1000].copy(), path=path, cat_names=cat_names, cont_names=cont_names)
    data = (TabularList.from_df(df, path=path, cat_names=cat_names, cont_names=cont_names, procs=procs)
        .split_by_idx(list(range(800,1000)))
        .label_from_df(cols=dep_var)
        .add_test(test)
        .databunch(num_workers=1))

# Succeeds
preprocess([FillMissing, Categorify, Normalize])

# Fails
preprocess([FillMissing(cat_names=cat_names, cont_names=cont_names, fill_strategy=FillStrategy.CONSTANT), Categorify, Normalize])
```

Stack trace:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "<stdin>", line 9, in preprocess
  File "/home/ac/projects/python/fastaigit/env/lib/python3.6/site-packages/fastai/data_block.py", line 483, in _inner
    self.process()
  File "/home/ac/projects/python/fastaigit/env/lib/python3.6/site-packages/fastai/data_block.py", line 537, in process
    for ds,n in zip(self.lists, ['train','valid','test']): ds.process(xp, yp, name=n)
  File "/home/ac/projects/python/fastaigit/env/lib/python3.6/site-packages/fastai/data_block.py", line 717, in process
    self.x.process(xp)
  File "/home/ac/projects/python/fastaigit/env/lib/python3.6/site-packages/fastai/data_block.py", line 84, in process
    for p in self.processor: p.process(self)
  File "/home/ac/projects/python/fastaigit/env/lib/python3.6/site-packages/fastai/tabular/data.py", line 62, in process
    if isinstance(proc, TabularProc): proc(ds.inner_df, test=True)
  File "/home/ac/projects/python/fastaigit/env/lib/python3.6/site-packages/fastai/tabular/transform.py", line 124, in __call__
    func(df)
  File "/home/ac/projects/python/fastaigit/env/lib/python3.6/site-packages/fastai/tabular/transform.py", line 172, in apply_test
    if name in self.na_dict:
AttributeError: 'FillMissing' object has no attribute 'na_dict'
```

**Expected behavior**

Runs without raising an error.

**Additional context**

I believe the reason for this error is that `apply_test` is being called before `apply_train` has been called. We can check with this `TabularProc` subclass. (Run this code after running the code above.)

```
class TrainBeforeTest(TabularProc):
    trained = False
    def apply_train(self, df:DataFrame):
        self.trained = True
    def apply_test(self, df:DataFrame):
        if not self.trained:
            raise Exception("apply_test called before apply_train")

# Succeeds
preprocess([TrainBeforeTest, FillMissing, Categorify, Normalize])

# Fails
preprocess([TrainBeforeTest(cat_names=cat_names, cont_names=cont_names), FillMissing, Categorify, Normalize])
```

Stack trace:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "<stdin>", line 9, in preprocess
  File "/home/ac/projects/python/fastaigit/env/lib/python3.6/site-packages/fastai/data_block.py", line 483, in _inner
    self.process()
  File "/home/ac/projects/python/fastaigit/env/lib/python3.6/site-packages/fastai/data_block.py", line 537, in process
    for ds,n in zip(self.lists, ['train','valid','test']): ds.process(xp, yp, name=n)
  File "/home/ac/projects/python/fastaigit/env/lib/python3.6/site-packages/fastai/data_block.py", line 717, in process
    self.x.process(xp)
  File "/home/ac/projects/python/fastaigit/env/lib/python3.6/site-packages/fastai/data_block.py", line 84, in process
    for p in self.processor: p.process(self)
  File "/home/ac/projects/python/fastaigit/env/lib/python3.6/site-packages/fastai/tabular/data.py", line 62, in process
    if isinstance(proc, TabularProc): proc(ds.inner_df, test=True)
  File "/home/ac/projects/python/fastaigit/env/lib/python3.6/site-packages/fastai/tabular/transform.py", line 124, in __call__
    func(df)
  File "<stdin>", line 7, in apply_test
Exception: apply_test called before apply_train
```

I think the underlying reason is this line: https://github.com/fastai/fastai/blob/d1551ab3221812bd47e704fc4f5e59e2b6938216/fastai/tabular/data.py#L62

If `proc` has already been initialised via its constructor, `isinstance(proc, TabularProc)` will be `True` and so `proc()` will always be called with `test=True`.

**Suggested fix**

Add a property `trained:bool` to `TabularProc`. Then that could be used in `TabularPreprocessor.process()`,  instead of using `isinstance(proc, TabularProc)` as the condition.

**Side note: `cat_names` and `cont_names`**

From these lines it looks like perhaps it is intended that `cat_names` and `cont_names` should always be set internally: https://github.com/fastai/fastai/blob/d1551ab3221812bd47e704fc4f5e59e2b6938216/fastai/tabular/data.py#L64-L65 But these are the first two arguments to the constructors of `FillMissing`, `Categorify` etc.

Options I can think of:

1. Overwrite `cat_names` and `cont_names` in `TabularPreprocessor.process()` (in which case the user-provided arguments are ignored)
2. Remove them as constructor parameters (API change)

Thank you!

**Comment by sgugger** [comment]
The categorical and continuous names change during preprocessing so the processors need to be instantiated one after the other when you group them in a `TabularPreprocessor` (unless you are using preprocessors that have already been setup on a separate dataset). 
This is not a bug but what enable the whole pipeline to work (`FillMissing` will add new categorical variables that are then passed to `Categorize`)

The cat_names and cont_names should be passed to your preprocess function. As for `FillMissing`, using it with another strategy is just a matter of using `partial`: `partial(FillMissing, fill_strategy=FillStrategy.CONSTANT)`.

**Comment by andycraig** [comment]
Aha! I was thinking that the `cat_names` and `cont_names` passed by the user to the constructor would be overwritten, but I see now that the user should never call the constructor. Everything works when the user creates a partial function instead. I understand the design now.

I'll post replies to the forum posts, suggesting the partial function approach.

Thank you!
