### ISSUE TITLE
test_vision_data broken on PyTorch 1.5+

### ISSUE THREAD

**Issue by gchanan** [fastai/fastai#2547]
**Describe the bug**

The following invocation (among others) fails if I install PyTorch 1.5+:
```
pytest tests/test_vision_data.py -k test_camvid
E               Exception: It's not possible to apply those transforms to your dataset:
E                Expected object of scalar type Float but got scalar type Double for argument #3 'mat2' in call to _th_addmm_out
```

**Provide your installation details**

```text
=== Software ===
python        : 3.7.4
fastai        : 1.0.61.dev0
fastprogress  : 0.2.3
torch         : 1.5.0a0+c164fbc
nvidia driver : 396.69
torch cuda    : None / is **Not available**

=== Hardware ===
nvidia gpus   : 2
Have 2 GPU(s), but torch can't use them (check nvidia driver)

=== Environment ===
platform      : Linux-4.16.18-210_fbk23_5358_gf2838c074351-x86_64-with-centos-7.6.1810-Core
distro        : CentOS Linux 7 Core
conda env     : __py37g11
python        : /data/users/gchanan/anaconda3/envs/__py37g11/bin/python
sys.path      : /data/users/gchanan/fastai
/data/users/gchanan/anaconda3/envs/__py37g11/lib/python37.zip
/data/users/gchanan/anaconda3/envs/__py37g11/lib/python3.7
/data/users/gchanan/anaconda3/envs/__py37g11/lib/python3.7/lib-dynload
/data/users/gchanan/anaconda3/envs/__py37g11/lib/python3.7/site-packages
/data/users/gchanan/_pytorch11
/data/users/gchanan/anaconda3/envs/__py37g11/lib/python3.7/site-packages/future-0.18.2-py3.7.egg
/data/users/gchanan/fastai
/data/users/gchanan/anaconda3/envs/__py37g11/lib/python3.7/site-packages/IPython/extensions
```

**To Reproduce**

See above

**Expected behavior**

Tests should pass

**Screenshots**

**Additional context**

The issue appears to be caused by this: https://github.com/pytorch/pytorch/pull/30486
Basically, this changed how the dtype inference worked for the `torch.tensor` constructor wrt NumPy scalars (like `np.float_`).  Previously, inference treated these as (basically) `float32` and now it matches the "dtype" of the NumPy scalar.  The previous behavior was definitely wrong for integral types, and it also changed how floating-point types are inferred, because `np.float_` would previously have been inferred as `float32` and now it is being inferred as `float64`.  This eventually causes the error in the test: the tensor type is created a `float64` tensor and is `matmul`-ed against a `float32` tensor, and `matmul` doesn't support type promotion.

I checked and adding:
```
if res.dtype == torch.float64:
        res = res.to(torch.torch.float32)
```
below https://github.com/fastai/fastai/blob/98b0ebb404aca768817675565933c72e2ca5ff1f/fastai/torch_core.py#L81 fixes the test.  There are probably better ways of solving though, like ensuring you are using `np.float32` instead of `np.float_`.

**Comment by sgugger** [comment]
In general, fastai v1 is not going to be compatible with latest PyTorch releases (v2 will). We're happy to take PRs that fixes issues without breaking backward compatibility but we're not proactively testing fastai v1 against the nightlies.

**Comment by lewtun** [comment]
I also ran into this problem today. Would it be possible to simply fix the `torch` and `torchvision` versions in the fastai requirements?

**Comment by sgugger** [comment]
Fixed the issue with the tests. In general it looks like some extra float will be required.

**Comment by hamedonline** [comment]
Looks like this fix is not enough, or maybe I'm missing something?
The previous issue was fixed but in addition I get this red flagged warnings right after following lines.
![image](https://user-images.githubusercontent.com/24595790/80085591-aa1a4800-856d-11ea-80fc-2db1fd9b8889.png)
![image](https://user-images.githubusercontent.com/24595790/80085653-c61de980-856d-11ea-896e-4b23a7b047c5.png)

**Comment by sgugger** [comment]
Yeah, there are a bunch of warnings. I fixed them in v2, will look at this when I have time (if anyone wants to tackle it before, I welcome any PR :) )

**Comment by amrrs** [comment]
I got the same error as @gchanan when I tried the first notebook of `fastai` course, is it related to this or something else? I'm sorry to reply back on a closed issue, but didn't want to open a new one unncessarily!

**Comment by amrrs** [comment]
@hamedonline Thanks for the link, I got over it by downgrading my Pytorch on Colab

`!pip install -q torch==1.4 torchvision==0.5.0`

**Comment by sgugger** [comment]
There will be a new release soon, that should fix the problem on colab once it's out there.

**Comment by amrrs** [comment]
Thanks @sgugger !

**Comment by sgugger** [comment]
Release has been made, now you just need to wait for it to make its way up to colab.
