### ISSUE TITLE
How do we get support for this library?

### ISSUE THREAD

**Issue by tchaffee** [fastai/fastai#2549]
No one is responding to my questions on the forum even after waiting days and I don't see any other options for getting support. I didn't want to open an issue, but I don't see how I can consider using this library in a professional setting if I cannot get support. The library seems very promising and I think the courses are excellent. But I would really like to consider using it beyond the courses.

**Comment by sgugger** [comment]
You should make sure to post in an appropriate thread (like [fastai users](https://forums.fast.ai/c/fastai-users)) and make sure to post all information to reproduce your problem. Opening an issue won't really help unless it's to fix a bug in the library.
