### ISSUE TITLE
n_classes not defined error in fastai.metrics file

### ISSUE THREAD

**Issue by Yue1Harriet1Huang** [fastai/fastai#2550]
**Describe the bug**

**Provide your installation details**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

line 158 in fastai.metrics file, n_classes is used without pre-defining, hence generating not defined error , unless it meant self.n_classes just like how it is being used anywhere else in the same file.

**Comment by sgugger** [comment]
Thanks for flagging this! Note that you can directly open a PR when you have a fix for your problem.
