### ISSUE TITLE
emb_szs

### ISSUE THREAD

**Issue by MorPeled** [fastai/fastai#2559]
https://github.com/fastai/fastai/blob/564896d7b84b59bee40db19ee298a1028235442b/fastai/tabular/models.py#L8

Hi,

On [documentation ](https://docs.fast.ai/tabular.learner.html) it said that emb_szs is a dictionary of string & int - if I got it right the string is the categorical variable name. I see here that it's not a dict but something else?

Thanks!

**Comment by sgugger** [comment]
You are comparing the documentation of `tabular_learner` with the init of the model. In the middle, there was a call to a function that changed those embedding sizes in [here](https://github.com/fastai/fastai/blob/564896d7b84b59bee40db19ee298a1028235442b/fastai/tabular/learner.py#L15).

As said in #2559, please use the [forum](https://forums.fast.ai/) for question around the code.
