### ISSUE TITLE
ds_type does not apply for TextClassificationInterpretation.from_learner

### ISSUE THREAD

**Issue by kdmcdrm** [fastai/fastai#2560]
It looks to me like it is not possible to set the ds_type when using TextClassificationInterpretation.from_learner. The issue is that the constructor fills arguments with the output of the learner object, which causes the default argument to get used for ds_type.

Here's the relevant snippet in fastai.text.interpret.py
``` python
class TextClassificationInterpretation(ClassificationInterpretation):
    """Provides an interpretation of classification based on input sensitivity.
    This was designed for AWD-LSTM only for the moment, because Transformer already has its own attentional model.
    """

    def __init__(self, learn: Learner, preds: Tensor, y_true: Tensor, losses: Tensor, ds_type: DatasetType = DatasetType.Valid):
        super().__init__(learn,preds,y_true,losses,ds_type)
        self.model = learn.model

    @classmethod
    def from_learner(cls, learn: Learner,  ds_type:DatasetType=DatasetType.Valid, activ:nn.Module=None):
        "Gets preds, y_true, losses to construct base class from a learner"
        return cls(learn, *learn.get_preds(ds_type=ds_type, activ=activ, with_loss=True, ordered=True))
```

You can reproduce by doing
```python
interp = TextClassificationInterpretation.from_learner(learn, ds_type=DatasetType.Test)
print(interp.ds_type)
```
where you'll find it's DatasetType.Valid.

This was very confusing for me as my validation and test sets are the same size so it would provide the losses associated with the incorrect text!

I am seeing this with version 1.0.60, but I took a look at the code in master and it doesn't appear to have been fixed.

**Comment by sgugger** [comment]
Thanks for flagging, it should be fixed now.
