### ISSUE TITLE
Issue in running the Roberta Model using FastAI

### ISSUE THREAD

**Issue by shravankoninti** [fastai/fastai#2561]
Hi All,

I am running a Roberta Model for predicting the sentence classification task. I am using Fastai implementation of it. I get a similar error as mentioned below. Please help me resolve this.

![fast_er_1](https://user-images.githubusercontent.com/6191291/81207069-a1545800-8fea-11ea-81e2-cdb572b324a7.JPG)

**Comment by sgugger** [comment]
Please use the [forum](https://forums.fast.ai/) to debug your code, we keep the issues for bugs in the library only.
