### ISSUE TITLE
dropout for continues variables

### ISSUE THREAD

**Issue by MorPeled** [fastai/fastai#2564]
https://github.com/fastai/fastai/blob/564896d7b84b59bee40db19ee298a1028235442b/fastai/tabular/models.py#L21

Hi,

If I got it right from this line, in the input layer there is no option to perform dropout on continues variables, right? (since the first droppout rate in the 'ps' list will always be 0.0)

Thanks!

**Comment by sgugger** [comment]
This is after the variables have been joined. The first 0 is because it hasn't been in any linear layer at this stage.

In general, please use the [forum](https://forums.fast.ai/) for questions around the code as we keep the issues for bugs only.
