### ISSUE TITLE
from_similars() always shows the "Computing similarities..." phase

### ISSUE THREAD

**Issue by Huud** [fastai/fastai#2571]
This is a minor oversight - I assume -, but running "from_similars()" from the image_cleaner widget always shows "Computing similarities..." even after the computation is done and returned, I spent an hour like an idiot waiting for this surprisingly long "Computing similarities..." part to end, just to realize it already did ages ago.

I though I missed something, but apparently this is how the function behaves since it is present even the example notebook:

https://github.com/fastai/fastai/blob/f2163fb547d3d68b5a609d39806245d121dc2d4e/docs_src/widgets.image_cleaner.ipynb

**Comment by sgugger** [comment]
I'm not sure what the issue is. The function tells you what it's doing, and when it's done... well your ntoebook is not executing anything so you know it?

**Comment by Huud** [comment]
When the last message being displayed is "Computing similarities..." indicating something is in the middle of being done, then the cell suddenly stops executing with nothing that confirms it ended successfully gives the impression for new users that something went wrong instead.

A good example done right is the message right before it, the "Getting activations..." has a progress bar that reaches 100% indicating it is done, a similar bar or even a simple "done." message could avoid needless first time confusion.

As I said, it's a minor issue with - I assume - a simple fix, if no one thinks it's worth fixing, then go ahead and close this issue.

**Comment by sgugger** [comment]
It's just I don't understand how you want to fix this.

**Comment by Huud** [comment]
As I said, a progress bar if possible, or simply printing "done." when it's done.

**Comment by sgugger** [comment]
I've just removed the print statement entirely since it's done on the whole tensor so it should be fast and there is no way to add a progress bar.
