### ISSUE TITLE
SentencePieceTrainer OSError: Not found

### ISSUE THREAD

**Issue by verissimomanoel** [fastai/fastai#2572]
When we try training a language model using MultFiT, the first phase is to load the unsup data with the code below:

data = (TextList.from_folder(dest, processor=[OpenFileProcessor(), SPProcessor(max_vocab_sz=15000)])
        .split_by_rand_pct(0.1, seed=42)
        .label_for_lm()
        .databunch(bs=bs, num_workers=8))

But we have the error OSError: Not found.

**Comment by sgugger** [comment]
This is way too vague for us to do anything to help. What is your environment? Where does `dest` point to?
In general, please follow the template to file an issue otherwise we won't really be able to help.

**Comment by andresti** [comment]
Hi, I was having the same issue (fastai v. 1.0.61).

The error is:
`~/miniconda3/envs/training/lib/python3.7/site-packages/fastai/text/data.py in train_sentencepiece(texts, path, pre_rules, post_rules, vocab_sz, max_vocab_sz, model_type, max_sentence_len, lang, char_coverage, tmp_dir, enc)
    435         f"--unk_id={len(defaults.text_spec_tok)} --pad_id=-1 --bos_id=-1 --eos_id=-1",
    436         f"--user_defined_symbols={','.join(spec_tokens)}",
--> 437         f"--model_prefix={quotemark}{cache_dir/'spm'}{quotemark} --vocab_size={vocab_sz} --model_type={model_type}"]))
    438     raw_text_path.unlink()
    439     return cache_dir

OSError: Not found: ""/[path]/docs/tmp/all_text.out"": No such file or directory Error #2
`

But actually the all_text.out file exists at the path and the contents seem fine. I managed to fix the problem by changing `quotemark = '\"'` to `quotemark = ''` in fastai/text/data.py

**Comment by nandakumar212** [comment]
I agree with @andresti , please refer to this [discussion](https://forums.fast.ai/t/multifit-runtime-error-permission-denied/72874). The {quotemark} around model_prefix need to be removed.

**Comment by lvwerra** [comment]
I had the same issue just now. I am happy to create a PR if there no side effects of removing the quotemark. Alternatively, one could add is an option to the SPProcessor. As far as I can see this was introduced by #2507 .

**Comment by jph00** [comment]
Thanks for the detective work! I'll revert that PR.
