### ISSUE TITLE
setup.py  deps generates invalid spec

### ISSUE THREAD

**Issue by itsallonetome** [fastai/fastai#2576]
**Describe the bug**

`$ python setup.py -q deps --dep-groups=core,text`
in a linux x86-64 minirconda environment with python 3.7 generates invalid spec:
`Pillow beautifulsoup4 bottleneck dataclasses;python_version<'3.7' fastprogress>=0.2.1 matplotlib numexpr numpy>=1.15 nvidia-ml-py3 packaging pandas pynvx>=1.0.0;platform_system=="Darwin" pyyaml requests scipy spacy>=2.0.18;python_version<'3.8' torch>=1.0.0`

**Provide your installation details**

$ python -m fastai.utils.show_install

```text
=== Software ===
python       : 3.7.6
fastai       : 1.0.62.dev0
fastprogress : 0.2.2
torch        : 1.1.0
torch cuda   : None / is **Not available**

=== Hardware ===
No GPUs available

=== Environment ===
platform     : Linux-3.10.0-1127.el7.x86_64-x86_64-with-redhat-7.6-Maipo
distro       : Red Hat Enterprise Linux Server 7.6 Maipo
conda env    : fastai
python       : /home/conda/miniconda3/envs/fastai/bin/python
sys.path     : /home/conda/fastai
/home/conda/miniconda3/envs/fastai/lib/python37.zip
/home/conda/miniconda3/envs/fastai/lib/python3.7
/home/conda/miniconda3/envs/fastai/lib/python3.7/lib-dynload
/home/conda/.local/lib/python3.7/site-packages
/home/conda/miniconda3/envs/fastai/lib/python3.7/site-packages
no supported gpus found on this system
```
$ `uname -a`
`Linux vm012370 3.10.0-1127.el7.x86_64 #1 SMP Tue Feb 18 16:39:12 EST 2020 x86_64 x86_64 x86_64 GNU/Linux`

**To Reproduce**

create conda env with python 3.7
$ `conda config --env --add channels conda-forge`
$ `conda config --env --add channels fastai`
$ `conda config --env --add channels pytorch`

then
$ `conda install scikit-learn pandas numpy scipy mkl`
$ `conda install pytorch-cpu torchvision-cpu cpuonly mkl`

then
```
git clone https://github.com/fastai/fastai
cd fastai/
tools/run-after-git-clone
```
then
$ `python setup.py -q deps --dep-groups=core,text`

**Expected behavior**

The generated dependencies will include only package specs which are compatible with the environment.
`dataclasses;python_version<'3.7'` is not compatible with python 3.7.6
`pynvx>=1.0.0;platform_system=="Darwin"` is not compatible with x86_64

**Screenshots**

**Additional context**

**Comment by jph00** [comment]
We're not likely to fix this, since v2 has a different packaging system, sorry.
