### ISSUE TITLE
Prediction Mismatch for RnnLearner

### ISSUE THREAD

**Issue by kdmcdrm** [fastai/fastai#2578]
Excuse me if this is known behaviour, I took a look on the forum and couldn't find any reason that this should be the case. What I noticed is that the predictions between two learner objects, after loading the same weights, differ.

Here's the example:
``` python
learn1 = text_classifier_learner(
    data_clas,
    AWD_LSTM,
    drop_mult=0.5
)
learn1.model_dir = MODEL_DIR
learn1.load_encoder("lm_encoder")
learn1 = learn1.load(TEST_MODEL_PREFIX + "_fine2")
learn1.predict("Some short test text", with_dropout=False)

learn2 = text_classifier_learner(
    data_clas,
    AWD_LSTM,
    drop_mult=0.5
)
learn2.model_dir = MODEL_DIR
learn2.load_encoder("lm_encoder")
learn2 = learn2.load(TEST_MODEL_PREFIX + "_fine2")
learn2.predict("Some short test text", with_dropout=False)
```
And the output shows that they predict the same class, but not with quite the same probabilities.

> (Category return_quick_reply,
>  tensor(2),
>  tensor([0.2519, 0.2333, 0.3683, 0.1464]))
 
> (Category return_quick_reply,
> tensor(2),
> tensor([0.2386, 0.2403, 0.3632, 0.1579]))

Is this expected for some reason? I do get consistent results for learners loaded after exporting, so I can use that for the live model.

**Comment by sgugger** [comment]
What's your fastai version? There was a bug with `WeightDropout` that could be causing this but it has been fixed.

**Comment by kdmcdrm** [comment]
@sgugger It's 1.0.60.

**Comment by sgugger** [comment]
Yes, you should upgrade to 1.0.61 then. Please reopen if that doesn't fix your issue.
