### ISSUE TITLE
'NoneType' object is not subscriptable in interp.GradCAM(idx)

### ISSUE THREAD

**Issue by Alymostafa** [fastai/fastai#2581]
I use ```vgg19``` from ```torchvision```  when i use gradcam it gives me that :
```
learn = cnn_learner(data, models.vgg19, metrics=[accuracy,error_rate])
interp = ClassificationInterpretation.from_learner(learn)
interp.GradCAM(1)
```
```
/usr/local/lib/python3.6/dist-packages/fastai/vision/learner.py in _cl_int_gradcam(self, idx, ds_type, heatmap_thresh, image)
    155 
    156     if (acts.shape[-1]*acts.shape[-2]) >= heatmap_thresh:
--> 157         grad = hook_g.stored[0][0].cpu()
    158         grad_chan = grad.mean(1).mean(1)
    159         mult = F.relu(((acts*grad_chan[...,None,None])).sum(0))

TypeError: 'NoneType' object is not subscriptable
```

**Comment by xylophone21** [comment]
I met the same issue:
CUDA Version: 10.1
torch  1.3.0
fastai 1.0.59

**Comment by Alymostafa** [comment]
I think the problem that vgg19 isn't included in fastai library, but it should work for all architectures

**Comment by xylophone21** [comment]
> I think the problem that vgg19 isn't included in fastai library, but GradCam should work for all architectures

I used models.squeezenet1_0, same issue

learn = cnn_learner(data, models.squeezenet1_0, metrics=accuracy)
interp = ClassificationInterpretation.from_learner(learn)
interp.plot_top_losses(4, figsize=(8,8),heatmap=True)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-ea4627e4eb6b> in <module>
      1 losses,idxs = interp.top_losses()
----> 2 interp.plot_top_losses(4, figsize=(8,8),heatmap=True)

/media/storage_0x00/ENV/miniconda3/envs/fastai/lib/python3.6/site-packages/fastai/vision/learner.py in _cl_int_plot_top_losses(self, k, largest, figsize, heatmap, heatmap_thresh, alpha, cmap, show_text, return_fig)
    179         im.show(ax=axes.flat[i], title=title)
    180         if heatmap:
--> 181             mult = self.GradCAM(idx,self.ds_type,heatmap_thresh,image=False)
    182             if mult is not None:
    183                 sz = list(im.shape[-2:])

/media/storage_0x00/ENV/miniconda3/envs/fastai/lib/python3.6/site-packages/fastai/vision/learner.py in _cl_int_gradcam(self, idx, ds_type, heatmap_thresh, image)
    147     acts  = hook_a.stored[0].cpu() #activation maps
    148     if (acts.shape[-1]*acts.shape[-2]) >= heatmap_thresh:
--> 149         grad = hook_g.stored[0][0].cpu()
    150         grad_chan = grad.mean(1).mean(1)
    151         mult = F.relu(((acts*grad_chan[...,None,None])).sum(0))

TypeError: 'NoneType' object is not subscriptable

**Comment by jph00** [comment]
GradCam in fastai v1 only works with some architectures, sorry.
