### ISSUE TITLE
ObjectItemList error when there is no bounding box in the first item

### ISSUE THREAD

**Issue by yindavidyang** [fastai/fastai#2582]
I was building a databunch for object detection:

-----
x= (ObjectItemList.from_folder(data_dir / 'train')
        .split_by_rand_pct()
        .label_from_func(get_y_func)
        .transform(tfms, tfm_y=True, size=sz)
     )
-----

My first item in the list has no bounding box or label, so it's `y` is simply `[[], []]`. This led to an error in `ImageBBox.create`:

-----
~/miniconda3/lib/python3.7/site-packages/fastai/data_block.py in _check_kwargs(ds, tfms, **kwargs)
    595     if (tfms is None or len(tfms) == 0) and len(kwargs) == 0: return
    596     if len(ds.items) >= 1:
--> 597         x = ds[0]
    598         try: x.apply_tfms(tfms, **kwargs)
    599         except Exception as e:

~/miniconda3/lib/python3.7/site-packages/fastai/data_block.py in __getitem__(self, idxs)
    118         "returns a single item based if `idxs` is an integer or a new `ItemList` object if `idxs` is a range."
    119         idxs = try_int(idxs)
--> 120         if isinstance(idxs, Integral): return self.get(idxs)
    121         else: return self.new(self.items[idxs], inner_df=index_row(self.inner_df, idxs))
    122 

~/miniconda3/lib/python3.7/site-packages/fastai/vision/data.py in get(self, i)
    353 
    354     def get(self, i):
--> 355         return ImageBBox.create(*_get_size(self.x,i), *self.items[i], classes=self.classes, pad_idx=self.pad_idx)
    356 
    357     def analyze_pred(self, pred): return pred

~/miniconda3/lib/python3.7/site-packages/fastai/vision/image.py in create(cls, h, w, bboxes, labels, classes, pad_idx, scale)
    357         if isinstance(bboxes, np.ndarray) and bboxes.dtype == np.object: bboxes = np.array([bb for bb in bboxes])
    358         bboxes = tensor(bboxes).float()
--> 359         tr_corners = torch.cat([bboxes[:,0][:,None], bboxes[:,3][:,None]], 1)
    360         bl_corners = bboxes[:,1:3].flip(1)
    361         bboxes = torch.cat([bboxes[:,:2], tr_corners, bl_corners, bboxes[:,2:]], 1)

IndexError: too many indices for tensor of dimension 0
------

The error was caused because `bboxes` here is an empty list `[]`, and the above code is trying to access `bboxes[:, 0]`.

**Comment by jph00** [comment]
Please use the forums for help.
