### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by nickcorona** [fastai/fastai#2584]
https://github.com/fastai/fastai/blob/54a9e3cf4fd0fa11fc2453a5389cc9263f6f0d77/fastai/tabular/data.py#L85

I run this code on bluebook data from the fastai course. However, it doesn't work in filling in applying the processors. I get this error. Any idea why?
```
procs = [FillMissing, Categorify]
data = TabularDataBunch.from_df('data', df, 'SalePrice', valid_idx=valid_idx, procs=procs, cat_names=cat_list)`
```

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by jph00** [comment]
Please use the forums for help.
