### ISSUE TITLE
Tokenizer is applied to labels instead of text for multifit  classifier

### ISSUE THREAD

**Issue by suryapa1** [fastai/fastai#2593]
<img width="1013" alt="Screenshot 2020-06-15 at 11 02 29 PM" src="https://user-images.githubusercontent.com/6042186/84688489-0c376e00-af5d-11ea-885c-fa99e760db90.png">

1) How to put text to be tokenized in abve screesnshot?
2)Any specifc structure is expected for multifit , though am maintaining train.csv/test.csv under data/sentimental/ folder path as per above screenshot.
3) Though i have shuffled train.csv( label & text ), why it is not applied in run time, is there any cache needs to be handled here ??

**Comment by suryapa1** [comment]
"data/de_sentiment/  folder path"

**Comment by jph00** [comment]
Please use the forums for help.
