### ISSUE TITLE
Error importing fastai.vision

### ISSUE THREAD

**Issue by rtapan25** [fastai/fastai#2597]
I have been trying to import fastai.vision but am greeted by the following error:
ImportError: cannot import name 'master_bar' from 'fastprogress'

Traceback:
ImportError                               Traceback (most recent call last)
<ipython-input-14-63b1e6c600e9> in <module>
      2 import numpy as np
      3 from fastprogress.fastprogress import master_bar, progress_bar
----> 4 from fastai.vision import *
      5 import matplotlib.pyplot as plt
      6 pd.set_option('display.max_columns', 500)

~\AppData\Local\Continuum\anaconda3\envs\torc\lib\site-packages\fastai\__init__.py in <module>
----> 1 from .basic_train import *
      2 from .callback import *
      3 #from .callbacks import *
      4 from .core import *
      5 from .basic_data import *

~\AppData\Local\Continuum\anaconda3\envs\torc\lib\site-packages\fastai\basic_train.py in <module>
      1 "Provides basic training and validation with `Learner`"
----> 2 from .torch_core import *
      3 from .basic_data import *
      4 from .callback import *
      5 

~\AppData\Local\Continuum\anaconda3\envs\torc\lib\site-packages\fastai\torch_core.py in <module>
      1 "Utility functions to help deal with tensors"
----> 2 from .imports.torch import *
      3 from .core import *
      4 
      5 AffineMatrix = Tensor

~\AppData\Local\Continuum\anaconda3\envs\torc\lib\site-packages\fastai\imports\__init__.py in <module>
----> 1 from .core import *
      2 from .torch import *

~\AppData\Local\Continuum\anaconda3\envs\torc\lib\site-packages\fastai\imports\core.py in <module>
     13 from dataclasses import dataclass, field
     14 from enum import Enum, IntEnum
---> 15 from fastprogress import master_bar, progress_bar
     16 from functools import partial, reduce, singledispatch
     17 from pdb import set_trace

ImportError: cannot import name 'master_bar' from 'fastprogress' (~AppData\Local\Continuum\anaconda3\envs\torc\lib\site-packages\fastprogress\__init__.py)

**Comment by brianrice2** [comment]
Do you have the most recent version of fastai? See [fastprogress #58](https://github.com/fastai/fastprogress/issues/58).

**Comment by jph00** [comment]
Please use the forums for help.
