### ISSUE TITLE
apply_tfms(resize_method=ResizeMethod.PAD) does not add padding

### ISSUE THREAD

**Issue by micimize** [fastai/fastai#2603]
It does not appear to be possible to pad images with `apply_tfms` (and thus `.transform`). Here is a minimum reproduction:
```python
from fastai.vision import *

path = untar_data(URLs.MNIST)
il = ImageList.from_folder(path, convert_mode='L')
defaults.cmap='binary'
ll = il.split_by_folder(train='training', valid='testing').label_from_folder()
x = ll.train[0][0]

x.show() # x.shape is 1x28x28

crop_pad(x.clone(), padding_mode='zeros', size=int(16 * 28)).show() # pads correctly

x.clone().apply_tfms(
    [crop_pad(padding_mode='zeros')],
    size=int(16 * 28), 
    resize_method=ResizeMethod.PAD,
    padding_mode='zeros'
).show() # resizes without padding
```

which yields: 
![image](https://user-images.githubusercontent.com/8343799/86155003-6d1c8580-bac9-11ea-908d-61c328175122.png)

This is because before applying any transforms, `x.resize(target)` is called, which scales the image up:
https://github.com/fastai/fastai/blob/8be0c6f707808c23374c478313e7aed645871a05/fastai/vision/image.py#L110-L114

Commenting out the resize in an extracted version yields expected results

**Comment by jph00** [comment]
Please use the forums for help.

**Comment by micimize** [comment]
@jph00 this is a bug report. `apply_tfms` scales images before padding them, so `resize_method=ResizeMethod.PAD` doesn't do anything. 

I'm fairly sure all that needs to be done is:
```diff
 if size is not None: 
     crop_target = _get_crop_target(size, mult=mult) 
-     if resize_method in (ResizeMethod.CROP,ResizeMethod.PAD): 
+     if resize_method in (ResizeMethod.CROP,): 
         target = _get_resize_target(x, crop_target, do_crop=(resize_method==ResizeMethod.CROP)) 
         x.resize(target) 
```
