### ISSUE TITLE
Fastai load runner taking CPU utilization high

### ISSUE THREAD

**Issue by nbhupendra** [fastai/fastai#2614]
Hi, I am the new user for fastai. I have trained model on GPU and now planning to deploy on CPU/VM. However on CPU, utilization go up to 350% every predict request i make. And if i open multiple process using gunicorn its just unmanageable. Kindly help.

pred_class, pred_idx, outputs = fastai_learner.predict(img_fastai). --- 3.5 Sec and 350% CPU on every request.

Am i doing anything wrong?

Train on GPU-
learner= cnn_learner(data, models.resnet101, metrics=[accuracy, error_rate])
learner.fit_one_cycle(30)
learner.save('save_model')
learner.export('export.pkl')

CPU-
learner = load_learner(model_fastai_path,model_fastai)
pred_class, pred_idx, outputs = fastai_learner.predict(img_fastai) - 3.5 Sec and 350% CPU on every request.

**Comment by jph00** [comment]
We are not able to provide support here, sorry.
