### ISSUE TITLE
TabularPandas (fastai v2) not setting self.loss_func for Regression

### ISSUE THREAD

**Issue by Dmayblom** [fastai/fastai#2615]
First time here so doing my best. Tried to simplify it as much as possible.

OS : Windows 10 show_install() didn't work

TabularPandas will set self.loss_func for a category y_name but not for regression. I tracked it down to Pipeline() at line 124 in core.py, then I got lost. Work around was to set it in the learner and everything worked.

'''
/fastai2/tabular/core.py 

line 124

#       self.cat_names,self.cont_names,self.procs = L(cat_names),L(cont_names),Pipeline(procs)
# expanded line to

        self.cat_names = L(cat_names) 
        self.cont_names = L(cont_names)
        
        print('y_block : ', y_block)
        print('procs : ', procs)

        print('loss_func BEFORE PIPELINE()',hasattr( self, 'loss_func'))
        
        self.procs = Pipeline(procs)
        
        print('loss_func AFTER_PIPELINE()',hasattr( self, 'loss_func'))

'''
#IN

CATEGORY_FIELD = ai.dep_vars[0]
REGRESSION_FIELD = ai.dep_vars[1]
print('CATEGORY')
TabularPandas(test_df, y_names=CATEGORY_FIELD, cat_names=ai.cat_names(), cont_names=ai.cont_names(),procs=[Categorify, FillMissing, Normalize])

print('\nREGRESSION')
TabularPandas(test_df, y_names=REGRESSION_FIELD, cat_names=ai.cat_names(), cont_names=ai.cont_names(),procs=[Categorify, FillMissing, Normalize])

print('\nFINISHED')

#OUT

CATEGORY
y_block :  <fastai2.data.block.TransformBlock object at 0x000001FE02A92DC8>
procs :  (#4) [<class 'fastai2.tabular.core.Categorify'>,<class 'fastai2.tabular.core.FillMissing'>,<class 'fastai2.data.transforms.Normalize'>,Categorize: (Tabular,object) -> encodes
(object,object) -> encodes (Tabular,object) -> decodes
(object,object) -> decodes]
loss_func BEFORE PIPELINE() False
loss_func AFTER_PIPELINE() True

REGRESSION
y_block :  <fastai2.data.block.TransformBlock object at 0x000001FE02A00C88>
procs :  (#4) [<class 'fastai2.tabular.core.Categorify'>,<class 'fastai2.tabular.core.FillMissing'>,<class 'fastai2.data.transforms.Normalize'>,RegressionSetup: (Tabular,object) -> encodes
(object,object) -> encodes (Tabular,object) -> decodes
(object,object) -> decodes]
loss_func BEFORE PIPELINE() False
loss_func AFTER_PIPELINE() False

FINISHED

**Comment by tcapelle** [comment]
this fastai V1 git, ideally post this on the forums.
