### ISSUE TITLE
export() pickle filetype changed

### ISSUE THREAD

**Issue by delbarital** [fastai/fastai#2618]
Yesterday I tried to export a new version of my model and load it to production, but the load function failed.
I noticed that the file icon on Google drive is different, but I couldn't understand what is going on. After reading the [release notes of Pytorch 1.6](https://github.com/pytorch/pytorch/releases) I realized that they changed the behavior of the torch.save() function. The pickle object is now saved in a new format. Basically they changed the pickle format to a zip file-based format.

There is an optional flag that you can pass to save it using the old format,  _use_new_zipfile_serialization=False, but fastai doesn't support it.
To overcome this problem I copied the relevant functions from the fastai library, export() and try_save() to my code and edited them to include this flag, but I'm pretty sure there is a better way to solve this.

I guess this will be solved on fastai2, but I think this is an important enough issue to solve it for this version as well.

    def export_fix(self, file:PathLikeOrBinaryStream='export.pkl', destroy=False):
        "Export the state of the `Learner` in `self.path/file`. `file` can be file-like (file or buffer)"
        if rank_distrib(): return # don't save if slave proc
        args = ['opt_func', 'loss_func', 'metrics', 'true_wd', 'bn_wd', 'wd', 'train_bn', 'model_dir', 'callback_fns']
        state = {a:getattr(self,a) for a in args}
        state['cb_state'] = {cb.__class__:cb.get_state() for cb in self.callbacks}
        #layer_groups -> need to find a way
        #TO SEE: do we save model structure and weights separately?
        with ModelOnCPU(self.model) as m:
            state['model'] = m
            xtra = dict(normalize=self.data.norm.keywords) if getattr(self.data, 'norm', False) else {}
            state['data'] = self.data.valid_ds.get_state(**xtra)
            state['cls'] = self.__class__
            try_save_fix(state, self.path, file)
        if destroy: self.destroy()

    def try_save_fix(state:Dict, path:Path=None, file:PathLikeOrBinaryStream=None):
        target = open(path/file, 'wb') if is_pathlike(file) else file
        try: 
            with warnings.catch_warnings():
                #To avoid the warning that come from PyTorch about model not being checked
                warnings.simplefilter("ignore")
                torch.save(state, target,  _use_new_zipfile_serialization=False)
        except OSError as e:
            raise Exception(f"{e}\n Can't write {path/file}. Pass an absolute writable pathlib obj `fname`.")

**Comment by jph00** [comment]
Thanks for letting us know. I've added that flag to fastai v1 in master. Please try it out and see if that works for you. For v2, we'll be releasing with pytorch 1.6 requirement from the start, so we won't add this flag. We could add a little conversion function however if people needed that.
