### ISSUE TITLE
BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

### ISSUE THREAD

**Issue by jameswangcnbj** [fastai/fastai#2621]
=== Software ===
python       : 3.8.4
fastai       : 1.0.61
fastprogress : 0.2.5
torch        : 1.5.1
torch cuda   : None / is **Not available**

=== Hardware ===
No GPUs available

=== Environment ===
platform     : macOS-10.13.6-x86_64-i386-64bit
conda env    : torch
python       : /Users/edz/Documents/anaconda/anaconda3/envs/torch/bin/python
sys.path     :
/Users/edz/Documents/anaconda/anaconda3/envs/torch/lib/python38.zip
/Users/edz/Documents/anaconda/anaconda3/envs/torch/lib/python3.8
/Users/edz/Documents/anaconda/anaconda3/envs/torch/lib/python3.8/lib-dynload
/Users/edz/Documents/anaconda/anaconda3/envs/torch/lib/python3.8/site-packages

when i run databunch = TextClasDataBunch.from_df(path, train, valid, test,
                                      tokenizer=bert_fastai_tokenizer,
                                      vocab=bert_vocab,
                                      include_bos=False,
                                      include_eos=False,
                                      text_cols="comment",
                                      label_cols='sentiment',
                                      bs=batch_size,
                                      collate_fn=partial(pad_collate, pad_first=False, pad_idx=0),
                                     )
then the error is blow:

 0.00% [0/1 00:00<00:00]
---------------------------------------------------------------------------
BrokenProcessPool                         Traceback (most recent call last)
<ipython-input-60-e12047de4d6b> in <module>
----> 1 databunch = TextClasDataBunch.from_df(path, train, valid, test,
      2                                       tokenizer=bert_fastai_tokenizer,
      3                                       vocab=bert_vocab,
      4                                       include_bos=False,
      5                                       include_eos=False,

~/Documents/anaconda/anaconda3/envs/torch/lib/python3.8/site-packages/fastai/text/data.py in from_df(cls, path, train_df, valid_df, test_df, tokenizer, vocab, classes, text_cols, label_cols, label_delim, chunksize, max_vocab, min_freq, mark_fields, include_bos, include_eos, **kwargs)
    203         else:
    204             if label_delim is not None: src = src.label_from_df(cols=label_cols, classes=classes, label_delim=label_delim)
--> 205             else: src = src.label_from_df(cols=label_cols, classes=classes)
    206         if test_df is not None: src.add_test(TextList.from_df(test_df, path, cols=text_cols))
    207         return src.databunch(**kwargs)

~/Documents/anaconda/anaconda3/envs/torch/lib/python3.8/site-packages/fastai/data_block.py in _inner(*args, **kwargs)
    482             self.valid = fv(*args, from_item_lists=True, **kwargs)
    483             self.__class__ = LabelLists
--> 484             self.process()
    485             return self
    486         return _inner

~/Documents/anaconda/anaconda3/envs/torch/lib/python3.8/site-packages/fastai/data_block.py in process(self)
    536         "Process the inner datasets."
    537         xp,yp = self.get_processors()
--> 538         for ds,n in zip(self.lists, ['train','valid','test']): ds.process(xp, yp, name=n)
    539         #progress_bar clear the outputs so in some case warnings issued during processing disappear.
    540         for ds in self.lists:

~/Documents/anaconda/anaconda3/envs/torch/lib/python3.8/site-packages/fastai/data_block.py in process(self, xp, yp, name, max_warn_items)
    716                     p.warns = []
    717                 self.x,self.y = self.x[~filt],self.y[~filt]
--> 718         self.x.process(xp)
    719         return self
    720 

~/Documents/anaconda/anaconda3/envs/torch/lib/python3.8/site-packages/fastai/data_block.py in process(self, processor)
     82         if processor is not None: self.processor = processor
     83         self.processor = listify(self.processor)
---> 84         for p in self.processor: p.process(self)
     85         return self
     86 

~/Documents/anaconda/anaconda3/envs/torch/lib/python3.8/site-packages/fastai/text/data.py in process(self, ds)
    295         tokens = []
    296         for i in progress_bar(range(0,len(ds),self.chunksize), leave=False):
--> 297             tokens += self.tokenizer.process_all(ds.items[i:i+self.chunksize])
    298         ds.items = tokens
    299 

~/Documents/anaconda/anaconda3/envs/torch/lib/python3.8/site-packages/fastai/text/transform.py in process_all(self, texts)
    118         if self.n_cpus <= 1: return self._process_all_1(texts)
    119         with ProcessPoolExecutor(self.n_cpus) as e:
--> 120             return sum(e.map(self._process_all_1, partition_by_cores(texts, self.n_cpus)), [])
    121 
    122 class Vocab():

~/Documents/anaconda/anaconda3/envs/torch/lib/python3.8/concurrent/futures/process.py in _chain_from_iterable_of_lists(iterable)
    482     careful not to keep references to yielded objects.
    483     """
--> 484     for element in iterable:
    485         element.reverse()
    486         while element:

~/Documents/anaconda/anaconda3/envs/torch/lib/python3.8/concurrent/futures/_base.py in result_iterator()
    609                     # Careful not to keep a reference to the popped future
    610                     if timeout is None:
--> 611                         yield fs.pop().result()
    612                     else:
    613                         yield fs.pop().result(end_time - time.monotonic())

~/Documents/anaconda/anaconda3/envs/torch/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
    437                 raise CancelledError()
    438             elif self._state == FINISHED:
--> 439                 return self.__get_result()
    440             else:
    441                 raise TimeoutError()

~/Documents/anaconda/anaconda3/envs/torch/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
    386     def __get_result(self):
    387         if self._exception:
--> 388             raise self._exception
    389         else:
    390             return self._result

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

my all code is:
from fastai.text import *
import pandas as pd
df = pd.read_csv("Documents/pythonprj/torch_test/fastai/jupter/dianping.csv")
from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size=.2, random_state=2)
train, valid = train_test_split(train, test_size=.2, random_state=2)
from pytorch_transformers import BertTokenizer, BertForSequenceClassification
bert_model = "bert-base-chinese"
max_seq_len = 128
batch_size = 32
bert_tokenizer = BertTokenizer.from_pretrained(bert_model)
bert_vocab = Vocab(list(bert_tokenizer.vocab.keys()))
class BertFastaiTokenizer(BaseTokenizer):
    def __init__(self, tokenizer, max_seq_len=128, **kwargs):
        self.pretrained_tokenizer = tokenizer
        self.max_seq_len = max_seq_len

    def __call__(self, *args, **kwargs):
        return self

    def tokenizer(self, t):
        return ["[CLS]"] + self.pretrained_tokenizer.tokenize(t)[:self.max_seq_len - 2] + ["[SEP]"]
tok_func = BertFastaiTokenizer(bert_tokenizer, max_seq_len=max_seq_len)
bert_fastai_tokenizer = Tokenizer(
    tok_func=tok_func,
    pre_rules = [],
    post_rules = []
)
databunch = TextClasDataBunch.from_df(path, train, valid, test,
                                      tokenizer=bert_fastai_tokenizer,
                                      vocab=bert_vocab,
                                      include_bos=False,
                                      include_eos=False,
                                      text_cols="comment",
                                      label_cols='sentiment',
                                      bs=batch_size,
                                      collate_fn=partial(pad_collate, pad_first=False, pad_idx=0),
                                     )
when i run here,the error happen,my machine is mac on jupter notebook

**Comment by jph00** [comment]
We don't support Mac, sorry.
