### ISSUE TITLE
Expected object of scalar type Float but got scalar type Long when plotting confusion matrix

### ISSUE THREAD

**Issue by vladimirkovacevic** [fastai/fastai#2627]
When runing [data tutorial](https://github.com/fastai/fastai/blob/master/docs_src/tutorial.data.ipynb) for part with multilable classification of planet data after executing all the cells from this part I wanted to see the confussion matrix so I've added new cell:
`interp = ClassificationInterpretation.from_learner(learn)'
'interp.plot_confusion_matrix()`
which gave me an error:
Expected object of scalar type Float but got scalar type Long for argument #2 'other'

I've found the issue regarding it on [fastai Github](https://github.com/fastai/fastai/issues/1801) saying there it should be fixed in the latest version, but I have fastai-1.0.61 and still getting the error. Does someone know the reason for this and is there a workaround?

**Comment by jph00** [comment]
There isn't enough info here to replicate the problem.
