### ISSUE TITLE
Major bug regarding Augmentation and TensorPoint

### ISSUE THREAD

**Issue by muellerzr** [fastai/fastai#2628]
In fastai2 v 0.0.17, the following would work as expected:
```python
item_tfms = [Resize(448, method='squish')]
batch_tfms = [Flip(), Rotate(), Zoom(), Warp()]
```
Where the outputted transformed image would have every point on the screen:

![image](https://user-images.githubusercontent.com/7831895/90449211-f6f1d380-e0b4-11ea-8be6-df5e2160ec9e.png)

However in the latest version, this fails, showing points off the screen. See two examples in the below batch:

![image](https://user-images.githubusercontent.com/7831895/90449171-e93c4e00-e0b4-11ea-84e4-762ef186acca.png)

Was there a major change that happened between the two? Why this becomes a problem from stemming such a little change is post fitting you run into a clumping issue. *Originally* when I found this bug it was due to resize not having "squish" along with the dataset being unclean, however extensive pre-processing was done to clean it. The notebook is available here (note this was run on 0.0.17):

https://github.com/muellerzr/Practical-Deep-Learning-for-Coders-2.0/blob/master/Computer%20Vision/06_Keypoint_Regression.ipynb

Two examples, the first being expected (0.0.17), the latter being current, this is made extremely visible:

![image](https://user-images.githubusercontent.com/7831895/90449345-3c160580-e0b5-11ea-998f-e602e3289e82.png)

![image](https://user-images.githubusercontent.com/7831895/90449353-40422300-e0b5-11ea-953c-59a156a8cd7e.png)

I'll start looking into other possibilities if nothing is extremely obvious, but may take me a bit as I am back at work again.

**Comment by jph00** [comment]
Turns out it's not a bug, just a missing feature. Bounding boxes are clamped, but TensorPoints aren't. Will consider adding that feature later.
