### ISSUE TITLE
to_distributed() wrapped DataLoader ignores get_idxs() so WeightedDL behaves inconsistently in DDP mode

### ISSUE THREAD

**Issue by antorsae** [fastai/fastai#2637]
If your dataloader  has its own get_idxs eg.  `WeightedDL` it gets ignored when `to_distributed(...)`, so as a result same code that e.g. does minority oversampling (using `WeightedDL`) will silently NOT do it in DDP mode, b/c DDP callback recreates wrapped dataloader from its Datasource directly ignoring any overridden `get_idxs` function you may had.

**Comment by jph00** [comment]
Thanks will check this out.
