### ISSUE TITLE
Tutorial issue: No module named 'fastai.vision.all'

### ISSUE THREAD

**Issue by oliverguhr** [fastai/fastai#2647]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

**Describe the bug**
Importing "from fastai.vision.all import *" retruns this error:
ModuleNotFoundError: No module named 'fastai.vision.all'

**To Reproduce**
1. Import "from fastai.vision.all import *"

**Expected behavior**
Import works

**Error with full stack trace**
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-319-5635efd54484> in <module>
----> 1 from fastai.vision.all import *

ModuleNotFoundError: No module named 'fastai.vision.all'

```

**Additional context**
I tried to follow the  [imagenette tutorial](https://docs.fast.ai/tutorial.imagenette) and got this message. 
The other [vision tutorial](http://docs.fast.ai/tutorial.vision) also states that one should import "from fastai.vision.all import *". 

Are the tutorials outdated or is it a bug?

**Comment by Ayush-Parhi** [comment]
> Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES
> 
> **Describe the bug**
> Importing "from fastai.vision.all import *" retruns this error:
> ModuleNotFoundError: No module named 'fastai.vision.all'
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Import "from fastai.vision.all import *"
> 
> 
> **Expected behavior**
> Import works
> 
> **Error with full stack trace**
> 
> ```
> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-319-5635efd54484> in <module>
> ----> 1 from fastai.vision.all import *
> 
> ModuleNotFoundError: No module named 'fastai.vision.all'
> ```
> 
> **Additional context**
> I tried to follow the [imagenette tutorial](https://docs.fast.ai/tutorial.imagenette) and got this message.
> The other [vision tutorial](http://docs.fast.ai/tutorial.vision) also states that one should import "from fastai.vision.all import *".
> 
> Are the tutorials outdated or is it a bug?

I don't see fastai.vision.all function or class in the source code, 
If your intention is to import all the functions and classes from fastai.vision module you can do:
```
from fastai.vision import *
```

**Comment by oliverguhr** [comment]
@Ayush-Parhi  I know, that's why I think that the tutorial is outdated. However, I wanted to use the "ImageDataLoaders" from the tutorial, but this class in not present in "fastai.vision"..
