### ISSUE TITLE
Readme links return 404 and need to be updated

### ISSUE THREAD

**Issue by robmarkcole** [fastai/fastai#2652]
Links from the [readme](https://github.com/fastai/fastai/blob/master/README.md) which are 404:
* https://github.com/fastai/fastai/blob/master/quick_start
* https://github.com/fastai/fastai/blob/master/tutorial
* https://github.com/fastai/fastai/blob/master/migrating_pytorch (under `Plain PyTorch`)
* https://github.com/fastai/fastai/blob/master/migrating_ignite (under `Ignite`)
* https://github.com/fastai/fastai/blob/master/migrating_lightning (under `Lightning`)
* https://github.com/fastai/fastai/blob/master/migrating_catalys (under `Catalyste`)

**Comment by hamelsmu** [comment]
We should try to fix nbdev so that the right links are shown rather than referencing the absolute URLS as I attempted to do in #2680  

cc: @jph00

**Comment by tyoc213** [comment]
@jph00 links on https://github.com/fastai/fastai/blob/master/README.md are OK

**Comment by jph00** [comment]
Thanks!
