### ISSUE TITLE
A way to strip all output from the notebooks in the repo

### ISSUE THREAD

**Issue by ARMATAV** [fastai/fastai#2659]
Couldn't make a new discussion - limited because new user;

https://forums.fast.ai/t/fastai2-and-new-course-release-date-aug-21st/75684/84?u=armatav

I'm running the latest version in Paperspace, and I see the following comment in the book;

> Full and Stripped Notebooks: There are two folders containing different versions of the notebooks. The full folder contains the exact notebooks used to create the book you're reading now, with all the prose and outputs. The stripped version has the same headings and code cells, but all outputs and prose have been removed.

Unfortunately, not only is there no `course-v4/nbs/full` or `course-v4/nbs/stripped` folders in the repo - which makes sense because the course is changing all the time, maybe they don't exist anymore - but it seems that even inside of the `fastbook/clean` folder, the outputs are still visible.

This is an image of what it looks like to open `course-v4/nbs/14_resnet`;

<img width="200" alt="Screen Shot 2020-08-22 at 12 55 07 PM" src="https://user-images.githubusercontent.com/2433203/90964689-bb218a00-e477-11ea-843a-5494a1e8f437.png">

Here is what it looks like to open `fastbook/clean/14_resnet`

<img width="200" alt="Screen Shot 2020-08-22 at 12 58 07 PM" src="https://user-images.githubusercontent.com/2433203/90964687-b6f56c80-e477-11ea-936f-bf57e4c7d9bc.png">

Here is `fastbook/14_resnet`

<img width="200" alt="Screen Shot 2020-08-22 at 1 01 42 PM" src="https://user-images.githubusercontent.com/2433203/90964680-ae049b00-e477-11ea-8ad8-424b88fc1d58.png">

Note, each example has the outputs pre-displayed below the cell. (The four images)

I may be in the minority here, but when the notebooks show the output, it really takes the magic of seeing everything "going" away. Devil's advocate here, obviously doesn't apply to people very focused on learning the content, but why run the model if I already see 16 cat images with probabilities below them.

Essentially, I don't want to be "spoiled", I want to actually wait the 20 minutes to train some big model and get rewarded the hard way. The only thing better than that I would say is a function definition with some comments;

```py
# Cell
def train_new_model():
    batch_size = 12

    # 1. Make sure you load in the learner!
    # 2. Make sure you've got the data ready from "some_global"!
    # 3. Begin training and print the outputs - hint: docs.fastai.com/logging/print_stuff
```

I want **hardmode**, and since there's nothing like the above right now, where can I find the stripped notebooks?

😃

**Comment by hamelsmu** [comment]
To strip outputs you can run 

nbs_clean_nbs

See nbdev docs http://nbdev.fast.ai/

**Comment by jph00** [comment]
We actually need to strip the outputs and non-markdown non-heading cells for this, and commit that to `clean` folder. I'll work on it.

**Comment by marii-moe** [comment]
I think this was already done: https://github.com/fastai/course-v4
