### ISSUE TITLE
show link in colab not working

### ISSUE THREAD

**Issue by foobar8675** [fastai/fastai#2665]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

**Describe the bug**
the show link in colab cells not working. 
**To Reproduce**
here's a colab notebook. just run the cells and click show in the doc cell
https://colab.research.google.com/drive/1uo0JgvXshH0EzO9TZ-UFv_SE_hA0MPNx?usp=sharing

**Comment by jph00** [comment]
Unfortunately colab doesn't run "real" juptyer, so some things just don't work.
