### ISSUE TITLE
Load learner is not loading in new version of fast ai (2.0)

### ISSUE THREAD

**Issue by hemanth1991** [fastai/fastai#2667]
While running the script for inference load_leaner is not loading with new version of fast ai 2.0 but works fine for 1.6 
getting this error.
model = load_learner("./weights/",'mobilenetv2_8epochs_best.pkl')
NameError: name 'load_learner' is not defined

Kindly help

**Comment by muellerzr** [comment]
We need much more information in regards to this, what code were you using? What are all the library versions exactly? What imports did you call?

**Comment by jph00** [comment]
Please use the forums for help

**Comment by hemanth1991** [comment]
> We need much more information in regards to this, what code were you using? What are all the library versions exactly? What imports did you call?

Kindly find the response inline:
from fastai import *
from fastai.vision import *
from fastai.vision import image
model = load_learner("./weights/",'mobilenetv2_8epochs_best.pkl')

Was getting NameError: name 'load_learner' is not defined
fast ai version 2.0 
fast ai version 1.6 it is working fine..

**Comment by muellerzr** [comment]
As Jeremy recommended, this is not a bug in the library. Please post on the forums for help with this issue. (And in general it’s best practice to do so then open an issue if it still can’t be resolved)
