### ISSUE TITLE
Need a Dataset Wrapper class for PyTorch Datasets

### ISSUE THREAD

**Issue by sampathweb** [fastai/fastai#267]
One of the members of the forum asked a question on how to give a PyTorch dataset to Fast.AI.  After looking around dataset.py, I ended up writing a `TorchWrapperDataset` based on ArraysDataset.  Appreciate if you can take a look and confirm if we can add to fastai datasets.

http://forums.fast.ai/t/how-to-use-pytorch-dataset/13300/2

**Comment by jph00** [comment]
Probably easiest to PR your wrapper so I can see what you did. Thanks for this!
