### ISSUE TITLE
Several fast.ai websites down (including docs.fast.ai)

### ISSUE THREAD

**Issue by spion** [fastai/fastai#2674]
**Describe the bug**

Looks like the documentation and book example data hosting sites are down.

**To Reproduce**
1.  Try to visit https://docs.fast.ai
2. If it works for you, try browsing through a service such as https://hidester.com/proxy/

**Expected behavior**
The website can be opened

**Error with full stack trace**

```
This site can’t provide a secure connectiondocs.fast.ai uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
Unsupported protocol
The client and server don't support a common SSL protocol version or cipher suite.
```

**Additional context**
Hidester reports:

```
Error: The requested resource could not be loaded. libcurl returned the error:
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

**Comment by jph00** [comment]
Should be fixed now.
