### ISSUE TITLE
Documentation: Links in navigation bar return Not Found (404)

### ISSUE THREAD

**Issue by CaveSven** [fastai/fastai#2683]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES 

**Describe the bug**
Clicking on any of the links in the left navigation bar on https://docs.fast.ai/ returns a 404 for various pages.
Examples:
* Does work for links in the section "Getting Started"
* Does not work for links in the section "Tutorials"

**To Reproduce**
1. Go to https://docs.fast.ai/
2. In left navigation bar, click "Tutorials".
3. Select link "Tutorials > Overview"

**Expected behavior**
Link should work, i.e. http status should be 200.

**Comment by jph00** [comment]
Working on it - thanks!

**Comment by CaveSven** [comment]
Working now, thanks a lot!
