### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ishandahal** [fastai/fastai#2685]
The link below seems to be broken.
https://docs.fast.ai/torch/utils/data/dataloader.py#L60

**Comment by jph00** [comment]
Where did you see that link?

**Comment by ishandahal** [comment]
Hey Jeremy,
Great to hear from you.
I was browsing the website to understand different class and functions and
came across it.

**Comment by ishandahal** [comment]
It's in the site below. The source code for class Dataloader.
https://docs.fast.ai/data.load#DataLoader

**Comment by jph00** [comment]
Many thanks - fixed.

**Comment by ishandahal** [comment]
Appreciate all that you do Jeremy!
