### ISSUE TITLE
development guide is hidden

### ISSUE THREAD

**Issue by hamelsmu** [fastai/fastai#2688]
AFAIK https://docs.fast.ai/dev/ is sort of a hidden site.  It is hard to navigate there from https://docs.fast.ai/

Can we have something in the sidebar or otherwise to fix this?

Maybe I will try to close this issue 😆

**Comment by jph00** [comment]
I'm not sure if any of those links are actually useful, and/or up to date. They're from fastai1. Maybe you can take a look and see if any are helpful? If so, we should include the helpful ones directly, after ensuring they're up to date.

**Comment by jph00** [comment]
OK I've added the links from that page to the sidebar. Some are a bit out of date and many are overly verbose though.

**Comment by hamelsmu** [comment]
Thanks main reason I thought of this is there are (broken) links to this
page from the Contributing guide and I think from some places in the README
