### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by prairie-guy** [fastai/fastai#2703]
In https://docs.fast.ai/  most of the links under `fastai development` are dead, including:
https://docs.fast.ai/abbr
https://docs.fast.ai/style
https://docs.fast.ai/gpu
https://docs.fast.ai/git

**Comment by muellerzr** [comment]
@prairie-guy some digging resulted in that it should point to here: https://docs.fast.ai/dev/, however here the `.md`'s still won't show

**Comment by jph00** [comment]
Many thanks - fixed now.
