### ISSUE TITLE
`vision.models` link broken?

### ISSUE THREAD

**Issue by iphyer** [fastai/fastai#2709]
Hi, I just checked this link, it seems, `vision.models` link is broken now, it says Not Found for this link

https://docs.fast.ai/vision.models.html

**Comment by hamelsmu** [comment]
Where did you find this link?

**Comment by iphyer** [comment]
Hi @hamelsmu it is found by googling. I want to check the model provided by FastAI and it is the second results showed.

![image](https://user-images.githubusercontent.com/1913891/91537313-b297dc00-e8db-11ea-861e-616dde7857b4.png)

**Comment by muellerzr** [comment]
It is part of the old library and is at https://fastai1.fast.ai/vision.models.html (so this can be closed)
