### ISSUE TITLE
nbdev_test_nbs fails when multiple versions of `libomp` are installed

### ISSUE THREAD

**Issue by aseifert** [fastai/fastai#2717]
YES i have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one)

**Describe the bug**
Running `nbdev_test_nbs --fname nbs/01_layers.ipynb` on my mac installation gives

`OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized.`

Many mac people describe a similar problem with other libraries, see e.g.: https://github.com/dmlc/xgboost/issues/1715

**Additional context**

> OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

Not sure what's the best way to go about it: make people fix their setup and risk having this problem come up again and again, or maybe to put this someplace in the library:

```python
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'
```

**Comment by jph00** [comment]
OK I'll do that workaround, until someone finds a better answer
