### ISSUE TITLE
Empty Generator when using your own dataset 

### ISSUE THREAD

**Issue by Angad-Boparai** [fastai/fastai#2720]
I am using a dataset having downloaded images from google search engine.
Uploaded the image folders using a mounted folder on google drive.
The dataset goes through most of the augmentation commands but unable to train.
![Capture](https://user-images.githubusercontent.com/61798473/91603861-5be9db00-e98b-11ea-9864-8c6394eeb256.JPG)

**Comment by jph00** [comment]
Best to use the forums for support.
