### ISSUE TITLE
Dead links from the search index

### ISSUE THREAD

**Issue by manisnesan** [fastai/fastai#2722]
**Describe the bug**
It appears there are dead links found in the search index. 

**To Reproduce**
1. Go to docs.fast.ai
2. Search for basic_data 
3. Click on any of the top 3 search results (eg: https://docs.fast.ai/basic_data , https://docs.fast.ai/overview.html, https://docs.fast.ai/datasets.html)
4. Would result in Not Found 

**Expected behavior**
Should return empty results if the keyword is not found. Or if found should return valid pages.

![screenshot-docs fast ai-2020 08 29-09_33_28](https://user-images.githubusercontent.com/153142/91638112-181ec200-e9db-11ea-86cb-71dafca723c7.png)

**Comment by manisnesan** [comment]
Debugging Notes
* There are 127 docs currently indexed by Google from docs.fast.ai https://www.google.com/search?q=site:docs.fast.ai
*  https://support.google.com/webmasters/answer/9012289 may help to identify why these are not urls are not indexed by Google.

Reference
* https://nbdev.fast.ai/search

**Comment by muellerzr** [comment]
Related, how to remove those index's: https://www.sistrix.com/ask-sistrix/google-index-google-bot-crawler/how-can-i-remove-a-url-on-my-website-from-the-google-index/#:~:text=Option%20%231%3A%20Use%20the%20robots%20meta%2Delement%20with%20NOINDEX&text=If%20the%20page%20already%20has,removed%20from%20the%20Google%20index.

**Comment by tyoc213** [comment]
currently it only display 2 results 

![image](https://user-images.githubusercontent.com/506234/93729577-c8bb5400-fb8a-11ea-8a2c-5258a5ecbe92.png)

which the first is 404 https://docs.fast.ai/callbacks.mem.html

**Comment by morganmcg1** [comment]
Multiple searches (including for "basic_data") return links that all work for me

 @jph00 I think this is fixed
