### ISSUE TITLE
NLP Classification/Regression MiniBatch Data Bug

### ISSUE THREAD

**Issue by nickgeoca** [fastai/fastai#2727]
NLP classification data processing bug. Input text is not put into the mini batches. Using IMDB data and AWS-LSTM model.

fastai 2.0

**Describe the bug**
After creating a classification/regression batch, the text data is removed. After row one, the text is padding symbols.
<img src="https://user-images.githubusercontent.com/2054736/91668396-4b3b8100-eac1-11ea-852c-37813289f6b2.png" width="120">

**To Reproduce**
```python
import fastbook
fastbook.setup_book()

from fastbook import *
from fastai.text.all import *

path = untar_data(URLs.IMDB)
get_imdb = partial(get_text_files, folders=['train', 'test', 'unsup'])

dls_lm = DataBlock(
    blocks=TextBlock.from_folder(path, is_lm=True),
    get_items=get_imdb, splitter=RandomSplitter(0.1)
).dataloaders(path, path=path, bs=128, seq_len=80)

dls_clas = DataBlock(
    blocks=(TextBlock.from_folder(path, vocab=dls_lm.vocab),CategoryBlock),
    get_y = parent_label,
    get_items=partial(get_text_files, folders=['train', 'test']),
    splitter=GrandparentSplitter(valid_name='test')
).dataloaders(path, path=path, bs=128, seq_len=72)

dls_clas.show_batch(max_n=3)
```

**Comment by nickgeoca** [comment]
Showing batch after runinng the first DataBlock works fine though. The second Datablock causes the bug.
```python
dls_lm = DataBlock(
    blocks=TextBlock.from_folder(path, is_lm=True),
    get_items=get_imdb, splitter=RandomSplitter(0.1)
).dataloaders(path, path=path, bs=128, seq_len=80)

dls_lm.show_batch(max_n=2)
```

**Comment by jph00** [comment]
I believe the data is there - it's just that the initial tokens are padding, since the data is sorted for you by size (and show_batch truncates). If you check the actual data and see it really is all padding, feel free to re-open this with the code showing that.
