### ISSUE TITLE
AttributeError: 'str' object has no attribute '__stored_args__'

### ISSUE THREAD

**Issue by binarymason** [fastai/fastai#2758]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

**About my system:**
```
os: Ubuntu 20.04.1
python: [GCC 7.3.0] :: Anaconda, Inc. on linux



fastai                    2.0.0              pyh39e3cac_0    fastai
fastbook                  0.0.9                    pypi_0    pypi
fastcache                 1.1.0            py38h7b6447c_0  
fastcore                  1.0.1              pyh39e3cac_0    fastai
fastprogress              1.0.0              pyh39e3cac_0    fastai
fastscript                1.0.0                    pypi_0    pypi
gh                        0.11.1                        0    fastai
nbdev                     1.0.10                   pypi_0    pypi
pytorch                   1.6.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
torchvision               0.7.0                py38_cu102    pytorch

```

**To Reproduce**
1. `conda install -c fastai -c pytorch -c anaconda fastai gh anaconda`
2. `python3 -c "from fastai.basics import *"`

**Expected behavior**
No errors to occur when following fastai examples.

**Error with full stack trace**

```
$ python3 -c "from fastai.basics import *"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/m/anaconda3/lib/python3.8/site-packages/fastai/basics.py", line 1, in <module>
    from .data.all import *
  File "/home/m/anaconda3/lib/python3.8/site-packages/fastai/data/all.py", line 5, in <module>
    from .transforms import *
  File "/home/m/anaconda3/lib/python3.8/site-packages/fastai/data/transforms.py", line 230, in <module>
    class Categorize(DisplayedTransform):
  File "/home/m/anaconda3/lib/python3.8/site-packages/fastai/data/transforms.py", line 232, in Categorize
    loss_func,order,store_attrs=CrossEntropyLossFlat(),1,'vocab,add_na'
  File "/home/m/anaconda3/lib/python3.8/site-packages/fastcore/utils.py", line 472, in _f
    return inst if to_return else f(*args, **kwargs)
  File "/home/m/anaconda3/lib/python3.8/site-packages/fastai/layers.py", line 306, in __init__
    def __init__(self, *args, axis=-1, **kwargs): super().__init__(nn.CrossEntropyLoss, *args, axis=axis, **kwargs)
  File "/home/m/anaconda3/lib/python3.8/site-packages/fastcore/utils.py", line 472, in _f
    return inst if to_return else f(*args, **kwargs)
  File "/home/m/anaconda3/lib/python3.8/site-packages/fastai/layers.py", line 281, in __init__
    store_attr(self, "axis,flatten,floatify,is_2d")
  File "/home/m/anaconda3/lib/python3.8/site-packages/fastcore/utils.py", line 97, in store_attr
    if not hasattr(self, '__stored_args__'): self.__stored_args__ = {}
AttributeError: 'str' object has no attribute '__stored_args__'

```

Thanks for the wonderful courses, easy-to-use library and of course, your help!

**Comment by binarymason** [comment]
**Update**: I can report that downgrading to fastcore=1.0.0 appears to fix this issue.  Perhaps this commit introduced a bug somehow?

https://github.com/fastai/fastcore/commit/ea1c33f1c3543e6e4403b1d3b7702a98471f3515#diff-2d5ca7a202ff50e2df29f58cfa4a4c12

**Comment by binarymason** [comment]
As this appears to be related to fastcore, closing this and opening issue on that repo. :+1:

**Comment by acabhishek942** [comment]
@binarymason did you submit an issue in fastcore repo ?

**Comment by jeffrwells** [comment]
If you're coming to this issue later on, the issue I ran into with this was that I had `fastcore==1.0.9` installed with `fastai==2.0.6`.

I downgraded to `fastcore==1.0.0` and got this to work

**Comment by vishalbakshi** [comment]
I'm putting a note here in case someone else is looking at this (and then [the related issue in the fastcore repo]()) as I was---the earliest release where this issue was resolved was `fastai==2.0.10`

**Comment by arnaujc91** [comment]
Same issue happening here. Downgrading to `fastcore==1.0.0` worked as well.

**Comment by cmasenas** [comment]
I have the problem.
```
>>> import fastcore
>>> fastcore.__version__
'1.0.13'
>>> import fastai
>>> fastai.__version__
'2.0.13'
>>> 
```

**Comment by aviogit** [comment]
I'm also having the problem with `fastcore 1.0.13` and `fastai 2.0.13`

**Comment by oriolcosp** [comment]
I'm having the same issue with fastcore 1.0.15 and fastai 2.0.10

**Comment by dreadknought** [comment]
Bump with
fastai==2.0.15
fastai2==0.0.30
fastcore==1.0.16

**Comment by JustinJKlein** [comment]
I am having this same issue and followed the above running into further errorswhcih directed me to update the versions to this:
!pip install fastai==2.1.8
!pip install fastai2==0.0.30
!pip install fastcore==1.3.8.

which worked after I restarted the runtime. I am not sure how to dynamically update this but it would be nice particularly in the how to for using notebooks

**Comment by aadil-srivastava01** [comment]
Sadly the problem still persists :'( in fastai 2.2.7 & fastcore 1.3.19
![image](https://user-images.githubusercontent.com/13318820/111017714-24002d80-83db-11eb-876f-630a571b56a8.png)
