### ISSUE TITLE
Google Colab uses old version of pandas when installing from repo

### ISSUE THREAD

**Issue by IRailean** [fastai/fastai#2760]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

**Describe the bug**
Google Colab uses old version of pandas when installing from repo (1.0.5 instead of last version (1.1.1) ).
This may happen because of duplication of pandas package in requirements in settings.ini file:
requirements = fastcore>=1.0.0 torchvision>=0.7 matplotlib **pandas** requests pyyaml fastprogress>=0.2.4 pillow scikit-learn scipy spacy **pandas>=1.1.0**

If first **pandas** is removed, pandas 1.1.1 is installed in Google Colab.

**To Reproduce**
1. Open Google Colab
2. !pip install git+https://github.com/fastai/fastai.git
3. In a new cell run :
`
    import pandas as pd  

    pd.\_\_version__
`
The result is 1.0.5

**Expected behavior**
Expected latest pandas version installed. (currently 1.1.1)

**Error with full stack trace**

Place between these lines with triple backticks:
N/A

**Additional context**
N/A

**Comment by KushajveerSingh** [comment]
Probably pandas is a requirement of some other package in colab i.e. why it is not upgrading it.

**Comment by IRailean** [comment]
Google Colab has its own version of pandas. 
In settings.ini we have 2 requirments for pandas: "pandas" and "pandas>=1.1.0". Maybe, pip during installing process ignores second requirment and will not install pandas with version >=1.1.0. 
Why there are two pandas reqs in settings.ini file, why it is required?

**Comment by tyoc213** [comment]
Is there some runable code that can be used to test for error?? just did the instructions in the OP and got fastai installed


![image](https://user-images.githubusercontent.com/506234/93728190-652e2800-fb84-11ea-8609-f95b90f39e4d.png)

If on the other case you can the latest for the moment doing `!pip install --upgrade pandas` before importing pandas (or restart colab env).

**Comment by morganmcg1** [comment]
@jph00 @muellerzr is there a need to list `pandas` twice in `settings.ini`?

**Comment by muellerzr** [comment]
@morganmcg1 no, that is a typo (though I don't believe it should affect anything except may check that it's installed)

**Comment by jph00** [comment]
This should be resolved now.
