### ISSUE TITLE
Problems running vision tutorial in colab

### ISSUE THREAD

**Issue by rfernand2** [fastai/fastai#2762]
**Describe the bug**
I have opened the vision tutorial notebook in colab, using the colab button on this page: https://docs.fast.ai/tutorial.vision.  When trying to execute the first cell (`from fastai.vision.all import *`) I get the following error:

> ModuleNotFoundError: No module named 'fastai.vision.all'

After some poking around, I tried to remove the ".all" in the above code, and the cell executed successfully.  Assuming that was a valid bug workaround, I then tried executing the other cells.  On the cell containing `dls = ImageDataLoaders.from_name_func(path, files, label_func, item_tfms=Resize(224))`, I received the error:

> NameError: name 'ImageDataLoaders' is not defined

**To Reproduce**
See Above

**Expected behavior**
I expected to execute each cell without errors and with correct output.

**Error with full stack trace**

Place between these lines with triple backticks:

```
```

**Additional context**

**Comment by vishalbakshi** [comment]
Hi @rfernand2 I found a potential solution ([from the fast.ai course forums](https://forums.fast.ai/t/modulenotfounderror-no-module-named-fastai-vision-all-on-kaggle-notebook/77008)) which is to run `!pip install fastai --upgrade`, then restart the runtime, upon which the `fastai.vision.all` import worked for me.

**Comment by rfernand2** [comment]
Thanks @vishalbakshi - that fixed the 2 problems for me!  But it seems there is a tutorial / colab version pairing problem that I hope gets addressed by this issue.

**Comment by jph00** [comment]
I've added a pip upgrade cell to the top of every notebook now, which should resolve this.

**Comment by rfernand2** [comment]
Awesome thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
