### ISSUE TITLE
"/callbacks" documentation pages returns a 404 

### ISSUE THREAD

**Issue by dgellow** [fastai/fastai#2763]
**Describe the bug**

The page https://docs.fast.ai/callbacks from the library documentation returns a `404 Not found`.

**To Reproduce**

1. Go to https://docs.fast.ai/
2. Search for "showgraph"
3. Click on the first result

![image](https://user-images.githubusercontent.com/2451004/92323794-e1305800-f03b-11ea-9ccf-28b9adac09ab.png)

**Expected behavior**

I expected to get to the documentation of fast.ai callbacks, but instead got a 404.

![image](https://user-images.githubusercontent.com/2451004/92323810-fb6a3600-f03b-11ea-830e-c0117b47ee22.png)

**Comment by dgellow** [comment]
Hmm, I found out that the correct page for the documentation seems to be https://docs.fast.ai/callback.progress#ShowGraphCallback, is `docs.fast.ai/callbacks` an outdated reference? Maybe the search index should be updated.

**Comment by TannerGilbert** [comment]
The search uses google, and google is still showing search results that were available with version 1 since docs.fast.ai was used for FastAI version 1 first. As the page returns a 404 error, it shouldn't take too long until this link disappears from the search.

**Comment by dgellow** [comment]
Yep, I tried again just now, that seems to be good now.
