### ISSUE TITLE
WeightedDL is inconsistent

### ISSUE THREAD

**Issue by antorsae** [fastai/fastai#2766]
This is really a bigger issue already fixed in https://github.com/fastai/fastai/pull/2729 but reporting here so it does not get lost. 

The problem is `get_idxs()` gets called in `WeightedDL` with `num_workers` > 1, and b/c it doesn't use `self.rng` as seed, multiple workers will create different (inconsistent) idxs. There is a test `AdamantDL` in the PR above to illustrate this clearly.

**Comment by morganmcg1** [comment]
@jph00 from the looks of the linked PR https://github.com/fastai/fastai/pull/2729 it looks like this is fixed
