### ISSUE TITLE
fastcore version fails import of from ```fastai.vision.all import *```

### ISSUE THREAD

**Issue by harsh2ai** [fastai/fastai#2770]
I tried using the new version of fastai on my local pc as well as colab settings, both gave me the same issue

Steps involved 

1.  pip install fastai==2.0
2. from fastai.vision.all import *
3. do the same steps as intro.ipynb

I expected the code cell to run without errors 

```import fastcore
from fastai.vision.all import *
path = untar_data(URLs.PETS)/'images'

def is_cat(x): return x[0].isupper()
dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2, seed=42,
    label_func=is_cat, item_tfms=Resize(224))

learn = cnn_learner(dls, resnet34, metrics=error_rate)
learn.fine_tune(1)

```

The following error popped up
```'str' object has no attribute '_stored_args_'```

I had to downgrade the version fastcore to 1.0.0 to run the code block. Let's hope this issue gets resolved in the future a few colleagues of mine also faced the same.

**Comment by KushajveerSingh** [comment]
Use `pip install fastai==2.0.9`. I think pip does not upgrade a package if there is only a patch release. I verified on the master branch and the code is working. So probably you have an older fastai version.

**Comment by harsh2ai** [comment]
Seems true tried this just now, I was using fastai 2.0.0 and you recommended 2.0.9, Things go sideways in just minor patch releases of the same version

**Comment by RMNT** [comment]
Had the same problem with
`from fastai.tabular.all import *`
What helped me was changing `pip install fastai` to `pip install fastai --upgrade`, running the cell and restarting the runtime

**Comment by tyoc213** [comment]
yeah, for the moment there is no dependence in versions for fastai and fastcore... so you need to upgrade to make sure you have the latest, the best you can do is to save in some place your fastai and fasctore versions so you know which versions you installed... but think of this, if you install fastai with version == 2, most likely you will get the latest fastcore version, not say v 1 of fastcore.

**Comment by tyoc213** [comment]
so my suguestion would be to use `!pip install --upgrade fastai`

**Comment by morganmcg1** [comment]
@jph00 I can see `fastcore>=1.0.5` is now in `settings.ini` which should address this dependency issue, this can probably be closed
