### ISSUE TITLE
404 for Callback page that shows up in Google results

### ISSUE THREAD

**Issue by Harsh-Singh-1** [fastai/fastai#2776]
Google results for fastai callback gives you the page "https://docs.fast.ai/callback.html" as the first result. However, upon clicking the results it gives you a 404 error. Please fix the broken link ASAP. 

Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

**Comment by TannerGilbert** [comment]
I think this error is a result of moving the old fastai v1 documentation from docs.fast.ai to fastai1.fast.ai.

- Callback FastAI v2: https://docs.fast.ai/callback.core
- Callback FastAI v1: https://fastai1.fast.ai/callback.html

**Comment by WillowRainbowe** [comment]
To everyone this may concern;

I have unsubscribed to this site , please STOP sending me any more emails.

Thank you
ntr.lvin.wiccan.witch@gmail.com

**Comment by morganmcg1** [comment]
Just tested a few searches for fastai ("fastai callback" etc) and all the links appear to work correctly now

@jph00 I think this can be closed
