### ISSUE TITLE
Followed link from google to broken link

### ISSUE THREAD

**Issue by schoenbl** [fastai/fastai#2777]
**Describe the bug**
Clicked on a link from Google, and it led me to a page that asked me to fill out a bug report.

**To Reproduce**
1.  Search untar_data in google, and click on the first link

**Expected behavior**
Expected to see a page that described the search

**Comment by RMNT** [comment]
I am pretty sure that different people will get different first links on google. Please provide your first link

**Comment by TannerGilbert** [comment]
Pretty sure this is also caused from moving the old documentation from docs.fast.ai to fastai1.fast.ai. Google took some time to realize that some urls have changed. 

Related issues:
https://github.com/fastai/fastai/issues/2776

**Comment by morganmcg1** [comment]
Tested this and the fastai docs links that I get in Google link to pages that work

@jph00 I think these doc's link issues look like they are fixed
