### ISSUE TITLE
Equivalent function of LanguageModelData in v1.0.x and onwards of fastai

### ISSUE THREAD

**Issue by ShreyaGupta08** [fastai/fastai#2783]
I am trying a script that has a line

`md = LanguageModelData(PATH, 1, vs, trn_dl, val_dl, bs=bs, bptt=bptt)` 

on running it, I get an error:
"NameError: name 'LanguageModelData' is not defined"

On looking at previous issues I discovered that this function was available only till v0.7 and has been removed in v1.0.x onwards. Is there a workaround to run codes that have used this function or an equivalent function that does the job of LanguageModelData?

I am using this function for the implementation of ULMFit, in the following code snippet:
`trn_dl = LanguageModelLoader(np.concatenate(trn_lm), bs, bptt)`
`val_dl = LanguageModelLoader(np.concatenate(val_lm), bs, bptt)`
`md = LanguageModelData(PATH, 1, vs, trn_dl, val_dl, bs=bs, bptt=bptt)`

where trn_lm and val_lm are numpy arrays.

**Comment by TannerGilbert** [comment]
LanguageModelData is from a real old version of FastAI (0.7 as far as I have seen). With FastAI 2 you can use TextDataLoaders instead. For more information on how to implement ULMFit with FastAI 2 you can check out [the documentation](https://docs.fast.ai/tutorial.text#The-ULMFiT-approach)

**Comment by morganmcg1** [comment]
@jph00 I think this has been answered, either by downgrading to v0.7 or modifying the script being used to follow the v2 example linked above
