### ISSUE TITLE
THCudaCheck FAIL: operation not supported on Windows device

### ISSUE THREAD

**Issue by christian-vorhemus** [fastai/fastai#2784]
torch version:  1.6.0+cu101
fastai version: 2.0.10
OS: Windows 10

I followed the "Vision" example from [here](https://www.fast.ai/2020/02/13/fastai-A-Layered-API-for-Deep-Learning/#vision) to create a model. First thing I noticed when I ran `learn.fit_one_cycle(4)` is that apparently there is no `fit_one_cycle()` method in the Learner class anymore - at least I don't find it in the source or the [docs](https://docs.fast.ai/learner.html#Learner). 

I guess this is just an update not reflected in the tutorial? I replaced it with `learn.fit(10)`

Second more critical thing is when I run learn.fit(10), I get `THCudaCheck FAIL file=..\torch/csrc/generic/StorageSharing.cpp line=247 error=801 : operation not supported`

As I read [here](https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-without-if-clause-protection), multiprocessing on CUDA tensors don't work when running on Windows. But shouldn't fastai catch this error internally and switch back to single process execution? How do I tell fastai to run just one process?

Full code:

```python
from fastai.vision.learner import cnn_learner
from fastai.vision.models import resnet34
from fastai.metrics import error_rate
from fastai.vision.data import ImageDataLoaders
from fastai.vision.augment import RandomResizedCrop, Resize, Normalize, imagenet_stats, crop_pad
import matplotlib.pyplot as plt

dls = ImageDataLoaders.from_folder('C:/ml/sampledata', train='train', valid='valid',
                                     tem_tfms=Resize(256), batch_tfms=Normalize.from_stats(*imagenet_stats))

dls.show_batch()
plt.show()

learn = cnn_learner(dls, resnet34, metrics=error_rate)
learn.fit(10)

learn.show_results()
plt.show()
```

**Comment by muellerzr** [comment]
You need to set `num_workers` to zero in your call to `ImageDataLoaders`

**Comment by jph00** [comment]
We don't support Windows, sorry.

**Comment by rawmean** [comment]
Setting `num_workers` to zero worked. Thanks!
`dls = bears.dataloaders(path, num_workers=0) `

**Comment by nelsonjchen** [comment]
@jph00 Would you take a PR to set and force `num_workers=0` on Windows with a warning printed that it was overridden if it was set? 

The `num_workers=0` thing isn't a terrible blocker and it would mean being able to run the tutorial notebooks out of the box on Windows without having to modify the notebooks. Reducing onboarding friction is always desirable.

As for maintenance burden drawback, would it be acceptable to have the removal milestone for this small piece of code be when WSL2 with CUDA/GPU access is released on stable Windows?

**Comment by jph00** [comment]
This only impacts notebooks, I believe, and I wouldn't want to break (or slow) working scripts.

**Comment by nelsonjchen** [comment]
The small change shouldn't break or slow working scripts at all as it would be a no-op on non-Windows platforms. Scripts on non-Windows platforms would not break, slow, or be affected in any way. 

That said, it may surprise Windows users who run code that forcibly set `num_workers` to non-zero or those who let fastai set the value. I think a printed warning and a do-what-i-mean-to-really-do-even-if-its-slower-than-linux-just-get-running-on-windows corrective action is probably better than not working at all with the mysterious message in this issue. 

This might be easier to explain if I just sent in the PR.

**Comment by jph00** [comment]
As I mentioned, the issue is that scripts don't need this change, only notebooks.
