### ISSUE TITLE
show_batch() function does not show BBoxes correctly.

### ISSUE THREAD

**Issue by IRailean** [fastai/fastai#2786]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES 

**Describe the bug**
Try to run https://docs.fast.ai/tutorial.datablock#Bounding-boxes tutorial with different parameter sent in Resize function (other than 128). BBoxes with wrong size and location are shown.

**To Reproduce**
1.  Install fastai from git using command:
     !pip install git+https://github.com/fastai/fastai.git
2. Import fastai
```
   from fastai.data.all import *
   from fastai.vision.all import *
```
3. Run the following code from the [tutorial](https://docs.fast.ai/tutorial.datablock#Bounding-boxes), setting the parameter in Resize function other that 128. (128 is the size of a picture in the coco_tiny dataset mentioned in the tutorial)
```
   
   coco_source = untar_data(URLs.COCO_TINY)
   images, lbl_bbox = get_annotations(coco_source/'train.json')
   img2bbox = dict(zip(images, lbl_bbox))
   
   coco = DataBlock(blocks=(ImageBlock, BBoxBlock, BBoxLblBlock),
                 get_items=get_image_files,
                 splitter=RandomSplitter(),
                 get_y=[lambda o: img2bbox[o.name][0], lambda o: img2bbox[o.name][1]], 
                 item_tfms=Resize(256),
                 batch_tfms=aug_transforms(),
                 n_inp=1)

   dls = coco.dataloaders(coco_source)
   dls.show_batch(max_n=9)

```
4. Look at the output of the show_batch() function.

**Expected behavior**
BBoxes shown correctly.

**Additional context**
This may happen because of applying PointScaler, Resize transforms incorrectly to TensorBBox.

**Comment by marii-moe** [comment]
Adding my gist to this one: https://gist.github.com/marii-moe/be625c65e6d8aa783370cc70c7bc7ae2

I am continuing to look into this one, but I am fairly stuck on it.

**Comment by IRailean** [comment]
Take a look at _unscale_pnts function in vision/core.py The problem may be that for unscaling it uses the original size of a picture not the resized one. 
I hardcoded sz variable in _unscale_pnts to a resized picture size: 
sz = fastuple((700, 700)) (In DataBlock API I used Resize(700, method=ResizeMethod.Squish)
and it worked! (Working also with other ResizeMethods.

So this may be the issue.

**Comment by marii-moe** [comment]
@IRailean yeah, I believe in previous versions of fastai x.get_meta('img_size') may have returned None, which is why this stopped working in more recent versions. I will try to run this against my older environment tomorrow to validate this though. I got stuck when actually determining what changed this behavior across the different versions of fastai, as I couldn't really find code that seemed responsible. 

If you check the git blame _get_sz hasn't changed within the last 9 months. https://github.com/fastai/fastai/blame/72590db2e66af6dd0eaa8c8874a80f11a4b8cbc2/fastai/vision/core.py#L244

**Comment by jph00** [comment]
Honestly, I don't recall how the obj det code works at the moment, and it'll be a while before I'm looking at it again. So I'll just accept the PR, and if anyone finds that the behavior isn't right, please let me know and we can try again!

**Comment by marii-moe** [comment]
@IRailean I think this one is fixed now?

**Comment by IRailean** [comment]
@marii-moe Yes, I think it can be closed. Thank you for your participation.
