### ISSUE TITLE
Google Colab wrong default version

### ISSUE THREAD

**Issue by TannerGilbert** [fastai/fastai#2790]
The [readme](https://github.com/fastai/fastai#installing) says: 
> "You can use fastai without any installation by using Google Colab. In fact, every page of this documentation is also available as an interactive notebook - click "Open in colab" at the top of any page to open it (be sure to change the Colab runtime to "GPU" to have it run fast!) See the fast.ai course Introduction to Colab for more information."

This isn't exactly true since the default FastAI version on Google Colab is 1.0.61. 

![fastai_version](https://user-images.githubusercontent.com/36239763/93018982-5ff53a00-f5d4-11ea-960a-36be5bb08bfe.png)

Therefore if you want to use FastAI v2 you will need to upgrade:

![upgrade_version](https://user-images.githubusercontent.com/36239763/93019005-8dda7e80-f5d4-11ea-8af5-19b7107d9450.png)

This also causes an error when you execute the documentation code after clicking "Open in colab"

Example (https://colab.research.google.com/github/fastai/fastai/blob/master/nbs/23_tutorial.vision.ipynb#scrollTo=cRys4c8EoDAO):

![computer_vision_documentation_error](https://user-images.githubusercontent.com/36239763/93019053-d98d2800-f5d4-11ea-8dcf-afbbe5698738.png)

@jph00 Is it possible to change the default version of FastAI in Google Colab to version 2?

**Comment by TannerGilbert** [comment]
Related to #2762

**Comment by jph00** [comment]
There's nothing we can do on Colab directly (we've already asked). I'll add a cell to the top of each notebook to update the lib with pip.

**Comment by TannerGilbert** [comment]
Ok thanks. Maybe also change the text in the installation section of the README to indicate that the library needs to be updated to version 2

**Comment by jph00** [comment]
I've added a pip upgrade cell to the top of every notebook now, which should resolve this.
