### ISSUE TITLE
Table of Contents Goes to Incorrect Section

### ISSUE THREAD

**Issue by kevinbird15** [fastai/fastai#2796]
When scrolling through the documentation, I noticed that clicking the link for Segmentation "Using the high-level API" takes me to the wrong section of the document.  It runs out there are two headers with the same name "Using the high-level API" and three with the name "With the data block API" on the same page: https://docs.fast.ai/tutorial.vision

My suggestion would be to modify the naming of these so they have the names in the sub-header as well as the header: 

![image](https://user-images.githubusercontent.com/7451178/93148214-db301c00-f6b8-11ea-8dfb-4279023d9117.png)

**Comment by rushabh-v** [comment]
Good catch! 

Alternatively, `nbdev` can be modified to assign `<header>_<sub-header>` (or some combination of them) as a tag to the sub-headers.
I am willing to contribute!

cc @hamelsmu @jph00

**Comment by jph00** [comment]
Thanks to you both. A PR that fixes the names to be unique would be great! And another one which warns if there are dupe names would also be nice. Don't worry about the header_subheader thing though...
