### ISSUE TITLE
Broken link: https://docs.fast.ai/vision.models.html

### ISSUE THREAD

**Issue by dimvar** [fastai/fastai#2797]
Loading the URL https://docs.fast.ai/vision.models.html gives an error. The error message suggests filing a bug here.

**Comment by TannerGilbert** [comment]
This page was split into two subpages. 
XResnet: https://docs.fast.ai/vision.models.xresnet
UNet: https://docs.fast.ai/vision.models.unet

**Comment by dimvar** [comment]
Thanks for the info.

The old page is still linked to from the search results, so that should probably be fixed. (See screenshot.)
![fastai-docs-screenshot](https://user-images.githubusercontent.com/286890/93246602-debbb580-f741-11ea-9b5f-37e52aff068a.png)

**Comment by TannerGilbert** [comment]
The search uses google to find the results. It will take some time until google search notices that some pages no longer exist.

**Comment by dimvar** [comment]
ok, let's just close this issue then. Thanks.
