### ISSUE TITLE
SubwordTokenizer issue when used in "tokenize_df" 

### ISSUE THREAD

**Issue by caprone** [fastai/fastai#2813]
HI
when in "tokenize_df" func I set SubwordTokenizer as tokenizer, the "TypeError: can't pickle SwigPyObject objects" issue raises..

I initialize the tokenizer:  tokenizer = SubwordTokenizer(vocab_sz=1000);  here I don't  call setup method of SubwordTokenizer class, because I pass raw tokenizer to tokenize_df...;
then I call the function:   df_tok, count = tokenize_df(df, ['text'], tok=tokenizer, n_workers=10)

it works perfectly with spacy tokenizer.
where can be the probelm? the 'setup' method?
thanks

EDIT: sorry, my issue, solved : tokenizer = Tokenizer(SubwordTokenizer(vocab_sz=1000))

**Comment by andresti** [comment]
I'm having the same issue, and the proposed solution doesn't actually work as it doesn't create the spm.model output so I suspect it removes some of the SubwordTokenizer properties
