### ISSUE TITLE
Basic first tutorial not using GPU when running on Google's Colab notebook in a GPU env.

### ISSUE THREAD

**Issue by yoniker** [fastai/fastai#2817]
Hi!

After changing runtime type to GPU, trying to run the following code,taken from the very first fastai tutorial,
will run only on the cpu and will not use the gpu at all: 

```
!pip install -Uqq fastbook
import fastbook
fastbook.setup_book()
from fastai.vision.all import *
path = untar_data(URLs.PETS)
files = get_image_files(path/"images")
def label_func(f): return f[0].isupper()
dls = ImageDataLoaders.from_name_func(path, files, label_func, item_tfms=Resize(224))
learn = cnn_learner(dls, resnet34, metrics=error_rate)
learn.fine_tune(1)
```
The result is that it takes about half an hour to run it, rather than a few minutes (it's only ~7000 images and one epoch).
Would have posted that on the forums as per your request, but there is no option for a new user to post in the fastai forums,and this issue is exactly for those kind of users (like me).

**Comment by asvcode** [comment]
I tried this just now and no issues.

![time](https://user-images.githubusercontent.com/25020209/93621658-bfff2e00-f990-11ea-9da3-41fea0f75b60.PNG)

Can you confirm that the GPU is active?  run this code(bit more flamboyant than needed but it will do the trick)
```
BLUE = '\033[94m'; BOLD = '\033[1m'; ITALIC = '\033[3m'; RESET = '\033[0m'

import fastai; print(BOLD + BLUE + "fastai Version: " + RESET + ITALIC + str(fastai.__version__))
import fastprogress; print(BOLD + BLUE + "fastprogress Version: " + RESET + ITALIC + str(fastprogress.__version__))
import torchvision; print(BOLD + BLUE + "torchvision: " + RESET + ITALIC + str(torchvision.__version__))
import torch; print(BOLD + BLUE + "torch version: " + RESET + ITALIC + str(torch.__version__))
print(BOLD + BLUE + "\nCuda: " + RESET + ITALIC + str(torch.cuda.is_available()))
print(BOLD + BLUE + "cuda Version: " + RESET + ITALIC + str(torch.version.cuda))
print(BOLD + BLUE + "GPU: " + RESET + ITALIC + str(torch.cuda.get_device_name(0)))
```

![gpu](https://user-images.githubusercontent.com/25020209/93622251-a8747500-f991-11ea-9104-a175319114a4.PNG)

**Comment by yoniker** [comment]
fastai Version: 2.0.13
fastprogress Version: 0.2.7
torchvision: 0.7.0+cu101
torch version: 1.6.0+cu101

Cuda: True
cuda Version: 10.1
GPU: Tesla P100-PCIE-16GB

I've tried to restart before i posted the issue, but now when I restarted it, everything is working fine...(less than 50 secs)
This might be related to something in Google Colab, temporary or not. Closing this issue for now.
