### ISSUE TITLE
error in pascal-multi.ipynb

### ISSUE THREAD

**Issue by shirishr** [fastai/fastai#282]
When computing ssd_loss here:

ssd_loss(batch, y, True)

I get an error:

RuntimeError: Expected object of type Variable[torch.cuda.FloatTensor] but found type Variable[torch.FloatTensor] for argument #1 'other'

print(type(batch[0]), type(y[0])) shows

<class 'torch.autograd.variable.Variable'> <class 'torch.autograd.variable.Variable'>

I thought we did declare torch.cuda.set_device(0). Not sure where this error is coming from.

**Comment by apiltamang** [comment]
This is because part of your data is in the GPU, hence the torch.**cuda**.FloatTensor, while part of the data is in CPU, hence the torch.FloatTensor without the **cuda** qualifier.

To resolve, do NOT execute any code calling .cpu() or to_cpu(). These were originally there only for some debugging purposes.

Let know if this helps ..

**Comment by shirishr** [comment]
@apiltamang,
I will try eliminating all .cpu() from all cells and update my results here.
If you do have a working notebook can you share with me?
Thanks

**Comment by apiltamang** [comment]
I've been trying to hand-write the code all the way from the top to the finish, and not quite done with it yet. Thus, don't have anything public to share.

I'm pretty sure people have done this though, so have faith. Somewhere in the fastai forum, you should find answers to any more issues, if still pending.

**Comment by apiltamang** [comment]
I think part of the reason why this was closed, was to move the discussion rather to the forums. Check the forums for this issue too. I barely remember reading somewhere that this might be a bug with PyTorch. Somebody might've resolved that though.

**Comment by jph00** [comment]
Yes that's the reason - the forums is where we would like to have these discussions please.

**Comment by shirishr** [comment]
FYI who may struggle with the pascal-multi.ipynb

If you have a gpu, this is what you may want to do:

Get rid of all **.cpu** and in the class BCE_Loss, definition of forward

change the line from **t = V(t[:,:-1].contiguous())** to **t = V(t[:,:-1].contiguous().cuda())**
