### ISSUE TITLE
_get_sz_change_idxs returns an extra element, 0

### ISSUE THREAD

**Issue by ababino** [fastai/fastai#2820]
**Describe the bug**
The function _get_sz_change_idxs returns an extra 0 if `sizes` changes between index 0 and 1.

**To Reproduce**
1. run
```python
from fastai.vision.models.unet import _get_sz_change_idxs
_get_sz_change_idxs([[3,128,128], [16,64,64], [32,32,32], [16,32,32], [32,32,32], [16,16]])
```
2. It should return [0,1,4]. Instead, it returns [0,0,1,4]

**Expected behavior**
It should pass the following test
```python
test_eq(_get_sz_change_idxs([[3,128,128], [16,64,64], [32,32,32], [16,32,32], [32,32,32], [16,16]]), [0,1,4])
```

**Additional context**

The problem seems to be that the following line in the function definition is not needed:
```python
if feature_szs[0] != feature_szs[1]: sz_chg_idxs = [0] + sz_chg_idxs
```
[This](https://github.com/fastai/fastai/blob/master/nbs/15a_vision.models.unet.ipynb) is the nb where the function is.

This behavior makes the DynamicUnet to use F.interpolate unnecessarily.

If you agree, I can make a PR with this line deleted and with the extra test.

**Comment by marii-moe** [comment]
@ababino I have not dug into this one, but have you run tests against this change? If it does not break anything, and you make sure to test edge cases such as lists of length 0,1,2 then I think it is probably good to make a pull request.

**Comment by ababino** [comment]
Thank you, @marii-moe. It does not break anything, and I added the edge case tests. I'll submit the PR then.
