### ISSUE TITLE
dev notebook code does not compile

### ISSUE THREAD

**Issue by miramar-labs** [fastai/fastai#2823]
Be sure you've searched [the forums](https://forums.fast.ai) for the error message you received. Also, unless you're an experienced fastai developer, first ask on the forums to see if someone else has seen a similar issue already and knows how to solve it. **Only file a bug report here when you're quite confident it's not an issue with your local setup.**

**Please see [this model example](https://github.com/fastai/fastai/issues/487) of how to fill out an issue correctly.  Please try to emulate that example as appropriate when opening an issue.**

Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES 

**Describe the bug**
going through the fastai/dev_nbs/course/lesson2-download.ipynb notebook, there is a block of code:

```
for c in classes:
    print(c)
    verify_images(path/c, delete=True, max_size=500)
```

that does not compile. Looking at the latest source code, I only see the following function with a different signature:

```
def verify_images(fns):
    "Find images in `fns` that can't be opened"
    return L(fns[i] for i,o in enumerate(parallel(verify_image, fns)) if not o)
```

**To Reproduce**
1. run the fastai/dev_nbs/course/lesson2-download.ipynb notebook

**Expected behavior**
it should compile and run

**Error with full stack trace**

Place between these lines with triple backticks:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-b3c17fc2b830> in <module>
      1 for c in classes:
      2     print(c)
----> 3     verify_images(path/c, delete=True, max_size=500)

TypeError: verify_images() got an unexpected keyword argument 'delete'
```

**Additional context**

**Comment by TannerGilbert** [comment]
The use of `verify_images` changed with the newest version. You can find an example in [02_production](https://github.com/fastai/fastbook/blob/master/clean/02_production.ipynb).

**Comment by morganmcg1** [comment]
@jph00 not sure if "dev_nbs" bugs are being actively worked on, if not then this can be closed. @TannerGilbert has pointed out a solution that will will help @miramar-labs get around the issue

(Description on Discord for what `dev_nbs` is for: "It's some useful nbs that aren't part of docs or part of the lib, mainly background info and examples")

**Comment by jph00** [comment]
Thanks - feel free to submit a PR to fix it, but it's probably not worth leaving an issue open.
