### ISSUE TITLE
'PoolingLinearClassifier' object does not support indexing

### ISSUE THREAD

**Issue by sky1ove** [fastai/fastai#2831]
learn = text_classifier_learner(dls, AWD_LSTM)
learn.model[-1][-1]

errors: 'PoolingLinearClassifier' object does not support indexing

**Comment by morganmcg1** [comment]
@sky1ove in future please be more descriptive when describing your issue, for example in the example that is given when you open an issue

If you look closely you can see you can see there is a named module called `layers` that you have to call:

```
PoolingLinearClassifier(
  (layers): Sequential(
    (0): LinBnDrop(
      (0): BatchNorm1d(1200, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (1): Dropout(p=0.2, inplace=False)
      (2): Linear(in_features=1200, out_features=50, bias=False)
      (3): ReLU(inplace=True)
    )
    (1): LinBnDrop(
      (0): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (1): Dropout(p=0.1, inplace=False)
      (2): Linear(in_features=50, out_features=2, bias=False)
    )
  )
)
```

 `learn.model[-1].layers[-1]` should get you what you need

**Comment by morganmcg1** [comment]
@jph00 I think this can be closed
