### ISSUE TITLE
fastai2 reproducibility

### ISSUE THREAD

**Issue by baidut** [fastai/fastai#2832]
I've searched [the forums](https://forums.fast.ai) and people have similar issues but not resolved.
https://forums.fast.ai/t/solved-reproducibility-where-is-the-randomness-coming-in/31628/24

Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES (fastai v2.0.13)

**Describe the bug**
Training results are not reproducible

**To Reproduce**
```python
from fastai.vision.all import *

def set_seed(x=42):
    random.seed(x)
    np.random.seed(x)
    torch.manual_seed(x)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    if torch.cuda.is_available(): torch.cuda.manual_seed_all(x)
    
def is_cat(x): return x[0].isupper()
path = untar_data(URLs.PETS)/'images'
dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2, seed=42,
    label_func=is_cat, item_tfms=Resize(224))


set_seed()
learn = cnn_learner(dls, resnet34, metrics=error_rate)
learn.fit(1)
set_seed()
learn = cnn_learner(dls, resnet34, metrics=error_rate)
learn.fit(1)
```
![image](https://user-images.githubusercontent.com/6234266/94164652-ec162580-fe4e-11ea-913d-38e5b797084d.png)

**Expected behavior**
Same results.

**Comment by vishalbakshi** [comment]
I'm getting the same results when using the `MNIST_SAMPLE` dataset ([here's a colab](https://colab.research.google.com/drive/13XJ_u_HsgLemi4TvWVswKoeO3In9lNCl?usp=sharing)). However, when I downgrade to `fastai==1.0.61` I am able to use the same approach to reproduce the error rate ([here's a colab showing that](https://colab.research.google.com/drive/1_qXO91NzPrzoxOj9k1-qHqsErN_xPtTx?usp=sharing)).

**Comment by marii-moe** [comment]
I took a quick look at this and came up with this which seems to fix your issue: 

```
def set_seed(dls,x=42):
    random.seed(x)
    dls.rng.seed(x)
    np.random.seed(x)
    torch.manual_seed(x)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    if torch.cuda.is_available(): torch.cuda.manual_seed_all(x)
```

**Comment by vishalbakshi** [comment]
Awesome that works for me! Thanks @marii-moe 

@baidut I've updated the colab if you want to see it: https://colab.research.google.com/drive/13XJ_u_HsgLemi4TvWVswKoeO3In9lNCl?usp=sharing

**Comment by marii-moe** [comment]
If you want to do this without all the extra code, you can use fastai's builin set_seed
```
set_seed(42,True)
dls.rng.seed(42)
```
It also does not set dls.rng, which is probably a bug. I'll take a look at it, because I know where it is now. I think this needs a test case so it doesn't regress in the future. 

I will go ahead and work on this, I will try to make it reproducable so that you only have to call ```set_seed```.

**Comment by marii-moe** [comment]
Just looked at this a bit more, and I think I determined how this is supposed to be used actually. This gives different results than previously, but is consistent between runs. The trick here is you have to set the seed, and recreate the dataloader. 
```
from fastai.vision.all import *
def is_cat(x): return x[0].isupper()
path = untar_data(URLs.PETS)/'images'
set_seed(42,True)
dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2, seed=42,
    label_func=is_cat, item_tfms=Resize(224))
learn = cnn_learner(dls, resnet34, metrics=error_rate)
learn.fit(1)
set_seed(42,True)
dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2, seed=42,
    label_func=is_cat, item_tfms=Resize(224))
learn = cnn_learner(dls, resnet34, metrics=error_rate)
learn.fit(1)
```
```

epoch | train_loss | valid_loss | error_rate | time
-- | -- | -- | -- | --
0 | 0.080560 | 0.007115 | 0.002706 | 00:25


epoch | train_loss | valid_loss | error_rate | time
-- | -- | -- | -- | --
0 | 0.080560 | 0.007115 | 0.002706 | 00:25

```

This is how the original set_seed was supposed to work, so after a little more investigation this does not seem to be a regression.

**Comment by baidut** [comment]
Thank you so much for your help! Problem solved!

**Comment by inrcr** [comment]
Thanks @marii-moe! I got different values than you did but they were consistent between runs for me as well. 

<img width="461" alt="Screen Shot 2020-09-25 at 8 38 26 AM" src="https://user-images.githubusercontent.com/71718532/94287006-9e5ef300-ff0a-11ea-888b-aaf32af3788d.png">

**Comment by vishalbakshi** [comment]
Thanks @marii-moe! I was able to get consistent results between runs as well.

<img width="461" alt="Screen Shot 2020-09-25 at 8 38 26 AM" src="https://user-images.githubusercontent.com/28925987/94287415-1f1def00-ff0b-11ea-9e3e-59e908c0999e.png">

**Comment by marcglobality** [comment]
I'm having problems with this. I have 
* in the data_block: shuffle=False, shuffle_train=False
* self.learner.dls.rng.seed(88) before the fine_tune
* set_seed(88, True) before creating the dataloders

Still not getting same results...
