### ISSUE TITLE
Broken link in delegation blogpost

### ISSUE THREAD

**Issue by jamestjw** [fastai/fastai#2833]
Be sure you've searched [the forums](https://forums.fast.ai) for the error message you received. Also, unless you're an experienced fastai developer, first ask on the forums to see if someone else has seen a similar issue already and knows how to solve it. **Only file a bug report here when you're quite confident it's not an issue with your local setup.**

**Please see [this model example](https://github.com/fastai/fastai/issues/487) of how to fill out an issue correctly.  Please try to emulate that example as appropriate when opening an issue.**

Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES 

**Describe the bug**
Broken link in blogpost on fast ai website

**To Reproduce**
1. Go to this blogpost https://www.fast.ai/2019/08/06/delegation/
2. Ctrl+f to look for `show_doc`, which is a link
3. Link brings you to `https://docs.fast.ai/gen_doc.nbdoc.html#show_doc` which gives a 404 not found error

**Expected behavior**
I expected to be brought to the documentation of `show_doc` or something along the lines of that

**Comment by tmabraham** [comment]
I think this was an old link from fastai v1, but I think this feature was moved into the library development package [nbdev](https://github.com/fastai/nbdev) over [here](https://nbdev.fast.ai/showdoc).

**Comment by jph00** [comment]
Many thanks for letting us know.
