### ISSUE TITLE
SaveModelCallback overwrites model files after learning restarts when using start_epoch

### ISSUE THREAD

**Issue by adamfarquhar** [fastai/fastai#2836]
**Describe the bug**

Learn.fit_one_cycle accepts an undocumented start_epoch parameter. This is essential for restarting learning so that it continues with the original hyperparameter schedule.

Start_epoch is very useful when the learner uses the SaveModelCallback with every_epoch=True. In this mode, the callback saves the learner each epoch to a model file with an appended epoch number (e.g., model_1.pkl, model_2.pkl, etc).
Unfortunately, when learning is restarted, the counter restarts at 1 and the model files are over written.
Less important, but undesirable, the progress tracking also restarts with epoch 0, which may lead to confusion.
Bug: SaveModelCallback overwrites early model files after fit_one_cycle restarts learning with a start_epoch specified. 

In general, the very useful ability to restart learning is very poorly covered in the documentation.

**To Reproduce**
1. Train a model for 10 epochs using, eg fine_tune with the SaveModelCallback every_epoch=True
2. Halt training at epoch 5
3. Restart training with start_epoch=5
6. Watch the model files for the first 4 epochs be overwritten during epochs 6-10.

**Expected behavior**
The model files should be named model_1 ... model_4 before restart and continue with model_5 ... model_10 after restart.

**Error with full stack trace**

Place between these lines with triple backticks:

```
```

**Additional context**

**Comment by jph00** [comment]
The current version of fastai does not have `start_epoch`. Feel free to create an issue requested support for restarting training, with details about how you'd like to see it work.
