### ISSUE TITLE
'Series' object has no attribute <Column name>

### ISSUE THREAD

**Issue by sky1ove** [fastai/fastai#2838]
Hi, I found out this bug:

When I load a dataframe, everything looks okay. 

```python
df = pd.read_json('train.json', lines=True)
df['sequence']
```

![image](https://user-images.githubusercontent.com/34699116/94349518-9ab29580-000a-11eb-880d-155747f3e084.png)

However, when I load the dataframe to the datablock, the bug appears:

```python
mRNA_lm = DataBlock(blocks=TextBlock.from_df('sequence', tok=SubwordTokenizer(vocab_sz=25),is_lm=True),
                    get_x=ColReader('sequence'),
                    splitter=RandomSplitter(0.1))
dls = mRNA_lm.dataloaders(df, bs=64)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-33d42daee4b3> in <module>()
----> 1 dls = mRNA_lm.dataloaders(df, bs=64)

9 frames
/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py in __getattr__(self, name)
   5272             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5273                 return self[name]
-> 5274             return object.__getattribute__(self, name)
   5275 
   5276     def __setattr__(self, name: str, value) -> None:

AttributeError: 'Series' object has no attribute 'sequence'
```

If I change the column name to 'text', then the dataloaders works. 

```python
df.rename({'sequence': 'text'}, axis='columns', inplace=True)
```

It looks that the columns name must be 'text' and can't be others. Could you help to fix this bug? Thanks.

**Comment by muellerzr** [comment]
That is not a bug. `TextBlock` has a `res_col_name` parameter, and this is where your tokenized text lives. This can be closed.

https://forums.fast.ai/t/issue-with-textblock-from-df-dataloaders-only-accepting-one-column-name/77467/2

**Comment by sky1ove** [comment]
I see! Thank you Muellerzr! @muellerzr

**Comment by stevegoldman** [comment]
I just made a pull request adding a couple of sentences to the tutorial about this behavior.

https://github.com/fastai/fastai/pull/2860
