### ISSUE TITLE
CPU: Unable to load a (tabular) learner with load_learner()

### ISSUE THREAD

**Issue by paulhart** [fastai/fastai#2861]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

**Describe the bug**
Unable to load a (tabular) learner through the load_learner() function, even within the same python environment.

**To Reproduce**
0. Provision a CPU-based environment
1. Train a tabular learner
2. Save learner using TabularLearner.save()
3. Attempt to reload the same learner with load_learner()

**Expected behavior**
Learner should be loaded into memory and ready to use

**Error with full stack trace**

Place between these lines with triple backticks:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-5044af9f41a5> in <module>
----> 1 learn = load_learner(path/'network.pth')

/opt/conda/envs/fastai/lib/python3.8/site-packages/fastai/learner.py in load_learner(fname, cpu)
    539     res = torch.load(fname, map_location='cpu' if cpu else None)
    540     if hasattr(res, 'to_fp32'): res = res.to_fp32()
--> 541     if cpu: res.dls.cpu()
    542     return res
    543 

AttributeError: 'dict' object has no attribute 'dls'
```

**Additional context**
I've used the tutorials in https://github.com/fastai/fastbook/blob/master/09_tabular.ipynb as guidance in my code. I confirmed that the current learner.py here has the same line 541.

**Comment by muellerzr** [comment]
`load_learner` expects an output from `learn.export`. Not `learn.save`

**Comment by paulhart** [comment]
> `load_learner` expects an output from `learn.export`. Not `learn.save`

Thanks for that - I guess it was an understanding gap on my part when reading the tutorial materials then (I didn't see an attempt to load the learner again in that page of the tutorials, and haven't looked at subsequent pages to see if they do).

Will close.
