### ISSUE TITLE
SyntaxError: import * only allowed at module level

### ISSUE THREAD

**Issue by actcod01** [fastai/fastai#2864]
import * fails in python script.
____

Versions used:
> python 3.6
> fastai 1.x

**Que :** How to use fastai model training and prediction in python script (Without jupyter interactive mode)?

Thanks,

**Comment by marii-moe** [comment]
@actcod01  I notice you are using fastai version 1. I think that code is now found here: https://github.com/fastai/fastai1

**Comment by jph00** [comment]
Please use forums.fast.ai for help. GitHub issues is for reporting confirmed bugs. If you're not sure if what you're seeing is a bug, or are not sure how to confirm it, ask for help on the forums. When posting on the forums, we have some suggestions to help you get your problem resolved:

https://forums.fast.ai/t/how-to-ask-for-help/10421
