### ISSUE TITLE
AttributeError: 'TabularLearner' object has no attribute 'fit_one_cycle'

### ISSUE THREAD

**Issue by fengdai1234** [fastai/fastai#2869]
I am trying to create a dataloader from TabularPandas. when I try to fit_one_cycle from the tabular learner,
it give me this error. Anybody can help me?

        splits = RandomSplitter(valid_pct=0.2)(range_of(train_all))
        to = TabularPandas(train_all, procs=[Categorify, FillMissing,Normalize],
                   cat_names = cat_cols,
                   cont_names = cont_cols,
                   y_names='binded',
                   splits=splits)
        
        dls = to.dataloaders(bs=64)
        # dls.show_batch()
        learn = tabular_learner(dls, metrics=accuracy_score)
        learn.fit_one_cycle(1)

Thanks

**Comment by muellerzr** [comment]
What are your imports?

**Comment by fengdai1234** [comment]
those are all the fastai library I imports:
from fastai.tabular import *
from fastai.tabular.core import *
from fastai.tabular.data import TabularDataLoaders
from fastai.tabular.learner import tabular_learner
from fastai.data.transforms import *
from fastai.data.block import TransformBlock, CategoryBlock
from fastai.losses import CrossEntropyLossFlat
from fastai.metrics import *
from fastcore.utils import *

**Comment by muellerzr** [comment]
Those are in `callback`, (ie `from fastai.callback.all import *` however when importing from the library generally you should do `from fastai.tabular.all import *`

**Comment by fengdai1234** [comment]
Thanks so much! That works for me.
