### ISSUE TITLE
fastai QRNN vs PyTorch LSTM

### ISSUE THREAD

**Issue by listener17** [fastai/fastai#2871]
I think fastai QRNN is expected to be a drop-in replacement for PyTorch LSTM or GRU. Right?
If yes, I think it will be good to keep same defaults and align them a bit?

For example LSTM/GRU in pytorch has as default: batch_first = False (in fastai it is True)

Also, is it possible to change n_layers to num_layers?

BTW: is bias = True in QRNN?

**Comment by jph00** [comment]
It's designed to be compatible with `AWD_LSTM`, not PyTorch.

It does have bias.
