### ISSUE TITLE
Where are DataBunch?

### ISSUE THREAD

**Issue by Roodgerr** [fastai/fastai#2873]
Please don't ask for help here. [Use the forums](https://forums.fast.ai)
![image](https://user-images.githubusercontent.com/69750481/95459713-756c4280-098d-11eb-9d7c-59f4036a0d16.png)
![image](https://user-images.githubusercontent.com/69750481/95459811-92087a80-098d-11eb-9590-50a0ea3d034e.png)

**Comment by vishalbakshi** [comment]
What version of fastai are you running? I believe the `DataBunch` is [a part of `fastai1`](https://github.com/fastai/fastai1/blob/bcef12e95405655481bb309761f8c552b51b2bd2/fastai/basic_data.py#L84) but no longer part of `fastai`.

**Comment by jasmcaus** [comment]
`DataBunch` is indeed a part of [fastai1]{https://fastai1.fast.ai/basic_data.html}
