### ISSUE TITLE
Documentation for Show_Images broken

### ISSUE THREAD

**Issue by ikeaney** [fastai/fastai#2876]
Be sure you've searched [the forums](https://forums.fast.ai) for the error message you received. Also, unless you're an experienced fastai developer, first ask on the forums to see if someone else has seen a similar issue already and knows how to solve it. **Only file a bug report here when you're quite confident it's not an issue with your local setup.**

**Please see [this model example](https://github.com/fastai/fastai/issues/487) of how to fill out an issue correctly.  Please try to emulate that example as appropriate when opening an issue.**

Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES /

**Describe the bug**
When I call doc(show_images) and click on the link the URL returned is broken (https://docs.fast.ai/torch.core#show_images)

**To Reproduce**

**Expected behavior**

**Error with full stack trace**

Place between these lines with triple backticks:

```
```

**Additional context**

**Comment by marii-moe** [comment]
I think this is the same as https://github.com/fastai/fastai/issues/2872

**Comment by hamelsmu** [comment]
@marii-moe where are you finding this link?  I'm seeing this link https://docs.fast.ai/torch_core#show_images show properly.

**Comment by muellerzr** [comment]
@hamelsmu can reproduce:
```python
!pip install fastai --upgrade
!pip install nbdev

from fastai.vision.all import *
doc(show_images)
```
Clicking the `Show in docs` url points to https://docs.fast.ai/torch.core#show_images
