### ISSUE TITLE
NameError: name 'CallbackHandler' is not defined

### ISSUE THREAD

**Issue by jpandeinge** [fastai/fastai#2877]
how to fix the error "NameError: name 'CallbackHandler' is not defined" on ubuntu 20.04?

**Comment by thesighsrikar** [comment]
Hello, 
Could you please elaborate on the issue so that I can reproduce this on my end? 
Much thanks in advance :) 

Srikar

**Comment by thesighsrikar** [comment]
> how to fix the error "NameError: name 'CallbackHandler' is not defined" on ubuntu 20.04?

Hello,
Could you please elaborate on the issue so that I can reproduce this on my end?
Much thanks in advance :)

Srikar

**Comment by jph00** [comment]
Please use forums.fast.ai for help
