### ISSUE TITLE
Tokenizing from folder taking more than 4 hours

### ISSUE THREAD

**Issue by sidwa** [fastai/fastai#2880]
Be sure you've searched [the forums](https://forums.fast.ai) for the error message you received. Also, unless you're an experienced fastai developer, first ask on the forums to see if someone else has seen a similar issue already and knows how to solve it. **Only file a bug report here when you're quite confident it's not an issue with your local setup.**

**Please see [this model example](https://github.com/fastai/fastai/issues/487) of how to fill out an issue correctly.  Please try to emulate that example as appropriate when opening an issue.**

Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES 

**Describe the bug**
I have been trying to load MT_ENG_FRA from the URLs class. The dataset gets downloaded successfully, however when I try to create a datablock it get stuck for hours. I have let it run for >6 hours on colab and multiple runs on 4-5 hours locally. The issue definitely seems to be in the Tokenizer.from_folder since it's been > 4 hours since I have started it and the Tokenizing is still not done. I'm Tokenizing only the english file as of now which is ~3.25 GB.

**To Reproduce**
```
# imports used for colab
#!pip install -Uqq fastbook
#import fastbook
#fastbook.setup_book()
#from fastbook import *

from fastai.data.all import *
from fastai.text.all import *
```
Download the data
```
nmt_path = untar_data(URLs.MT_ENG_FRA)
nmt_path.ls()
```
Move the english and french files to separate folders
```
en_dir = nmt_path/"en"
fr_dir = nmt_path/"fr"
if not en_dir.exists():
    en_dir.mkdir()
    shutil.move(nmt_path/"giga-fren.release2.fixed.en", nmt_path/"en"/"giga-fren.release2.fixed.en")
if not fr_dir.exists():
    fr_dir.mkdir()
    shutil.move(nmt_path/"giga-fren.release2.fixed.fr", nmt_path/"fr"/"giga-fren.release2.fixed.fr")

print(en_dir.ls())
print(fr_dir.ls())
```
Tokenize the english file (getting stuck here)
```
tok = Tokenizer.from_folder(en_dir)
```
**Expected behavior**
Tokenizing getting complete in at most 2 hours.

**Comment by ARMATAV** [comment]
Same here.

![Screen Shot 2020-10-15 at 10 47 18 PM](https://user-images.githubusercontent.com/2433203/96217946-880bec00-0f38-11eb-8304-0c7e6e895ae1.png)

**Comment by jph00** [comment]
@sidwa I copied and pasted that into a notebook, and it worked for me. So maybe a data problem or you're not on Linux. I'd suggest asking on the forums. If you can find a sequence of steps that reliably reproduces the issue on a fresh install, please reopen this issue.
