### ISSUE TITLE
Hanging DataLoaders when working with a large dataset on Paperspace

### ISSUE THREAD

**Issue by ARMATAV** [fastai/fastai#2882]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

![Screen Shot 2020-10-15 at 6 09 54 PM](https://user-images.githubusercontent.com/2433203/96201526-a6122600-0f11-11eb-9369-0734bd56a524.png)

Hey guys, I have a large dataset of 400k text documents that I'm doing a language model on while reading Chapter 10 of the book.

The DataLoader setup process always seems to hang at some point. When I use `top` at the beginning of loading, it shows 6-8 python processes. When I use `top` after the freeze it says there are some number of 'zombie processes' which I'm assuming have thrown an error but are not terminating.

Is there a correct way to debug this sort of thing, something like a `try/catch` but for items in the `DataLoader`? Currently I can't get a stacktrace since it never exits. Maybe the tokenizer is hitting an error?

https://forums.fast.ai/t/dataloader-hanging-while-training-a-big-dataset-on-paperspace/80513

**Comment by ARMATAV** [comment]
I think also this may just be a Paperspace thing where it's running out of memory, but I'm not getting a `cuda out of memory` style error for this one.

**Comment by ARMATAV** [comment]
Switching out the tokenizer gets you a hung notebook.

![Screen Shot 2020-10-15 at 7 53 58 PM](https://user-images.githubusercontent.com/2433203/96207589-69016000-0f20-11eb-9a25-83e88fc16515.png)

![Screen Shot 2020-10-15 at 7 55 19 PM](https://user-images.githubusercontent.com/2433203/96207596-6bfc5080-0f20-11eb-96f2-cc646751adf6.png)

**Comment by ARMATAV** [comment]
And interestingly it goes from processing 200 items per second to doing around 3 for what seems to be no reason.

![Screen Shot 2020-10-15 at 10 47 18 PM](https://user-images.githubusercontent.com/2433203/96217890-6ad71d80-0f38-11eb-8fea-7d2e5a4256c4.png)

**Comment by ARMATAV** [comment]
And then the kernel dies.

![Screen Shot 2020-10-15 at 10 51 08 PM](https://user-images.githubusercontent.com/2433203/96218140-fa7ccc00-0f38-11eb-9c7d-632172b82ad6.png)

**Comment by ARMATAV** [comment]
Yeah - so if you do the Tokenization on a smaller dataset it works out fine - but you have to do it outside of the DataBlock - otherwise you hit `Unhashable type: L`.

**Comment by jph00** [comment]
Sorry we're not able to provide help thru gh issues
