### ISSUE TITLE
old docs are not accessible, for instance: https://docs.fast.ai/train.html#fit_one_cycle

### ISSUE THREAD

**Issue by disha-dp** [fastai/fastai#2883]
Be sure you've searched [the forums](https://forums.fast.ai) for the error message you received. Also, unless you're an experienced fastai developer, first ask on the forums to see if someone else has seen a similar issue already and knows how to solve it. **Only file a bug report here when you're quite confident it's not an issue with your local setup.**

**Please see [this model example](https://github.com/fastai/fastai/issues/487) of how to fill out an issue correctly.  Please try to emulate that example as appropriate when opening an issue.**

Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES / NO

**Describe the bug**

**To Reproduce**
1. 

**Expected behavior**

**Error with full stack trace**

Place between these lines with triple backticks:

```
```

**Additional context**

**Comment by TannerGilbert** [comment]
The docs for FastAI v1 have been moved to https://fastai1.fast.ai/. So if you want to access the fit_one_cycle docs you need to navigate to https://fastai1.fast.ai/train.html#fit_one_cycle
