### ISSUE TITLE
do inference on the batch data (for text classifier)

### ISSUE THREAD

**Issue by p9anand** [fastai/fastai#2885]
Below are steps i followed.
`import joblib
vocab = joblib.load('vocab')
tb = TextBlock.from_df('text', vocab=vocab)
imdb_clas = DataBlock(
    blocks=tb,
    get_x=ColReader('text')
)

dls = imdb_clas.dataloaders(df, bs=64)`

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/7848315/96257638-55193500-0fd8-11eb-87e6-ae1d9ba557da.png">
above image was some samples.
learn = load_learner('without_language_model.pkl')
learn.dls.test_dl = dls
pp = learn.get_preds(dl=dls)

Can anyone please guide where i'm doing wrong.
i'm getting following error:
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/7848315/96257783-9f021b00-0fd8-11eb-9bae-99bfba85e380.png">

**Comment by jph00** [comment]
Please use forums.fast.ai for help
