### ISSUE TITLE
incorrect kwargs delegates in `DcmDataset.show`

### ISSUE THREAD

**Issue by kessido** [fastai/fastai#2887]
Hey, I notices the following code error which I believe is cause be thinking that delegates accept *args `(signature is to=None, keep=None but=None)`:
`@delegates(show_image, show_images)`

https://github.com/fastai/fastai/blob/39b0cd49fb8176dd28211d1d21adb9e264926447/fastai/medical/imaging.py#L174

**Comment by jph00** [comment]
Thanks for letting us know.
