### ISSUE TITLE
clip_remove_empty should remove bboxes with area 0

### ISSUE THREAD

**Issue by ababino** [fastai/fastai#2893]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

**Describe the bug**
The function `clip_remove_empty` should remove bounding boxes with area 0. In the current implementation, it only removes boxes with negative areas.

**To Reproduce**
Run the following test:
```python
from fastai.vision.all import *

bb = tensor([[-2,-0.5,0.5,1.5], [-0.5,-0.5,0.5,0.5], [1,0.5,0.5,0.75], [-0.5,-0.5,0.5,0.5], [-2, -0.5, -1.5, 0.5]])
bb,lbl = clip_remove_empty(bb, tensor([1,2,3,2,5]))
test_eq(bb, tensor([[-1,-0.5,0.5,1.], [-0.5,-0.5,0.5,0.5], [-0.5,-0.5,0.5,0.5]]))
test_eq(lbl, tensor([1,2,2]))
```

**Expected behavior**
`clip_remove_empty` should remove bounding boxes with area 0.

**Additional context**
If you crop an image, and a bounding box lays outside the cropped area, `clip_remove_empty` will clip the bounding box to (-1,1) and the bounding box will have area 0. The current implementation only removes bounding boxes with negative areas. Simply changing the `<` by a `<=` in the following line of code fixes the issue:
```python
empty = ((bbox[...,2] - bbox[...,0])*(bbox[...,3] - bbox[...,1]) <= 0.)
```
[This is the original line of code](https://github.com/fastai/fastai/blob/13bf45874516a78068c671d0f1e0618a888457ed/fastai/vision/data.py#L27)

This issue only happens if you are working with rectangular images and `Resize` crops a border of the image.

If you agree, I can make a PR with this change and the new test.

**Comment by jph00** [comment]
A PR would be most welcome!
