### ISSUE TITLE
Docs Menu Bug

### ISSUE THREAD

**Issue by Isaac-Flath** [fastai/fastai#2895]
**Describe the bug**
On https://docs.fast.ai/, there are tabs on the left menu.  On a couple of pages, some of the menu sections disappear.  

One of those is "Integrations".  If you Expand Integrations and go to https://docs.fast.ai/callback.wandb, the Integrations section disappears from the menu and so you cannot navigate from that page to view the other Integrations.  This seems to be the case for that page as well as https://docs.fast.ai/callback.neptune, though all the other pages seem to work as expected leaving the menu intact.  For example at https://docs.fast.ai/callback.tensorboard the Integration menu is still present as I think it should be

**To Reproduce**
1. Got to https://docs.fast.ai/
1. Expand Integration and navigate into https://docs.fast.ai/callback.wandb
1. Look for "Integration" section in left menu and see it is not there.

**Expected behavior**
The Navigation Menu should have all sections at all times.  Or at least have consistent behavior across all links.

@jph00

**Comment by jph00** [comment]
Thanks @Isaac-Flath - we're rewriting nbdev from scratch so this problem will fix itself. So I'll close this now. cc @hamelsmu
