### ISSUE TITLE
ImageDataLoaders num_workers >0 → RuntimeError: Cannot pickle CUDA storage; try pickling a CUDA tensor instead

### ISSUE THREAD

**Issue by dreamflasher** [fastai/fastai#2899]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

**Describe the bug**
When using a `DataLoaders` with num_workers>0, training raises `RuntimeError: Cannot pickle CUDA storage; try pickling a CUDA tensor instead`

**To Reproduce**
```
from fastai.vision.data import ImageDataLoaders
from fastai.vision.learner import cnn_learner
from fastai.vision.augment import aug_transforms
import pandas as pd
from fastai import vision

df = pd.read_csv("/data/cats/labels.csv")

data = ImageDataLoaders.from_df(df=df, path="/", label_col=1, bs=100, batch_tfms=[
    *aug_transforms(size=224)], valid_pct=0.2, num_workers=1)
learn = cnn_learner(data, getattr(vision.models, "resnet18"))
learn.fit_one_cycle(10)
```

**Expected behavior**
There shouldn't be an exception, as there is none when using `num_workers=0`.

**Error with full stack trace**

Place between these lines with triple backticks:

```
Traceback (most recent call last):
  File "/home/df/git/mitl/mitlmodels/model.py", line 426, in train
    pass  # This comment shows up if we ran into a callback error
  File "/home/df/git/mitl/mitlmodels/ml_utils.py", line 63, in __exit__
    raise exc_type(exc_val).with_traceback(exc_tb) from None
  File "/home/df/git/mitl/mitlmodels/model.py", line 401, in train
    learn.fit_one_cycle(max_epochs, slice(lr_init, lr_init * 30), wd=wd,
  File "/home/df/.local/lib/python3.8/site-packages/fastcore/logargs.py", line 56, in _f
    return inst if to_return else f(*args, **kwargs)
  File "/home/df/.local/lib/python3.8/site-packages/fastai/callback/schedule.py", line 113, in fit_one_cycle
    self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
  File "/home/df/.local/lib/python3.8/site-packages/fastcore/logargs.py", line 56, in _f
    return inst if to_return else f(*args, **kwargs)
  File "/home/df/.local/lib/python3.8/site-packages/fastai/learner.py", line 207, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "/home/df/.local/lib/python3.8/site-packages/fastai/learner.py", line 155, in _with_events
    try:       self(f'before_{event_type}')       ;f()
  File "/home/df/.local/lib/python3.8/site-packages/fastai/learner.py", line 197, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "/home/df/.local/lib/python3.8/site-packages/fastai/learner.py", line 155, in _with_events
    try:       self(f'before_{event_type}')       ;f()
  File "/home/df/.local/lib/python3.8/site-packages/fastai/learner.py", line 191, in _do_epoch
    self._do_epoch_train()
  File "/home/df/.local/lib/python3.8/site-packages/fastai/learner.py", line 183, in _do_epoch_train
    self._with_events(self.all_batches, 'train', CancelTrainException)
  File "/home/df/.local/lib/python3.8/site-packages/fastai/learner.py", line 155, in _with_events
    try:       self(f'before_{event_type}')       ;f()
  File "/home/df/.local/lib/python3.8/site-packages/fastai/learner.py", line 161, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)
  File "/home/df/.local/lib/python3.8/site-packages/fastai/data/load.py", line 102, in __iter__
    for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
  File "/home/df/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 737, in __init__
    w.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
```

**Comment by dreamflasher** [comment]
Solved by setting `set_start_method('fork', force=True)` – which is already set in the fastai library (maybe it's changed by a library that I import). But now the issue is that I don't see the progress bar anymore.

**Comment by jph00** [comment]
I'm not seeing this - perhaps you're running on some OS other than Linux? If you can repro this on Linux with no other libs imported, please reopen with the details.

**Comment by PalaashAgrawal** [comment]
I see the same issue.
I'm using google colab, and mostly all fastai defaults.
the problem arises during learn.fit()

> 
> `/usr/local/lib/python3.6/dist-packages/fastcore/logargs.py in _f(*args, **kwargs)
>      54         init_args.update(log)
>      55         setattr(inst, 'init_args', init_args)
> ---> 56         return inst if to_return else f(*args, **kwargs)
>      57     return _f
> 
> /usr/local/lib/python3.6/dist-packages/fastai/callback/schedule.py in fit_one_cycle(self, n_epoch, lr_max, div, div_final, pct_start, wd, moms, cbs, reset_opt)
>     111     scheds = {'lr': combined_cos(pct_start, lr_max/div, lr_max, lr_max/div_final),
>     112               'mom': combined_cos(pct_start, *(self.moms if moms is None else moms))}
> --> 113     self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
>     114 
>     115 # Cell
> 
> /usr/local/lib/python3.6/dist-packages/fastcore/logargs.py in _f(*args, **kwargs)
>      54         init_args.update(log)
>      55         setattr(inst, 'init_args', init_args)
> ---> 56         return inst if to_return else f(*args, **kwargs)
>      57     return _f
> 
> /usr/local/lib/python3.6/dist-packages/fastai/learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)
>     205             self.opt.set_hypers(lr=self.lr if lr is None else lr)
>     206             self.n_epoch = n_epoch
> --> 207             self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
>     208 
>     209     def _end_cleanup(self): self.dl,self.xb,self.yb,self.pred,self.loss = None,(None,),(None,),None,None
> 
> /usr/local/lib/python3.6/dist-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
>     153 
>     154     def _with_events(self, f, event_type, ex, final=noop):
> --> 155         try:       self(f'before_{event_type}')       ;f()
>     156         except ex: self(f'after_cancel_{event_type}')
>     157         finally:   self(f'after_{event_type}')        ;final()
> 
> /usr/local/lib/python3.6/dist-packages/fastai/learner.py in _do_fit(self)
>     195         for epoch in range(self.n_epoch):
>     196             self.epoch=epoch
> --> 197             self._with_events(self._do_epoch, 'epoch', CancelEpochException)
>     198 
>     199     @log_args(but='cbs')
> 
> /usr/local/lib/python3.6/dist-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
>     153 
>     154     def _with_events(self, f, event_type, ex, final=noop):
> --> 155         try:       self(f'before_{event_type}')       ;f()
>     156         except ex: self(f'after_cancel_{event_type}')
>     157         finally:   self(f'after_{event_type}')        ;final()
> 
> /usr/local/lib/python3.6/dist-packages/fastai/learner.py in _do_epoch(self)
>     189 
>     190     def _do_epoch(self):
> --> 191         self._do_epoch_train()
>     192         self._do_epoch_validate()
>     193 
> 
> /usr/local/lib/python3.6/dist-packages/fastai/learner.py in _do_epoch_train(self)
>     181     def _do_epoch_train(self):
>     182         self.dl = self.dls.train
> --> 183         self._with_events(self.all_batches, 'train', CancelTrainException)
>     184 
>     185     def _do_epoch_validate(self, ds_idx=1, dl=None):
> 
> /usr/local/lib/python3.6/dist-packages/fastai/learner.py in _with_events(self, f, event_type, ex, final)
>     153 
>     154     def _with_events(self, f, event_type, ex, final=noop):
> --> 155         try:       self(f'before_{event_type}')       ;f()
>     156         except ex: self(f'after_cancel_{event_type}')
>     157         finally:   self(f'after_{event_type}')        ;final()
> 
> /usr/local/lib/python3.6/dist-packages/fastai/learner.py in all_batches(self)
>     159     def all_batches(self):
>     160         self.n_iter = len(self.dl)
> --> 161         for o in enumerate(self.dl): self.one_batch(*o)
>     162 
>     163     def _do_one_batch(self):
> 
> /usr/local/lib/python3.6/dist-packages/fastai/data/load.py in __iter__(self)
>     100         self.before_iter()
>     101         self.__idxs=self.get_idxs() # called in context of main process (not workers/subprocesses)
> --> 102         for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
>     103             if self.device is not None: b = to_device(b, self.device)
>     104             yield self.after_batch(b)
> 
> /usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py in __init__(self, loader)
>     735             #     before it starts, and __del__ tries to join but will get:
>     736             #     AssertionError: can only join a started process.
> --> 737             w.start()
>     738             self._index_queues.append(index_queue)
>     739             self._workers.append(w)
> 
> /usr/lib/python3.6/multiprocessing/process.py in start(self)
>     103                'daemonic processes are not allowed to have children'
>     104         _cleanup()
> --> 105         self._popen = self._Popen(self)
>     106         self._sentinel = self._popen.sentinel
>     107         # Avoid a refcycle if the target function holds an indirect
> 
> /usr/lib/python3.6/multiprocessing/context.py in _Popen(process_obj)
>     221     @staticmethod
>     222     def _Popen(process_obj):
> --> 223         return _default_context.get_context().Process._Popen(process_obj)
>     224 
>     225 class DefaultContext(BaseContext):
> 
> /usr/lib/python3.6/multiprocessing/context.py in _Popen(process_obj)
>     282         def _Popen(process_obj):
>     283             from .popen_spawn_posix import Popen
> --> 284             return Popen(process_obj)
>     285 
>     286     class ForkServerProcess(process.BaseProcess):
> 
> /usr/lib/python3.6/multiprocessing/popen_spawn_posix.py in __init__(self, process_obj)
>      30     def __init__(self, process_obj):
>      31         self._fds = []
> ---> 32         super().__init__(process_obj)
>      33 
>      34     def duplicate_for_child(self, fd):
> 
> /usr/lib/python3.6/multiprocessing/popen_fork.py in __init__(self, process_obj)
>      17         util._flush_std_streams()
>      18         self.returncode = None
> ---> 19         self._launch(process_obj)
>      20 
>      21     def duplicate_for_child(self, fd):
> 
> /usr/lib/python3.6/multiprocessing/popen_spawn_posix.py in _launch(self, process_obj)
>      45         try:
>      46             reduction.dump(prep_data, fp)
> ---> 47             reduction.dump(process_obj, fp)
>      48         finally:
>      49             set_spawning_popen(None)
> 
> /usr/lib/python3.6/multiprocessing/reduction.py in dump(obj, file, protocol)
>      58 def dump(obj, file, protocol=None):
>      59     '''Replacement for pickle.dump() using ForkingPickler.'''
> ---> 60     ForkingPickler(file, protocol).dump(obj)
>      61 
>      62 #
> 
> /usr/local/lib/python3.6/dist-packages/torch/multiprocessing/reductions.py in reduce_storage(storage)
>     308     from . import get_sharing_strategy
>     309     if storage.is_cuda:
> --> 310         raise RuntimeError("Cannot pickle CUDA storage; try pickling a CUDA tensor instead")
>     311     elif get_sharing_strategy() == 'file_system':
>     312         metadata = storage._share_filename_()
> 
> RuntimeError: Cannot pickle CUDA storage; try pickling a CUDA tensor instead`

**Comment by jph00** [comment]
@PalaashAgrawal to be able to help we need a the code necessary to reproduce the problem, or a link to your colab notebook.

**Comment by dreamflasher** [comment]
> 
> 
> I'm not seeing this - perhaps you're running on some OS other than Linux? If you can repro this on Linux with no other libs imported, please reopen with the details.

I am running on Linux, with no other libs.

**Comment by jph00** [comment]
Thanks for letting me know. Can you please provide a full reproducible example (e.g. a colab notebook, or a standalone script) so we can see the problem? Then we should be able to fix it reasonably quickly.

**Comment by PalaashAgrawal** [comment]
On it. I actually came across this issue on a custom dataset, so i guess my colab notebook won't run on your system(because the data comes from my Google drive). So I'll try to reproduce this error on a generic tensor dataset, or another data, and open a new issue when i do. Thanks for replying!

**Comment by jph00** [comment]
Many thanks! :)

**Comment by mszhanyi** [comment]
One script to reproduce similar issue.
It should be related to DataBlocks and process start method.
@jph00 
```
from fastai.vision.all import *
from fastai.data.all import *

def get_data(url, presize, resize):
    path = untar_data(url)
    return DataBlock(
        blocks=(ImageBlock, CategoryBlock), get_items=get_image_files, 
        splitter=GrandparentSplitter(valid_name='val'),
        get_y=parent_label, item_tfms=Resize(presize),
        batch_tfms=[*aug_transforms(min_scale=0.5, size=resize),
                    Normalize.from_stats(*imagenet_stats)],
    ).dataloaders(path, bs=128)
    
if __name__ == "__main__":
    # uncomment it to reproduce in Linux
    #torch.multiprocessing.set_start_method('spawn') 
    
    # the imagedataloders works
    #dls = ImageDataLoaders.from_folder(untar_data(URLs.IMAGENETTE_160), valid='val', 
    #    item_tfms=RandomResizedCrop(128, min_scale=0.35), batch_tfms=Normalize.from_stats(*imagenet_stats))
    
    # throws exception. 
    dls = get_data(URLs.IMAGENETTE_160, 160, 128)
    print(L(dls.train))
```

**Comment by jph00** [comment]
Reopening this now that we're supporting Windows.

**Comment by mszhanyi** [comment]
I got it.
it works by changing
`batch_tfms=[*aug_transforms(min_scale=0.5, size=128), Normalize.from_stats(*imagenet_stats)]`
to 
`batch_tfms=aug_transforms(min_scale=0.5, size=128).append(Normalize.from_stats(*imagenet_stats))`

* dereference looks incompatible with pickle serialization

**Comment by jph00** [comment]
Huh that's odd - I have no idea why that is! Great find

**Comment by mszhanyi** [comment]
Sorry, It has nothing with dereference.
It has something with the function aug_transforms.
same exception occurs with `batch_tfms=aug_transforms(min_scale=0.5, size=128)`
append() returns None.
It can be reproduced in Linux by setting start_method as spawn.

**Comment by mszhanyi** [comment]
[
[imgdl.txt](https://github.com/fastai/fastai/files/6069474/imgdl.txt)

](url)

**Comment by mszhanyi** [comment]
[Uploading imgdl.txt…]()

**Comment by mszhanyi** [comment]
The root cause is that pickle doesn't support serialize cuda variable.
Let's start with a very simple script, the exception could be reproduced easily on Windows and Linux.
`
import torch
from multiprocessing import Process

my_tensor = torch.tensor([1.0]).cuda()
def proc_info(my_obj):
    import os
    print(os.getpid())
    print(obj.__dict__)

if __name__ == "__main__":
   mp.set_start_method('spawn')
   p = Process(target=proc_info, args=(my_tensor,))
   p.start()
   p.join()
`

**Comment by mszhanyi** [comment]
For fastai, it could be reproduced with the below snippet.

x is already a cuda variable.
https://github.com/fastai/fastai/blob/87827a10c946ea024fb09ecaf00073395e4d950d/fastai/vision/augment.py#L464

```
from fastai.data.load import *
from fastai.vision.all import *
from fastai.data.all import *

def proc_info(dls):
    import os
    print(os.getpid())
    print("dls -------")
    print(dls)
    print("/dls ------")

if __name__ == "__main__":
    multiprocessing.set_start_method('spawn')
    print("start main ...")

    path = untar_data(URLs.IMAGENETTE_160)
    tkw = {'size': None, 'mode': 'bilinear', 'pad_mode': 'reflection', 'batch': False, 'align_corners': True}
    flip_1 = Flip(p=0.5, **tkw)

    dls = ImageDataLoaders.from_folder(path, valid='val', 
        item_tfms=RandomResizedCrop(128, min_scale=0.35), batch_tfms=flip_1)

    proc_info(dls)

    p = Process(target=proc_info, args=(dls,))
    p.start()
    p.join()
```

I think it should be caused by 
https://github.com/fastai/fastai/blob/45376f13df04ddf72749be25ae8a6dff35859f68/fastai/data/core.py#L212

the call stack for training should be like the below image
![image](https://user-images.githubusercontent.com/16190118/109803150-a9f1db00-7c5b-11eb-85cf-045b04fe5180.png)

**Comment by mszhanyi** [comment]
For spawn, I think we should copy data from cpu to gpu in workers.

**Comment by jph00** [comment]
@mszhanyi many thanks for the debugging - sorry for the slow response, we've been moving to Australia so a bit overwhelmed by that!

Is `Flip` the only transform that's causing this problem? Have you tried including everything except `Flip` to see if it works?

Regarding "we should copy data from cpu to gpu in each workers": how are you thinking we might implement that? Any sample code you could show?

**Comment by mszhanyi** [comment]
NO，`Flip` isn't the only transform that's causing this problem. 
Any transform causes this problem.
![image](https://user-images.githubusercontent.com/16190118/110270358-98645680-8000-11eb-9eee-b7b6abb08666.png)
I think it's caused by
https://github.com/fastai/fastai/blob/45376f13df04ddf72749be25ae8a6dff35859f68/fastai/data/core.py#L119-L123

The sample code is below, the issue can be reproduced both on Windows and Linux if the process start method is spawn
```
from fastai.torch_basics import *
from fastai.data.load import *
from fastai.vision.all import *
from fastai.data.all import *
        
def proc_info(dls):
    import os
    print(os.getpid())
    print("dls -------")
    print(dls)
    print("/dls ------")

if __name__ == "__main__":
    multiprocessing.set_start_method('spawn')
    print("start main ...")

    dls = ImageDataLoaders.from_folder(path, valid='val', 
        item_tfms=RandomResizedCrop(128, min_scale=0.35), batch_tfms=aug_transforms(min_scale=0.5, size=128))

    proc_info(dls)

    p = Process(target=proc_info, args=(dls,))
    p.start()
    p.join()
```

**Comment by mszhanyi** [comment]
@jph00 
I find a good post about cuda and multiple workers in Dataloader.
https://discuss.pytorch.org/t/cuda-initialization-error-when-dataloader-with-cuda-tensor/43390/2

**Comment by mszhanyi** [comment]
@jph00 , one more interesting thing. 

https://github.com/fastai/fastai/blob/00d88637cd7f804da55473b7c3c31aba4fecba1c/fastai/data/core.py#L218-L221

if we change the fastai\data\core.py as below, and run the sample script.
```
# no exception
dl = dl_type(self.subset(0), **merge(kwargs,def_kwargs, dl_kwargs[0]))
dls = [dl]
return self._dbunch_type(*dls, path=path, device=device)
```


```
# has exception of Cannot pickle CUDA storage
dl = dl_type(self.subset(0), **merge(kwargs,def_kwargs, dl_kwargs[0]))
dl2 = dl.new(self.subset(0), **merge(kwargs,def_kwargs, dl_kwargs[0]))
dls = [dl2]
return self._dbunch_type(*dls, path=path, device=device)
```

could you give some hint sine I haven't understand fastai foundation libs very well?

**Comment by davidgilbertson** [comment]
I'm getting this error, it seems to be triggered by `lr_find` in `fastai 2.7.9`

I have the very uncool setup of Windows 11 and vanilla Python 3.10 (just a script, no Jupyter)

```py
from fastai.callback.schedule import slide, valley
from fastai.metrics import error_rate
from fastai.vision.augment import aug_transforms, Resize
from fastai.vision.data import ImageDataLoaders
from fastai.vision.learner import vision_learner

if __name__ == "__main__":
    dls = ImageDataLoaders.from_folder(
        "paddy-disease-classification/train_images/bacterial_leaf_blight",
        valid_pct=0.2,
        item_tfms=Resize(480, method="squish"),
        batch_tfms=aug_transforms(size=192, min_scale=0.75),
        bs=64,
    )

    learn = vision_learner(dls, "resnet26d", metrics=error_rate, path=".").to_fp16()
    learn.lr_find(suggest_funcs=(valley, slide))
```

Full error:
```
Traceback (most recent call last):-------------------------------------| 0.00% [0/6 00:00<?]
  File "C:\Users\david\py\libs\fastbook\tmp.py", line 40, in <module>
    learn.lr_find(suggest_funcs=(valley, slide))
  File "C:\Users\david\py\libs\fastbook\venv\lib\site-packages\fastai\callback\schedule.py", line 293, in lr_find
    with self.no_logging(): self.fit(n_epoch, cbs=cb)
  File "C:\Users\david\py\libs\fastbook\venv\lib\site-packages\fastai\learner.py", line 256, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "C:\Users\david\py\libs\fastbook\venv\lib\site-packages\fastai\learner.py", line 193, in _with_events
    try: self(f'before_{event_type}');  f()
  File "C:\Users\david\py\libs\fastbook\venv\lib\site-packages\fastai\learner.py", line 245, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "C:\Users\david\py\libs\fastbook\venv\lib\site-packages\fastai\learner.py", line 193, in _with_events
    try: self(f'before_{event_type}');  f()
  File "C:\Users\david\py\libs\fastbook\venv\lib\site-packages\fastai\learner.py", line 239, in _do_epoch
    self._do_epoch_train()
  File "C:\Users\david\py\libs\fastbook\venv\lib\site-packages\fastai\learner.py", line 231, in _do_epoch_train
    self._with_events(self.all_batches, 'train', CancelTrainException)
  File "C:\Users\david\py\libs\fastbook\venv\lib\site-packages\fastai\learner.py", line 193, in _with_events
    try: self(f'before_{event_type}');  f()
  File "C:\Users\david\py\libs\fastbook\venv\lib\site-packages\fastai\learner.py", line 199, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)
  File "C:\Users\david\py\libs\fastbook\venv\lib\site-packages\fastai\data\load.py", line 129, in __iter__
    for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
  File "C:\Users\david\py\libs\fastbook\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1077, in __init__
    w.start()
  File "C:\Program Files\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python310\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Python310\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\david\py\libs\fastbook\venv\lib\site-packages\torch\multiprocessing\reductions.py", line 345, in reduce_storage
    raise RuntimeError("Cannot pickle CUDA storage; try pickling a CUDA tensor instead")
RuntimeError: Cannot pickle CUDA storage; try pickling a CUDA tensor instead
[W ..\torch\csrc\CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
```

**Comment by jph00** [comment]
You'll need to set `num_workers=0` on windows since we haven't found a way to make it work otherwise.

**Comment by davidgilbertson** [comment]
Aha, good to know. Yep that works now.

It would be great if this happened automatically, or maybe it's mentioned in the docs and I should read the docs...

**Comment by davidgilbertson** [comment]
I'd been hoping that Windows was a first-class citizen and I could avoid a layer of complexity (running inside WSL). But I see that generally in the deep learning world Python packages don't seem to get tested on Windows.

So I guess using WSL is the smart move, thanks for the guidance.

**Comment by jph00** [comment]
We had some kinda folks from msft work with us for quite a few months to try to get things working smoothly on Windows. But they only managed to get it to a point that it kinda worked, and worked slowly.

It's not just a lack of testing - Windows just doesn't have the APIs that DL frameworks are using. So the frameworks would need to be rewritten with Windows APIs in mind, AFAICT, and few people are doing that. (There's some cool stuff like https://diffsharp.github.io/ , but few projects use that.)
