### ISSUE TITLE
In "Transfer learning in text" tutorial, the "dls.show_batch()" show wrong outputs

### ISSUE THREAD

**Issue by dgg32** [fastai/fastai#2910]
I am following the [Beginner tutorial](https://docs.fast.ai/tutorial.text). When I run the code both in my local machine in Colab, several times, the output of cell 5 "dls.show_batch()" are wrong (screenshot below),  from the second item downwards they are all "xxpad xxpad xxpad xxpad xxpad xxpad". These are also different from what the tutorial page showed:

My run:
<img width="1391" alt="Bildschirmfoto 2020-10-27 um 19 52 56" src="https://user-images.githubusercontent.com/1873196/97348172-1748c600-188e-11eb-8d88-778c26505580.png">

Tutorial page:
<img width="779" alt="Bildschirmfoto 2020-10-27 um 19 55 41" src="https://user-images.githubusercontent.com/1873196/97348522-8cb49680-188e-11eb-8302-e8a77bde1ea7.png">

What is the cause of this issue please?

**Comment by marii-moe** [comment]
Starting working on this one.

**Comment by marii-moe** [comment]
I am able to reproduce this issue in my local environment.
