### ISSUE TITLE
URL on Documentation on callbacks.one_cycle

### ISSUE THREAD

**Issue by SOVIETIC-BOSS88** [fastai/fastai#2922]
The documentation on the following URL returns a 404 Not Found error:

- [callbacks.one_cycle]( https://docs.fast.ai/callbacks.one_cycle)

**Comment by marii-moe** [comment]
@SOVIETIC-BOSS88 Where did you find this link? one_cycle is not a callback anymore as it is absorbed into ParamScheduler.

**Comment by SOVIETIC-BOSS88** [comment]
I found the link by typing 'callbacks' into the search bar, and searching by Relevance. It was the second search result.
