### ISSUE TITLE
Add support for train_pct?

### ISSUE THREAD

**Issue by huangyingw** [fastai/fastai#2923]
**Link to forum discussion.**
https://forums.fast.ai/t/add-support-for-train-pct/81302

**Describe the solution you'd like**
currently, fastai has valid_pct, which will decide the percentage of data to be used as validation set.
is it possible to another parameter, called train_pct, which will define the percentage of data to be used as train data set.
the reason is that, when the data is huge, I want to have a small set of data to train my model first.

**Comment by muellerzr** [comment]
This can be closed, as the solution was posted in that thread. We have `RandomSubsetSplitter` for this.

(cc @jph00)

**Comment by huangyingw** [comment]
yes, thanks very much
