### ISSUE TITLE
`from vision.all import *` overwrites python built-in function `all`

### ISSUE THREAD

**Issue by ababino** [fastai/fastai#2924]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

**Describe the bug**
When you run `from vision.all import *` the python function `all` is overwritten.
**To Reproduce**
The following lines through an error
```python
from fastai.vision.all import *
all([True, False])
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-a22d80fd5ca5> in <module>
      1 from fastai.vision.all import *
----> 2 all([True, False])

TypeError: 'module' object is not callable
```
**Expected behavior**
```python
from fastai.vision.all import *
all([True, False])
```
should return `False`
**Additional context**
I think this happens because [this line](https://github.com/fastai/fastai/blob/d6f17ba84a6c2f3099611d8119d0eca2c9b88803/fastai/vision/all.py#L8) should not be there. Since there is an [all.py file](https://github.com/fastai/fastai/blob/master/fastai/vision/models/all.py) inside the [models folder](https://github.com/fastai/fastai/tree/master/fastai/vision/models), `from .models import *` overwrites the `all` function. 

Line 6, in that same file, is already importing the models, so removing line 8 should not affect their import. 

I can delete the line and make a PR, but I am unsure if there should be a test for this and where that test should be.

**Comment by jph00** [comment]
A PR would be most welcome :) . Thanks for noting the problem and the fix. I agree your suggested fix looks right.

**Comment by jph00** [comment]
Fixed it myself :)
