### ISSUE TITLE
torch 1.7.0 incompatibilty 

### ISSUE THREAD

**Issue by pford221** [fastai/fastai#2926]
Hello,

There is a thread on the forums that reproduces a potential bug with `AWD_LSTM` with torch==1.7.0
https://forums.fast.ai/t/the-size-of-tensor-a-400-must-match-the-size-of-tensor-b-0-at-non-singleton-dimension-2/81277

I've investigated and I believe the source of the problem is line 14 in awdlstm.py. Specifically this line:
```x.new(*sz).bernoulli_(1-p).div_(1-p)```

When `x` is a `TensorText` the `new` method does not appear to be compatible and it returns nothing. 

Here's a simple example:

```
from fastai.text.data import TensorText
tt = TensorText([[1,2,3], [4,5,6]])
tt.new(size=(2,3))
```
You'll notice that what is returned is an empty TensorText object where I think  the desire is to return the data contents of `tt`.

I think using `new_zeros` will work just fine for line 14 of awdlstm.py. I will make a PR to this effect.

Thanks!

**Comment by pford221** [comment]
Hi, 

I wrote this in PR #2927 as it was being merged, so at the risk of duplicating myself, I'll write it again:

-----
I'm afraid that this incompatibility is more pervasive than just this instance (I was afraid of that!). Another case is in line 172 of fastai.text.learner in the LMLearner.predict() method. Again, calling idxs.new([idx]) is returning an empty TensorText.

I'm happy to do what I can to try to spot other instances with a broad find and replace but I worry that I won't always know when the tensor is TensorText and whether this issue extends to other sublasses of torch.Tensor.
------

**Comment by jph00** [comment]
Fixed now.
