### ISSUE TITLE
unet_learner memory leak

### ISSUE THREAD

**Issue by moritzschwyzer** [fastai/fastai#2946]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

**Describe the bug**
There seems to be a GPU memory leak when using unet_learner. GPU memory of the fastai process increased from 2065MiB to 2575MiB within 50 epochs (checked via nvidia-smi).

**To Reproduce**
```
path = untar_data(URLs.CAMVID_TINY)
dls = SegmentationDataLoaders.from_label_func(
    path, bs=8, fnames = get_image_files(path/"images"),
    label_func = lambda o: path/'labels'/f'{o.stem}_P{o.suffix}',
    codes = np.loadtxt(path/'codes.txt', dtype=str)
)
learn = unet_learner(dls, resnet34)
learn.fine_tune(50)
```

**Comment by muellerzr** [comment]
Was the increase gradual or was it sudden? After the first epoch this could be expected as we unfreeze the model

**Comment by moritzschwyzer** [comment]
It was gradual (about after every 15th epoch).
