### ISSUE TITLE
Dataset leak issue with at least Tabular

### ISSUE THREAD

**Issue by muellerzr** [fastai/fastai#2949]
For the last day @jph00 and I have been fighting references to datasets inside of tabular and around fastai in general. We fixed two, referenced [here](https://github.com/fastai/fastcore/issues/174) and [here](https://github.com/fastai/fastai/pull/2948) and this issue partially originated from this flag: https://github.com/fastai/fastai/issues/2945

Through the use of the `pympler` library (docs [here](https://pympler.readthedocs.io/en/latest/muppy.html) ) I was able to narrow down the fact that we have two extraneous `DataFrames` still being exported via our `load_learner`. It's a bit more of a complex problem so here is a google colab notebook recreating what we've done: 

https://gist.github.com/muellerzr/c126e75b0265f88c3baa1ea50a4dfe6b

**Comment by jph00** [comment]
Should be fixed now.
