### ISSUE TITLE
'TensorPoint' object has no attribute 'img_size'

### ISSUE THREAD

**Issue by odysseus0** [fastai/fastai#2950]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

Describe the bug
When I ran through the tutorial code at https://docs.fast.ai/tutorial.vision#Points in Colab, the execution of `learn.show_results()` throws `AttributeError: 'TensorPoint' object has no attribute 'img_size'`.

To Reproduce
Simply run through the tutorial code in the above notebook and reach the `show_results` part.

**Comment by muellerzr** [comment]
When reporting issues please try to provide the full stack trace for us to look at as well as a (minimal) reproducer.

**Comment by rolandc85** [comment]
https://forums.fast.ai/t/attributeerror-tensorpoint-object-has-no-attribute-img-size/81431

To reproduce, run the 06_multicat.ipynb in colab from fast.ai.

**Comment by jph00** [comment]
Fixed by https://github.com/fastai/fastai/commit/62fbc69aad01804ec3bb37271d77c273aa1b1a68
