### ISSUE TITLE
Unexpected number of channels in DynamicUnet model makes learning 25% slower

### ISSUE THREAD

**Issue by ababino** [fastai/fastai#2965]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

**Describe the bug**
The number of channels in some `DynamicUnet` layers are not a power of 2.

**To Reproduce**
If you ran the following code:
```python
from fastai.vision.all import *
m = resnet18()
m = nn.Sequential(*list(m.children())[:-2])
tst = DynamicUnet(m, 3, (128,128), norm_type=None)
sizes = model_sizes(tst, (128, 128))
L(sizes).itemgot(1)[5:]
```
You'll get this list `[384,256,96,96,96,99,99,3]`
The elements 0, 2,3, and 4 are not powers of 2.

**Expected behavior**
I am not sure if this is a bug, or not. I believe that the DynamicUnet model is an exclusive feature of fastai (isn't it?). So, I don't have another implementation to compare it with. But I was expecting the decoder's layers to have twice as many (or the same) number of channels than the encoder.

**Additional context**
I believe that this is due to the implementation of `UnetBlock` that downsamples the number of channels of the input before concatenating it with the output of the skip connection [here](https://github.com/fastai/fastai/blob/e9d8aa82d9fafd662a3669c25e0cbc8f389ab236/fastai/vision/models/unet.py#L23). If we replace that line by:
```python
self.shuf = PixelShuffle_ICNR(up_in_c, x_in_c, blur=blur, act_cls=act_cls, norm_type=norm_type)
```
And [this line](https://github.com/fastai/fastai/blob/e9d8aa82d9fafd662a3669c25e0cbc8f389ab236/fastai/vision/models/unet.py#L25) by:
```python
ni =2*x_in_c
```
The decoder's layers get the expected number of channels `[256, 128, 64, 64, 64, 67, 67, 32]`

I run some experiments to understand the effect of this feature/bug and it seems that both models reach the same loss value, but the execution time is ~25% faster when we change the `UnetBlock` definition. You can see my analysis [here](https://gist.github.com/ababino/a041e252d707b9ffc126d8572dcea816).

If you think that this should be fixed I can make a PR.

**Comment by jph00** [comment]
As discussed on discord, seems to just be a # params issue.
