### ISSUE TITLE
README.md #installing is incomplete

### ISSUE THREAD

**Issue by pjgoodall** [fastai/fastai#2986]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES 

**Describe the bug**

The  installation instructions are missing the installation of the jupyter notebook, and *possibly* some supporting utilities. Please we should not assume that the OS/platform has various parts of the necessary configuration installed.

I'm calling this a bug, not a feature request, because the system can easily be inoperable without a fix - the resultant install will be incomplete.

**To Reproduce**
1.  `% conda install -c fastai -c pytorch fastai`
2.  `% which jupyter > jupyter is not installed`

**Expected behavior**

After the 

**Error with full stack trace**

Place between these lines with triple backticks:

```
% git clone git@github.com:fastai/fastbook.git
% cd ./fastai
% jupyter notebook
>bash: command not found: jupyter

```

**Additional context**
 I suggest having an `end-user_environment.yml `in the repository - looking like:

``` yml
name: fastai
channels:
- fastai
- pytorch
- defaults
dependencies:
- fastai
# My additions
- conda-forge::notebook
```

then this will do a full end-user install
```
% conda env create  -f ./my_environment.yml
% conda activate fastai
% jupyter notebook
```

More in my comment in fastai forums at: [Installation Guide Fastai V2 for Linux](https://forums.fast.ai/t/installation-guide-fastai-v2-for-linux/77432/3)

**Comment by jph00** [comment]
jupyter is not required to use fastai

**Comment by pjgoodall** [comment]
I see what you mean.
Trouble is - I am led here by installation instructions for students of the course.
