### ISSUE TITLE
Could you fix the bug of AWD_QRNN? 

### ISSUE THREAD

**Issue by sky1ove** [fastai/fastai#3017]
AWD_QRNN does not work, and always show the error. To reproduce the error: https://colab.research.google.com/drive/19WzwYTzs78DNvQ7VTw_37hbXq3l5ozsk?usp=sharing

**Comment by jph00** [comment]
Hi - you'd already created an issue for this bug. Creating 2 issues makes more administrative overhead for us, and slows us down, making it take longer to fix bugs. In this case, I'd just fixed the bug, and now I have to mark two issues closed instead of one. So please don't do this.

**Comment by sky1ove** [comment]
Hi Jeremy, Thanks for fixing!
