### ISSUE TITLE
NameError: name 'log_args' is not defined

### ISSUE THREAD

**Issue by Alex-Songs** [fastai/fastai#3018]
NameError: name 'log_args' is not defined (in fastai2/layers.py)

**Comment by tyoc213** [comment]
Probably you have an old version of fastai2 https://github.com/fastai/fastai/issues/2954

**Comment by tyoc213** [comment]
Maybe just a `!pip install -U fastai --upgrade` will do the job.

**Comment by Alex-Songs** [comment]
Thanks ! @tyoc213

**Comment by marii-moe** [comment]
@Alex-Songs Looks like this one was solved, so closing it.
