### ISSUE TITLE
Can't use fastai 2.1.5 after recent update. 

### ISSUE THREAD

**Issue by BishalLakha** [fastai/fastai#3046]
Fastai 2.1.5 was working fine few days back but it is not working after recent update

![image](https://user-images.githubusercontent.com/9823258/100535684-33e86d00-3243-11eb-88e1-7f6e6f188335.png)

**Comment by morganmcg1** [comment]
@BishalLakha have you tried updating fastcore?

`conda update fastcore`

**Comment by jph00** [comment]
Just checked and works on latest fastcore AFAICT

**Comment by BishalLakha** [comment]
> @BishalLakha have you tried updating fastcore?
> 
> `conda update fastcore`

I had previously installed it with pip, recently did with miniconda but still no luck 
![image](https://user-images.githubusercontent.com/9823258/100694486-4f748480-33b7-11eb-83dd-ca3ca7121299.png)

**Comment by jph00** [comment]
Your pytorch is too old. Suggest you ask on the forums for help.
