### ISSUE TITLE
ClassificationInterpretation.from_learner not working on training set

### ISSUE THREAD

**Issue by lluissalord** [fastai/fastai#3051]
First of all, thank you for this amazing framework!!

Using last version of fastai, when setting ds_idx=0 and training DataLoader is using `drop_last=True` raise IndexError.

My intuition is that as it is taking directly the DataLoader from training I suspect can generate incorrect behaviours if training is set with `drop_last=True`.

I suggest to change this part of the code:
https://github.com/fastai/fastai/blob/a07f271ac6a03cd14ff7f8c031c38527e5b238ed/fastai/interpret.py#L26-L29

to:

```python
def from_learner(cls, learn, ds_idx=1, dl=None, act=None):
        "Construct interpretation object from a learner"
        if dl is None: dl = learn.dls[ds_idx].new(shuffled=False, drop_last=False)
        return cls(dl, *learn.get_preds(dl=dl, with_input=True, with_loss=True, with_decoded=True, act=None))
```

Doing this it is replicated the behaviour seen on `get_preds`:
https://github.com/fastai/fastai/blob/cb01af7dbf7ae16fda68a7eec19a87c75423a8fe/fastai/learner.py#L223-L225

**Comment by muellerzr** [comment]
@hamelsmu can be closed due to my fix earlier today

**Comment by lluissalord** [comment]
Hi @muellerzr,

I have seen that the same issue happen on line 579:
https://github.com/fastai/fastai/blob/7fe5fcaab3c0b692a0be54ffe651f04f4cdd4a39/fastai/learner.py#L575-L579

Could you please also add this fix?
Thanks!

**Comment by muellerzr** [comment]
@lluissalord thanks! Fixed with https://github.com/fastai/fastai/pull/3347
