### ISSUE TITLE
NameError: name 'log_args' is not defined Error after from fastai2.basics import *

### ISSUE THREAD

**Issue by sminize** [fastai/fastai#3056]
Hello,
i installed the latest fasta2r version and fastcore with these commands.

!pip install git+https://github.com/fastai/fastcore.git
    
!pip install git+https://github.com/fastai/fastai2.git

Then i imported fastai2 with.

`from fastai2.basics import *`

I got the error message:

'log_args' is not defined

In older issues i read that it has something to do with fastcore. However i used the latest fastcore and fastai2 version.

Thank you for your help.

**Comment by muellerzr** [comment]
`fastai2` is heavily outdated, as it was merged into `fastai` a few months back (hence why its an archived project). I would recommend using the latest `fastai`, otherwise you would need to try and find the suitable `fastcore` version to install, which looks to be `0.1.34`.

**Comment by letrongan** [comment]
@muellerzr What is the version of nbdev? I am using fastai == 1.0.60, fastcore == 0.1.34 but it doesn't work. Thank you!

**Comment by muellerzr** [comment]
@letrongan nbdev is the current pip release, so 1.1.15. You are using the old version of fastai. You should do `pip install fastai --upgrade` on whatever platform you have so it shows fastai `2.x.x`

**Comment by glitt13** [comment]
I also get this error message following `from fastai.vision.all import *` despite having fastai `2.0.19`. I tried installing in my anaconda as follows:  `conda install -c fastai -c pytorch -c anaconda fastai gh anaconda`

**Comment by vojtajina** [comment]
@glitt13 It's because `log_args` was removed in fastcore 1.3.5, so if you are using `fastai==2.0.19`, you need to also force `fastcore==1.3.2`.

**Comment by bojnin-basile** [comment]
> @glitt13 It's because `log_args` was removed in fastcore 1.3.5, so if you are using `fastai==2.0.19`, you need to also force `fastcore==1.3.2`.

Yes, thank you. How do you do that?

**Comment by muellerzr** [comment]
@bojnin-basile 

```python
pip install fastai==2.0.19 fastcore==1.3.2
```

@hamelsmu this should be closable :)
