### ISSUE TITLE
Fastai v2.1.7 missing utils submodule

### ISSUE THREAD

**Issue by than3-bits** [fastai/fastai#3057]
Good Afternoon, it looks like the fastai.utils submodule is no longer part of the library with fastai v2.1.7.

Can someone please document how these library imports should now be transformed to get the equivalent function. 
Also, there are still references to using this submodule and for new people that follow that documentation its now failing. 

The only relevant and now, top, google post when searching for 'fastai.utils' ModuleNotFound references a vague post that there was a change but doesn't say what that change was nor provide a resolution.

**Comment by tcapelle** [comment]
it is called `test_utils` now I think.

**Comment by muellerzr** [comment]
@hamelsmu this can be closed, as it is `test_utils`
