### ISSUE TITLE
Workaround for Pytorch bug: One of the differentiated Tensors does not require grad

### ISSUE THREAD

**Issue by cimenzhong** [fastai/fastai#3072]
```python
captum.visualize(fnames[idx],baseline_type='uniform') # OK.
captum.visualize(fnames[idx],metric='NT',baseline_type='uniform') # error
```

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-12-ad13e36e215b> in <module>
----> 1 captum.visualize(fnames[idx],metric='NT',baseline_type='uniform')

~/app/anaconda3/envs/py36/lib/python3.6/site-packages/fastai/callback/captum.py in visualize(self, inp, metric, n_steps, baseline_type, nt_type, strides, sliding_window_shapes)
     57 
     58         # Get Required Metrics
---> 59         attributions=self._get_attributions(enc_data,metric,n_steps,nt_type,baseline_type,strides,sliding_window_shapes)
     60 
     61         #Visualise the attributions

~/app/anaconda3/envs/py36/lib/python3.6/site-packages/fastai/callback/captum.py in _get_attributions(self, enc_data, metric, n_steps, nt_type, baseline_type, strides, sliding_window_shapes)
     90             self._integrated_gradients = self._integrated_gradients if hasattr(self,'_integrated_gradients') else IntegratedGradients(self.model)
     91             self._noise_tunnel= self._noise_tunnel if hasattr(self,'_noise_tunnel') else NoiseTunnel(self._integrated_gradients)
---> 92             return self._noise_tunnel.attribute(enc_data[0].to(self.dls.device), n_samples=1, nt_type=nt_type, target=enc_data[1])
     93         elif metric == 'Occl':
     94             self._occlusion = self._occlusion if hasattr(self,'_occlusion') else Occlusion(self.model)

~/app/anaconda3/envs/py36/lib/python3.6/site-packages/captum/log/__init__.py in wrapper(*args, **kwargs)
     33             @wraps(func)
     34             def wrapper(*args, **kwargs):
---> 35                 return func(*args, **kwargs)
     36 
     37             return wrapper

~/app/anaconda3/envs/py36/lib/python3.6/site-packages/captum/attr/_core/noise_tunnel.py in attribute(self, inputs, nt_type, n_samples, stdevs, draw_baseline_from_distrib, **kwargs)
    238                 self.attribution_method,  # self
    239                 inputs_with_noise if is_inputs_tuple else inputs_with_noise[0],
--> 240                 **kwargs,
    241             )
    242 

~/app/anaconda3/envs/py36/lib/python3.6/site-packages/captum/attr/_core/integrated_gradients.py in attribute(self, inputs, baselines, target, additional_forward_args, n_steps, method, internal_batch_size, return_convergence_delta)
    290                 additional_forward_args=additional_forward_args,
    291                 n_steps=n_steps,
--> 292                 method=method,
    293             )
    294 

~/app/anaconda3/envs/py36/lib/python3.6/site-packages/captum/attr/_core/integrated_gradients.py in _attribute(self, inputs, baselines, target, additional_forward_args, n_steps, method, step_sizes_and_alphas)
    353             inputs=scaled_features_tpl,
    354             target_ind=expanded_target,
--> 355             additional_forward_args=input_additional_args,
    356         )
    357 

~/app/anaconda3/envs/py36/lib/python3.6/site-packages/captum/_utils/gradient.py in compute_gradients(forward_fn, inputs, target_ind, additional_forward_args)
    123         # torch.unbind(forward_out) is a list of scalar tensor tuples and
    124         # contains batch_size * #steps elements
--> 125         grads = torch.autograd.grad(torch.unbind(outputs), inputs)
    126     return grads
    127 

~/app/anaconda3/envs/py36/lib/python3.6/site-packages/torch/autograd/__init__.py in grad(outputs, inputs, grad_outputs, retain_graph, create_graph, only_inputs, allow_unused)
    186             create_graph=create_graph,
    187             only_inputs=only_inputs,
--> 188             allow_unused=allow_unused,
    189         )
    190 

~/app/anaconda3/envs/py36/lib/python3.6/site-packages/torch/overrides.py in handle_torch_function(public_api, relevant_args, *args, **kwargs)
   1061         # Use `public_api` instead of `implementation` so __torch_function__
   1062         # implementations can do equality/identity comparisons.
-> 1063         result = overloaded_arg.__torch_function__(public_api, types, args, kwargs)
   1064 
   1065         if result is not NotImplemented:

~/app/anaconda3/envs/py36/lib/python3.6/site-packages/fastai/torch_core.py in __torch_function__(self, func, types, args, kwargs)
    317 #         if func.__name__[0]!='_': print(func, types, args, kwargs)
    318 #         with torch._C.DisableTorchFunction(): ret = _convert(func(*args, **(kwargs or {})), self.__class__)
--> 319         ret = super().__torch_function__(func, types, args=args, kwargs=kwargs)
    320         if isinstance(ret, TensorBase): ret.set_meta(self, as_copy=True)
    321         return ret

~/app/anaconda3/envs/py36/lib/python3.6/site-packages/torch/tensor.py in __torch_function__(cls, func, types, args, kwargs)
    993 
    994         with _C.DisableTorchFunction():
--> 995             ret = func(*args, **kwargs)
    996             return _convert(ret, cls)
    997 

~/app/anaconda3/envs/py36/lib/python3.6/site-packages/torch/autograd/__init__.py in grad(outputs, inputs, grad_outputs, retain_graph, create_graph, only_inputs, allow_unused)
    202     return Variable._execution_engine.run_backward(
    203         outputs, grad_outputs_, retain_graph, create_graph,
--> 204         inputs, allow_unused)
    205 
    206 

RuntimeError: One of the differentiated Tensors does not require grad

**Comment by jph00** [comment]
Have you tried the latest master version of fastai? Do you know if this problem is a captum problem or a fastai problem? Maybe you could ask the captum folks to take a look, since we're not captum experts here!

**Comment by ababino** [comment]
This is the problem that I could not solve, and I described [here](https://github.com/fastai/fastai/pull/3043).

If I have to guess, I would say that this is not a problem with fastai nor captum, but with PyTorch and tensor subclasses. One solution is to override the in-place operation `.requires_grad_()` like so:

```python
class FooTensor(Tensor):
    def requires_grad_(self):
        self.requires_grad = True
        return self
```

What do you think @jph00?

**Comment by jph00** [comment]
I've filed a bug with Pytorch https://github.com/pytorch/pytorch/issues/50219 and added a workaround to `TensorBase`.
