### ISSUE TITLE
https://docs.fast.ai/callback.neptune.html broken

### ISSUE THREAD

**Issue by amaarora** [fastai/fastai#3085]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES 

**Describe the bug**
The documentation page for the `neptune` callback is broken and gives a Not Found error. 

**To Reproduce**
1. Go to https://docs.fast.ai/callback.neptune.html

**Expected behavior**
I should be able to see how the documentation on how to integrate Neptune with Fastai.

**Error with full stack trace**

Place between these lines with triple backticks:

```
Not Found
The requested URL was not found on this server.

If you found this broken link on a fast.ai site or search engine, please tell us about it by filing a bug report here.
```

**Additional context**

**Comment by tmabraham** [comment]
There is no error anymore, @jph00 can close...

**Comment by jph00** [comment]
Great
