### ISSUE TITLE
issue to set embedding size in tabular learner

### ISSUE THREAD

**Issue by didopop3** [fastai/fastai#3086]
https://github.com/fastai/fastai/blob/89b1afb59e37e5abf7008888f6e4dd1bf1211e3e/fastai/tabular/learner.py#L29

I believe this line should be 
`emb_szs = get_emb_sz(dls.train_ds, {})  if emb_szs is None else emb_szs`

**Comment by muellerzr** [comment]
We include it as what that allows is partial sizes to be used, for instance we can do:
```python
emb_szs = {'workclass':100}
learn = tabular_learner(dls, layers=[200,100], emb_szs=emb_szs)
```
And it will still generate embeddings for the other variables, whereas yours would fail (it's a helpful guard)

@jph00 can close

**Comment by jph00** [comment]
Thanks!
