### ISSUE TITLE
Classes list of TextLearner

### ISSUE THREAD

**Issue by adammzd** [fastai/fastai#3093]
Please don't ask for help here. [Use the forums](https://forums.fast.ai)
I want to get Classes list of TextLearner, I cannot get it by learn.classes or learn.dls.classes.
can you help me please?
learn = load_learner('model.pkl')

**Comment by muellerzr** [comment]
I responded in your forum post as well: https://forums.fast.ai/t/classes-list-of-textlearner/83777/2

But it lives in `learn.dls.categorize.vocab`. It's not in `learn.dls.vocab` (as it would be for other applications using `CategoryBlock` or `MultiCategoryBlock`) as text has its own vocab. As a result we need to go to the direct transform
