### ISSUE TITLE
Link does not exist-  "Before posting in this thread please read the troubleshooting instructions 37"

### ISSUE THREAD

**Issue by Christian-daigneault** [fastai/fastai#3099]
in the Fastai v1 install issues thread,  the following link brings to error message:  

Not Found

The requested URL was not found on this server.

If you found this broken link on a fast.ai site or search engine, please tell us about it by filing a bug report here.

**Comment by muellerzr** [comment]
Try changing the url from `docs.fast.ai/blah` to `fastai1.fast.ai`
