### ISSUE TITLE
WandbCallback doesn't log anything but system's stats (CPU, GPU)

### ISSUE THREAD

**Issue by tumbleintoyourheart** [fastai/fastai#3102]
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES

**Describe the bug**
WandbCallback doesn't log anything (loss, metrics, gradients, ...). In the app.wandb run, it only logs system's stats (CPU, GPU, ...)
The same code below worked previously, but didn't with some latest version of the library:
```
learner = Learner(dls, SomeCustomModel(), 
                  loss_func=LabelSmoothingCrossEntropyFlat(), 
                  metrics=[SomeCustomMetrics()], 
                  )
cbs = [ShowGraphCallback(), 
       SaveModelCallback(), 
       WandbCallback(log_preds=False, log_model=False), 
]
learner.fit_one_cycle(n_epochs, lr, cbs=cbs)
```

**To Reproduce**

**Expected behavior**
No errors thrown, training/validation works perfectly.

**Error with full stack trace**

**Additional context**

**Comment by dreamflasher** [comment]
@tumbleintoyourheart I can't confirm this, wandb is working for me. If you provide an example that I can run (with all imports, variables etc.), I can give it a try here, to see if there's a problem specific to your code.

**Comment by tumbleintoyourheart** [comment]
What a pity, due to IP reason I can't open-sourcing the project. I can confirm that W&B callback works well on other lesson notebooks. Closing this now since it's not a common issue, debugging it on my own. I will share any insights that might have caused me the problem.
