### ISSUE TITLE
'name noops is not defined' in class 'BaseLoss'

### ISSUE THREAD

**Issue by Boolwark** [fastai/fastai#3103]
```/usr/local/lib/python3.6/dist-packages/fastai/losses.py in BaseLoss()
     13 class BaseLoss():
     14     #"Same as loss_cls, but flattens input and target."
---> 15     activation=decodes=noops
     16     def __init__(self, loss_cls, *args, axis=-1, flatten=True, floatify=False, is_2d=True, **kwargs):
     17         store_attr("axis,flatten,floatify,is_2d")

NameError: name 'noops' is not defined

**Comment by muellerzr** [comment]
What is your version of fastcore and fastai? We can't do much without knowing this. It seems you may have an old version

**Comment by SelmanAKA** [comment]
I got the same error when i tried to run the 01_intro.ipynb from fastai/fastbook in colab. It happens at the first cell in import fastbook line. Notebook only gives an error when i change the runtime type and try to use a GPU. Everything seems to work fine when i dont use a GPU.

**Comment by SelmanAKA** [comment]
I just try to reproduce the error to post here but now the notebook is working perfectly and not giving an error.

**Comment by Daocuong-main** [comment]
> Further help for those who find this page... I just found this page after running, on Colab,
> 
> ```
> !pip install -Uqq fastbook
> import fastbook
> ```
> 
> ...as in the fastbook notebooks.
> 
> What you need to do is run
> 
> ```
> !pip install -Uqq fastai fastbook
> ```
> 
> THEN restart the runtime. Then you can run "import fastbook" and it will work.

not work for me :(

**Comment by muellerzr** [comment]
@Daocuong-main please tell us your versions of:

```bash
pip show fastai fastcore fastbook
```
And your environment. Are you running in Colab?

**Comment by Daocuong-main** [comment]
> 

fastai: 2.5.3
fastcore: 1.3.27
fastbook: 0.0.18

yes i use colab
