### ISSUE TITLE
`cont_cat_split` function doesn't work for int64 pandas columns

### ISSUE THREAD

**Issue by NouamaneTazi** [fastai/fastai#3114]
`cont_cat_split` function doesn't work for int64 pandas columns

**To Reproduce**
1.  Create a column with int64 values
2. Pass it to `cont_cat_split` function
3. Get the column as continuous no matter what `max_card` is

I think the problem comes from the comparison to `int` which is different from `dtype('int64')`
```python
if df[label].dtype == int and df[label].unique().shape[0] > max_card or df[label].dtype == float:
            cont_names.append(label)
```

**Comment by binarymason** [comment]
Thanks for making this issue, @NouamaneTazi.  I also am experiencing this issue. Thought I was going crazy.

**Comment by binarymason** [comment]
ref: https://github.com/fastai/fastai/issues/2583

**Comment by muellerzr** [comment]
@jph00 this was fixed in https://github.com/fastai/fastai/pull/3117

**Comment by NouamaneTazi** [comment]
Thanks!
