### ISSUE TITLE
[Beginner] Bring back the Performance Tips and Update for Latest Versions/Ideas

### ISSUE THREAD

**Issue by muellerzr** [fastai/fastai#3125]
If anyone would like to tackle this, in the old version we had this documentation:

https://fastai1.fast.ai/performance.html

Which discussed bringing in libjpeg turbo among other libraries. It would be nice to have this back in the documentation and updated where it needs be in case anyone has discovered any performance tricks with the external libs, etc needed with fastai.

It's Markdown is available here for you to look at: 
https://github.com/fastai/fastai1/blob/master/docs/performance.md

In total what this PR should do is update that markdown, move it to `fastai/docs_src/dev/performance.md`, and update the sidebar at `fastai/docs_src/sidebar.json` to include it in with the "Getting started" category

**Comment by nglillywhite** [comment]
Happy to tackle this, @muellerzr thanks for the suggestion and guidance. I'll put together a PR and post back here if that's the best way forward. Let me know if there's anything else.

**Comment by nglillywhite** [comment]
I noticed that check_perf() wasn't migrated into the new repo and so I removed that from the previous performance doc, was this intentional or this function didn't make the cut to the new version of the library?

**Comment by muellerzr** [comment]
@jph00 you may be better at suggesting this. Ideally if you wanted to bring it over, it would reside in the same place that we already have the `show_install`? 

The actual func in v1 is here: https://github.com/fastai/fastai1/blob/master/fastai/utils/collect_env.py#L156

**Comment by nglillywhite** [comment]
Hey @muellerzr , I think this can be closed now. Thanks for the guidance and help with my first PR and contribution to fastai, the experience was really positive (thanks jeremy as well for feedback).

**Comment by jph00** [comment]
Great!
