### ISSUE TITLE
Issues with fastai Tensor subclasses & equality operation

### ISSUE THREAD

**Issue by pford221** [fastai/fastai#3130]
Hi,

I think this issue is known based on [Zachary's response on this thread](https://forums.fast.ai/t/chapter-13-learner-error/83114), but I didn't see a github issue for it explicitly

Versions:
fastai : 2.2.1
torch: 1.7.1
fastcore: 1.3.16

Reproducible example:
```
import numpy as np
from fastai.torch_core import TensorImage
from fastai.torch_core import TensorMask

size = (3, 10, 10)
ti = TensorImage(np.random.uniform(size=size))
tm = TensorMask(np.random.choice([0,1], size=size))

ti == tm
```

Error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-27-f607939df9b1> in <module>
      6 tm = TensorMask(np.random.choice([0,1], size=size))
      7 
----> 8 ti == tm

~/.local/share/virtualenvs/fastai_modeling-wXHhCDlU/lib64/python3.7/site-packages/torch/tensor.py in wrapped(*args, **kwargs)
     23         from torch.overrides import has_torch_function, handle_torch_function
     24         if not all(type(t) is Tensor for t in args) and has_torch_function(args):
---> 25             return handle_torch_function(wrapped, args, *args, **kwargs)
     26         try:
     27             return f(*args, **kwargs)

~/.local/share/virtualenvs/fastai_modeling-wXHhCDlU/lib64/python3.7/site-packages/torch/overrides.py in handle_torch_function(public_api, relevant_args, *args, **kwargs)
   1066     raise TypeError("no implementation found for '{}' on types that implement "
   1067                     '__torch_function__: {}'
-> 1068                     .format(func_name, list(map(type, overloaded_args))))
   1069 
   1070 def has_torch_function(relevant_args: Iterable[Any]) -> bool:

TypeError: no implementation found for 'torch.tensor.eq' on types that implement __torch_function__: [<class 'fastai.torch_core.TensorImage'>, <class 'fastai.torch_core.TensorMask'>]

**Comment by simonstadlinger** [comment]
I have the same issue when using the `foreground_acc` metric on a segmentation data loader.
`dataloaders = SegmentationDataLoaders.from_label_func(
    SEGMENTATION_IMAGE_DIR, 
    fnames = train_val_images,
    label_func = get_lung_mask,
    valid_pct=train_val_split,
    seed=42,
    codes=codes,
    batch_tfms=batch_transformations,
    item_tfms=item_transformations,
    bs=4)

learn = unet_learner(dataloaders, models.resnet34, metrics=[foreground_acc])
`
`no implementation found for 'torch.tensor.eq' on types that implement __torch_function__: [<class 'fastai.torch_core.TensorImage'>, <class 'fastai.torch_core.TensorMask'>]`

**Comment by cimenzhong** [comment]
> Hi,
> 
> I think this issue is known based on [Zachary's response on this thread](https://forums.fast.ai/t/chapter-13-learner-error/83114), but I didn't see a github issue for it explicitly
> 
> Versions:
> fastai : 2.2.1
> torch: 1.7.1
> fastcore: 1.3.16
> 
> Reproducible example:
> 
> ```
> import numpy as np
> from fastai.torch_core import TensorImage
> from fastai.torch_core import TensorMask
> 
> size = (3, 10, 10)
> ti = TensorImage(np.random.uniform(size=size))
> tm = TensorMask(np.random.choice([0,1], size=size))
> 
> ti == tm
> ```
> 
> Error:
> 
> ```
> TypeError                                 Traceback (most recent call last)
> <ipython-input-27-f607939df9b1> in <module>
>       6 tm = TensorMask(np.random.choice([0,1], size=size))
>       7 
> ----> 8 ti == tm
> 
> ~/.local/share/virtualenvs/fastai_modeling-wXHhCDlU/lib64/python3.7/site-packages/torch/tensor.py in wrapped(*args, **kwargs)
>      23         from torch.overrides import has_torch_function, handle_torch_function
>      24         if not all(type(t) is Tensor for t in args) and has_torch_function(args):
> ---> 25             return handle_torch_function(wrapped, args, *args, **kwargs)
>      26         try:
>      27             return f(*args, **kwargs)
> 
> ~/.local/share/virtualenvs/fastai_modeling-wXHhCDlU/lib64/python3.7/site-packages/torch/overrides.py in handle_torch_function(public_api, relevant_args, *args, **kwargs)
>    1066     raise TypeError("no implementation found for '{}' on types that implement "
>    1067                     '__torch_function__: {}'
> -> 1068                     .format(func_name, list(map(type, overloaded_args))))
>    1069 
>    1070 def has_torch_function(relevant_args: Iterable[Any]) -> bool:
> 
> TypeError: no implementation found for 'torch.tensor.eq' on types that implement __torch_function__: [<class 'fastai.torch_core.TensorImage'>, <class 'fastai.torch_core.TensorMask'>]
> ```
np.array(ti.cpu()) == np.array(tm.cpu())

**Comment by tcapelle** [comment]
try this:
```
import numpy as np
from fastai.vision.all import *
from fastai.torch_core import TensorImage
from fastai.torch_core import TensorMask

for o in Tensor.__eq__,:
    TensorBase.register_func(o, TensorMask, TensorImageBase)
    TensorBase.register_func(o, TensorImageBase, TensorMask)


size = (3, 10, 10)
ti = TensorImage(np.random.uniform(size=size))
tm = TensorMask(np.random.choice([0,1], size=size))

ti == tm
```

**Comment by pford221** [comment]
Thanks @tcapelle for the suggestion. I saw the most recent commit to Main branch (that you made) added this. So, is it safe to assume that this is resolved if pulling from Main branch?

**Comment by tcapelle** [comment]
Not really... It fixes your particular issue: `ti == tm` but it misses others. I am pretty noob on all this subclassing issues. I am figuring out.
