### ISSUE TITLE
DataBlock.dataloaders does not support the advertised "shuffle" argument

### ISSUE THREAD

**Issue by juliangilbey** [fastai/fastai#3133]
Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): YES
fastai 2.2.2, fastcore 1.3.16, nbdev 1.1.6

**Describe the bug**
The DataBlock documentation describes the [https://docs.fast.ai/data.block.html#DataBlock.dataloaders](`dataloaders`) function and explicitly says that there is an optional kwarg `shuffle`.  However, using this results in the error:
```
TypeError: fastai.data.core.TfmdDL() got multiple values for keyword argument 'shuffle'
```

**To Reproduce**
Take the notebook for Chapter 2 of the fastai book, and change the cell which reads `dls = bears.dataloaders(path)` to read `dls = bears.dataloaders(path, shuffle=True)` instead.

**Expected behavior**
It should perform shuffling as requested.

**Error with full stack trace**
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-cb46ba7faa34> in <module>
----> 1 dls = bears.dataloaders(path, shuffle=True)

~/fast.ai.course/fastai-venv/lib/python3.9/site-packages/fastai/data/block.py in dataloaders(self, source, path, verbose, **kwargs)
    113         dsets = self.datasets(source, verbose=verbose)
    114         kwargs = {**self.dls_kwargs, **kwargs, 'verbose': verbose}
--> 115         return dsets.dataloaders(path=path, after_item=self.item_tfms, after_batch=self.batch_tfms, **kwargs)
    116 
    117     _docs = dict(new="Create a new `DataBlock` with other `item_tfms` and `batch_tfms`",

~/fast.ai.course/fastai-venv/lib/python3.9/site-packages/fastai/data/core.py in dataloaders(self, bs, val_bs, shuffle_train, n, path, dl_type, dl_kwargs, device, **kwargs)
    211         if dl_type is None: dl_type = self._dl_type
    212         drop_last = kwargs.pop('drop_last', shuffle_train)
--> 213         dl = dl_type(self.subset(0), bs=bs, shuffle=shuffle_train, drop_last=drop_last, n=n, device=device,
    214                      **merge(kwargs, dl_kwargs[0]))
    215         dls = [dl] + [dl.new(self.subset(i), bs=(bs if val_bs is None else val_bs), shuffle=False, drop_last=False,

TypeError: fastai.data.core.TfmdDL() got multiple values for keyword argument 'shuffle'
```

**Additional context**
The cause of the error is clear, though the best way to solve it is not as obvious.  The `DataBlock.dataloaders()` method:
https://github.com/fastai/fastai/blob/373050bcbf5d31712340c06316326c8d0403ed76/fastai/data/block.py#L112-L115
just passes most of the keyword arguments through to its `Datasets` object, which in turn is a subclass of `FilteredBase`, so inherits the `dataloaders()` method from there.  This method is as follows:
https://github.com/fastai/fastai/blob/d1cf81c2aacaad4497d1920c468f3c73a3a6fc71/fastai/data/core.py#L207-L217
This has the keyword argument `shuffle_train` (but not shuffle), but on lines 213-214, calls the `dl_type` function with an explicit `shuffle` keyword and then the `kwargs` passed through (merged with `dl_kwargs[0]`).  So if `kwargs` includes `shuffle`, there will be a repeated keyword argument.

I haven't checked whether the same would apply to the other keyword arguments listed on line 213.

One simple way would be to rewrite lines 213-214 as:
```python
        dl = dl_type(self.subset(0),
                     **merge({'bs': bs, 'shuffle': shuffle_train, 'drop_last': drop_last, 'n': n, 'device': device},
                     kwargs, dl_kwargs[0]))
```

**Comment by juliangilbey** [comment]
Actually, I see the same issue appears on lines 215-216 as well, if `shuffle` appears in `dl_kwargs[i]`.

**Comment by marii-moe** [comment]
Was able to reproduce this and taking a look at it now.

**Comment by tcapelle** [comment]
just to understand, what are you trying to shuffle?

**Comment by juliangilbey** [comment]
I was trying to shuffle the validation set (I had a good reason to), but realised that even if the `shuffle` argument did as it said, it would still not shuffle the validation set, only the training set. So I found a different (perhaps clunky) way to do what I wanted to do. But if someone didn't want to shuffle the training set for some reason, `shuffle=False` would not work either, so the bug definitely remains, though it's a pretty small one.

**Comment by marii-moe** [comment]
@juliangilbey Just to help with writing this, why are you trying to shuffle the validation set? I wouldn't think we would want to drop the last batch on the validation set so making sure.

**Comment by marii-moe** [comment]
@jph00 For this one I think it might be good to assume keyword arguments apply to train, and can be overridden for the validation set by starting with 'val_'. The key idea below: 
```
#default_kwargs - keyword arguments we have default values like bs,shuffle,drop_last
def create_dl(): #place holder for creating dataloaders
val_kwargs={k[4:]:v for k,v in kwargs.items() if k.startswith('val_')} #implmenting this is the key idea
dls = [ create_dl(merge(kwargs,default_kwargs,val_kwargs,dl_kwargs[i]) ) for i in range(num_dls) ]
#combined_kwargs could then be pass
```

Here is a more complete gist for my idea: https://gist.github.com/marii-moe/7374ee9d59400f85b17dc54b7a2c4af0

Here is the original: https://github.com/fastai/fastai/blob/dded7854017ecfebe8b70e0674915e7b50f134c5/fastai/data/core.py#L207

This would mean removing 'shuffle_train' which has been part of the api as far back as I could track in fastai_dev/fastai2. `kwargs` was originally included in creating the validation dataloader, but more recently was removed, so less sure about including that one as part of the merge. Unable to find info on why kwargs is not included as part of creating validation dataloaders, but it could have been to simplfy things. Here is the commit that changed it though: https://github.com/fastai/fastai/commit/a4e2456420832f9507924d69e73a62a0ac0c4571#diff-b881fa2851a7d60fe30b52d6cd1bc25cd510f0b9ac30de516cd01c3de05af1cbL166

**Comment by juliangilbey** [comment]
> @juliangilbey Just to help with writing this, why are you trying to shuffle the validation set? I wouldn't think we would want to drop the last batch on the validation set so making sure.

Hi @marii-moe I wanted to run `dls.valid.show_batch()` to check that things looked OK in the validation set. Unfortunately, the original data is very nicely ordered, so I only see data instances from one class.  Being able to shuffle the validation set would help for this.

**Comment by jph00** [comment]
> For this one I think it might be good to assume keyword arguments apply to train, and can be overridden for the validation set by starting with 'val_'.

I like it. Let's leave `shuffle_train` as well for now, but have it raise a deprecation warning if not `None`, and have it just set `shuffle`. How does that sound?
