### ISSUE TITLE
Merge Walk with fastai links into the documentation

### ISSUE THREAD

**Issue by muellerzr** [fastai/fastai#3137]
(Placeholder issue while I work on things so it can show up in the changelog :) )

**Comment by jph00** [comment]
We don't normally have docs changes in the changelog - and I'd rather not have stuff in issues that aren't actionable.

**Comment by jph00** [comment]
(BTW a PR with a label appears in the changelog, regardless of whether there's an issue too)

**Comment by muellerzr** [comment]
Ahhhh. I wasn’t sure on that one. Thanks for catching! Good to know for in
the future
