### ISSUE TITLE
Jitter or alternative image transform options

### ISSUE THREAD

**Issue by kkorunes** [fastai/fastai#3147]
Feature requests should first be proposed on [the forum](https://forums.fast.ai). 

**Link to forum discussion:**

https://forums.fast.ai/t/jitter-transform-that-was-available-in-v1-is-removed-in-v2/80205

see also: https://forums.fast.ai/t/exchange-rows-transform/80452

**Describe the solution you'd like:**
I'm looking for a few data augmentation options that I'm unable to find in fastai V2. Specifically, the jitter function that was available in V1 appears to not have carried over to V2 (see forum links above). Can this be made available in V2? Relatedly, is there a way to apply transforms to exchange pixels along one axis (e.g., shuffling rows or columns of pixels), like the question raised in the 2nd forum link above?

**Describe alternatives you've considered:**
A viable alternative to the above would be coding custom transforms, but as a fastai beginner, this is challenging. Is there any documentation or guidance available on creating custom transforms?

**Comment by tcapelle** [comment]
I would recommend checking the [vision notebook] (https://github.com/fastai/fastai/blob/master/nbs/07_vision.core.ipynb) to do it.

**Comment by kkorunes** [comment]
Thank you so much for addressing both questions, this is very helpful. I will try this out!

**Comment by tcapelle** [comment]
@jph00  you can close this
