### ISSUE TITLE
Runtime Error using AWD-LSTM (RuntimeError: Input and hidden tensors are not at the same device)

### ISSUE THREAD

**Issue by anindabitm** [fastai/fastai#3158]
Hi,

I am getting a runtime error on using AWD_LSTM model on GPU. Please find below the code to reproduce and the error generated. This is my first time posting an issue here. Apologies if I have posted incorrectly. 

![bug](https://user-images.githubusercontent.com/39881731/104608402-d8b1f300-56a7-11eb-9cf2-d3bd9975ca7b.jpg)

RuntimeError Traceback (most recent call last)
in ()
----> 1 learn.model(x).shape

5 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
725 result = self._slow_forward(*input, **kwargs)
726 else:
–> 727 result = self.forward(*input, **kwargs)
728 for hook in itertools.chain(
729 _global_forward_hooks.values(),

/usr/local/lib/python3.6/dist-packages/fastai/text/models/awdlstm.py in forward(self, inp, from_embeds)
104 new_hidden = []
105 for l, (rnn,hid_dp) in enumerate(zip(self.rnns, self.hidden_dps)):
–> 106 output, new_h = rnn(output, self.hidden[l])
107 new_hidden.append(new_h)
108 if l != self.n_layers - 1: output = hid_dp(output)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
725 result = self._slow_forward(*input, **kwargs)
726 else:
–> 727 result = self.forward(*input, **kwargs)
728 for hook in itertools.chain(
729 _global_forward_hooks.values(),

/usr/local/lib/python3.6/dist-packages/fastai/text/models/awdlstm.py in forward(self, *args)
51 # To avoid the warning that comes because the weights aren’t flattened.
52 warnings.simplefilter(“ignore”, category=UserWarning)
—> 53 return self.module(*args)
54
55 def reset(self):

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
725 result = self._slow_forward(*input, **kwargs)
726 else:
–> 727 result = self.forward(*input, **kwargs)
728 for hook in itertools.chain(
729 _global_forward_hooks.values(),

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py in forward(self, input, hx)
580 if batch_sizes is None:
581 result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
–> 582 self.dropout, self.training, self.bidirectional, self.batch_first)
583 else:
584 result = _VF.lstm(input, batch_sizes, hx, self._flat_weights, self.bias,

RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu

**Comment by tcapelle** [comment]
I think this is tricky. Try with an actual `dls` on the gpu before calling the forward method.
I think the Learner is initalizing the hidden state on the device of the dataloader, as there is `None`, it is putting the tensors on the CPU.

**Comment by anindabitm** [comment]
Many thanks for your response. I tried it using a dls also but facing same error

![bug](https://user-images.githubusercontent.com/39881731/104614486-4eb95880-56ae-11eb-929f-bcfe3d51314c.jpg)

**Comment by tcapelle** [comment]
As you are no using the text learner, pass the `ModelResetter` Callback first.

**Comment by tcapelle** [comment]
@jph00  you can close this

**Comment by anindabitm** [comment]
Thanks a lot. This is of great help
