### ISSUE TITLE
Docs pages for migration not found (404)

### ISSUE THREAD

**Issue by sbp-dev** [fastai/fastai#3166]
**Describe the bug**
Not sure if this is the correct place to log the issue but the documentation page for migrating to Fastai is unreachable. 
![Capture](https://user-images.githubusercontent.com/54526452/104744746-40814000-5773-11eb-92e1-2192a439b66d.PNG)

**To Reproduce**
1. Open browser
2. Try to open this link: https://docs.fast.ai/migrating_pytorch

**Expected behavior**
I read the documentations just a few days back, wanted to check again

**Comment by tcapelle** [comment]
same as https://github.com/fastai/fastai/issues/3154

**Comment by muellerzr** [comment]
@hamelsmu can be closed, all migration doc links are working
