### ISSUE TITLE
module generated layers can't be exported to jit.script

### ISSUE THREAD

**Issue by muellerzr** [fastai/fastai#3172]
Currently layers using the `@module` decorator can't be properly exported via `torch.jit.script`. They can with `torch.jit.trace`, but `script` is more flexible and preferred. Specifically `jit` does not support complied functions that take keyword-only arguments with defaults. I've attached a minimal example below in a gist, it would be nice if fastai could allow for this. 

https://gist.github.com/muellerzr/d34f07aff73546930e16c2721a38d3a4

**Comment by muellerzr** [comment]
Related: https://github.com/pytorch/vision/issues/3159

**Comment by tcapelle** [comment]
the `@module` decorator does not seems to be used extensively on fastai code. Did you tried replacing only the flatten layer to see if it works?

**Comment by muellerzr** [comment]
Yes, removing the Flatten layer lets the model work (I did this via a custom head). Looks like having the `@module` doesn't matter, as I rewrote `Flatten` as 
```python
class myFlatten(Module):
    def __init__(self, full=False): self.full = full
    def forward(self, x): return TensorBase(x.view(-1) if self.full else x.view(x.size(0), -1))
```
So it can't be scripted on CUDA, but it can on CPU. @tcapelle do you know if this limits anything? Also closing since this isn't entirely a bug anymore

**Comment by tcapelle** [comment]
I have a meeting tomorrow morning with Nvidia, I can try to ask.
The truth is I don't understand a lot of what is happening with
`torch.script` in general, I know it serializes, but the host device can be
changed at loading, so...
I would be favorable to remove the @module decorator, it does not save a
lot of space, we already have the fastai `Module`.

**Comment by tcapelle** [comment]
![image](https://user-images.githubusercontent.com/18441985/104960373-5f324180-59d4-11eb-8aaf-101ff6c72d63.png)

**Comment by hal-314** [comment]
I think that TensorBase call in `Flatten` is the culprit that Flatten can't be scripted.

```python
@module(full=False)
def myFlatten(self, x):
    "Flatten `x` to a single dimension, e.g. at end of a model. `full` for rank-1 tensor"
    # return TensorBase(x.view(-1) if self.full else x.view(x.size(0), -1)) <- Fastai implementation.
    return x.view(-1) if self.full else x.view(x.size(0), -1)

path = untar_data(URLs.PETS)/'images'
dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2,
    label_func=lambda x: x[0].isupper(), item_tfms=Resize(224))
learn = cnn_learner(dls, resnet18)

assert isinstance(model[1][1], Flatten)
model[1][1] = myFlatten()

ts_model = torch.jit.script(learn.model)
```

This can be scripted.

**Comment by tcapelle** [comment]
it has, this solves the issue:
```python
@patch
def requires_grad_(self:TensorBase, requires_grad=True):
    # Workaround https://github.com/pytorch/pytorch/issues/50219
    self.requires_grad = requires_grad
    return self
```

**Comment by hal-314** [comment]
In my opinion, there is another important limitation with tracing. You need to use the same batch size that you used when you traced your module. So, it's difficult to use a traced model in a production server that support batching request. For example torchserve, cortex or BentoML support this. 

I don't generally find difficult to script a model. Most of them works out of the box or with small tweaks (I scripted several classification and segmentation models, yolov5 and some custom models). With small tweaks I mean annotating code with Python annotation (mostly constants in the __init__) + avoid to use functions/methods with **kwargs.

**Comment by tcapelle** [comment]
I don't think that tracing has this limitation.
![image](https://user-images.githubusercontent.com/18441985/107010130-382a8c80-6796-11eb-81eb-d3717b65b765.png)
