### ISSUE TITLE
LanguageModelData.from_dataframes requires test_df

### ISSUE THREAD

**Issue by kevindewalt** [fastai/fastai#319]
## Works
`md = LanguageModelData.from_dataframes(path=data_path, field=TEXT, col='all_text',
                                      train_df=train_df, val_df=val_df, test_df=test_df, bs=bs, bptt=bptt)`

works fine.

## Error
Replacing `test_df=test_df` with `test_df=None` returns error: 

`md = LanguageModelData.from_dataframes(path=data_path, field=TEXT, col='all_text',
                                      train_df=train_df, val_df=val_df, test_df=None, bs=bs, bptt=bptt)`
returns:

`ValueError                                Traceback (most recent call last)
<ipython-input-104-5813a72e373e> in <module>()
      1 md = LanguageModelData.from_dataframes(path=data_path, field=TEXT, col='all_text',
----> 2                                       train_df=train_df, val_df=val_df, test_df=None, bs=bs, bptt=bptt)

~/fastai/fastai/nlp.py in from_dataframes(cls, path, field, col, train_df, val_df, test_df, bs, bptt, **kwargs)
    275     def from_dataframes(cls, path, field, col, train_df, val_df, test_df=None, bs=64, bptt=70, **kwargs):
    276         trn_ds, val_ds, test_ds = ConcatTextDatasetFromDataFrames.splits(text_field=field, col=col,
--> 277                                     train_df=train_df, val_df=val_df, test_df=test_df)
    278 
    279         return cls(path, field, trn_ds, val_ds, test_ds, bs, bptt, **kwargs)

ValueError: not enough values to unpack (expected 3, got 2)`

## investigation
Same error when replacing val_df with None.

**Comment by mcskinner** [comment]
@jph00 any reason for this `None` filtering in `ConcatTextDatasetFromDataFrames` ([code here])(https://github.com/fastai/fastai/blob/16313f83fef7f47b6008643e9eb8f5397fbabe54/fastai/nlp.py#L196):
`return tuple(d for d in (train_data, val_data, test_data) if d is not None)`

It seems easy to remove, and my grepping says the only caller is the one in this stack trace.

**Comment by jph00** [comment]
Yeah it's for use in notebooks where `splits` is often called without a test set.

**Comment by dalupus** [comment]
I've added a pull to fix this.  #347
