### ISSUE TITLE
Broken link in callbacks docs.

### ISSUE THREAD

**Issue by KBodolai** [fastai/fastai#3191]
Hi!

I was going through the callbacks docs, where I stumbled upon a broken link [in the mixed precision section](https://docs.fast.ai/callback.fp16.html). The broken link in question is the one to the video from NVIDIA with some background.

I think the correct link might be [this one](https://on-demand.gputechconf.com/gtc/2019/video/_/S9143/).

K.

**Comment by muellerzr** [comment]
@hamelsmu this can be closed
