### ISSUE TITLE
`learn.fit_one_cycle` results should be saved and made more easily 

### ISSUE THREAD

**Issue by tianhuil** [fastai/fastai#3195]
Feature requests should first be proposed on [the forum](https://forums.fast.ai). 

**Link to forum discussion.**

https://forums.fast.ai/t/obtain-learn-fit-results-as-a-dataframe/55883

**Is your feature request related to a problem? Please describe.**
I'd like to save off the dataframe which is printed to stdout during runs (see image below):
![image](https://user-images.githubusercontent.com/1906321/106350228-f6c34a00-6288-11eb-96a4-395a1acebe61.png)

This allows me to programmatically save off the results and (e.g.) combine them across different calls to `learn.fit_one_cycle` so that I can easily plot training performance against time for different parameters or different models.

**Describe the solution you'd like**
Ideally, `learner.recorder.results` (or better yet) `learner.results` would return the df.  It would also be ideal if this was explained in the notebooks.

**Describe alternatives you've considered**
It turns out that 80% of this has already been implemented in the `Recorder` class which is available via `learn.recorder.values`.  For more information, check out [learner.py](https://github.com/fastai/fastai/blob/b31cf9430fa1719dfd1eacc5ab28fccf6cfc6c6c/fastai/learner.py).  However, this does not save off the training time (which is not saved in the recorder).  The training time is useful for plotting performance because model benchmarks are not per epoch but per unit time (i.e. to normalize for different models taking different epochs).

**Additional context**
N/A

**Comment by tmabraham** [comment]
This is already implemented with the [CSVLogger](https://docs.fast.ai/callback.progress.html#CSVLogger) callback. Is there a reason this callback does not fulfill your needs?

**Comment by tmabraham** [comment]
@jph00 this can be closed
