### ISSUE TITLE
AttributeError for multiple output models when using mixed precision

### ISSUE THREAD

**Issue by joomyjoo** [fastai/fastai#3202]
In the callback/fp16.py, .dtype is called on self.preds
However, when the model has two or more outputs, self.preds is a tuple of tensors not tensor
This results in an assertion error when self.preds.dtype is called.

To reproduce, train a model with two or more outputs with mixed precision.
"""
/usr/local/lib/python3.6/dist-packages/fastai/callback/fp16.py in after_pred(self)
     20     def before_batch(self): self.autocast.__enter__()
     21     def after_pred(self):
---> 22         if self.pred.dtype==torch.float16: self.learn.pred = to_float(self.pred)
     23     def after_loss(self): self.autocast.__exit__()
     24     def before_backward(self): self.learn.loss_grad = self.scaler.scale(self.loss_grad)

AttributeError: 'tuple' object has no attribute 'dtype'
"""

Expected Behavior:
The dtype check should be done on one of the outputs, regardless the number of outputs of a model.
Checking all outputs for dtype should not be necessary, because outputs should be of the same dtype.

Fix:
Using listify(self.preds)[0].dtype instead of self.preds[0] in callback/fp16.py
should resolve this issue.

--> I'm new to github and nbdev; I've managed to push the changes to joomyjoo/fastai;
but im not sure to the request a merge to the master. Hoping someone could help!

**Comment by tmabraham** [comment]
I have a similar issue with my package [UPIT](https://github.com/tmabraham/UPIT), great to see you already have a fix.

Have you tried following [this guide](https://docs.fast.ai/dev-setup.html) to make your changes and submit a PR?

**Comment by joomyjoo** [comment]
> I have a similar issue with my package [UPIT](https://github.com/tmabraham/UPIT), great to see you already have a fix.
> 
> Have you tried following [this guide](https://docs.fast.ai/dev-setup.html) to make your changes and submit a PR?

Thanks, I followed those steps to request a merge [Here](https://github.com/fastai/fastai/pull/3212)

**Comment by tmabraham** [comment]
This issue was solved by #3217 (cc: @jph00)

**Comment by jph00** [comment]
Thanks!
