### ISSUE TITLE
captum integration broken

### ISSUE THREAD

**Issue by lsb** [fastai/fastai#3207]
There are links to Captum, Weights & Biases, Neptune, and Tensorboard. Only Captum 404s out, and the following three work. The 404 page helpfully links to how to make an issue for this, so.
Specifically, I'm getting a 404 for https://docs.fast.ai/callback.captum.html whereas I don't for https://docs.fast.ai/callback.tensorboard.html

**Comment by ReinierKoops** [comment]
Might be related to which python packages are installed on the server when "nbdev_build_docs" is run. When I build it locally with [dev] packages installed, there is a html-package created...

**Comment by ReinierKoops** [comment]
My guess is that something should be edited in the "fastai/workflows/build-docs@master", which is not public. @jph00

**Comment by muellerzr** [comment]
@hamelsmu let's rename this issue to "Captum Integration" broken (which we know this being due to captum currently not working)

**Comment by lsb** [comment]
https://github.com/fastai/fastai/issues/3325#issuecomment-1120098229
