### ISSUE TITLE
fastai 2.2.5 on PyPI is actually version 2.2.3

### ISSUE THREAD

**Issue by juliangilbey** [fastai/fastai#3220]
Something clearly went wrong there!  It's dated Jan 13, and its contents are version 2.2.3.

Best wishes, Julian

**Comment by aberres** [comment]
Yeps, I can confirm this. 

Just wondered why the Pandas dtype fix for `cont_cat_split` was not around.

Seems as if Jeremy is doing the releases himself, hence a friendly ping @jph00

**Comment by snapwich** [comment]
yes, i've been pulling my hair out for hours now trying to figure out why fastbook 09_tabular.ipynb was giving me wrong results, only to update fastai and then find it no longer ran. specifically `cont_cat_split` was turning YearMade and other columns into category fields causing my results to differ greatly from the results in the lessons. 

once I nailed it down to an issue with `cont_cat_split` I updated my fastai dependency to the latest (2.2.5) only to find that `cont_cat_split` no longer worked at all. I found https://github.com/fastai/fastai/pull/3157 and confirmed that I had a version that had supposedly had that fix, but after no luck getting the code to run and digging through the module dependencies on disk i realized it doesn't really have that fix. i've patched my local version and now things are working again, but right now 09_tabular.ipynb is broken for anyone running the latest published version of fastai.

i tried to include as many keywords as i could in here so hopefully anyone running into the same issue can find this with a google search; i wasn't finding anything myself.

**Comment by jph00** [comment]
Many thanks for the reports - I've just released 2.2.6, which hopefully actually contains the fixes from 2.2.5. Please take a look and let me know if this resolves the issues.

**Comment by snapwich** [comment]
@jph00 I updated to the latest and the `fastai.__version__` still says 2.2.5 but confirmed that it does have the fix for `con_cat_split` so I think it is the latest and fixes the issue I was seeing. Thanks for your help; and for the lessons!

**Comment by juliangilbey** [comment]
@jph00 Thanks Jeremy, that does fix the `cont_cat_split` issues.  I guess this report can now be closed, then, taking care that the next release is version 2.2.7 or later.

**Comment by aberres** [comment]
Things are looking good now

```
>>> import fastai
>>> fastai.__version__
'2.2.7'
```

**Comment by muellerzr** [comment]
@hamelsmu this can be closed, Jeremy fixed this with a release a bit ago
