### ISSUE TITLE
Fastai gives NameError: name 'delegates' is not defined

### ISSUE THREAD

**Issue by fil82** [fastai/fastai#3221]
When importing fastai I am getting the following error :
from fastai.tabular.all import *
NameError: name 'delegates' is not defined

I have updated to the latest versions:
fastai ==2.2.5
fastcore ==1.3.20

**Comment by prudhvirajboddu** [comment]
same issue . You got any solution for that ?

**Comment by smart-patrol** [comment]
Getting this as well. Going to try to downgrade to a previous version.

**Comment by smart-patrol** [comment]
Deleting the imports file as described in #3090 worked. 

Uninstall and reinstall does not.

**Comment by muellerzr** [comment]
@smart-patrol @fil82 are you still having issues? If so can you try installing the latest version and try again? (and give a bit more context on your systems being used, the version of fastai, etc?)

**Comment by hamelsmu** [comment]
I haven't been able to replicate this issue.

I'm on the latest versions of fastai ( `2.7.10`)  and fastcore (` 1.5.28`)so I'm closing this issue.

**Comment by tomasvanoyen** [comment]
I am having the same issue with fastai (`2.7.12`) and fastcore (`1.5.29`).
