### ISSUE TITLE
Support PyTorch 1.8, TorchVision 0.9.0 and TorchAduio 0.8.0

### ISSUE THREAD

**Issue by DavidSpek** [fastai/fastai#3244]
I know there is probably some testing that needs to happen, and that you devs are probably already aware of it, but PyTorch 1.8, TorchVision 0.9.0 and TorchAduio 0.8.0 were released two days ago so support for these in the next FastAI release would be nice. 

https://github.com/pytorch/pytorch/releases/tag/v1.8.0

**Comment by muellerzr** [comment]
Do you know specifically if anything breaks when using torchvision and torch that we need to fix? It would be very helpful if you could find any areas which are breaking, as if there are none then nothing is needed :)

**Comment by DavidSpek** [comment]
I was using the 1.8 nightly with fastai very briefly as I needed to for RTX3090 support. I didn't notice anything that broke, but my use was very limited.

**Comment by muellerzr** [comment]
@DavidSpek someone already tested this the day of release and confirmed it worked without error, so this can be closed.

**Comment by DavidSpek** [comment]
@muellerzr Cool. Should I create a PR to change the dependency listing to include PyTorch 1.8?

**Comment by DavidSpek** [comment]
@muellerzr It seems like there is a difference between the `settings.ini` and the `environment.yml` files in regards to PyTorch 1.8 and TorchVision 0.9. 

https://github.com/fastai/fastai/blob/00d88637cd7f804da55473b7c3c31aba4fecba1c/settings.ini#L16
https://github.com/fastai/fastai/blob/00d88637cd7f804da55473b7c3c31aba4fecba1c/settings.ini#L17

https://github.com/fastai/fastai/blob/00d88637cd7f804da55473b7c3c31aba4fecba1c/environment.yml#L8
https://github.com/fastai/fastai/blob/00d88637cd7f804da55473b7c3c31aba4fecba1c/environment.yml#L18

Should I create a PR to extend the pinning in the `settings.ini` file?

I'm wanting to add FastAI to some of the new docker images provided with Kubeflow in the upcoming release, but as we are wanting to only include the latest version of frameworks it would be nice if FastAI could be installed with PyTorch 1.8 (through pip).

**Comment by 1enn0** [comment]
I totally agree, it would be very cool to be able to install `fastai` with `torch` 1.8.0 / `torchvision` 0.9.0 from PyPI, since the Windows wheels for `torchvision` only started to be pushed to PyPI again (starting with 0.9.0)

Any updates on this? :)

**Comment by nrhodes** [comment]
Also an issue when using colab (see [this post](https://forums.fast.ai/t/fastai-install-fail-on-colab-version-mismatch-in-pytorch/86655)).

**Comment by DavidSpek** [comment]
@hamelsmu Could you maybe give your input on this? This is currently preventing me from updating to the latest PyTorch for the new Notebook images that will be included with Kubeflow 1.3.

**Comment by hamelsmu** [comment]
@jph00 do you want to take a look at this?

**Comment by DavidSpek** [comment]
From what I saw fastai version 2.3.0 still requires PyTorch 1.7.1. PyTorch 1.8.1 has since been released.

**Comment by Sting18** [comment]
Does anybody know if I can run pytorch with CudaToolkit11.1 and fastai? I've been having issues trying to get them both to work together. I'm running a 3090 so I need cuda>=11, but I've been having issues getting a compatible version of torchvision installed.

ERROR: Could not find a version that satisfies the requirement torchvision<0.9,>=0.8 (from fastai)
ERROR: No matching distribution found for torchvision<0.9,>=0.8

**Comment by Rangarajan731** [comment]
runtime crashes in colab when I try to use tensor().

**Comment by ruffson** [comment]
> Does anybody know if I can run pytorch with CudaToolkit11.1 and fastai? I've been having issues trying to get them both to work together. I'm running a 3090 so I need cuda>=11, but I've been having issues getting a compatible version of torchvision installed.
> 
> ERROR: Could not find a version that satisfies the requirement torchvision<0.9,>=0.8 (from fastai)
> ERROR: No matching distribution found for torchvision<0.9,>=0.8

Did you have any luck? 

I am on a 3080 notebook GPU and get a warning: `Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.`
And if I try to still train I get a `RuntimeError: CUDA error: no kernel image is available for execution on the device`

**Comment by Sting18** [comment]
> 
> 
> > Does anybody know if I can run pytorch with CudaToolkit11.1 and fastai? I've been having issues trying to get them both to work together. I'm running a 3090 so I need cuda>=11, but I've been having issues getting a compatible version of torchvision installed.
> > ERROR: Could not find a version that satisfies the requirement torchvision<0.9,>=0.8 (from fastai)
> > ERROR: No matching distribution found for torchvision<0.9,>=0.8
> 
> Did you have any luck?
> 
> I am on a 3080 notebook GPU and get a warning: `Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.`
> And if I try to still train I get a `RuntimeError: CUDA error: no kernel image is available for execution on the device`

I downgraded my FastAI version I believe, but now I have a plethora of other issues I'm running into. Still haven't been able to train a GAN with FastAI on a 3090. Got to the point I have stepped away to reset after the burnout and frustration.

**Comment by ruffson** [comment]
> > > Does anybody know if I can run pytorch with CudaToolkit11.1 and fastai? I've been having issues trying to get them both to work together. I'm running a 3090 so I need cuda>=11, but I've been having issues getting a compatible version of torchvision installed.
> > > ERROR: Could not find a version that satisfies the requirement torchvision<0.9,>=0.8 (from fastai)
> > > ERROR: No matching distribution found for torchvision<0.9,>=0.8
> > 
> > 
> > Did you have any luck?
> > I am on a 3080 notebook GPU and get a warning: `Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.`
> > And if I try to still train I get a `RuntimeError: CUDA error: no kernel image is available for execution on the device`
> 
> I downgraded my FastAI version I believe, but now I have a plethora of other issues I'm running into. Still haven't been able to train a GAN with FastAI on a 3090. Got to the point I have stepped away to reset after the burnout and frustration.

So I entangled myself in python package dependency hell yesterday but then switched over to anaconda from miniconda. And after freshly installing fastai, etc. it seems that it works now for me. At least it does not break where it broke before when training a resnet. So I hope that can work for others.

**Comment by ShadowTemplate** [comment]
Hi guys! Do you have any update on this issue?
Is there any reason to not bump PyTorch's dependency?
Thanks a lot!

**Comment by estaar** [comment]
Any new Update on this. tried to install fastai today and that error is very annoying and I have to recreate my environment again and just use normal Pytorch

**Comment by muellerzr** [comment]
@estaar we're working on this for the next release. There were a few bugs between the two torch versions

**Comment by jph00** [comment]
fastai 2.3.1 now supports the latest pytorch and torchvision.
