### ISSUE TITLE
61_tutorial.medical_imaging.ipynb  requires Normalize 

### ISSUE THREAD

**Issue by rubensmau** [fastai/fastai#3250]
To make the fit work properly, we need to replace the line:
batch_tfms=aug_transforms(size=224))
by:
batch_tfms=[*aug_transforms(size=224),Normalize.from_stats(*imagenet_stats)])

otherwise there is a size mismatch
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[64, 1, 1024, 1024] to have 3 channels, but got 1 channels instead

**Comment by trdvangraft** [comment]
I faced the same problem, working on implementing the solution that you gave!
