### ISSUE TITLE
FastAI repository cleaning suggestion

### ISSUE THREAD

**Issue by ReinierKoops** [fastai/fastai#3273]
Currently both https://github.com/fastai/fastai and https://github.com/fastai/course-v3 have overlap with the following folders:
- fastai: "fastai/dev_nbs/course"
- course-v3: "course-v3/nbs/dl1"

I would propose to delete the fastai folder "fastai/dev_nbs" since it's a duplicate of v3. The duplication makes maintainability harder. There are now two repositories to fix instead of one.

**Comment by jph00** [comment]
course-v3 is the fastai1 version of the nbs, and dev_nbs contains the fastai2 version. We'd like to keep both.
