### ISSUE TITLE
 fastai 2.3.0 - No module named 'fastai.callbacks'

### ISSUE THREAD

**Issue by matveevai** [fastai/fastai#3289]
Ubuntu 18.04
python 3.6.9

fastai - - - - - - - 2.3.0
fastcore - - - - - 1.3.19
fastprogress - - 1.0.0
fastrelease - - - 0.1.11

**Code**
`from fastai.callbacks import SaveModelCallback`

**Error with full stack trace**
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-6c1732b81c03> in <module>
----> 1 from fastai.callbacks import SaveModelCallback

ModuleNotFoundError: No module named 'fastai.callbacks'
```

**Comment by tmabraham** [comment]
yeah, it's `fastai.callback` not `fastai.callbacks`

**Comment by TingNLP** [comment]
@matveevai I have a same problem. do you solve it ?

**Comment by TingNLP** [comment]
> @matveevai I have a same problem. do you solve it ?

try this

![image](https://user-images.githubusercontent.com/54096137/114806555-8c29a100-9dd7-11eb-9ce9-83e27306c751.png)

**Comment by muellerzr** [comment]
@matveevai fastai version 1 has the import as `fastai.callbacks, but in fastai version 2 it's `fastai.callback` which you should also import with: `from fastai.callback.all import *`.

You'll know if you're using version 1 or two if `pip show fastai` (or `fastai.__version__`) shows fastai 1.0.x or fastai 2.x.x

@hamelsmu should be okay to close as this relates to the old version of the library
