### ISSUE TITLE
name 'DatasetType' is not defined

### ISSUE THREAD

**Issue by Saeed0Baba** [fastai/fastai#3290]
fastai VERSION 2.2.7

I am running prediction like this:

preds = learn.get_preds(ds_type=DatasetType.Test)
which is used in fastai v1 with no problem. but running the same code in fastai v2 raise the following error:

NameError: name 'DatasetType' is not defined

what should be used instead of DatasetType?

**Comment by shIsmael** [comment]
You don't need to use ds_type=DatasetType.Test, you can use:
`dl = learn.dls.test_dl(df_test)
preds = learn.get_preds(dl=dl)`

**Comment by muellerzr** [comment]
@Saeed0Baba as @shIsmael said, `DatasetType` was fastai v1 specific, now we can simply pass in any `DataLoader` to get preds, and you can perform inference with the snippet shown there.

@hamelsmu should be good to close now.
