### ISSUE TITLE
fastai 2.2.7-No module named 'fastai.column_data'

### ISSUE THREAD

**Issue by Angel-Wei** [fastai/fastai#3293]
Hi, I installed fastai 2.2.7. Other info are provided here for reference:
pytorch 1.7.1
conda 4.9.2
Python 3.6.12
I got the error `ModuleNotFoundError: No module named 'fastai.column_data'` when I run `from fastai.column_data import *`.
However when I tried to uninstall and downgrade the fastai to 1.0.61. I got errors `No module named 'fastai.learner'` together with `ModuleNotFoundError: No module named 'fastai.column_data'`. when I run
`from fastai.learner import *`
`from fastai.column_data import *`
I have no clue what causes these errors and wonder if these problems can be fixed. Really need the help and thanks in advance!

**Comment by muellerzr** [comment]
You're trying to use extremely outdated code. It would help to know the source of the article or the rough time period in which it came out. As it clearly isn't using fastai v2, nor fastai v1.0.0

**Comment by Angel-Wei** [comment]
Thanks for the clarification! That's what I thought. I was reading a paper published in 2019 and looked at their code to construct the collab learner and I have checked the tutorials of the updated fastai and sorted it out. Thanks again.
