### ISSUE TITLE
Older fastai version (v2.2.7) on conda

### ISSUE THREAD

**Issue by kai-tub** [fastai/fastai#3304]
It seems like the conda version of fastai is still on v2.2.7 (https://anaconda.org/fastai/fastai)
Is it possible that the same error as in #3233 ?
@jph00 would you be so kind to take a quick look at this?
If conda simply takes a while before it is updated, sorry for the unnecessary ping.
I am looking forward to use my tiny fix in v2.3.0 and remove some of my local patch code :)

Best regards,
Kai

**Comment by jph00** [comment]
Many thanks for the report - fixed now
