### ISSUE TITLE
docs.fast.ai seems corrupted

### ISSUE THREAD

**Issue by fredguth** [fastai/fastai#3306]
**Describe the bug**
The bug is online. The docs.fast.ai site has several pages leading to "Not Found".

**To Reproduce**
1. Go to: https://docs.fast.ai/tutorial.datablock.html
2. or: https://docs.fast.ai/tutorial.pets.html
3. etc

```
```

**Additional context**
It seems something that happened today, because I was using these docs not long ago.

**Comment by amaarora** [comment]
@fredguth This seems to be working for me. Any chance you could post some screenshots? 

![image](https://user-images.githubusercontent.com/41290559/113962862-e7094880-986b-11eb-95a8-39219585cf8a.png)
![image](https://user-images.githubusercontent.com/41290559/113962880-ed97c000-986b-11eb-98f8-fdfc2bee511f.png)

**Comment by hamelsmu** [comment]
We had some intermittent issues, but they should be fixed now.  Thanks
