### ISSUE TITLE
Creation of new DataLoader in Learner.get_preds has wrong keyword

### ISSUE THREAD

**Issue by d-miketa** [fastai/fastai#3312]
Should be an easy one, but I don't have the dev environment set up to submit a PR myself. I think the keyword argument on this line should be `shuffle=False`, not `shuffled=False`.
https://github.com/fastai/fastai/blob/f726d1ac3f00c5536e9dad39291935c087e0b952/fastai/learner.py#L232

**Comment by tcapelle** [comment]
Thanks:
https://github.com/fastai/fastai/pull/3316

**Comment by muellerzr** [comment]
@jph00 or @hamelsmu this can be closed thanks to #3316
