### ISSUE TITLE
Cannot install through pip (downgrades PyTorch)

### ISSUE THREAD

**Issue by HiPhish** [fastai/fastai#3323]
I wanted to ask this on the forums, but the forum software does not let me create topics.

**Describe the bug**
When installing fastai using pip the installed version of PyTorch gets downgraded, and then the installation fails because the version is too low.

**To Reproduce**
1. Install PyTorch according to the official documentation: `pip install torch torchvision torchaudio`
2. Install fastai: `pip install fastai`

**Expected behavior**
Everything should install as expected.

**Error with full stack trace**

The installation aborts with the following message:

```
Installing collected packages: murmurhash, cymem, wasabi, tqdm, srsly, pyparsing, preshed, plac, idna, chardet, catalogue, blis, torch, threadpoolctl, thinc, scipy, pytz, python-dateutil, packaging, kiwisolver, joblib, cycler, torchvision, spacy, scikit-learn, pyyaml, pandas, matplotlib, fastprogress, fastcore, fastai
  Attempting uninstall: torch
    Found existing installation: torch 1.8.1
    Uninstalling torch-1.8.1:
      Successfully uninstalled torch-1.8.1
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.9.1
    Uninstalling torchvision-0.9.1:
      Successfully uninstalled torchvision-0.9.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 0.8.1 requires torch==1.8.1, but you have torch 1.7.1 which is incompatible.
Successfully installed blis-0.7.4 catalogue-1.0.0 chardet-4.0.0 cycler-0.10.0 cymem-2.0.5 fastai-2.3.0 fastcore-1.3.19 fastprogress-1.0.0 idna-2.10 joblib-1.0.1 kiwisolver-1.3.1 matplotlib-3.4.1 murmurhash-1.0.5 packaging-20.9 pandas-1.2.4 plac-1.1.3 preshed-3.0.5 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2021.1 pyyaml-5.4.1 scikit-learn-0.24.1 scipy-1.6.2 spacy-2.3.5 srsly-1.0.5 thinc-7.4.5 threadpoolctl-2.1.0 torch-1.7.1 torchvision-0.8.2 tqdm-4.60.0 wasabi-0.8.2
```

**Additional context**
Running on [Void](https://voidlinux.org/) and Python 3.9.4, pip 21.0.1. All packages are installed without using `sudo`. Upon installing PyTorch I get the following packages on my system:

```
$ pip list --user
Package           Version
----------------- -------
torch             1.8.1
torchaudio        0.8.1
torchvision       0.9.1
typing-extensions 3.7.4.3
```

After trying to install fastai the versions have been changed:

```
$ pip list --user
Package           Version
----------------- -------
blis              0.7.4
catalogue         1.0.0
chardet           4.0.0
cycler            0.10.0
cymem             2.0.5
fastai            2.3.0
fastcore          1.3.19
fastprogress      1.0.0
idna              2.10
joblib            1.0.1
kiwisolver        1.3.1
matplotlib        3.4.1
murmurhash        1.0.5
packaging         20.9
pandas            1.2.4
plac              1.1.3
preshed           3.0.5
pyparsing         2.4.7
python-dateutil   2.8.1
pytz              2021.1
PyYAML            5.4.1
scikit-learn      0.24.1
scipy             1.6.2
spacy             2.3.5
srsly             1.0.5
thinc             7.4.5
threadpoolctl     2.1.0
torch             1.7.1
torchaudio        0.8.1
torchvision       0.8.2
tqdm              4.60.0
typing-extensions 3.7.4.3
wasabi            0.8.2
```

**Comment by tmabraham** [comment]
Everything looks fine to me. fastai does not support torch 1.8+ yet. It seems you have successfully installed fastai though...

**Comment by HiPhish** [comment]
Then the install instructions are wrong. I have not installed fastai using just `pip install fastai` without manually installing PyTorch first and it seems to be working. Could have saved me a lot of frustration. Should I leave this issue open until the installation instructions are fixed?

**Comment by tcapelle** [comment]
This is an issue, had the same problem last week on a fresh VM.

**Comment by hellocybernetics** [comment]
1. fastai does not support torch 1.8+ yet, therefore torch 1.8 was uninstalled and 1.7 was installed.
2. torchaudio which was installed before running `pip install fastai` does not support torch 1.7.
3. That is a dependency conflict. 

This problem is not due to fastai install instructions. If you only had run `pip install torch` before `pip install fastai`, everything was fine. Do you need torchaudio really? If yes, you can install torchaudio 0.7.x.

`pip uninstall torchaudio`
`pip install torchaudio==0.7.2

**Comment by tmabraham** [comment]
Is this issue relevant anymore @HiPhish? Fastai just added support for the latest PyTorch packages...

**Comment by HiPhish** [comment]
As far as I am concerned the issue is that the installation instructions are wrong. It says:

> If you install with pip, you should install PyTorch first by following the PyTorch [installation instructions](https://pytorch.org/get-started/locally/).

This extra step is what caused the problem, so the documentation should be fixed to not included that sentence. You can create a separate issue and close this one if you think it is more appropriate.

**Comment by tcapelle** [comment]
I think this is not an issue anymore @jph00
