### ISSUE TITLE
Upgrade to spacy 3.x

### ISSUE THREAD

**Issue by rosbo** [fastai/fastai#3338]
Hi,

I am an engineer on the [Kaggle Notebooks](https://www.kaggle.com/code) team. 

We maintain a Docker image with several data science packages pre-installed for the Kaggle notebooks environment.

We want to upgrade the `spacy` package to 3.x.

However, `fastai` has a strict dependency on `spacy<3`: https://github.com/fastai/fastai/blob/41e5e9cf7d7be8f33f2ea28f8c8a8bfdbecc719a/settings.ini#L16

Is it on your radar to add support for `spacy` 3.x?

Thread about upgrading `spacy` on the Kaggle docker python image repo: https://github.com/Kaggle/docker-python/issues/986

Thank you

**Comment by jph00** [comment]
Thanks @rosbo . I'll take a look and see how much work it'll be to support spacy3.

**Comment by jph00** [comment]
@rosbo this is now done - use fastai 2.3.1 for compat with spacy3

**Comment by rosbo** [comment]
Thanks @jph00 for the quick turnaround on this.
