### ISSUE TITLE
downloading imagenette2-160.tgz results in "file download is broken" error

### ISSUE THREAD

**Issue by tfriedel** [fastai/fastai#3369]
Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): YES
This is happening with fastai 2.3.1 on windows. 

**Describe the bug**
Trying to download Imagenette 160 results in an error "File download is broken". Checksum of downloaded file doesn't match the file in checks.txt.

**To Reproduce**
```dls = get_data(URLs.IMAGENETTE_160, 160, 128)```

**Expected behavior**
The file is downloaded successfully.

**Error with full stack trace**

```
A new version of this dataset is available, downloading...

File downloaded is broken. Remove C:\Users\Thomas\.fastai\archive\imagenette2-160.tgz and try again.
Due to IPython and Windows limitation, python multiprocessing isn't available now.
So `number_workers` is changed to 0 to avoid getting stuck

```

**Additional context**
I looked in `checks.txt` and the checksum for the file is this:
```
  "https://s3.amazonaws.com/fast-ai-imageclas/imagenette2-160.tgz": [
    8388608,
    "e28cd4207d545c64f2372bcb64753d01"
  ],
```
But running _check_file on the downloaded file returns this:
```[99003388, 'c475f8f7617a200ba35b9facc48443c3']```

**Comment by jph00** [comment]
I believe that's fixed now. Thanks for the report.
