### ISSUE TITLE
Multiprocessing is not maintaining any metadata

### ISSUE THREAD

**Issue by muellerzr** [fastai/fastai#3382]
Prime example of this behavior:

`TensorPoint`'s keep track of the `img_size` of some tensor When `num_workers` is set to zero, said image size can be seen on the output tensor, but when it is 1+, this is gone.

Attached are two minimal gists, one is from myself and DomMK on the fastai discord:

TensorPoint example: https://gist.github.com/muellerzr/cde7943738848eb3e435dbbb0391be9d

Generic example (by Dom): https://gist.github.com/muellerzr/cde7943738848eb3e435dbbb0391be9d

As well as minimal code to get the TensorPoint issue is below:

```python
from fastai.vision.all import *

path = untar_data(URLs.BIWI_HEAD_POSE)
img_files = get_image_files(path)
def img2pose(x): return Path(f'{str(x)[:-7]}pose.txt')
cal = np.genfromtxt(path/'01'/'rgb.cal', skip_footer=6)
def get_ctr(f):
    ctr = np.genfromtxt(img2pose(f), skip_header=3)
    c1 = ctr[0] * cal[0][0]/ctr[2] + cal[0][2]
    c2 = ctr[1] * cal[1][1]/ctr[2] + cal[1][2]
    return tensor([c1,c2])

biwi = DataBlock(
    blocks=(ImageBlock, PointBlock),
    get_items=get_image_files,
    get_y=get_ctr,
    splitter=FuncSplitter(lambda o: o.parent.name=='13'),
    batch_tfms=[*aug_transforms(size=(240,320)), 
                Normalize.from_stats(*imagenet_stats)])

dls_a = biwi.dataloaders(path, num_workers=0)
dls_b = biwi.dataloaders(path, num_workers=1)

o = next(iter(dls_a[0]))
print(o[1].img_size)

o = next(iter(dls_b[0]))
print(o[1].img_size)

**Comment by kevinbird15** [comment]
This is also an issue in fastaudio with an open issue over there as well.  

https://github.com/fastaudio/fastaudio/issues/95
