### ISSUE TITLE
1.8 Pythoch related bug on TensorBBox and TensorMultiCategory transform

### ISSUE THREAD

**Issue by MarkB2** [fastai/fastai#3384]
Standard object detection datablock throws exception
```
pascal = DataBlock(blocks=(ImageBlock, BBoxBlock, BBoxLblBlock),
                 splitter=RandomSplitter(),
                 get_items=get_train_imgs,
                 getters=getters,
                 item_tfms=item_tfms,
                 batch_tfms=batch_tfms,
                 n_inp=1)
dls = pascal.dataloaders(path/'train')

Could not do one pass in your dataloader, there is something wrong in it
```

**To Reproduce**
```
from fastai.vision.all import *
bbox = TensorBBox.create([10,10,20,20])
label = TensorMultiCategory([1,0,0])
clip_remove_empty(bbox, label)
```

**Expected behavior**

**Error with full stack trace**

Place between these lines with triple backticks:

```
TypeError                                 Traceback (most recent call last)

<ipython-input-9-b73fdd196d01> in <module>()
      2 bbox = TensorBBox.create([10,10,20,20])
      3 label = TensorMultiCategory([1,0,0])
----> 4 clip_remove_empty(bbox, label)

/usr/local/lib/python3.7/dist-packages/fastai/vision/data.py in clip_remove_empty(bbox, label)
     33     bbox = torch.clamp(bbox, -1, 1)
     34     empty = ((bbox[...,2] - bbox[...,0])*(bbox[...,3] - bbox[...,1]) <= 0.)
---> 35     return (bbox[~empty], label[~empty])
     36 
     37 # Cell

TypeError: no implementation found for 'torch.Tensor.__getitem__' on types that implement __torch_function__: [TensorMultiCategory, TensorBBox]

```

**Additional context**

**Comment by kevinbird15** [comment]
I have just ran into this same issue using fastai 2.3.1 and torch 1.8.1

**Comment by kevinbird15** [comment]
I believe the breaking example should actually be: 
```
from fastai.vision.all import *
bbox = TensorBBox.create([[10,10,20,20]])
label = TensorMultiCategory([[1,0,0]])
clip_remove_empty(bbox, label)
```

which works with fastai 2.1.8 and torch 1.7.0

**Comment by kevinbird15** [comment]
This is the piece that it actually fails on: 
```
label[~empty]
```

Here's a slightly more minimal code to reproduce: 
```
label = TensorMultiCategory([[1,0,0]])
empty = TensorBBox([True])
label[~empty]
```

**Comment by kevinbird15** [comment]
Still trying to think through this, but I think we are running into this so maybe we need to somehow implement how some of this should work?  I'm not sure 

https://pytorch.org/docs/stable/notes/extending.html#extending-torch

Here are the old docs (https://pytorch.org/docs/1.7.1/notes/extending.html?highlight=extending#extending-torch)

**Comment by kevinbird15** [comment]
They seem to be pretty similar, but not quite identical

**Comment by tcapelle** [comment]
I saw this some time ago, the indexing is not automatically inherited between tensor sublclasses. The quick fix is to cast the indexer to Tensor, but it is not very clean.

**Comment by thatgeeman** [comment]
Ran into the same issue in the [bounding box tutorial](https://docs.fast.ai/tutorial.datablock.html#Bounding-boxes). 
fastai==2.3.1
torch==1.8.1

**Comment by kevinbird15** [comment]
Another (possibly better?) option to solve this is to register this function:

```
TensorMultiCategory.register_func(Tensor.__getitem__, TensorMultiCategory, TensorBBox)
```

(Thanks @riven314 for finding this solution)

**Comment by anashas** [comment]
> Another (possibly better?) option to solve this is to register this function:
> 
> ```
> TensorMultiCategory.register_func(Tensor.__getitem__, TensorMultiCategory, TensorBBox)
> ```
> 
> (Thanks @riven314 for finding this solution)

I was facing a similar issue, but this did fix it. Thank you
