### ISSUE TITLE
document expected inputs 

### ISSUE THREAD

**Issue by DanTaranis** [fastai/fastai#3387]
I am a pytroch user. 
I'm trying out fast ai's framework to work faster on basic vision tasks. 

The documentation is huge but useless. 
Please! please! add a specification of what each input to each class\function should be. 
For 2 days I've just been trying to guess what each function expects. The code is ultra obscured in inheritance of obfuscated classes so it's incredibly hard to reverse engineer the input specifications as well. 

Numpy for example does an amazing job at this. I really suggest following their lead. Each function lists out each of the inputs and specify their type and a sentence or two of what they do. Check out [this](https://numpy.org/doc/stable/reference/generated/numpy.roll.html) for example.

For example - DataBlock - seems super useful and great. But then the documentation is "You may also need to include get_x and get_y or a more generic list of getters that are applied to the results of get_items."  Now I need to spend 3 hours to figure out what get_x and get_y may look like and how they relate to get_items (another unknown). Why not specify:
 
get_x : function, gets a dataset df row as an input, outputs a path as string. Used with ....blah blah

Thanks,
Dan

**Comment by tcapelle** [comment]
Most of fastai documentation is by examples, tutorials and courses. It is indeed not easy for someone that just want to try one functionality out of the box without reading the notebooks. The `DataBlock` is indeed pretty powerful.  I would recommend reading this tutorial: https://docs.fast.ai/tutorial.datablock.html

**Comment by bjornasm** [comment]
Is it correct to close this issue as completed @jph00  ? The issue is asking for better documentation of inputs, while they got help for their example, I can't see that it solves their actual problem:

>The documentation is huge but useless.
Please! please! add a specification of what each input to each class\function should be.
For 2 days I've just been trying to guess what each function expects. The code is ultra obscured in inheritance of obfuscated classes so it's incredibly hard to reverse engineer the input specifications as well.

>Numpy for example does an amazing job at this. I really suggest following their lead. Each function lists out each of the inputs and specify their type and a sentence or two of what they do. Check out [this](https://numpy.org/doc/stable/reference/generated/numpy.roll.html) for example.
