### ISSUE TITLE
Unable to install due to broken dependancy (Bottleneck)

### ISSUE THREAD

**Issue by jeettrivedi** [fastai/fastai#3391]
Was attempting to install the package in a fresh virtual environment and can't seem to get it install. The install gets stuck at the Bottleneck installation steps. It then successively attempts to install older and older versions until a point where the installer fails (either due to exhausting available versions or some installer retry limit). You can see the output of the installer [here](https://github.com/fastai/fastai/files/6567725/error.txt). Here is the commands to reproduce the error. The last command is where it fails.
```
python -m virtualenv bug_rep
source bug_rep/bin/activate
pip3 install torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
pip install fastai==1.0.61
```

Any help will be greatly appreciated. I've attempted to install Bottleneck using the .whl download on their website but that seems to fail as well.

**Comment by tmabraham** [comment]
fastai v1 isn't supported anymore... please use the latest version of fastai if possible...
