### ISSUE TITLE
Fast-ai PyTorch version compatibility 

### ISSUE THREAD

**Issue by mansimane** [fastai/fastai#3402]
Hi, 
1. When I try to install fastai 2.3.1, with pytorch 1.9 release candidate, I get warning that 
fastai 2.3.1 requires torch<1.9,>=1.7.0, but you have torch 1.9.0 which is incompatible. Will fast ai release new version which would be compatible with pytorch 1.9?

2. If I install fastai 1.0.61 with pytorch 1.9 release candidate, I do not get any such warning. Does this mean fastai  1.0.61 is compatible with pytorch 1.9 or it is incompatible but warning is not printed? 

Where can I find pytorch-fastai compatibility table?

**Comment by tmabraham** [comment]
@mansimane fastai usually adds support for the latest version of pytorch soon after it's released. pytorch 1.9 release was just added

fastai v1 is no longer supported (except for bug fixes) and will likely not be compatible with the latest versions of pytorch

**Comment by jph00** [comment]
generally you can use the latest fastai with the latest released version of pytorch.
