### ISSUE TITLE
Depreciate Mish JIT support for native PyTorch 1.9 version

### ISSUE THREAD

**Issue by digantamisra98** [fastai/fastai#3403]
With Mish now being supported out of the box in PyTorch 1.9, the JIT version present in Fast AI should be removed to keep it synchronous and use the [`nn.Mish()`](https://pytorch.org/docs/stable/generated/torch.nn.Mish.html?highlight=mish#torch.nn.Mish) version instead. 

Happy to submit a PR if this will be approved.

**Comment by tcapelle** [comment]
you made Mish to nn, congratz!

**Comment by digantamisra98** [comment]
Thank you! @tcapelle

**Comment by jph00** [comment]
Thanks @digantamisra98. In order to avoid changing the version dependency, how about having fastai delegate to the PyTorch version if it's 1.9 or greater, and use its internal implementation otherwise? If that sounds OK, I'd be happy to take a PR that does that.

**Comment by digantamisra98** [comment]
Sure, that makes sense. I will submit a PR at the earliest, thanks!

**Comment by tmabraham** [comment]
@jph00 I think this issue can be closed thanks to your commit https://github.com/fastai/fastai/commit/f09e11907646d262f5161176045aa575891a244d
