### ISSUE TITLE
The docs are not rendered without JavaScript enabled

### ISSUE THREAD

**Issue by KOLANICH** [fastai/fastai#3432]
Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): Don't use fastai at all currrhtly.

**Describe the bug**
The docs are not rendered without JavaScript enabled

**To Reproduce**
1. Disable JS in your browser
2. Visit https://docs.fast.ai/quick_start.html
3. Enjoy lack of docs.

**Expected behavior**
The docs should be rendered.

**Comment by jph00** [comment]
we won't be changing this
