### ISSUE TITLE
Hit error in course ml1, lesson 1

### ISSUE THREAD

**Issue by kechan** [fastai/fastai#344]
When trying to draw the decision tree:

draw_tree(m.estimators_[0], df_trn)

I got an error: CalledProcessError: Command '['dot', '-Tsvg']' returned non-zero exit status 1

I have brew install graphviz to get the latest and my "dot" is:

      dot - graphviz version 2.40.1 (20161225.0304)

Anyone know what I can do to solve this? 

Thanks.

**Comment by jph00** [comment]
Use the forums
