### ISSUE TITLE
Unable to access docs.fast.ai

### ISSUE THREAD

**Issue by chendingyan** [fastai/fastai#3467]
**Describe the bug**
Can not access to https://docs.fast.ai/ 
**To Reproduce**
1. just use browers to access docs website
![image](https://user-images.githubusercontent.com/16874978/130315904-facbabe9-48e6-4400-800c-fc89843fd897.png)

**Comment by muellerzr** [comment]
This can be closed now, Jeremy fixed this. The entire documentation was down. 

cc @jph00
