### ISSUE TITLE
Docs not loading on the website

### ISSUE THREAD

**Issue by ElisonSherton** [fastai/fastai#3468]
Hey guys,

Good Day!

I was trying to access `item_tfms` documentation on `docs.fast.ai` but got this error as follows.

![image](https://user-images.githubusercontent.com/45599762/130321377-63a3c922-47a0-4257-8d01-6b0ecb80158d.png)

Thanks,
Vinayak

**Comment by wassafshahzad** [comment]
HI is this issue open  and can I start working on it ?

**Comment by muellerzr** [comment]
This is closed now, Jeremy fixed this. The entire documentation was down. 

cc @jph00
