### ISSUE TITLE
new version of torchvision moves torchvision.models.utils

### ISSUE THREAD

**Issue by dalupus** [fastai/fastai#3507]
Be sure you've searched [the forums](https://forums.fast.ai) for the error message you received. Also, unless you're an experienced fastai developer, first ask on the forums to see if someone else has seen a similar issue already and knows how to solve it. **Only file a bug report here when you're quite confident it's not an issue with your local setup.**

**Please see [this model example](https://github.com/fastai/fastai2/issues/487) of how to fill out an issue correctly.  Please try to emulate that example as appropriate when opening an issue.**

Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): YES / NO

**Describe the bug**
The new version of torchvision moves the torchvision.models.utils package.
This causes a problem when doing `from fastai.vision.all import *`

specifically the issue appears to be related to https://github.com/fastai/fastai/blob/master/fastai/vision/models/xresnet.py#L13
which does `from torchvision.models.utils import load_state_dict_from_url`

This particular function appears to have been moved to `torchvision._internally_replaced_utils` which is then just pulling the function from `torch.hub`

**To Reproduce**
1.   `from fastai.vision.all import *`

**Expected behavior**
import without error

`ModuleNotFoundError: No module named 'torchvision.models.utils'`

**Additional context**

**Comment by DanTaranis** [comment]
I still get this issue - fast ai version '2.5.2'

**Comment by AleksBro** [comment]
I've tried to run the example from the book. I've run pip install fastai and I still get this error:

`    from fastai.vision.all import *
  File "C:\Python311\Lib\site-packages\fastai\vision\all.py", line 1, in <module>
    from . import models
  File "C:\Python311\Lib\site-packages\fastai\vision\models\__init__.py", line 1, in <module>
    from . import xresnet
  File "C:\Python311\Lib\site-packages\fastai\vision\models\xresnet.py", line 13, in <module>
    from torchvision.models.utils import load_state_dict_from_url
ModuleNotFoundError: No module named 'torchvision.models.utils'`
