### ISSUE TITLE
interp.plot_top_losses show only one image, other's blank

### ISSUE THREAD

**Issue by cimenzhong** [fastai/fastai#3523]
![2021-11-08 10-04-54屏幕截图](https://user-images.githubusercontent.com/9363904/140673317-9fc29a1a-5bf1-4ec2-b33e-ea5b1b4af1d8.png)

change this version (in file fastai/interpret.py)
```python
plot_top_losses(x, y, its, outs.itemgot(slice(len(inps), None)), L(self.preds).itemgot(idx), losses,  **kwargs)
```
to earlier version code
```python
plot_top_losses(x, y, its, outs.itemgot(slice(len(inps), None)), self.preds[idx], losses,  **kwargs)
```
will be normal to show images.

**Comment by Rebolforces** [comment]
@jph00 I think this can be closed. or maybe keep open until released?
It was reverted on the 29th Oct  
https://github.com/fastai/fastai/commit/841dd664ceb73b2dc5d246735acc3c720689b35c

**Comment by opassos** [comment]
I am still having problems using `plot_top_losses`. Am I doing something wrong?

**Comment by rvalieris** [comment]
seems like there's no new release since the fix, so its still an issue.

**Comment by jph00** [comment]
Released now.
