### ISSUE TITLE
tabular learner predictions

### ISSUE THREAD

**Issue by cconstantinou73** [fastai/fastai#3524]
Be sure you've searched [the forums](https://forums.fast.ai) for the error message you received. Also, unless you're an experienced fastai developer, first ask on the forums to see if someone else has seen a similar issue already and knows how to solve it. **Only file a bug report here when you're quite confident it's not an issue with your local setup.**

**Please see [this model example](https://github.com/fastai/fastai2/issues/487) of how to fill out an issue correctly.  Please try to emulate that example as appropriate when opening an issue.**

Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): YES / NO
my version is:
fastai version: 2.5.2

**Describe the bug**
hello i am using fastai tabular for a classification problem. By searching online i found 2 ways on how to do inference once you have trained a model. One of the predicts one point at a time and the other many. Can someone help with the following code example i prepared? My question is why when i use the second method of prediction (i.e the fast one multiple predictions at a time) i dont get the same predictions as when using the method of predicting one by one. Also if you see in the example with the fast method ('get_preds') i get 100 percent accuracy while i have trained for only one epoch which doesnt make sense. This will only work if the labels are used somehow like being return in the output.

**To Reproduce**
```
import os 
import numpy as np
import pandas as pd

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import fastai
from fastai.tabular.all import *


# import some data to play with
iris = datasets.load_iris()
X = iris.data[:] 
y = iris.target

data_df = pd.DataFrame(data=X,columns=[f'feat_{i}' for i in range(X.shape[1])])

# numerical features
num_cols = list(data_df.columns)

# addinng dummy categorical feature
data_df['feat_4'] = [np.random.choice(['a','b','c']) for i in range(len(data_df))]

cat_cols = ['feat_4']

# adding y
data_df['target'] = y
target_name ='target'

# split data to train and test
df_train,df_test = train_test_split(data_df,test_size=0.2)


# perform train validation split
splits = RandomSplitter(valid_pct=0.2)(range_of(df_train))


to = TabularPandas(df_train, 
                   procs=[Categorify, FillMissing,Normalize],
                   cat_names=cat_cols,
                   cont_names=num_cols,
                   y_names=target_name,
                   splits=splits,
                   device='cpu',
                   y_block = CategoryBlock()
                  )


# choose batch size for training
dls = to.dataloaders(bs=32)

# define  model (automated through tabular_learner)
learn = tabular_learner(dls,metrics=accuracy )
# fit for 1 epoch
learn.fit(1)

# test data
df_test = df_test.reset_index(drop=True)


# predictions one by one

y_preds_test_1 = []
for i in range(len(df_test)):
    
    row, clas, probs = learn.predict(df_test.iloc[i])
    y_preds_test_1.append(clas)

# get predictions to array
y_preds_test_1 = np.array([i.item() for i in y_preds_test_1])
    
# predictions many
test_dl_l = learn.dls.test_dl(df_test)

# here we get logits and predictions
y_preds_test_2 = learn.get_preds(dl=test_dl_l)

# isolate predictions
y_preds_test_2 = y_preds_test_2[1].flatten().numpy()

# true values
y_true = df_test['target'].values

print('fastai version:',fastai.__version__)
print(f'accuracy predicitons one by one:  {(y_true == y_preds_test_1).mean()}')
print(f'accuracy predicitons many: {(y_true == y_preds_test_2).mean()}')

assert np.all(y_preds_test_1 == y_preds_test_2), 'Not the same'
```

**Expected behavior**
I expect the fast method 'get_preds' to give the same predictions as the method when predicting one by one ('predict')

**Error with full stack trace**

Place between these lines with triple backticks:

```
#################################################
the output i get when running the code above is:
fastai version: 2.5.2
accuracy predicitons one by one:  0.9333333333333333
accuracy predicitons many: 1.0
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_83439/1487418880.py in <module>
     91 print(f'accuracy predicitons many: {(y_true == y_preds_test_2).mean()}')
     92 
---> 93 assert np.all(y_preds_test_1 == y_preds_test_2), 'Not the same'
     94 

AssertionError: Not the same
```

**Additional context**
This happens to me only for classification . 
For regression i get the expected behaviour

**Comment by warner-benjamin** [comment]
Hi @cconstantinou73,

[`Learner.get_preds`](https://docs.fast.ai/learner.html#Learner.get_preds) returns a tuple of predictions and targets. The example scores a perfect accuracy because the code here:
```python
# isolate predictions
y_preds_test_2 = y_preds_test_2[1].flatten().numpy()
```
uses the targets, not the predictions. Comparing the returned predictions from `Learner.get_preds` will result in the same accuracy as looping over `Learner.predict` to generate the predictions.

**Comment by cconstantinou73** [comment]
Ok thanks that makes sense now! I assumed a "get_preds" call would only output predictions as i already have the target values from the df_test and that the second element of the tuple was the argmax() operation on the logits (fisrt element of the output tuple)
