### ISSUE TITLE
No module named 'fastai.core'

### ISSUE THREAD

**Issue by JerryLeolfl** [fastai/fastai#3525]
I installed fastai version 2.5.3. When I import fastai.core, it gives the "No module named 'fastai.core'" output.
Do you know what happend?

**Comment by zhaoshaojun** [comment]
There is a fastcore package. Could you try install that and try?

**Comment by JerryLeolfl** [comment]
> 

Thanks for your reply and could you please tell me how to install it?

**Comment by JerryLeolfl** [comment]
> > 
> 
> Thanks for your reply and could you please tell me how to install it?

Ok, I got it. But it is fastcore. That means I should turn the code "import fastai.core" to "import fastcore"?

**Comment by tmabraham** [comment]
Why are you trying to import fastai.core? The old version of fastai had a fastai.core module but not the current, v2 version.

**Comment by JerryLeolfl** [comment]
> Why are you trying to import fastai.core? The old version of fastai had a fastai.core module but not the current, v2 version.

Yes, I installed the version 1.0.51. The problem is solved now.

**Comment by tmabraham** [comment]
Okay please close the issue if the problem is resolved...
