### ISSUE TITLE
fastai에 대한 쉬운 접근을 위하여 한글로 번역하고 싶습니다.

### ISSUE THREAD

**Issue by neeeelt** [fastai/fastai#3533]
Feature requests should first be proposed on [the forum](https://forums.fast.ai). 

**Link to forum discussion.**

Please place URL here.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or code examples about the feature request here.

**Comment by jph00** [comment]
We're not doing any translations at the moment, but thanks for the offer.
