### ISSUE TITLE
Running FastAi on google colab, can't import * from fastai.tabular.all!

### ISSUE THREAD

**Issue by Abelcanc3rhack3r** [fastai/fastai#3535]
Be sure you've searched [the forums](https://forums.fast.ai) for the error message you received. Also, unless you're an experienced fastai developer, first ask on the forums to see if someone else has seen a similar issue already and knows how to solve it. **Only file a bug report here when you're quite confident it's not an issue with your local setup.**

**Please see [this model example](https://github.com/fastai/fastai2/issues/487) of how to fill out an issue correctly.  Please try to emulate that example as appropriate when opening an issue.**

Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): YES / NO
I pip install: pip install fastai on google colab

**Describe the bug**
After pip install fast ai on google colab, I write:
from fastai.tabular.all import *

Then it says:

**To Reproduce**
1. !pip install fastai
from fastai.tabular.all import *

**Expected behavior**
It can import

**Error with full stack trace**

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-3be3f09dbd5a> in <module>()
      1 # This file contains all the main external libs we'll use
----> 2 from fastai.tabular.all import *

ModuleNotFoundError: No module named 'fastai.tabular.all'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

```
```

**Additional context**

**Comment by warner-benjamin** [comment]
You need to upgrade the fastai install from Colab's default of fastai v1 to fastai v2:

```
!pip install fastai --upgrade
```

**Comment by strickvl** [comment]
I had the same with `fastai.vision.all`. This fix worked for me as well.

**Comment by Rebolforces** [comment]
@jph00 Can be closed.

**Comment by asif-nuaa** [comment]
I am getting following error on vastai. 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 from fastai.vision.all import *

File /opt/conda/lib/python3.10/site-packages/fastai/vision/all.py:1
----> 1 from . import models
      2 from ..basics import *
      3 from ..callback.all import *

File /opt/conda/lib/python3.10/site-packages/fastai/vision/models/__init__.py:2
      1 from . import xresnet
----> 2 from . import unet
      3 from .tvm import *

File /opt/conda/lib/python3.10/site-packages/fastai/vision/models/unet.py:12
     10 # %% ../../../nbs/15a_vision.models.unet.ipynb #022403b1
     11 from ...torch_basics import *
---> 12 from ...callback.hook import *
     14 # %% ../../../nbs/15a_vision.models.unet.ipynb #c317474a
     15 def _get_sz_change_idxs(sizes):

File /opt/conda/lib/python3.10/site-packages/fastai/callback/hook.py:12
      8 __all__ = ['Hook', 'hook_output', 'Hooks', 'hook_outputs', 'dummy_eval', 'model_sizes', 'num_features_model', 'has_params',
      9            'HookCallback', 'total_params', 'layer_info', 'module_summary', 'ActivationStats']
     11 # %% ../../nbs/15_callback.hook.ipynb #19fb2c41
---> 12 from ..basics import *
     14 # %% ../../nbs/15_callback.hook.ipynb #e4cd49d7
     15 @docs
     16 class Hook():

File /opt/conda/lib/python3.10/site-packages/fastai/basics.py:1
----> 1 from .data.all import *
      2 from .optimizer import *
      3 from .callback.core import *

File /opt/conda/lib/python3.10/site-packages/fastai/data/all.py:5
      3 from .load import *
      4 from .external import *
----> 5 from .transforms import *
      6 from .block import *

File /opt/conda/lib/python3.10/site-packages/fastai/data/transforms.py:367
    363     return [f(tensor(o).view(*v)) for o in t]
    365 # %% ../../nbs/05_data.transforms.ipynb #d365cc25
    366 @docs
--> 367 class Normalize(DisplayedTransform):
    368     "Normalize/denorm batch of `TensorImage`"
    369     parameters,order = L('mean', 'std'),99

File /opt/conda/lib/python3.10/site-packages/fastcore/foundation.py:61, in docs(cls)
     59 def docs(cls):
     60     "Decorator version of `add_docs`, using `_docs` dict"
---> 61     add_docs(cls, **cls._docs)
     62     return cls

File /opt/conda/lib/python3.10/site-packages/fastcore/foundation.py:51, in add_docs(cls, cls_doc, **docs)
     49     f = getattr(cls,k)
     50     if hasattr(f,'__func__'): f = f.__func__ # required for class methods
---> 51     f.__doc__ = v
     52 # List of public callables without docstring
     53 nodoc = [c for n,c in vars(cls).items() if callable(c)
     54          and not n.startswith('_') and c.__doc__ is None]

AttributeError: 'Function' object attribute '__doc__' is read-only
```
This code is working fine in google colab, but not working in vastai instances. even I have changed many templates. The error appears on the statement. 

`from fastai.vision.all import *`

**Comment by jph00** [comment]
Fixed now. Was a bug in an upstream lib
