### ISSUE TITLE
How to deal with test data without labels or tags?

### ISSUE THREAD

**Issue by changebio** [fastai/fastai#355]
https://github.com/fastai/fastai/blob/8f18b021a7f0ea11880aa0559cf1df3148229419/fastai/dataset.py#L476
Got a error, when I predict test data without labels which are in a folder, ‘test’.
Have any ideas? Thanks

tfms = tfms_from_model(f_model, sz, crop_type=CropType.NO, tfm_y=tfm_y, aug_tfms=augs)
md = ImageClassifierData.from_csv(PATH, JPEGS, BB_CSV, tfms=tfms, continuous=True,test_name=‘test’)

learn.predict(is_test=True)

**IndexError: index 2 is out of bounds for axis 0 with size 1**

Why don't you use code the following in from_paths method to deal with test data without labels or tags?
        if test_name:
            test = folder_source(path, test_name) if test_with_labels else read_dir(path, test_name)
        else: test = None

**Comment by jph00** [comment]
Please use the forums
