### ISSUE TITLE
NameError: name 'get_transforms' is not defined

### ISSUE THREAD

**Issue by Summiya-Batool** [fastai/fastai#3555]
Be sure you've searched [the forums](https://forums.fast.ai) for the error message you received. Also, unless you're an experienced fastai developer, first ask on the forums to see if someone else has seen a similar issue already and knows how to solve it. **Only file a bug report here when you're quite confident it's not an issue with your local setup.**

**Please see [this model example](https://github.com/fastai/fastai2/issues/487) of how to fill out an issue correctly.  Please try to emulate that example as appropriate when opening an issue.**

Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): YES / NO

**Describe the bug**

**To Reproduce**
1. 

**Expected behavior**

**Error with full stack trace**

Place between these lines with triple backticks:

```
```

**Additional context**

**Comment by tmabraham** [comment]
Please provide more details for us to be able to help you otherwise we'll close this issue...

**Comment by imvishal09** [comment]
> Please provide more details for us to be able to help you otherwise we'll close this issue... pls have a look

![image](https://user-images.githubusercontent.com/39182918/167660344-4a29788b-2dd9-4fd3-8d74-a8decfb3daa3.png)

**Comment by tmabraham** [comment]
@jph00 you can close this...
no additional details are being provided and I am going to assume this is an error of trying to use fastai v1 code with fastai v2 (`get_transforms` is from fastai v1)

**Comment by Summiya-Batool** [comment]
Previously I was not enabled to form dataloader (Fastai) for classification
of data in jupyter notebook now code is running. Can you tell me is there
any code of classification through fastai for test dataset?
