### ISSUE TITLE
CUDA capability sm_86 is not compatible with the current PyTorch installation

### ISSUE THREAD

**Issue by renjiege** [fastai/fastai#3570]
Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): YES 

**Describe the bug**
when importing fastai vision
`from fastai.vision.all import *`
I have the warning that suggests CUDA is not compatible with the current Pytorch installation. 

**To Reproduce**
fastai == 2.3.1
python ==3.8

**Error with full stack trace**

Place between these lines with triple backticks:

```
UserWarning: 
GeForce RTX 3080 with CUDA capability **sm_86** is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the GeForce RTX 3080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
```

**Comment by kevinbird15** [comment]
How did you install fastai?  I have had success using light-the-torch to install pytorch.  Not sure if this is something fastai can resolve

**Comment by renjiege** [comment]
@kevinbird15  I did the following in my notebook:
```
import sys
!{sys.executable} -m pip install fastai
```

**Comment by eric-vanartsdalen** [comment]
This error is coming from Pytorch itself. You may have to find a version of Pytorch which supports compute compatibility 8.6...
See:
https://pytorch.org/get-started/locally/
Note: fastai setup.ini indicates the version of pytorch>=1.7.0,<1.11

Also any possible issues in Pytorch forums itself might help guide you.
https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen++%22RTX+3080%22

**Comment by renjiege** [comment]
Thanks, @eric-vanartsdalen. I upgraded the Pytorch version to '1.10.1+cu113'. Now the error becomes: 
`ModuleNotFoundError: No module named 'torchvision.models.utils'`

my torchvision version is:
`'0.11.2+cu113'`

**Comment by renjiege** [comment]
Upgrading fastai to 2.5.3 solves the problem
