### ISSUE TITLE
Gradio web demos in example notebooks

### ISSUE THREAD

**Issue by AK391** [fastai/fastai#3574]
Hi, would you be interested in adding [Gradio](https://github.com/gradio-app/gradio) to the example notebooks? Gradio is a fast way for developers to build ML apps in python and can be used inside colab or jupyter notebooks. Fastai users can quickly try out a example demos in Gradio before having to run a entire notebook as well as share the demo with others to use with a shareable link. Gradio demos can also be hosted for free on Huggingface Spaces, for more details see this blog post: https://huggingface.co/blog/gradio-spaces

we could also have a huggingface Spaces badge next to the colab badge to try out the web demo at the start of each tutorial 
<img width="897" alt="Screen Shot 2022-02-08 at 7 53 20 PM" src="https://user-images.githubusercontent.com/81195143/153101286-3333f574-1550-4faf-bf7a-28254075d42f.png">

**Comment by jph00** [comment]
Thanks @AK391 can you provide an example for one of fastai's notebooks, so I can see what it would look like?

**Comment by AK391** [comment]
@jph00 Thanks, here is a colab notebook for fastai applications - quick start with minimal gradio demos added for each section https://colab.research.google.com/drive/1jMpV7q8Jly-M21YFovv-aTomtfyg1ZLL?usp=sharing

 the actual models for each task on the quick start page could be "opened in Spaces" (https://huggingface.co/spaces) so that people can start interactively using the models in their browser. This would really make this quick start guide accessible to an even wider audience, e.g. those starting out in ML

the badges currently are not linked to a Space

<img width="832" alt="Screen Shot 2022-02-11 at 12 48 50 AM" src="https://user-images.githubusercontent.com/81195143/153543563-cf43f62a-9a81-48a2-ba90-3990bfa8e0c0.png">

**Comment by jph00** [comment]
Thanks - this doesn't look like a good fit for our docs, but I appreciate your time to discuss it
