### ISSUE TITLE
Jupiter Notebook issue

### ISSUE THREAD

**Issue by sardar-abdullah-698** [fastai/fastai#3594]
I have issue in running this code on jupiter notebook. please help m
![Capture](https://user-images.githubusercontent.com/62802607/155936576-6e91ec01-3e68-4e4a-9f46-f1b4f80ae183.PNG)
e

**Comment by kevinbird15** [comment]
ImageDataBunch is for fastai v1 so you will either need to download v1 or update your code to use something like [ImageDataLoaders](https://docs.fast.ai/vision.data.html#ImageDataLoaders.from_folder) instead

**Comment by tmabraham** [comment]
@jph00 you can close
