### ISSUE TITLE
W&B callback validation could be delayed?

### ISSUE THREAD

**Issue by hiromis** [fastai/fastai#3600]
Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): YES

**Describe the bug**
It is more of a request/question than a bug. 

I am currently following this flow that is in W&B documentation: 
http://wandb.me/artifacts-colab 

In step 3 "Log a Model", I want to create fastai `Learner` and log it to W&B. As you notice in their comment, they recommend not training at this point:

>We'll start by just initializing the model, not training it. That way, we can repeat the training while keeping everything else constant.

However, due to [this validation](https://github.com/fastai/fastai/blob/346e60231b954283e9780b7fac23bbe8dcb95396/fastai/callback/wandb.py#L25) in the constructor of the `WandbCallback`,  I cannot simply create a learner that has `WandbCallback` without initializing `wandb.run`. 

It seems as though these checks can be delayed till `before_fit` as we won't really need till somebody initiates `fit`. But I wanted to double-check before creating a PR.

**Comment by tcapelle** [comment]
You could just do:
```python
from fastai.callback.wandb import *

model_path = learn.save("non_trained_model.pt")

with wandb.init():
  log_model(model_path, "non_trained_model.pt")
```

**Comment by hiromis** [comment]
Thank you for chiming in 😊
Yes, I could initialize a run like that. Typically, when I am developing a function for creating a learner, there are many failures before I end up with something good. And if I kick off a run for every try, I end up with a bunch of runs in W&B that are not very useful (hence the question).

**Comment by kevin-b1rd** [comment]
This would be a nice modification to the current callback.  I don't think there are any downsides to this since it will still check, but not before it actually needs it
