### ISSUE TITLE
Broken link for Azure ML on https://docs.fast.ai/

### ISSUE THREAD

**Issue by hashiromer** [fastai/fastai#3614]
**Describe the bug**

The link https://docs.fast.ai/callback.azureml.html appears to be broken, the server returns a 404 response. 

**To Reproduce**

1. Go to https://docs.fast.ai/
2.  Under integrations, click on Azure ML

**Expected behavior**

Either the hyperlink should not appear on https://docs.fast.ai/ or the server should return an html page instead of returning a 404.

**Comment by johan12345** [comment]
I think the issue relates to [this commit](https://github.com/fastai/fastai/commit/ac905f74297296fd0d3a15282104bd33e978b4fc) from @jph00 which disabled the Azure ML callback (but did not remove the [link](https://github.com/fastai/fastai/blob/409a22a487a7807bb2d00bd688a1bfe7ccb8d01c/docs_src/sidebar.json#L122) from the navigation bar). However there seems to be no explanation as to why it was disabled...

**Comment by manisnesan** [comment]
Users reported having trouble installing fastai using the command pip install -e .[dev]. Specifically the issue was due to azureml module. See https://github.com/fastaidocsprint/fastai/pull/2#issuecomment-1039163535

**Comment by jph00** [comment]
Many thanks for letting us know - I've removed that from the sidebar now.
