### ISSUE TITLE
docs.fast.ai broken links in Text

### ISSUE THREAD

**Issue by WNoxchi** [fastai/fastai#3615]
Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): N/A

**Describe the bug**
Broken (404) links on the Text section of the docs.fast.ai site. All Text links broken (Core, Data, Learner, Models/Core, Models/AWD LSTM). Other section links, like Vision, are working.

**To Reproduce**
1. Go to https://docs.fast.ai
2. Click the Text side tab. 
3. Click any link under Text.

**Expected behavior**
A display of documentation for a Text subsection.

**Error with full stack trace**
N/A

**Additional context**
FastAI contributors may already know about this issue. The website asked to submit a bug report. This is not a local install issue.

**Comment by manisnesan** [comment]
This issue is resolved.

**Comment by tmabraham** [comment]
@jph00 please close
