### ISSUE TITLE
search_images_ddg() method argument 'max_images' not working properly. 

### ISSUE THREAD

**Issue by franfram** [fastai/fastai#3622]
search_images_ddg() method argument 'max_images' not working properly. No matter what integer you pass to the max_images argument, it always returns 100 URLs. 

This issue is also on fastai forums: 
https://forums.fast.ai/t/max-images-not-working-in-search-images-ddg-function/89538

Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): YES 

**Describe the bug**

**To Reproduce**
```
from fastbook import *
results = search_images_ddg('grizzly bear', max_images=2)
len(results)
```
**Expected behavior**
`len(results)` returns 2

**Error with full stack trace**
No error

```
```

**Additional context**
Tested on both Paperspace + Fast.ai and in local environment. 
Local environment versions:  
python: 3.8.13
fastai: 2.5.6
fastcore: 1.4.2

**Comment by jph00** [comment]
Should be fixed now.
