### ISSUE TITLE
torch.backends.mps.is_available() is the new torch.cuda.is_available()

### ISSUE THREAD

**Issue by geg00** [fastai/fastai#3662]
Feature requests should first be proposed on [the forum](https://forums.fast.ai). 

**Link to forum discussion.**

Please place URL here.
https://forums.fast.ai/t/fastai-on-apple-m1/86059/28?u=gerardo

**Is your feature request related to a problem? Please describe.**
When you use learner there is no way to select the device to be used 

learn = vision_learner(dls, resnet18, metrics=error_rate)

**Describe the solution you'd like**
It just goes to use CPU not the MPS

**Describe alternatives you've considered**
Availability to select a device 

**Additional context**
Add any other context or code examples about the feature request here.
https://forums.fast.ai/t/how-to-specify-gpu-like-pytorch-device-cuda-2-in-fastai/54379/2?u=gerardo

THIS IS FOR FASTAI ON APPLE M1 MAC

**Comment by jph00** [comment]
mac is not supported for fastai

**Comment by geg00** [comment]
Well that's disappointing
