### ISSUE TITLE
`learn.lr_find` does not work in distributed setup.

### ISSUE THREAD

**Issue by Outsiders17711** [fastai/fastai#3688]
**Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): YES**
Problem is visible in fastai v2.7.0, fastcore v1.4.5 and nbdev v1.2.9. The GitHub repositories were cloned.

**Describe the bug**
I tested the new integration of **accelerate** into fastai #3646 by @muellerzr using the examples provided [here](https://docs.fast.ai/distributed.html). While I was able to get `learn.fine_tune` and `learn.fit_flat_cos` to work without any issues, `learn.lr_find` got stuck.

**To Reproduce**

Run the first code in [this gist](https://gist.github.com/Outsiders17711/99954e5f15e3f91701c83d96a10c053d) using `accelerate launch accelerate_lr_find_1.py`

**Expected behavior**

I expected to get **four** printouts of the `lr_find` results -- I have 4 GPUs (0, 1, 2, 3) on my machine --  the code terminates and all GPU resources are released. 

However, I got three printouts, the resources on GPUs 1, 2, 3 were released, the resources on GPU 0 were not released (which is the main process with the missing printout) and the code did not terminate. It just got stuck with no error messages whatsoever. I had to forcefully terminate the code with `Ctrl+C`.

When I added `accelerate.wait_for_everyone` in the second code `accelerate_lr_find_2.py` in linked [gist](https://gist.github.com/Outsiders17711/99954e5f15e3f91701c83d96a10c053d), I got the forth printout. Still, the resources on GPU 0 were not released and the code did not terminate.

My thoughts:
I took a look at the [`fastai.distributed.py`](https://github.com/fastai/fastai/blob/master/fastai/distributed.py#L214) file and added a print statement to `line 214` after `self.detach_distributed`. 

The learner object was only detached for three GPUs with `learn.lr_find`. For `learn.fine_tune` and `learn.fit_flat_cos`, the learner object was detached for all GPUs and the code terminated as expected. For some reason, the main process/GPU isn't getting detached with `learn.lr_find`.

**Error with full stack trace**

As stated, the code just got stuck with no error messages. The stack trace below is the output when I forcefully terminated the code in the terminal.

Place between these lines with triple backticks:

```
(d-rhlu) oluwaleke@csep072172server1:~/outsiders17711/exps-distributed$ accelerate launch accelerate_lr_find_1.py
lrs.valley = 2.0892961401841603e-05 | lrs.slide = 9.999999747378752e-06
lrs.valley = 2.0892961401841603e-05 | lrs.slide = 9.999999747378752e-06
lrs.valley = 2.0892961401841603e-05 | lrs.slide = 9.999999747378752e-06
^CKilling subprocess 28221
Killing subprocess 28222
Killing subprocess 28223
Killing subprocess 28224
Main process received SIGINT, exiting
Traceback (most recent call last):
  File "/home/oluwaleke/anaconda3/envs/d-rhlu/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/oluwaleke/anaconda3/envs/d-rhlu/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/oluwaleke/anaconda3/envs/d-rhlu/lib/python3.8/site-packages/accelerate/commands/launch.py", line 528, in launch_command
    multi_gpu_launcher(args)
  File "/home/oluwaleke/anaconda3/envs/d-rhlu/lib/python3.8/site-packages/accelerate/commands/launch.py", line 277, in multi_gpu_launcher
    process.wait()
  File "/home/oluwaleke/anaconda3/envs/d-rhlu/lib/python3.8/subprocess.py", line 1079, in wait
    return self._wait(timeout=timeout)
  File "/home/oluwaleke/anaconda3/envs/d-rhlu/lib/python3.8/subprocess.py", line 1804, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/oluwaleke/anaconda3/envs/d-rhlu/lib/python3.8/subprocess.py", line 1762, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**Additional context**

I have checked the fastai forums but as the accelerate integration is quite new, I couldn't find any discussion about it.

@muellerzr

**Comment by muellerzr** [comment]
Hi @Outsiders17711! Can you confirm if the LR finder worked before the integration?

**Comment by Outsiders17711** [comment]
Hello @muellerzr,

Thank you for your response. 

I created a new environment to test the Accelerate integration. I have no issues with `learn.lr_find` in my usual working environment. 

I also tried running the code in the gist I provided without Accelerate i.e.  `python accelerate_lr_find_1.py` within the new environment. As expected, the training only occurred on GPU 0; `learn.lr_find` and `learn.fine_tune` worked okay; and the code terminated successfully. 

```
(d-rhlu) oluwaleke@csep072172server1:~/outsiders17711/exps-distributed$ python accelerate_lr_find_1.py
lrs.valley = 0.0010000000474974513 | lrs.slide = 0.003019951749593019559 3.0705]
epoch     train_loss  valid_loss  error_rate  accuracy  time
0         0.413860    0.244745    0.108931    0.891069  02:13
(d-rhlu) oluwaleke@csep072172server1:~/outsiders17711/exps-distributed$
```

**Comment by muellerzr** [comment]
Could we rename this to lr_find doesn't work in distributed setup then? 😄 I'll still try and work on it, but Accelerate isn't the root cause, it's a multiproc issue

**Comment by Outsiders17711** [comment]
Hello @muellerzr,

Done. 

I have been trying to switch my single GPU training code to a distributed one using Accelerate because my models are getting larger. I have gotten every other part of the code to work with Accelerate except LR Finder.  Any help will be much appreciated. 

Thank you. Cheers.

**Comment by muellerzr** [comment]
I'd recommend finding an lr first, then just use the distributed setup for
training :)

**Comment by Outsiders17711** [comment]
That sounds good.

Thing is, my training setup has several rounds with increasing image sizes. So I just call `lr_find` at the beginning of each round and use the `lrs.valley`. This approach has given the best model accuracies till date. It also makes the same code robust regardless of the dataset and image sizes.

Of course, if `lr_find` won't work, I will definitely have to use a workaround. Unfortunately. 😓 Thanks for the suggestion.

**Comment by muellerzr** [comment]
Perhaps maybe compare the LR's used to see if they're similar as you scale?

**Comment by muellerzr** [comment]
In the interim until a solution is available of course :)

**Comment by muellerzr** [comment]
@Outsiders17711 this pr will solve it: https://github.com/fastai/fastai/pull/3689

In the interim to try it out do:
```python
pip install git+https://github.com/muellerzr/fastai@distrib-fix
```

**Comment by Outsiders17711** [comment]
Hello @muellerzr,

Thanks for the quick fix. It worked like a charm. I really appreciate the time you took to look into the issue. 

Thanks again. Cheers!
