### ISSUE TITLE
How to use multiple Gpus together

### ISSUE THREAD

**Issue by dingdingdeding** [fastai/fastai#3705]
Please don't ask for help here. [Use the forums](https://forums.fast.ai)
i have two 3090, but the train only use one of the, i can appoint one by use os.environ['CUDA_VISIBLE_DEVICES']='0' or '1', when i use os.environ['CUDA_VISIBLE_DEVICES']='0,1'，only 0 be used, So, want should i do, use 0 and 1 Gpus together

**Comment by muellerzr** [comment]
You'd want the **distributed** training integration fastai has with Accelerate. 

- [The general docs are available here](https://docs.fast.ai/distributed.html)
- Tutorials with how to launch distributed training from a notebook [can be found here](https://docs.fast.ai/tutorial.distributed) that I personally recommend starting from. 
- Finally there's a number of examples with using the distributed training in a notebook [here](https://docs.fast.ai/distributed_app_examples) that follow the core examples from fastai. 

Just make sure you do `pip install accelerate` before starting!
