### ISSUE TITLE
accelerate and deepspeed support?

### ISSUE THREAD

**Issue by alleniver** [fastai/fastai#3714]
the demand for speed is getting higher and higher  now, can you support accelerate and deepspeed in fastai ? thanks

**Comment by alleniver** [comment]
huggingface and fastai are awesome,whether the deep integration of the two can be done is very beneficial to developers.

**Comment by jph00** [comment]
Accelerate is supported for distrib training now. Additional support will be in v3

**Comment by alleniver** [comment]
> 

oh i see, good job man! hah
