### ISSUE TITLE
Broken link to developer's guide

### ISSUE THREAD

**Issue by AnMeiDP** [fastai/fastai#3723]
**Describe the bug**
Broken link in the fastai Developement webpage

**To Reproduce**
1.  Go to this link: https://docs.fast.ai/dev/git.html
2. Below the table of contents the hyperlink  _developer's guide_ is broken, 404 Not Found error

**Expected behavior**
Lead me to a page where the developer's guide is

**Comment by alok620** [comment]
#3728

**Comment by hamelsmu** [comment]
This link is no longer broken
