### ISSUE TITLE
Use pillow-simd instead of pillow

### ISSUE THREAD

**Issue by jaidmin** [fastai/fastai#373]
I only found pillow used in dataset.py in the function resize_img, but that is used in the ImageData class, and thus in every image related model, as far as I understand. Given that torchvision also would profit from pillow-simd and Jeremy showed us the performance improvements with simd in last years course, I was wondering why it isn't used here. 

I could do a PR adding it.

Cheers

**Comment by jph00** [comment]
There isn't always up to date conda packages available and it's not always easy to compile.
