### ISSUE TITLE
Broken links to the source code in the docs

### ISSUE THREAD

**Issue by aleonfm** [fastai/fastai#3738]
**Describe the bug**
There are broken links to the source in some pages of the docs. I've noticed it happens for https://docs.fast.ai/learner.html and https://docs.fast.ai/layers.html.

**To Reproduce**
1. Go to https://docs.fast.ai/learner.html#Learner.fit
2. Click on the [source] link

**Expected behavior**
Go to a new page where I can see the source code.

**Error**
Go to https://docs.fast.ai/fastai/learner.py#L233, which gives a 404 error.

**Comment by tmabraham** [comment]
Issue fixed today, @jph00 you can close
