### ISSUE TITLE
union2tuple source code is not found in link provided in documentation page

### ISSUE THREAD

**Issue by hangjoni** [fastai/fastai#3740]
Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): YES 

**Describe the bug**
Was looking for the source code of union2tuple  , which is a helper function created and used in fastcore, documented at https://fastcore.fast.ai/basics.html#union2tuple

When clicking on the 'Source' link in documentation, was led to this page, which says it could not be found
https://fastcore.fast.ai/fastcore/basics.py#L326

**To Reproduce**
1. Go to https://fastcore.fast.ai/basics.html#union2tuple
2. Click on 'Source' to go to https://fastcore.fast.ai/fastcore/basics.py#L326

**Expected behavior**
Expected to see source code of union2tuple function

**Error with full stack trace**

```
Not Found
The requested URL was not found on this server.

If you found this broken link on a fast.ai site or search engine, please tell us about it by filing a [bug report here](https://github.com/fastai/fastai/issues/new/choose).
```

**Additional context**
Was using setup_comp function provided in fastkaggle
setup_comp(comp, install='"timm>=0.6.2.dev0" "fastcore>=1.4.5" "fastai>=2.7.1"')

This produced the error: NameError: name 'union2tuple' is not defined
This was why I went to look for the union2tuple source code

**Comment by tmabraham** [comment]
This should have been an issue under https://github.com/fastai/fastcore but anyway this issue was resolved today. 

@jph00 you can close

**Comment by davidgilbertson** [comment]
I'm getting the error `name 'union2tuple' is not defined` in a Kaggle Notebook clone from the [Course notebook](https://www.kaggle.com/code/jhoward/is-it-a-bird-creating-a-model-from-your-own-data), is that related to this, or a different issue?

The notebook appears to be running `fastcore` version `1.3.29` and `fastai` version `2.7.9`

**Comment by snewcomer** [comment]
Same

**Comment by lanks** [comment]
Hmm getting this issue now as well with the Kaggle Notebook clone for lesson 1. @snewcomer @davidgilbertson did you guys manage to figure out what the issue is?

**Comment by davidgilbertson** [comment]
Sorry @lanks I don't think I resolved this. I recall trying installing different versions of fastai but don't remember what got it working exactly.
