### ISSUE TITLE
SameFileError on resizeImages

### ISSUE THREAD

**Issue by cvergnes** [fastai/fastai#3744]
**Describe the bug**

SameFileError on resize_images when in place (same src and dest folder) and image size < max_size

**Provide your installation details**

**To Reproduce**

```
from fastai.vision.utils import *
from pathlib import Path
download_images(dest='.', urls=['https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1200px-Image_created_with_a_mobile_phone.png'])
resize_images( path='.', dest='.', max_size=None)
```

=> generate always a shutil.SameFileError

**Expected behavior**

No error and no copy if file are exactly the same. I will create a PR by my self.

**Screenshots**

**Additional context**

Forum where the issue was discussed : https://forums.fast.ai/t/same-file-path-error-while-resizing-images-lesson-1/97601/12
resize_images is used in lesson 1. Some beginners (like me) could have the same issue.  nformation, but we have already asked you to do so, so please don't waste our time and yours and supply it in first place. If you don't, your issue will be closed. You are free to resubmit this time with the required information. Thank you for helping us help you. -->

**Describe the bug**

SameFileError on resize_images when in place (same src and dest folder) and image size < max_size

**Provide your installation details**

**To Reproduce**

```
from fastai.vision.utils import *
from pathlib import Path
download_images(dest='.', urls=['https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1200px-Image_created_with_a_mobile_phone.png'])
resize_images( path='.', dest='.', max_size=None)
```

=> generate always a shutil.SameFileError

**Expected behavior**

No error and no copy if file are exactly the same. I will create a PR by my self.

**Screenshots**

**Additional context**

Forum where the issue was discussed : https://forums.fast.ai/t/same-file-path-error-while-resizing-images-lesson-1/97601/12
resize_images is used in lesson 1. Some beginners (like me) could have the same issue.

**Comment by jph00** [comment]
fixed now.
