### ISSUE TITLE
Docs "Report an issue" sidebar link is dead / 404s

### ISSUE THREAD

**Issue by abevoelker** [fastai/fastai#3748]
Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): N/A

**Describe the bug**
The "Report an issue" link in the [docs page](https://docs.fast.ai/) sidebar is dead.

**To Reproduce**
1. Visit https://docs.fast.ai/
2. In the right sidebar, click the "Report an issue" hyperlink
3. The result is [a GitHub 404 error page](https://github.com/fastai/fastai/tree/master/issues/new)

**Expected behavior**
The link should go to a valid location, e.g. [https://github.com/fastai/fastai/issues/new/choose](https://github.com/fastai/fastai/issues/new/choose)

**Error with full stack trace**
N/A

**Additional context**
N/A

**Comment by jph00** [comment]
thanks fixed now.
