### ISSUE TITLE
Many broken links in the docs pages

### ISSUE THREAD

**Issue by abevoelker** [fastai/fastai#3749]
Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): N/A

**Describe the bug**
Many hyperlinks in the docs are broken

**To Reproduce**
1. Visit the [docs "Quick start"](https://docs.fast.ai/quick_start.html)
2. Click on [the first hyperlink to "DataLoaders"](https://docs.fast.ai/data.core#DataLoaders)
3. It's a 404 error page

**Expected behavior**
The DataLoaders docs displays correctly w/ a 200 OK page

**Error with full stack trace**
N/A

**Additional context**
N/A

**Comment by abevoelker** [comment]
For now I figured out I can visit https://fastai.github.io/fastai-docs/<path> to work around the missing links.

Perhaps https://github.com/fastai/fastai-docs/commit/ac5c34ca5c6cd3dd71aa9888b8514b59941fdee8 has something to do with this?

**Comment by jph00** [comment]
Fixed now.
