### ISSUE TITLE
Allow new users to write on fastai forum

### ISSUE THREAD

**Issue by nprime496** [fastai/fastai#3759]
There's no link to forum discussion because I can't write there, this is my feature request. Preventing new users from writing seems to be a good defensive move  but it is actually very irritating for new users.
I created an account because I needed help but I can't post anything. I think most of the people creating account are doing it either because they want to answer a question or ask one. Even [stackoverflow](stackoverflow.com) isn't so restrictive.

Can you please think again about this design ?

**Describe the solution you'd like**
Allow users to write after account creation.

**Comment by jph00** [comment]
You need to spend some time reading before you ask a question. That's what we wish to enforce.
