### ISSUE TITLE
cv2.imread error in open_image not handled correctly

### ISSUE THREAD

**Issue by Zohaggie** [fastai/fastai#376]
If there is an error in line 239 of dataset.py:
`im = cv2.imread(str(fn), flags).astype(np.float32)/255`
it cannot be handled by the next line  
`if im is None: raise OSError(f'File not recognized by opencv: {fn}')`

Therefore can we separate it like this (or as preferred for fast.ai)?
```
im = cv2.imread(str(fn), flags)
if im is None:     
    raise OSError(f'File not recognized by opencv: {fn}') 
else: 
    im = im.astype(np.float32)/255
```

**Comment by jph00** [comment]
That makes sense - can you open a PR with that? (see https://hub.github.com/ )
