### ISSUE TITLE
Broken Links - https://docs.fast.ai/#migrating-from-other-libraries

### ISSUE THREAD

**Issue by jturner116** [fastai/fastai#3765]
Maybe could mark these WIP until they're finished? I am anxious to see them, was pretty sad to see the 404 haha.

Thanks!

**Comment by jph00** [comment]
Looks like we're missing the .html suffix - this works: https://docs.fast.ai/#migrating-from-other-libraries.html

I'll fix the link now.

**Comment by jturner116** [comment]
I actually meant the links in that section, like the following:
https://docs.fast.ai/migrating_pytorch
https://docs.fast.ai/migrating_ignite
https://docs.fast.ai/migrating_lightning
https://docs.fast.ai/migrating_catalyst

**Comment by jph00** [comment]
> I actually meant the links in that section, like the following:

Understood - I'm fixing them too (they all need .html suffixes to work)
