### ISSUE TITLE
TabularLearner.predict prints a newline in notebooks

### ISSUE THREAD

**Issue by Mikko-Finell** [fastai/fastai#3773]
Everytime I call TabularLearner.predict it not just returns `row, clas, probs` as expected, but it also prints an empty newline too.

It's fine when you predict on one row. But when I'm calling `.predict` in a loop it keeps printing an ever increasing amount of newlines which, to put it mildly, makes my notebook harder to read. Looking into it, `.predict` calls `.get_preds` which is what actually prints the newline every time.

This: (fastai/tabular/learner.py)
```
inp,preds,_,dec_preds = self.get_preds(dl=dl, with_input=True, with_decoded=True)
```
I tried looking into `get_preds` to find where the newline is actually coming from but the code is too advanced for me to understand so I didn't get any further than this, so therefore I'm not able to submit my own pull request to fix this.

I would be very thankful if you can fix this and make `get_preds` stop printing newlines, thanks.

**Comment by Ben-Karr** [comment]
Hey,
what you are getting is actually not a newline but  the remainings of a progress bar. You can recreate this behaviour by calling `learn('before_validate')` (after training, before .predict) which shows you that progress bar. `learn('after_validate)` removes it, so calling both in succession leaves that empty space.
You can avoid this by removing the ProgressCallback from the list of callbacks but conveniently fastai offers a context manager that doesn't launch the progress bar. 
__So a solution would be to run your loop in the context of: `with learn.no_bar():`.__

Also this behaviour is not exclusive to the TabularLearner, at least the Learner from `vision_learner` does exactly the same...
Hope I could help.

**Comment by Mikko-Finell** [comment]
Thank you, this appears to have solved my problem completely.
