### ISSUE TITLE
_array2tensor() got an unexpected keyword argument 'requires_grad'

### ISSUE THREAD

**Issue by davidgilbertson** [fastai/fastai#3781]
Please confirm you have the latest versions of fastai, fastcore, and nbdev prior to reporting a bug (delete one): YES

```
fastai  : 2.7.9
fastcore: 1.5.14
```

**Describe the bug**
The code below throws an error when using `requires_grad=True`

**To Reproduce**
```py
import fastai
import torch

this_is_fine = fastai.torch_core.tensor([3.], requires_grad=True)
this_is_not = fastai.torch_core.tensor(3., requires_grad=True)
this_is_also_fine = torch.tensor(3., requires_grad=True)
```

**Expected behavior**
It should not throw an error.

**Error with full stack trace**

Place between these lines with triple backticks:

```
TypeError                                 Traceback (most recent call last)
File ~\.virtualenvs\fastbook--K4-LsvW\lib\site-packages\fastai\torch_core.py:152, in tensor(x, *rest, **kwargs)
    144     if len(rest): x = (x,)+rest
    145     # There was a Pytorch bug in dataloader using num_workers>0. Haven't confirmed if fixed
    146     # if isinstance(x, (tuple,list)) and len(x)==0: return tensor(0)
    147     res = (x if isinstance(x, Tensor)
    148            else torch.tensor(x, **kwargs) if isinstance(x, (tuple,list))
    149            else _array2tensor(x) if isinstance(x, ndarray)
    150            else as_tensor(x.values, **kwargs) if isinstance(x, (pd.Series, pd.DataFrame))
    151 #            else as_tensor(array(x, **kwargs)) if hasattr(x, '__array__') or is_iter(x)
--> 152            else _array2tensor(array(x), **kwargs))
    153     if res.dtype is torch.float64: return res.float()
    154     return res

TypeError: _array2tensor() got an unexpected keyword argument 'requires_grad'
```

**Additional context**
There are two problems:
* The source passes `**kwargs` to `_array2tensor`, but that function doesn't accept `**kwargs`
* But also, the logic within `tensor` doesn't handle the case of a single float being passed in. Perhaps better logic would be to test for all the special cases that fastai wants to handle, then fall back to passing all args to `torch.tensor`

**Comment by SaadAhmedGit** [comment]
Hi, I have linked a PR to this issue. I am still new to the repo but do you think this will resolve the issue that you are currently facing? I know you suggested a refactor of logic for testing arguments in torch_core.tensor() but I haven't touched that as I think there's more to it than I know.

**Comment by SaadAhmedGit** [comment]
@jph00 Even after your commit https://github.com/fastai/fastai/commit/aa58b1316ad8e7a5fa2e434e15e5fe6df4f4db56, don't you think not being able to pass `**kwargs` to `_array2tensor()` essentially means that you **can't** set the `requires_grad` attribute of the returned tensor?

For example, in the following snippet:
```
should_req_grad = fastai.torch_core.tensor(np.array([3., 4., 5.]), requires_grad=True)

print(should_req_grad.requires_grad)
#Output: False
#Expected: True
```
The expected output is different from the original output when we are passing a numpy array to create a tensor out of.
I think the solution to this would be to allow `_array2tensor()` to accept `**kwargs` and use it to set the `requires_grad` attribute. What are your thoughts?

**Comment by jph00** [comment]
I see where you're coming from @SaadAhmedGit, and that potentially could be a useful feature to add though. I'm not sure it's necessarily the expected behaviour... pytorch's `tensor()` takes `(dtype=None, device=None, requires_grad=False, pin_memory=False). If we're going to have `requires_grad` work for numpy arrays, it seems odd to have the rest not work IMO.

I think if we could have all kwargs work in all situations, and keep things reasonably simple and fast, I'd be happy to make that change.
