### ISSUE TITLE
Add import statement to fast.ai quickstart doc

### ISSUE THREAD

**Issue by lehmannerich** [fastai/fastai#3782]
The very first code example at [Computer vision classification](https://docs.fast.ai/quick_start.html) should have this statement
`from fastai.vision.all import *`

I think a lot of people trip up there and get a NameError.

**Comment by Ben-Karr** [comment]
This issue is a duplicate of #3771, I created a PR there.

**Comment by hamelsmu** [comment]
closing duplicate issue
