### ISSUE TITLE
"default_device" logic is repeated twice, related to `mps` / OSX support.

### ISSUE THREAD

**Issue by gregglind** [fastai/fastai#3785]
https://github.com/fastai/fastai/blob/c5b9aa050e1ed382b40a7f772a07d74453fdcacb/fastai/torch_core.py#L259

@jph00, previous fixes in #3719 repeated the logic.  

While there could we add a docstring for how to get a 'cpu only' build?  `use=0`, or use='cpu') would be great for that.

Re-assign it to me as a bug if you like, and I will be happy to submit a patch.

**Comment by jph00** [comment]
Assigned!
