### ISSUE TITLE
Text tutorial is missing

### ISSUE THREAD

**Issue by idrv** [fastai/fastai#3788]
Hello,

the link [text tutorial](http://docs.fast.ai/tutorial.text.html) located [here](https://docs.fast.ai/text.learner.html#loading-a-pretrained-model) leads to a 404.

**Comment by TomPham97** [comment]
The links you provided work perfectly fine for me. Could you check them again?

**Comment by idrv** [comment]
You're right, now it works flawlessly. It didn't though at the moment of submitting the issue.
Thank you!
