### ISSUE TITLE
ImageClassifierData.from_csv does not select the rows corresponding to val_idxs even if explicitly passed.

### ISSUE THREAD

**Issue by sidchat04** [fastai/fastai#386]
The method parse_csv_labels returns a sorted list of file names, hence the indices passed using val_idxs select the wrong rows when creating the validation data.

**Comment by jph00** [comment]
Could you provide a simple failing test case?

**Comment by sidchat04** [comment]
Hi @jph00, I can provide a test case in a sample notebook, or even try to put in a pull request for a test case in code (though I don't have a lot of experience there). What would be the preferred way?
I am actually also working on a simple fix for this issue, and will try to put in a pull request for that soon.

**Comment by jph00** [comment]
Ah well in that case, putting a test in the PR would be perfect. We have
a 'tests' directory now, so you could put it there, if not inconvenient.
Otherwise a notebook as a gist with a link in the PR would be fine.
--
Jeremy Howard


On Tue, Apr 24, 2018, at 8:05 AM, Sidharth Chaturvedi wrote:
> Hi @jph00[1], I can provide a test case in a sample notebook, or even
> try to put in a pull request for a test case in code (though I don't
> have a lot of experience there). What would be the preferred way?>  I am actually also working on a simple fix for this issue, and will
>  try to put in a pull request for that soon.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/jph00
  2. https://github.com/fastai/fastai/issues/386#issuecomment-383967183

**Comment by radekosmulski** [comment]
I think I ran into the same issue. By the time our filenames and targets arrive at `split_by_idx` they are sorted. They are split based on idxs that correspond to the original order in the csv and this produces incorrect results.

**Comment by radekosmulski** [comment]
This happens in dataset.py here:

```
   115  def parse_csv_labels(fn, skip_header=True, cat_separator = ' '):
   116      """Parse filenames and label sets from a CSV file.
   117
   118      This method expects that the csv file at path :fn: has two columns. If it
   119      has a header, :skip_header: should be set to True. The labels in the
   120      label set are expected to be space separated.
   121
   122      Arguments:
   123          fn: Path to a CSV file.
   124          skip_header: A boolean flag indicating whether to skip the header.
   125
   126      Returns:
   127          a four-tuple of (
   128              sorted image filenames,
   129              a dictionary of filenames and corresponding labels,
   130              a sorted set of unique labels,
   131              a dictionary of labels to their corresponding index, which will
   132              be one-hot encoded.
   133          )
   134      .
   135      :param cat_separator: the separator for the categories column
   136      """
   137      df = pd.read_csv(fn, index_col=0, header=0 if skip_header else None, dtype=str)
   138      fnames = df.index.values
   139      df.iloc[:,0] = df.iloc[:,0].str.split(cat_separator)
   140      return sorted(fnames), list(df.to_dict().values())[0]
```

I removed the sorting on fnames and this seems to work. I am not sure though if we don't rely on the dataset being sorted by filenames in some other parts of the code.
