### ISSUE TITLE
Some fastai Loss Functions Cannot be Exported due to Pickling Error

### ISSUE THREAD

**Issue by warner-benjamin** [fastai/fastai#3901]
Some fastai loss functions, such as `LabelSmoothingCrossEntropyFlat` are not picklable, and thus not exportable via `Learner.export`. But most, including `LabelSmoothingCrossEntropy` and other flattened losses, appear pickle without issue.

This minimal reproduction on Python 3.10 with the `Learner.export` default `protocol=2`
```python
try:
    pickle.dumps(LabelSmoothingCrossEntropyFlat(), protocol=2)
    print("The class is picklable")
except pickle.PicklingError as e:
    print(e)
```
results in `TypeError: cannot pickle 'code' object` for `LabelSmoothingCrossEntropyFlat` but no errors for `LabelSmoothingCrossEntropy` or `CrossEntropyLossFlat`.

We should probably add a test for pickling `LabelSmoothingCrossEntropyFlat` to catch future changes to pickle.

**Comment by nglillywhite** [comment]
Hey @warner-benjamin, let me know if this still needs picking up, I'll put in a PR if so.

**Comment by warner-benjamin** [comment]
@nglillywhite I am unaware of this being worked on

**Comment by nglillywhite** [comment]
Great, I'll have a look and put in a PR, thanks

**Comment by nglillywhite** [comment]
[PR 3910](https://github.com/fastai/fastai/pull/3910) adds these guards for current loss functions, I'd like to investigate why these loss functions can't be pickled with this issue but happy to open a new issue & PRs if you'd like to keep them separate.

**Comment by dharik-arsath** [comment]
Hi, I am facing a same issue on Focal Loss, unable to pickle focal loss. am I missing out something, is there any solution to this problem.

**Comment by jordiju** [comment]
Bump. Same issue here.

**Comment by kevin-vitro** [comment]
It seems like the issue here is somewhere in `Module`. That is why some of the loss functions work and others don't.

I dug into this a bit and got to the following test: 
```
class FocalLossTest(Module):
    def __init__(self):
        pass

    def forward(self, inp:Tensor, targ:Tensor) -> Tensor:
        return 0

#Works
pickle.dumps(FocalLossTest())

#Works
BaseLoss(FocalLossTest)

# Fails
pickle.dumps(BaseLoss(FocalLossTest))

# Fails
pickle.dumps(FocalLossTest().__annotations__)

# Fails
pickle.dumps(FocalLossTest().__annotations__['_modules'])
```

here is the stacktrace I see (which matches what benjamin mentioned as well: 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [286], in <cell line: 2>()
      1 # Fails
----> 2 pickle.dumps(FocalLossTest().__annotations__['_modules'])

TypeError: cannot pickle 'code' object
```

**Comment by kevin-vitro** [comment]
This appears to be an issue on torch versions >1.13.  I tested on torch 1.12.1 and pickling worked fine, but 1.13.1 give the TypeError

**Comment by kevin-vitro** [comment]
Here is a minimal reproduceable example of the issue: 
```
import torch.nn as nn
import pickle
import functools

pickles_fine = nn.Module()
pickle.dumps(pickles_fine);

pickle_fails = functools.update_wrapper(pickles_fine, nn.Module)
pickle.dumps(pickle_fails)
```

From what I can tell, the problem is with how nn.Module handles its typing.  Here is what the typing looks like that I think is causing the issue (not really sure why still): https://github.com/pytorch/pytorch/blob/2db33054b30534165f342fc0958b48cfff6fd19b/torch/nn/modules/module.py#L438
```
_modules: Dict[str, Optional['Module']]
```

This gets converted into the following in nn.Module's `__annotations__` 
```
 '_modules': typing.Dict[str, typing.Optional[ForwardRef('Module')]],
```

which cannot be pickled, but this doesn't show up in the `__dict__` of `pickles_fine` until `functools.update_wrapper` runs and copies __annotations__.  Once this happens, pickles_fine can no longer be pickled.
