### ISSUE TITLE
AttributeError: ‘list’ object has no attribute ‘data’ in pascal notebook

### ISSUE THREAD

**Issue by bharadwaj6** [fastai/fastai#392]
happens in single object detection section.

More details here: http://forums.fast.ai/t/attributeerror-list-object-has-no-attribute-data/15301

**Comment by gsgbills** [comment]
I had that error, and fixed it by replacing in model.py:212
res.append([f(preds.data,y.data) for f in metrics]) 
by 
res.append([f(preds.data,y) for f in metrics]) 

It may be related to the change to Pytorch 0.4....

**Comment by hiromis** [comment]
I can confirm it's not related to Pytorch 0.4 - I tested with both 0.3 and 0.4 and got the same error.
