### ISSUE TITLE
FutureWarning: is_categorical_dtype is deprecated (pandas 2.1.1)

### ISSUE THREAD

**Issue by feldgendler** [fastai/fastai#3967]
Please confirm you have the latest versions of fastai, <s>fastcore, and nbdev</s> prior to reporting a bug: YES

fastai 2.7.12

fastcore and nbdev are irrelevant, the problem is clearly in fastai.

**Describe the bug**
```
FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
```

**To Reproduce**
Execute the very first example in [Chapter 1 from fastbook](https://github.com/fastai/fastbook/blob/master/01_intro.ipynb) under “Running Your First Notebook”.

**Expected behavior**
No deprecation warnings.

**Error with full stack trace**

Full stack traces aren't shown for deprecation warnings.

```
/home/alexey/ai/mambaforge/lib/python3.10/site-packages/fastai/data/transforms.py:225: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(col):
```

**Additional context**
I get a slightly varied set of deprecation warnings about `is_categorical_dtype` (from different code locations) when I run various examples from fastbook. The warnings contain advice on how to replace the deprecated calls.

**Comment by warner-benjamin** [comment]
This is resolved in #3928. Will be fixed with the next fastai release.
