### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Debugger28** [fastai/fastai#397]
I am trying to run this:

import fastai

from fastai.imports import *
from fastai.structured import *

Error:

  File "/Users/parihar/anaconda2/lib/python2.7/site-packages/fastai-0.6-py2.7.egg/fastai/structured.py", line 33
    f'Tree {{ size={size}; ratio={ratio}', s)))
                                        ^
SyntaxError: invalid syntax

**Comment by yanneta** [comment]
you need python 3.6

**Comment by devforfu** [comment]
@Debugger28 Right, string interpolation was introduced in Python v3.6 only.
