### ISSUE TITLE
requirements.txt is incomplete for fastai part 2

### ISSUE THREAD

**Issue by bhaskarb** [fastai/fastai#402]
I had to add the following for it to install successfully in virtualenv.  I was trying to install it i my machine and user a virtualenv and pip install -r requirements.txt for the same. These packages were missing and I manually added them to my requirements.txt for it to compile fine:
graphviz>=0.8.2
scikit-learn>=0.19.1
sklearn-pandas>=1.6.0
torch>=0.4.0
torchvision>=0.2.1
chardet>=3.0.4 
idna>=2.6 
requests>=2.18.4 
torchtext>=0.2.3 
urllib3>=1.22

Do let me know if I was missing something.

**Comment by jph00** [comment]
I think this is fixed now - feel free to open new issue or (better still) PR if anything else missing.
