### ISSUE TITLE
Lesson 4 issue

### ISSUE THREAD

**Issue by jackalhan** [fastai/fastai#417]
While executing the following line in Lesson 4, 

```
m3 = md2.get_model(opt_fn, 1500, bptt, emb_sz=em_sz, n_hid=nh, n_layers=nl, 
           dropout=0.1, dropouti=0.4, wdrop=0.5, dropoute=0.05, dropouth=0.3)
m3.reg_fn = partial(seq2seq_reg, alpha=2, beta=1)
m3.load_encoder(f'adam3_20_enc')
```

I am having the following error: 
`'RNN_Learner' object has no attribute 'data_path'`

Could you please provide your opinions how to fix the issue?

Thank you

**Comment by javedqadruddin** [comment]
This thread might be helpful http://forums.fast.ai/t/notimplementederror-during-the-fitting-of-language-model-in-rnn-reg-py/15699
