### ISSUE TITLE
Need Unit Tests

### ISSUE THREAD

**Issue by jackalhan** [fastai/fastai#418]
This repo and library need some Unit tests because in each time something is getting fixed, another problem occurs so repo should be maintained under the correct procedure. Otherwise, it will not be useful.
Thank you.

**Comment by PiotrCzapla** [comment]
That is already being addressed. If you want to help let us know. @mcskinner  is adding some test as he goes through the library  (he is quite productive btw) and I'm working on tests for `transform.py`.

**Comment by jackalhan** [comment]
Sure, I would be happy to contribute to it.
