### ISSUE TITLE
Dependency on old version of colorama lib

### ISSUE THREAD

**Issue by mirekphd** [fastai/fastai#419]
fastai python library in its version 0.6 has an indirect dependency (through awscli) on the old version of colorama: <= 0.3.7, current version: 0.3.9). This implies that you cannot install fastai together with h2o, which depends on a disjoint version of colorama (>=0.3.8).

How to reproduce:

```
pip install colorama==0.3.7
pip install fastai
pip install h2o
pip install pipdeptree
pipdeptree --reverse --packages colorama
```

Reverse dependencies of colorama, after installing colorama in the 0.3.7 version required by fastai:
```
Warning!!! Possibly conflicting dependencies found:
* h2o==3.18.0.8
 - colorama [required: >=0.3.8, installed: 0.3.7]
------------------------------------------------------------------------
colorama==0.3.7
  - awscli==1.15.10 [requires: colorama<=0.3.7,>=0.2.5]
    - fastai==0.6 [requires: awscli]
  - h2o==3.18.0.8 [requires: colorama>=0.3.8]
```

Environment:
Ubuntu 16.04
Python 3.6.5
conda 4.5.1
pip 10.0.1

**Comment by jph00** [comment]
awscli isn't really a dependency. I'll remove it from the env.
