### ISSUE TITLE
rotate_cv(im, 180)  adds some padding

### ISSUE THREAD

**Issue by PiotrCzapla** [fastai/fastai#431]
The test below passes and the `e` is clearly not something one would expect after rotation of 90 degs.
```
    im = np.array([
        [0.,   0.1,  0., ],
        [0.,   0.2,  0., ],
        [0.,   0.3,  0., ],])
    
    a = rotate_cv(im, 90)
    e = np.array([[0. , 0. , 0. ],
                           [0. , 0. , 0. ],
                           [0.1, 0.2, 0.3]])
    np.testing.assert_array_equal(a, e)
```

**Comment by IgorKasianenko** [comment]
I didn't test your case, but why do you have comas before square bracket closes in `im = np.array `?
Looks like you have 4 extra comas compared to `e`

**Comment by sgugger** [comment]
Been fixed by previous PR.
