### ISSUE TITLE
Provide a module to download datasets like scikit-learn

### ISSUE THREAD

**Issue by bhoomit** [fastai/fastai#434]
Was trying to use Google Colab for DL1. Downloading dataset for different lessons and setting it up is not seamless. Is it possible to provide an abstraction? Something like [this](http://scikit-learn.org/stable/tutorial/basic/tutorial.html#loading-an-example-dataset)

```
$ python
>>> from sklearn import datasets
>>> iris = datasets.load_iris()
>>> digits = datasets.load_digits()
```
Will be happy to contribute.

**Comment by jph00** [comment]
I'd be happy to accept a PR :)
