### ISSUE TITLE
Can we please consolidate the project? 

### ISSUE THREAD

**Issue by jackalhan** [fastai/fastai#438]
Hello @jph00  and other friends,
I have been trying to experiment IMDB notebooks in DL1 and DL2 in order to quickly utilize the transfer learning for LM, I could not be successful although I have been trying for several days. 

Our project name is fastai but unfortunately, since we have some inconsistencies with the torch on the backhand side, we can not get fast solutions from the existing implemented code. I can not utilize the library as it is advertised. 

Can we please first consolidate the project to somehow make all the existing code runnable without wasting tons of time and then implement new add-ons? Otherwise, it is working only for time "t" (time that @jph00 is giving the lecture) and not after then.

On the other hand, can we also use this platform instead of fastai forum since some people are entering issues on there, some people on here, there can be duplicated issues, it is getting difficult to follow and synchronize both places? 

BTW: I still can not run the IMDB codes. Issue ID : #439 

Thank you for your patience in advance.

**Comment by jph00** [comment]
We only officially support GPU. For help with CPU, please use the forums.
