### ISSUE TITLE
Pytorch support of old gpu

### ISSUE THREAD

**Issue by nikky4D** [fastai/fastai#440]
Hi,

I install fastai on a K2000M Quadro with compute 3.0. Pytorch says it no longer supports this gpu because it is too old. It appears this is only from Pytorch 3.1. Will Fastai still work with Pytorch 3.0 or is there something I can do to make Fastai and Pytorch work with my gpu

THanks

Here is my error:

Found GPU0 Quadro K2000M which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-14-e6c87b20ce86> in <module>()
      1 arch=resnet34
      2 data = ImageClassifierData.from_paths(PATH, tfms=tfms_from_model(arch, sz))
----> 3 learn = ConvLearner.pretrained(arch, data, precompute=True)
      4 learn.fit(0.01, 2)

~/pytorchLearn/fastai/courses/dl1/fastai/conv_learner.py in pretrained(cls, f, data, ps, xtra_fc, xtra_cut, custom_head, precompute, pretrained, **kwargs)
    111                    pretrained=True, **kwargs):
    112         models = ConvnetBuilder(f, data.c, data.is_multi, data.is_reg,
--> 113             ps=ps, xtra_fc=xtra_fc, xtra_cut=xtra_cut, custom_head=custom_head, pretrained=pretrained)
    114         return cls(data, models, precompute, **kwargs)
    115 

~/pytorchLearn/fastai/courses/dl1/fastai/conv_learner.py in __init__(self, f, c, is_multi, is_reg, ps, xtra_fc, xtra_cut, custom_head, pretrained)
     50         self.n_fc = len(fc_layers)
     51         self.fc_model = to_gpu(nn.Sequential(*fc_layers))
---> 52         if not custom_head: apply_init(self.fc_model, kaiming_normal)
     53         self.model = to_gpu(nn.Sequential(*(layers+fc_layers)))
     54 

~/pytorchLearn/fastai/courses/dl1/fastai/initializers.py in apply_init(m, init_fn)
      8 
      9 def apply_init(m, init_fn):
---> 10     m.apply(lambda x: cond_init(x, init_fn))
     11 
     12 

~/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/nn/modules/module.py in apply(self, fn)
    196         """
    197         for module in self.children():
--> 198             module.apply(fn)
    199         fn(self)
    200         return self

~/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/nn/modules/module.py in apply(self, fn)
    197         for module in self.children():
    198             module.apply(fn)
--> 199         fn(self)
    200         return self
    201 

~/pytorchLearn/fastai/courses/dl1/fastai/initializers.py in <lambda>(x)
      8 
      9 def apply_init(m, init_fn):
---> 10     m.apply(lambda x: cond_init(x, init_fn))
     11 
     12 

~/pytorchLearn/fastai/courses/dl1/fastai/initializers.py in cond_init(m, init_fn)
      5     if not isinstance(m, (nn.BatchNorm1d,nn.BatchNorm2d,nn.BatchNorm3d)):
      6         if hasattr(m, 'weight'): init_fn(m.weight)
----> 7         if hasattr(m, 'bias'): m.bias.data.fill_(0.)
      8 
      9 def apply_init(m, init_fn):

RuntimeError: cuda runtime error (8) : invalid device function at /opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/generic/THCTensorMath.cu:15

**Comment by jackalhan** [comment]
You can. Please look at the following discussion: http://forums.fast.ai/t/pytorch-not-working-with-an-old-nvidia-card/14632

**Comment by nikky4D** [comment]
Thank you. As the forum said, installing from source works.
