### ISSUE TITLE
pyTorch 0.4 warning calling VV() on Windows

### ISSUE THREAD

**Issue by IgorKasianenko** [fastai/fastai#443]
Hi, I had compatability error for old gpu, so I updated to pyTorch 0.4. Now there is an warning running Lesson 13 style-transfer notebook, calling VV variable:

```
\fastai\courses\dl2\fastai\core.py:23: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  x = Variable(T(x), volatile=volatile, requires_grad=requires_grad)
```

I wonder if it will be back compatible with pytorch 3 if i change usage of the function in fastai\core.py?

**Comment by jph00** [comment]
If you `git pull` I think you'll find this resolved.

**Comment by jph00** [comment]
(Actually I think you'll still get the warning - but it is using the new behavior too, so can be ignored.)
