### ISSUE TITLE
lesson4-mnist_sgd fit epochs=5 returns error message

### ISSUE THREAD

**Issue by miwojc** [fastai/fastai#461]
![image](https://user-images.githubusercontent.com/32404415/39890849-11da8a90-546a-11e8-8f3b-086da59323ba.png)

should be 'n_epochs=5'

**Comment by jph00** [comment]
Thanks! Would you like to submit a PR?

**Comment by miwojc** [comment]
sure, will do that!

**Comment by miwojc** [comment]
i have locally created branch, corrected file, commit-ed,  but i am unable to access fastai.git when git push --set-upsteream origin 
![image](https://user-images.githubusercontent.com/32404415/40007042-d03e992a-5769-11e8-9acf-95b907541e6d.png)

**Comment by Eric-Arellano** [comment]
@miwojc This is normal for open source projects - only a couple of people have push access to the repository to prevent someone accidentally pushing code that breaks the app.

Instead, you'll have to fork the repository and submit a pull request. Here's a guide on how to do this all! https://gist.github.com/Chaser324/ce0505fbed06b947d962

Thanks for taking the time to do this all!
