### ISSUE TITLE
Adding type hints

### ISSUE THREAD

**Issue by Eric-Arellano** [fastai/fastai#477]
Hi @jph00, would you consider merging a PR to add Python 3.6 type hints to the project if I submitted one? 

It not only helps to catch compile time bugs, but improves documentation both internally and externally when exporting as pip package, without potentially rotting like comments.

I see we already have good docstring for most functions, so this would be moving the type definitions  piece to the function parameters instead of docstring, which allows for static tool analysis + adding either Pyre or MyPy to actually check for type errors.

See [PEP 484](https://docs.python.org/3/library/typing.html) for implementation details and this blog for some [examples](http://www.daveoncode.com/2017/03/06/writing-better-software-with-python-3-6-type-hints/).

**Comment by jph00** [comment]
Yes absolutely!

**Comment by Eric-Arellano** [comment]
@jph00 I'm still working on adding typing, but am slowed down much more than I expected because I'm not familiar with the code base. I'll push soon the framework/tool for getting it to work, so that others can contribute as well. 

Do you know of any contributors familiar with the codebase who would be interested in helping?

**Comment by ifiokjr** [comment]
@jph00 is this something I can help with?
