### ISSUE TITLE
Cleaning up root level files

### ISSUE THREAD

**Issue by Eric-Arellano** [fastai/fastai#478]
Hello, are `environment-old.yml` and `environment-nopytorch.tml` still being maintained / actively used by people? I understand `environment-cpu.yml` is to allow running without a GPU, but am not sure why those two environments exist.

If they are primarily there for reference, I'll submit a PR to remove them because we can always look back at them through Git. Reduces complexity of project to not have to support as many environments.

**Comment by jph00** [comment]
Yup we don't need them.
