### ISSUE TITLE
Error caused by .DS_Store

### ISSUE THREAD

**Issue by amirhakim** [fastai/fastai#488]
Using fastai-cpu on OSX causes this error
OSError: Error handling image at: /data/carsuv/train/suv/.DS_Store

**Comment by Adam314** [comment]
I have the same issue. Mac OS is creating those .DS_Store files in every folder. You need to:

1. close all finder windows that have fast folders open
2. delete files from command line. In your fastai folder run: `find . -name ".DS_Store" -delete`

I suppose it'd be nice if fastai ignored all hidden files while listing test, train and validation dirs

**Comment by Adam314** [comment]
Update: to fix it we need to change file https://github.com/fastai/fastai/blob/master/fastai/dataset.py#L72 and add a line `iff name not in ('.DS_Store')`
