### ISSUE TITLE
custom_head and precompute=True: Issue saving precomputed weights

### ISSUE THREAD

**Issue by th3ragex** [fastai/fastai#491]
I had some trouble using ConvLearner.pretrained() with 'precompute=True' and a 'custom_head'. After the first predicted batch finished computing bcolz complained with: 
```python 
'fastai\model.py in predict_to_bcolz(m, gen, arr, workers)' @ arr.append(y)
     ValueError: array trailing dimensions do not match with self.
```

I think I found the following lines to be the root cause:
```python
class ConvnetBuilder():
    def __init__(...):
[...]
        self.nf = model_features[f] if f in model_features else (num_features(layers)*2)
        if not custom_head: layers += [AdaptiveConcatPool2d(), Flatten()]
[...]
```
Without the flatten layer precompute doesn't seem to work. Additionally it looks like the previous line expects the AdaptiveConcatPool2d to be part of the top_model, since it doubles the number of expectd features from the last 'top_model' layer.

I couldn't find an easy workaround without creating a derived class which doesn't call the base class initializer.

**Comment by jph00** [comment]
Yes we don't currently support that combination.
