### ISSUE TITLE
Brief project description on PyPI

### ISSUE THREAD

**Issue by bkowshik** [fastai/fastai#499]
Shall we have a brief description of the `fastai` library on PyPI? Currently it is empty.

- https://pypi.org/project/fastai/

<img width="1260" alt="screen shot 2018-05-24 at 23 01 01" src="https://user-images.githubusercontent.com/2899501/40501733-5a7d6e24-5fa6-11e8-8a30-5f3133041a6f.png">

**Comment by jph00** [comment]
Looks like that needs to be added to the setup.py file - PRs welcome! :)
