### ISSUE TITLE
environment-cpu.yml should contain pytorch-cpu<0.4, not pytorch<0.4

### ISSUE THREAD

**Issue by ishida330** [fastai/fastai#503]
Hi, Thank you for the great course! 
I'd like to run fast.ai framework( new one based on pyTorch) on Windows( without GPU=CPU mode ) and found one thing. 
I think **environment-cpu.yml** line 89 should contain - pytorch-cpu<0.4 , not - pytorch<0.4.
When I test it (=conda env update -f environment-cpu.yml and run lesson1.ipynb) on Windows 10 with current settings, it failed as:
![image](https://user-images.githubusercontent.com/9675895/40571751-8117e986-60d9-11e8-9418-608bcf5a64f3.png)
> ImportError: DLL load failed:  module specified not found.

When I changed the line 89 to pytorch-cpu<0.4, it worked fine.
Thank you !

**Comment by jph00** [comment]
I believe that only works for windows.
