### ISSUE TITLE
fastai/dataset.py ImageClassifierData gives error 'tuple index out of range' with test folder

### ISSUE THREAD

**Issue by miwojc** [fastai/fastai#512]
See the forum thread for description:
http://forums.fast.ai/t/imageclassifierdata-from-csv-gives-indexerror-tuple-index-out-of-range/17192

seems that by reverting changes to dataset.py file line 374 fixes the issue:
test_lbls = np.zeros((len(test),1)) --> works
test_lbls = np.zeros((len(test),trn[1].shape[1])) --> doesn't work

**Comment by tbass134** [comment]
There's some more info about this on the forum
http://forums.fast.ai/t/imageclassifierdata-from-csv-gives-indexerror-tuple-index-out-of-range/17192/5

**Comment by jph00** [comment]
I think the recent PR fixes this - feel free to reopen if that's not the case.

**Comment by tbass134** [comment]
thanks @jph00 that fixed the issue.
