### ISSUE TITLE
Fastai on Python 3.5

### ISSUE THREAD

**Issue by chintler** [fastai/fastai#514]
I'm setting up fastai locally on Ubuntu 16.04 that already includes Python 3.5 by default, and there are a few features that seem to only be compatible with 3.6, such as a lot of f strings. Is a setup of Python 3.6 environment a must, and are there any tips for setting up the same? 

I'm specifically concerned about jupyter-notebook and ipython shell since I'd like to avoid reinstallation of these two, as well as a virtualenv.

**Comment by kechan** [comment]
I had the same question posted on fastai forum. I tried 2 ways:

1) use docker ufoym/deepo:all-py36-jupyter (or cpu variant if you don't have gpu)
2) run notebook on google colab with python3 (with comes with 3.6)

I think (1) should be good, although, my kernel died when running some specific cell in dl1 lesson 3. I don't know and havent debug why the kernel died. Running the same on google colab was fine. 

One person on that forum just told me to edit those f strings to use the old way. But it is sort of not maintainable and given that fastai seemed to be officially on py3.6, I don't want any nasty and worse, silent surprise later on. 

Let me know how this goes for you.

**Comment by jph00** [comment]
3.6 is required

**Comment by chintler** [comment]
In case anyone wants a quicker, simpler solution for running a Python 3.6 environment, I installed an additional jupyter environment via 

``python3.6 -m pip install fastai``
and I ran jupyter notebook directly, with
``python3.6 -m jupyter notebook``

Minimum hassles.
