### ISSUE TITLE
Redundant import statements in layers.py

### ISSUE THREAD

**Issue by mattmcclean** [fastai/fastai#518]
Have been trying to deploy a fast.ai trained resnext conv model to AWS Lambda as the inference engine. Want to keep the packages/libraries used to a minimum to satisfy the AWS Lambda constraint of a max 250MB uncompressed deployment package. I found an issue loading the exported model (using dill as the serialization library) as it attempts to find many unnecessary packages when loading the fast.ai custom ``AdaptiveConcatPool2d`` layer. The layer is defined in the ``layers.py`` file which imports the ``torch_imports.py`` file with many import statements of packages not needed for model inference.  I have managed to get it to work but had to make a slight change to the code base by replacing the import statements with only the necessary torch only imports.

The changes I made were replacing:
```
from .imports import *
from .torch_imports import *
```
with:
```
import torch
from torch import nn
```
 in the ``fastai/layers.py`` file.

The only issue this caused was a Name not found error with the  LooseVersion class when loading the ``torch_imports.py`` file. Is fixed by adding the following import statement to the ``torch_imports.py`` file.

```
from distutils.version import LooseVersion
```
Should I submit a pull request with these changes or do you see any further issues?

**Comment by jph00** [comment]
That sounds fine to me :)
