### ISSUE TITLE
validate_next issue with pytorch 0.4

### ISSUE THREAD

**Issue by hnisonoff** [fastai/fastai#523]
I discovered an issue while trying to use `lr_find2` with pytorch 0.4.
`lr_find2` calls `validate_next`, in which we have the following:
```
1. def validate_next(stepper, metrics, val_iter):
2.     """Computes the loss on the next minibatch of the validation set."""
3.     stepper.reset(False)
4.     import pdb; pdb.set_trace()
5.     with no_grad_context():
6.         (*x,y) = val_iter.next()
7.         preds,l = stepper.evaluate(VV(x), VV(y))
8.         res = [to_np(l)[0]]
9.         res += [f(preds.data,y) for f in metrics]
10.     stepper.reset(True)
11.     return res
```

I get an IndexError at line 8. The issue is that in pytorch 0.4 `l` is a tensor:
```
(Pdb) !l
tensor(8.2462, device='cuda:0')
```
and when `to_np(l)` is called the following is returned:
`(Pdb) to_np(l)
array(8.24617, dtype=float32)`

This array is scalar and cannot be indexed. In older versions of pytorch I saw the following behavior.

```
(Pdb) !l
Variable containing:
 8.2459
[torch.cuda.FloatTensor of size 1 (GPU 0)]

(Pdb) [to_np(l)[0]]
[8.245869]
```

I am not yet familiar enough with the library and recent changes to pytorch to recommend a solution, but I would appreciate any input into this problem.

**Comment by jph00** [comment]
@sgugger you want to look at this one?

**Comment by sgugger** [comment]
Oh yeah, it's the same problem with had in save_metrics at the point with the loss being sometimes a scalar and sometimes an array with only one element.
I'll get on it right away.

**Comment by sgugger** [comment]
Should be solved in the latest PR, let me know if it's not the case @hnisonoff .

**Comment by hnisonoff** [comment]
Works great. Thank you!
