### ISSUE TITLE
Issue with FP16 with Sequential Models

### ISSUE THREAD

**Issue by hnisonoff** [fastai/fastai#526]
The current implementation of `Learner.half()` modifies `Learner.models.model` to a new object, of type `FP16`. Currently this does not work with sequential models. For example, I tried to use `Learner.half()` on the `RNN_Learner` class for training a language model and ran into an issue when `get_layer_groups` was called:
```
1. class LanguageModel(BasicModel):
2.     def get_layer_groups(self):
3.         m = self.model[0]
4.         return [*zip(m.rnns, m.dropouths), (self.model[1], m.dropouti)]

```
The error I get is that objects of type `FP16`  (in this case it the object in question is `self.model` in line 3) cannot be indexed. Thus, by forcing the model to be of type `FP16` we lose any additional properties of the original `model` object that are not directly inherited by `nn.Module` (such as `_get_item_by_idx`). Is there a different approach to introducing fp16 into arbitrary models that could solve this issue?

**Comment by jph00** [comment]
Thanks for letting us know. We'll post here if we come up with a solution (and let us know if you think of one!)

**Comment by bny6613** [comment]
I could be wrong, but seems like you can solve this particular issue by declaring __getitem__ method on F16 class, so it delegates the call to the module:  
```
def __getitem__(self, idx):
        return self.module[idx]
```

**Comment by jph00** [comment]
Seems reasonable - want to give it a go, and submit a PR if it works?
