### ISSUE TITLE
 NameError: name '_int_classes' is not defined when running Carvana notebook

### ISSUE THREAD

**Issue by 43061b4a** [fastai/fastai#530]
## Error Details

> ~/fastai/dataloader.py in __init__(self, dataset, batch_size, shuffle, sampler, batch_sampler, pad_idx, num_workers, pin_memory, drop_last, pre_pad, half, transpose, transpose_y)
>      41             if sampler is None:
>      42                 sampler = RandomSampler(dataset) if shuffle else SequentialSampler(dataset)
> ---> 43             batch_sampler = BatchSampler(sampler, batch_size, drop_last)
>      44 
>      45         if num_workers is None:
> 
> ~/miniconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/data/sampler.py in __init__(self, sampler, batch_size, drop_last)
>     110                              "torch.utils.data.Sampler, but got sampler={}"
>     111                              .format(sampler))
> --> 112         if not isinstance(batch_size, _int_classes) or isinstance(batch_size, bool) or \
>     113                 batch_size <= 0:
>     114             raise ValueError("batch_size should be a positive integeral value, "
> 
> NameError: name '_int_classes' is not defined

## Code:
`
tfms = tfms_from_model(resnet34, sz, crop_type=CropType.NO, tfm_y=TfmType.CLASS, aug_tfms=aug_tfms)
datasets = ImageData.get_ds(MatchedFilesDataset, (trn_x,trn_y), (val_x,val_y), tfms, path=PATH)
md = ImageData(PATH, datasets, bs, num_workers=8, classes = 0)
`

Tried reinstalling torch, still the same issue.

**Comment by jph00** [comment]
Please use the forums

**Comment by 43061b4a** [comment]
Ok, I'll use the forums in future. 
The problem was the version of Pytorch. Updated environment.yml file to - pytorch=0.4.0. - pytorch<=0.4.0 installed version 0.1.12.
