### ISSUE TITLE
Please comment out all crestle lines

### ISSUE THREAD

**Issue by austinmw** [fastai/fastai#537]
I tried running an entire notebook on paperspace (fastai/courses/dl1/lesson2-image_models.ipynb), but crestle lines were not commented out and it created symbolic links. Now I'm getting an error `FileNotFoundError: [Errno 2] No such file or directory: 'data/planet/train-jpg/train_0.jpg'` I couldn't figure out where `train_0.jpg` actually resided or if it was overwritten, so I deleted and restarted my entire paperspace machine (having to wait several hours for new machine approval).

**Comment by jph00** [comment]
I'd rather not do this.

**Comment by itsmuriuki** [comment]
What would you recommend?
