### ISSUE TITLE
RNN_Encoder doesn't have bias term in its constructor while language model has bias term

### ISSUE THREAD

**Issue by rahul-iyer** [fastai/fastai#539]
There is an error when we call get_language_model().
`
TypeError                                 Traceback (most recent call last)
<ipython-input-57-9fa2488808f7> in <module>()
      1 learner= md.get_model(opt_fn, em_sz, nh, nl, 
----> 2     dropouti=drops[0], dropout=drops[1], wdrop=drops[2], dropoute=drops[3])
      3 
      4 learner.metrics = [accuracy]
      5 learner.freeze_to(-1)

/project/6006845/r3iyer/fastai/courses/dl2/fastai/text.py in get_model(self, opt_fn, emb_sz, n_hid, n_layers, **kwargs)
    199 
    200     def get_model(self, opt_fn, emb_sz, n_hid, n_layers, **kwargs):
--> 201         m = get_language_model(self.n_tok, emb_sz, n_hid, n_layers, self.pad_idx, **kwargs)
    202         model = LanguageModel(to_gpu(m))
    203         return RNN_Learner(self, model, opt_fn=opt_fn)

/project/6006845/r3iyer/fastai/courses/dl2/fastai/lm_rnn.py in get_language_model(n_tok, emb_sz, nhid, nlayers, pad_token, dropout, dropouth, dropouti, dropoute, wdrop, tie_weights, qrnn, bias)
    234 
    235     rnn_enc = RNN_Encoder(n_tok, emb_sz, nhid=nhid, nlayers=nlayers, pad_token=pad_token,
--> 236                  dropouth=dropouth, dropouti=dropouti, dropoute=dropoute, wdrop=wdrop, qrnn=qrnn, bias=bias)
    237     enc = rnn_enc.encoder if tie_weights else None
    238     return SequentialRNN(rnn_enc, LinearDecoder(n_tok, emb_sz, dropout, tie_encoder=enc))

TypeError: __init__() got an unexpected keyword argument 'bias'

`

**Comment by seb799** [comment]
# #540
