### ISSUE TITLE
`bptt + 5 * 5` in `LanguageModelLoader`

### ISSUE THREAD

**Issue by bkj** [fastai/fastai#543]
What's the explanation for this line:

https://github.com/fastai/fastai/blob/61da3f46dd000aad83bb71793c4638d8f448f5d0/fastai/text.py#L165

multiplying the `bptt` parameter by 25?  Is that a typo, or is there a reason we want to do this?

~ Ben

**Comment by jph00** [comment]
I think it's right. To avoid pytorch mem problems, we want the first sequence to be the largest. Since we draw from N(bptt,5) below, then bptt+5*5 is 5 stdev from the mean, which should be safe. Feel free to reopen if this seems wrong to you.

**Comment by bkj** [comment]
Ah got it -- makes sense to me.  Thanks.
