### ISSUE TITLE
Lesson 6 Multi-Step Losses higher than in video

### ISSUE THREAD

**Issue by rexmadden** [fastai/fastai#544]
See [lesson 6 thread](http://forums.fast.ai/t/wiki-lesson-6/9404/31?u=rexmadden)

Basically, a change was made in commit https://github.com/fastai/fastai/commit/052bf674c244784ce68e46981af63e9e9fead210 to the notebook, and the losses shot up to about 2.0 instead of 1.5 and 1.6 that @jph00 was getting in the video. You can see those losses in the notebook outputs now.

**Comment by jph00** [comment]
Let's discuss in the forum thread
