### ISSUE TITLE
Specify device (or GPU for torch < 0.4) in LanguageModelData

### ISSUE THREAD

**Issue by yinleon** [fastai/fastai#545]
Can I request a feature to add the device number (or `device` in Torch 0.4.0) when calling `to_gpu(m)` in [`LanugaeModelData`](https://github.com/fastai/fastai/blob/master/fastai/text.py#L202)? I am happy to make the changes and submit a PR. This might also benefit other models, too :)

**Comment by jph00** [comment]
Can you just use cuda.set_device?

**Comment by yinleon** [comment]
Yes -- I also see that you can use `learner.model.cuda(device)`, thanks Jeremy!
