### ISSUE TITLE
Error in merge_wiki.py. Happen after prepare_wiki.sh is run

### ISSUE THREAD

**Issue by arnav13081994** [fastai/fastai#554]
I have been trying to run "bash prepare_wiki.sh" and after it downloads and everything finally I get a syntax  error " print(f'Writing to {file_path}...')" in merge_wiki.py line 23.

Can't figure out what is causing this. Any help would be appreciated.

**Comment by sgugger** [comment]
This is a python 3.6 (required for the fastai library) syntax for formatting string, I think you may be using an earlier version of python.

**Comment by arnav13081994** [comment]
Yes you are right. I made an anaconda env 3.6 and everything worked!
