### ISSUE TITLE
learner.fit() duplicate keyword arguments

### ISSUE THREAD

**Issue by MaxTaggart** [fastai/fastai#563]
### Problem

When working through the lang_model.ipynb notebook the following code produced the following error:

```
TEXT = data.Field(lower=True)
FILES = dict(train='wiki.train.tokens', validation='wiki.valid.tokens', test='wiki.test.tokens')
bs,bptt = 80,70
md = LanguageModelData.from_text_files(PATH, TEXT, **FILES, bs=bs, bptt=bptt, min_freq=10)
len(md.trn_dl), md.nt, len(md.trn_ds), len(md.trn_ds[0].text)

em_sz = 200
nh = 500
nl = 3
learner = md.get_model(SGD_Momentum(0.7), em_sz, nh, nl)
reg_fn=partial(seq2seq_reg, alpha=2, beta=1)

clip=0.3
learner.fit(10, 1, wds=1e-6, reg_fn=reg_fn, clip=clip)
```

Error:
```
TypeError: fit() got multiple values for keyword argument 'reg_fn'
```

### Reason For Problem
In `learner.py` in the final call to `fit()` (in `fit_gen()`) both `**kwargs` and `reg_fn` and `clip` get passed to `fit()` which means that if you already specified a `reg_fn` and/or a value for `clip` when calling `learner.fit()` then we end up with duplicate keyword arguments because `reg_fn` and `clip` have already been defined as instance variables of `learner` in the constructor. 

### Proposed Solution
Maybe the API has just evolved so that you always pass `reg_fn` and `clip` to the `learner` constructor. But if the idea is to maintain the ability to pass in different `reg_fn`s and `clip` values at different stages of training then maybe it would be better to check in `fit_gen()` if `reg_fn` or `clip` are already present in the `**kwargs` and if so to pull them out before passing them along to `fit()`.

**Comment by sgugger** [comment]
learner.fit is not supposed to take a reg_fn or clip arguments, it's passing the reg_fn and clip defined inside learner to the fit function of model.py. You should either:
- use the lines learner.reg_fn = reg_fn; learner.clip = clip before calling learner.fit,
or
- use the fit function directly.
