### ISSUE TITLE
proc_df API adjustment fix in courses/ml1 notebooks

### ISSUE THREAD

**Issue by stas00** [fastai/fastai#569]
in courses/ml1/bulldozer_dl.ipynb

replace:

`df, y, mapper = proc_df(df_raw, 'SalePrice', do_scale=True)`

with:

`df, y, nas, mapper = proc_df(df_raw, 'SalePrice', do_scale=True)`

otherwise it fails expecting 3 return values, but getting 4.

and:

in courses/ml1/bulldozer_linreg.ipynb:

replace:

`df, y, mapper, nas = proc_df(df_sub, 'SalePrice', max_n_cat=10, do_scale=True)`

with:

`df, y, nas, mapper = proc_df(df_sub, 'SalePrice', max_n_cat=10, do_scale=True)`

Thank you.

**Comment by stas00** [comment]
moved to https://github.com/fastai/courses/issues/220

**Comment by sgugger** [comment]
Should be fixed by one of your PR.
