### ISSUE TITLE
python2.7/site-packages/fastai/text.py", line 8 SyntaxError: Non-ASCII character '\xe2' 

### ISSUE THREAD

**Issue by UTTAM2311** [fastai/fastai#570]
I tried installing the fastai with pip.
`pip install fastai` .

While importing the module 
`import fastai.text` 
the following error is thrown .

> lib/python2.7/site-packages/fastai/text.py on line 8, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

How to resolve this issue?

**Comment by th3ragex** [comment]
The [environment.yml](https://github.com/fastai/fastai/blob/master/environment.yml) of fast.ai has a dependency to at least Python 3.6.
`- python>=3.6.0`
 An update may resolve your issue.
