### ISSUE TITLE
Framework for documenting functions and API

### ISSUE THREAD

**Issue by hkhanna** [fastai/fastai#571]
I'm a former Practical Deep Learning for Coders (Part 1, v2) student and I'm digging through the framework to understand it in detail. As I do this, I thought it might be helpful for me to document the functions with docstrings and descriptions of the arguments. But I saw this in the documentation:

> We don't want this detailed documentation to create clutter in the code, and we also don't want to overwhelm the user when they just want a quick summary of what a method does. Therefore, docstrings should generally be limited to a single line. The python standard library is documented this way--for instance, the docstring for re.compile() is the single line "Compile a regular expression pattern, returning a pattern object." But the full documentation of the re library on the python web site goes into detail about this method, how it's used, and its relation to other parts of the library.

Since detailed docstrings are discouraged in this project, and since there isn't really another established approach to documenting the functions in this library, I wanted to take Jeremy et al. temperature on which direction to go for documentation so I can start documenting some of the functions. 

[Sphinx](http://www.sphinx-doc.org/en/master/) seems to be fairly standard in the Python community. If folks are fine with this, I can spend the time to learn it and I can submit a PR to get it set up in the library.

**Comment by KaiLicht** [comment]
Hey! I just thought about this yesterday too. I always really liked the keras documentation, both the website and the entirely markdown-based codebase. They're using mkdocs, which makes it really nice and easy to contribute. In the keras project they're also using a custom python script to incorporate the docstrings (mkdocs does not support that by default).

Or: Why not having an auto-generated docstring documentation + a rich mkdocs-style documentation with lots of examples, explanations and insights?

**Comment by jph00** [comment]
We've got the start of a templating system available now in the /docs directory here. The `transforms.*` files show an example of use.
