### ISSUE TITLE
Courses > dl1 > lesson1-rxt50 and lesson1-vgg

### ISSUE THREAD

**Issue by ucffool** [fastai/fastai#572]
Update accuracy() code from the following:
```
log_preds,y = learn.TTA()
probs = np.mean(np.exp(log_preds),0)

accuracy(probs,y)
```
to the following:
```
log_preds,y = learn.TTA()
probs = np.mean(np.exp(log_preds),0)

accuracy_np(probs,y)
```
Current version spits out an error due to data type mismatch. Specifically, in the **lesson1-vgg** notebook it's missing the probs line completely.

**Comment by jph00** [comment]
Good point. Would you be interested in submitting a PR to fix this?
