### ISSUE TITLE
Clarifications about lr_find2()

### ISSUE THREAD

**Issue by terribilissimo** [fastai/fastai#575]
Hi. 

Le me say that I'not opening the present issue for complaining, but just for getting some clarifications.

Performing some experiments, I noticed (Feb 3, 2018) that the LR Finder didn't work on small dataset.

I reported the issue in this blog post: http://forums.fast.ai/t/lesson-1-my-experiments-with-resnet34-and-some-questions/10857

Jeremy kindly encouraged me (as he often does with practitioners) in modifying, with his help, the code so that the finder could run more epochs in case of small dataset. 

I did it and **reported the full code later in the same thread** (proposing some other modification ideas). 

No one acknowledged, but the bosses are pretty busy boys/girls, so I just waited. 

Then, on 20 March 2018 I wrote a PM to Jeremy. It was viewed but not answered. Probably he cannot answer to all the PMs he gets, so I waited.

A week ago, I wrote another forum post, tagging Jeremy, Rachel, and Reshama. I waited, but no one answered.

Yersterday (19 June 2018) I decided to open a pull request.In those last months I obviously maintained my environment up to date. 
So I opened learner.py to check the code for such a pull request, and doh! My proposed modification to the code was there, just with other names for functions and params (e.g `num_it` instead of `run_for`)..!

Now like I said I don't want to complain, and obviously I do not have any claim upon the code (I'm just a student), but why not to say just "Hey boy, we put it into the code."

No matter how little my contribution, It would have been reason of immense satisfaction for me.

Thank you, even if you won't answer.

**Comment by jph00** [comment]
That does sound frustrating. I've been busy recently helping my wife through her brain surgery, so I haven't been keeping on top of the forums or PRs, but I'd guess that what happened is that someone else submitted a PR with the same thing.

**Comment by terribilissimo** [comment]
It is awful to bother about such trifles when one has something really
serious (like brain surgery) to worry about.

Let me just say that reading a post forum of mine and then submit a PR with
exactly the same code is unkind, unpolite, and absolutely contrary to the
spirit of our community (or any other community whatsoever, I reckon).

Thanks for your kind reply.
Andrea
