### ISSUE TITLE
proc_df method modifies passed df

### ISSUE THREAD

**Issue by th3ragex** [fastai/fastai#580]
The proc_df method seems to drop all ignored fields (ignore_flds) from the provided dataframe (df) right before it gets copied.
If a subset is used this behaviour doesn't happen due to the copy operation within the get_sample method.

First lines of the proc_df method:
```
if not ignore_flds: ignore_flds=[]
if subset: df = get_sample(df,subset)
ignored_flds = df.loc[:, ignore_flds]
df.drop(ignore_flds, axis=1, inplace=True)
df = df.copy()
```

Something like: 
```
if not ignore_flds: ignore_flds=[]
if subset:  
    df = get_sample(df,subset)
else:
    df = df.copy()
ignored_flds = df.loc[:, ignore_flds]
df.drop(ignore_flds, axis=1, inplace=True)
```
might solve this issue.

**Comment by jph00** [comment]
Would you be interested in trying to fix this with a PR?
