### ISSUE TITLE
rectangular images

### ISSUE THREAD

**Issue by simonm3** [fastai/fastai#584]
It would be better if cropping and scaling were treated just like any other transformations rather than mandatory crop and resize as square.

I have images that are all 48*900. I don't want to resize them nor do I want to crop them. I thought maybe I could just set the resize and crop to their existing size. However scale only outputs a square image; and the intriguingly named "nocrop" class actually crops at random.

**Comment by yanneta** [comment]
Rectangular images are not an option at the moment. You could try to work
with your own dataset. Here is an example.

https://github.com/yanneta/deep-learning-with-pytorch/blob/master/lesson9-muti-task.ipynb

**Comment by simonm3** [comment]
Thanks. I got it working I think with a couple of hacks - in transforms I
only add the crop transform if crop_type is not none. In image_gen I only
do the scaling if sz is not none.

This seems to work  - at least it ran through training on a tiny sample
without errors. Am I going to come up against some other issues or will
that fix it for now? I am currently precomputing by dataset but it takes
2.5 hours.

**Comment by yanneta** [comment]
On Tue, Jun 26, 2018 at 10:51 AM, simon <notifications@github.com> wrote:

> Thanks. I got it working I think with a couple of hacks - in transforms I
> only add the crop transform if crop_type is not none. In image_gen I only
> do the scaling if sz is not none.
>
> This seems to work - at least it ran through training on a tiny sample
> without errors. Am I going to come up against some other issues or will
> that fix it for now? I am currently precomputing by dataset but it takes
> 2.5 hours.


Are your images large? If they are you should resize them.


>
>

**Comment by simonm3** [comment]
48*900. They are images of rows of text where I am detecting markings which
are often on the left or right so important I don't crop it. I have 1.5m in
the training set so prefer to avoid any processing if possible. I have
already trained this successfully using keras but would like to replicate
the results using fastai/pytorch.

**Comment by simonm3** [comment]
I recall 48 was the minimum size in keras for their pretrained models. 900
retains the ratio of width/height.
