### ISSUE TITLE
Change the way fast.ai is documented

### ISSUE THREAD

**Issue by KaiLicht** [fastai/fastai#596]
Hey all! I recently had a look into documenting python libraries for a work related project. I combined that with digging a little deeper into the fast.ai library. I know that there's already some work done for the documentation and I don't mean to disrespect that, but I thought I share this as an alternative. [Here](http://wp1073433.server-he.de/index.html) you can find a build of the skeleton, which includes all the content from the current /docs directory + [my documentation of the transforms module](http://wp1073433.server-he.de/transforms.html). You can find the source in the /docs folder of [my fastai-fork](https://github.com/KaiLicht/fastai/tree/master/docs).

I'm using sphinx with some extensions. Here's why I think it's a good approach to do it like that:

* **It's easy to get involved:** You don't have to care a lot about the documentation framework. It's almost entirely written in markdown (with some reStructuredText for the autogenerated docstrings). There's one markdown file per module in the [source folder](https://github.com/KaiLicht/fastai/tree/master/docs/source).

* **It's possible and very easy to incorporate autogenerated docstrings.** Sphinx allows to use reStructuredText code blocks to incorporate docstrings. You can individually paste those blocks wherever you feel it's neccessary in the documentation. ([See](https://github.com/KaiLicht/fastai/blob/master/docs/source/transforms.md) the source for the fastai.transforms module)

* **You can include ipython notebooks.** You just have to put the name in the [index.rst](https://github.com/KaiLicht/fastai/blob/master/docs/source/index.rst) file. [As you can see](http://wp1073433.server-he.de/notebooks/TestNotebook.html) that's a pretty neat feature. So even if people do not dive deep into the library they can contribute examples and best practices to show how the library works. 

* **Flexible and easy building and deployment.** You can build the static html files from your fast.ai environment or with a [docker image](https://hub.docker.com/r/kailicht/fastai/~/dockerfile/) I created for this purpose (only one command: `docker run -it --rm -v ~/PathTo/local/fastai:/fastai kailicht/fastai:docs`). It's static html so can be deployed on github.pages, readthedocs (autodeployment) or just on the fast.ai webspace.

I really think that a good documentation is absolutely crucial, especially for projects like fast.ai. It's not only complex in terms of software engineering but also very scientific. Maybe this can be a good starting point for a documentation where people can easily get involved. It's a working skeleton with a framework that gives a lot of room to customize and improve.

@jph00 Let me know if you want me to make a pull request

**Comment by joliva** [comment]
This otherwise wonderful project could really use some proper documentation.  I endorse this approach.

**Comment by swaroopkml96** [comment]
I second this.

**Comment by KaiLicht** [comment]
Hmm, is this an actively maintained project or more something only used for the fast.ai course?

**Comment by sgugger** [comment]
Thanks for the suggestion. Now that Jeremy has decided to create a new version of the library for the next course on October, this project will be maintained with the necessary fixes but we won't begin any major change.

I note the idea for fastai_v1 though, as a proper documentation is definitely on our list of things to do. Thanks for suggesting this!

**Comment by KaiLicht** [comment]
pity, is it generally not planned to make a library, which is used outside the courses?
Should I adapt it to the new one Le just delete it?

**Comment by sgugger** [comment]
We do plan to have a library used outside of the course, and it will be the next version of this one. With the changes in pytorch on one hand, and the new features added as time goes, Jeremy felt he had to start again from scratch to create something more intuitive that ties all the existing APIs together.

Please keep that idea in mind and if you want to adapt it to the fastai_v1, it will be more than welcome!

**Comment by KaiLicht** [comment]
Good to hear, I'll watch fastai and  propose that again!

**Comment by rohitgeo** [comment]
> "... that ties all the existing APIs together."

Wait a minute... that's _very_ interesting! Can you clarify what all APIs we're talking about here?

Is the idea to have fastai be a higher level wrapper over both PyTorch and TensorFlow? That would be terrific!

**Comment by jph00** [comment]
No @sgugger means APIs for vision, NLP, etc. We have no immediate plans for additional backends, but maybe in the future that will change.

**Comment by odysseus0** [comment]
@KaiLicht Do we have a plan for what you proposed here right now?
