### ISSUE TITLE
fastai failed to install

### ISSUE THREAD

**Issue by marjanhs** [fastai/fastai#603]
I am trying to install fastai via conda however when I run 
`conda env update`
I receive and error:

> Executing transaction: failed
2018-07-03 14:48:49,107 - conda.core.link - ERROR - An error occurred while installing package 'conda-forge::widgetsnbextension-3.2.1-py36_0'.
LinkError: post-link script failed for package conda-forge::widgetsnbextension-3.2.1-py36_0

**Comment by sgugger** [comment]
Please use the (forum)[http://forums.fast.ai/] for those issues. Be sure to describe your setup.
