### ISSUE TITLE
Support for Torch=0.4.0

### ISSUE THREAD

**Issue by malhotravasu** [fastai/fastai#604]
Adding support for pytorch=0.4.0 will be much appreciated as it is the latest build as well as the only build which supports Windows completely.

**Comment by pford221** [comment]
There's unofficial support: [](http://forums.fast.ai/t/unofficial-pytorch-0-4-support/16285)

**Comment by stas00** [comment]
@pford221, your markup for the link is broken: http://forums.fast.ai/t/unofficial-pytorch-0-4-support/16285

**Comment by malhotravasu** [comment]
All the tests specified in 'tests' directory fail when using 0.4.0. Maybe the lesson notebooks will work fine :)

**Comment by yurket** [comment]
I run ~5-6 lessons notebooks with pytorch 4.0 on Linux and had to make just a couple small fixes. So the majority of the code should work fine with pytorch 4.0, I suppose.

**Comment by tomthebuzz** [comment]
As I have a hard dependency on Cuda 9.2 I even have the requirement for torch 0.4.1 to resolve the seemingly closed errors in rnn_reg.py:

`
~/anaconda3/lib/python3.6/site-packages/fastai/rnn_reg.py in forward(self, words, dropout, scale)
    174         if padding_idx is None: padding_idx = -1
    175 
--> 176         X = self.embed._backend.Embedding.apply(words,
    177              masked_embed_weight, padding_idx, self.embed.max_norm,
    178              self.embed.norm_type, self.embed.scale_grad_by_freq, self.embed.sparse)

~/anaconda3/lib/python3.6/site-packages/torch/nn/backends/backend.py in __getattr__(self, name)
      8         fn = self.function_classes.get(name)
      9         if fn is None:
---> 10             raise NotImplementedError
     11         return fn
     12 

NotImplementedError: 

`
Any hint on where to start is warmly appreciated. Maybe @yurket has some notes or snippets to go by? Thx for the support.

**Comment by sgugger** [comment]
Closing this as, for one support will stay unofficial for fastai, two, tips and tricks to make the installation work should be discussed on the [forum](http://forums.fast.ai/).

**Comment by aaronlelevier** [comment]
It seems like support for PyTorch `0.4.x` isn't being added because [fastai_v1](https://github.com/fastai/fastai_v1) is being developed, so future versions of PyTorch will be supported by that library?
