### ISSUE TITLE
Learner has RuntimeError

### ISSUE THREAD

**Issue by BitYog** [fastai/fastai#612]
I was working with a dataset (time-series) from a Kaggle competition. I have faced this issue two times. The learner runs well and there are no errors. On calling a ``lr_find()`` the console throws this error:

cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:20

The first time I faced this error, I made the mistake of not doing any encoding, and I understood that the index was out of bounds. This time I used one-hot encoding and still the learner failed. Help??

**Comment by sgugger** [comment]
This is a bug that's probably due to your model definition. Please use the (forum)[forums.fast.ai] to solve your issue.
