### ISSUE TITLE
train_cats() causes SIGSEGV after feather

### ISSUE THREAD

**Issue by Krogsager** [fastai/fastai#616]
Attempts to read categorical values from a dataframe, after calling train_cats(), followed by `to_feather` and `read_feather` causes the error:
> Segmentation fault (core dumped)

Running this code will cause SIGSEGV:
```
import os.path
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from fastai.structured import *

class provokeSIGSEGV(object):

	def main(self):

		df = pd.DataFrame({'account-start': ['2017-02-03', '2017-03-03', '2017-01-01'],
		                   'client': ['Alice Anders', 'Bob Baker', 'Charlie Chaplin'],

		                   })
		train_cats(df) #comment out this line and the code runs fine.

		print("Categorical data can be read before to_feather:")
		print(df.client[0])
		
		df.to_feather(os.getcwd()+'/dfSIGSEGV')
		df = pd.read_feather(os.getcwd()+'/dfSIGSEGV')
		
		print("-but not afterwards.")
		print(df.client[0])
				

if __name__ == "__main__":
    pssv = provokeSIGSEGV()       
    pssv.main()

```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-104-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.3
pytest: 3.6.2
pip: 9.0.3
setuptools: 40.0.0
Cython: None
numpy: 1.14.5
scipy: 1.1.0
pyarrow: 0.8.0
xarray: None
IPython: 6.4.0
sphinx: 1.7.1
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.4
feather: 0.4.0
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by bny6613** [comment]
All train_cats does is:
```
for n,c in df.items():
        if is_string_dtype(c): df[n] = c.astype('category').cat.as_ordered()
```
So, if you remove library dependency and change train_cats call to this snippet, do you still get a segmentation fault?
```
import os.path
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
import sys

class provokeSIGSEGV(object):

	def main(self):

		df = pd.DataFrame({'account-start': ['2017-02-03', '2017-03-03', '2017-01-01'],
		                   'client': ['Alice Anders', 'Bob Baker', 'Charlie Chaplin'],

		                   })
        
		for n,c in df.items():
				if is_string_dtype(c): df[n] = c.astype('category').cat.as_ordered()
                    
		print("Categorical data can be read before to_feather:")
		print(df.client[0])
		
		df.to_feather(os.getcwd()+'/dfSIGSEGV')
		df = pd.read_feather(os.getcwd()+'/dfSIGSEGV')
		
		print("-but not afterwards.")
		print(df.client[0])
				

if __name__ == "__main__":
    pssv = provokeSIGSEGV()       
    pssv.main()
```

**Comment by Krogsager** [comment]
@bny6613 
Hi Nick, I'm getting this:
> NameError: name 'is_string_dtype' is not defined:

So I had to modify your example.
```
import sys
import os.path
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
import pandas as pd
from pandas.api.types import is_string_dtype



class provokeSIGSEGV(object):

    def main(self):

        df = pd.DataFrame({'account-start': ['2017-02-03', '2017-03-03', '2017-01-01'],
                           'client': ['Alice Anders', 'Bob Baker', 'Charlie Chaplin'],

                           })

        for n, c in df.items():
            if is_string_dtype(c): df[n] = c.astype('category').cat.as_ordered()

        print("Categorical data can be read before to_feather:")
        print(df.client[0])

        df.to_feather(os.getcwd() + '/dfSIGSEGV')
        df = pd.read_feather(os.getcwd() + '/dfSIGSEGV')

        print("-but not afterwards.")
        print(df.client[0])


if __name__ == "__main__":
    pssv = provokeSIGSEGV()
    pssv.main()
```

I'm still getting 

> Segmentation fault (core dumped)

Using gdb (GNU Debugger):

> Thread 1 "python" received signal SIGSEGV, Segmentation fault.
> 0x00007ffff5de9e55 in _basic_copy (elsize=1, src=src@entry=0x7ffff7fee040, dst=0x7fff9a4c40e8)
>    from /home/paperspace/anaconda3/envs/fastai/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-x86_64-linux-gnu.so

**Comment by bny6613** [comment]
Hi,
> Hi Nick, I'm getting this:
>NameError: name 'is_string_dtype' is not defined:
>So I had to modify your example.

Sorry, forgot about imports)

So, i tried both examples and i am not able to reproduce this issue. I even tried it on paperspace instance, since i see that you are using paperspace. It seems like there is something wrong with your particular instance, are you able to reproduce it on other vm instances?
![test](https://user-images.githubusercontent.com/7903523/42842347-a6926d48-8a15-11e8-9fd5-c773bb610d44.png)

**Comment by Krogsager** [comment]
I created a new env in python, cloned the fastai master branch, and tested. It works fine.
So the issue is my default environment. Should I abandon it or try to fix it?
I don't know where I would start with debugging so this point it would be easer to just save my files and start over.

**Comment by Krogsager** [comment]
BTW my question still stands ;-)

**Comment by bny6613** [comment]
I am not sure, what to do with it. As you can see, this error is not related to fastai library, but something with external packages - pandas , feather-format, (numpy according to your gdb output). If it is not reproducible outside that specific instanse, it will be pretty hard to fix. I am not very confident with debugging low level code, so you should probably create an Issue in pandas repo and provide the core dump.
