### ISSUE TITLE
Making resizing of Image more efficient

### ISSUE THREAD

**Issue by karanchahal** [fastai/fastai#618]
The code for Image Resizing as of right now is as follows:

```python
if is_y: return scale_min(x, self.sz_y, cv2.INTER_AREA if self.tfm_y == TfmType.PIXEL else cv2.INTER_NEAREST)
else   : return scale_min(x, self.sz,   cv2.INTER_AREA   )
```

I was reading up on Open CV documentation [here](https://docs.opencv.org/2.4/modules/imgproc/doc/geometric_transformations.html?highlight=resize#resize) , more specifically this line.

_To shrink an image, it will generally look best with CV_INTER_AREA interpolation, whereas to enlarge an image, it will generally look best with CV_INTER_CUBIC(slow) or CV_INTER_LINEAR (faster but still looks OK)._

The code for Fast.ai doesn't support the best method for enlarging an image, that is, use ```CV_INTER_LINEAR```.

Do you think it would be a good idea to change that code , so that when we want to shrink the size of image , we continue to use ```cv2.INTER_AREA```, but when we want to enlarge an image we use ```cv2.INTER_LINEAR``` ?

I would be happy to submit a pull request for the change.

**Comment by sgugger** [comment]
This function is almost all the time used to reduce the size of images, which is why the default is cv2.INTER_AREA. A simple PR to define an interpolation depending on the target size wouldn't hurt though.

**Comment by karanchahal** [comment]
👍
