### ISSUE TITLE
Document or automatically install spacy en model

### ISSUE THREAD

**Issue by panozzaj** [fastai/fastai#632]
Thanks for all of your work with the fastai library and online course! I was going through dl1 -> lesson 4 and when I ran:

    spacy_tok = spacy.load('en')

I got the following error:

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-34-70a9937dc522> in <module>()
----> 1 spacy_tokens = spacy.load('en')

~/anaconda3/envs/fastai/lib/python3.6/site-packages/spacy/__init__.py in load(name, **overrides)
     13     if depr_path not in (True, False, None):
     14         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 15     return util.load_model(name, **overrides)
     16 
     17 

~/anaconda3/envs/fastai/lib/python3.6/site-packages/spacy/util.py in load_model(name, **overrides)
    117     elif hasattr(name, 'exists'):  # Path or Path-like to model data
    118         return load_model_from_path(name, **overrides)
--> 119     raise IOError(Errors.E050.format(name=name))
    120 
    121 

OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

Some quick research led to: http://forums.fast.ai/t/lesson-4-oserror-cant-find-model-en/11252 and I fixed it by running `$ python -m spacy download en`.

I'm wondering if we should add a note to the notebook for that lesson. Another (maybe better) solution is to install en_core_web_sm (>= 2.0.0) [via pip](https://github.com/explosion/spacy-models#downloading-models) with the environment.yml since that is the model that is installed when I run the command above.

Just trying to remove any friction -- how would you feel about a pull request for one of these possible solutions?

**Comment by sgugger** [comment]
Any PR fixing this would be welcome, yes. Thanks for volunteering!

**Comment by jetou** [comment]
thank you!

**Comment by yasimk** [comment]
I had a similar error when I tried to download spacy from the web and run in windows. 

I downloaded the English version using the below command and it works fine now. 
python -m spacy download en

**Comment by Chadni-Islam** [comment]
Thank you! :)

**Comment by habibsifat** [comment]
OSError: [E050] Can't find model 'de'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory. site:stackoverflow.com

**Comment by sgugger** [comment]
Yes if you want the model for another language, you will have to specifically download it (same instruction, replace 'en' by 'de').

**Comment by habibsifat** [comment]
" python -m spacy download de " this command does not work

**Comment by sgugger** [comment]
Then that's a Spacy issue, not a fastai one. This is what they indicate [here](https://spacy.io/models/).

**Comment by 1235Lovely** [comment]
Go to command prompt and type the following command:
python -m spacy download en_core_web_lg
python -m spacy link en_core_web_lg en
