### ISSUE TITLE
predict_array does not work with MixedInputModel

### ISSUE THREAD

**Issue by nwertzberger** [fastai/fastai#642]
Something like this for a startup:

    md = ColumnarModelData.from_data_frame(
        PATH,
        val_idxs,
        df,
        yl.astype(np.float32),
        cat_flds=categories,
        bs=1024,
        test_df=df_test)
    m = md.get_learner(
        emb_szs,
        len(df.columns) - len(categories),
        0.04,
        1,
        [1000,500, 100],
        [0.001,0.01, 0.01],
        y_range=y_range)
    # Try this
    m.predict_array(df.values[0,:])

You'll get this error:

    TypeError: forward() missing 1 required positional argument: 'x_cont'

It looks like the predict_array interface doesn't have a way to pass in categorical vs continuous variables, which is required for the underlying class MixedInputModel(nn.Module). In my read around, maybe the predict_array function needs to be overridden for StructuredLearner.

**Comment by sgugger** [comment]
That's probably it, yes. Would you mind proposing a PR to fix this?

**Comment by jph00** [comment]
thanks!
