### ISSUE TITLE
Notebook pascal broken 

### ISSUE THREAD

**Issue by punkt2** [fastai/fastai#644]
The Notebook [pascal](https://github.com/fastai/fastai/blob/master/courses/dl2/pascal.ipynb) from "Lesson 9: Deep Learning Part 2 2018 - Multi-object detection" is broken in Section "Single object detection".

The problem occurs when setting metrics
```
learn.metrics = [detn_acc, detn_l1]
```

```
learn.fit(lr, 1, cycle_len=3, use_clr=(32,5))
```
After the first epoch following exception is thrown.

```
~/fastai/courses/dl2/fastai/model.py in validate(stepper, dl, metrics, seq_first)
    236             batch_cnts.append(batch_sz(x, seq_first=seq_first))
    237             loss.append(to_np(l))
--> 238             res.append([f(preds.data, y.data) for f in metrics])
    239     return [np.average(loss, 0, weights=batch_cnts)] + list(np.average(np.stack(res), 0, weights=batch_cnts))
    240 

~/fastai/courses/dl2/fastai/model.py in <listcomp>(.0)
    236             batch_cnts.append(batch_sz(x, seq_first=seq_first))
    237             loss.append(to_np(l))
--> 238             res.append([f(preds.data, y.data) for f in metrics])
    239     return [np.average(loss, 0, weights=batch_cnts)] + list(np.average(np.stack(res), 0, weights=batch_cnts))
    240 

AttributeError: 'list' object has no attribute 'data'
```

In this case y is a list and has no data attribute.

This commit cause the error https://github.com/fastai/fastai/commit/d1d0b60558ae6dab9b9ad47b5928b144e95946c5

**Comment by punkt2** [comment]
just reinstalled the fastai environment and the notebook works now.

**Comment by punkt2** [comment]
too fast, the error still exists.

**Comment by sgugger** [comment]
Yeah, I see where it comes from: basically the y.data needs to be mapped on to all the elements of the list if y is a list (like [x.data for x in y]). I'll look at it this week, but feel free to propose a PR in the meantime!

**Comment by lharries** [comment]
The current way the accuracy functions in the pascal notebook is setup requires that the full y list be passed in, which is then handled within the function
i.e.
```
def detn_l1(input, target):
    bb_t,_ = target
    bb_i = input[:, :4]
    bb_i = F.sigmoid(bb_i)*224
    return F.l1_loss(V(bb_i),V(bb_t)).data

def detn_acc(input, target):
    _,c_t = target
    c_i = input[:, 4:]
    return accuracy(c_i, c_t)
```

I've sent in a PR which handles y if it's listy, by passing the complete y list/tuple to the function, and therefore the above works as expected :)

**Comment by sgugger** [comment]
Thanks for digging into this! Just changed your code to go with the usual fastai style and will merge when the automatic checks are passed.
