### ISSUE TITLE
ModuleNotFoundError:Windows10 

### ISSUE THREAD

**Issue by srinivasPrashanth027** [fastai/fastai#655]
Download project: `git clone https://github.com/fastai/fastai.git`
1. Move into root folder: `cd fastai`
1. Set up Python environment: `conda env update`
1. Activate Python environment: `conda activate fastai`

After performing the above steps in Windows10 Nvidia GPU system . I am able to activate the fastai environment and i was able to open jupyter notebook too. But when i open any notebook and run the notebook . I found the below Error. ModuleNotFoundError(refer to below screenshot)

![fastai](https://user-images.githubusercontent.com/41332953/43244828-cff57e9a-90c9-11e8-9595-1644eaa535c2.PNG)
Kindly help me here

**Comment by Gokkulnath** [comment]
hi @srinivasPrashanth027 
I guess symlink for fastai folder is missing. Can you check if it is there ?
P.S : Please refrain from raising a issue here instead please use [forums](http://forums.fast.ai/) for such queries. Most of the time you might find the solution already available there .

Regards,
Gokkul

**Comment by srinivasPrashanth027** [comment]
How to check the symlink ?

**Comment by sgugger** [comment]
As @Gokkulnath said, please use the forum for this kind of questions. There is a detailed step by step process to install the library [here](http://forums.fast.ai/t/howto-installation-on-windows/10439), you apparently need to redo step 8.

**Comment by srinivasPrashanth027** [comment]
Fine.. I have sorted out the issue.
Thanks closing it
