### ISSUE TITLE
Can not use pytorch 0.3.1

### ISSUE THREAD

**Issue by mongolia19** [fastai/fastai#656]
I use win10 with no GPU and the newest version.

after running the command "conda env update -f environment-cpu.yml"
everything is OK, but when test is done, all 7 tests failed, because pytorch can not load the DLL:

ImportError while importing test module 'E:\project_src\fastai\tests\test_core.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\__init__.py:3: in <module>
    import cv2,torch
E:\Users\baoyujian\AppData\Local\Continuum\anaconda3\envs\fastai-cpu\lib\site-packages\torch\__init__.py:76: in <module>
    from torch._C import *
E   ImportError: DLL load failed: 找不到指定的模块。

How to solve this?

**Comment by sgugger** [comment]
Hi, please use the [forum](http://forums.fast.ai/) for this.
