### ISSUE TITLE
from fastai cannot import anything

### ISSUE THREAD

**Issue by gaithal** [fastai/fastai#657]
Hi
in my windows machine, i followed the instructions to install ai using anaconda prompt and jupyter captured in the link http://forums.fast.ai/t/howto-installation-on-windows/10439
i completed till step 8 captured in the link above and all executed with no errors.
Now i go to jupyter and import fastai
it works and no errors.
now i try to import from fastai using from fastai.learner import, nothing works
from fastai itself is not recognized and fastai is not recognizable as a package in jupyter.
kindly guide me what i am missing. Appreciate timely help
my mail is gaithal@vmware.com or gaithal2@gmail.com
kindly send me precise instructions to overcome above issue

**Comment by sgugger** [comment]
Please use the [forum](http://forums.fast.ai/) for this kind of issues. My guess is that there is no simlink to the fastai library in the directory you are working in.
