### ISSUE TITLE
nlp notebook-specific help functions

### ISSUE THREAD

**Issue by stas00** [fastai/fastai#662]
dl1/lang_model-arxiv.ipynb and dl1/nlp-arxiv.ipynb have several issues, the main one is not having easy access to their data. 

Someone posted a working code to generate this data, and it's a big chunk of code.
http://forums.fast.ai/t/where-to-download-data-for-these-lessons-4-5-arxiv-wikipedia-etc/8434/11
should I paste it directly into the notebook, or abstract it into some helper function and in which case where should I put it in fastai files? along with the notebooks or is there some special place for that kind of notebook helper utils?

Alternatively, if it has been decided on where to host the notebook datasets, perhaps we could put the datasets there?

Thanks.

**Comment by stas00** [comment]
I guess for now let's just add it into the notebook itself, since it's not being used a the moment anywhere else. Please see: https://github.com/fastai/fastai/pull/669

**Comment by sgugger** [comment]
Thanks for doing this!
