### ISSUE TITLE
run create_toks.py error

### ISSUE THREAD

**Issue by Amitabha2018** [fastai/fastai#666]
when i run create_toks.py ,only the tok_trn.npy can be created. 
i am confused
i would appreciated if anyone can help me

**Comment by sgugger** [comment]
Please use the [forum](http://forums.fast.ai/) for this kind of problems.

**Comment by Amitabha2018** [comment]
Thanks for your reply ,now i am  a member  of this forum already.
i am searching useful information about this error ,but i still can't find.
I have only 8GB RAM ,and the system always said the memory error.
i don't know how to modify the  create_toks.py to adapt my RAM.
I would be most grateful if you could lend me a hand at your convenice.
