### ISSUE TITLE
Python 3.7 code break (async becomes a keyword for Py3.7)

### ISSUE THREAD

**Issue by pjeroff** [fastai/fastai#677]
On the forum, Mr. Cedric Chee (http://forums.fast.ai/t/cuda-syntax-error/20177/5) identified the problem I was having due to the python 3.7 instalation. 

In his words:
_According to Python deprecation plans, async will become a keyword in Python 3.7; it means it can’t be used as an argument name, as it’d be a SyntaxError.

The async keyword was renamed to non_blocking in PyTorch since version 0.4.0. Ref - PyTorch CUDA semantics documentation, PyTorch Pull Request making this change._

**Comment by sgugger** [comment]
Hi,
fastai won't support python 3.7 for this reason, since it won't officially support pytorch 0.4. You should install in an environment with python 3.6.
fastai_v1 will support pytorch 3.7 on the other hand, but that will be for October!
