### ISSUE TITLE
ULMFiT From Scratch

### ISSUE THREAD

**Issue by victorsun123** [fastai/fastai#680]
Is the from_scratch parameter mentioned in train_clas of imdb_scripts  corresponding to the "from scratch" results from table 7 of the ULMFiT paper? Am trying to replicate the results of experiments on IMDB but running from scratch is giving me around 50 percent validation for a binary classification problem, so clearly something isn't working properly. Do you know what the issue is, are there any others flags needed to train from scratch?

Also, what parameters should I use for running "full model", if i set startat =0, it uses freezing, if i set starat=1, its attempts to a load a not yet initialized intermediate class file

**Comment by sgugger** [comment]
Issues are for the library only. This question would be better asked on the [forum](http://forums.fast.ai/). Tagging Sebastian Ruder might be useful.
