### ISSUE TITLE
backwards in ULMFit

### ISSUE THREAD

**Issue by linbojin** [fastai/fastai#683]
Hi, I have a question about this file [pretrain_lm.py](https://github.com/fastai/fastai/blob/8d928df96590fb16998dd4d3268e4fa65fa56977/courses/dl2/imdb_scripts/pretrain_lm.py#L36), if run it with `backwards=True`, is the line 36 correct?
`trn_dl = LanguageModelLoader(trn_lm, bs, bptt)
`
or it should be as follows:
`trn_dl = LanguageModelLoader(trn_lm, bs, bptt, backwards=True)
`

**Comment by sgugger** [comment]
This question should be asked on the [forum](http://forums.fast.ai/).
