### ISSUE TITLE
the error message of python setup.py egg_info" failed with error code 1 in C:\Users\shuxi\AppData\Local\Temp\pip-install-2dzeqo5s\shapely\

### ISSUE THREAD

**Issue by wenouyang** [fastai/fastai#685]
Hi, I followed the following steps to install library

```
Normal installation
Download project: git clone https://github.com/fastai/fastai.git
Move into root folder: cd fastai
Set up Python environment: conda env update step of installing fastai library, 

```

But I got the following error message after running `conda env update`.  I tried `pip install --upgrade setuptools`, but it still generates the following error message. 

```
Collecting shapely (from geopandas>=0.3.0->plotnine->-r C:\Users\shuxi\fastai\condaenv.xnozmcqr.requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\shuxi\AppData\Local\Temp\pip-install-2dzeqo5s\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\shuxi\AppData\Local\Temp\pip-install-2dzeqo5s\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\Users\shuxi\Anaconda3\envs\fastai\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\shuxi\AppData\Local\Temp\pip-install-2dzeqo5s\shapely\

CondaValueError: pip returned an error
```

**Comment by AstaTus** [comment]
I have the same error   how do you solve it???@wenouyang

**Comment by Killerkirschli** [comment]
I have the same error, have one of you been able to solve it? @wenouyang  @AstaTus

**Comment by Mapharazzo** [comment]
**Worked for me in windows 10 after the same error, but gets too complicated**

Download the Python 3.6 version of Shapely from https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely

Install the wheel file with pip **and remember to activate the anaconda environment beforehand**

(source: https://stackoverflow.com/questions/43182999/issue-installing-shapely-python-package)

After this step, the "conda env update" will just install a couple more packages and then fail to install Fiona. The install instructions are pretty complicated for windows here and i personally gave up. If one of you guys could make a detailed guide on how to get through this installation, it'll be much appreciated.
