### ISSUE TITLE
Cannot set learn.precompute=True and then fit

### ISSUE THREAD

**Issue by ThomasBourgeois** [fastai/fastai#692]
Hi there, 
Following fast.ai courses and jupyter notebook lesson2-image_models.ipynb
After a couple of cycles of gradient descent, I'm trying to set precompute to True (and model is frozen), and I get this error when I try to continue for a few cycles: 
"
AttributeError                            Traceback (most recent call last)
<ipython-input-37-3acc59d457b3> in <module>()
----> 1 learn.fit(lr, 2, cycle_len=1, cycle_mult=2)

~/fastai/courses/dl1/fastai/learner.py in fit(self, lrs, n_cycle, wds, **kwargs)
    302         self.sched = None
    303         layer_opt = self.get_layer_opt(lrs, wds)
--> 304         return self.fit_gen(self.model, self.data, layer_opt, n_cycle, **kwargs)
    305 
    306     def warm_up(self, lr, wds=None):

~/fastai/courses/dl1/fastai/conv_learner.py in data(self)
    138 
    139     @property
--> 140     def data(self): return self.fc_data if self.precompute else self.data_
    141 
    142     def create_empty_bcolz(self, n, name):

AttributeError: 'ConvLearner' object has no attribute 'fc_data'
"

How can that be ?

**Comment by sgugger** [comment]
Please use the [forum](http://forums.fast.ai/) for those questions. Be sure to share more details (for instance how you created your learner) as it'll help people give you an answer faster.
