### ISSUE TITLE
Can not import get_rnn_classifier. 

### ISSUE THREAD

**Issue by happypetewht** [fastai/fastai#694]
I can not import get_rnn_classifier from lm_rnn.py. When I typed, it gives me this information:
![image](https://user-images.githubusercontent.com/26719562/43981423-c34b5168-9cbf-11e8-809b-2bcd8055a94a.png)

but if I import other modules, it works perfectly. For example
![image](https://user-images.githubusercontent.com/26719562/43981539-38cb1220-9cc0-11e8-89c7-a9cd4d0d3066.png)

**Comment by alesee** [comment]
`fastai.lm_rnn.get_rnn_classifier` imports on my end
<img width="582" alt="screen shot 2018-08-11 at 10 40 13 pm" src="https://user-images.githubusercontent.com/24426271/43997923-8f433c20-9db7-11e8-863a-05479373b1a0.png">

you can try updating your version of the library with `git pull`

**Comment by happypetewht** [comment]
Thank for sharing that. I am using Google Colab now. Maybe that is the problem.

**Comment by alesee** [comment]
you can install the latest version on goggle colab with `pip install git+https://github.com/fastai/fastai.git`

**Comment by happypetewht** [comment]
I also tried that too. Unfortunately, same issues.

**Comment by sakimahesh** [comment]
@happypetewht  This error was due to a spelling mistake. Update the function call to 'get_rnn_classifer' instead of 'get_rnn_classifier'. I faced this error in line 76 of train_clas.py.

**Comment by sgugger** [comment]
Hey all, could you please use the [forum](http://forums.fast.ai/) to discuss those issues? If there are typos to correct don't hesitate to submit a PR.
get_rnn_classifier and get_rnn_classifer should both work as there is a link from one to the other in the latest version.
