### ISSUE TITLE
fastai modules lack documentatation on module level

### ISSUE THREAD

**Issue by dov** [fastai/fastai#695]
The fastai library lacks documentation on the module level. As an example the structured.txt file starts like this:

```
from .imports import *

from sklearn_pandas import DataFrameMapper
from sklearn.preprocessing import LabelEncoder, Imputer, StandardScaler
from pandas.api.types import is_string_dtype, is_numeric_dtype
from sklearn.ensemble import forest
from sklearn.tree import export_graphviz
```
I would like to see a blurb describing the contents of its file, why it makes up a unit, and a short description of how to use it.

In addition there are lots of methods in the fastai that don't include documentation. This makes it difficult to follow an algorithm.

**Comment by sgugger** [comment]
As it's minimally maintained, there won't be an effort to change the documentation of fastai now (although any PR in that sense will be accepted). fastai_v1 will be better documented.
