### ISSUE TITLE
Don't use import *

### ISSUE THREAD

**Issue by dov** [fastai/fastai#696]
This is a feature request, which is highly opinionated, but almost all python coding guidelines, recommends that all imports should be explicit, and that `from foo import *` should never be used. There are several reasons for this, including:

* tractability - Where do I find the source code of a specific function?
* function collisions - What if two modules declares a method with the same name?

fastai makes heavily use of `import *` which makes the sources difficult to follow.

**Comment by sgugger** [comment]
This had been endlessly debated on the [forum](http://forums.fast.ai/), lately [here](http://forums.fast.ai/t/recommendation-replace-import-with-import-as/19836) for the development of fastai_v1.
There won't be any change to the way things are imported in fastai as it's only maintained minimally while we develop the next version.
