### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by gutouyu** [fastai/fastai#7]
### How to contribute?
I'd like to contribute to this project. But I don't know where to start. Is there any suggestions? Thank you.

**Comment by trusty** [comment]
Fork this repo and make the changes in your repo. once you are ready, ask for a pull request.

**Comment by trusty** [comment]
https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by gutouyu** [comment]
is this project still alive? I see your pr, hopefully it will be merged. :)

**Comment by trusty** [comment]
it is merged
