### ISSUE TITLE
Lesson 1 Issues

### ISSUE THREAD

**Issue by BSalita** [fastai/fastai#70]
Lesson 1 has developed some issues (empty graphs and Value Error). Described at http://forums.fast.ai/t/anyone-able-to-run-the-lesson-1-notebook/7190/45

Update: Issue with empty graphs resolved by latest github updates. Value Error still an issue.

**Comment by reshamas** [comment]
@bsalita I went through Forum notes and added (is_test=True) and that did not solve the error.   Not sure what to do next.

**Comment by jph00** [comment]
As I mentioned on the forum, it's because of the change to `TTA`. I'm checking in a fix to the notebook now - but it's worth making sure you understand how TTA now works so you know how to fix this kind of issue yourself in the future. Let me know on the forums if you have any questions.

**Comment by BSalita** [comment]
Thanks. Your fixes have resolved the issues. lesson1 runs to expected completion (Windows + CUDA 9.0).
