### ISSUE TITLE
Testing during setup on an EC2 Failing

### ISSUE THREAD

**Issue by ssmostagh** [fastai/fastai#701]
I spun up the Ubuntu Deep Learning AMI on g2.2xlarge EC2 (it's an older generation instance but does have GPU) to access a Jupyter notebook to do this course. I chose to use the terminal in the Jupyter environment to follow the set up steps and was able to follow the normal installation path with the following commands:
`git clone https://github.com/fastai/fastai.git`
`cd fastai`
`conda env update`
`source activate fastai`

However, I wasn't able to get all the tests to pass when I ran `pytest tests` and received the result of 49 tests passing, 1 failing, and 1 being skipped. The following message was displayed for the one I think failed:
```
_________________________________________________________ test_T __________________________________________________________

HalfTensorMock = <MagicMock name='HalfTensor' id='139635496833544'>

    @mock.patch("fastai.core.torch.cuda.HalfTensor")
    def test_T(HalfTensorMock):
      tensor = torch.ones([1, 2])
>     assert core.T(tensor) is tensor
E     assert \n 1  1\n[torch.cuda.FloatTensor of size 1x2 (GPU 0)]\n is \n 1  1\n[torch.FloatTensor of size 1x2]\n
E      +  where \n 1  1\n[torch.cuda.FloatTensor of size 1x2 (GPU 0)]\n = <function T at 0x7eff810ad1e0>(\n 1  1\n[torch.FloatTensor of size 1x2]\n)
E      +    where <function T at 0x7eff810ad1e0> = core.T
tests/test_core.py:38: AssertionError
==================================================== warnings summary =====================================================
tests/test_core.py::test_T
  /home/ubuntu/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/cuda/__init__.py:97: UserWarning:
      Found GPU0 GRID K520 which is of cuda capability 3.0.
      PyTorch no longer supports this GPU because it is too old.

    warnings.warn(old_gpu_warn % (d, name, major, capability[1]))

-- Docs: http://doc.pytest.org/en/latest/warnings.html
=============================== 1 failed, 49 passed, 1 skipped, 1 warnings in 5.39 seconds ================================
```

I tried changing to the CPU environment with `source activate fastai-cpu` but there's an issue and I get the error:
```
Could not find conda environment: fastai-cpu
You can list all discoverable environments with `conda info --envs`.
```

To troubleshoot this I ran `conda update -n base conda` and then followed the same installation path instructions with `conda env update` which allowed me to stop using `source activate fastai`.  I was able to use `conda activate fastai` but still got the above error attempting to run `pytest tests` and `conda activate fastai-cpu`

**Comment by Gokkulnath** [comment]
@ssmostagh  You need to create a separate environment for cpu-only version of fastai.  
you can use : conda env create -f environment-cpu.yml to create the same. 
Once you have created the environment you might be able to do conda activate fastai-cpu. 

Regarding the tests that are failing, Those are valid cases of that should fail (i believe). If you observe the error stack, it is trying to create half precision tensors which were not available with older GPU's.

**P.S :** Please forum for discussing issues like this. you will get your responses faster.

~Gokkul
