### ISSUE TITLE
run train_clas.py error

### ISSUE THREAD

**Issue by Amitabha2018** [fastai/fastai#702]
when i run train_clas.py  the error occur,how i issue this?
File "train_clas.py", line 141, in train_clas
    learn.fit(lrs, 1, wds=wd, cycle_len=None if use_regular_schedule else 1)

 File "/home/yhl/anaconda3/envs/fastai/lib/python3.6/site-packages/fastai/text.py", line 113, in __getitem__
    return np.array(x),self.y[idx]
IndexError: index 91252 is out of bounds for axis 0 with size 80000

**Comment by sgugger** [comment]
Please use the [forum](http://forums.fast.ai/) for this. You might also want to share more of your code so that people can help you more easily.
