### ISSUE TITLE
Cannot load pretrained InceptionResnetV2

### ISSUE THREAD

**Issue by jalola** [fastai/fastai#706]
I tried to load pretrained InceptionResnetV2 by:
`learn = ConvLearner.pretrained(arch, data)` 
where arch = inceptionresnet_2, but I got the following error:

> KeyError: unexpected key 'classif.bias' fastai in state_dict'

I checked and there is a a mismatching (module `torch.imports` vs `inceptionresnetv2 ` class) as followings:

https://github.com/fastai/fastai/blob/master/fastai/torch_imports.py#L65
which uses inceptionresnetv2-d579a627

https://github.com/fastai/fastai/blob/master/fastai/models/inceptionresnetv2.py#L8
which uses inceptionresnetv2-520b38e4

I replaced d579a627 with 520b38e4 (also download its pretrained weights) and it works.

**Comment by sgugger** [comment]
Good catch. Would you mind suggesting a PR that makes this change in fastai?

**Comment by Gokkulnath** [comment]
@jalola i have raised the PR. #707 .

**Comment by sgugger** [comment]
Thanks!

**Comment by jalola** [comment]
Thanks both
