### ISSUE TITLE
Add Binary Classification (from CSV) Example

### ISSUE THREAD

**Issue by mknippen** [fastai/fastai#708]
When learning machine learning, one of the most often used examples is passing in a CSV file and trying to determine if something has happened or not. (For example, fraud detection, purchase predictions, ad clicks, titanic deaths, etc)

Fast.ai has some amazing tools for testing these things and exploring data, and I would love to use it in this use case. Is this something that Fast.ai supports? Is there a particular video in the class that would help with this?

Any help would be great.

**Comment by jph00** [comment]
Please use the forum.
