### ISSUE TITLE
ModuleNotFoundError: No module named 'testfixtures'

### ISSUE THREAD

**Issue by ReinoutHeeck** [fastai/fastai#709]
After installing fastai for the first time, running the tests fails:

 pytest tests/test_core.py 
...
ImportError while importing test module '/home/reinz/Documents/fastai_reinz/fastai/tests/test_core.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_core.py:6: in <module>
    from testfixtures import tempdir
E   ModuleNotFoundError: No module named 'testfixtures'

executing 
  conda install testfixtures

resolved this problem...

**Comment by sgugger** [comment]
Added it in the environment. Thanks for pointing this out!
