### ISSUE TITLE
Learn.predict_array will fail when learn.precompute is true

### ISSUE THREAD

**Issue by fromLittleAcorns** [fastai/fastai#717]
I think this is a genuine problem, it caught me out for a while until I realised what was happening. It would be pretty easy to put a switch in place to overcome this by temporatily switching the precompute off and then back on when leaving the routine.  If you would like me to do this and generate a pull request please let me know

**Comment by sgugger** [comment]
Oh, it could be messy indeed. Please feel free to propose a PR about this.

**Comment by fromLittleAcorns** [comment]
Will do, Ill have a look at it tomorrow

**Comment by fromLittleAcorns** [comment]
I have submitted a pull request now so hopefully we can close this one

https://github.com/fastai/fastai/pull/733

**Comment by sgugger** [comment]
Merged so this can be closed.
