### ISSUE TITLE
RandomScaleXY instantiation issue?

### ISSUE THREAD

**Issue by sogaiu** [fastai/fastai#72]
In 5300b154a, RandomScaleXY was added with constructor signature:

```python
def __init__(self, sz, max_zoom, p=0.75, tfm_y=TfmType.NO):
```

https://github.com/fastai/fastai/commit/5300b154af0641580f67708eeb26d981fdf465d1#diff-48685f6197acf069ae438de1ac77a613R320

Later in the same file, there is a definition for image_gen, where RandomScaleXY is used:

```python
scale = [RandomScaleXY(sz, max_zoom, tfm_y) if max_zoom is not None else ScaleXY(sz, tfm_y)]
```

https://github.com/fastai/fastai/commit/5300b154af0641580f67708eeb26d981fdf465d1#diff-48685f6197acf069ae438de1ac77a613R409

Isn't tfm_y (local to image_gen) being used as the value of the p parameter?

Should that not be:

```python
scale = [RandomScaleXY(sz, max_zoom, tfm_y=tfm_y) if max_zoom is not None else ScaleXY(sz, tfm_y)]
```
?

**Comment by jph00** [comment]
@yanneta do you want to look at this?

**Comment by yanneta** [comment]
I will.

**Comment by yanneta** [comment]
thanks @sogaiu. You are right. This is a bug. I fixed it.
