### ISSUE TITLE
Input type (CUDAFloatTensor) and weight type (CPUFloatTensor) should be the same

### ISSUE THREAD

**Issue by pricel3ss** [fastai/fastai#721]
Hey gang, sorry to post this here but i think it could be a real issue.

I cloned the repo and have been experimenting using the lesson 8 pascal-multi.ipynb notebook. 

**I have cloned all the data sets succesfully and didn't edit any of the code other than the paths to the input data sets. Finally, i installed fastai using pip install fastai and seem to have confirmed that I am using the correct version of pytorch.**

After training the model, this line appears to fail due to a mismatch in weight types and input types : 

batch = learn.model(x)

Error thrown : 

RuntimeError: Input type (CUDAFloatTensor) and weight type (CPUFloatTensor) should be the same

I sincerely apologize if this is the wrong place to post this, but I thought it could be an important error.

**Comment by sgugger** [comment]
Please the [forum](http://forums.fast.ai/) for these questions. The error message indicates you didn't pass your model on the GPU.

**Comment by pricel3ss** [comment]
I ran the notebook out of the box. I didn't change a line of code other than the input directories. The error was within the classes...
