### ISSUE TITLE
if imdb_scripts can be run on windows computer?

### ISSUE THREAD

**Issue by Sandy4321** [fastai/fastai#726]
if https://github.com/fastai/fastai/tree/master/courses/dl2/imdb_scripts  can be run on windows computer, for example windows computer torch installation is impossible

**Comment by sgugger** [comment]
Pytorch can now be installed on Windows, there is also a [thread on the forum](http://forums.fast.ai/t/howto-installation-on-windows/10439) on how to install fastai on Windows.
