### ISSUE TITLE
problem with shapely package in windows

### ISSUE THREAD

**Issue by tfriedel** [fastai/fastai#729]
when executing conda env update in anaconda3 5.2 on windows 10 this error prevents the installation of the environment:

> Collecting shapely (from geopandas>=0.3.0->plotnine->-r S:\projects\fastai\condaenv.rek9wsqw.requirements.txt (line 9))
>   Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\Thomas\AppData\Local\Temp\pip-install-kvdh_caj\shapely\setup.py", line 80, in <module>
>         from shapely._buildcfg import geos_version_string, geos_version, \
>       File "C:\Users\Thomas\AppData\Local\Temp\pip-install-kvdh_caj\shapely\shapely\_buildcfg.py", line 200, in <module>
>         lgeos = CDLL("geos_c.dll")
>       File "S:\toolkits\anaconda3-5.2.0\envs\fastai\lib\ctypes\__init__.py", line 348, in __init__
>         self._handle = _dlopen(self._name, mode)
>     OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden
>

**Comment by evanbpierce** [comment]
Try this:
conda config --add channels conda-forge

Then try again.

**Comment by sgugger** [comment]
Closing this as it seems to have solved the problem. Please reopen if needed.
