### ISSUE TITLE
Setup fastai environment failed.

### ISSUE THREAD

**Issue by bzqweiyi** [fastai/fastai#732]
I have set up the fastai using the method guide. Both of them are failed. 
I have using two system one is maxos, another one is windows 10. 
Although I can use conda activate fastai. But in my project I have change the environment to the new fastai. After build the project, both of them said ModuleNotFoundError: No module named 'fastai'. 
**So could pls help me to solve this problem?** Many thanks. BTW, My IP address is in China.

**Comment by sgugger** [comment]
You should use the [forums](http://forums.fast.ai/) for this. Are you sure you have a simlink to the fastai folder in your workind directory?
