### ISSUE TITLE
MultiBatchRNN: AttributeError: 'MultiBatchRNN' object has no attribute 'hidden'

### ISSUE THREAD

**Issue by briandw** [fastai/fastai#737]
MultiBatchRNN as defined in lm_rnn.py : 127 is a subclass of class RNN_Encoder. RNN_Encoder sets it's self.hidden var at the end of the forward method. 

MultiBatchRNN references self.hidden before calling super.forward
This results in 
`AttributeError: 'MultiBatchRNN' object has no attribute 'hidden'`

**Comment by sgugger** [comment]
Could you share a bit more about when you get the error? Normally there has been a call to the reset method of MultiBatchRNN (which is the same as RNN_Encoder) that creates this hidden state.

**Comment by briandw** [comment]
I was trying to use the MultiBatchRNN class outside of the fastai training system. I added the reset call in and it's working fine. Thanks.
