### ISSUE TITLE
fix_missing possible bug?

### ISSUE THREAD

**Issue by EKami** [fastai/fastai#74]
On [this line](https://github.com/fastai/fastai/blob/6db37b3f6d98d38dfc9d770b85beb547a0069f44/fastai/structured.py#L265) the `fix_missing` function would "fix" a given column if it contains any missing values in it by filling in the `NaN` by the median and adding a new column like `my_column_name_na`.
The way we use it is typically like this (by passing in the `na_dict` from the train dataset to the test dataset):
```
train_df, y, nas, mapper = proc_df(train_df, 'Sales', do_scale=True) 
test_df, _, nas, mapper = proc_df(test_df, 'Sales', do_scale=True, mapper=mapper, na_dict=nas)
```
Now what happens if both dataframes has, say, a column named `material` and this columns has no `NaN` in `train_df` but do have `NaN` in `test_df`? We will end up with `test_df` having 1 more column than `train_df` and it will break the number of inputs for our model right?

**Comment by AdityaSoni19031997** [comment]
We might need to look for nan's in test set also?

**Comment by EKami** [comment]
> We might need to look for nan's in test set also?

I don't understand the question. But yes, NaN could exists in the test set and not in the train set and given the actual code that would cause some issues regarding the resulting dimensions of the 2 sets.

**Comment by AdityaSoni19031997** [comment]
Actually I was always under the impression that the test set will atleast won't contain that or will have a method to auto resolve that issues or remove that particular entry..
Thanks.

**Comment by jph00** [comment]
Yes it could do, I think. I guess give it a go and see if you can come up with a situation where it fails - if you can, a PR to fix would be appreciated! :)

**Comment by jph00** [comment]
I'll close this in the absence of a failing test case - feel free to reopen if you manage to create one.

**Comment by AdityaSoni19031997** [comment]
Can we use `proc_df` in the testset?
It seems that `y_fld` is to be mentioned?

**Comment by AdityaSoni19031997** [comment]
Ran into this issue while trying out the kaggle's House Regression Price Prediction Competition
