### ISSUE TITLE
Installation of Fast ai fails on local machine

### ISSUE THREAD

**Issue by jaideep11061982** [fastai/fastai#742]
fastai/setup.py
Collecting torch<0.4 (from fastai)
  Using cached https://files.pythonhosted.org/packages/5f/e9/bac4204fe9cb1a002ec6140b47f51affda1655379fe302a1caef421f9846/torch-0.1.2.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JAIDEE~1\AppData\Local\Temp\pip-install-r9nxq9dk\torch\setup.py", line 11, in <module>
        raise RuntimeError(README)
    RuntimeError: PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).

    Please follow the instructions at http://pytorch.org/ to install with miniconda instead.

**Comment by sgugger** [comment]
Hi all, I'm closing this here as it should be discussed on the [forum](http://forums.fast.ai/). Thanks!

**Comment by jaideep11061982** [comment]
I very well use Python 3.6
Pip install fastai dsnt completes without error
