### ISSUE TITLE
Dependency `jupyter` is 3 years old

### ISSUE THREAD

**Issue by elgalu** [fastai/fastai#746]
Hi, dependency `jupyter` is [3 years old](https://pypi.org/project/jupyter/#history), any chance is no longer needed or should switch to the [notebook](https://pypi.org/project/notebook/#history) package maybe?

https://github.com/fastai/fastai/blob/b0d0b101e68e0922fe883160b6bd51a2b701ed83/requirements.txt#L17

Also there is [jupyter_core](https://pypi.org/project/jupyter_core/#history) last update 1 year ago. Is that also needed?

**Comment by sgugger** [comment]
Not sure we'll change the requirements on this one, it's minimally maintained while we move to fastai_v1 where we'll have more recent requirements.
I'll keep that in mind for the new version!
