### ISSUE TITLE
Torch Requirements

### ISSUE THREAD

**Issue by erikgaas** [fastai/fastai#752]
Is there a reason fastai needs a torch<0.4 requirement? 

I was testing 0.3.1 and I ran into trouble with DataLoader batching where calling next on a DataLoader never seemed to terminate. This is on simple 256x256 images. This is on an AWS instance. Oddly if I use an instance with a large number of vCPUs (30) and a lot of RAM it works fine and returns a batch. 

But if I upgrade pytorch to 0.4, despite the fastai warning, then it everything works fine even on the lower resource instances.

Would it be okay to change the requirement to torch<=0.4?

**Comment by sgugger** [comment]
As it has been discussed on the [forum](http://forums.fast.ai/t/unofficial-pytorch-0-4-support/16285) the support for pytorch 0.4 isn't official and there are probably multiple bugs. Fastai_v1 will use the latest version of pytorch but 0.7 will stick to pytorch 0.3.
