### ISSUE TITLE
Query about the 18mins training on imageNet

### ISSUE THREAD

**Issue by garyhujingyao** [fastai/fastai#755]
It said here([http://www.fast.ai/2018/08/10/fastai-diu-imagenet/](url)) that the first official release of nexus-scheduler, including the features merged from the fast.ai tools, is planned for Aug 25th. But I can not find it anywhere. 

Does someone has any information about it? Any update would be very appreciated!

**Comment by jph00** [comment]
Try asking on this repo: https://github.com/diux-dev/imagenet18
