### ISSUE TITLE
cv2 cannot read gif picture

### ISSUE THREAD

**Issue by cy69855522** [fastai/fastai#756]
HBox(children=(IntProgress(value=0, description='Epoch', max=1), HTML(value='')))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/fastai/dataset.py in open_image(fn)
    227         try:
--> 228             im = cv2.imread(str(fn), flags).astype(np.float32)/255
    229             if im is None: raise OSError(f'File not recognized by opencv: {fn}')

AttributeError: 'NoneType' object has no attribute 'astype'

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
<ipython-input-70-f34ad430deec> in <module>()
      3 lrs = np.arange(lr_start, lr_end, (lr_end - lr_start) / len(learn.get_layer_groups()))
      4 #周期性学习率尝试
----> 5 learn.lr_find(lrs / 1000)
      6 #绘制学习率曲线
      7 learn.sched.plot_lr()

/usr/local/lib/python3.6/dist-packages/fastai/learner.py in lr_find(self, start_lr, end_lr, wds, linear, **kwargs)
    328         layer_opt = self.get_layer_opt(start_lr, wds)
    329         self.sched = LR_Finder(layer_opt, len(self.data.trn_dl), end_lr, linear=linear)
--> 330         self.fit_gen(self.model, self.data, layer_opt, 1, **kwargs)
    331         self.load('tmp')
    332 

/usr/local/lib/python3.6/dist-packages/fastai/learner.py in fit_gen(self, model, data, layer_opt, n_cycle, cycle_len, cycle_mult, cycle_save_name, best_save_name, use_clr, use_clr_beta, metrics, callbacks, use_wd_sched, norm_wds, wds_sched_mult, use_swa, swa_start, swa_eval_freq, **kwargs)
    232             metrics=metrics, callbacks=callbacks, reg_fn=self.reg_fn, clip=self.clip, fp16=self.fp16,
    233             swa_model=self.swa_model if use_swa else None, swa_start=swa_start,
--> 234             swa_eval_freq=swa_eval_freq, **kwargs)
    235 
    236     def get_layer_groups(self): return self.models.get_layer_groups()

/usr/local/lib/python3.6/dist-packages/fastai/model.py in fit(model, data, n_epochs, opt, crit, metrics, callbacks, stepper, swa_model, swa_start, swa_eval_freq, **kwargs)
    148 
    149         if not all_val:
--> 150             vals = validate(model_stepper, cur_data.val_dl, metrics)
    151             stop=False
    152             for cb in callbacks: stop = stop or cb.on_epoch_end(vals)

/usr/local/lib/python3.6/dist-packages/fastai/model.py in validate(stepper, dl, metrics)
    204     stepper.reset(False)
    205     with no_grad_context():
--> 206         for (*x,y) in iter(dl):
    207             preds, l = stepper.evaluate(VV(x), VV(y))
    208             if isinstance(x,list): batch_cnts.append(len(x[0]))

/usr/local/lib/python3.6/dist-packages/fastai/dataloader.py in __iter__(self)
     86                 # avoid py3.6 issue where queue is infinite and can result in memory exhaustion
     87                 for c in chunk_iter(iter(self.batch_sampler), self.num_workers*10):
---> 88                     for batch in e.map(self.get_batch, c):
     89                         yield get_tensor(batch, self.pin_memory, self.half)
     90 

/usr/lib/python3.6/concurrent/futures/_base.py in result_iterator()
    584                     # Careful not to keep a reference to the popped future
    585                     if timeout is None:
--> 586                         yield fs.pop().result()
    587                     else:
    588                         yield fs.pop().result(end_time - time.time())

/usr/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    423                 raise CancelledError()
    424             elif self._state == FINISHED:
--> 425                 return self.__get_result()
    426 
    427             self._condition.wait(timeout)

/usr/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

/usr/lib/python3.6/concurrent/futures/thread.py in run(self)
     54 
     55         try:
---> 56             result = self.fn(*self.args, **self.kwargs)
     57         except BaseException as exc:
     58             self.future.set_exception(exc)

/usr/local/lib/python3.6/dist-packages/fastai/dataloader.py in get_batch(self, indices)
     73 
     74     def get_batch(self, indices):
---> 75         res = self.np_collate([self.dataset[i] for i in indices])
     76         if self.transpose:   res[0] = res[0].T
     77         if self.transpose_y: res[1] = res[1].T

/usr/local/lib/python3.6/dist-packages/fastai/dataloader.py in <listcomp>(.0)
     73 
     74     def get_batch(self, indices):
---> 75         res = self.np_collate([self.dataset[i] for i in indices])
     76         if self.transpose:   res[0] = res[0].T
     77         if self.transpose_y: res[1] = res[1].T

/usr/local/lib/python3.6/dist-packages/fastai/dataset.py in __getitem__(self, idx)
    165             xs,ys = zip(*[self.get1item(i) for i in range(*idx.indices(self.n))])
    166             return np.stack(xs),ys
--> 167         return self.get1item(idx)
    168 
    169     def __len__(self): return self.n

/usr/local/lib/python3.6/dist-packages/fastai/dataset.py in get1item(self, idx)
    158 
    159     def get1item(self, idx):
--> 160         x,y = self.get_x(idx),self.get_y(idx)
    161         return self.get(self.transform, x, y)
    162 

/usr/local/lib/python3.6/dist-packages/fastai/dataset.py in get_x(self, i)
    237         super().__init__(transform)
    238     def get_sz(self): return self.transform.sz
--> 239     def get_x(self, i): return open_image(os.path.join(self.path, self.fnames[i]))
    240     def get_n(self): return len(self.fnames)
    241 

/usr/local/lib/python3.6/dist-packages/fastai/dataset.py in open_image(fn)
    230             return cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
    231         except Exception as e:
--> 232             raise OSError('Error handling image at: {}'.format(fn)) from e
    233 
    234 class FilesDataset(BaseDataset):

OSError: Error handling image at: ./data/valid/1/0f1d793468ca4127bb3fda4ee3beb0a5.gif

Thx for such a wonderful package, however, there is a problem caused by cv2. I will appreciate it if you can improve it.

**Comment by sgugger** [comment]
Please use the [forum](http://forums.fast.ai/) for errors like this. Sharing the image that opencv can't open would also be helpful.
