### ISSUE TITLE
fit bug

### ISSUE THREAD

**Issue by cy69855522** [fastai/fastai#758]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-9ef9e1061184> in <module>()
----> 1 learn.fit(lrs, epoch, cycle_len=1, cycle_mult=2)

/content/drive/AI/cloud/fastai/learner.py in fit(self, lrs, n_cycle, wds, **kwargs)
    300         self.sched = None
    301         layer_opt = self.get_layer_opt(lrs, wds)
--> 302         return self.fit_gen(self.model, self.data, layer_opt, n_cycle, **kwargs)
    303 
    304     def warm_up(self, lr, wds=None):

/content/drive/AI/cloud/fastai/learner.py in fit_gen(self, model, data, layer_opt, n_cycle, cycle_len, cycle_mult, cycle_save_name, best_save_name, use_clr, use_clr_beta, metrics, callbacks, use_wd_sched, norm_wds, wds_sched_mult, use_swa, swa_start, swa_eval_freq, **kwargs)
    247             metrics=metrics, callbacks=callbacks, reg_fn=self.reg_fn, clip=self.clip, fp16=self.fp16,
    248             swa_model=self.swa_model if use_swa else None, swa_start=swa_start,
--> 249             swa_eval_freq=swa_eval_freq, **kwargs)
    250 
    251     def get_layer_groups(self): return self.models.get_layer_groups()

/content/drive/AI/cloud/fastai/model.py in fit(model, data, n_epochs, opt, crit, metrics, callbacks, stepper, swa_model, swa_start, swa_eval_freq, visualize, **kwargs)
    123     model_stepper = stepper(model, opt.opt if hasattr(opt,'opt') else opt, crit, **kwargs)
    124     ep_vals = collections.OrderedDict()
--> 125     tot_epochs = int(np.ceil(np.array(n_epochs).sum()))
    126     cnt_phases = np.array([ep * len(dat.trn_dl) for (ep,dat) in zip(n_epochs,data)]).cumsum()
    127     phase = 0

AttributeError: 'int' object has no attribute 'ceil'

This bug occurs when the epoch is large. For example learn(0.1, 1000)

**Comment by sgugger** [comment]
Please use the [forum](http://forums.fast.ai/). You should also share more of your code to give more information to the people that will help you, from what I see here it looks like you created a variable named np (which is supposed to be the module numpy).
