### ISSUE TITLE
where to find sr-samp0? (courses/dl2/enhance.ipynb)

### ISSUE THREAD

**Issue by stas00** [fastai/fastai#763]
courses/dl2/enhance.ipynb fails at:

`  t = torch.load(learn.get_model_path('sr-samp0'), map_location=lambda storage, loc: storage)`
`FileNotFoundError: [Errno 2] No such file or directory: 'data/imagenet/models/sr-samp0.h5'`

where do we get 'sr-samp0'? I can't find any references to it anywhere online.

Perhaps it's some kind of chicken and egg problem? I can see it saved at a later time, but never created or downloaded before it being used:

```
courses/dl2/enhance.ipynb:    "t = torch.load(learn.get_model_path('sr-samp0'), map_location=lambda storage, loc: storage)\n",
courses/dl2/enhance.ipynb:    "learn.save('sr-samp0')"
```

**Comment by stas00** [comment]
I found a workaround of adding:

    learn.save('sr-samp0')

At the end of ## Pixel loss, just before ## Perceptual loss starts. But I have no way of telling whether this is the intended way, or whether something else should be there. The video mentions that one needs to go back and forth in the notebook to make this work, but if you look at the code, that suggestion only works when waving hands ;) and not talking to a computer.

**Comment by sgugger** [comment]
The second part course notebooks aren't working when you just execute the cells in order, which I think is half on purpose. Yet if you feel this one is really mean, feel free to create a PR ;)

**Comment by stas00** [comment]
I am not sure why you'd call it mean, but it surely is not clear from the video what needs to be done. 

I mean, what is the real reason why is it not saved in first place, before it being used, I fail to see how this can be of any help to a student.

There are quite a few other issues with this notebook, I will submit a PR, but I also have one more question - I needed to do this as well:

```
## modified /cells/53/source:
@@ -1,3 +1,3 @@
-conv_shuffle = m.features[10][2][0]
+conv_shuffle = m.features[10][0][0]
 kernel = icnr(conv_shuffle.weight, scale=scale)
 conv_shuffle.weight.data.copy_(kernel);
```
`m.features[10][2][0]` fails saying there is no such thing  - is it related to multiple GPUs?

`m.features[10][0][0]` works. I guess this is related to a change:

+m = nn.DataParallel(m, [0])
+#m = nn.DataParallel(m, [0,2])
