### ISSUE TITLE
Unable to install fastai

### ISSUE THREAD

**Issue by sejalchopra** [fastai/fastai#764]
I am using PyTorch version = 0.4.1 and whenever I try to install fastai I get the error : 
"   Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\seja9890\AppData\Local\Temp\pip-install-awrak67f\torch\setup.py", line 11, in <module>
        raise RuntimeError(README)
    RuntimeError: PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).

    Please follow the instructions at http://pytorch.org/ to install with miniconda instead.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\seja9890\AppData\Local\Temp\pip-install-awrak67f\torch\

"
I have already looked at the forum and did not find something suitable. Kindly let me know what is the way forward.

**Comment by sgugger** [comment]
Please use the [forum](http://forums.fast.ai/) to ask any questions regarding installation. Also fastai doesn't support pytorch 0.4 officially.
