### ISSUE TITLE
GPU memory not freed after training

### ISSUE THREAD

**Issue by javedsha** [fastai/fastai#770]
Hello,

Code: IMDB script, course - dl2

After running the first learner "learner.fit" for the language model, the GPU memory is not freed. I have a M60 GPU, with 8GB memory. There are no problems in training but after training I am expecting all of my GPU memory to get freed. 

After the first training, GPU memory: 6745 / 7618.

Any idea how to clear the memory after training?

Thanks.

**Comment by sgugger** [comment]
Please use the [forum](http://forums.fast.ai/) for these questions.
