### ISSUE TITLE
pytorch version 

### ISSUE THREAD

**Issue by zsk423200** [fastai/fastai#771]
i noticed that pytorch version in your environment.yml is 0.3.1, but i use 0.4.1, so is fastai apply to me, is it work fine if i modify pytorch<0.4 to pytorch > 0.4

**Comment by sgugger** [comment]
As it has already been stated, fastai doesn't officially support pytorch 0.4. It may work but it hasn't been thoroughly tested and there might be some bugs.
fastai_v1 will support the latest version of pytorch.
