### ISSUE TITLE
Progress bar rendering when running a learning from CLI

### ISSUE THREAD

**Issue by devforfu** [fastai/fastai#776]
When you run the training process in the notebook, a nice Jupyter widget with a progress bar is rendered. However, when the training code is invoked from terminal, the output looks like:
```
Epoch:   0%|                                                                          | 0/1 [00:00<?, ?it/sepoch      trn_loss   val_loss   <lambda>                                                                    
    0      1.894452   17.534646  0.3654    
Epoch: 100%|██████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.76s/it]
Epoch:   0%|                                                                          | 0/3 [00:00<?, ?it/sepoch      trn_loss   val_loss   <lambda>                                                                    
    0      0.324009   0.136329   0.9529    
Epoch:  33%|██████████████████████                                            | 1/3 [00:04<00:09,  4.72s/it    1      0.17263    0.079551   0.9744                                                                      
Epoch:  67%|████████████████████████████████████████████                      | 2/3 [00:09<00:04,  4.75s/it    2      0.115407   0.074599   0.9747                                                                      
Epoch: 100%|██████████████████████████████████████████████████████████████████| 3/3 [00:14<00:00,  4.79s/it]
```
In other words, it renders each epoch progress on a separate line. As I can see from the library's code, it automatically uses a correct `tqdm` wrapper depending on the shell where you're executing the code. But somehow I have the output shown above. 

Is it possible to somehow override the progress bar behavior, or is there any other way to alleviate this little issue?

**Comment by sgugger** [comment]
Bug is mostly coming from the tqdm side AFAICT, so we can't do much about it. In fastai_v1, we'll be using our own implementation for progress bars so this won't happen anymore.
