### ISSUE TITLE
Error while setting up 

### ISSUE THREAD

**Issue by satishrdd** [fastai/fastai#778]
I get the following error when setting up the tools on my windows machine.

extensions/gdal_wrap.cpp:2853:22: fatal error: cpl_port.h: No such file or directory
compilation terminated

which is related to installation of fiona.I've tried few things on stackoverflow links but could not solve the problem

**Comment by sgugger** [comment]
Not sure I can help without more information. Also, please use the [forum](http://forums.fast.ai/) for this as you'll get more people to answer you.
