### ISSUE TITLE
change in 'add_datepart()' for the `df[targ_pre+'Elapsed']` formula ?

### ISSUE THREAD

**Issue by EricPerbos** [fastai/fastai#79]
Hi,

I have some trouble reproducing some of Jeremy's notebooks' results from Rossmann (DL1) and Bulldozers (ML1) videos, when using the 'add_datepart()' function in Structured.py.

It keeps generating 10+ digits figures, like "1356998400" while it's more likely in the range of 100s, maybe 1000s days max if counting the number of days elapsed between 2 events ?

Looking at the history of the code, and some screen captures from Jeremy's videos in Oct-Nov 2017, I noticed this change in code.

Before: `df[targ_pre+'Elapsed'] = (fld - fld.min()).dt.days`

Today: `df[targ_pre+'Elapsed'] = fld.astype(np.int64) // 10**9`

**Comment by jph00** [comment]
Yeah I think it's the first/last rows that are causing this. It doesn't seem to impact the results, but a PR to fix would certainly be appreciated! :)
