### ISSUE TITLE
Different keys of pretrained weights and fa_resnet architectures

### ISSUE THREAD

**Issue by shang-vikas** [fastai/fastai#793]
Keys of pretrained weights and fa_resnet models are different. 
pretrained=True fails.
![error](https://user-images.githubusercontent.com/25061285/46004495-b360db80-c0d0-11e8-8be7-ab0d737b09f2.png)

**Comment by shang-vikas** [comment]
created the pull request here #792

**Comment by sgugger** [comment]
Merged so I can close this, thanks for helping!
