### ISSUE TITLE
Better names?

### ISSUE THREAD

**Issue by mraggi** [fastai/fastai#798]
This library would be great if a bit more thought went into naming functions and variables.

First, why are there so many abbreviations? I mean, "train_cats" is probably the funniest named function I've seen, but funny is not good for a library. Why not "train_categories"? Another example: is it really that much faster to type fld than field?

Besides, the names often don't tell you what the functions do at all: train_cats doesn't train any cats, okay, but neither does it train any categories! From the documentation: "Change any columns of strings in a panda's dataframe to a column of categorical values."

So why is it not called "convert_string_columns_to_categories" or something like that?

These are just examples. I've spotted many, many functions and variables that would benefit from a name change.

**Comment by sgugger** [comment]
I would suggest reading the guides on [style](https://github.com/fastai/fastai/blob/master/docs/style.md) and [abbreviation](https://github.com/fastai/fastai/blob/master/docs/abbr.md). This has also been debated a lot on the [forum](http://forums.fast.ai/).
