### ISSUE TITLE
notebooks for ml lessons 6 - 11

### ISSUE THREAD

**Issue by cdfox** [fastai/fastai#801]
I started taking a look at the new ML course, and I see notebook only for lessons 1 - 5 (https://github.com/fastai/fastai/tree/master/courses/ml1). I did also see that there notebooks on the forum for some of the other lessons from Tim Lee. Is the plan to add those notebooks alongside the others in the repo at some point?

**Comment by jph00** [comment]
The notebooks there cover all the lessons - they don't match names.
