### ISSUE TITLE
function T() in core doesn't work if it is given a Variable as an argument

### ISSUE THREAD

**Issue by denised** [fastai/fastai#804]
If you try `fastai.core.T(x)` where x is a `torch.Variable`, you get an error.
It would be nice if it worked in this case, either passing the argument through or getting the tensor out of the variable.

I can see that mainline code has changed massively since the version of fastai that I am using, but fastai.torch_core.tensor appears to have the same behavior.

**Comment by sgugger** [comment]
You are trying to use version 1.0 of fastai, which requires pytorch 1.0. There are no more Variable objects in pytorch 1.0 so that's why it's not supported.
If you want to use the old fastai 0.7, you should follow the instruction [here](https://github.com/fastai/fastai/tree/master/old).
