### ISSUE TITLE
ML Lesson 1: fastai.structured?

### ISSUE THREAD

**Issue by tobiaspahlberg** [fastai/fastai#806]
Hi, 
I tried this import in the first lesson but it didn't work: 
from fastai.structured import *

Found the function add_datepart in the Old-folder, is there something new coming?

/N00b programmer

**Comment by Zohaggie** [comment]
Yes, version 1 is coming. You need to reconfigure your fastai symlink to ../../old/fastai in the meantime. See http://forums.fast.ai/t/moving-the-fastai-0-7-folder/23667
