### ISSUE TITLE
Cannot install fastai from conda

### ISSUE THREAD

**Issue by markb-trustifi** [fastai/fastai#808]
I run this command `conda install -c pytorch -c fastai fastai pytorch-nightly`
and get this error:
```
PackagesNotFoundError: The following packages are not available from current channels:
  - fastai
  - fastprogress
  - fastai
  - pytorch-nightly
  - fastai
  - torchvision==0.2.1=py_0
```

**Comment by stas00** [comment]
Thank you for your report.

What do you get when you run:

    conda search -c pytorch pytorch-nightly

**Comment by markb-trustifi** [comment]
It is better, but there is still missing pytorch-nightly package.

```JS
$ conda install -c pytorch -c fastai fastai pytorch-nightly
Solving environment: failed
PackagesNotFoundError: The following packages are not available from current channels:
  - fastai
  - pytorch-nightly
  - fastai
  - torchvision==0.2.1=py_0
  - pytorch-nightly
```

**Comment by stas00** [comment]
Thank for your feedback, @markb-trustifi. Let's continue debugging this then.

Please go to https://pytorch.org/get-started/locally/ and choose the right setup for your system. Make sure to pick Preview in the first row. What install command do you get and what do you get when you run it (installing `pytorch-nightly` that is).

**Comment by markb-trustifi** [comment]
Preview Build Not Yet Available on Windows.

**Comment by markb-trustifi** [comment]
Just FYI, I succeeded to install fastai on Mac.

**Comment by Karna829** [comment]
How to start with fast ai on windows machine ? I have a good GPU on my windows QuadroM4000 ? I can build from source but I don't know where to get the source and what sources to use ?

**Comment by stas00** [comment]
Currently, there is no dedicated thread for v1/windows, since it's not quite supported (until pytorch releases windows packages), but some people did report success, search for "windows" in this thread: https://forums.fast.ai/t/fastai-v1-install-issues-thread/24111

**Comment by Karna829** [comment]
Hey thanks man. That was really quick response. Fastest I have ever got. Thank you .

**Comment by mariaaslam706** [comment]
> Thank for your feedback, @markb-trustifi. Let's continue debugging this then.
> 
> Please go to https://pytorch.org/get-started/locally/ and choose the right setup for your system. Make sure to pick Preview in the first row. What install command do you get and what do you get when you run it (installing `pytorch-nightly` that is). Please paste both of them. Thank you.
> 
> Actually, let's first debug each component separately. conda client is not very user-friendly to tell the user which dependency is missing. And it complains about them all together, which is wrong most of the time.
> 
> $ conda install -c pytorch pytorch-nightly
> $ conda install -c pytorch -c fastai torchvision==0.2.1=py_0
> $ conda install -c pytorch -c fastai fastai

this worked for me:  'conda install pytorch torchvision cudatoolkit=10.2 -c pytorch-nightly'
