### ISSUE TITLE
plot_pdp no longer works

### ISSUE THREAD

**Issue by rexmadden** [fastai/fastai#809]
In lesson2-rf_interpretation.ipynb, pdp.pdp_isolate now takes 4 parameters. The signature was changed as part of this commit:

https://github.com/SauceCat/PDPbox/commit/2cf4e679e2971e8bf1d2d2934c52cdb540e7ed02

**Comment by sgugger** [comment]
Could you propose a PR to change the notebook so that it works? Thanks in advance.
