### ISSUE TITLE
Error installing fastai from anaconda channel fastai

### ISSUE THREAD

**Issue by Ace139** [fastai/fastai#811]
(fastai) λ conda install -c fastai fastai
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - fastai
  - pytorch-nightly
  - fastai
  - torchvision==0.2.1=py_0

Current channels:

  - https://conda.anaconda.org/fastai/win-64
  - https://conda.anaconda.org/fastai/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**The pip version is working fine.**

**Comment by stas00** [comment]
Thank you for this report, @Ace139 

I'm glad to hear pip build works.

Any reason why you weren't following the conda installation [instructions](https://github.com/fastai/fastai/blob/master/README.md#conda-install). And if you did can you paste all of the steps, including successful ones.

Thanks.

**Comment by abedkhooli** [comment]
Here's what I got for conda install (no GPU). I can see the packages listed at https://anaconda.org/fastai and https://anaconda.org/pytorch - may be a config file is causing this (fastai listed twice below). This is for Win 10 (1803) 17134.285 OS build.
--------------------------------------------------------------
E:\software\anaconda351\Scripts>conda install -c pytorch -c fastai fastai pytorch-nightly==1.0.0.dev20180928=py3.6_cpu_0
Solving environment: failed
PackagesNotFoundError: The following packages are not available from current channels:
  - fastai
  - pytorch-nightly
  - fastai
  - torchvision==0.2.1=py_0
  - pytorch-nightly==1.0.0.dev20180928=py3.6_cpu_0
Current channels:
  - https://conda.anaconda.org/pytorch/win-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://conda.anaconda.org/fastai/win-64
  - https://conda.anaconda.org/fastai/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/anaconda-fusion/win-64
  - https://conda.anaconda.org/anaconda-fusion/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
To search for alternate channels that may provide the conda package you're
looking for, navigate to
    https://anaconda.org
and use the search bar at the top of the page.
