### ISSUE TITLE
fastai.structured not found in pytorch (pip installation)

### ISSUE THREAD

**Issue by Ace139** [fastai/fastai#812]
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-713ddf51e021> in <module>()
      1 from fastai.imports import *
----> 2 from fastai.structured import *
      3 
      4 from pandas_summary import DataFrameSummary
      5 from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier

ModuleNotFoundError: No module named 'fastai.structured'
```

**Comment by Ace139** [comment]
Did **structured** got moved to **tabular** ? Can someone confirm? The source methods looks similar.

**Comment by sgugger** [comment]
Same as before, you are trying to execute code of the fastai 0.7 with fastai 1.0.

**Comment by LeynerBejaranoOfficial** [comment]
Hi, I had the same problem, what is the solution?

**Comment by shubham7298** [comment]
It worked for me on changing 
`from fastai.structured import *`
to
`from fastai.tabular import *`
thanks @Ace139

**Comment by Santiago8888** [comment]
@sgugger what does "before" means. Please provide a link or reference an earlier issue.

Thanks in advance.
This is relevant for all of us who are trying to follow the Machine Learning Course:
https://github.com/fastai/fastai/blob/master/courses/ml1/lesson1-rf.ipynb

**Comment by serkan19** [comment]
Unfortunately , from fastai.tabular import * is not working .Is there alternative thing ?

**Comment by tcapelle** [comment]
`from fastai.tabular.all import *`
