### ISSUE TITLE
[Minor Issue] pandas_summary package missing (pip installation)

### ISSUE THREAD

**Issue by Ace139** [fastai/fastai#813]
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-9ba440ec021d> in <module>()
      2 from fastai.tabular import *
      3 
----> 4 from pandas_summary import DataFrameSummary
      5 from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
      6 from IPython.display import display

ModuleNotFoundError: No module named 'pandas_summary'
```

**Comment by sgugger** [comment]
You are trying to load a fastai v0.7 file with a pip installation that has probably installed v1.0. If you are looking to use the old version of the library, be sure to follow the instructions [here](https://github.com/fastai/fastai/tree/master/old) for installation.

**Comment by blossom2016** [comment]
pip install pandas-summary
Just enter that it should work

**Comment by Santiago8888** [comment]
# conda install -c conda-forge pandas-summary
for the anaconda users

**Comment by kizombaciao** [comment]
What
