### ISSUE TITLE
Need to import numpy and pandas seperately after importing from fastai.imports import *

### ISSUE THREAD

**Issue by Ace139** [fastai/fastai#814]
I can see numpy (np) and pandas (pd) is there in the **fastai.imports** github source code. But it's not getting imported as np and pd.

**Comment by sgugger** [comment]
The library imports separately imports.core and imports.torch in core and torch_core, that's why. Though with [this commit](https://github.com/fastai/fastai/commit/fce6f2c399e4bb6eb4447ec7beae0d4f2f9d2c1d), you should be able to do from fastai.import import * if you want.
