### ISSUE TITLE
ImportError: cannot import name 'set_trace'

### ISSUE THREAD

**Issue by karamesh** [fastai/fastai#821]
from IPython.core.debugger import set_trace
ImportError: cannot import name 'set_trace'

**Comment by sgugger** [comment]
Hi there, we need a tiny little bit more detail to figure out what your problem is (which version of the fastai library are you running? What code? Your editor?) and you should use the [forum](http://forums.fast.ai/) as you'll get more people responding to you there.

**Comment by cescnghia** [comment]
I had the same problem when trying to import fastai. Actually you have to update your ipython:

- conda update ipython
