### ISSUE TITLE
Tabular dataset doesn't create a test_df dataset

### ISSUE THREAD

**Issue by Aphaniteja** [fastai/fastai#830]
The below function doesn't create a test_df dataset even when a test_df pandas dataframe is passed.

https://github.com/fastai/fastai/blob/8d9047d3001753445c28488a4ba6959ba3651b92/fastai/tabular/data.py#L70

The problem is in this line
`if test_df:
        datasets.append(TabularDataset.from_dataframe(valid_df, dep_var, train_ds.tfms, 
                                    train_ds.cat_names,train_ds.cont_names, train_ds.stats, log_output))`

When given a test_df , the function creates a Tabular Dataset with valid_df as the input pandas dataframe.

**Comment by sgugger** [comment]
Fixed, thanks for pointing it out!
