### ISSUE TITLE
ResolvePackageNotFound: cuda90

### ISSUE THREAD

**Issue by delgermurun** [fastai/fastai#84]
I ran `conda env update` command right after I cloned repo.

But it raises following error:
```
Using Anaconda API: https://api.anaconda.org
Solving environment: failed

ResolvePackageNotFound:
  - cuda90
```

Conda version: `conda 4.4.6`
OS: macOS 10.13

Thank you.

**Comment by delgermurun** [comment]
I commented out `cuda90` (`#cuda90`) in `environment.yml` file and `conda env update` works successfully.

**Comment by jph00** [comment]
Mac isn't a supported platform for fastai FYI.

**Comment by delgermurun** [comment]
@jph00 Any plan to support it :) ?

**Comment by rudedogg** [comment]
@delgermurun Were you able to run the lessons (with CUDA support) without that package? I'm can't get CUDA support working and think this is the issue

**Comment by mbfisher** [comment]
If anybody else comes across this, using the `environment-cpu.yaml` works on a Mac. There's instructions for this in the README.

**Comment by joseandrespena** [comment]
Here is a https://developer.nvidia.com/cuda-90-download-archive there is a downloadable for Mac...

**Comment by vikumar1** [comment]
Can we use CUDA9.2  and associates with fastai enviorment.
Also let me know difference between CUDA9.0 and CUDA90
