### ISSUE TITLE
Can't install fastai using conda environment

### ISSUE THREAD

**Issue by faizan2786** [fastai/fastai#840]
Installation command:  `conda install -c pytorch -c fastai fastai pytorch-nightly cuda90`

PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch-nightly
  - fastai
  - pytorch-nightly
  - fastai
  - torchvision==0.2.1=py_0

**Comment by jph00** [comment]
http://forums.fast.ai/t/fastai-v1-install-issues-thread/24111

**Comment by stas00** [comment]
@faizan2786, I addressed this issue here http://forums.fast.ai/t/fastai-v1-install-issues-thread/24111
Please follow up in the thread. Thank you.

**Comment by stas00** [comment]
Apparently it may take a few months. Or you can build it from source.

**Comment by faizan2786** [comment]
Aah. I will try to build from source then. I believe I will need to build both pytorch preview version and fast AI build from source right?

**Comment by stas00** [comment]
fastai is pure python. Once you have pytorch installed, you can install fastai it in many ways:  https://github.com/fastai/fastai/blob/master/README.md

**Comment by stas00** [comment]
I have just updated https://github.com/fastai/fastai/blob/master/README.md to separate pytorch installation from fastai - so it'll be much easier to debug the issue.
