### ISSUE TITLE
ModuleNotFoundError: No module named 'fastai.torch_imports'

### ISSUE THREAD

**Issue by mutcato** [fastai/fastai#841]
Although i have correctly `!pip install fastai` with no error on Google Colab, i am getting ModuleNotFound error for two days.

I get same error for each fastai subclasses except `fastai.imports`

![image](https://user-images.githubusercontent.com/8294447/46499902-14ec1d00-c82a-11e8-928a-e213b586de7b.png)

**Comment by sgugger** [comment]
As explained in the [forum](http://forums.fast.ai/t/moving-the-fastai-0-7-folder-do-not-use-pip-for-the-course/23667/9) if you want to have access to the old library to do the old courses, you shouldn't pip install.

**Comment by aebk2015** [comment]
I am getting the same error as mutcato, i have tried pip, conda, git but none of them worked.  is there a simple step by step installation for installing fastai on CPU?

**Comment by stas00** [comment]
Please see and comment:
* fastai 0.7.x installation issues  [here](http://forums.fast.ai/t/fastai-v0-install-issues-thread/24652) .
* fastai v1 installation issues   [here](http://forums.fast.ai/t/fastai-v1-install-issues-thread/24111).

**Comment by Stevengu999** [comment]
good！
