### ISSUE TITLE
Typo in Tokenizer class

### ISSUE THREAD

**Issue by devforfu** [fastai/fastai#844]
It seems there is a typo in [this line](https://github.com/fastai/fastai/blob/3dfc898c359f01b19c9545f68954a131ced88548/fastai/text/transform.py#L104
) of `Tokenizer` class. Shouldn't it be `_process_all_1`? I.e., to start with underscore, as a few lines below? Otherwise, it will probably raise an error when `n_cpus <= 1`

**Comment by sgugger** [comment]
It's been fixed in [this commit](https://github.com/fastai/fastai/commit/8960bed1e5e3c49e76ae274d628734f8c6e370d9#diff-514fa59d16193e2788df19cb082759bf) already.
