### ISSUE TITLE
Prepare data for the LanguageModelLoader (ULMFit)

### ISSUE THREAD

**Issue by king-menin** [fastai/fastai#849]
While running imdb notebook i had an error:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-22-f1ce9602b6a0> in <module>
----> 1 trn_dl = LanguageModelLoader(np.concatenate(trn_lm), bs, bptt)

~/.local/lib/python3.6/site-packages/fastai/text/data.py in __init__(self, dataset, bs, bptt, backwards)
    191     def __init__(self, dataset:TextDataset, bs:int=64, bptt:int=70, backwards:bool=False):
    192         self.dataset,self.bs,self.bptt,self.backwards = dataset,bs,bptt,backwards
--> 193         self.data = self.batchify(np.concatenate(dataset.ids))
    194         self.first,self.i,self.iter = True,0,0
    195         self.n = len(self.data)

AttributeError: 'numpy.ndarray' object has no attribute 'ids'
```

**By run the following code:**

```
trn_lm = np.load('ulmfit/data/trn_ids.npy')
trn_dl = LanguageModelLoader(np.concatenate(trn_lm), bs, bptt)
```

How should i prepare data for the `LanguageModelLoader`?

**Comment by devforfu** [comment]
I think you need to wrap your data into `TextDataset` class, as constructor's type annotation suggests.

**Comment by sgugger** [comment]
The scripts are for the old version of the library (0.7) so you should use that version. Installation instructions are [here](https://github.com/fastai/fastai/tree/master/old).

**Comment by ShreyaGupta08** [comment]
@sgugger I have a script that uses 'LanguageModelData' function. I can't find the installation instructions for version 0.7 of fastai, as suggested by you here:

> The scripts are for the old version of the library (0.7) so you should use that version. Installation instructions are [here](https://github.com/fastai/fastai/tree/master/old).

Would you know the equivalent function of LanguageModelData in v1.0.x and onwards of fastai or a way to install v0.7 to run a code with this function?
