### ISSUE TITLE
Issue with installing CPU version of 1.0 (pytorch-nightly-cpu is not recognized by fastai script)

### ISSUE THREAD

**Issue by AirVetra** [fastai/fastai#856]
While installing it for CPU only i need to put the version of torch I'd like to use. 

But only CPU torch is a different package now and if i mention this pytorch-nightly-cpu version it's not recognized by scrip and it failes to install.

So, the only way for me to find an old version of pytorch-nightly w/o -cpu at the end with no cuda mentioned 

PS. Now you changed in manual to firstly install pytorch-nightly-cpu and afterwards - fastai - but conda tels that all the packages is missing:

(base) airvetra@AirVetra-X1:~$ conda install fastai -c fastai
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - fastai
  - pytorch-nightly
  - fastai
  - torchvision-nightly
  - fastai
  - torchvision==0.2.1=py_0

Current channels:

  - https://conda.anaconda.org/fastai/linux-64
  - https://conda.anaconda.org/fastai/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by AirVetra** [comment]
BTW, CPU version of fastai/pytorch 1.0 is possible to install on Windows easily:

1) Install WSL with Ubuntu 18.04
2) Install Anaconda for Linux 
3) And then in bash made all the needed steps - install pytorch, fastai
4) start jupyter notebook
5) Use it anythere with any browser, even from outside with DDNS!

Unfortunately, GPU is not working this way as Cuda from WSL is not possible to access Nvidia driver in Windows (should be done soon)

**Comment by stas00** [comment]
I have just made a new release to reflect the introduction of pytorch-nightly-cpu, please see [this](
https://github.com/fastai/fastai/blob/master/README.md#conda-install). It should solve this issue.
