### ISSUE TITLE
Potential bug with anchor_cnr in dl2/pascal-multi notebook

### ISSUE THREAD

**Issue by aaronlelevier** [fastai/fastai#875]
**Describe the bug**

Is the first definition for this code correct in [pascal-multi.ipynb](https://github.com/fastai/fastai/blob/master/courses/dl2/pascal-multi.ipynb) ?

```python
anchor_cnr = hw2corners(anchors[:,:2], anchors[:,2:])
```

For example, the 8th item in `anchor_cnr` is `0.2500  0.7500  0.5000  1.0000`. I'm interpreting each item as `[y1, x1, y2, x2]`. But, if these are corners, and it's a 4x4 grid `[0,1]` normalized, then they should be `0.25` apart. But, here the coordinates are `0.5` apart. 

I was working through the Lesson # 9 on Object Detection SSD, and testing my IoU, and plotting when I noticed this.

**To Reproduce**
This is present in the *master* branch.

**Expected behavior**
Expecting all `x,y` pairs to be `0.25` distance apart.

**On another note**

@sgugger, if you're reading this, I met you at PTDC last week. You said to tell you all what I think of `fastai`. Well, I'm super enjoying it. I'm really impressed with the libraries use of type annotations, and I've just been learning more Python, let alone PyTorch, reading over the source code. Keep it up guys and gals!

**Comment by sgugger** [comment]
Not sure what the bug is supposed to be. In your example, you show the coordinates are 0.25 apart (since its `y1` then `x1` then `y2` then `x2`). Could you precise a little bit more?
And glad I met you too :)

**Comment by aaronlelevier** [comment]
@sgugger you're correct. I was thinking that `x1,y1` and `x2,y2` should be `0.25` apart but it's actually `x1,x2` and `y1,y2` that should be and are `0.25` apart, which they are indeed. I plotted the points out now in a scatter plot. I'll close the issue. Sorry about that.
