### ISSUE TITLE
can't optimize a non-leaf Tensor when calling lr_find second time

### ISSUE THREAD

**Issue by fredguth** [fastai/fastai#878]
**Describe the bug**
When I run `learner.lr_find` a second time, it throws error `ValueError: can't optimize a non-leaf Tensor`

**To Reproduce**

Added test here:https://github.com/fastai/fastai/pull/877

Basically, I had a language model learner and tried to run lr_find twice in sequence.

**Expected behavior**

lr_find should not throw error.
**Screenshots**

![screenshot from 2018-10-10 12-31-26](https://user-images.githubusercontent.com/392879/46747771-83950480-cc88-11e8-9356-e7f6b64a0971.png)

**Additional context**

**Comment by fredguth** [comment]
I also noticed that lr_find does not save/load learner anymore, learner is not changed during the lr_find?

**Comment by fredguth** [comment]
The same error is happening when I run `lr_find` then `fit_one_cycle`.  My guess is that lr_find is changing the learner.

**Comment by sgugger** [comment]
This has been raised yesterday [here](http://forums.fast.ai/t/cant-optimize-non-leaf-tensor-error-with-learn-fit-one-cycle-after-running-plotting-lr-find-a-second-time/24875) and should have been fixed (don't forget to seach the forum when you have an error as the message is the same ;) ).
With the latest version of fastai (ideally a developer install) you shouldn't have this anymore.
