### ISSUE TITLE
conda env update fails on Windows 10 x64 

### ISSUE THREAD

**Issue by SurealCereal** [fastai/fastai#88]
I am running Anaconda with conda 4.4.7-py36_0 on Windows 10 x64.
When I run `conda env update` the following is the output:
```
Using Anaconda API: https://api.anaconda.org
Solving environment: failed

ResolvePackageNotFound:
  - libgcc
  - cuda90
  - glib
  - torchvision[version='>=0.1.9']
  - pytorch[version='>=0.2.0']
  - fontconfig
  - jbig
  - libgfortran
  - readline
  - terminado
  - libffi
  - ptyprocess
```
The libgcc packages for Win64 are woefully out of date: https://anaconda.org/search?q=platform%3Awin-64+libgcc
Its not a problem for me to spin up some Linux VM, but then I would lose CUDA acceleration, or at least some stability/performance  Is it possible to make all this run on Windows 10 x64?

**Comment by jph00** [comment]
Yes it runs but isn't officially supported yet. Will be after pytorch 0.4. There are workarounds on the forums if you want help.
