### ISSUE TITLE
Missing/Incorrect dropout layers from get_tabular_learner?

### ISSUE THREAD

**Issue by jmhsi** [fastai/fastai#880]
For the tabular model created from get_tabular_learner, it looks like dropout layers are not being created properly? I have emb_drop = .25 but looking at learn.model it still shows 0. Also, I have ps=[.3,.25] but there are no dropout layers at all in (layers): Sequential? I believe bn_drop_lin from fastai.layers is supposed to be making the Dropout layers?
![screen shot 2018-10-11 at 12 13 41 am](https://user-images.githubusercontent.com/12853718/46786785-c5ef2d80-ccea-11e8-88aa-1143b24e1381.png)

**Comment by sgugger** [comment]
Thanks for flagging this!
