### ISSUE TITLE
tabular learner does not support float (or str?) dtype for dependent variable

### ISSUE THREAD

**Issue by jhmenke** [fastai/fastai#881]
**Describe the bug**
I am using the function *tabular_data_from_df* to get a DataBunch from a pandas DataFrame. The column dtypes are either string or np.float. The dependent variable is of type np.float.

I then use *get_tabular_learner* to create a learner as per the example in the doc.  The following stacktrace is given using a dependent variable of type np.float with values in (-1., 0. or 1.) and torch.nn.functional.mse_loss *or* fastai.metrics.accuracy as the metrics value:

> Traceback (most recent call last):
>   File "/home/jan/PythonProjects/betting/analysis/fastai_analysis.py", line 20, in <module>
>     learn.fit_one_cycle(1, 1e-2)
>   File "/home/jan/PythonProjects/fastai/fastai/train.py", line 18, in fit_one_cycle
>     learn.fit(cyc_len, max_lr, wd=wd, callbacks=cbs)
>   File "/home/jan/PythonProjects/fastai/fastai/basic_train.py", line 135, in fit
>     callbacks=self.callbacks+callbacks)
>   File "/home/jan/PythonProjects/fastai/fastai/basic_train.py", line 88, in fit
>     raise e
>   File "/home/jan/PythonProjects/fastai/fastai/basic_train.py", line 78, in fit
>     loss = loss_batch(model, xb, yb, loss_fn, opt, cb_handler)
>   File "/home/jan/PythonProjects/fastai/fastai/basic_train.py", line 21, in loss_batch
>     loss = loss_fn(out, *yb)
>   File "/home/jan/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1646, in cross_entropy
>     return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
>   File "/home/jan/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1070, in log_softmax
>     return input.log_softmax(dim)
> RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

If i convert the dependent column to int, this happens:

> /home/jan/PythonProjects/fastai/fastai/tabular/data.py:35: RuntimeWarning: divide by zero encountered in true_divide
>   self.conts = (self.conts - means[None]) / stds[None]
> /home/jan/PythonProjects/fastai/fastai/tabular/data.py:35: RuntimeWarning: invalid value encountered in true_divide
>   self.conts = (self.conts - means[None]) / stds[None]
> epoch  train loss  valid loss  accuracy
> Traceback (most recent call last):
>   File "/home/jan/PythonProjects/betting/analysis/fastai_analysis.py", line 20, in <module>
>     learn.fit_one_cycle(1, 1e-2)
>   File "/home/jan/PythonProjects/fastai/fastai/train.py", line 18, in fit_one_cycle
>     learn.fit(cyc_len, max_lr, wd=wd, callbacks=cbs)
>   File "/home/jan/PythonProjects/fastai/fastai/basic_train.py", line 135, in fit
>     callbacks=self.callbacks+callbacks)
>   File "/home/jan/PythonProjects/fastai/fastai/basic_train.py", line 88, in fit
>     raise e
>   File "/home/jan/PythonProjects/fastai/fastai/basic_train.py", line 78, in fit
>     loss = loss_batch(model, xb, yb, loss_fn, opt, cb_handler)
>   File "/home/jan/PythonProjects/fastai/fastai/basic_train.py", line 21, in loss_batch
>     loss = loss_fn(out, *yb)
>   File "/home/jan/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1646, in cross_entropy
>     return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
>   File "/home/jan/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1503, in nll_loss
>     return torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
> RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed.  at /opt/conda/conda-bld/pytorch-nightly-cpu_1539155206632/work/aten/src/THNN/generic/ClassNLLCriterion.c:93

Also, as a third test, with the dependent variable converted to a string of values in ("-1", "0", "1") and fastai.metrics.accuracy as the metrics value:

> Traceback (most recent call last):
>   File "/home/jan/PythonProjects/betting/analysis/fastai_analysis.py", line 18, in <module>
>     data = prepare_df()
>   File "/home/jan/PythonProjects/betting/analysis/fastai_analysis.py", line 14, in prepare_df
>     return tabular_data_from_df(path, train_df, validate_df, cat_names=cat_inputs, dep_var="target", tfms=tfms)
>   File "/home/jan/PythonProjects/fastai/fastai/tabular/data.py", line 75, in tabular_data_from_df
>     train_ds = TabularDataset.from_dataframe(train_df, dep_var, tfms, cat_names, cont_names, stats, log_output)
>   File "/home/jan/PythonProjects/fastai/fastai/tabular/data.py", line 65, in from_dataframe
>     ds = cls(df, dep_var, cat_names, cont_names, stats, log_output)
>   File "/home/jan/PythonProjects/fastai/fastai/tabular/data.py", line 24, in __init__
>     if not is_numeric_dtype(df[dep_var]): df[dep_var] = df[dep_var].cat.astype(np.int64)
> AttributeError: 'CategoricalAccessor' object has no attribute 'astype'

**To Reproduce**

it is easily reproducable by using the tabular.ipynb example and changing the dtype of the dependent variable:

```
from numpy import float as npfloat
train_df[">=50k"] = train_df[">=50k"].astype(npfloat)
```

also this does not work:

```
train_df.loc[10, ">=50k"] = -1
```

after some iterations it will crash

**Expected behavior**
I expect the learner to learn successfully without errors.

**Additional context**
I have installed the **latest Git develop build of** fast.ai on Linux Ubuntu 64 bit with conda as per the README.md. I am using the **CPU** version.

**Comment by jhmenke** [comment]
in the latest developer build, the error is a bit different. again using a dependent variable of type np.float with values -1, 0 or 1 and torch.nn.functional.mse_loss as the metrics value:

> Traceback (most recent call last):
>   File "/home/jan/PythonProjects/betting/analysis/fastai_analysis.py", line 20, in <module>
>     learn.fit_one_cycle(1, 1e-2)
>   File "/home/jan/PythonProjects/fastai/fastai/train.py", line 18, in fit_one_cycle
>     learn.fit(cyc_len, max_lr, wd=wd, callbacks=cbs)
>   File "/home/jan/PythonProjects/fastai/fastai/basic_train.py", line 135, in fit
>     callbacks=self.callbacks+callbacks)
>   File "/home/jan/PythonProjects/fastai/fastai/basic_train.py", line 88, in fit
>     raise e
>   File "/home/jan/PythonProjects/fastai/fastai/basic_train.py", line 78, in fit
>     loss = loss_batch(model, xb, yb, loss_fn, opt, cb_handler)
>   File "/home/jan/PythonProjects/fastai/fastai/basic_train.py", line 21, in loss_batch
>     loss = loss_fn(out, *yb)
>   File "/home/jan/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1646, in cross_entropy
>     return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
>   File "/home/jan/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1070, in log_softmax
>     return input.log_softmax(dim)
> RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

And with the dependent variable converted to a string ("-1", "0", "1") and accuracy as the metrics value:

> Traceback (most recent call last):
>   File "/home/jan/PythonProjects/betting/analysis/fastai_analysis.py", line 18, in <module>
>     data = prepare_df()
>   File "/home/jan/PythonProjects/betting/analysis/fastai_analysis.py", line 14, in prepare_df
>     return tabular_data_from_df(path, train_df, validate_df, cat_names=cat_inputs, dep_var="target", tfms=tfms)
>   File "/home/jan/PythonProjects/fastai/fastai/tabular/data.py", line 75, in tabular_data_from_df
>     train_ds = TabularDataset.from_dataframe(train_df, dep_var, tfms, cat_names, cont_names, stats, log_output)
>   File "/home/jan/PythonProjects/fastai/fastai/tabular/data.py", line 65, in from_dataframe
>     ds = cls(df, dep_var, cat_names, cont_names, stats, log_output)
>   File "/home/jan/PythonProjects/fastai/fastai/tabular/data.py", line 24, in __init__
>     if not is_numeric_dtype(df[dep_var]): df[dep_var] = df[dep_var].cat.astype(np.int64)
> AttributeError: 'CategoricalAccessor' object has no attribute 'astype'

**Comment by jhmenke** [comment]
From #852 i gathered that maybe `train_df.loc[10, ">=50k"] = -1` does not work because the loss function is incorrect for 3 classes?

if i change the loss to `F.binary_cross_entropy_with_logits`  it gives another error:

> Traceback (most recent call last):
>   File "/home/jan/PythonProjects/betting/analysis/fastai_analysis.py", line 21, in <module>
>     learn.fit_one_cycle(1, 1e-2)
>   File "/home/jan/PythonProjects/fastai/fastai/train.py", line 18, in fit_one_cycle
>     learn.fit(cyc_len, max_lr, wd=wd, callbacks=cbs)
>   File "/home/jan/PythonProjects/fastai/fastai/basic_train.py", line 135, in fit
>     callbacks=self.callbacks+callbacks)
>   File "/home/jan/PythonProjects/fastai/fastai/basic_train.py", line 88, in fit
>     raise e
>   File "/home/jan/PythonProjects/fastai/fastai/basic_train.py", line 79, in fit
>     if cb_handler.on_batch_end(loss): break
>   File "/home/jan/PythonProjects/fastai/fastai/callback.py", line 231, in on_batch_end
>     stop = np.any(self('batch_end'))
>   File "/home/jan/PythonProjects/fastai/fastai/callback.py", line 182, in __call__
>     return [getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs) for cb in self.callbacks]
>   File "/home/jan/PythonProjects/fastai/fastai/callback.py", line 182, in <listcomp>
>     return [getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs) for cb in self.callbacks]
>   File "/home/jan/PythonProjects/fastai/fastai/callbacks/one_cycle.py", line 43, in on_batch_end
>     self.opt.lr = self.lr_scheds[self.idx_s].step()
>   File "/home/jan/PythonProjects/fastai/fastai/callback.py", line 281, in step
>     return self.func(self.start, self.end, self.n/self.n_iter)
> ZeroDivisionError: division by zero

i'm sorry for the inconvenience as i cannot really understand at this point if it's a bug in the library or a user (my) error.

**Comment by sgugger** [comment]
If you want to do a classification with three values, you should convert them as categories, otherwise it won't work yes (unless your three values are the integers 0, 1 and 2).
If you want to do a regression, you should specify y_range = (min,max) so that the data object knows it.

**Comment by diablo34** [comment]
> If you want to do a classification with three values, you should convert them as categories, otherwise it won't work yes (unless your three values are the integers 0, 1 and 2).
> If you want to do a regression, you should specify y_range = (min,max) so that the data object knows it.

i set the learner = tabular_learner(y_ranger = [0.500]) 
but still get error...

**Comment by jhmenke** [comment]
> > If you want to do a classification with three values, you should convert them as categories, otherwise it won't work yes (unless your three values are the integers 0, 1 and 2).
> > If you want to do a regression, you should specify y_range = (min,max) so that the data object knows it.
> 
> i set the learner = tabular_learner(y_ranger = [0.500])
> but still get error...

y_range cannot contain a single value, it should include both min. and max. values
