### ISSUE TITLE
tabular_data_from_df processing non-specified columns

### ISSUE THREAD

**Issue by ecatkins** [fastai/fastai#887]
**Describe the bug**
When specifying both `cont_names` and `cat_names` the `tabular_data_from_df` function errors trying to process other columns.
E.g. running the following code...

```
cat_names = ['matches', 'state']
cont_names = ['bedrooms', 'bathrooms', 'sold', 'square_feet', 'price']
data = tabular_data_from_df('data/path', train_df, valid_df, dep_var, 
                            tfms=[FillMissing, Categorify], cat_names=cat_names, cont_name=cont_names)]
```

I receive the error below, the the value of which I can trace to a column ('date') that isn't in the specified columns.

`TypeError: could not convert string to float: '9/20/18' `

**Expected behavior**
I'm not sure what the desired behavior is here, but I expected it to ignore unspecified columns. As it stands, I had to first remove the other columns from `train_df`, `valid_df`.

**Comment by sgugger** [comment]
Sorry I only catch up now on this. I just ran a similar example without problems, so I'm guessing this has been fixed in a later version. Let me know if you still have the problem, but the expected behavior is as you thought: when passing cat_names and cont_names, other columns should be ignored.
