### ISSUE TITLE
Attempt to create learner with VGG19 or squeezenet models fails with a Type Error 

### ISSUE THREAD

**Issue by melikovk** [fastai/fastai#888]
Attempt to create learner with VGG19 or squeezenet models fails with a Type Error 

TypeError                                 Traceback (most recent call last)
----> 3 learn = ConvLearner(databanch, tvm.vgg19, metrics=accuracy)

~/fastai/vision/learner.py in __init__(self, data, arch, cut, pretrained, lin_ftrs, ps, custom_head, split_on, **kwargs)
     52         torch.backends.cudnn.benchmark = True
     53         body = create_body(arch(pretrained), ifnone(cut,meta['cut']))
---> 54         nf = num_features(body) * 2
     55         head = custom_head or create_head(nf, data.c, lin_ftrs, ps)
     56         model = nn.Sequential(body, head)

TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

It looks like these networks do not have num_features attribute in their penultimate layer. I have added elif statement to num_features() function like so:

`def num_features(m:Model)->int:
 "Return the number of output features for a `model`."
     for l in reversed(flatten_model(m)):
         if hasattr(l, 'num_features'): return l.num_features
         elif hasattr(l, 'out_channels'): return l.out_channels `
This removes the error for both models and VGG19 model fits. Squeezenet model has some additional problems during training.

**Comment by sgugger** [comment]
Yes, we don't support those models in ConvLearner yet. We'll work on this soon.

**Comment by melikovk** [comment]
OK. Thank you.

**Comment by init27** [comment]
Thanks @sgugger, @melikovk  
Meanwhile could you please help with suggestions on how to make squeezenet work? 
I'm trying to build a model for mobile platforms.

**Comment by jph00** [comment]
These models are now not exported, to make it clear that they're not supported. For help adding new models, please discuss on fastai-dev on the forum.
