### ISSUE TITLE
Lesson 3 ML - Grocery notebook

### ISSUE THREAD

**Issue by d-henderson** [fastai/fastai#890]
In the Machine Learning course on Lesson 3, can you please provide a copy of the Grocery Jupyter notebook to the repo. This notebook was created for the Kaggle Favorita grocery sales forecasting competition as shown here:

https://youtu.be/YSFG_W8JxBo?t=3049

As I understand, the competition has closed so there is no issue with sharing code/notebook with other people.

Thanks.

**Comment by stas00** [comment]
There are several notebooks posted here, @d-henderson:
http://forums.fast.ai/t/corporacion-favorita-grocery-sales-forecasting/8359/82
Please continue a discussion over at that forum. Thank you.
