### ISSUE TITLE
Headline example from vision.ipynb doesn't match and/or work

### ISSUE THREAD

**Issue by nlothian** [fastai/fastai#896]
The very first example in the fastai docs is this:

```
untar_data(MNIST_PATH)
data = image_data_from_folder(MNIST_PATH)
learn = ConvLearner(data, tvm.resnet18, metrics=accuracy)
learn.fit(1)
```

It says this comes from the [vision example](https://github.com/fastai/fastai/blob/master/examples/vision.ipynb), but the code there is this (edited to remove output lines):

```
untar_data(Paths.MNIST)
data = image_data_from_folder(Paths.MNIST, ds_tfms=(rand_pad(2, 28), []))
data.normalize(imagenet_stats)
learn = ConvLearner(data, tvm.resnet18, metrics=accuracy)
learn.fit_one_cycle(1, 0.01)
```

However this doesn't work. The imports are incorrect (need `from fastai.docs import *`), `Paths.MNIST` doesn't exist and the normalization process seems incorrect.

This isn't a great "first run" experience.

I think the notebook code should be something like this:

```
import fastai
from fastai import *          # Quick access to most common functionality
from fastai.vision import *   # Quick access to computer vision functionality
from fastai.docs import * # access to datasets

# new cell

untar_data(MNIST_PATH)
MNIST_PATH

# new cell

data = image_data_from_folder(MNIST_PATH, ds_tfms=(rand_pad(2, 28), []),  tfms=imagenet_norm)
# not sure about this, since it doesn't do the same as the original notebook. It does work though
show_image_batch(data.train_dl, data.train_ds.classes, 3, figsize=(6,6), denorm=imagenet_denorm)

# new cell

learn = ConvLearner(data, tvm.resnet18, metrics=accuracy)
learn.fit_one_cycle(1, 0.01)

# new cell

accuracy(*learn.get_preds())
```

**Comment by sgugger** [comment]
The vision example is the one working. Note that there was a change in the fastai library removing the docs module, so you should update to the last version (or do a developer install from master) to run it.
Thanks for flagging the index of the docs is now outdated, will change this one ASAP.
