### ISSUE TITLE
Text example fails... Produces RuntimeError: Could not infer dtype of numpy.int64

### ISSUE THREAD

**Issue by dwbressler** [fastai/fastai#907]
**Describe the bug**
The text example (https://github.com/fastai/fastai/blob/master/examples/text.ipynb) fails at the last step.

**To Reproduce**

learn = RNNLearner.classifier(data_clas)
learn.load_encoder('enc')
learn.fit(1, 1e-3)

Produces this error:

RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/conda/lib/python3.6/site-packages/fastai/text/data.py", line 278, in pad_collate
    return res, torch.tensor([s[1] for s in samples]).squeeze()
RuntimeError: Could not infer dtype of numpy.int64

![screen shot 2018-10-16 at 11 12 04 pm](https://user-images.githubusercontent.com/9092115/47065762-f6c2dd00-d198-11e8-9f0e-caabcd44bef1.png)

**Comment by dwbressler** [comment]
Apologies, this issue was due to incorrect installation.

**Comment by 0xB10C** [comment]
> Apologies, this issue was due to incorrect installation.

Can you describe how you fixed your incorrect installation? What did you change to make it work? I'm facing the same issue.

**Comment by 0xB10C** [comment]
The example works when installing fastai via PyPi. The example works.

**Comment by xelda1988** [comment]
I have fastai installed via PyPi and I have the same problem:

fastai                          1.0.12
torch                           0.4.1     
torchvision                  0.2.1     
torchvision-nightly      0.2.1

also I had 1.013dev install before, also didn't work.
