### ISSUE TITLE
Bug in the definition of fib3 in lesson3-rf_foundations.ipynb 

### ISSUE THREAD

**Issue by NPann** [fastai/fastai#910]
**Describe the bug**
In fastai/courses/ml1/lesson3-rf_foundations.ipynb, I believe there is a bug in the definition of fib3

```
%%cython
def fib3(int n):
    cdef int b = 1
    cdef int a = 0
    cdef int t = 0
    while b < n:
        t = a
        a = b
        b = a + b
```
Should read:

```
%%cython
def fib3(int n):
    cdef int b = 1
    cdef int a = 0
    cdef int t = 0
    while b < n:
        t = a
        a = b
        b = t + b <-- FIX
```
The timings are marginally impacted.

**Comment by jph00** [comment]
Thanks for spotting that! Any chance you could submit a PR with that change?

**Comment by NPann** [comment]
Done. Thanks for doing what you do.
