### ISSUE TITLE
Documentation links don't link directly to the source methods

### ISSUE THREAD

**Issue by aaronlelevier** [fastai/fastai#920]
**Describe the bug**
When looking up some methods in the [docs.fast.ai](docs.fast.ai), the `[source]` links don't link directly to the method in the source code.

**To Reproduce**
Here are 2 examples. If you click `[source]` it goes to the source file but not exactly to the method definition in the source.

[http://docs.fast.ai/torch_core.html#to_np-1](http://docs.fast.ai/torch_core.html#to_np-1)

[http://docs.fast.ai/torch_core.html#apply_init-1](http://docs.fast.ai/torch_core.html#apply_init-1)

**Expected behavior**
I'd expect the links to go directly to the method definition in the source. There's most likely a bug with how the `[source]` links are being generated.

**Comment by jpparent** [comment]
This might have been on github's side since the links properly point to the correct target (i.e. line in source). Now, some target seem to not be pointing to the right line. This is a different issue it seems.

**Comment by sgugger** [comment]
This comes when we change the source code but forget to run the script to update those links. It's been corrected now.

**Comment by aaronlelevier** [comment]
Ok, I just wanted to let you all know. 

If there's a git tagging script per release then maybe it could also have "generate documentation" step so it's part of the process.

**Comment by stas00** [comment]
It's just running ` tools/build-docs` inside fastai_docs repo and committing the results. We should update http://docs.fast.ai/gen_doc.html

It shouldn't happen on release but much more often than that, since release doesn't freeze the docs.fast.ai website.
