### ISSUE TITLE
conv2d(): argument 'input' (position 1) must be Tensor, not bool

### ISSUE THREAD

**Issue by 674106399** [fastai/fastai#928]
tfms = get_transforms(flip_vert=False, max_lighting=0.1, max_zoom=1.00, max_warp=0., max_rotate=30)                
data = ImageDataBunch.from_df('',df=df, folder='', ds_tfms=tfms, size=224, sep=' ',
    fn_col=2, label_col=3, device=device)
data.normalize()

data.show_batch(rows=3, figsize=(6,6))

learner = ConvLearner(data, model, metrics=[accuracy], callback_fns=ShowGraph, pretrained=False)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-6473a9b9a8b0> in <module>()
----> 1 learner = ConvLearner(data, model, metrics=[accuracy], callback_fns=ShowGraph, pretrained=False)

~/anaconda3/lib/python3.6/site-packages/fastai/vision/learner.py in __init__(self, data, arch, cut, pretrained, lin_ftrs, ps, custom_head, split_on, **kwargs)
     50         meta = model_meta.get(arch, _default_meta)
     51         torch.backends.cudnn.benchmark = True
---> 52         body = create_body(arch(pretrained), ifnone(cut,meta['cut']))
     53         nf = num_features(body) * 2
     54         head = custom_head or create_head(nf, data.c, lin_ftrs, ps)

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/anaconda3/lib/python3.6/site-packages/torchvision/models/resnet.py in forward(self, x)
    137 
    138     def forward(self, x):
--> 139         x = self.conv1(x)
    140         x = self.bn1(x)
    141         x = self.relu(x)

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py in forward(self, input)
    311     def forward(self, input):
    312         return F.conv2d(input, self.weight, self.bias, self.stride,
--> 313                         self.padding, self.dilation, self.groups)
    314 
    315 

TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not bool

model is torchvision.models.resnet101()
data.show_batch() works perfectly, but I cannot initialize the ConvLearner
My Pytorch version is 1.0.0.dev20181019
I've tried to reinstall pytorch, fastai and torchvision

**Comment by 674106399** [comment]
I read the source code of learner.py, and found that parameter, "arch",  should be models.resnet101 instead of models.resnet101() (they are different!!!)

**Comment by Lin-plax** [comment]
> I read the source code of learner.py, and found that parameter, "arch", should be models.resnet101 instead of models.resnet101() (they are different!!!)

Do you mean the resnet101 can not be pretrained?
