### ISSUE TITLE
basic_train.get_preds() does not work when model returns multiple values ...

### ISSUE THREAD

**Issue by ohmeow** [fastai/fastai#947]
Another one that was fixed before (I believe), but is back again when evaluating predictions for an `RNNLearner.classifier` derived model (which returns a tuple that includes document vectors).

When attempting to run:  `basic_train.get_preds(learn.model, learn.data.valid_dl)`

I get:  "TypeError: expected Tensor as element 0 in argument 0, but got tuple"

<img width="1019" alt="screen shot 2018-10-23 at 11 52 40 am" src="https://user-images.githubusercontent.com/14000/47383929-a11b9280-d6ba-11e8-9f6c-17a9c73e92f6.png">

**Comment by sgugger** [comment]
You should use learn.get_preds so that the callbacks of the learner get passed (and the output be reduced).

**Comment by ohmeow** [comment]
Ah ok ... that works.

But shouldn't the behavior be the same in terms of reducing the output?  If I deploy my model into production, I imagine I won't need/want a `Learner` for inference and would want to use the `basic_train.get_preds()` against it.

**Comment by sgugger** [comment]
You will need to write your own script for production anyway ;). You can pass callbacks to get_preds, so if you really need that function, just add a callback that treats your output to keep only the first element.

**Comment by ohmeow** [comment]
I didn't realize that could be done with a `Callback` ... but unless I'm wrong and/or this can be improved, yah ...

```
class PredictionsFromTupleCallback(Callback):
    def on_loss_begin(self, **kwargs:Any)->None:
        "Useful for cleaning up things and saving files/models."
        #pdb.set_trace()
        return kwargs['last_output'][0]
    
cbh = CallbackHandler(callbacks=[PredictionsFromTupleCallback()], metrics=None)
basic_train.get_preds(learn.model, learn.data.valid_dl, cb_handler=cbh)
```
