### ISSUE TITLE
Question: Why does T() avoid to_gpu() when dtype==np.float32?

### ISSUE THREAD

**Issue by MattKleinsmith** [fastai/fastai#96]
I've noticed that for float32 numpy arrays I need to call .cuda() despite calling V. This isn't an issue, but I'm wondering why this is. Does it have something to do with .cuda()'s async argument?

---

```python
def T(a):
    if torch.is_tensor(a): res = a
    else:
        a = np.array(np.ascontiguousarray(a))
        if a.dtype in (np.int8, np.int16, np.int32, np.int64):
            res = torch.LongTensor(a.astype(np.int64))
        elif a.dtype in (np.float32, np.float64):   #  <--------------
            return torch.FloatTensor(a.astype(np.float32))   #  <--------------
        else: raise NotImplementedError
    return to_gpu(res, async=True)
```
https://github.com/fastai/fastai/blob/master/fastai/core.py#L17

V -- > V_ --> T -- > to_gpu --> cuda, for numpy arrays that don't contain floats.

---

Meta: Let me know if I should ask questions like these on [forums.fast.ai](forums.fast.ai) instead of creating a github issue.

**Comment by jph00** [comment]
Funnily enough I just noticed that and fixed it. Will push shortly.
