### ISSUE TITLE
LRFinder doesn't work with negative losses

### ISSUE THREAD

**Issue by r4m0n** [fastai/fastai#962]
LRFinder aborts the evaluation whenever it encounters negative losses, which can happen on some metrics. The problem is due to the way loss increase is being tested for [here](https://github.com/fastai/fastai/blob/master/fastai/callbacks/lr_finder.py#L33).

Don't know which would be the best way to detect a good stopping point. Using self.best_loss + 3*abs(self.best_loss) would immediately fix the problem, but I don't think the resulting value makes much sense for any losses that can go below 0. Maybe storing the loss as it was at the start and stopping when going over it?

**Comment by sgugger** [comment]
I think the right way to address that is to add a parameter that prevents that early stopping. Will code this sometimes today.

**Comment by sgugger** [comment]
Added an argument `stop_div` in `lr_find()`. Put it to False and the function won't abort.
