### ISSUE TITLE
save destination of untar_data does not the docs or the return object

### ISSUE THREAD

**Issue by wAuner** [fastai/fastai#964]
**Describe the bug**

System: Linux Mint 19
installed via conda, GPU version

I just used `untar_data(URLs.PETS)` to download the pets dataset. According to the [docs](https://docs.fast.ai/datasets.html#untar_data) the dataset should be downloaded to `~/.fastai/data/`.

From the docs:
> By default, data will be downloaded to ~/.fastai/data folder.
> Configure the default data_path by editing ~/.fastai/config.yml.

But it doesn't. First of all, I don't have a .fastai directory.
After the data is downloaded, the function returns a PosixPath object

    PosixPath('/home/username/anaconda3/lib/python3.6/site-packages/fastai/../data/oxford-iiit-pet')

So I looked at that path, but it wasn't there either. Turns out the data is saved at

    /home/username/anaconda3/lib/python3.6/site-packages/data

Is this a bug or am I missing something?

Btw great that you're using type hints, that is very helpful. Would be even better if type hints were also included for the return values.

**Comment by sgugger** [comment]
You don't have the latest version of fastai, this is why you see a different behavior.

**Comment by wAuner** [comment]
so what's the best way to get the most up to date version? I installed today via conda and got version 1.0.6. Just cloning the repo and then link to it? or does that limit some functionality?

**Comment by sgugger** [comment]
You should update your conda since the last version is 1.0.12, then 
`conda update fastai`.
There are more instructions [here](http://course-v3.fast.ai/) depending on your platform.

**Comment by wAuner** [comment]
well that's the point. when you install the package via conda you don't get the most recent version. I installed today and got 1.0.6. When I try to update with `conda update -c fastai fastai`, I always get it is already up to date. Although it shows that there are newer version available on conda.

```
conda search -c fastai fastai
Loading channels: done
# Name                  Version           Build  Channel
fastai                    1.0.2            py_1  fastai
fastai                    1.0.3            py_1  fastai
fastai                    1.0.4            py_1  fastai
fastai                    1.0.5            py_1  fastai
fastai                    1.0.6            py_1  fastai
fastai                    1.0.7            py_1  fastai
fastai                    1.0.9            py_1  fastai
fastai                   1.0.10            py_1  fastai
fastai                   1.0.11            py_1  fastai
fastai                   1.0.12            py_1  fastai
```

I guess there is something wrong with the upload to conda?

**Comment by sgugger** [comment]
You have to uninstall and reinstall conda then.

**Comment by stas00** [comment]
@wAuner, please let's move this discussion [here](http://forums.fast.ai/t/fastai-v1-install-issues-thread/24111).  The 1.0.12 should have fixed that problem, but clearly it didn't. So please post the summary of the issue and the output of `python -c "import fastai; fastai.show_install()"` in that thread and we will take it from there.
