### ISSUE TITLE
RuntimeError: cuda runtime error (59)

### ISSUE THREAD

**Issue by ben0it8** [fastai/fastai#972]
I've encountered some inexplicable behaviour when replicating the very same steps as in the examples/text notebook on a different dataset.

RNNLearner.language_model: initializing, fine-tuning and saving the encoder works as expected
RNNLearner.classifier: initializing and loading the encoder works, calling fit_one_cycle gives:

> RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch-nightly_1540409230384/work/aten/src/THC/generic/THCTensorCopy.cpp:20

**Additional context**
Weirdly, if I go back and initialize RNNLearner.language_model again, it sometimes raises the same error
Also, calling fit on the classifier produces a different error:

> RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch-nightly_1540409230384/work/aten/src/THCUNN/generic/ClassNLLCriterion.cu:111

I'm having CUDA 8.0 installed with cuDNN 7, pytorch-nightly build py3.6_cuda8.0.61_cudnn7.1.2_0 and fastai 1.013.

Full traceback:
![screen shot 2018-10-25 at 13 51 53](https://user-images.githubusercontent.com/11842615/47498364-55edb500-d85d-11e8-855a-581a12097c79.png)
![screen shot 2018-10-25 at 13 52 33](https://user-images.githubusercontent.com/11842615/47498374-5be39600-d85d-11e8-9dcb-9e281ab2767d.png)

**Comment by sgugger** [comment]
Please search the [forum](https://forums.fast.ai/) before posting this issue. You have to lower the batch size to fit the model in your GPU, this is not due to the library.

**Comment by ben0it8** [comment]
I don't think that this is a memory issue since PyTorch throws a different runtime error for that and I have 16GB of GPU memory...(but, I tried anyways lowering the bs and got the same error obviously). I understand that this is not an issue strictly due to fastai, but it is somehow related and I never encountered this with PyTorch before.

**Comment by sgugger** [comment]
Sorry, I misread. Again please [use the forum](https://forums.fast.ai/) where this kind of error has also been discussed. Can't help you without the code as it likely comes from a bad index error of a tensor on the GPU. While posting on the forum, please try to have the same thing run on the CPU as it'll return a clearer error message.
