### ISSUE TITLE
`download_images` bug

### ISSUE THREAD

**Issue by WNoxchi** [fastai/fastai#978]
**Describe the bug**

`download_images` either fails silently or throws a `BrokenProcessPool` error when called to download images from urls. `download_images` can be made to start working as intended, by first running `download_url`. This happens when following along with [course-v3/nbs/dl1/download_images.ipynb](https://github.com/fastai/course-v3/blob/master/nbs/dl1/download_images.ipynb) with your own set of urls.

**To Reproduce**

See gist: [fastai_bug_download_images_20181026.ipynb](https://gist.github.com/WNoxchi/ced5ad2c8248a152ed1ae5334b742290)

**Expected behavior**

`download_images` should download (or attemp to) all images pertaining to the urls in a provided filepath, to a specified folder.

**Screenshots**

See gist above.

**Additional context**

fastai developer install, updated 20181026 at 02:26 EST; courses-v3 folder updated soon before.
System: macOS 10.14.

**Comment by jph00** [comment]
Well that's odd! Not sure what's going on there. Try using a debugger and removing the use of the process pool to if you can find the actual error that's causing this.

**Comment by WNoxchi** [comment]
It looks like the lack of an error is causing this; as if `ProcessPoolExecutor` needs something to hit it to wake up.

I made another notebook gist: [nbviewer link](https://nbviewer.jupyter.org/gist/WNoxchi/952a85be92619f3358341ca74f153a12) to try and document & reproduce this from start to end.

What happens is I run `download_image` with `overwrite=True`, and a folder (not filename) passed as `dest`. This throws a directory error which I catch. _Then_ `ProcessPoolExecutor` does its job. Though not in the notebook, I tested that adding this try/except to the source code function works.

What I haven't tested is more of what's going on with `download_url`. I'll check it out more. It confused me for a bit when I was trying to replicate the bug/fix by returning NoneType to an assignment... but `download_image` calls it with `overwrite=True` so that shouldn't be it.

I also noticed after importing * from fastai and fastai.vision,`download_image` and `as_completed` (from concurrent.futures) are not available, and have to be imported to be used in the notebook -- I don't know if that has any effect.

**Comment by discdiver** [comment]
Same issue on mac. Same manual fix worked.

**Comment by jph00** [comment]
Can you try with max_workers=0 and show what error you get?

**Comment by WNoxchi** [comment]
I just had a case where max_workers=0 got `download_images` to work, where it wasn't working before (default settings). Haven't tested it thoroughly, but popped up just now (going through lesson2-download notebook).

**Comment by sgugger** [comment]
Closing this since the option apparently works to fix the bug.

**Comment by f0k** [comment]
> Closing this since the option apparently works to fix the bug.

Would be nice if it was working out of the box, though. Is it really needed to download the images using multiprocessing, rather than multithreading? If not, passing `threadpool=True` in https://github.com/fastai/fastai/blob/0e01131/fastai/vision/utils.py#L37 should make it work for all platforms.

**Comment by jph00** [comment]
This was an issue for fastai v1. If there's still an issue with v2 or fastbook, please create a new issue and at-mention me (or create a PR with the `threadpool=True` workaround). Many thanks!
