### ISSUE TITLE
untar_data issue with follow redirects and long filenames

### ISSUE THREAD

**Issue by arunoda** [fastai/fastai#983]
**Describe the bug**
`untar_data` throws errors when dealing with files with redirects and has long and weird names (due to AWS signing, etc)

**To Reproduce**
We can use GitHub releases to store datasets like this: https://github.com/arunoda/fastai-courses/releases
Then our URL looks something like this: https://github.com/arunoda/fastai-courses/releases/download/fastai-vehicles-dataset/fastai-vehicles.tgz

But when it's downloading, it'll redirect to a s3 url. 
Then there are some errors.

**Expected behavior**
Should be able to download the dataset.

**Comment by sgugger** [comment]
I'm not sure we can cover all cases of downloads. `untar_data` is primarily intended for the fastai datasets and its behavior elsewhere is untested. Can you use `download_url` to download your dataset?

**Comment by arunoda** [comment]
> I'm not sure we can cover all cases of downloads
Oh yes. I agree.

@sgugger but follow redirects could be something simple to add. 

I hope `untar_data` has `fname` and `dest`. So we can use them to save the file and extract without looking at the URL.

**Comment by jph00** [comment]
> @sgugger but follow redirects could be something simple to add.

Would you be able to provide a PR with this functionality? That would be great!

**Comment by arunoda** [comment]
@jph00 Why did you close this issue.
Not exactly sure how we manage issues here, but I think the issue should be opened until the issue resolves.

BTW: Here's the pseudo code which works for almost all the datasets:

```python
import os
import subprocess

def exec(commands, cwd=None):
  FNULL = open(os.devnull, 'w')
  cp = subprocess.run(commands, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True)
  
  if cp.returncode != 0:
    raise Exception(cp.stdout)

def get_data(url, filename):
  homedir = os.getenv('HOME')
  datadir = f'{homedir}/userdata'
  tmpdir = f'/tmp/{filename}'
  tarfile = f'{tmpdir}/data.tgz'

  exec(['rm', '-rf', tmpdir])
  exec(['mkdir', '-p', tmpdir])
  exec(['curl', '-L', url, '--output', tarfile])
  exec(['tar', 'xzf', tarfile], cwd=tmpdir)
  exec(['rm', tarfile])

  exec(['rm', '-rf', datadir])
  exec(['mkdir', '-p', datadir])
  exec(['mv', tmpdir, datadir])
  
  return f'{datadir}/{filename}'


dataset_url = 'https://github.com/arunoda/fastai-courses/archive/fastai-vehicles-dataset.tar.gz'
print(get_data(dataset_url, 'name'))
```

**Comment by jph00** [comment]
I assumed you were going to do a PR so we can move the discussion there.

**Comment by arunoda** [comment]
@jph00 I am not familiar with the codebase yet. I thought it's easy for someone who knows about it do that change.
