### ISSUE TITLE
Error rendering Enclosure plot in ml1/lesson2-rf_interpretation

### ISSUE THREAD

**Issue by mrw34** [fastai/fastai#986]
**Describe the bug**
a1b5152 modified `plot_pdp` to accept 2 arguments rather than 3. This breaks the following code in lesson2-rf_interpretation.ipynb:
```
plot_pdp(['Enclosure_EROPS w AC', 'Enclosure_EROPS', 'Enclosure_OROPS'], 5, 'Enclosure')
```

**To Reproduce**
Run the latest `lesson2-rf_interpretation.ipynb` and observe error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-56-75a1bc515f1f> in <module>
----> 1 plot_pdp(['Enclosure_EROPS w AC', 'Enclosure_EROPS', 'Enclosure_OROPS'], 5, 'Enclosure')

TypeError: plot_pdp() takes from 1 to 2 positional arguments but 3 were given
```

**Expected behavior**
A ICEplot for Enclosure is rendered, as shown in the rendered version of [lesson2-rf_interpretation.ipynb](https://github.com/fastai/fastai/blob/master/courses/ml1/lesson2-rf_interpretation.ipynb)

**Screenshots**
<img width="1121" alt="screenshot 2018-10-27 at 14 26 20" src="https://user-images.githubusercontent.com/1101318/47604653-64220980-d9f4-11e8-9d33-6defb455d765.png">

**Comment by jph00** [comment]
Thanks  - I'll close this so we can discuss on the PR.
