### ISSUE TITLE
wish list:  add labels to top of graph

### ISSUE THREAD

**Issue by reshamas** [fastai/fastai#998]
file name:  `fastai/fastai/vision/learner.py`
function name:  `def plot_top_losses`
`interp.plot_top_losses(9, figsize=(15,11))`  

The numbers at the top of the images represent, in this order:  
- prediction label
- actual label
- loss
- probability it was predicted

Can we add labels to these 4 items to a **wish list** somewhere?
(even a title for the plot with that info would do)

<img width="482" alt="cherries_labeled" src="https://user-images.githubusercontent.com/2507232/47622468-80e53c80-dadb-11e8-8de5-c2d78dc21698.png">

**Comment by sgugger** [comment]
I think [this](https://github.com/fastai/fastai/pull/1001) solves this issue.
